### ISSUE TITLE
Re-release map Desert Needle with offending widget removed

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1001]
Mapoptions info disappears at gamestart.
Until then the mapoptions Info & Commander-Selector are both in center of screen and overlap:

![bla](https://cloud.githubusercontent.com/assets/3044855/9358978/15cdc608-468f-11e5-8b0e-69990410e803.jpg)

Not picture here but the countdown ("Starting in 3,2,1") also overlaps with mapoptions.

**Comment by GoogleFrog** [comment]
Map Options is a map widget. The map should be unfeatured and fixed if anyone really likes the map.

**Comment by KingRaptor** [comment]
Not sure if should be unfeatured, but anyway close as "not our jurisdiction"?

**Comment by knorker** [comment]
map is http://zero-k.info/Maps/Detail/30318
overlapping GUI elements = clearly a bug.

**Comment by KingRaptor** [comment]
But this bug is caused by a map 
* that wasn't made for/by ZK
* which we have no control over (beyond making it go away)
* fixing it would require moving ZK UI elements that are otherwise perfectly fine where they are

**Comment by GoogleFrog** [comment]
This is a real bug because we endorse that map. The easy fix is to remove the map. The harder one is to re-release it. The evil fix is to make a widget which disables this maps widget.

**Comment by Anarchid** [comment]
I will degrate Desert Needle to `supported` for now.
