### ISSUE TITLE
Do not use LOS view during pre-game (startpos/com select/prequeue)

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1002]
LOS view gets automatically enabled.
In pregame stage there are no units yet = No LOS.
So while picking start positions etc the whole map looks dark/ugly

**Comment by Licho1** [comment]
Excellent idea!

**Comment by Orfelius** [comment]
Why was this closed it is a really good idea. Consider that this is one of the first things a newb is gonna see after getting into the game.

**Comment by knorker** [comment]
it was fixed, was just forgotten to mention in commit so it did not autolink it in issue
( https://github.com/ZeroK-RTS/Zero-K/commit/32b5c909fae716410c0576e9750175765fef8827 )

**Comment by Orfelius** [comment]
Ah ok then :)
