### ISSUE TITLE
Crash in unit_refuel_pad_handler.lua

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#1008]
Battle replay: http://zero-k.info/Battles/Detail/371261
There were several Reefs in this battle.

[f=0033784] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_refuel_pad_handler.lu..."]:251: attempt to perform arithmetic on local 'turnCircleRadius' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_refuel_pad_handler.lu..."]:251: in function 'CircleToLand'
	[string "LuaRules/Gadgets/unit_refuel_pad_handler.lu..."]:525: in function 'UpdatePadLocations'
	[string "LuaRules/Gadgets/unit_refuel_pad_handler.lu..."]:533: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
	(tail call): ?

The error was spammed for the rest of the battle.

**Comment by GoogleFrog** [comment]
Attach infologs!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by GoogleFrog** [comment]
FFS the replay is broken and all I want is the infolog from it!!!!!!!!!!!!!!

**Comment by ashdnazg** [comment]
https://dl.dropboxusercontent.com/u/204076271/20150820_214208_spiders%20web_100.zip

**Comment by ashdnazg** [comment]
IIRC the infologs had this error repeat like mad

**Comment by GoogleFrog** [comment]
Infologs can have initial errors at the top which then cause the other spam.

Fixed probably https://github.com/ZeroK-RTS/Zero-K/commit/b8cf524ba11052c18ecc6413e6aaa79a2139b452
