### ISSUE TITLE
Disabled units can be built using Initial Queue

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#1016]
Units disabled using "setoption disabledunits=unitname" can be queued in pregame using Initial Queue, and they get built without problems.

To test use "setoption disabledunits=armsolar". Before placing start position use command menu to queue a few Solars with shift. Notice the Solar button is not grayed. Now start the game and watch the comm building Solars... 
Bring command menu again - notice the button is now correctly grayed and no more Solars can be placed.

**Comment by sprunk** [comment]
Also applies to CAI as far as I know.
