### ISSUE TITLE
Better naming for Sumo weapon toggle instead of "on / off"

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1018]
Sumo can toggle between attracting units with its beam or repulsing them.
The UI switch for this is labeled "on/off" and uses on/off graphic, which does not represent the function.

**Comment by KlonZK** [comment]
problem seems to be that icons/tooltips are the same for all units and the on/off state for newton type units is the same on/off state as for any other unit.

**Comment by ashdnazg** [comment]
this can be closed

**Comment by sprunk** [comment]
What about GF's remarks from https://github.com/ZeroK-RTS/Zero-K/pull/2560#issuecomment-336775252 ?

**Comment by ashdnazg** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/c9db22be2f229701abc99ddde77fc5abd1e5ccdf
