### ISSUE TITLE
Nuke missile bugged - falls straight down at about half of the maximum range.

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#1019]
Can happen in very long maps. Happened in this game:
http://zero-k.info/Battles/Detail/371866  (about 20 minutes in)

I built 4 nuke silos at the very end of the map and when they were ready I fired them at the other end of the map. After flying about 60% of the distance all 4 four missiles at the same time turned downwards and flew vertically into ground (hitting our forward base...). Same happened with another 2 missiles fired by Burp.

**Comment by ArchShaman** [comment]
Sounds like they timed out midflight producing some lulzy effects.

**Comment by KingRaptor** [comment]
(Most likely) Fixed in a785d2b582d8b8e6639b1b6f577aa225664f38a6
Thanks!
