### ISSUE TITLE
Command Panel doesn't enable building hotkeys when clicking on a building panel

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#1024]
While using a hotkey (default Z,X,C,V) to enter a building production tab enables building hotkeys properly, clicking into the same tab does not. The hotkeys should always be enabled for the chosen tab.

**Comment by GoogleFrog** [comment]
This was intended but could be changed.

**Comment by GoogleFrog** [comment]
Added an option https://github.com/ZeroK-RTS/Zero-K/commit/4cc5387f2cc1e721ca45346895ae5cac5b3ba387

**Comment by GoogleFrog** [comment]
It is disabled by default as a test and to show that it can be implemented. It effectively does not exist while disabled by default so there is still a decision required.
