### ISSUE TITLE
drones cannot be captured

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1032]
dominatrix cannot capture drones but aims them... so it is kinda useless in that moment.
It would be nice if it can capture drones though, would be one more funnel counter

**Comment by GoogleFrog** [comment]
Except drones without a Funnelweb die. Would captured drones just die? Perhaps they could just attack their parent Funnelweb and die if it does? That last one is hardest but probably fits best.

**Comment by CarabusX** [comment]
Even if they just die after getting capped, it would be still infinitely better than being completely immune to capture. (who did think it is a good idea?)
