### ISSUE TITLE
disable Water Level and Terrain Speed Boost modoptions until Spring 101.0

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#1043]
According to http://zero-k.info/Forum/Thread/20018#141859 these modoptions can cause desync because of how Spring 100.0 handles path cache when Lua modifies the map. These modoptions should be disabled until Spring 101.0 gets released which supposedly fixes the path cache desync.

**Comment by GoogleFrog** [comment]
Water level is gimmicky and can be disabled. Speed boost is important because maps with speed boost are often unplayable. My solution would be to change the speedboost values in frame 1. This should prevent desync as the modification would be treated as an on-the-fly change.
