### ISSUE TITLE
endgame graph overlapped by other widgets

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1047]
Some widgets can overlap the endgame graph.
Here the mouse on the graph but behind the graph there is a radar tower:
The unit tooltip shows up on top of the graph.

![bla2](https://cloud.githubusercontent.com/assets/3044855/9852062/796fb01e-5afc-11e5-8546-33feec552329.jpg)

The metalspot info ("2.04 meta per spot") also shows through the graph window. Maybe more widgets too.

**Comment by Anarchid** [comment]
Sounds like it fails to consume the cursor. Probably needs a `false` somewhere.
