### ISSUE TITLE
Units attracted by sumo go through it instead of colliding against it

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K#1059]
Observe, as Sumo the Insubstantial pulls two halberds and a glaive into itself! Watch as natural law is overcome, when they pass right through him!

http://zero-k.info/Battles/Detail/376607

**Comment by GoogleFrog** [comment]
I think that is just how unit-unit physics works.

**Comment by sprangg** [comment]
Units thrown by sumo go through at least sumo and detriment. They also go through zenith, but collide with zenith wreck. Collisions also happen with both singularity reactors and their wrecks.

**Comment by sprangg** [comment]
Ok, so it looks like the model file's colvol (grey color) is used for unit-to-unit collisions like sumo throws. Whereas the game-side override colvol (purple color) is not used for this. Sumo appears to have some tiny model file colvol and that's why units go through it, whereas warlord for example has a sizeable model file colvol for units to collide with.

Warlord and sumo side by side, with colvols visible:
http://prntscr.com/8jdr3a

**Comment by sprunk** [comment]
Sumo has the gray vol exactly the same as the purple one which is why the gray one doesn't seem to appear.

**Comment by sprangg** [comment]
Yeah, it's not the grey box. For some other reason, warlord doesn't let units through its central part where the grey colvol is, but lets through in the tips of the ship.

**Comment by sprangg** [comment]
I'm willing to let sumo stay magical, this case seems to me too mysterious to solve.
