### ISSUE TITLE
Scythe animation

### ISSUE THREAD

**Issue by SouLTaKeR1** [ZeroK-RTS/Zero-K#1063]
The animation and the range of scythe does NOT match its weapon in reality.

The weapon scythe has is more of a halberd than a spear.

the way its being used is as a spear.

for halberd it requires 2 hands in order to attack your opponent because the edge top is heavy.
if you zoomed into scythe while attacking you will see his weapon flows up making him hold the weapon on almost the bottom end of his weapon's shaft, WITH ONE HAND, which makes the attack complete unbalanced.

suggesting to look at it with needing to follow either one of the 3 options

1- changing the weapon model to something fittable with its current scheme.
2- reduce the range, i dont know how much of range nerf it needs to receive inorder to match 'reality'.
possibly 10% of range being nerfed is enough.

3- if you really dont care about such details and you do not really care about that level of realism into game then please ignore everything i said.

redo the animation of it would be too diffecult, i tried, you're limited with only the upper body+and hands, if unit is moving you cannot use the legs which is the main extension of any kind of shaft kind of weapons.

**Comment by Anarchid** [comment]
You can make it look more realistic by turning it into a slash attack in which the momentum is braked by continued rotation.

**Comment by SouLTaKeR1** [comment]
in that case i cannot animate it with 2 hands unless u set 2 type of attack-range for each animation, with out the legs simply scythe cannot reach to its target without extending the pole and using only one hand.

it will really look off.

**Comment by Anarchid** [comment]
Triggering different animations for different distances to target would be easy and nice as well, so i can definitely do that! :)

**Comment by SouLTaKeR1** [comment]
here is what you've asked but couldnt find you online.

https://gyazo.com/7ff52d4a0bc9e8c8ce3802ae38bbe417

so to put things on table, the solar hitbox is different from any other unit so thats k, lets just imagin its a big square instead triangle.

see how scythe extends the pole till very tip of it and attacking at his 'max range' ? i made it show the attack range circle along with it.
there is 2 problems you can see in that image. Halberd mainly used to aim at the crotch/knees/areas around the bottom of chest, this one is being used to slash from above on the head with completely what should be offbalance in real life if you use the weapon like that.

second one even though i said we can imagin the solar a big box instead triangle, u can still see even with the extension of his weapon the target still too far.

So now lets put the animation into him holding it by 2 hands.

https://gyazo.com/39ccc5f756a1dedccd112a92bbc08279

this might be inaccurate distance but we can ETA it.

on the left the scythe holding it with 2 hands is already rotated with his chest/shoulders and able to do slash to hit his target with 'almost' the tip.

i would imagin the range is more further than the right scythe appear to be which is why i think 2 hands would really look off.

**Comment by GoogleFrog** [comment]
I'm leaning towards (3). The animation does not need to match reality, it just needs to fit game logic. I presume the weapon is a halberd because it is cooler than a spear. My main problem with the animation is that it does not reach its max range, this is not a large problem though.

If you work on it keep these things in mind:
 * The animation has to work while the unit is moving. It cannot involve the hips or legs.
 * The animation should be visible, a small poke or swipe may be more realistic but is not useful from a UI perspective. People should be able to tell when an attack occurs from normal play distance.
 * The animation should be unambiguous. Similar to the previous point, it should be clear when the animation occurs and what is being attacked. So it should be short and directed.

The current animation only fails in terms of ambiguous target.

**Comment by SouLTaKeR1** [comment]
Thanks, thats kind of answer I'm seeking, if its ought to be introduced, the 2hands wielding then we going to approach it with double attack-range approach, I'm guessing ill just make the scythe current attack animation exactly the same but nicer/smoother.

**Comment by sprunk** [comment]
Is there progress?

**Comment by SouLTaKeR1** [comment]
Well yes, I've done all the animation needed, rest was on anarchid to convert it into the game or so. :)

Not sure what happen to it or if he did or not.

Date: Mon, 1 Feb 2016 12:55:35 -0800

**Comment by Anarchid** [comment]
I'll upload the stuff i have currently later today.

**Comment by Anarchid** [comment]
"Today" turned into "this week" but here are the files: https://dl.dropboxusercontent.com/u/19320633/scythe_animations.7z

This contains the animations, one per file. The Scythe model should be exportable from scythe_bindpose .blend into a .dae directly, and all animations can be viewed in blender by opening and playing the appropriate files.

The TODO here is to convert the animations into lua script snippets with requisite keyframes and compile them into a full animation script. Ideally, this also should include the moving of ConstructSkeleton and PlayAnimation functions from dynstrike.lua into a separate animation system include.

**Comment by SouLTaKeR1** [comment]
Nice, I'll get to see them soon then

Date: Sun, 7 Feb 2016 09:52:17 -0800

**Comment by sprunk** [comment]
Is there progress?

**Comment by sprunk** [comment]
Seems safe to say there isn't.
