### ISSUE TITLE
Minimap appears too dark on many maps

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1067]
Default minimap is barely visible and not useful for navigation.
Stuff outside los should be more visible.
http://i.imgur.com/5ChsgoA.jpg

Map itself should also be brighter.
MAp is Fetid Marsh 05

**Comment by Licho1** [comment]
It's actually two problems
1) fog brightness default value is too low
2) minimap does not render sea properly

**Comment by GoogleFrog** [comment]
Whether the fog brightness, minimap brightness and minimap sea is set correctly is largely up to the map. We should pick maps which do it correctly.
