### ISSUE TITLE
COFC - Zooming in all the way on deep sea maps (Such as Inculta Wet) causes crash

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1072]
You can go under the terrain and it will cause a crash.

Steps to reproduce:
0.) !map inculta wet
1.) zoom as far in as you can.
2.) you're under the terrain!
3.) Spring crashes.

**Comment by ArchShaman** [comment]
I can't get any errors from the infolog... it's pretty weird.

Not sure if I should mantis this.

**Comment by dvr333** [comment]
I realize it's been a while, but test again with the latest COFC. I'm pretty sure the tiltzoom rewrite fixed all the water related zooming bugs.

**Comment by sprunk** [comment]
7286a5eec7e7a357183657dedf29aa24e55e980a
