### ISSUE TITLE
Consider removing Venom real damage for Flea synergy

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1078]
Consider increasing Flea range and removing Venom damage, for elegant synergy between the two:
- Longer ranged flea will no longer get inside Venom AoE, making it usable as its damage dealer.
- Venom not having damage means that fleas that do accidentially get inside the AoE won't die.

Also helps in other areas:
- Flea range would help against tedious micro of moving them away from exploding stuff such as windgens during raids.
- Venom lightning is somewhat inconsistent with other lightning (has both AoE and real damage) which removal of real damage fixes.

**Comment by GoogleFrog** [comment]
This sounds good by itself. My worry is with high level micromanagement of flea balls to kill other raiders (such as Glaives).

**Comment by sprunk** [comment]
Preventing Flea from getting inside Venom AoE is sufficient to fulfil point 1 and thus by extension 2 and 4 so something other than range could also be tried.

For example pathing changes such as brake rate, or tactical AI which makes sure they keep away from targets. Range was just the simplest solution and had point 3 as a side effect.

Alternatively if killing other raiders becomes problematic some other value could be tweaked (health? The main affected raiders would be Glaive and Bandit who in turn are the ones with low enough alpha to benefit from a change here).

**Comment by GoogleFrog** [comment]
The potential problem with Flea vs Glaive is outranging. Health would not be a fix here (with good micro).

**Comment by Anarchid** [comment]
Since we're on a modern engine, the option of changing Venom to chain lightning mode instead of naked AOE could also be considered. It's a lot less elegant than flea range, though.

**Comment by sprunk** [comment]
Currently Flea has 140 range while Glaive has 185. It can't be equal due to different projectile speeds but I think there is some leeway.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/7b94eb6f83cf5e2a51586df9bbcd24dff62a087e

Venom damage still remains.

**Comment by Anarchid** [comment]
Is this ticket still relevant with all that has happened in 2018?

**Comment by sprunk** [comment]
Venom damage is still inelegant and teamkills fleas attempting to damage stunned units.

**Comment by sprunk** [comment]
Venom real damage was recently increased which is the opposite direction of removal ( a944ea9c55e6031b7ed53c8551bd56c2a4b5703f )
