### ISSUE TITLE
Cons dont patrol properly

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1098]
1) have strider hub building a dante
2) take cloak cons and have them patrol nearby

-> if they are on "hold pos" stance (default) they won't assist dante.

Is this supposed to happen? I don't think so.

**Comment by sprunk** [comment]
This is engine behavior. There are other undocumented things, for example patrolling cons on "Maneuver" stance will assist your own fac but not ally fac.

**Comment by GoogleFrog** [comment]
We can't do much about this and I feel it is dangerous to ask for an engine change. The engine devs would look at the movestate/assist rules, see that they are arbitrary and then do something to them. The rules are quite arbitrary but we like most of them.
