### ISSUE TITLE
Change fac insert to Space

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1099]
See Licho's comment here https://github.com/ZeroK-RTS/Zero-K/pull/1094#issuecomment-148356702

**Comment by GoogleFrog** [comment]
I don't think it would be a good change. It is awkward to hold Space and Ctrl at the same time. The common combinations are Shift + Space and Shift + others,

**Comment by sprunk** [comment]
Licho's argument is consistency with fac insert so perhaps fac insert could instead be made space?

**Comment by GoogleFrog** [comment]
Yes, fac inset with space is the way to go. If you want to provide reverse compatibility and confusing duplication Alt could also be insert for factories.

**Comment by Skasi** [comment]
Space is used for tooltips though. Would they be moved to Alt+click?

**Comment by Licho1** [comment]
Told you it should be alt everywhere.. alt for command inserts too and space for alt mode..

**Comment by Licho1** [comment]
Also its genre standard, many use alt to insert into queue, none use space.. 
so please ALT

**Comment by GoogleFrog** [comment]
There are games which allow you to insert into queue???

**Comment by Licho1** [comment]
Yeah, i have seen that in other games, i think sins of solar empire had alt to insert into build queue beginning.

**Comment by GoogleFrog** [comment]
I think this didn't happen. Especially with the design of the factory hotkey layout.

**Comment by mtroyka** [comment]
This isn't practical, given the number of different hotkey mods there are. Factory queues and worker queues are fundamentally different and have different requirements, and there aren't enough keys on anyone's keyboards to make them consistent with each other.

**Comment by Licho1** [comment]
Imo if both factory queue and worker queue support insert, it should be the same key regardless what key it is.
Argument that there is not enough keys is void since we do have this feature, it's just about making both more consistent if possible.
Reopening for further thinking.

**Comment by sprunk** [comment]
Currently SPACE is consistently stats window:
 * fac buildpic + ALT = insert
 * fac buildpic + SPACE = stats window
 * existing unit + SPACE = stats window

So a change that doesn't break this would be to move stats window to ALT in both cases:
 * fac buildpic + SPACE = insert
 * fac buildpic + ALT = stats window
 * existing unit + ALT = stats window

I think ALT is free for use on existing units.

**Comment by GoogleFrog** [comment]
ALT is not free, it modifies most commands somehow and is often used with Shift and Ctrl. You can't press Ctrl + Space + Shift as easily as Alt.

**Comment by sprunk** [comment]
Closing due to lack of free modifiers.

@Licho1 feel free to reopen if you come up with a decent modifier key replacement for stats window.
