### ISSUE TITLE
Combined metal/energy icon looks too much like energy

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1114]
Atm cost is represented using icon which has energy overlaid over metal bar.
Problem is metal is by far more important/interesting and when you look at the icon you barely see the bar.

Revert back to use only metal icon, this is just confusing.

**Comment by sprunk** [comment]
Nobody else seems to have complained.

**Comment by Licho1** [comment]
Irrelevant.

**Comment by sprunk** [comment]
How so? "Looks too much like energy" is a subjective experience thing, I can see the metal bar behind it fine.

**Comment by Licho1** [comment]
Cost should just show metal. Thats what is interesting. Energy is not even meant to be storable, its operating necessity.

**Comment by GoogleFrog** [comment]
Cost cannot be just a metal bar while it appears alongside metal income in unit tooltips, also shown with a metal bar.

**Comment by Licho1** [comment]
It can be! 
There was a distinguishement using:
- symbol prefix (+,- vs nothing)
- color (red/green vs teal or other neutral color)
