### ISSUE TITLE
Felon: don't target drains unless explicitly ordered

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1116]
Felon already considers drains (like Razor or Dirtbag) as the last priority for targeting but when they are the only things left it will still drain itself onto them.

The proposal is to make Felon only attack them when excessing charge or when explicitly ordered to.

**Comment by Licho1** [comment]
Make it target them when charge is full

**Comment by KlonZK** [comment]
can it change priority dynamically when the drain is in open state?

**Comment by mtroyka** [comment]
AFAIK all units already disprefer shooting at armored targets. You can watch units do a dance between open/closed solars as proof. On the other hand, forcing users to use force-fire vs armored is also the same as making felons ignore Crabes, which is suicidal.

**Comment by Anarchid** [comment]
People with enough APM to manually target solars and crabes have enough APM to put felon on holdfire or return fire.

**Comment by sprunk** [comment]
Crabe is not necessarily considered a drain since it does stuff when closed.

**Comment by GoogleFrog** [comment]
Covered here: https://github.com/ZeroK-RTS/Zero-K/issues/2789
