### ISSUE TITLE
manual aim on terraformed spike or whatever does not work

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1118]
the unit will walk to that spike instead of shooting it. I know thats maybe a problem because it cannot shoot into the "void" but if you put radar it will fire on that dot on that spike.

**Comment by GoogleFrog** [comment]
This is because you cannot see the ground just back from the top of a cliff. I don't see a solution to this. If you let units force fire in midair then they could range hax or not fire at where you want them to fire.

**Comment by GoogleFrog** [comment]
The best you can do is fire at the top of the cliff. No fix possible here.
