### ISSUE TITLE
Overdrive nil orgMetal

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#112]
It seems that the overdrive gadget will break if too much energy is on the grid. This will likely not happen in real games, but it seems like around +25000e/s or +600m/s or something similarly huge and the gadget breaks with the error:

[f=0011489] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_mex_overdrive.lua"]:380: attempt to perform arithmetic on local 'orgMetal' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_mex_overdrive.lua"]:380: in function 'AddPylonToGrid'
	[string "LuaRules/Gadgets/unit_mex_overdrive.lua"]:646: in function 'AddPylonsInQueueToGrid'
	[string "LuaRules/Gadgets/unit_mex_overdrive.lua"]:904: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1004: in function <[string "LuaRules/gadgets.lua"]:1002>
	(tail call): ?

Using Engine version 97.0.1-258, latest Zero-K from Git

**Comment by Orfelius** [comment]
Overdrive was changed recently I suppose this is no longer correct?

**Comment by dvr333** [comment]
I'll have to test at some point

**Comment by dvr333** [comment]
I don't seem to be able to reproduce this the way I had before, so I'm closing for now.
