### ISSUE TITLE
Making CAI play the game for you (Capture bug)

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1123]
During a random game played against CAI, I noticed that it's squads or w/e do not update when one of it's units are captured. This leads to lulzy self-playing. Also potentially annoying crap where the AI will override your orders.

May be a rare bug.

Replays:
http://zero-k.info/Battles/Detail/384031

**Comment by GoogleFrog** [comment]
I recall fixing this and the gadget seems to have code to handle it.
