### ISSUE TITLE
zenith is able to shoot outside its range

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1134]
you can manual fire outside of zeniths range....

**Comment by Jamanno** [comment]
update maybe better to reproduce:
set zenith hold fire. Manually aim outsides its range and set to fire at will again

**Comment by GoogleFrog** [comment]
The fix is to add a range check to the start of this function.

https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/zenith.lua#L196
