### ISSUE TITLE
Deluxeplayerlist should recalculate unit/porc values on /SpecFullView

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1151]
Currently using the /SpecFullView UI command can cause wrong numbers to be calculated on the playerlist.

"/SpecFullView (unsynced) Sets or toggles between full LOS or ally-team LOS, if the local user is a spectator"

I suppose that this happens because unit deaths and completions are not added to/subtracted from total metal values while spectators watch a single player's perspective. Anyway, a fix for this would be either completely recalculating the values or detecting units/unit deaths that were not counted earlier. I assume the "recalculate values completely" option would be the simpler one.

**Comment by dvr333** [comment]
This also happens with mex spot colouring, FacPanel, and anything controlling selections (clicking on a unit on an allyteam you weren't spectating fixes the last two, as does hitting a number on the homerow not corresponding to a player). My guess is that there's an issue engine-side with specfullview not properly informing widgets that they can get data about everyone if they've been limited.

Unless there's a callin I'm missing.

**Comment by sprunk** [comment]
Deluxe is deprecated.
