### ISSUE TITLE
XP gain from 1v1 games calculated from team elo

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1156]
Currently XP gain from 1v1 games is calculated from team elo when it should be calculated from 1v1 elo instead.

http://zero-k.info/Battles/Detail/388616
Here is a game example. Notice how NorthChileanG gained more XP than Failer even though NorthChileanG has a higher **1v1 elo** than Failer.

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/f46ab78f9029d9f23a02e938bcef6b9e27de3ef1/ZkData/Ef/SpringBattle.cs#L242
public void Calculate1v1Elo()
is using WinnerTeamXpChange and LoserTeamXpChange

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/f46ab78f9029d9f23a02e938bcef6b9e27de3ef1/ZkData/Ef/SpringBattle.cs#L153
these are both using eWin and eLose

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/f46ab78f9029d9f23a02e938bcef6b9e27de3ef1/ZkData/Ef/SpringBattle.cs#L128
which are both using winnerElo and loserElo
which are both using r.Account.EffectiveElo

Not really sure where "EffectiveElo" comes from, I guess that's database stuff. I don't really understand how to specify whether I want to retrieve team or 1v1 elo from the database, so I have no idea how exactly I could fix this issue myself.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues

No official way to move issues, unfortunately.

**Comment by Skasi** [comment]
Zero-K-Infrastructure#890
