### ISSUE TITLE
initial unit state does not work for on/off

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1157]
Try to set newton inital unit state to off. New build unit will be on "On".
same when you try while building settings state to off, it will be On after finished building.

**Comment by mtroyka** [comment]
It doesn't work for outlaw either, even after a clean install. Outlaws always start "off" no matter what you set them to in new unit states.

**Comment by Jamanno** [comment]
This is kinda annoying though newton is a good wyvern catcher.
