### ISSUE TITLE
BuildETA should be visible on unit icons

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1168]
BuildETA should be visible when zoomed out and unit models get replaced with radar icons. If not by default then this should at least be available via a toggle option.

Currently even when "Display Height" on buildETA is set to 5000 it's hidden as soon as icons become visible.

**Comment by GoogleFrog** [comment]
I think there is an option for this.

**Comment by CrazyEddieTK** [comment]
If so, it should probably be enabled by default. When zoomed out to icon view, there is (by default) no way to distinguish between _actual_ units and incomplete nanoframes. This is pretty important information to have.
