### ISSUE TITLE
Bait Resistant Screamer/Hacksaw Unit AI

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1169]
I have been considering writing a selective-fire mode for the Screamer. The mode would prevent it from wasting missiles on inappropriate targets. I believe the weapon should ignore at least drones. It could even take into account how many other units will be close to the target in order to maximize efficiency. The mode should be toggleable through the unit command tab of the multipurpose user interface panel which, by default, can be found in the lower left hand corner of the screen.

What do you think? Do you find this a good idea?

**Comment by mtroyka** [comment]
Ignoring drones is a bad idea. Vs funnelwebs attacking drones can damage the funnel's shields, and vs  reefs the aoe is likely to kill lots of them at once. In both cases the drones are also highly threatening to everything else, so killing them makes sense.

There are probably things that it doesn't make sense for a screamer to target, such as gnats and blastwings, but besides those two most other targets are highly situational. It could certainly use smarter targeting priorities though, as currently the only thing it prefers to shoot specifically are bombers.

**Comment by DeinFreund** [comment]
I would appreciate such a mode. But don't forget that this would require the screamer to wait for enemies to enter LOS and thereby disclose their unitdef. Still this could be helpful for many cases where you currently have to set the screamer to hold fire. 

Maybe it could even incorporate the amount of missiles stockpiled(<5 only bombers, <20 only unitdefs worth more than 100 metal, >=20 shoot at all radar dots)

**Comment by GoogleFrog** [comment]
The unitdef detection poses quite an issue. It may be possible to determine a unit by its speed and height but I would prefer if that was not done, it is too invisible.

For implementation look at don't fire at radar.

**Comment by GoogleFrog** [comment]
Covered here: https://github.com/ZeroK-RTS/Zero-K/issues/2789
