### ISSUE TITLE
COFC - /track causes camera weirdness

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1180]
I wanted to track this com's journey in this game. Went to type /track, but now I'm staring at the sky.
![screen00258](https://cloud.githubusercontent.com/assets/7841201/12072982/ac0d84c8-b0c0-11e5-9f62-702615d202a9.png)

**Comment by mojjj** [comment]
there is a hotkey for tracking a unit with the camera, but i forgot. someone help? knorke knows!
