### ISSUE TITLE
Display DPS shows up even when UI is disabled (via f5)

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1181]
Intended?
![screen00257](https://cloud.githubusercontent.com/assets/7841201/12072999/68d8d47c-b0c1-11e5-9376-576d8ca5b328.png)

**Comment by KingRaptor** [comment]
It was meant to be hidden with F5, but this got broken way back in the past. Fixed now, thanks for reporting!
