### ISSUE TITLE
Resign as last player bug

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1182]
If your opponent leaves and the Win button appears and you decide to resign for whatever reason, it causes the following error:

[f=0061380] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_over.lua"]:392: Incorrect arguments to SetGameRulesParam()
stack traceback:
	[C]: in function 'SetGameRulesParam'
	[string "LuaRules/Gadgets/game_over.lua"]:392: in function 'ProcessLastAlly'
	[string "LuaRules/Gadgets/game_over.lua"]:509: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
	(tail call): ?
[f=0061425] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_over.lua"]:392: Incorrect arguments to SetGameRulesParam()
stack traceback:
	[C]: in function 'SetGameRulesParam'
	[string "LuaRules/Gadgets/game_over.lua"]:392: in function 'ProcessLastAlly'
	[string "LuaRules/Gadgets/game_over.lua"]:509: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
	(tail call): ?
[f=0061470] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_over.lua"]:392: Incorrect arguments to SetGameRulesParam()
stack traceback:
	[C]: in function 'SetGameRulesParam'
	[string "LuaRules/Gadgets/game_over.lua"]:392: in function 'ProcessLastAlly'
	[string "LuaRules/Gadgets/game_over.lua"]:509: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
	(tail call): ?

And the game will never end unless it's exited.

**Comment by GoogleFrog** [comment]
See if it works now on test host.

**Comment by sprunk** [comment]
Tested http://zero-k.info/Battles/Detail/399947

No longer crashes but won't end the game despite there being no-one. The resigned party can't do anything and the dropper might not come back.

Decide what to do:
 * keep things as-is. If a dropper comes back he wins (through the button if there are more droppers or automatically if he was the only one and all opposition resigned). If no dropper comes back the game drags on and has to be exited.
 * declare the dropper the winner. In 1v1 this is alright (resign -> enemy wins regardless of drop) but problematic if there is eg. a 3-way FFA with 2 droppers and 1 resigner.
 * declare a game-over with no winners.

**Comment by Anarchid** [comment]
What about: have the button read "declare draw" if everyone else has resigned or dropped when it appears, and change its function to declare draw.

**Comment by sprunk** [comment]
So "declare win" if you are a non-resigned player and all other non-resigned players are dropped, and "declare draw" if you are a resigned player all non-resigned are dropped? Sounds convoluted.

If you are not resigned then forcing draw makes no sense. The button is there so you don't have to spend X minutes clearing the uncontrolled units.

The original issue is resolved and I kept it open because the "game wont end" might be seen as a problem and is a direct consequence of the fix. The decision is fairly minor though. The differences are:
 * keep as-is allows the dropper to come back to grab his win, but meanwhile the other people have a "what now?" confusion because nothing is happening.
 * resign causing a win for the other party, even if dropped, sounds like the proper solution for 1v1 but won't work in FFAs with 1 resign and 2 droppers.
 * automatic draw would prevent confusion.

**Comment by GoogleFrog** [comment]
I would make it a draw. This would be shown with the "Game ended with no winner" text for the endgame screen (it currently handles no-winner games, I forget what the exact text is). If someone wants a win they need to be not dropped. The FFA double drop edge case prevents us from declaring dropped players to be winners.

**Comment by Anarchid** [comment]
> So "declare win" if you are a non-resigned player and all other non-resigned players are dropped, and "declare draw" if you are a resigned player all non-resigned are dropped? Sounds convoluted.

More like: Declare win if you are a non-dropped player who is selfish. Declare draw if you are a non-dropped player who is polite. Automatically declare draw if all non-resigned non-spectators have dropped, and in fact why is the game even running in such case.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/99a15af8f97deee023ac7b2041fcdda22a0a423f
