### ISSUE TITLE
CAI gets stuck

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1193]
Replay: https://drive.google.com/file/d/0B0FswUjncRt0UVZaSFZWeHUyck0/view?usp=sharing

The CAIs fac was blocked from minute 6 by a Zeus that didnt properly leave the fac. CAI eventually sends its away when it is attacked a lot later.

CAI didn't try to build a second fac and instead keeps spamming solars and winds all over the place..

This pretty much caused the game to be PlayerVsNullAI. Would be nice if CAI could either disallow units to stand inside the fac or build a second fac(Which I think it used to do).

**Comment by sprunk** [comment]
CAI has been replaced by Circuit.
