### ISSUE TITLE
Air unit going underground

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1194]
The battle with description of the bug:
http://zero-k.info/Battles/Detail/393758
After repair bomber goes underground from airpad, out of the map and never returns.
Happens to fighters too (if my memory serves me well).

**Comment by GoogleFrog** [comment]
Bottom right 6:25.

**Comment by GoogleFrog** [comment]
Unit entered the repair pad but left on the same frame? It was already rearmed and was almost at full health while being repaired by nano.

**Comment by sprunk** [comment]
Ancient engine and airpad code has been touched since.
