### ISSUE TITLE
Some updates for 101.0

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#1199]
* Currently bombers have a check for GetUnitFuel in script.BlockShot. since ZK doesn't use fuel and it was also removed from the engine, the check can probably be removed.
* instead of calling SetProjectilePos(-100000, -1000000, -100000) call DeleteProjectile(projID)

**Comment by Anarchid** [comment]
Possibly relevant wrt 101: http://zero-k.info/Forum/Thread/20934

**Comment by ashdnazg** [comment]
ooh right! LOS_MULT  needss to be 1 IIRC
