### ISSUE TITLE
Wakes visible for cloaked ships.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1201]
This occurs at least with Halberd. A check for cloaking should be inserted into the relevant scripts.

**Comment by Anarchid** [comment]
Should cloaked units also:
- not emit smoke (i think you can catch scyhhes now with this)
- not emit wakes

?

**Comment by GoogleFrog** [comment]
Yes. Cloaked units should not emit things which can seen merely by viewing the position. LUS fixes the smoke emitting problem so I am fairly sure you cannot see Scythes. See https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/constants.lua#L78

**Comment by GoogleFrog** [comment]
Todo: Ships and Dagger.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/0166ac6ca07ec935530f6e5fb813dc689b54b1f9

**Comment by sprunk** [comment]
Related: #1375 - has pretty much the same solution (convert ships to LUS and make wakes conditional).

**Comment by Anarchid** [comment]
Not all ships require converting to LUS, so some are fixable as-is.
