### ISSUE TITLE
zk:test on Springie crashes LuaUI

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1211]
Join BETA TEST host. Start the game. LuaUI is missing in action.

- `/luaui enable` reactivates LuaUI
- infolog contains a bunch of error messages of being unable to allocate memory because LuaUI exceeded quota of ~800 megabytes
- seems to also happen to @rlcevg here: https://github.com/ZeroK-RTS/Zero-K/issues/905#issuecomment-172891250
- same version of the game hosted locally as Zero-K $VERSION does not seem to exhibit the problem
- i didn't test locally hosted zk: test yet

**Comment by Licho1** [comment]
Can you check script.txt?

**Comment by Anarchid** [comment]
script.txt, as extracted from local demofile via hex edito: http://hastebin.com/vurotogare.hs

The problem also happens on mac for me, though i guess we don't really support mac.

**Comment by Anarchid** [comment]
Exact text of infolog error:
`[f=0000000] Fatal: LuaUI: cannot allocate more memory! (805306369 bytes already used, 805306368 bytes maximum)`

**Comment by Anarchid** [comment]
Does not happen with zk:test hosted locally.

**Comment by Anarchid** [comment]
Does not happen on Springie when starting as a commanderless smurf.

**Comment by Anarchid** [comment]
The issue seems to only happen when i join the game with 6 configured commanders. Removing one and adding it back causes the problem to disappear and reappear.

**Comment by GoogleFrog** [comment]
This startscript works fine for me: http://hastebin.com/ugagiyafih.avrasm

Test to see if it breaks.

**Comment by GoogleFrog** [comment]
805306369 bytes is about 768 mega bytes so the value sounds correct.

**Comment by GoogleFrog** [comment]
A 7 player game gave me enough commanders in the startscript to cause out of memory. Here is a startscript built from it:

http://pastebin.com/wEqM5Fvf

With echos I determined that commDataRaw = Spring.Utilities.Base64Decode(commDataRaw) causes out of memory.

**Comment by GoogleFrog** [comment]
I made a stress test with 70 players worth of commanders and my fix held up. Here is the startscript. Test it out and see whether the fix works for you.

[GoogleFrogComm.txt](https://github.com/ZeroK-RTS/Zero-K/files/111204/GoogleFrogComm.txt)
