### ISSUE TITLE
music does not play until volume-slider is moved to zero and back

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1216]
Music does not play until music-volume slider is moved to left (zero) and then moved back. Appearently at least two players with this problem.

http://zero-k.info/Forum/Thread/20928
>  Hitting F6, changing sliders, doesn't give me back music. Sounds work fine. How can I get music back? 

.

 > Use audio volume slider to completely to left to mute sound then slide it back. 

.

> that works for me as well wolas 

.

> It worked thanks!

**Comment by knorker** [comment]
A way to reproduce:
1) delete ZK_data.lua file

2) On next start the game-volume will be at 50% and music at 0%
Sounds play, music does not. (as expected)

3) Move the music-volume slider to right: 
Still no music plays (bug)

4) Move music-volume slider to zero.

5) Move music-volume slider to right, for second time:
Music plays

**Comment by GoogleFrog** [comment]
Could not reproduce step 2. Music and sound were both positive.

**Comment by GoogleFrog** [comment]
My way to reproduce:

1) delete ZK_data.lua file

2) Start game, set music to 0%. Exit

3) Start game again, Move the music-volume slider to right:
No music plays (bug)

4) Move music-volume slider to zero.

5) Move music-volume slider to right, for second time:
Music plays
