### ISSUE TITLE
Bugs found in Blending edge room 100.0.1-1001

### ISSUE THREAD

**Issue by TurBoss** [ZeroK-RTS/Zero-K#1217]
Hi,
factories teamcolor black
Cloackies teamcolor are black
mexes teamcolor black too

geo is invisible

and some errors in infolog
http://paste.springfiles.com/view/1cf5e339

thx

**Comment by TurBoss** [comment]
Hovers factory teamcolor is black too but no units

**Comment by TurBoss** [comment]
Krow fires up and spreads all misiles in a huge radius

**Comment by GoogleFrog** [comment]
Fixed.
