### ISSUE TITLE
crabe improvements

### ISSUE THREAD

**Issue by springraaar** [ZeroK-RTS/Zero-K#1230]
Crabe's model and animation suck.

I made some simple changes to the 3do model to make it suck slightly less:
- removed the missile launcher pack because it's not used (kept the invisible pieces because script)
- fixed the barrel

get the updated 3do file here:
http://www.filedropper.com/armcrabe

The walk animation cycle can be improved significantly with this simple change:
local PACE = 1.2  ----> local PACE = 2.8

without replacing the model, improving it further requires tweaking the curl/uncurl animation:
- it shouldn't prevent the unit from firing
- it should prevent crabe from moving (apparently something like that is commented on the lua script)
- it should make it look more armored (it should match the 3x toughness, somehow)

**Comment by springraaar** [comment]
old model : http://snag.gy/FhL54.jpg

new model : http://snag.gy/RR2IR.jpg

**Comment by GoogleFrog** [comment]
I did not realize that the top thingy was a missile launcher. I think it should remain because it improved the form of the unit and breaks up the white space on top.

**Comment by GoogleFrog** [comment]
Fixed.
