### ISSUE TITLE
Native AI commanders do not receive the economy module.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1234]
- add a Circuit.
- observe its commander having 0.3 income from being a mobile nano.

**Comment by rlcevg** [comment]
The [faulty line](https://github.com/ZeroK-RTS/Zero-K/blob/b8f4c0a120a66830578e7a7cfd641b9c55f6ee1b/LuaRules/Gadgets/start_unit_setup.lua#L183)
```
- return Spring.GetTeamRulesParam(teamID, "start_unit") or "dyntrainer_assault_base"
+ return UnitDefNames[Spring.GetTeamRulesParam(teamID, "start_unit") or "dyntrainer_assault_base"].id
```
Also GetStartUnit now must return id, so [this](https://github.com/ZeroK-RTS/Zero-K/blob/b8f4c0a120a66830578e7a7cfd641b9c55f6ee1b/LuaRules/Gadgets/start_unit_setup.lua#L176) is also wrong (though obsolete?)
