### ISSUE TITLE
Some players cannot get comms to level 3

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1242]
swappan says he cannot upgrade commanders to level 3. He clicks upgrade button to get them to level 2 and then clicking the button no longer opens the dialogue. There is nothing in his infolog. He gets the popup if he clicks the button in the replay.

http://pastebin.com/St6b83hy

http://zero-k.info/Battles/Detail/397985

**Comment by sprunk** [comment]
Looks fixed, no complaints.

**Comment by GoogleFrog** [comment]
I have made no changes since then so I don't know why it would be fixed.

**Comment by sprunk** [comment]
The report is from version v1.4.2.4 so there have been minor changes. Comms are fairly popular and there have been 8 months without further complains so it's fair to assume one of the minor changes fixed that.
