### ISSUE TITLE
Tooltip shows wrong unit on pregame comm ghost if commander name is the same as an existing unit

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1244]
![screen00344](https://cloud.githubusercontent.com/assets/7841201/12765134/5edfae66-c9ba-11e5-8abb-c2d816f33867.png)

Wub wub?
I really can't even describe this... This is beyond failure..

**Comment by GoogleFrog** [comment]
Urg the tooltip widget. How badly does it have to be in order to do this? UnitDefID exists for a reason.
