### ISSUE TITLE
Pregame screen flicker

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1247]
First occurs with 1.4.2.0 (that release series) for only some players. atom2 is affected. It is probably to do with the startbox drawing speedups.

**Comment by GoogleFrog** [comment]
According to atom2 it started around 2 weeks ago. This makes no sense as there was no release then.

**Comment by Orfelius** [comment]
Maybe it is just some driver problem? Things like that happen with botched drivers in sometimes.

**Comment by sprunk** [comment]
I just asked atom2 and he said he has no flicker. There seems to have been no reports of the same issue since then either. Reopen if still happens.
