### ISSUE TITLE
Cheat Unit Spawner UI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1253]
Occasionally people ask how to spawn units ingame for testing. There should be an ingame UI for this rather than relying on text commands.

My solution is to add a submenu to Menu/Game. This menu would contain submenus full of buttons which let people spawn any unit. Perhaps there are a few buttons for spawning 1, 5 or 100.

**Comment by CrazyEddieTK** [comment]
As an addition to this feature, consider some buttons for spawning a random collection of enemy units, similar to what I described in #2242 . This would be just for fun, not for testing, but if we implement the basic feature for testing it should be easy and worthwhile to add the extra feature for fun.
