### ISSUE TITLE
Start commander is light transportable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1256]
The 1000 metal cost (before modules) seems to have made the starting commander transportable by Valk. This is probably due to their mass. I think we should hardcode their mass to be at least the threshold for heavy-only. Transports should take modules into account but currently do not because mass cannot be modified.

**Comment by ArchShaman** [comment]
Guardian com isnt transportable by valk. Only support strike and recon.

**Comment by GoogleFrog** [comment]
That would be due to health having an effect on mass.

**Comment by GoogleFrog** [comment]
Fixed.
