### ISSUE TITLE
Fix Shaders for ATI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1268]
Sortale has an ATI card and this came with many shader errors. These include invisible units. Apparently Wind, Defender, Support Commander and cloaked units were visible.

Infolog: http://pastebin.com/iH1PcPdY
Screenshot: https://www.dropbox.com/s/n7hwat10z3qf3go/Zero-k_editor56.jpg?dl=0

**Comment by ashdnazg** [comment]
Before fixing shaders, please check if this still happens in 100.0.1-1140-g9ebb848

**Comment by GoogleFrog** [comment]
Next task is to get Sortale to re-test. See ticket https://springrts.com/mantis/view.php?id=5077

**Comment by GoogleFrog** [comment]
KingRaptor says this is fixed but I would still like an infolog to check whether the shader errors are still present.

**Comment by sprunk** [comment]
It has been over a year so presumably fixed.
