### ISSUE TITLE
Save gadget handling

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1269]
Here is a list of enabled gadgets and what needs to be done for them to work with save/load. Debug gadgets are ignored but otherwise the list has every enabled gadget.
- [ ] ai_CAI has gadget:Save and gadget:Load acting on all its data in a naive way. I did not add this and have never checked whether it works. Check whether it works.
- [x] api_fog_hidden_effects. No data.
- [x] api_modularcomms. Data reconstructed on Initialize.
- [ ] api_saveload. The save/load gadget. Check whether the desired world properties are saved correctly.
- [x] api_widget_events. No data.
- [ ] awards. It seems to have a lot of data which would need to be saved. Perhaps teamRulesParams are appropriate? I have no idea how the gadget works.
- [ ] chicken_control. Silly mode, seems to have data.
- [ ] cmd_areaguard. Perhaps it is reconstruct-able from order queues. Needs testing.
- [x] cmd_hide_autorepairlevel. No data.
- [x] cmd_remove_wait. No data.
- [ ] cmd_retreat. Lots of data. Perhaps some of it already exists in unitRulesParams.
- [x] engine_taslbar_stuff. No data.
- [x] exp_no_air_nuke. No data.
- [ ] factory_anti_slacker. Units may end up being permanently unblocking. Perhaps use a unitRulesParam to reload or set all units to blocking upon load.
- [x] feature_blocking_tag_implementation. No data.
- [x] game_disable_take. No data.
- [ ] game_lagmonitor. Multiplayer only so not required for singleplayer save/load. Saving this data is required for multiplayer.
- [ ] game_over. Seems to initialize its data in Initialize. Check whether this works.
- [x] game_perks. Gets data from Initialize.
- [x] game_resign. No data.
- [x] init_auto_ready. Removed after game start. Don't save before the game starts!
- [ ] lavarise. Has data.
- [x] lockunits_modoption. Gets data on Initialize.
- [ ] lups_cloak_fx. Check whether it works. Units should not be left cloaked without an effect.
- [x] lups_nano_spray. No nanoparticles for a second on save is probably ok.
- [x] lups_shockwaves. Losing shockwaves for a second after load is fine.
- [x] lups_thrusters. Has luarules reload safety.
- [ ] lups_wrapper. N/A? Check whether lups works on load.
- [x] mex_placement. Gets data on load. Mex placement has some leeway for rez, will work here.
- [x] mex_spot_finder. Gets data on load.
- [ ] mission_orbital_drop. Needs save/load for units currently under movectrl.
- [ ] mod_stats. Probably unimportant.
- [x] share_control. No data.
- [x] start_boxes. Loads all data on init.
- [ ] start_unit_setup. Contains Save/Load functions. Check whether they work.
- [ ] terrain_texture_handler. Needs save/load and to reapply terrain texture.
- [x] typemap_options. Reapplies typemap changes on load.
- [x] unit_air_plants. Recreates data on load.
- [x] unit_aircraft_crash. For a few seconds after load planes may gib less readily. Unimportant.
- [x] unit_allow_builder_hold_fire. No data.
- [ ] unit_anitnuke_handler. No data but check whether this works with the projectile spawning interactions.
- [x] unit_attributes. No data which is not recreated on the fly. Other gadget should call unit_attributes during load to update the attributes which they set.
- [ ] unit_bomber_command. Mostly uses params, appears to work fine without specific save/load implementation?
- [ ] unit_bomber_dive. Could be made more luarules reload safe by saving any applying dive state.
- [ ] unit_boolean_disable. Reloads itself from unitRulesParams. Check whether it works.
- [ ] unit_capture. Has save/load functions. Check whether they work.
- [x] unit_carrier_drones. Needs to be made luarules reload safe with unitRulesParams.
- [x] unit_centeroffset. Reloads on init.
- [x] unit_cloak_shield. Shield radius drops on reload. Possibly make a unitRulesParam for radius.
- [x] unit_commander_upgrade. No data, everything is stored as unitRulesParams and acted on by the gadget.
- [x] unit_gunship_control_strafe_range. No data.
- [ ] unit_decloak_damaged. Probably needs save/load to prevent permanent decloak (at least until manually toggled).
- [x] unit_dgun_aim. No data.
- [x] unit_disable_buildoptions. No data.
- [ ] unit_dont_fire_at_radar. Needs reload from unit state. Perhaps store state in unitRulesParam.
- [x] unit_energy_drain. No data.
- [ ] unit_explosion_spawner. Decide whether disabling Wolverine for a second is ok. It is probably ok.
- [x] unit_fall_damage. With perfect timing you may be able to prevent some fall damage. Probably not worth the effort to patch.
- [ ] unit_gamerules_events. Needs save/load to un-set gameRules if they were set at the time of save.
- [ ] unit_grey_goo. Reconstruct data from unitRulesParam.
- [ ] unit_gunship_strafe_control. Save unit state.
- [x] unit_icongenerator. N/A
- [ ] unit_impulsefloat_toggle. Save unit state in unitRulesParam?
- [x] unit_instant_self_destruct. Very unlikely to break from save/load. Breakage leads to late self-d for ticks.
- [x] unit_is_on_fire. Needs save/load.
- [x] unit_jumpjets. Needs save/load for reload and to deal with movectrl units.
- [ ] unit_marketplace. Does this even work?
- [x] unit_mex_overdrive. Luarules reload safe. May lead to a weird economy frame on load but settles down rapidly.
- [x] unit_missilesilo. Needs save/load to associate missiles with silos (probably).
- [x] unit_morph. Lots of data, probably needs save/load or unitRulesParams.
- [ ] unit_nanoframe_death. Needs to reconstruct table unitFromFactory; check if this occurs automatically when loaded units are respawned.
- [x] unit_nofriendlyfire. No data.
- [x] unit_noselfd. No data.
- [x] unit_oneclick_weapon. No data.
- [x] unit_overkill_prevention. No bad behaviour after a few seconds of load. Probably not worth the effort to save/load.
- [x] unit_paralysis_damage. No data.
- [x] unit_planetwars. Decree that there is no saving and loading planetwars matches.
- [x] unit_prevent_lab_hax. luarules reload safe.
- [x] unit_prevent_landship. No problem with not using save/load. Landships may just stop bouncing for a short time after load.
- [ ] unit_priority. Most data is recreated on load. Reload reserve state and check whether unit states are set properly. Perhaps use unitRulesParam for priority state.
- [ ] unit_puppy_handler. Needs save/load for Puppies to return when fired. It is a hard task to link projectile to unitID. Perhaps just spawn a puppy if a missile hits and kill underground ones.
- [x] unit_reclaim_hp. Data regenerated when reclaim continues after load.
- [x] unit_refuel_pad_handler. Reload rearm progress from unitRulesParam.
- [x] unit_regeneration. Needs to reload idleRegenTimer unitRulesParam.
- [ ] unit_repair_speed. Make a 'recently damaged' unitRulesParam and reload from it.
- [x] unit_rezz_hp. Single frame effect could lead to a bug. No other data.
- [ ] unit_script. Think about whether saving piece rotation and position is feasible.
- [x] unit_script_notification. No data.
- [x] unit_self_destruct. Probably no data.
- [x] unit_setnanopiece. No data.
- [x] unit_shield_charge. Luarules reload safe.
- [x] unit_shield_link. Luarules reload safe.
- [x] unit_show_shooter. No save/load just leads to a temporary loss of vision. Not required for save/load.
- [x] unit_solar_force_closed. Close no longer forced. Gadget probably works as it should.
- [x] unit_spawner. Chicken gadget. Save/load implementation required; need to profile synced-to-unsynced data transmission and implement alternatives if use of _G/SYNCED is too costly.
- [x] unit_spherical_los. Gadget appears unused. If used, should check all units on Initialize to then be save/load ready.
- [x] unit_stealth. Takes effect properly when units recloak following game load.
- [ ] unit_stockpile. Needs to set engine stockpile parameters on load.
- [ ] unit_tactical_ai_commands. Needs save/load because many units could have bogus move orders. Issues will clear up after a few seconds. Consider worth of adding save/load.
- [ ] unit_target_on_the_move. Reload target data from unitRulesParams.
- [x] unit_target_priority has no data to save.
- [x] unit_teleporter. Lots to save. Teleporter ID, beacons, teleport progress. Perhaps set unitRulesParams for these and then reconstruct on load.
- [x] unit_terraform. The tables terraformUnit and terraformUnitTable need to be saved and loaded. As far as I know the other tables are constructed correctly upon unit creation.
- [x] unit_timeslow. (Slow damage/health) is stored as a unitRulesParam, but degrade timer is not.
- [x] unit_transport_ai_buttons. No data.
- [ ] unit_transport_pickup_floating_amph. Its a xponen widget which seems to have data. Test whether ignoring the data breaks anything.
- [x] unit_transport_speed. The table 'inTransport' is reconstructed when transportees are reattached on load.
- [x] unit_turn_without_interia. No data.
- [x] unit_vertical_swarm. Data recreated on Initialize.
- [ ] unit_water_effects. Save and load water tank from unitRulesParam.
- [x] unit_windmill_control. Data recreated on Initialize.
- [x] unit_xp. No data,
- [ ] unit_zombies. Has lots of featureID tables. Saveload would be best with featureRulesParams. Perhaps ignore until the engine gets them.
- [ ] weapon_area_damage. Saves and load mid-progress damage areas, but graphics are not currently regenerated. Is it possible to spawn a ceg part-way through? Probably not.
- [ ] weapon_impulse. The table 'unit' is for applying impulse in the next frame. Losing this table in a load is not a problem. The table 'inTransport' is reconstructed when transportees are reattached on load.
- [x] weapon_noexplode_stopper. With no save a noExplode projectile which passed through a shield may re-collide with that shield upon load. This is unlikely to occur.
- [x] weapon_single_hit. Units will receive double damage from gauss if the projectile is inside them the frame of the save. Very unlikely.
- [x] weapon_timed_replace. Not used.

**Comment by sprunk** [comment]
For most awards, team rules params will do. The main issue would be the XP award which requires units to keep XP between saves.

Award gadget does a lot of stats tracking and so I plan to reuse it for endgame graph stats. These are team rules params so will be easily ported, see https://github.com/ZeroK-RTS/Zero-K/commit/20fbf56395fe8d669a2d577fdbab289f414a27be

**Comment by GoogleFrog** [comment]
With the steam milestone for save/load I don't think we need to make it work perfectly. I think we can settle for save/load working reasonably well in most cases.

**Comment by GoogleFrog** [comment]
Many fixes have occurred and I think lua has had a pass. Specific issues need tickets.
