### ISSUE TITLE
Stuck Striderhub

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1275]
Late in this battle a Strider Hub has construction orders but fails to turn and start production. Its head seems to move slightly but not reach the correct heading.

http://zero-k.info/Battles/Detail/399933

**Comment by sprunk** [comment]
This sounds like an engine bug but the replay is from 100.0, the engine devs aren't going to look at it and it is fairly likely this might've been fixed since.
