### ISSUE TITLE
Can't toggle LoS View with transports selected

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1278]
LoS view cannot be toggled if a transport is selected. This is because the L key conflicts for the toggle and the Load command.

**Comment by GoogleFrog** [comment]
It has been this way forever and I have known about it for just as long. Perhaps it is vet bias but I think the conflict is fine. Both these actions are rare.

**Comment by sprunk** [comment]
Should the LoS toggle be so trivially accessible? Newbies might press it accidentally. In theory there shouldn't be any reason to disable the LoS view - the fogged map should still be bright enough to see. 

Would Ctrl+L be alright? This would prevent accidental presses and solve the key conflict.

**Comment by GoogleFrog** [comment]
Sure.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/f3682821d68f3b6c654495504214f1889b161ffa
