### ISSUE TITLE
Ghost Site shader ATI issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1279]
People with ATI get this error

[f=0001168] Vertex shader failed to compile with the following errors:
ERROR: 0:18: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:19: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:28: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:29: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:31: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:34: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: error(#273) 6 compilation errors.  No code generated

**Comment by GoogleFrog** [comment]
[infolog(1).zip](https://github.com/ZeroK-RTS/Zero-K/files/133989/infolog.1.zip)
Here is a zip of the infolog because it is large.

**Comment by GoogleFrog** [comment]
I reverted the change to Ghost Site to enable further testing.
https://github.com/ZeroK-RTS/Zero-K/commit/8eb7d318156c5e982e1efa912bc985b46c808fbc

**Comment by dvr333** [comment]
Goddammit ATI!

Who on the dev team even has an ATI card? I don't, so I need someone else to check through the shader code for when ATI's shit isn't together.

**Comment by GoogleFrog** [comment]
KingRaptor and Licho have ATI I think. You should be able to get KingRaptor to test.

**Comment by GoogleFrog** [comment]
Edge extension has been fixed. Reopen or make a more useful ticket if Ghost Site is broken.
