### ISSUE TITLE
stinger on spire shows higher range than it can reach

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1306]
terra up stinger and watch the attack range. it won't have it when you actually build it.

**Comment by CarabusX** [comment]
From what I remember it happens with all beamlasers, Annihilator too.
When placing the building engine thinks it will get range boost from height, but their actual ranges are spherical.

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=1225

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/2a88f642b9a726590b8f53b5539c296da0695116
