### ISSUE TITLE
Decide whether to reset hotkeys due to screw-up

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1309]
https://github.com/ZeroK-RTS/Zero-K/commit/85eb2a969333f407d8e0ea5ac7673ca7fed78ea2

GF's hotkeys got inflicted onto people and reverting the commit does not fix that.
Decide whether to tell everyone to clean up their hotkeys manually or do a reset.

**Comment by GoogleFrog** [comment]
It probably makes the most sense to do a pre-swap reset and then make a stable with the swap a few days later.

**Comment by Anarchid** [comment]
Might be possible to only reset for affected individuals by checking for an exact match?

**Comment by GoogleFrog** [comment]
Ok don't do the reset just yet. Figure out how many people are affected first.

**Comment by sprunk** [comment]
The longer we wait the more affected people will have fixed their keys (forcing them to do it yet again) and the more unaffected people get reset (people coming back from breaks and The Afflicted going on breaks).

**Comment by Licho1** [comment]
Do a reset

**Comment by GoogleFrog** [comment]
I feel like the answer is not to reset by now. Unless we can only target those affected.

**Comment by sprunk** [comment]
Nothing was done. It is now too late.
