### ISSUE TITLE
Radar circle missing for comm

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1315]
The green radar circle on Shift and Mouseover is missing on commanders with a Field Radar. It's drawn on the minimap when the unit is selected, but not on the actual game world. The radar circle is draw just fine for radar towers.

To clarify: This is not about the LoS-map radar display, but the radar circle similar to decloak-, build- and attack ranges.

Also commanders seem to emitting radar from their butt cheeks. Isn't that funny?

**Comment by sprunk** [comment]
Engine draws these circles. They could be emulated from within ZK but it shouldn't be hard to change engine.

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/247

**Comment by sprunk** [comment]
Engine PR merged so now we just need to wait for adoption.
