### ISSUE TITLE
Plantwars Cremuss models are invisible

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1317]
I forget his name but his models are invisible. Geo, Adv Geo, Sneaky Pete and Plantwars Buildings.

**Comment by Anarchid** [comment]
Cremuss. Obj import pipeline (non-assimp).

**Comment by GoogleFrog** [comment]
Anachid would you fix this?

**Comment by Anarchid** [comment]
I'll look into this weekendly.

**Comment by GoogleFrog** [comment]
Does this mean Sneaky Pete and the two geos are fixed? Planetwar structures are possibly still broken.

Also of note: BAR uses a few planetwars structures and those aren't broken.

**Comment by GoogleFrog** [comment]
Sneaky Pete faces are inside out when it is cloaked. The texture in the partially cloaked state is garbled.

**Comment by Anarchid** [comment]
> Does this mean Sneaky Pete and the two geos are fixed? Planetwar structures are possibly still broken.
Yes.

> Also of note: BAR uses a few planetwars structures and those aren't broken.
They likely use them in s3o format.

> Sneaky Pete faces are inside out when it is cloaked. The texture in the partially cloaked state is garbled.
I know of no way to fix this without going s3o or telling kloot.

**Comment by Anarchid** [comment]
This seems to no longer occur on the engine currently used by ZK.
