### ISSUE TITLE
Banisher CEG Fail

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1318]
Force fire Banisher at the ground on Scorpio Battleground and the CEG stops showing after a few shots. It is probably because the smooth makes the CEG appear underground. Best fix is to tell the engine to draw CEGs even if they are underground. Workaround may be to delay the smooth for 1 frame.

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/301

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/305

**Comment by GoogleFrog** [comment]
Now the tag needs applying and engine updating. This also applies to other units. I think the tag could be on by default given the wide range of units that very rarely have the issue.

**Comment by sprunk** [comment]
There is no new tag, the patch that went through instead makes it so that underground is considered ground (an existing tag). So ZK-side nothing needs to be touched and the only thing to do is to apply the engine.

**Comment by sprunk** [comment]
We're now using the new engine.
