### ISSUE TITLE
Gibs are different

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1320]
The engine added another type of gib and apparently it is not disabled by default. Many of our gibs look different and some might be ridiculous looking.

**Comment by sprunk** [comment]
It didn't add a new type of gib, it changed an existing one. The "shatter" effect used to be 2D confetti from the unit's paintjob but now it's actual broken-up 3D pieces. Shatter was used mostly for violent deaths so it should be appropriate in most cases.

**Comment by dvr333** [comment]
Oh, nice. I hadn't really been looking for this, but a better shatter effect sounds awesome. I hated the old 2d shatter effect, looked very PS1 era.

**Comment by GoogleFrog** [comment]
I did a a few mass self-destructions and did not notice anything out of place.
