### ISSUE TITLE
! removed hardcoded logic to zombify (stun+immobilize) a unit on death

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1321]

**Comment by KingRaptor** [comment]
How many units don't die instantly anyway (i.e. have death anims?)
The ones I remember are:
*Recom
*Supcomm
*Dante
*Warlord

I assume we fix these by giving the unit 999999 stun damage in unit script at the start of death anim. Or do we want something "cleaner" or more sophisticated?

**Comment by Anarchid** [comment]
Also at least strikecom and reef.

**Comment by sprunk** [comment]
They could slide along if they died under a lot of impulse but that's probably fine (sudden stop looks even worse).

**Comment by GoogleFrog** [comment]
Morph does not EMP units, it disables them entirely with just the attributes gadget. A "dead" attribute which is then sent to the attributes gadget is probably the best way to deal with this.

**Comment by GoogleFrog** [comment]
I have not noticed an issue so far.

**Comment by sprunk** [comment]
Looks solved.
