### ISSUE TITLE
BP tooltips wrong on dyncomms

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1324]
Many BP tooltips are wrong for dyncomms. See http://i.imgur.com/xnJ6rRi.jpg

**Comment by GoogleFrog** [comment]
Already done https://github.com/ZeroK-RTS/Zero-K/commit/92a9895540468863bd81035b209d0df00d723a85

**Comment by sprunk** [comment]
Not fully. Description still says the base amount.
