### ISSUE TITLE
dae cloak transition texture garble

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1326]
In 101.0+33 dae models have a garbled texture while they are in cloak transition.

**Comment by Anarchid** [comment]
Pretty sure this always happened, even back in 91.0. Worth mantising.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/694e8116d4d359b4e0077cd1c92220210c61c8d9
