### ISSUE TITLE
LOS-view looks ugly during paused game. (especially in missions)

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1328]
The animated LOS effect looks bad when game is paused.
The random blue and green pixels look almost more like a bug.
This is especially ugly during missions where the game gets constantly pause & unpaused.

![ugly los](https://cloud.githubusercontent.com/assets/3044855/13567628/9d099334-e45c-11e5-9d10-3acd74247f58.jpg)

**Comment by ashdnazg** [comment]
This is fixed in 101

**Comment by Anarchid** [comment]
Closing as such.
