### ISSUE TITLE
(desync)  Zero-K v1.4.3.1, spring 100.0, chicken

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1329]
One player desyncs shortly after start, leaving game & rejoin did not fix it.
No infolog because next game was started too soon.

attached is demos before/after rejoin.

[20160307_135012_Fields_Of_Isis_100.zip](https://github.com/ZeroK-RTS/Zero-K/files/161526/20160307_135012_Fields_Of_Isis_100.zip)

**Comment by GoogleFrog** [comment]
I don't think we can do much without an infolog. Most immediate desyncs occur due to a resources problem. Something may be been corrupted or the lobby might have started the wrong game/engine.

**Comment by knorker** [comment]
engine should have been correct one, there is only one downloaded.
rest idk.

**Comment by GoogleFrog** [comment]
New engine in use.
