### ISSUE TITLE
No volume option for text-to-speech

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1331]
Text-to-Speech is default enabled (for some reason)
Ingame I did not see an option to adjust its volume. (only game / music)

**Comment by Licho1** [comment]
ZKL now accepts messages in the form
"TTS VOLUME 33" where 33 must be a number between 0 and 100. Message must be self-said like ENABLE TTS or DISABLE TTS

**Comment by dvr333** [comment]
I would like to assume that a proper setting (i.e. nothing text/console related) will be in the upcoming lobby replacement, is that right?

**Comment by Licho1** [comment]
This is interface for a widget, widget for volume slider has to be modified to send this command.

**Comment by dvr333** [comment]
Oh, okay, that's fine then. I was under the impression that TTS was a lobby thing.

**Comment by Licho1** [comment]
Lobby is a provider of TTS yes, but it should be controlled from the game because thats what people see... Lobby producing TTS is just a technicality, because it's not possible directly from game.

**Comment by Licho1** [comment]
Slider should go to audio volume not be separate.
