### ISSUE TITLE
(v1.4.2.16) (animdef) disarmed Commander walks funny

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1332]
https://youtu.be/Q_JgrbYj_bU?list=PLmJnvU5T53FnsURH6EyL9lCaBNifNUStx&t=678
at 11min 20 sec

**Comment by GoogleFrog** [comment]
Strike commander.

**Comment by GoogleFrog** [comment]
The disarm seems to be relevant. Cannot reproduce but I can fix it.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/639ce1dff346d5eded9e84931471c8fc304827fa
