### ISSUE TITLE
Gravity guns fire at unit nanoframes, but don't affect them

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K#1340]
Gravity guns automatically fire at unit nanoframes, but don't affect them. Would be best to ignore nanoframes.

Sumo and newton fruitlessly assaulting a flea: http://i.imgur.com/u2ef4Uj.png

**Comment by GoogleFrog** [comment]
This is probably something to put in the target priorities gadget.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/35a147c9e41b86cf3356a18991fa9cf203a8785f#diff-81ea0164a917d1ffc0fcf24961af83c0R150
