### ISSUE TITLE
build spacing saves by unitdefid, saves defaults

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#1345]
gui_persistent_build_spacing.lua creates config file entries like:

```
	["Persistent Build Spacing"] = {
		buildSpacing = {
			[17] = 2,
			[19] = 2,
			[20] = 2,
			[23] = 2,
			[26] = 2,
			[37] = 2,
			[38] = 2,
			[40] = 2,
...
			[865] = 2,
			[874] = 2,
			[930] = 2,


```

**Comment by GoogleFrog** [comment]
Isn't this barely an issue?

**Comment by knorker** [comment]
unitdef-ids change when units are removed or added: mod updates or missions or with dynamic unitdef generation. (commanders)
Between matches unitdef-ids can be considered ~randomized.

http://zero-k.info/Battles/Detail/406278 3v3 and http://zero-k.info/Battles/Detail/406160 9v9
both matches with Zero-K v1.4.3.4 
in one game cormex is unitdefID **264**, in other game cormex is unitdefID **296**

![zkunitdefid](https://cloud.githubusercontent.com/assets/3044855/13960593/44c5e2d2-f059-11e5-9301-f388fbda785d.png)

I did not test it, but if the widget functions like that it would be by luck.
