### ISSUE TITLE
Improve grid modification function

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1353]
Currently overdrive grids are destroyed and recreated if they are modified. This occurs once a second if a change was made in the previous second (because the grid is only used once a second). The information required by the rest of OD is as follows:
 * A list of connected components.
 * For each component a list of structures in the component.

**Comment by ashdnazg** [comment]
https://github.com/ZeroK-RTS/Zero-K/compare/master...ashdnazg:master?w=1
I've started working on this a bit, adding a quadfield caused significant improvement, but there's still more to be done.

**Comment by ashdnazg** [comment]
btw, another thing to drastically improve performance in 100.0 (unnecessary in 101.0+) will be to remove windgen ground decals.

**Comment by sprunk** [comment]
What is the grid performance now? Is there much to improve? Can this ticket be closed?

**Comment by ashdnazg** [comment]
sim performance is OK, but graphics is still an issue
