### ISSUE TITLE
Dev engine performance

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1355]
Dev engine may have poor performance. Investigate.

**Comment by GoogleFrog** [comment]
[20160330_182513_Comet Catcher Redux_101.0.1-203-g4977986 develop.zip](https://github.com/ZeroK-RTS/Zero-K/files/195096/20160330_182513_Comet.Catcher.Redux_101.0.1-203-g4977986.develop.zip)
Here is a replay. It uses $VERSION so lacks usefulness.

**Comment by GoogleFrog** [comment]
Here is a caiFight benchmark. https://docs.google.com/spreadsheets/d/1ZeFMnq1aU_iGpRhBZNr1IHNhgl1cRaSG3-sVGN__nxU/edit#gid=0

**Comment by ashdnazg** [comment]
On my machine the benchmark runs faster with https://github.com/spring/spring/commit/fc5f3bad325507df12e9297ce9cd3fd3ae467082 than with 100.0.

**Comment by GoogleFrog** [comment]
Page 2 of the spreadsheet contains a new benchmark.

101.0.1-207-gfc5f3ba runs better than 100.0 for all metrics apart from speedy_dt. This measures the time it takes to fast forward the first 8 minutes of the game. Maybe there is something which occurs early in the CAI games to cause a performance issue. Perhaps the dev engine is worse at going faster.

The issue is now minor and part of the issue would be to determine whether the effect is real.

**Comment by ashdnazg** [comment]
you may want to test again with latest, perf should be better and speedy_dt is on par

**Comment by GoogleFrog** [comment]
Fixed.
