### ISSUE TITLE
Chat bubbles crash at end of game

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#1356]
From a private Springie game with no bots:

`[f=0000045] game_message: KingRaptor wins!`
`[f=0000053] [cawidgets.lua] Error: Error in AddConsoleMessage(): [string "LuaUI/Widgets/gui_chili_chatbubbles.lua"]:274: bad argument #1 to 'GetPlayerInfo' (number expected, got nil)`
`[f=0000053] [cawidgets.lua] Error: Removed widget: Chili Chat Bubbles`

**Comment by sprunk** [comment]
-> remove chat bubbles? :P

**Comment by Anarchid** [comment]
The new chat widget supercedes them anyway, i think?

**Comment by GoogleFrog** [comment]
Chat bubbles are not in use.
