### ISSUE TITLE
Toggle drone deployment for drone carriers

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1362]
To allow for better concealment of your strength in FFA games. Alternatively hold fire could make drones land on carrier.

**Comment by GoogleFrog** [comment]
Drones can be set to hold fire which allows them to hide in an area cloaker. I don't think they are going to be dockable as that would require the gadget to destroy and recreate units for little game.

**Comment by ArchShaman** [comment]
>gadget to destroy and recreate units for little game.

What about movectrling them to a very very far place outside the map and hold firing them? When the drone carrier redeploys them, teleport them back to the drone carrier and revert state?

**Comment by Anarchid** [comment]
It should also be possible to make them actually physically land on the carrier and become shielded by its colvol / untargetable / invulnerable / uncollidable.

**Comment by GoogleFrog** [comment]
I'm pretty sure this was done with hold fire, recall drones, and drone construction toggle.
