### ISSUE TITLE
playerlist doesnt allow to give units to rejoined player

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1365]
autolag gives some units back, but  when you try to give back other units lagged out player still counts as afk somehow and you cannot give anything back.

**Comment by sprunk** [comment]
Show a replay.

**Comment by Jamanno** [comment]
http://zero-k.info/Battles/Detail/409715?ShowWinners=True
When OldFrog comes back and I had the same problem on a battle with Senaven too, but cannot remember the  battle. I will add more replays here soon when the same problem occurs again.

**Comment by sprunk** [comment]
Playerlists are deprecated.
