### ISSUE TITLE
Chicken game crash

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1366]
Everyone in chickens room crashed simultaneously.
Infolog(Windows trace :/ ): http://paste.springfiles.com/view/148bc452

Reportedly there has been a crash in the teams room as well, so the issue may be Network/Springie related.

**Comment by sprunk** [comment]
Simultaneous crash in teams room, and lack of anything of interest in the infolog, seem to suggest this was not a game issue. Reopen if more information becomes available.

**Comment by knorker** [comment]
> lack of anything of interest in the infolog

infolog can be put into stacktrace translator.
