### ISSUE TITLE
Edge extension ATI error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1369]
Apparently the error in this ticket is caused by edge extension: https://github.com/ZeroK-RTS/Zero-K/issues/1279

[f=0001168] Vertex shader failed to compile with the following errors:
ERROR: 0:18: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:19: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:28: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:29: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:31: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:34: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: error(#273) 6 compilation errors. No code generated

With this line of the edge extension widget https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/map_edge_extension.lua#L165

**Comment by dvr333** [comment]
I'm getting increasingly convinced that ATI cards can't actually *do* anything.

**Comment by KingRaptor** [comment]
```
Error: Map Edge Extension widget: mirror shader error: Vertex shader failed to compile with the following errors:
ERROR: 0:31: error(#162) Wrong operand types: no operation "&&" exists that takes a left-hand operand of type "uniform highp float" and a right operand of type "uniform highp float" (or there is no acceptable conversion)
ERROR: error(#273) 1 compilation errors.  No code generated
```
