### ISSUE TITLE
Commander can't fire dgun

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1372]
Occurs to Testo's commander in http://zero-k.info/Battles/Detail/410705 around minute 30.

Commander shows dgun in space+click view, but neither me nor Testo can use the dgun with either the gui or the hotkey. Reloading the UI does not solve the problem.

**Comment by Skasi** [comment]
Could this be related to the following issue?
http://i.imgur.com/L6RXlpT.jpg
The menu shows that a Disruptor bomb module was equipped, but there is no such weapon in the actual weapon list, nor a Dgun button.

**Comment by DeinFreund** [comment]
Yes, that looks just like the issue I had.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/045c9d605441c3d08f418494e1a138f393c2d662
