### ISSUE TITLE
Transported ships wakes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1375]
Wake cegs appear below ships which are in transports over the sea surface. This occurs in the dev engine. Part of the ticket is to see if it occurs elsewhere. It also may occur for units other than ships.

**Comment by sprunk** [comment]
Fixed for hovers https://github.com/ZeroK-RTS/Zero-K/commit/462da8a26ec98b2ae498132ac42aa7c40721ebea

**Comment by sprunk** [comment]
As far as I can tell this is fixed.
