### ISSUE TITLE
Moderator Friendly Fire

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1380]
Moderators are prone to friendly fire because their model is inappropriate. Friendly fire can occur when they turn just before they fire because their muzzle is very far from their center of mass. Ideally Moderator would be remodeled or somehow changed to have a more central weapon (also one that looks more appropriate).

**Comment by sprunk** [comment]
Duplicate of #894 ? Also, the same happens to snipers.

**Comment by GoogleFrog** [comment]
Do you expect it to start working? The fix in this case is a better model.

**Comment by GoogleFrog** [comment]
Spring 101.0+dev fixes this. I had 20 Moderators Fight at 4 approaching Jacks.One of them took 200 damage but that was probably from other bumping or bumping against wrecks.
