### ISSUE TITLE
context menu crash

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#1385]
[f=0009248] [cawidgets.lua] Error: Error in MousePress(): [string "LuaUI/i18nlib/i18n/interpolate.lua"]:33: bad argument #2 to 'format' (no value)
    [f=0009248] [cawidgets.lua] Error: Removed widget: Context Menu

I wanted to compare stats of Hammer and Moderator, but then context menu crashed after space+click on the units. I don't remember exactly which of the two units I clicked as the crash occurred, but I've seen a unit window pop up at least for one frame.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/b605a726f0f831b6134746f270aa1856e0574b86
