### ISSUE TITLE
Latecomers lose their 2nd com

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K#1388]
When a player arrives late to battle, so that they haven't placed their startpoint and their commander falls from the sky, they don't get a 2nd commander when they should.

Link to an exited battle where this happens to Failer:
https://www.dropbox.com/s/kd58jw945du7bvn/20160510_002037_Victoria%20Crater%20v2_100.sdf?dl=0

**Comment by knorker** [comment]
> when they should

I think they should not, and the commander should be given to an more active player

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/2e2a6bfe608c9b14498e40a3e347eedaf4d4b333
