### ISSUE TITLE
Make all non-kudos unlocks free

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#1397]
Since the dynamic comm UI makes all comms and modules available ingame anyway, all this does is keep new players from properly customizing their templates on site. I can make every unlock require zero XP and level 0, this makes the site treat them as unlocked for everyone without any user-side input required.

This issue report is here so people can bring up any objections to the plan they can think of. I'll do it later next week if nobody objects,

**Comment by GoogleFrog** [comment]
There should be no non-kudos unlocks. If you can do something which is equivalent to this then I am in favour. Does the site side customisation work in other respects?

**Comment by knorker** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/973 related

**Comment by KingRaptor** [comment]
> Does the site side customisation work in other respects?

There's https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/935 but I never got the lists of "broken stuff to fix" I asked people for. Anyway that can be dealt with separately.

(also I just noticed this is on the wrong repo sigh)

**Comment by Licho1** [comment]
I think that without unlockable you wont keep people ingame for long enought to appretiate zero-k.
Do not remove unlockables imo.

**Comment by Anarchid** [comment]
Unlocks for retention belong in campaign, not in MP, imo.

**Comment by Licho1** [comment]
Thats a sound compromise if there is no other support for mp unlocks (than from me)

**Comment by KingRaptor** [comment]
Unlocks freed.
