### ISSUE TITLE
Zenith doesn't gain experience

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1403]
1.) Make zenith.
2.) Kill stuff.
3.) Experience: 0.00
4.) Never know how much cost you made.

**Comment by GoogleFrog** [comment]
It doesn't own the meteors, it just controls them. Technically the meteors are owned by gaia. I did this to make them not penetrate allied shields. I think this is useful and thematically appropriate.

**Comment by sprunk** [comment]
It also doesn't count for the endgame stats graphs.
