### ISSUE TITLE
Sprungbox: improve recommended start points

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1414]
CAI used to split up evenly along the startbox, this isn't working anymore on the latest dev engine.

**Comment by sprunk** [comment]
This only happens on maps without custom boxes defined.

Create a list of these maps, they should get a proper config.

**Comment by DeinFreund** [comment]
What comes to mind:

http://zero-k.info/Maps/Detail/7251
http://zero-k.info/Maps/Detail/7696
http://zero-k.info/Maps/Detail/21269
http://zero-k.info/Maps/Detail/31508
http://zero-k.info/Maps/Detail/52721

**Comment by sprunk** [comment]
CAI has been deprecated but the points should be defined regardless because they have other uses.
