### ISSUE TITLE
Set UI to reset on screen resolution change.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1415]
Set this widget option to true about a month after the current stable. This is to catch new players without causing displeasure for everyone else when their UI is changed.

**Comment by GoogleFrog** [comment]
Here is the release stable: https://github.com/ZeroK-RTS/Zero-K/commit/90a6fa9c7a08859e47e0cd5d98477dc8b651674a

**Comment by KingRaptor** [comment]
Full reset seems a bit heavy-handed, could it reset only window positions?

**Comment by GoogleFrog** [comment]
It presses the "default" button in HUD presets. This enables/disables the right panel-creating widgets.

**Comment by Skasi** [comment]
Would the reset be triggered every time a player resizes Spring in windowed mode?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by GoogleFrog** [comment]
Implemented.
