### ISSUE TITLE
Bumblebee support-art requirements

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1416]
Bumblebee needs a death clone and unitpic.

**Comment by GoogleFrog** [comment]
Actually, I would release with just a unitpic. The triangle soup death clones are sufficient temporarily.

**Comment by GoogleFrog** [comment]
Unitpic and sound: https://github.com/ZeroK-RTS/Zero-K/commit/815697ad5a5d52b49fb0c01a28265207fe77c090

Just needs a death clone.

**Comment by Anarchid** [comment]
I'll make a corpse eveningly.

**Comment by Anarchid** [comment]
It is done.
