### ISSUE TITLE
Terraform bug.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1417]
A structure ends up squished between two cliffs due to terraform.

https://snag.gy/nb3hTp.jpg

http://zero-k.info/Battles/Detail/417040

**Comment by GoogleFrog** [comment]
There is no crash or error message. The geo finishes morphing after the terraform is started. This seems to make the terraform ignore it.

**Comment by sprunk** [comment]
b574f7bc90e08e420086d9e1c6ad78e16feb1a06 ?

**Comment by sprunk** [comment]
The linked replay is dead but this seems to have been fixed since there haven't been any reports about this.
