### ISSUE TITLE
Desyncs in new engine

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1422]
Desyncs currently happening since engine switch(?)

Currently affected games:
B417848 - http://pastebin.com/tPPkNnEX [B417848 replay.zip](https://github.com/ZeroK-RTS/Zero-K/files/297333/B417848.replay.zip)
B417884 (http://zero-k.info/Battles/Detail/417884 ) [B417884 (HiEnergy).zip](https://github.com/ZeroK-RTS/Zero-K/files/297892/B417884.HiEnergy.zip) / http://pastebin.com/bgW7YsvJ [B417884 Shaman.zip](https://github.com/ZeroK-RTS/Zero-K/files/297888/B417884.Shaman.zip) (Shaman)

**Comment by ArchShaman** [comment]
Desync in B417884 (http://zero-k.info/Battles/Detail/417884 ) - https://www.dropbox.com/s/arl5hpw714j6pq2/desync-issue.zip?dl=1 (HiEnergy)

**Comment by rlcevg** [comment]
lamer
https://www.dropbox.com/s/q9vy6jqgl8lkamz/desync_B417884.zip?dl=0

**Comment by ashdnazg** [comment]
thanks for the reports! Desync was pinpointed and a new version will roll out soon

**Comment by ArchShaman** [comment]
rokomata reported that there's still desyncs in 411. Did not report them here though which is sad.

**Comment by GoogleFrog** [comment]
Apparently this particular one was fixed.
