### ISSUE TITLE
Check energy and metal income graphs regarding reclaim

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1425]
Does the energy and metal income graphs at the end of the game take reclaim into account? I think reclaim should be included in the graphs if not.

The graphs from this game are suspicious http://zero-k.info/Battles/Detail/418065

**Comment by sprunk** [comment]
Currently this is just the base income since reclaim is available in a separate graph.

**Comment by GoogleFrog** [comment]
There should be a graph of all income. This is the graph you check to see where the economic advantage lay. Then, if they think reclaim played a big part, players may go and look at the other graphs.

**Comment by GoogleFrog** [comment]
There is no energy reclaimed graph.
