### ISSUE TITLE
Rotated Funnelweb nanoframe

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1426]
Funnelwebs built by DeinFreund in http://zero-k.info/Battles/Detail/418292 are built standing on their opisthosoma with legs in the air.

Upon completion they grow up into regular healthy Funnelwebs.

This should be mantised if repeatable.

**Comment by GoogleFrog** [comment]
You originally said pointing up in the air, perhaps even 90 degrees. This bug is actually quite minor and occurs for lots of things if you use Athena.

Report https://springrts.com/mantis/view.php?id=5269

**Comment by ArchShaman** [comment]
This also affects Athena as well.

**Comment by ashdnazg** [comment]
please verify that this is solved in 101.0.1-459-g4dac650

**Comment by GoogleFrog** [comment]
Fixed.
