### ISSUE TITLE
Isle of Grief's /advmapshading (default) mode is broken

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#1431]
See https://snag.gy/LuXW8O.jpg
Looks ok if advmapshading is turned off.

**Comment by ArchShaman** [comment]
![screen00029](https://cloud.githubusercontent.com/assets/7841201/15994970/f44465dc-30c6-11e6-8e4a-6ecc6e2e0705.png)
Not just Isle of Grief.

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=5280

https://github.com/ZeroK-RTS/Zero-K/commit/0e51ef74b5bf3d286d782dc9e924f4f037e85f88
