### ISSUE TITLE
Blastwings stay cloaked while flying

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1435]
I've seen this a lot when testing ais in skirmish mode with new engine. Blastwing lands, cloaks, then starts flying but does not decloak, preventing defenses from targeting it. Confirm?

**Comment by rlcevg** [comment]
http://zero-k.info/Battles/Detail/420825
at ~5th minute few flying cloaked blastwings

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/48d5fdc8324ab8067564141f3e672ffac713d50d
