### ISSUE TITLE
pressing flag icon in chat (near label text) does not update some camera variables

### ISSUE THREAD

**Issue by FuckYouCannonFodderLovers** [ZeroK-RTS/Zero-K#1438]
How to reproduce: left-mouse-click flag in chat, then press ctrl+arrow. Rotating will be performed around position of camera that was before clicking on a flag.

Camera - COFC.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/pull/1439/commits/7d3efb3e5ebc68924ba630bdc337fbfb2e78b991
