### ISSUE TITLE
Chickens don't spawn 

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1442]
Are they finally extinct?

Unluckily the game never ends if the queen doesn't spawn.

Infolog: https://drive.google.com/file/d/0B0FswUjncRt0UHZaRkpOWDlQWlk/view?usp=sharing
Replay: http://zero-k.info/Battles/Detail/421473

**Comment by DeinFreund** [comment]
> [f=0096909] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3179: Invalid unitID given to GiveOrderToUnit()
> stack traceback:
> 	[C]: in function 'spGiveOrderToUnit'
> 	[string "LuaRules/Gadgets/unit_terraform.lua"]:3179: in function 'GameFrame'
> 	[string "LuaRules/gadgets.lua"]:1008: in function <[string "LuaRules/gadgets.lua"]:1006>
> 	(tail call): ?

**Comment by ArchShaman** [comment]
I've seen that error too in my test runs. Seems like this doesn't check if the unitID is valid.

I hate all that setprojectiletracking bloat though.

**Comment by mtroyka** [comment]
note that wolverine mines also stopped spawning properly that game.

**Comment by GoogleFrog** [comment]
Probably fixed more recently.
