### ISSUE TITLE
screen flickers badly when combat units are selected

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K#1446]
cannot give a lot of information about this because i switched to minimal settings after it occured and then it was gone. it seems to be newly introduced in the last 4-5 months. 

only seems to happen for combat units, but not constructors or the com. also it only happens when the game is running, not during pause.

**Comment by dvr333** [comment]
Can you record a video of this happening?

**Comment by sprunk** [comment]
There's already a general ticket for bad UI performance #2170 and this one does not have any specific information.
