### ISSUE TITLE
Vindicator has no range

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1448]
Transport range hax seems to be no longer working.

**Comment by sprunk** [comment]
It seems that gunships will no longer ever lower their altitude for firing, regardless of short weapon ranges.

SetMaxUnitRange does not help either.

**Comment by Licho1** [comment]
Yeh vindicators guns are now useless imo it should be reverted.. or if you don't want it to attack ground, we should just give it AA lasers.

**Comment by sprunk** [comment]
What should be reverted? ZK did nothing, engine changed.

By the way it already has AA lasers https://github.com/ZeroK-RTS/Zero-K/blob/master/units/corbtrans.lua#L99

**Comment by Licho1** [comment]
I believe its range has been nerfed singificantly. Unsure how many years ago.

**Comment by GoogleFrog** [comment]
It has a laser and those all have spherical range. This was not always the case, the consistency was added so that it is able to shoot directly under it but not much further. Perhaps the engine changed somehow to reduce its effective range.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/60cd9035d94babd80d38985b29c2e7bc138fe4c9
