### ISSUE TITLE
Fight command misbehave

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1449]
Eternal chase on fight: http://zero-k.info/Battles/Detail/422532
The side issue of eternal chase is that siege units won't siege (and slashers are totally useless being baited into enemy lines)

Also venom's behaviour wasn't commented: http://zero-k.info/Battles/Detail/418855

**Comment by sprunk** [comment]
Venom (or generally, all EMP units) drop their current Attack order if it's not the last order and the target is stunned. This is engine behaviour.
