### ISSUE TITLE
Pregame music

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#1451]
It's a little disconcerting to have no music in pregame, especially now that the lobby has music. Not sure if this requires Lua-side scripting or if there is a music folder we aren't using.

**Comment by dvr333** [comment]
There are plenty of unused tracks, and if it is technically feasible, then I'll just pick a few.

Also, loading screen music, that occurred to me too after writing the issue. It does seem like some way to cross fade between tracks will help a lot too.

**Comment by KingRaptor** [comment]
Pregame music can be added simply by tossing the tracks into `sounds/music/briefing`.

**Comment by dvr333** [comment]
That's great. Loading screens are probably a bit more difficult, and cross-fading is probably engine-side, but that's a good start.

**Comment by sprunk** [comment]
Duplicate of #1947
