### ISSUE TITLE
Funky dirtbag

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1458]
http://zero-k.info/Battles/Detail/423209
Dirbags walk cool, but can't attack structure from the ground.

**Comment by sprunk** [comment]
Duplicate of #1461

**Comment by mtroyka** [comment]
I don't think that's an accurate assessment. In this case the dirtbags jump onto something, but then land oriented incorrectly and stay that way, unable to attack anything. It's more of a 'crab' behavior than just failing to attack.

**Comment by sprunk** [comment]
Fixed the funky orientation. The inability to attack is not related to funkiness and is covered in #1461.
