### ISSUE TITLE
Scythes, Jacks, Dirtbags fail to attack buildings

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1461]
http://zero-k.info/Battles/Detail/423303

I've seen this issue with AIs as well, where scythes/jacks will walk up to a stinger, attack it once or not at all and then sit there doing nothing until they get killed.

EDIT: I've also seen this happen with fleas and dirtboxes vs mexes. I think it may also be related to another issue I've observed with bandits and scorchers where they stutter when shooting causing them to either shoot very slowly or not at all in certain situations.

**Comment by Anarchid** [comment]
This looks like the unit is trying to reach the center of target, rather than to clip the boundary. Probably an engine issue?

**Comment by sprunk** [comment]
The units do have targetBorder=1 and they used to work previously without getting touched. Looks like engine.

**Comment by Anarchid** [comment]
https://springrts.com/mantis/view.php?id=5345

**Comment by mojjj** [comment]
dirtbags do not even attack lotus. http://zero-k.info/Battles/Detail/433325

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5457

**Comment by KingRaptor** [comment]
Mantis 5457 reports fixed and my own testing indicates likewise.
