### ISSUE TITLE
Enable specmute in all modes

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1462]
Spectator chat seems to cause more problems than it solves. Chesti, firepluk, and co constantly heckle players, others join in because it's not punished. So maybe it's time to remove it. Spectators shouldn't even be speaking anyways, they're watchers, not commentators.

**Comment by db81** [comment]
I think most spec chat is fine and it serves a needed social role. And I don't see it creating problems that are endemic to it, except spec cheat which rarely happens in a major way. I understand that you don't want to see it, but most people tend to like it.

If people heckle games too much, report them, with specmute you can still heckle your team and opponents ingame or be nasty to other specs and people in lobby.

**Comment by GoogleFrog** [comment]
Enable spec chat by default so that players have to make a conscious decision to talk to players. Then give out specmutes for hecklers.
