### ISSUE TITLE
Rejoining as a spectator to a not-yet-started game zoomed to start position

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1464]
I rejoined a game as a spectator and the game had not yet started. My camera was zoomed to focus on a start location. Spectators should not get this zoom.

**Comment by dvr333** [comment]
Odd. I thought https://github.com/ZeroK-RTS/Zero-K/commit/6e830bc76dfb2669163d30f83bc7e1eb0b2ceb70 fixed it.

**Comment by mtroyka** [comment]
I've been seeing this issue as well. It zooms to a startbox at the beginning, but when you try to move the camera at all it snaps back to the middle of the map.
