### ISSUE TITLE
No second commander given in unbalanced teams

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1468]
Spring 103, Zk 1.4.7.0, 4v5 on Serious Host
The smaller team only got 4 commanders in total, with everyone being there on game start.

Replay:
http://www.mediafire.com/download/ahb0izcy58rfqaz/20160721_181548_Desert_Plateaus_103.sdfz

**Comment by sprunk** [comment]
Commander spawning has been touched since then (comshare) so might be fixed, needs to be checked.

**Comment by DeinFreund** [comment]
Bugs don't fix themselves yet
![bug](http://i.imgur.com/staiqEz.jpg)

**Comment by sprunk** [comment]
Apparently this is by design as neither Serious nor Custom room modes give out second comm. (Serious has been removed; whether Custom should is an infra question.)

**Comment by GoogleFrog** [comment]
This looks good as a modoption.

**Comment by Licho1** [comment]
I dont think its intentional its probably caused by proliferation of "modes".
It should only be off in custom i think or as modoption..
