### ISSUE TITLE
Write LUS to add OKP for Hammer, Crabe, Goliath, Ravager and Reaper

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1470]
These units need LUS scripts because then they can have OKP against static targets. See https://github.com/ZeroK-RTS/Zero-K/issues/1469 for implementation.
- [x] Rocko
- [x] Hammer
- [ ] Ravager
- [ ] Reaper
- [ ] Crabe
- [ ] Goliath

**Comment by GoogleFrog** [comment]
Also Crabe.

**Comment by sprunk** [comment]
Also Goliath.

**Comment by sprunk** [comment]
Rocko done: https://github.com/ZeroK-RTS/Zero-K/commit/472c552f4f7ba1ef1b896023fdb2a9c2dfc1b7db

**Comment by DeinFreund** [comment]
Couldn't statics also get OKP against statics? I just watched 2 annihilators firing at a defender.

**Comment by GoogleFrog** [comment]
Yes. Annihilator could even get OKP against mobiles.

**Comment by DeinFreund** [comment]
I'm not sure due to the beam duration often leading to only grazing the enemy unit, it's even more extreme than hlt. Also this issue seems to be about anti static okp only.

**Comment by GoogleFrog** [comment]
It could be given 1000 OKP damage because it is probably going to deal that much damage. If it doesn't kill a 1000 HP unit then another Annihilator can try 1 second later, whatever the unit did to survive probably would have foiled multiple anni shots.

>  Also this issue seems to be about anti static okp only.

This issue isn't even about Annihilator at all since Annihilator has a LUS. You're right, I will probably forget everything off topic that happened here.

**Comment by sprunk** [comment]
Annihilator and Penetrator also done in 4fff63dcc33df05f85a7576415bb3d68826fa27e
