### ISSUE TITLE
Crabe stuck in armored form bug

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1471]
http://zero-k.info/Battles/Detail/425137 (follow my crabe)

In this game, crabe becomes locked in armor up mode, crawling extremely slowly into position.

**Comment by Anarchid** [comment]
Seems to not have been happening since?

**Comment by sprunk** [comment]
Possibly d66bf499ce35f9c020f0107dce2d99ef02ff00fe might help. Regardless, the replay is dead.
