### ISSUE TITLE
Detriment missiles misses

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1474]
Could the missile get unit velocity extrapolation like most other weapons have? Otherwise it even misses enemy striders(slow units) that are just moving in a straight line.

Of course this won't make it magically hit fleas, but at least it should be able to hit slow opponents.

**Comment by GoogleFrog** [comment]
Its a Quake/Impaler sidearm. I don't think it has ever been intended to hit units.

**Comment by DeinFreund** [comment]
It's currently detriment's best anti swarm weapon and also does extremely well against support striders(like Reefballs)

**Comment by GoogleFrog** [comment]
StarburstLaunchers can't have prediction. Spring did not support it last time I checked.

**Comment by mtroyka** [comment]
What detri missile (and impaler and other similar stuff) needs is
A: target priorities that penalize it vs units that are currently moving (ie more than 0 velocity)
and
B: OKP vs buildings.

since most of detri's missiles are wasted doing one of those two things.

**Comment by sprunk** [comment]
Voided by Det rework, no longer has missiles
