### ISSUE TITLE
Zero-K lobby does not show me download progress bars

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#1475]
I just downloaded the new and improved lobby. and jumped into a lobby to download the game and maps. However, I was very confused because there were no progress bars.

http://imgur.com/a/t5O3V

When I attempted to play missions from /campaign they failed to download, however easy chickens downloaded/played successfully, but that's another problem. this problem is about being unable to clear the "failed to download" bars.

**Comment by GoogleFrog** [comment]
Yes, this is a problem. The place to report is here though: https://github.com/ZeroK-RTS/Zero-K-Infrastructure

**Comment by SteelBlueZK** [comment]
Thank you, it seems it was already reported there.
