### ISSUE TITLE
Trazirem wants to make a skin.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1477]
We should probably ask him later to see if he came up with anything good.

**Comment by GoogleFrog** [comment]
[carbon.zip](https://github.com/ZeroK-RTS/Zero-K/files/391023/carbon.zip)

**Comment by sprunk** [comment]
http://zero-k.info/Users/LobbyDetail/Trazirem
First Login: 5 months ago, Last Login: 4 months ago
