### ISSUE TITLE
Submerged units have no los

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1490]
Steps to reproduce:
1) run 103.0 spring, IncultaV2wetV3 map, ZK 1.4.7.1
Enable cheats
2) /cheat
Give few daggers to enemy team above commanders head (commander should be in water)
3) /give 10 corsh
Result: daggers seen only when they attack commander or when they get into 1x1 los square above commander. It still has airlos and can see gunships and planes.

In spring 100.0 all daggers inside commanders los radius are visible.
101.0+ bugged

**Comment by ashdnazg** [comment]
not bugged. it's on purpose.
Water & LoS don't mix now.

**Comment by rlcevg** [comment]
I knew it!
So what's the modrule to get back previous behaviour? It seems very noticable balance change (for nonexistent sea play)

**Comment by GoogleFrog** [comment]
Engine, and I don't think it's bad enough to warrant a gadget.
