### ISSUE TITLE
Puppy reclaim does not remove ground decals

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1493]
http://zero-k.info/Battles/Detail/428624
After puppies eat a dead jumpfac the decal remains.

**Comment by Anarchid** [comment]
I think this also happens for other reclaim. I've seen leftover decals quite a few times without puppies present.

Features cannot have decals anyway; that means by the time puppies were eating it, decal was stuck already.

This is an engine bug. Nothing in ZK changed that would affect this.
