### ISSUE TITLE
factoryspider have invisible walls

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1494]
http://zero-k.info/Battles/Detail/428675 - Crabe stuck and couldn't move for no visible reason.
I guess spider/amph/jump factories have walls to prevent other units from moving through (and bumping at nanoframes), but apparantly it produces new bug (this).
Options:
1) add walls to factoryspider, factoryamph models;
2) Fix passable yardmap. On nanoframe created event place invisible unpassable building-placeholder on top of factory (or yardmap). On nanoframe finished/destroyed remove placeholder;
3) improve engine pathing.

**Comment by Anarchid** [comment]
Walls do not exist: Spring pathing only works on a grid and does not know or care about collision volumes.

Reimplementing spring yardmap mechanics using Lua sounds a bit over the top. This is probably either an engine bug or something that can be workarounded more gently.

**Comment by rlcevg** [comment]
http://i.imgur.com/yl0yR1i.jpg

**Comment by rlcevg** [comment]
Close to option (2) is yardMap = [[oooooo oooooo iiiiii iiiiii iiiiii iiiiii]],
but without additional changes units won't leave factory until it starts closing up.

**Comment by sprunk** [comment]
Why won't they? As far as I know units attempt to leave facs always.

**Comment by rlcevg** [comment]
For yardMap = [[oooooo oooooo iiiiii iiiiii iiiiii iiiiii]] 'i' changes yard to closed/unpassable on factory open (unit creation) and open/passable when factory closed/idle. So unit being finished on upassable terrain.

With yardMap = [[oooooo oooooo cccccc cccccc cccccc cccccc]] other units may try to go through factory and bump/stuck at unfinished nanoframe (engine doesn't go around nanoframes of mobile units).

Current yardMap = [[oooooo oooooo occcco occcco occcco occcco]] - invisible walls.

**Comment by Anarchid** [comment]
I am unsure why is it `occcco`. Presumably the 'walls' keep it safer from units wandering in.

A solution i would try first (tomorrow?) is using a double resolution yardmap (engaged by putting `h` in front of the string) to make walls thinner.

**Comment by GoogleFrog** [comment]
The walls exist to stop enemies trying to path through your factory. This would be detrimental to the enemies because the factory hax widget would force them out and they would become stuck.

**Comment by mtroyka** [comment]
I still think the best solution here is to have spring make yardmaps fully blocked for enemies. Then the walls and closed state wouldn't be needed.
