### ISSUE TITLE
Weird new Starlight firing behaviour

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1502]
Starlight cannot be force fired at the ground. When aimed at units it fires early.
![screen00297](https://cloud.githubusercontent.com/assets/1318249/18231356/2249d2de-72fb-11e6-897f-f465a016f6da.jpg)

**Comment by Anarchid** [comment]
Does firing mean the thick beam thing?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by Anarchid** [comment]
Unsure how to wait for heading to also align.

**Comment by GoogleFrog** [comment]
I don't see how it was hard.
