### ISSUE TITLE
Black Star's startboxes suck

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1510]
It's a featured FFA map so it definitely should.

**Comment by Anarchid** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Configs/StartBoxes/BlackStar.lua exists
TODO: figure out where it goes wrong. Wrong name?

**Comment by mtroyka** [comment]
Ok correction, it actually has startboxes but they're tiny and don't contain any mexes, which is bad for ai and sucks in general.

**Comment by Anarchid** [comment]
For *the* AI, you could see if startboxes exist and contain no mexes; and in that case, tag the mexes on the triangle which contains the start area.

Also: There are other maps like this, for example Geyser Plains.

**Comment by sprunk** [comment]
Read the GRP?

**Comment by Anarchid** [comment]
Ohh, the AI could also read the startpos vertices for such small boxes.

Are there actually GRP for vertices?

**Comment by mtroyka** [comment]
It used to be possible for AI to read startboxes from GRP, but now they're stored in GG instead so only gadgets can read them. So what I did was to add an AI callin to check valid enemy start positions, but since it can't read boxes it can only check mexes, and if the startbox doesn't contain any mexes then it can't infer where the enemy is likely to be.

Fixing the crappy startboxes on all of like 2 maps should also be easier than changing the startbox interface yet again anyway.

**Comment by Anarchid** [comment]
You can check the recommended start positions and taint the triangle upon which they fall if no mexes are tainted.

**Comment by sprunk** [comment]
> It used to be possible for AI to read startboxes from GRP, but now they're stored in GG instead so only gadgets can read them.

Huh? They're in GRP https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/start_boxes.lua#L161

**Comment by mtroyka** [comment]
>>Huh? They're in GRP https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/start_boxes.lua#L161

It does put -something- in GRP, but that something is just a null placeholder and doesn't give any real information about the startboxes. Basically it always says that the number of vertices is 0 and no actual vertices are listed.

**Comment by sprunk** [comment]
Alright, I'll go and fix that.
