### ISSUE TITLE
Ctrl + Area Rez

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1516]
Currently CTRL + Area Rez makes it so that wrecks are not ignored for being actively reclaimed. This isn't particularly useful, when doing a "fight" over the wreck the rezzer will pretty much pump metal to the reclaiming team.

Consider whether it would be better if CTRL meant that only wrecks with full metal value are considered for rezzing. This guarantees zero metal spending (current behaviour without CTRL is to refill wrecks which are partially reclaimed but not actively being reclaimed).

**Comment by sprunk** [comment]
Or better yet, have the "only fresh wrecks" be the default and "also refill half-eaten ones" be the CTRL behaviour.

**Comment by Licho1** [comment]
It could also be so that ress aborts active reclaims of allies.

**Comment by sprunk** [comment]
It already does that for Area-reclaim.
