### ISSUE TITLE
Decoration Handler Error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1517]
[f=0000051] [cawidgets.lua] Error: Error in UnitCreated(): [string "LuaUI/Widgets/unit_decoration_handler.lua"]:59: bad argument #1 to 'FileExists' (string expected, got nil)
[f=0000051] [cawidgets.lua] Error: Removed widget: Decoration Handler

**Comment by Licho1** [comment]
Was it a skirmish game?

**Comment by GoogleFrog** [comment]
No. It was a MP game. Perhaps the animated clan icons broke the decoration handler?

**Comment by Licho1** [comment]
Decoration is not icons, decorations should be commander skins for kudos.

**Comment by sprunk** [comment]
There is a comm overhead clan icon as a kudos thing, and it is handled by Decoration Handler widget.

**Comment by GoogleFrog** [comment]
Fixed.
