### ISSUE TITLE
When starting latest dev engine on red comet invalid loading screen is shown

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1518]
1) get chobby fresh
2) go skirmish red comet
3) wait for game download, add cai
4) start

REsult->
http://i.imgur.com/MSRDkUO.png

**Comment by sprunk** [comment]
Still happens?

**Comment by Licho1** [comment]
Is there are a reason to think it does not?

2016-10-01 1:15 GMT+02:00 sprunk <notifications@github.com>:

**Comment by sprunk** [comment]
New chobby version happened meanwhile

**Comment by sprunk** [comment]
No longer seems to happen.
