### ISSUE TITLE
Slasher fight command gives permanent attack commands

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1521]
They should be cancelled once the slasher has come to a stop, so it chooses targets by priority. 

I.e. if it gets an attack command on a solar, stops to shoot at it and then a glaive pops up, it should target the glaive instead of focus firing the solar.

**Comment by sprunk** [comment]
#1413

**Comment by DeinFreund** [comment]
I didn't say focus solars, just kill solars.

**Comment by mtroyka** [comment]
#1413 should have been fixable just by removing nochase. That shouldn't affect target priorities though, but slashers on fight do seem to stick to one target even if better targets come within range, which is bad.

**Comment by GoogleFrog** [comment]
Fixed in engine.
