### ISSUE TITLE
Stuck air units

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1529]
http://zero-k.info/Battles/Detail/431038
At 2:30 a swift is losing control, flying of the map and never returns
Hint: select swift, press 'ctrl+z' to select all swifts, press 'shift' to look at commands, see the command going from the outer space.

**Comment by rlcevg** [comment]
I didn't double check, but from orders given to aa units (underground) https://github.com/ZeroK-RTS/Zero-K/issues/1194 can be related

**Comment by sprunk** [comment]
Reopen if reproduced on a newer engine. `103.0.1-131-g5a68792` is both no longer available for download and quite old so the bug might've since been fixed.
