### ISSUE TITLE
Multi-Frame Lasers leading targets -> miss

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1538]
They seem to try to aim in front of units to have them run through the laser. This works for normal speed ground units, but leads to Stingers/Annis regularly missing air units that should be easy food for an instant-hit laser weapon.

Could the behaviour be changed to try to hit units at the first frame instead of last/center frame?

**Comment by Anarchid** [comment]
Leading is entirely engine authority.

**Comment by DeinFreund** [comment]
We could just reduce the beamtimes, this would also make damage more consistent against big units. Is there any problem with a 0.2 second hlt?

**Comment by Anarchid** [comment]
I think at that level, it would be better to use what ZK calls "particle beams" and "disrupters" - that is, single-frame beam weapons with no duration but a lasting visual effect.

**Comment by DeinFreund** [comment]
Not sure if that's what's desired for penetrator/anni.

**Comment by mtroyka** [comment]
Most of the 'long burst' lasers have the capacity to hit units behind the one they're aiming at if that unit dies or moves out of the way. Making them particle beams would remove that and make those weapons significantly worse.

Also while leading the target -is- an engine thing I believe there's a setting somewhere for how much to lead, so it should be fixable.

**Comment by sprunk** [comment]
Yes. ZK *can* reduce engine leading through appropriate WD tags.

**Comment by DeinFreund** [comment]
What are those tags?

**Comment by Anarchid** [comment]
Beamtime is the only one i can think of.

**Comment by Anarchid** [comment]
Low `leadlimit` might work.

* float `leadLimit`  default: -1.0 

 *Limits the maximum distance a unit will lead a target. The default of -1 allows an infinite distance*.
* float `leadBonus`  default: 0.0 

 *Controls how experience boosts the weapon's target leading. Is multiplied with the unit's experience and added to the leadLimit.*
* float `predictBoost`  default: 0.0 (0.5 for burnblow = true weapons)

 *Controls how well the weapon predicts unit speeds. Works in a similar way to targetMoveError except that it is 1-dimensional. This tag spreads the shots in a line based on the direction of the target whereas targetMoveError spreads the shots all around based on the movement.*

**Comment by sprunk** [comment]
As far as I remember this is by design. Fast jinking units might dodge a long beam entirely.

**Comment by DeinFreund** [comment]
Isn't the design idea to have units try their best to be as effective as possible? A widget could achieve better results through manual targeting, so either a mechanic has to prevent accurate aiming or it should be set to aim properly on its own.

**Comment by GoogleFrog** [comment]
The beam times will not be shortened. This inconsistency against targets which can move out of the beam is by design. However, the stupid behaviour is worth removing.

**Comment by GoogleFrog** [comment]
Lets call lasers tracking lasers (no reload time), burst lasers (for particle beams and AA) or beam lasers (for those that burst a duration beam) for the three types of lasers.

Part of the design of beam lasers is to make them bad against fast units. A low duration Penetrator would instantly kill Wyvern. With the current settings, a full-speed Wyvern only spends 5 frames at any fixed location so can only take 500 damage from a Penetrator (unless it flies right at it). Another large part of the design is that long duration beams are cool and physicsy.
