### ISSUE TITLE
BB prioritizes Claws

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1540]
Shooting at mines should be lowest priority

**Comment by sprunk** [comment]
Related #1537

**Comment by mtroyka** [comment]
Derp, turns out mines did not have any penalty for target priorities. I'll make it so that mines are treated as worse than unarmed, since in cases where it makes any difference at all then they really are the worst targets.

**Comment by GoogleFrog** [comment]
Fixed I think.
