### ISSUE TITLE
Add metal spot textures for maps that lack them

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1543]
Smoth has a widget and some images which draws metal spots. This widget could easily be adapted to draw metal spots for our maps which lack them. 

https://springrts.com/phpbb/viewtopic.php?f=13&t=35575

**Comment by Anarchid** [comment]
Alternative: using the feature mexes like on yak maps and the recent sprung maps.

**Comment by Anarchid** [comment]
![crystals](https://cloud.githubusercontent.com/assets/3822768/19089265/39cbf272-8a82-11e6-9925-e75b7f0c2421.png)

I'm going to add decals to all existing feature mex thingies ("coral", "crystal", and "eldritch").

Is it better to modify maps with unmarked mexes themselves (if they are featured), or add a gadget to ZK?

**Comment by Licho1** [comment]
If gadget is 0 performance cost then gadget, otherwise modify maps imo.

**Comment by Anarchid** [comment]
Performance cost is equal in both cases. 

Modifying maps inside ZK (like we do for metalmap overrides) is untidy but convenient because re-releasing maps is often uncomfortable.

**Comment by GoogleFrog** [comment]
Feature mexes have trouble conforming to terrain changes. The feature would have to be fairly small, maybe even invisible, and apply a ground decal.

**Comment by Anarchid** [comment]
Thesis: mexes on slopes should not exist.

**Comment by Anarchid** [comment]
Fair enough; pure decals can also work. But i don't think i've met a really bad case in the wild yet: the features are prevented from ever moving by being made non-colliding with everything, and to make the feature tilt, the middle vertex needs to be affected by deformation, which nobody wants to do because they want to build a mex there.

**Comment by GoogleFrog** [comment]
@Anarchid never did anything. I have added the widget.
