### ISSUE TITLE
Bugged Commanders

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1548]
I haven't confirmed the extent of this, but in skirmish mode I noticed that if you select engineer trainer you get a bugged commander instead. I don't know if it only applies to engineer trainer and I don't know if it also applies in multiplayer or not. The bugged commander is listed as having a bunch of different weapons, none of them work, and also does not get an economy pack.

**Comment by KingRaptor** [comment]
I just tried an Engineer Trainer in skirmish and it appeared to work correctly; it had the economy pack and could be upgraded to use a missile launcher.

Assuming any underlying issue was fixed in the interim; reopen if observed again.
