### ISSUE TITLE
Add commshare mode

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1557]
There should be a modoption which enforces one team per allyTeam. This can be done at the start of the game with Spring.AssignPlayerToTeam.

**Comment by Licho1** [comment]
Autohost can also force it and I plan to force it for missions (COOP missions one team humans).
It would be best if this could be changed mid - game, let people join together at will.

**Comment by ArchShaman** [comment]
Ah, this. I still have code left from my attempt at it. Never finished it because I had difficulties implementing the whole function thing at the time. Will reattempt it after midterms week.

**Comment by ArchShaman** [comment]
You can find the last version I have here.
https://github.com/ArchShaman/Zero-K/blob/Share-mode/LuaRules/Gadgets/game_share_mode.lua

This includes the entry points and etc. Probably doesn't fully work but the frame work is there. I'll work on it next week.

**Comment by Licho1** [comment]
UIs for such things should be integrated with other things. In this case probably with player list.

**Comment by GoogleFrog** [comment]
Don't worry about income changing. It's easy.

**Comment by sprunk** [comment]
Commshare lives. Problems exist but these have separate tickets .
