### ISSUE TITLE
com immobilized in rezzed fac model

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#1562]
http://zero-k.info/Battles/Detail/433265

my com was standing in shady water inside a wreck of a hover fac. when rezzing named fac, the com found itself inside the fac hitbox trapped, not able to move. (it then died on site to gunships)

**Comment by KingRaptor** [comment]
As I understand it, fixing this would require making hover wrecks not block, or a gadget to forcibly expel anything stuck in a factory. (The latter would be useful for factory-exit-clogging scenarios as well)

**Comment by Sgathec** [comment]
What's the desired solution? A blocking wreck or a gadget?

**Comment by Sgathec** [comment]
A blocking wreck would solve this particular problem, right?

**Comment by Sgathec** [comment]
A unit also got stuck inside a ship factory in my test.

**Comment by GoogleFrog** [comment]
When a structure is resurrected push all the units within it to the edges. That should fix all these cases.

**Comment by Sgathec** [comment]
Ok, I'll do that.

**Comment by Sgathec** [comment]
What if there's no room around the structure?

**Comment by Sgathec** [comment]
Do units get stuck into structures due to the unpathable ground/water that is beneath them? The purple shape that Alt+B brings up is not the reason.
