### ISSUE TITLE
Lag/AFK should increase unit limit of the recipient

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#1566]
We've recently played some speedmetal games with the maxunits set
When the highest elo player receives units due to AFK/Lag of his teammate he goes well beyond the set unit limit and has no way to recover except self-d/share units to someone else.

**Comment by GoogleFrog** [comment]
I don't think spring currently supports transferring unit limits.

**Comment by let4be** [comment]
Could unit limit be implemented artificially? i.e. check count of owned units via LUA Gadget && cancel production orders/share commands from other players
Afaik current unit limit may be bypassed by sharing units
Though I'd be more interested to see proper solution via engine

**Comment by Licho1** [comment]
I would rather see max unit limit increased or removed completely. 500 per team means each player in a  big game has less units than SC game.

**Comment by GoogleFrog** [comment]
Unit limit cannot be implemented artificially because the limit exists in the engine. Spring will block unit creation for teams which exceed the unit limit.

**Comment by let4be** [comment]
It looks like you never read what I write @Licho1 ...
I was talking about manually set unit limit(how can it be increased?) and speed metal games

**Comment by let4be** [comment]
sad
