### ISSUE TITLE
Upgrade UI selector window doesn't properly store position

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1567]
It somehow always likes to pop up at some random location, like behind the minimap or nearly off screen in the top right corner. I can usually reposition it with ctrl+f11, but next game it will again be in an annoying position. It would also make sense to just always show it right of the main window, keeping the two together.

I'm talking about this window:
![1](https://i.imgur.com/v2QJVaG.png)

**Comment by Licho1** [comment]
Yeah it shows below other ui elemenets and does not remember position.
It should imo go into middle - like a dialog - and show on top.

**Comment by sprunk** [comment]
e0eff807be8b3277a77c05793f8f214942ddbe46
