### ISSUE TITLE
Delux playerlist error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1569]
http://pastebin.com/cRX2QUjt

[f=0052020] [cawidgets.lua] Error: Error in PlayerChanged(): [string "LuaUI/Widgets/gui_chili_deluxeplayerlist.lu..."]:1260: attempt to index field '?' (a nil value)

**Comment by sprunk** [comment]
Deluxe is deprecated.

**Comment by GoogleFrog** [comment]
Patchable crashes are still reportable since it's a common widget currently. It just should not have any new features or insufficiently widespread rewrites.

**Comment by sprunk** [comment]
?

**Comment by KingRaptor** [comment]
Is Deluxe still considered under maintenance with Tab playerlist being enabled by default?
