### ISSUE TITLE
Balance: Gnat

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1572]
Gnat needs a look at. The experiment from a few years ago of inaccuracy and high damage has yielded that result that it is too inaccurate.

Goals:
 * Anti-heavy stunner which must maintain a presence to keep the unit stunned.
 * Works well from Reaper to Detriment level. Works ok for Ravager up.
 * No dominating the early game with rushes.

Current ideas:
 * Increase accuracy. Perhaps not all the way. Missing small raiders is still desirable for game opening balance. Missing Defender and LLT would be good too as that makes the early game resilient to OP Gnats. It should almost always hit Ravager.
 * Increase weight. This is another rush prevention technique and something which makes it worse against the common unit costs (150 to 500).
 * Paralysis time to 1s, reload time to 0.9s. This is an unsubtle implementation of requiring proximity to keep something stunned. Watch out for situations where a high health unit can regen the DPS of a single Gnat and make sure this change works.

**Comment by sprunk** [comment]
On weight increase: GS already has Banshee and Rapier in the next weight "tier". How about swapping weight with one of them? Having a swarming combat GS at that weight level could give Cobra a role (which a non-owled Gnat wouldn't do at current weight since you dont raid bases with antiheavy stunners).

**Comment by Licho1** [comment]
Imo it can be light if you limit its "stun" to single unit and need active banshee to maintain it.

**Comment by sprunk** [comment]
Gnat was touched, but not a redesign so not closing the ticket 49d72c9ebf447884a93fe69fe69e983d4388072d

**Comment by sprunk** [comment]
Gnat was touched a bunch of times so it seems like we're not too unhappy with it (also ticket is ancient and buried behind 30 pages)
