### ISSUE TITLE
Make dynamic lights fade on impact OR add explosion lights

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1578]
Currently dynamic lights fade immediately after the projectile disappears. They should be improved to fade out for a few frames after the projectile disappears.

**Comment by Anarchid** [comment]
Wouldn't adding explosion lights be better?

**Comment by GoogleFrog** [comment]
There is barely a difference. Do one or the other.

**Comment by Anarchid** [comment]
This seems to have been resolved with fade on impact.
