### ISSUE TITLE
Solve factory blocking

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1586]
It is possible, and reasonably easy, for new players to block their own factories. This should be fixed somehow, Perhaps a large open area in front of each, achieved with an extended footprint and model offset. Changing game mechanics is acceptable to fix this as its quite a problem.

Todo:
- [ ] Vehicle factory - remodel
- [ ] Tank factory - remodel
- [x] Hover factory - apply the Shieldbot and Cloakbot factory footprint extensions.

**Comment by GoogleFrog** [comment]
Our factory models are also a bit hodgepodge.

I really like the Cloaky, Ship and Gunship factories because they look like decent models and fit the structure of the thing they produce. Cloaky factory is also small enough to never have a problem with things walking into the factory. The Hover factory is also quite good in this regard.

The Vehicle, Tank and Plane factories look quite good in a way similar to Cloaky, Ship, Hover and Gunship. They are pretty OTA but probably fine. A consistent redo of factories should look at them again.

Shield, Spider and Amphib factories look like placeholders. They also look far too open for their actual pathability and we can't increase their pathability at the risk of units getting stuck in the factory or blocking it. Jumpy looks less like a placeholder but is also too open.

**Comment by GoogleFrog** [comment]
Factories have a few issues:
 * Allied units can accidentally walk into your factory and/or get stuck or stop it from building units. This is especially common for commanders walking around early in the game.
 * Enemy units can get stuck due to prevent lab hax while trying to walk through a factory.
 * Factories can be placed such that the exit is blocked.
 * Structures can be placed after factory placement in a way that blocks the exit.

It's important that these issues are solved because it seems to be a major point of frustration. Games with simple unit spawning at the edge of their factories (*craft, basically every game really) solve the issues by simply checking everywhere around the factory and spawning the unit in a valid location. TA and TA-derived games tend to have multiple exits for their factory to solve the blocking problem. Supcom goes further and prevents structures from being built so close that units cannot walk between them (maybe?).

We can think far outside the box for ways to implement factories. Factories can be comprised of multiple fake units, some which construct and others which form a boundry/target area. One fairly resilient method would be an unselectable striderhub which takes its orders from a selectable fake factory which exists for the purpose of sending orders to the striderhub and keeping track of waypoints. The striderhub would automatically place the nanoframe in some predictable and smart way. I don't think this is a good solution but its probably the kind of place we need to think about.

**Comment by Licho1** [comment]
Factory placed so that exit is blocked is also reverse issue - we should block structure placement in front of existing factory. That is what was going on on GDS - people put one factory and then put second so that they block exit of first.

**Comment by sprunk** [comment]
Related: #1170 #1494

**Comment by GoogleFrog** [comment]
I have implemented the technical side of the solution for Spider, Jumpy, Amph and Ships. https://github.com/ZeroK-RTS/Zero-K/commit/10ecc36fa62dc78337de532042ef27af0efe7efa

The solution I have chosen is to allow factories to have open sides and decree that every factory must have enough of an open side to allow its largest unit to escape a wall of solars across the front of its factory. Prevent Lab Hax required modification to make this work. The gadget will still be required because:
 * It needs to block structure placement inside a factory. The same commit adds this feature. Spring does not block construction inside a factory and using build mask would allow for pathmap LOS hax. The solution I chose was to block placement in allied factories with AllowCommand.
 * Pathing with factory yardmaps is the dodgyest part of Spring pathing. It is possible to get a unit quite deep in the 'solid' part of the factory. This does not cause units to become stuck so I did not enable prevent lab hax for allied units.
 * Features can fall into factories and block production. Prevent Lab Hax moves features out of factories.

I gave the factories fully blocking yardmaps when not constructing. This is partially to make the UI better when placing structures around inactive factories and it also reduces the likelyhood of your own units blocking production.

**Comment by GoogleFrog** [comment]
@Anarchid said he would remodel factories as required. Cloaky, Shield, Veh, Tank and Hover will require a remodel to follow the new rules. Amph and Spider could do with a remodel. The models may only need to have open edges equal to the size of their largest unit so there is some leeway for some factories.

**Comment by GoogleFrog** [comment]
A screenshot from local noob testing. Ticket is important.

![screen00422](https://user-images.githubusercontent.com/1318249/28166981-4706c42a-681d-11e7-8c7f-644714e1d255.jpg)

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/9ea8cfa02651ebc5a00794b5efb1548aa255fcf6, https://github.com/ZeroK-RTS/Zero-K/commit/2e507bc7eb3e7725559050d72b83b411edc88b48.
