### ISSUE TITLE
Block plop on mexes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1587]
Factories should not be ploppable on mexes. Perhaps nothing should be buildable on mexes at all. There could be some super-hardcore mex-blocking strategy so I don't want to fully disable construction on mexes. It could be a menu option.

**Comment by Licho1** [comment]
There is no known mex blocking strategy. Imo block all constructions there.

**Comment by GoogleFrog** [comment]
The lack of a strategy at the moment does not mean one couldn't exist. I think mex blocking is the sort of creative thing we should allow. Maybe put Razors on a megamex if you're about to lose the territory. However, this option is much less important than new-player usability so at most I would want some sort of manual override option/key which allows for mex blocking. The defaults should be not to block mex spots as it is far more likely to happen accidentally than on purpose.

**Comment by Licho1** [comment]
I think its extremely silly to allow that. Blocking enemy makes no sense with any unit, they all cost metal which is lost while mex is likely to recover cost very quickly.
Its only use is to troll allies because they have no way to remove it. 
It's not a creative strategy, at best its pretty uncreative trolling.

**Comment by Anarchid** [comment]
>  Blocking enemy makes no sense with any unit, they all cost metal which is lost while mex is likely to recover cost very quickly.
Fairly certain Dirtbags are cheaper.

**Comment by GoogleFrog** [comment]
Razor is cheap compared to the amount of time they can take to kill. There would be situations when they are cost effective and, ideally, it would be allowed as it is a creative strategy. Potential trolling is not an excuse, I have not seen mex blocking used to troll allies and there are already plenty of other ways to troll.

Anarchid you're wrong. Mexes can be built on any terrain.
