### ISSUE TITLE
Generalize lagmonitor to deal with sharemode

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1590]
I realized that lagmonitor does not know about team sharing at all. The gadget doesn't do anything when disabled so can be left in. Lagmonitor needs to be written in terms of players, not teams, for share mode to work correctly.

**Comment by sprunk** [comment]
>I realized that lagmonitor does not know about team sharing at all.

Is that from testing? Looking at the code it seems like it knows teams can have multiple players and should only tag a team AFK if all its players are AFK: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/game_lagmonitor.lua#L302-L315

**Comment by GoogleFrog** [comment]
No, there was no mention in the sharemode PR of lagmonitor so this is a ticket to do testing and make the required changes. Some change will be required because it is lagmonitor which must tell overdrive how many players are on an allyTeam and how many resources to give each team.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/5d8902d30c5e3a6f0189bdf779bc9b829abf647e
OD can now be told how many shares a team has (so far lagmonitor will only supply 0 or 1).

**Comment by sprunk** [comment]
It is done.
