### ISSUE TITLE
Rename the unitdefs

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1596]
The current unitdefs could be renamed to be more consistent. Two main advantages:
 * More convenient developing.
 * Whitewashing of mod-status history.

The already agreed upon method of naming units is ChassisRole and many of the more recently added units conform to it. Renaming was suggested in the past but could not be done because systems such as modstats and missions would break. At the moment modstats doesn't work and we may have relatively few working missions so now would be a time to rename the units. Places to rename:
 * ZK lua (easy find and replace).
 * Third party AI configs (just tell them rename is occurring)
 * Missions.
 * Anything else?

User effect:
 * Reset of everyones persistent build spacing and persistent build height settings. Minor.
 * If anyone has directly bound the construction of a unit to a key then they will need to update. No units are bound to keys by default.
 * Some obscure Ctrl+Key selection keys would break, for example the one that selects Vultures.
 * People who have custom widgets may need to change them if they hardcode the units they handle.

It looks like a bit of work but, if it should be done, it should be done sooner rather than later.

**Comment by Licho1** [comment]
Also stuff in infrastructure, unit icons, avatars, unitguide and some
currently unused things - modstats, unlocks.

2016-11-16 4:39 GMT+01:00 GoogleFrog <notifications@github.com>:

**Comment by mtroyka** [comment]
On one hand that's tempting, since zk units are often labeled 'core' and 'arm' when we no longer have those factions and a lot of units have little or no relationship to the historical names they carry. It certainly would make things easier on new devs. On the other hand it might break a lot of random things and the damage is difficult to predict.

Also it might be a good idea to reorganize unitdef params, since the default alphabetical order with no spacing/groups is about as good as random if you're trying to edit them.

**Comment by Aquanim** [comment]
Fixing stuff that is broken by this will mean more work in the short term, but in the long run I think this will save a worthwhile amount of time and effort.

**Comment by sprunk** [comment]
There seems to be agreement to do this and changes in this direction have been made (in the recent sea refactor) so any externals are already bork.

**Comment by Anarchid** [comment]
What should be the scheme for economy, defense, intel, and superweapon buildings? 

While turrets and eco are reasonably straightforward (`turretriot`,`turretcancer`, `energysolar`,`energywind`,`energyfusion`), superweapons and striders are more complicated and tend to have proper names in their defnames (`reef`, `dante`, `funnelweb`, `zenith`). 

So for those i see three options:
- chassis prefix with proper name (`superzenith`, `striderdante`)
- chassis prefix with role (`supermeteor`, `striderriot`)
- standardize on proper names (`zenith`, `dante`)

**Comment by Licho1** [comment]
proper names..

**Comment by GoogleFrog** [comment]
I thought that Name was a good idea but now I think ChassisName is a good idea. Prefixing all striders by Strider groups them and makes them more searchable. Here is a potential rule:
 * If the unit has a clear role then call it ChassisRole.
 * Otherwise call the unit ChassisName.
 * The mobile chassis are cloak, shield, veh, hover, gunship, plane, spider, jump, tank, amph, ship, strider and drone.
 * The structure chassis are factory, econ, defense, utility, mine. They could just be based on menu tab.

**Comment by GoogleFrog** [comment]
Here is a list:
 - [ ] amgeo -> energyheavygeo
 - [ ] amphartillery -> ampharty
 - [ ] amphraider -> grebe
 - [ ] amphraider2 -> amphimpulse
 - [ ] amphraider3 -> amphraid
 - [ ] arm_spider -> spidercon
 - [ ] arm_venom -> spideremp
 - [ ] armaak -> jumpaa
 - [ ] armamd -> staticantinuke
 - [ ] armanni -> turretantiheavy
 - [ ] armarad -> staticheavyradar
 - [ ] armartic -> turretemp
 - [ ] armasp -> staticrearm
 - [ ] armbanth -> striderskirm
 - [ ] armbrawl -> gunshipsupport
 - [ ] armbrtha -> staticheavyarty
 - [ ] armca -> planecon
 - [ ] armcir -> turretaafar
 - [ ] armcomdgun -> striderantiheavy
 - [ ] armcrabe -> spidercrabe
 - [ ] armcsa -> athena
 - [ ] armcybr -> bomberheavy
 - [ ] armdeva -> turretriot
 - [ ] armdeva -> turretriot
 - [ ] armestore -> energypylon
 - [ ] armflea -> spiderscout
 - [ ] armfus -> energyfusion
 - [ ] armham -> cloakarty
 - [ ] armjamt -> staticjammer
 - [ ] armjeth -> cloakaa
 - [ ] armkam -> gunshipraid
 - [ ] armmanni -> hoverarty
 - [ ] armmerl -> vehheavyarty
 - [ ] armmstore -> staticstorage
 - [ ] armnanotc -> staticcon
 - [ ] armorco -> striderheavy
 - [ ] armpb -> turretgauss
 - [ ] armpw -> cloakraid
 - [ ] armraven -> striderarty
 - [ ] armrectr -> cloakcon
 - [ ] armrock -> cloakskirm
 - [ ] armsnipe -> cloaksniper
 - [ ] armsolar -> energysolar
 - [ ] armsonar -> sonar
 - [ ] armsptk -> spiderskirm
 - [ ] armspy -> spiderantiheavy
 - [ ] armstiletto_laser -> bomberdisarm
 - [ ] armtick -> cloakbomb
 - [ ] armwar -> cloakriot
 - [ ] armwin -> energywind
 - [ ] armzeus -> cloakassault
 - [ ] assaultcruiser -> shipassaultheavy
 - [ ] asteriod -> asteriod
 - [ ] attackdrone -> dronelight
 - [ ] battledrone -> droneheavy
 - [ ] benzecom1 -> benzecom1
 - [ ] blackdawn -> gunshipassault
 - [ ] bladew -> gunshipemp
 - [ ] blastwing -> gunshipbomb
 - [ ] bomberassault -> bomberassault
 - [ ] bomberdive -> <remove>
 - [ ] bomberlaser -> bomberlaser
 - [ ] bomberstrike -> bomberstrike
 - [ ] cafus -> energysingu
 - [ ] capturecar -> vehcapture
 - [ ] carrydrone -> dronecarry
 - [ ] <skip chickens>
 - [ ] cobtransport -> cobtransport
 - [ ] <skip comms>
 - [ ] coracv -> tankcon
 - [ ] corawac -> planescout
 - [ ] corbhmth -> staticarty
 - [ ] corbtrans -> gunshipheavytransport
 - [ ] corcan -> jumpassault
 - [ ] corch -> hovercon
 - [ ] corclog -> shieldscout
 - [ ] corcom1 -> corcom1
 - [ ] corcrash -> shieldaa
 - [ ] corcrw -> gunshipkrow
 - [ ] cordoom -> turretheavy
 - [ ] core_spectre -> shieldshield
 - [ ] corfast -> jumpcon
 - [ ] corfav -> vehscout
 - [ ] corflak -> turretaaflak
 - [ ] corgarp -> veharty
 - [ ] corgator -> vehraid
 - [ ] corgol -> tankantiheavy
 - [ ] corgrav -> turretimpulse
 - [ ] corhlt -> turretheavylaser
 - [ ] corhurc2 -> bomberriot
 - [ ] corjamt -> staticshield
 - [ ] corlevlr -> vehriot
 - [ ] corllt -> turretlaser
 - [ ] cormak -> shieldriot
 - [ ] cormart -> tankarty
 - [ ] cormex -> mex
 - [ ] cormist -> vehsupport
 - [ ] cornecro -> shieldcon
 - [ ] corned -> vehcon
 - [ ] corpyro -> jumpraid
 - [ ] corpyro2 -> jumpraid2
 - [ ] corrad -> staticradar
 - [ ] corraid -> vehassault
 - [ ] corrazor -> turretaalaser
 - [ ] correap -> tankassault
 - [ ] corrl -> turretmissile
 - [ ] corroach -> shieldbomb
 - [ ] corsent -> tankaa
 - [ ] corsh -> hoverraid
 - [ ] corshad -> bomberprec
 - [ ] corsilo -> staticnuke
 - [ ] corsktl -> jumpbomb
 - [ ] corstorm -> shieldskirm
 - [ ] corsumo -> jumpsumo
 - [ ] corthud -> shieldassault
 - [ ] corvalk -> gunshiptransport
 - [ ] corvamp -> fighterheavy
 - [ ] fighterdrone -> dronefighter
 - [ ] firewalker -> jumparty
 - [ ] funnelweb -> funnelweb
 - [ ] geo -> energygeo
 - [ ] gunshipsupport -> gunshipskirm
 - [ ] heavyturret -> sunlance
 - [ ] logokoda -> tankraid
 - [ ] missilesilo -> staticmissilesilo
 - [ ] missiletower -> turretaaclose
 - [ ] nsaclash -> hoverskirm
 - [ ] panther -> tankheavyraid
 - [ ] puppy -> jumpscout
 - [ ] slowmort -> jumpskirm
 - [ ] spherecloaker -> cloakjammer
 - [ ] spherepole -> cloakheavyraid
 - [ ] tawf114 -> tankriot
 - [ ] trem -> tankheavyarty

**Comment by mtroyka** [comment]
there are some things that I don't particularly like about some of the names.
-Adding 'static' to the names of all the statics is kind of redundant and pointless.
-Adding 'energy' to every energy building is equally so. It's just more typing.
-Calling advgeo and advradar 'heavy' is misleading, and also more typing than 'adv'.

Some suggestions:
geo -> geo
amgeo -> advgeo
armanni -> turrettachyon
armarad -> advradar
armasp -> airpad
armestor -> pylon
armfus -> fusion
cafus -> singu
missilesilo -> tacsilo
corsilo -> stratnuke

most of the mobile units are good, a few suggestions though:
core_specter -> shieldwalker (shieldshield is kind of.. lol)
corgarp -> vehskirm (wolv is more skirm than arty, and then impaler can be veharty with no 'heavy')
trem -> tanksatarty (it's not really heavy, just saturation)

also don't forget this will break tactical ai, target priorities and possibly other gadgets/widgets.

**Comment by Aquanim** [comment]
Adding "static" to the name of all the statics makes it easier to search for that unitdef specifically, as opposed to wherever that name is mentioned. (The characters 'geo' appear in a LOT of places.)

**Comment by GoogleFrog** [comment]
No name should be a subword of a word that is likely to appear anywhere else. Adv is actually more typing because adv shares its first letter with assault, arty and aa so will fail at tab completion.

**Comment by mtroyka** [comment]
tab completion in what tool? I'm not aware of any that would meaningfully fill in unit def names. Also 'assault' 'arty' and 'aa' appear at the end of names but not at the beginning, so I don't see that working in any case.

As for 'static' and 'energy', you could use stc and en instead, as in 'stcstorage' and 'engeo'.

**Comment by sprunk** [comment]
>tab completion in what tool? I'm not aware of any that would meaningfully fill in unit def names.

Engine `/give`.

**Comment by KingRaptor** [comment]
Rename has been implemented in stable.

**Comment by sprunk** [comment]
Many models are still named `arm*` and `cor*` so the whitewashing of mod status is not fully done.

Some existing units don't seem to use the naming scheme (`mahlazer`, `zenith`, `raveparty`).

Some unused units also don't fit. For example Grebe is just called `grebe` (not `amphraid2`). Test units (`tiptest`, `empiricaldpser` etc) were untouched, could get called `testbla`. Some chicken units also don't use chicken (`roost` -> `chickenroost`, `thicket` -> `chickenthicket`).

**Comment by GoogleFrog** [comment]
The main aim was convenience. I didn't touch test units and chickens due to a lack of a scheme. There are some oversights in the striders and superweapons but they are minor.
