### ISSUE TITLE
mason build script issue

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1614]
There seems to be an issue with mason's build script which prevents it from placing nanoframes under certain conditions. They just get stuck sitting there looking at the job. I haven't seen this happen with any other workers, so I assume that it's mason-specific.

**Comment by sprunk** [comment]
Presumably fixed https://github.com/spring/spring/commit/251c631d13b12154ad6178131c80deec5500f3e2
