### ISSUE TITLE
New UI: Extended playerlist

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1620]
The new UI has a playerlist but its in a pretty poor spot for screen widths below 1650. Also, a screen of 1920 would be required to use deluxe playerlist.

The playerlist should be at least partially replaced with a button on the top left which shows a large, FPS-style, playerlist in the middle of the screen. The whole H share box should be replaced by this screen.

The relatively small playerlist could also be placed in the top left of the screen and hidden with a button. This top left button to toggle the playerlist could even exist for a playerlist regardless of where it is.

**Comment by Licho1** [comment]
Scrap player list, waste of space and performance.
Make on-demand player list (when you hold some key) that is fullscreen and shows more data.

**Comment by sprunk** [comment]
#1869
