### ISSUE TITLE
Requesting Push Access

### ISSUE THREAD

**Issue by PicassoCT** [ZeroK-RTS/Zero-K#1622]
Can i have push access, to upload the created bigNukeLand CEG?

**Comment by PicassoCT** [comment]
Yep, i guessed the answer

**Comment by GoogleFrog** [comment]
I'd prefer a PR.

**Comment by GoogleFrog** [comment]
I've added the effect, I'm not sure what it should be applied to though.

**Comment by Licho1** [comment]
Nuke ?

**Comment by Anarchid** [comment]
This is supposed to be the replacement for nuke mushroom cloud, land variation, because Picasso (and GDS feedback) found that cheesy.

However i don't think this is much better (yet).

**Comment by Licho1** [comment]
People didnt like th enuke yeah and also other particle effect, some said they need smoothing. Also people noticed and disliked missile trails not being smoothly bent.
