### ISSUE TITLE
The name "Disco Rave Party" isn't serious enough

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1631]
In my opinion, if the game is supposed to be rather serious, then calling a unit "Disco Rave Party" is inappropriate.

**Comment by GoogleFrog** [comment]
This ticket was on my todo, come up with suggestions.

**Comment by Sgathec** [comment]
Hydra, Typhon or Cerberus because they're multiheaded creatures. However, Hydra appears to be a water creature, Typhon's snake heads seem to breathe fire and Cerberus is apparently usually depicted to have only three heads.

**Comment by Anarchid** [comment]
Gravitas!

**Comment by sprunk** [comment]
Discord (fairly short, ominous, pun).

Current description is "rainbow surprise" which is also nonserious. Someone suggested "Destructive Rainbow Projector" to keep current shorthand.

**Comment by Anarchid** [comment]
```
I am tormented by dreams of our death,
And grief at what is to come.
For in dreams, i have seen the heavens falter,
And the stars drop from the sky.
In my dreams, creation ceases without a sound.
I have seen the destruction of the way.
```
Discord wins my vote.

**Comment by ashdnazg** [comment]
Discord is good

**Comment by GoogleFrog** [comment]
Discord is good but doesn't have enough to do with colours for my liking.

**Comment by Licho1** [comment]
I like DRP, it pretty much describes what it does.

**Comment by Aquanim** [comment]
Finding a name which conveys both the chaos and the colours of DRP is a tough ask. Discord has the advantage that it is at least similar to the current name.

Is this based on feedback from newer players that Disco Rave Party feels out of place as a name?

**Comment by Licho1** [comment]
I like non-serious stuff...
This is a game project made for fun.. why take the game too seriously?

**Comment by Anarchid** [comment]
> This is a game project made for fun.. why take the game too seriously?

There's something to be said about not being tutomod.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/c45c49914d5df85f372329a2123fdd47e176d9af

**Comment by GoogleFrog** [comment]
Any advances on Discord?

**Comment by sprunk** [comment]
No.

I think Discord is at a local maximum of appropriateness. I don't think a reference to colours can be added to the name while keeping its other good traits. So if the global maximum is not Discord then it would have to be completely unrelated to Discord.

**Comment by Anarchid** [comment]
> c45c499

81e656d

**Comment by let4be** [comment]
yea, let's drain out all the fun of this game and make it look more corporate, we're serious dudes minding serious business here after all...

**Comment by GoogleFrog** [comment]
Why do I keep getting assigned to things? let4be you're just a random person wandering onto the ticket.

**Comment by ashdnazg** [comment]
@GoogleFrog that's because you're the decision-maker at the moment.

**Comment by sprunk** [comment]
@GoogleFrog I assign you where the ticket boils down to you saying how you want things done.

**Comment by Licho1** [comment]
Sad day for humanity...  Where is the party?

**Comment by let4be** [comment]
gg wp

**Comment by GoogleFrog** [comment]
You're both bad at reading the information in this repository.

**Comment by ashdnazg** [comment]
The weapon is absurd - an absurd name is not inappropriate.
