### ISSUE TITLE
The Jack model should be replaced

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1632]
I think the current Jack model is almost like just a cube with an attached lever on top so I think it is not good enough in my opinion.

**Comment by mtroyka** [comment]
I thought it was a dalek. :P

**Comment by sprunk** [comment]
Cube conveys tanky and crude which fits Jack.

**Comment by GoogleFrog** [comment]
I think the model is fine.

**Comment by Licho1** [comment]
What? Jack is one of the most iconic units we have.

**Comment by KingRaptor** [comment]
It could stand to have a nicer texture at least.

**Comment by mtroyka** [comment]
>It could stand to have a nicer texture at least.

That could be said for every zk unit and building. We could probably also afford to increase our polygon budget significantly.

**Comment by Anarchid** [comment]
*especially on Hunter*
