### ISSUE TITLE
New Lobby and game UI settings not remembered

### ISSUE THREAD

**Issue by elethio** [ZeroK-RTS/Zero-K#1634]
The game and new lobby always start in windowed mode, even when fullscreen is selected.
To get fullscreen in lobby I have change it to windowed then back to fulscreen.
For game I have to enter lobby while its running then change settings to windowed then back to fullscreen, even if it already says fullscreen.

As you may guess, this means I have to adjust all the UI menus everytime I start a game.

My monitor is 21:9 3440x1440 don't know if this is effecting things.

**Comment by GoogleFrog** [comment]
What is your OS? It may be best if you just attach your infolog.
