### ISSUE TITLE
No UI adjustment Icon

### ISSUE THREAD

**Issue by elethio** [ZeroK-RTS/Zero-K#1635]
Since the last update, the "green X" is missing from the game UI, Ctrl F11 does the same job, but if I didn't know that it would be a big problem.

**Comment by Anarchid** [comment]
I believe that's intentional. Rearranging UI is for advanced users.

**Comment by GoogleFrog** [comment]
It is intentional. It is far too easy to break your UI with tweak mode so there is no way it should be that accessible for new players. More experienced tweak users just use the hotkey. The option is in Settings/HUD Panels/Extras and can be bound there.
