### ISSUE TITLE
Wolverine direct projectile hits don't do full damage to units.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1639]
AFAIK, Wolverine projectiles that collide directly with unit targets are supposed to impart the full damage of the projectile impact *and* the five bomblets inside Claw to the hit unit.

This seems to work for shields, but seems to (again?) not work for unit impacts. I'm not sure it even really worked at any point.

Even if this is intentional, this severely limits effectiveness of Wolverines against elevated defenses of any sort - the projectiles either over/undershoot, landing Claws on the lower terrain and unable to launch bomblets at the structure; or they hit directly, doing negligible damage.

**Comment by GoogleFrog** [comment]
I'm fairly sure that Wolverines are not supposed to do their full damage upon hitting units. Their impact damage has AoE, it wouldn't make sense. What is supposed to happen is that the bomblet is spawned on impact. The ground is where I thought they were spawned but ideally they would spawn in the air and fall.

**Comment by Anarchid** [comment]
Oh. Then the issue is evident: upon Explosion, the spawner gadget checks whether the position is unoccupied to allow the structure to be placed - which is false in case it hits something directly from above, landing within its footprint column.

Claw cannot currently fall because it's a structure (to prevent gravity shenanigans? *should* they be prevented?), but i'll see what can be done.

**Comment by GoogleFrog** [comment]
Explosion could just not check whether there is a unit there. That would fix it.

**Comment by GoogleFrog** [comment]
Fixed. Projectiles now spawn a mine when they hit a unit directly. This accounts for all the damage.
