### ISSUE TITLE
Lobby music volume not remembered

### ISSUE THREAD

**Issue by elethio** [ZeroK-RTS/Zero-K#1641]
New Lobby, music volume is set at maximum when lobby starts, even if settings say it is lower.
Selecting volume sliders returns it to correct level, even if you don't adjust it.
(Its not a big issue). 

BTW thanks for fixing the fullscreen bug so quickly Googlefrog, nice job.

**Comment by ArchShaman** [comment]
Isn't this a Chobby issue?

**Comment by sprunk** [comment]
Made a copy in the proper repo https://github.com/ZeroK-RTS/Chobby/issues/61
