### ISSUE TITLE
Land units going underground

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#1642]
[At 4th minute i finally managed to bury pesky bantha](https://www.dropbox.com/s/hyon4poapqbrvby/20161126_004052_wanderlust_V01_103.0.1-298-gaf1edb1%20HEAD.sdfz?dl=0)
For some reason server didn't want to save replay, uploaded  local replay.

Report inspired by [MP battle](http://zero-k.info/Battles/Detail/437306) (marked as "drowned bantha" at ~40th minute)

Probably terraform / high slope related.

**Comment by GoogleFrog** [comment]
I think it is quite obscure and not important to fix. If this is somehow a problem then a gadget could poll units occasionally.

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5587
