### ISSUE TITLE
Numpad Enter does not allow scrollable chat

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1646]
Normal Enter allows user to enter something into chat, and brings up the scrollable chat button.

Numpad Enter allows user to enter something into chat; however the scrollable chat button disappears almost immediately.

(Numlock on/off is irrelevant.)

**Comment by GoogleFrog** [comment]
Yes, Spring seems to have some hardcoded key suppression which deletes Return key release if chat is open but doesn't delete Numpad Enter key release while chat is open. Working around this would require ridiculous hax so I hoped that nobody would try to use it.
