### ISSUE TITLE
Consider resetting Integral settings

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1650]
If you select factory and want to give fight order to factory (which is pretty much what you always want to do) instead you queue some random BS unit!!

WTF this is beyond stupid!!! Command buttons must NEVER be reused by queueing. It's beyond wrong rever this BS asap.

**Comment by sprunk** [comment]
A is not bound to any unit by default.

**Comment by Licho1** [comment]
I havent touched my configs.

**Comment by sprunk** [comment]
For new players the binding has no conflicts: 
 * Fight is A and no unit is bound to A.
 * no unit has [P]atrol either.

For old players there's a conflict but the hotkeys can be toggled off (Settings/HUD Panels/Command Panel/Grid Keyboard Layout == Disable Grid Keys). Old version of Integral Menu is also available if you also want the old layout ("Chili Integral Menu Old2").

GoogleFrog probably knows more and might give more useful info when he shows up.

**Comment by Anarchid** [comment]
You still have your configs from many years ago if you have  not changed them since then. F is Force Fire.

**Comment by Licho1** [comment]
My complaint still applies. I never manually edited my configs. I just have older "defaults". If this is breaking change we should reset bindings on all. Various changes made my game not very playable.

**Comment by Licho1** [comment]
(Devs are supposed to use defaults and not touch configs)

**Comment by GoogleFrog** [comment]
I don't think a global default reset is reasonable as it would significantly disrupt everybody. I think that by now the affected people have adapted or turned off the unit tab hotkeys. I think devs are supposed to use a UI close to the default and they have to touch configs to do this. If you don't touch your configs then you will have legacy UI, they need deleting occasionally to get the new experience.

**Comment by Licho1** [comment]
Watch out for player drops. Similar changes can really annoy people. I will reset my configs to current ones but I think that general reset might be better. Legacy gui will otherwise be more and more out of sync.
