### ISSUE TITLE
Chat backlog button seems to broken

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1651]
It isn't showing up at game start even though the chatbox shows up in backlog mode and the option to display it is set. Chat backlog isn't really something optional either, since it's easy to miss something someone typed, although the button could probably use a less cryptic icon.

**Comment by Aquanim** [comment]
I'm not at my computer right now so I can't check, but if it does appear when you press Enter to type something in chat I believe this was an intentional change.

**Comment by mtroyka** [comment]
No, that doesn't work either. And that's stupid. There are times when I want to check the chatlog when I'm not intending to chat. Like to see recent map markers, or in replays.

**Comment by Aquanim** [comment]
There are times when I wish it wasn't cluttering up my screen, so there are pros and cons to it.

I don't think the backlog chat settings are working properly at the moment. You might need to toggle "Backlog Arrow" or "Chat shows hacklock arrow" on and off again to get the desired effect, which is not desirable behaviour.

**Comment by GoogleFrog** [comment]
There are too many stupid sentences in this ticket. Instead of interacting with the reporter I would like them to provide their infolog.txt as well as zk_data.lua.
