### ISSUE TITLE
Improve capture visuals

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1654]
The stippled line between capturer and capturiee is coder graphics. It should be replaced with something nice. Perhaps look at the little blue line drawn between Lamp and teleportiee for inspiration.

**Comment by Anarchid** [comment]
The moment of transition might also use an effect. Suggestions?

**Comment by Sgathec** [comment]
While the binary beam may help convey what the unit is doing, I think it makes a pretty poor impression aesthetically. I think it's more of a visual hint than a good graphical effect.

**Comment by Anarchid** [comment]
Note that the ticket is about the stipple line for already captured units, not for the weapon visuals itself. And my suggestion is about the transitionary moment with its associated temporary loss of vision.
