### ISSUE TITLE
Consider Geospot construction block

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1656]
Analogical to mexspots (see #1587).

**Comment by GoogleFrog** [comment]
Thinking about the placement of geospots on some maps I think this is more likely to be a breaking change. Geospots are often ignored when they are in a dangerous position and mappers like to put them on the crest of cliffs, good turret locations.

The benefit of geospot construction blocking is not the same as mex blocking. It is uncommon to have a geospot near your start location so there is little danger of blocking them with facplop. Also, it is barely an issue if a new player does block a geospot.

**Comment by Licho1** [comment]
I think that some maps being not optimal is not a good argument.
The geo spots are very specialized and if we have them the game should make sure allies dont screw each other by accident or trolling.
Losing small footprint on some rare silly maps cliffs is less damage than being trolled (or accidentally trolled) by allies on all maps.

**Comment by sprunk** [comment]
Disagreement, no progress -> keeping status quo.
