### ISSUE TITLE
Supermassive desync alert

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1664]
[desyncinfolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/629067/desyncinfolog.txt)
https://www.dropbox.com/s/u7j8cu4sjnoh1d1/20161203_121617_FolsomDamDeluxeV4_103.0.1-298-gaf1edb1%20develop.sdfz?dl=0

Unknown if this is ZK or engine related.

**Comment by ArchShaman** [comment]
Currently it seems to be map-dependent:
- Folsom Dam Deluxe desyncs instantly (had this happen both yesterday and today in 6v6+ games)

**Comment by GoogleFrog** [comment]
Likely fixed.
