### ISSUE TITLE
GBC error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1665]
[f=0039775] <Global Build Command> Spectator mode. Widget removed.
[f=0039775] WAAA, stack traceback:
	[string "LuaUI/Widgets/chili/handlers/debughandler.l..."]:30: in function <[string "LuaUI/Widgets/chili/handlers/debughandler.l..."]:26>
	[string "LuaUI/Widgets/chili/handlers/debughandler.l..."]:363: in function 'OriginalRemoveWidget'
	[string "LuaUI/Widgets/gui_epicmenu.lua"]:2907: in function 'RemoveWidget'
	[string "LuaUI/Widgets/unit_global_build_command.lua"]:767: in function <[string "LuaUI/Widgets/unit_global_build_command.lua"]:761>
	[C]: in function 'pcall'
	[string "LuaUI/cawidgets.lua"]:755: in function 'PlayerChanged'
	[string "LuaUI/cawidgets.lua"]:1887: in function <[string "LuaUI/cawidgets.lua"]:1884>
	(tail call): ?
[f=0039775] [cawidgets.lua] Error: Error in PlayerChanged(): [string "LuaUI/Widgets/chili/handlers/debughandler.l..."]:32: table index is nil
[f=0039775] [cawidgets.lua] Error: Removed widget: Global Build Command

https://github.com/ZeroK-RTS/Zero-K/files/629067/desyncinfolog.txt

**Comment by mtroyka** [comment]
I've seen that too but I'm convinced that it's not my problem.

Here are the contents of the function it's claiming is causing an error (after editing, though it still does the same stupid thing):
function widget:PlayerChanged(playerID)
	if spGetSpectatingState() then
		Echo( "<Global Build Command> Spectator mode. Widget removed." )
		widgetHandler:RemoveWidget()
		return
	end
end

and the error it throws is related to widgetHandler:RemoveWidget() but I'm not aware of any other method of removing widgets. That, or it's an epicmenu issue.

and the current contents of widget:Shutdown:
function widget:Shutdown()
	WG.GlobalBuildCommand = nil
	WG.icons.SetDisplay('gbcicon', false)
	WG.icons.SetDisplay('gbcidle', false)
end

**Comment by GoogleFrog** [comment]
I have not seen the error for any other widget so I doubt the error would occur if GBC is enabled. I don't want random errors to occur for any reason so It's your problem.
