### ISSUE TITLE
Give engine trees a model and hitvolume

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1669]
On Finns Revenge I tried to reclaim trees for a while until I remembered that I had to center the cursor on a tree. This still failed because the trees there lack hitvolumes. The raytrace to hit trees should have a fallback which checks if there are any trees in a small area around the hit ground position for such a case.

**Comment by sprunk** [comment]
Does Finns use engine trees? Perhaps they could get a proper hitvolume instead.

**Comment by sprunk** [comment]
It seems that things using the default engine tree rendering (ie. 2d sprites and not a model) cannot have a hitvolume. However the trees are fairly ugly anyway so I think the best solution would be to get a decent model which both makes them look decent and enables hitvolume.

**Comment by GoogleFrog** [comment]
Sounds good.

**Comment by sprunk** [comment]
https://springrts.com/phpbb/viewtopic.php?f=13&t=35914

This might get solved engine-side. If not, the tree set provided by Beherith looks very good and I'd use it.
