### ISSUE TITLE
Buff Tremor

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1670]
Tremor is underwhelming. As it is I think it should have these roles:
 * Area decloak
 * Smoothing terrain so tanks can pass.
 * Attrition for weak units and defenses.

I think it should have more smoothing, more range and perhaps more AoE.

**Comment by Aquanim** [comment]
It could potentially also be cheaper, with or without other changes. 1500 is a lot to pay for a utility unit which is kind of flimsy and has no way to defend itself.

However, that does move it closer to Pillager which may be undesirable.

**Comment by Anarchid** [comment]
I dislike the aesthetic effect of Tremor shells looking huge and terrifying and kicking up dust etc etc but then fail to kill a flimsy Defender with a direct hit (300 hp on corrl, 135 damage on trem)

So personally i'd just about triple its damage on purely artistic grounds.

**Comment by DeinFreund** [comment]
The cost really puts it outside of the price range of something you'd use as a reaction to cloaked units. The price also makes it a ridiculous dirtbag "counter" and for countering porc I'd take a single impaler or firewalker over tremor.

**Comment by Licho1** [comment]
Atm I dont think its too weak. I would take tremor over 2 pillagers any time. But not two tremors over catapult or over behemoth which might be the problem.

Regarding smoothing, I think in this case its bad idea to combine the function. Its probably hard to utilize it for it. Unit with similar movement style to tanks should do it, for example welder could be smoothing terrain around it, or gollie (on some incurred cost like much slower movement).

**Comment by Anarchid** [comment]
Neon: Instead of continuous but ineffectual bombing, Tremor shoots a *Moving Barrage* with significant AoE terraform shells in a straight line.

**Comment by Licho1** [comment]
I would like that.

If it forms a "path", basically guaranteed passable strip it would be much more useful and interesting for terraforming. It could start close to tremor and continue to its max range.

For terraforming to be useful you need tremor to mostly guarantee passability in some well defined path, with current random spread its too hard, because single minor obstacle can halt the tank blitz.

**Comment by GoogleFrog** [comment]
Why does the moving barrage move? How do you make it not a micro sink? Is it just like a Starlight- slow turn rate? I like the idea of a walking barrage but don't yet see how it is done in a non-evil way.

**Comment by Licho1** [comment]
Oh no its just one shot/burst.. basically each "shot" consists of burst that moves from tremor to max range.. Not a micro sink

**Comment by Anarchid** [comment]
My idea was burst with each consequent projectile shot to a somewhat longer distance. The first projectile would fall some distance short of the target, and the last would fall an equal distance behind the target. The projectile in the middle of the barrage would fall square on target, guaranteeing at least one hit even against small structures like Defender.

I'm not yet sure how i would go about implementing that with ballistics/ With missiles i'd just SetProjectileTarget.

**Comment by sprunk** [comment]
ad7a3772fe65cee69ffa16ffb4283adbbb5c5e89
