### ISSUE TITLE
GameRules are not reset by Spring.Restart

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1672]
![screen00113](https://cloud.githubusercontent.com/assets/7841201/20866205/91cafd42-b9e4-11e6-9bd4-2aac1c4f3438.png)

Possible cause:
- Pregame the only loaded in opponent quits.

**Comment by GoogleFrog** [comment]
This sounds related to the chicken screen: https://github.com/ZeroK-RTS/Zero-K/issues/1671

Afaik their display is controlled by gameRulesParams, maybe Spring.Restart doesn't clear the values between games. This is easy enough to test.

**Comment by GoogleFrog** [comment]
I had this bug once, it was against Aquanim and it may have been directly after a battle where he disconnected instead of resigning. The workaround fix is to make a gadget de-set all gamesRulesParams on load.

**Comment by GoogleFrog** [comment]
Confirmed.

**Comment by GoogleFrog** [comment]
Surely fixed by https://github.com/ZeroK-RTS/Zero-K/commit/6324cacf7b279f71477d85641b0e74fa3af60c71 (works for chickens).
