### ISSUE TITLE
Chicken is broken.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1674]
Chicken does not work because its GameRulesParams are deleted by a workaround gadget. https://github.com/ZeroK-RTS/Zero-K/commit/6324cacf7b279f71477d85641b0e74fa3af60c71

No gadgets should call Spring.SetAnything during loading because load order is undefined. Everything should be done within gadget callins. The same holds for widgets and defining things in GG.

**Comment by sprunk** [comment]
FYI https://github.com/spring/spring/commit/f4304c560b016d8b6f4a7a71af4716f712c986cf

**Comment by GoogleFrog** [comment]
I don't expect to use that engine any time soon and it is just bad to call Spring outside callins.
