### ISSUE TITLE
Radar wobble - engine fixed

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1677]
Dev engine fixes the wobble reduction feature ( https://github.com/spring/spring/commit/4960e3990d621e6859b31f43159e233650fcb975 ).

As far as I know there were multiple reasons for removal but the commit only lists the technical one so it seems worthwhile to notify GoogleFrog.

**Comment by DeinFreund** [comment]
arad is still 500, at least adjusting that would be nice.

**Comment by sprunk** [comment]
That's a related yet separate issue.

**Comment by Aquanim** [comment]
Even at its current cost and characteristics I believe Advanced Radar has a non-zero (although niche and rare) use case, for what that is worth.

**Comment by GoogleFrog** [comment]
http://pastebin.com/fArzPn7g

TLDR, it's not something that would be added unless it already existed. Why should there be exactly one global upgrade in the game which is basically a buff for Pene and Impaler?
