### ISSUE TITLE
Projectile light fadeout is bad.

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1682]
If it were really short, ie to mask the fact that projectile lights don't move as smoothly as the actual projectiles, then I think it'd be fine (if that could even work, and I'm not sure of that). But trying to fake explosion lights with an unnatural fadeout looks stupid. The lights just pile up where the projectiles hit causing it to be overbright, and it looks particularly bad with projectiles that don't really explode like razor, bandit, etc.

**Comment by GoogleFrog** [comment]
I implemented this to avoid the harsh transition from light to no light when a projectile impacts. I found it most noticeable with Rogue, it creates the impression that the rocket just disappears.
