### ISSUE TITLE
Adding a GUI element to show the window about the statistics of the unit

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1685]
Holding Space down and clicking on the desired unit probably isn't discoverable enough. I suggest adding a button or a link that leads to the window that shows the unit type statistics and description. The information window for displaying the current unit state that appears on selecting a unit is probably the place that should contain it.

**Comment by GoogleFrog** [comment]
I'm not so sure that it isn't discoverable enough. How many hours do you think a player must play before it is unacceptable for them to not know it exists?

**Comment by Sgathec** [comment]
Unit type stats are important. If the player hasn't found the unit information elsewhere, which I'm pretty sure is not rare, I think 2 hours.

**Comment by GoogleFrog** [comment]
Really? I think unit stats are barely important. Is knowing how to see unit stats more important than any awareness that overdrive exists?

**Comment by sprunk** [comment]
Do you mean something more by "unit type stats" (as opposed to just "unit stats")?

Types are discoverable through unit descriptions. The relationships between types are fairly discoverable in combat while being hard to discover if you just look at raw numbers.

**Comment by Sgathec** [comment]
I meant unit types like the Glaive, Firewalker or Goliath.

Sorry, I'm too busy now to respond thoroughly. Does any tutorial explain unit roles?

**Comment by KingRaptor** [comment]
Tutorial 2 explains unit roles.

Game already says to space-click to view unit stats in the unit tooltips (both for an existing unit and its menu build button). Menu/Help/Guide contains a browsable list of units, where clicking the button brings up the stats window for that unit.

**Comment by Licho1** [comment]
I would say its best if this is tutorialied (no need for GUI change).

**Comment by meriton42** [comment]
As a new Zero-K player, I can confirm that space-clicking is sufficiently well explained. At least, I learned about it within hours, so I don't think there is anything that needs to be done here.

(Only thing I find somewhat annoying is that space-clicking a unit in the factory panel, if another unit is beneath it on the map, will show that unit's statics. Its usually quite obvious that is the wrong stat window, so this is just a minor thing)

**Comment by sprunk** [comment]
It seems like the consensus is that ingame discoverability is sufficient and that the responsibility belongs to tutorials.
