### ISSUE TITLE
EMPed units able to fire when moved onto Surfboard

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1687]
On the HP bar the unit is at "100%" stun rather than displaying a time to un-stunned-ness.

The unit remains stunned and is unable to fire if moved back off the Surfboard.

A unit which is stunned while on the Surfboard is not able to fire; this only happens when a stunned unit is taken on board.

**Comment by sprunk** [comment]
EMP and transports (in particular "fire platforms") are both engine things.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/pull/1710/commits/9287707fa84d4d24d6fa679391e9388170d87c60
