### ISSUE TITLE
Fac Plop generating stuck units & CAI not being able to resolve unit cluster

### ISSUE THREAD

**Issue by kylelt** [ZeroK-RTS/Zero-K#169]
*Map*: Green Comet Basic
*Spring Version*: 91.0
*ZK Version*: 1.2.8.17
*Issue*:
  CAI placed LV factory near lumpy ground, once built majority of vehicles were clustered for a while
![screen00001](https://cloud.githubusercontent.com/assets/734473/4056402/245d2cca-2dba-11e4-93d5-4b1cb68991dc.png)
Game Replay and Info 
http://zero-k.info/Battles/Detail/288635

**Comment by Orfelius** [comment]
This is a problem with CAI which is no longer being developed by anybody. It also sometimes spawns in the holes etc. Nothing can be done in this regard I am afraid and new kind of AI is being in development right now anyway. Close?
