### ISSUE TITLE
Investigate reload-based skirmLeeway

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1691]
Long reload, relatively speedy units like Rapier, Dagger and Duck may benefit from increased skirm distance based on their current reload time. This would move them outside skirm range just after they fire, a bit like the Mutalisks that won the Broodwar AI competition.

**Comment by mtroyka** [comment]
Or circuitAI's black dawn behavior. :P

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/70d34acfbc5b282ed1617d6701eda8837fe17d4d

The feature exists so now it's a matter of finding which units should receive it and tweaking the configs.

**Comment by GoogleFrog** [comment]
I remembered thinking about this feature request and looked for it before deciding I had not implemented it yet. I think I was remembering this ticket.

**Comment by GoogleFrog** [comment]
This is probably best to leave as is. Perhaps some units could benefit but the danger is that running away gives the enemy a window in which to disengage.

**Comment by sprunk** [comment]
The technology now exists and specific units seem to be getting their own tickets (eg #3038).
