### ISSUE TITLE
CEG Debugger cannot be used without epicmenu

### ISSUE THREAD

**Issue by ForbodingAngel** [ZeroK-RTS/Zero-K#1692]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/dbg_ceg_spawner.lua

Could the ability be added for it to be used independently of epicmenu?

(CarRepairer)

**Comment by sprunk** [comment]
CarRepairer seems rarely available nowadays. The entire widget is pretty much a simple wrapper around this line: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/dbg_ceg_spawner.lua#L71

**Comment by GoogleFrog** [comment]
I'm not touching epicmenu more than I need to and I don't think anyone is interested in making ceg tools.
