### ISSUE TITLE
Surfboard

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1695]
Surfboard has technical problems:
 * misbehaves with morph (see #1686)
 * misbehaves with EMP (see #1687)
 * units are teleported in front of it for loading and then the (un)loading process is just a slide (which allows units to slide through walls). This is bad but the model does not allow anything better.
 * the model is ugly and somewhat silly (pretty much an actual surfboard).
 * nubs might think it's a regular transport.

Ordinarily this would mean "those need fixing" but I'm unsure if Surfboard is well-designed from a gameplay POV either. It does have a role (anything a specialist land unit does but is unavailable in sea, Surfboard can provide) but I don't think the implementation is good.
 * control and management. The surfboard and its passenger are separate units of existing types. That means the interface for such a pair is subpar compared to regular units. There's an overhead in keeping the units paired, including getting them together physically, but also eg. keeping track of how many you have so there's a ~ 1:1 ratio. You can't for example ctrl+z (because if you ctrl+z a Surfboard you also select those with different passenger types, and if you don't you can't move), retreat won't work (a Surfboard might lose its passenger but won't go back because it is still healthy itself), unit counts are skewed (the UI says you have X units but half of them are sunken passengers whose surfboards died and are actually marooned underwater) etc.
 * balance. Passengers are tuned for the land game so the only controllable variable for a pair is the Surfboard, but that affects all other pairings as well. In practice this means there's a small handful of units that Surfboard works decently with and the other pairings are owled. Having regular units fulfil Surfboard's roles would mean they can be tweaked independently without the risk of owling something else.

**Comment by Anarchid** [comment]
Two major utility units that used to be surfboarded are the shield walker and the area cloaker, both of which are amphibious now.

**Comment by Aquanim** [comment]
I have a problem with Surfboard as well, but I don't have a solution at this time.

**Comment by GoogleFrog** [comment]
Surfboard also has many issues with unloading. It is unrealistic to try to assault a coast with them simply because they often fail to unload. People sometimes expect them to work so I think they are better off removed. For example, they want surfboard to work with ferry points which is not going to happen while its unloading is so broken.

A surfboard with fixed technical issues, model, transportability confusion and balance is fine.

**Comment by Licho1** [comment]
Also it's not very used unit atm, removing it won't hurt and perhaps it will make a room for something more interesting and less broken.
