### ISSUE TITLE
Pyro outranges Redback

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1696]
When fighting in mountainous terrain because of spherical vs cylindrical range. Pyro already gets the "fire through terrain" bonus, so that should be enough of a bonus..

**Comment by sprunk** [comment]
Is Pyro really cylindrical?

Its weapon is technically a laser ( https://github.com/ZeroK-RTS/Zero-K/blob/master/units/corpyro.lua#L151 ) and does not seem to have cylinder targeting tags.

**Comment by DeinFreund** [comment]
![crabetower](https://i.imgur.com/DSIGovo.png)
Explain!

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/98b9a39c0cfc351d9acfb9843c4d907ae0bfcca1
