### ISSUE TITLE
gui_battle_room_window error

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1699]
```
 [f=-000001] [LuaMenu] Error: In DownloadFinished(): [string "LuaMenu/Widgets/gui_battle_room_window.lua"]:46: attempt to index upvalue 'battleLobby' (a nil value)
 [f=-000001] [LuaMenu] Error: Removed widget: < Battle Room Window >
```

**Comment by ArchShaman** [comment]
Unknown if this is chobby or zk related widget. Sorry if miss-post.

**Comment by sprunk** [comment]
Thanks for your bug report. :) it's much appreciated.

For future references, however, the Chobby Repo (go back to ZeroK-RTS) is where you'd report issues with the lobby.

Thanks again and happy hunting mate!

**Comment by ArchShaman** [comment]
Lol'd.
