### ISSUE TITLE
It's too easy to issue an order to start reclaiming your cons

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1700]
I've had several incidents with the new layout lately where I'd accidentally start reclaiming my cons. Could this be issued with a modifier key instead? It's too easy to center the reclaim command on a con when you're in a hurry.

**Comment by sprunk** [comment]
It already only works with CTRL.

**Comment by GoogleFrog** [comment]
I swapped CTRL so if there is a widget which detects CTRL it will reclaim your own units without any modifiers.

**Comment by sprunk** [comment]
I tested and after the CTRL swap, the unit reclaimer does not work at all because tree reclaimer eats the command in all cases.
