### ISSUE TITLE
Mex placement fails with terraform height if offcenter.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1704]

**Comment by sprunk** [comment]
Should the height be ignored if a mexspot already has a nanoframe at incorrect height?

**Comment by GoogleFrog** [comment]
If there is a nanoframe on the spot then doesn't the order not get given? In any case, if you give a persistent build height command on a mex spot with a nanoframe then the persistent build height should have no effect. The only change required by this ticket is to put the terraform command location on the mex spot when the command would have an effect.
