### ISSUE TITLE
Terraform is hit by raytraces in bad situations.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1707]
Example:

![screen00129](https://cloud.githubusercontent.com/assets/7841201/21075361/3e7cef72-becd-11e6-865d-ddf02fc49d5d.png)

Desired behavior:
Smaller selection radius?

**Comment by GoogleFrog** [comment]
It's not a radius, its some sort of ha or an /engine bug to do with the weird position parameters.

**Comment by GoogleFrog** [comment]
What is this about? It is an awful title.

**Comment by sprunk** [comment]
I think the underlying issue is the same as #1877

**Comment by GoogleFrog** [comment]
Fixed https://github.com/spring/spring/commit/e2eeee6faa11c39c9945e12f21da8811b8f525fa

Terraform is now never hit since it doesn't have a hitvolume anywhere near ground level. So it is never hit in bad situations.
