### ISSUE TITLE
Transportability Inconsistancy

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1711]
Unithelp guide states Quail (144 mass) is heavy transport, while Hermit (180) is light.
![screen00130](https://cloud.githubusercontent.com/assets/7841201/21075804/8992afaa-bed8-11e6-88e6-e26fdfcc7933.png)

**Comment by ArchShaman** [comment]
Possibly fixed by PR 1710?

**Comment by sprunk** [comment]
Yes.
