### ISSUE TITLE
Ghost Site: LoS hax

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1713]
Regular buildings' ghost site persists if they die outside LoS, you need to see the location to learn they died.

Protector, Silencer and Gauss lose the ghost site immediately if they die, regardless of LoS.

**Comment by sprunk** [comment]
Closed by misclick? Still happens.

**Comment by GoogleFrog** [comment]
There is a commit which says it is fixed.

**Comment by sprunk** [comment]
The commit is not in master branch.
