### ISSUE TITLE
Shadows miss. Don't dive enough.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1716]
http://zero-k.info/Battles/Detail/439281

Missing targets behind a hill is an old issue (that still needs fixing) but they even missed targets on hills.

**Comment by Licho1** [comment]
I think its good if its part of the physical world simulation.

**Comment by sprunk** [comment]
It's good that they can miss if they don't dive low enough (= physics).
It's bad that they don't want to dive low enough (= bad unit AI).

**Comment by DeinFreund** [comment]
As airplanes in spring they break the laws of physics all day. Their diving and flying is not controllable by the player, so the player should be able to trust in them executing their orders optimally.

**Comment by GoogleFrog** [comment]
Make a simple reproduction replay. Use /give.

**Comment by GoogleFrog** [comment]
Their dive has been lowered at some point since this ticket. Feedback required otherwise.
