### ISSUE TITLE
Scouting/Units entering LOS causes massive lag

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1720]
One can easily fall behind multiple seconds just by sending a vulture over a well built-out enemy base. 

What widgets have the highest impact here? They should be optimized or distribute the load over a longer timespan.

**Comment by GoogleFrog** [comment]
Make a replay to demonstrate it.

**Comment by GoogleFrog** [comment]
No feedback and I cannot reproduce. Performance improvements may have made this irrelevant.
