### ISSUE TITLE
Siren is too op

### ISSUE THREAD

**Issue by Helwor** [ZeroK-RTS/Zero-K#1727]
can be anti air, anti sub, arty, and good defense vs ships attacking... altogether.
monospam of siren negate almost any other choice of the other ships unit.

**Comment by Aquanim** [comment]
I have a few candidate fixes for this but I need to discuss with GoogleFrog first.

**Comment by sprunk** [comment]
Relevant #1737

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/53b6c56fe8ab0ec6ee425f5bfb051289f35cdc04
