### ISSUE TITLE
Check whether OD grid works

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1731]
Afaik this change should have broken pylons: https://github.com/ZeroK-RTS/Zero-K/commit/d26c5929c637023310f4f4647b9510bc642ea990

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/commit/27ad9b28fc5e9c6b684307eae9a9d8d87b3c3334

I'm not convinced by the message that it works. It will require convincing code review to say that the change is fine.

**Comment by sprunk** [comment]
See also: https://github.com/ZeroK-RTS/Zero-K/pull/1722

A circle larger than square size will just belong to multiple quads[1].
GetIntersections (the quadfield method used by OD gadget) correctly checks all of the quads the circle belongs to[2][3].
Note that regardless of how small a circle's size is, it's possible to make it belong to 4 quads (if you place it at a grid point) so if that was broken it would fail regardless of square size.

[1] https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Utilities/quadField.lua#L77
[2] https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Utilities/quadField.lua#L123
[3] https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Utilities/quadField.lua#L98

**Comment by GoogleFrog** [comment]
Ok, looks convincing.
