### ISSUE TITLE
personal room name doesnt work

### ISSUE THREAD

**Issue by Helwor** [ZeroK-RTS/Zero-K#1732]
I tried to set up a room called "All welcome", that doesnt work, the room still called "Helwor's Teams".

**Comment by sprunk** [comment]
Not the correct repo. Belongs to either https://github.com/ZeroK-RTS/Zero-K-Infrastructure or https://github.com/Spring-Chobby/Chobby/issues/new

**Comment by DeinFreund** [comment]
Most likely lobby related

**Comment by GoogleFrog** [comment]
Works for me.
