### ISSUE TITLE
Scorchers sometimes shoot through things without doing any damage

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1734]
I've seen this happen with workers and llts, where scorchers' heat rays completely pass through the target and go to max range without hitting the target or doing damage. It seems to be colvol related and probably isn't new, but it's pathological when it happens with the new scorcher dive because the scorcher's entire attack is negated and the condition very often persists up until the scorcher dies.

**Comment by GoogleFrog** [comment]
Find a way to reproduce this.

**Comment by sprunk** [comment]
There is neither replay nor reproduction steps. Reopen if you get either.
