### ISSUE TITLE
Make 'defense ranges' for radar

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1742]
Visible enemy radar radar range for seen radar towers would improve people's ability to make sneak attacks. Something like defense ranges could be implemented. Ideally it would be a minimap toggle button and would have merged circles.

**Comment by Licho1** [comment]
That would be a big chaos and imo not very interesting, because most of the time most of the map is covered..

**Comment by GoogleFrog** [comment]
Defense ranges has these same failings and is still useful.
