### ISSUE TITLE
Extended cursor set is clutter

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1744]
The animations are wrong, it looks like the text file defining them is ignored and the frames are just taken in order.

My fix would be to remove the option. The ability to make the attack cursor spin instead of pulsate is not particularly useful.

**Comment by sprunk** [comment]
Big Wait cursor is nice and should ideally be preserved.

**Comment by sprunk** [comment]
I have discovered the source of the breakage ( 43fbab0292e983ca633bdf480e9a03ba422bcb1d ) and was able to fix it ( 4f0ec48fc6dd6e19cafcc4d167fabd0d9da23fa2 ).

In spite of that, I still think the option does too little to be anything more than clutter (especially since it breaks on some cards). So the proposal is to:
 * check out Big Wait. I don't think anything can be done since current Wait already grows to 32x32 and anything larger breaks on some cards but perhaps GF can make some use of it.
 * definitely remove the menu option.
 * perhaps remove the cursors as well. Nobody should even get the idea that differing cursor sets are a useful option to have.

**Comment by GoogleFrog** [comment]
They seem to have been removed.

**Comment by sprunk** [comment]
Why do you think so? They are still there.
