### ISSUE TITLE
Broken resource panel

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1745]
I started the game as a player and had an empty resource panel, as if I were spectating gaia.

**Comment by GoogleFrog** [comment]
Might fix https://github.com/ZeroK-RTS/Zero-K/commit/2df7a504832a72f1eddbea7545b37584c7ab615f

**Comment by sprunk** [comment]
I assume the fix worked given lack of reports to the contrary.
