### ISSUE TITLE
reality adjustment: forbid jetpack-jump midair acceleration stop

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#1748]
if you newtonramp-accelerate jump units, they fly. while they fly, you can use jump to make them stop flying and then they land safely on the jump target. this is valid for jetpack jumps (pyro, jack) and not for leg-jump (sumo, skuttle).

why is there made a difference? ok, jetpack does influence physically the acceleration, but hey, it doesnt stop it, or prevent fall damage.

in the stated game, the strategy was applied to pyros to transport them in the back of my team. my understanding is, that for transporting there are transports or teleporter...
http://zero-k.info/Battles/Detail/440248

**Comment by sprunk** [comment]
This is by design.

**Comment by GoogleFrog** [comment]
It is by design. I'll need some evidence of it being brokenly abusable.

**Comment by mojjj** [comment]
> Zero-K is a FREE, multi-platform, open source Real Time Strategy game, which aims to be a dynamic, action-packed, hassle-free experience, full of clever strategies and constantly moving combat. Includes an epic scale, realistic projectile and unit physics, terraforming terrain and hundreds of unique and interesting units.

**Comment by mojjj** [comment]
if this is by design, i will attempt to abuse. if it is relieable abusable, will the design decision be discussed?

**Comment by sprunk** [comment]
>advertised as physics.

If that's a problem then change advertising.

>if it is relieable abusable, will the design decision be discussed?

Sure, feel free to provide replays.

**Comment by ArchShaman** [comment]
In that game, pyro destruction would have been easily avoided if you put down some lotus after SavageBlake pointed it out. Your team didn't respond to the incoming pyro threat _at all_ and  thus were punished for it. The only abuse case here is that people don't pay attention to the map. A few measy lotuses would have saved that singu, factories, com, whatever else I killed.

**Comment by sprunk** [comment]
Reopen having gathered brokenness evidence.

**Comment by GoogleFrog** [comment]
Physics doesn't exactly mean realistic physics. It means that something that looks a bit like physics is relevant to gameplay.
