### ISSUE TITLE
New defaults allow multiple versions of pro console to be enabled.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1750]
For some reason text input flashes to the top right.
See:
http://i.imgur.com/A0ZcV6o.jpg

**Comment by DeinFreund** [comment]
The new defaults enables some widgets without disabling other ones. This leads to having multiple chat widgets and a completely messed up UI(overlapping elements) for people using nonstandard UI elements.

**Comment by ArchShaman** [comment]
Yes it is. Confirmed that both proconsole and proconsole 2 are enabled. Disabling 1 then disabling/enabling 2 fixed it.

**Comment by ashdnazg** [comment]
I want to point out that the new console (or maybe the old, I don't know which is enabled) doesn't support the backlog (when the backlog shows through toggle backlog it immediately disappears a few seconds later).
This is very bad since I frequently fail to notice chat lines on time.

**Comment by GoogleFrog** [comment]
Proconsole 2 has never been enabled in stable so this is only the type of problem that will affect highly experienced users. They can sort it out for themselves. There are many other widgets which are not disabled by the presets.

@ashdnazg, make your own ticket for any unrelated bugs.
