### ISSUE TITLE
Default selections panel is huge

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1751]
![huge](https://i.imgur.com/nKwsrHg.jpg)
(The panel bottom center)

Is it going to use that width for something?

**Comment by GoogleFrog** [comment]
It's for looking coherent.

**Comment by DeinFreund** [comment]
I guess it would be nice if some other elements could scale horizontally as well. Otherwise I agree with having it huge over having empty space.

**Comment by sprunk** [comment]
Done on purpose.
