### ISSUE TITLE
Console does not support the backlog

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#1753]
The new console (or maybe the old, I don't know which is enabled) doesn't support the backlog (when the backlog shows through toggle backlog it immediately disappears a few seconds later).
This is very bad for me since I frequently fail to notice chat lines on time.

**Comment by GoogleFrog** [comment]
There isn't really enough information here. Send zk_data and zk_order.

**Comment by GoogleFrog** [comment]
I think the issue can be fixed by disabling this setting, since renamed to be more descriptive: https://github.com/ZeroK-RTS/Zero-K/commit/9c753475394ea75030053140969ced3430b6580f

**Comment by ashdnazg** [comment]
I'll check next game

**Comment by sprunk** [comment]
@ashdnazg Any recent advances?

**Comment by ashdnazg** [comment]
ah, sorry, renaming helped me understand the settings better.
