### ISSUE TITLE
Activate "Stay up to date" HUD panel option

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1757]
The option "Stay up to date" should set people's UI panels to the new default whenever it changes. It is enabled by default but inactive. This open should probably be made active in February after everyone is warned about it.

**Comment by sprunk** [comment]
February is over so doing this now can be considered.

**Comment by sprunk** [comment]
I think people haven't been notified. How's this for a newspost? https://hastebin.com/edupidigej.vbs

**Comment by sprunk** [comment]
#2468

**Comment by GoogleFrog** [comment]
Post made.
