### ISSUE TITLE
Chili Integral Menu crashes without Core Selector

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1760]
Disabling the Core Selector in widget list causes the Integral Menu to crash on the next selection change.

IMO, these should either form a single widget or be able to survive separation.

I have this opinion because i do not have any uses for the Core Selector and would like to recycle its screen space for myself.

**Comment by sprunk** [comment]
Can't reproduce by just disabling Core selector (on either new or old Integral), impart infolog.

**Comment by Anarchid** [comment]
```
[f=0000076] [cawidgets.lua] Error: Error in CommandsChanged(): [string "LuaUI/Widgets/chili/controls/object.lua"]:423: attempt to index field 'parent' (a nil value)
[f=0000076] [cawidgets.lua] Error: Removed widget: Chili Integral Menu
```
Seems to need a selection change first.

**Comment by GoogleFrog** [comment]
Load luaUI with core selector disabled to avoid the crash.
