### ISSUE TITLE
Licho stuck mid-air

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1761]
![licho](https://i.imgur.com/Gl1ll8z.png)

Not moving anymore :|

**Comment by Aquanim** [comment]
I expect a replay will be required to solve this.

**Comment by ArchShaman** [comment]
Perhaps this is similar to #1756 ?

**Comment by sprunk** [comment]
The airpad gadget has since received [a bugfix](https://github.com/ZeroK-RTS/Zero-K/commit/b9b4a12baf7860c4342d2bc2be2175af29b4b3de) and there is no replay to investigate any further.
