### ISSUE TITLE
Sharemode: Own team is not self coloured

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1764]
The units that you control should always be coloured with the self colour. Sharemode breaks this. The local team colours widget needs to know about changing teams.

**Comment by GoogleFrog** [comment]
The naive change to local team colors fails because NotifyColorChange() interacts with poorly written chili widgets and causes a second long freeze when the default playerlist displays 30 NullAIs.

**Comment by sprunk** [comment]
65fc0ebd9bd505f19dc34b404db977e9e124978b
