### ISSUE TITLE
Sharemode clutters playerlist

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1765]
The playerlist(s) show the original team of the sharing player as dead. This is clutter. The sharemode gadget should set a teamRulesParam and the playerlists should use it.

**Comment by ArchShaman** [comment]
Is this with crude player list or deluxe player list? What teamrulesparam do you want?

**Comment by ArchShaman** [comment]
I've added a true/false under isCommsharing. Which playerlists create clutter?

**Comment by GoogleFrog** [comment]
Crude and Deluxe.

**Comment by Licho1** [comment]
ffs just remake the playerlist already, it should be on demand when you press something because it can show a lot of interesting info and controls..

These old playerslists are waste of work. I will personally delete them before steam release.

**Comment by sprunk** [comment]
Close with the same reason as #1723 ?

> It is a bad widget. It is playable now and effort spent on this widget is wasted.
