### ISSUE TITLE
Tactical AI, check Rapier vs Warrior

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1768]

**Comment by mtroyka** [comment]
According to the defs rapier should skirmish vs warrior, however rapier uses all default settings. From what I've seen it works decently, although air strafe sometimes causes them to suicide anyway.

**Comment by GoogleFrog** [comment]
I've seen Rapier take damage from Warrior (in fairly pure circumstances) when their relative maneuverability says that it shouldn't happen.
