### ISSUE TITLE
Save/load breaks with factories

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#1769]
When a factory is built, the game is saved, and then loaded:

- The factory builds units facing the wrong way (always south).
- If the factory is facing east or west, the game hangs once the factory completes a unit, requiring a SIGABRT. Infolog/stdout doesn't report any errors.

Tested with cloakybot and vehicle factories.

**Comment by ashdnazg** [comment]
is this a /luasave ?

**Comment by KingRaptor** [comment]
Yes. 
[(Relevant gadget)](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/api_saveload.lua)

**Comment by ashdnazg** [comment]
so not sure how much of an engine issue this is.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/api_saveload.lua#L195 sets facing to 0 (south) unconditionally. This is worked around by setting heading in L202 but buildings have some facing constraints which might not play well with this (for example footprints where X != Z would be wrong; presumably crashing E/W facs is another symptom of this as well).
