### ISSUE TITLE
Ducks use their water weapon vs wolverine mines

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1773]
This happens on land. I'm not really sure why.

**Comment by mtroyka** [comment]
This affects scallops and other units with water weapons as well.

**Comment by sprunk** [comment]
This happens when Ducks have no clear line of fire for the missiles. The torpedoes are thrown at an angle so can go above the obstruction and still hit. I think in this case this is desirable.
