### ISSUE TITLE
Fix chicken dynamic lights

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1776]
Dynamic light configuration is quite off for many chicken weapons.

**Comment by sprunk** [comment]
3ef96edf31808cc72e8c5c07e79c134d3ce35a8c
dd8aaa82ce51a35eee3ed77f95c0e8095c0830d8

Is this done considering the two above?

**Comment by KingRaptor** [comment]
Yeah, forgot to close. Reopen if any other offenders are found.
