### ISSUE TITLE
error in pretty much every game on current version

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#1779]
http://zero-k.info/Battles/Detail/441220

'''
Error: LuaRules::RunCallIn: error = 2, AllowCommand, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_prevent_lab_hax.lua"]:367: attempt to perform arithmetic on local 'x' (a nil value)
'''

for instance here: http://zero-k.info/Battles/Detail/441226

**Comment by GoogleFrog** [comment]
Infolog?

**Comment by GoogleFrog** [comment]
No infolog. Error not in replay. http://zero-k.info/Battles/Detail/441220

**Comment by ashdnazg** [comment]
check http://zero-k.info/Battles/Detail/441226 then

**Comment by sprunk** [comment]
52b27b0f2412ee312772195ed338363e0c12182f
