### ISSUE TITLE
Waterlevel simplification

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1783]
Currently the waterlevel modoption requires people to input a raw number. Its meaning is not obvious (% of map area that gets flooded? % of height that gets flooded? absolute height?). Absolute heights/depths also differ per map so it's fairly hard to get a decent setting without first spending time checking the specific map's heights.

Consider a simplification where the option becomes a 3-way toggle:
 * do nothing.
 * dry.
 * flooded. This autodetects map heights and fills half the map area with water (possibly removing water on, say, IncultaWet). There can be a config with handpicked override (like mexes and boxes).

This does remove some control but I think the simplicity and ease of use are more important than the rare case of someone going "oh but I'd rather this specific puddle were dry".

<hr/>

As a more extreme solution consider creating separate archives for maps that play well when modified and just removing the option. This is because:
 * there's a precedent for dry/flooded versions. DSD, Kappa Basin Flooded, etc.
 * modoptions are not shown in lobby. This applies to all modoptions but the lobby does explicitly show the map so it conveys wrong information if the map is modified. Having explicit eg. "X Flooded" with a blue minimap makes sure everyone knows what to expect.
 * there's not many quality maps that still play good when modified but don't yet have a modified version; the modoption is barely used.
 * any map that does get a modification is pretty much guaranteed to have a decent handpicked value so there's some quality assurance.

**Comment by GoogleFrog** [comment]
Modoptions are shown in the lobby.

I dislike the non-extreme solution simply because modoptions are bad. They are hard to coordinate and can't be applied in matchmaking. I think the waterlevel modoption is perfect for what it does as I only expect modoptions to be applied in organised games (I'm treating public teams hosts as disorganised).

If a map plays well wet then there could be a wet version of the map. Ideally without using the modoption at all.

**Comment by sprunk** [comment]
>Modoptions are shown in the lobby.

**Comment by sprunk** [comment]
>I only expect modoptions to be applied in organised games (I'm treating public teams hosts as disorganised)

People still apply them in public teams hosts though, with varying results (usually people know what they're doing but sometimes random settings get proposed and mostly pass because voting people assume the proposal was sane).

Perhaps that's an infra issue where a public host should have rules similar to MM and disallow modoptions and unfeatured maps. On the other hand people would then use a private host.

Regardless, having presets means it's that much easier to organise a game. Even if someone knows what they want to do ("play this map but with water") they might not necessarily know how to implement that using the option ("input 200 if flooding titan duel, 1000 if desert triad...") and presets help that.

**Comment by sprunk** [comment]
Any feedback? TL;DR: presets make it way easier to organise a game for the typical user
![preset_usefulness](https://cloud.githubusercontent.com/assets/2573076/22421017/8680752e-e6e5-11e6-9c3b-07daebf542f1.png)

**Comment by GoogleFrog** [comment]
I don't think the typical user generic desire part of the chart exists.

**Comment by GoogleFrog** [comment]
But if you can implement an automatic optionthat would fairly well then it would be a decent addition to modoptions.

**Comment by sprunk** [comment]
I think it's the most common part because people generally won't know arbitrary per-map height values (which makes it more common than the two parts with technical knowledge) and will mostly care about general presence of water rather than its exact extent (so more common than specific desires).

**Comment by sprunk** [comment]
6679f910e92c66c7333f589348c75918486c2943
