### ISSUE TITLE
Drone control, force attack ground with hold fire

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1789]
If you force attack the ground with a Funnelweb set to hold fire then the drones fly to that location and fly around without attacking anything. The use I imagine for this is to keep the drones from wandering off on their own while still allowing the Funnelweb to be told to attack targets in an area.

As far as I can tell, the only purpose for drone hold fire is to keep them cloaked. Therefore holdfire could only be applied if their carrier is set to hold fire and the drone could cloak if it wasn't firing.

**Comment by Anarchid** [comment]
For existing drones this is true, but consider any drones that may have long reload weapons, whether long autonomous reload (less expensive) or bomber reload on mothership (more expensive to waste shots).

**Comment by Aquanim** [comment]
Even if the carrier (and by extension the drones) are set to hold fire I believe they will still attack if the carrier is given an attack order on a specific enemy unit.

**Comment by Anarchid** [comment]
Drone Attack Ground also gains more validity in at least some of the bomber drone concepts i can picture.

**Comment by Aquanim** [comment]
That's true.

**Comment by GoogleFrog** [comment]
The only change required for the particular case of a holdfire carrier force attacking the ground is that the drones should not be on hold fire. I did not say the drones should attack ground, they should do the normal behaviour for when a carrier has an attack command.

In general, hold fire on units means that units do not assign their own targets, if they have an attack (or set target) command then they should do their usual attack behaviour.

**Comment by sprunk** [comment]
#1793 merged.
