### ISSUE TITLE
Resign causes multi second lag

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1796]
http://zero-k.info/Battles/Detail/442119

Try to watch the replay as player to reproduce. Every time a player resigns the game lags for about a second.

**Comment by GoogleFrog** [comment]
The commshare stuff introduced some code when players change state. @ArchShaman ? Or just revert?

**Comment by ArchShaman** [comment]
Commshare only has PlayerAdded, not PlayerChanged:

 ```
function gadget:PlayerAdded(playerID)
	if Spring.GetGameFrame() > config.mintime then
		local name,active,spec,team,ally,_	 = Spring.GetPlayerInfo(playerID)
		if spec == false and active == true and config.mergetype ~= "none" and controlledplayers[team] then
			MergePlayer(playerID,controlledplayers[playerID])
			Spring.Echo("game_message: Player " .. name .. "has been remerged!")
		end
	end
end
```

**Comment by GoogleFrog** [comment]
I'm not talking about the commshare gadget. The commshare changes are beyond one gadget. Other bits of code were changed as well in various ways.

**Comment by GoogleFrog** [comment]
Logs will know.

**Comment by GoogleFrog** [comment]
I looked into it myself and didn't revert everything.
