### ISSUE TITLE
Licho doesn't do the listed damage

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1799]
It can't one shot economy coms most of the time. This is due to slight inaccuracies of the missile combined with the sharp falloff.

**Comment by GoogleFrog** [comment]
The bomb is not inaccurate and does not have sharp falloff. You need to directly hit a 2000 health commander to kill it with a 2000 damage bomb. The bomb has no homing and is burnblow so you're unlikely to hit a mobile unit directly.

**Comment by DeinFreund** [comment]
Could we get prediction in this case?

**Comment by sprunk** [comment]
I managed to reproduce hits on stationary support coms doing less than 2000 damage (about ~1980), especially when the Wyvern approaches from high/low angle (hills). I'll produce a replay and reopen.

**Comment by GoogleFrog** [comment]
The blurblow is probably going off a frame early. It's a gadget.
