### ISSUE TITLE
Reset defaults with epicmenu makes all invisible

### ISSUE THREAD

**Issue by TurBoss** [ZeroK-RTS/Zero-K#1803]
Hello

if you reset the config to the defaults using epicmenu
all is hidded

tested on single player

http://i.imgur.com/w5kFBzM.png

**Comment by GoogleFrog** [comment]
I have never seen that button before.

**Comment by GoogleFrog** [comment]
It does the same thing for me. I have never needed or planned to use such a button so I think it's probably just removable.

**Comment by GoogleFrog** [comment]
All the button does is apply every single epicmenu option at the same time so my guess is that there is an option somewhere which is broken.

**Comment by TurBoss** [comment]
Thanks
