### ISSUE TITLE
Sharemode is too complicated

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1809]
The squad and subordinate system is too complicated. Why is a squad leader required at all? The two parameters for 'invite' don't make sense to me as your playerID always appears with the luaMessage anyway. Players don't need the complication of two different ways to say "I want to commshare with X".

**Comment by ArchShaman** [comment]
Okay, so how do we get the mergeID then? Lowest PlayerID? Biggest team size? 

A bonus if we keep the current implementation and remove some announcements is that we can create a sort of psychological warfare meta. Which is both awesome sounding and cool. Pros can 'merge' into newbies and totally terrorize the other team and make them overvalue the newbie! Or even merge newbies/average joes into pros and make pros look omnipresent/out-ecoing you.

I can see why it could be potentially complicated, however, I think some of the complication on the user side of things could be simplified with some nice icons: a teal commander with an arrow into a green commander (request merger), and a green commander into a teal commander (invite to squad).

**Comment by sprunk** [comment]
>Even if we were to get rid of leaders, who should be able to accept/decline invites?

Any team member?

**Comment by ArchShaman** [comment]
That is the plan now.
