### ISSUE TITLE
Low priority does not work properly (build priorioty)

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#181]
Start two projects, leave one on normal, put other on low priority.
Even when you stall you still get progress on low priority..
Normal should completely block low priority.
Best seen for example with moho geo morph + something on low prio.

This used to work properly in the past

**Comment by Orfelius** [comment]
This seems to be fixed now. Close?

**Comment by GoogleFrog** [comment]
It never did but I fixed the dev engine gadget so it will.
