### ISSUE TITLE
Something which is probably energy reserve prevents construction with zero storage

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1810]
It is now possible to lose all storage by losing all storages and commanders.  Energy reserve exists and is enabled by default. Without storage, only high priority projects seem to receive buildpower. 

This matches the behaviour of energy reserve to block all expenditure until energy storage threshold is exceeded. If the limit is above zero and storage size is zero, the limit can never be exceeded.

Also i was unable to discover how to disable the energy reserve.

**Comment by sprunk** [comment]
>It is now possible to lose all storage by losing all storages and commanders

[Is it?](https://github.com/ZeroK-RTS/Zero-K/commit/d0cf7f0807f90e1539e5360f7b115ffebd9c3646#diff-ecefc095b7d1b766fdbb38c1e910228fR44)

**Comment by Anarchid** [comment]
The initial default energy reserve is 25. While the objection is technically correct (the best kind of correct), 5 is well below 25.

**Comment by sprunk** [comment]
>The initial default energy reserve is 25.

[Initial.](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_priority.lua#L719)

**Comment by Anarchid** [comment]
Intriguing. At least the default economy bars widget did not clear the visuals for reserve when i partially reclaimed my commander while testing, destroying its storage. I haven't tested actually destroying it in that test.

**Comment by Anarchid** [comment]
Complete destruction of commander (and all other storages) results in 5 metal being spent on any new construction, and then a lock-up despite sufficient income to keep working. High priority still works around the problem.

**Comment by Anarchid** [comment]
Should be fixed by https://github.com/ZeroK-RTS/Zero-K/commit/a47a4bfa069f27717911902a29c85c90620d8e57
