### ISSUE TITLE
Unit start states nonsense

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1811]
Skirmishers (and certain arty units) are set to hold position by default in unit start states. This is bad because those units will not skirmish when set to hold position, leading them to suicide stupidly. They should just use 'inherit from factory' like everything else does.

Factories should probably be set to 'maneuver' by default, except for planes because their leash range is ridiculously short for their speed.

Also related: brawlers should not use air strafe by default, because it causes them to wander into enemy porc/units and die for no reason. Other gunships are probably fine as is.

I would just PR this but I don't even know where the start states defaults are stored. I checked the widget and found no mention of skirmishers or arty.

**Comment by sprunk** [comment]
>I don't even know where the start states defaults are stored

[Here](https://github.com/ZeroK-RTS/Zero-K/blob/master/units/armrock.lua#L45)

**Comment by Aquanim** [comment]
The start state in which a Rocko can be lured into range of a Stinger because it was chasing a constructor is an even more stupid start state. There is a reason why this is as it is. 

It is easier to make your units skirmish when desired by giving them a fight order than it is to stop them from chasing every time they are baited.

**Comment by mtroyka** [comment]
Is that not exactly what every other unit in the game does? I don't see why skirmishers are special, and if anything it's even more stupid when a  rocko is standing there and then dies to a random warrior because it failed to skirmish due to holdpos, which is way more common than baiting is. With skirmishers that have more range than rocko (esp wolverine, which outranges stinger, and vs llts for most other skirms) it's significantly worse. I don't agree with a default setting that defeats tactical ai and if someone wants their skirms to hold pos then unit start state can still be customized to achieve exactly that.

This is also why I intend to set facs to maneuver by default, because it's significantly less bad vs baiting than roam is.

**Comment by Aquanim** [comment]
>Is that not exactly what every other unit in the game does? I don't see why skirmishers are special
They have longer range, and by virtue of their role are frequently the first unit to engage the enemy. 

I don't park my Glaives just outside the range of a Stinger because there would be no point (they would be outranged by a unit protected by the Stinger. However, I would do that with Rockos more frequently.

>which is way more common than baiting is
I think you do not realise how much more frequently skirmishers would be baited than other units.

**Comment by Licho1** [comment]
Player should use fight (or attack move in nuspeak).

**Comment by Anarchid** [comment]
Skirmishers should skirmish.

**Comment by DeinFreund** [comment]
From what I've seen, hold position causes many more losses for newbies not knowing about the skirmishing ability/not having enough free APM than baiting. The default configuration should help them if we want to advertise smart units. Even for myself, setting racketeers to limited move made them a lot more effective than trying to move them, my shieldball and my raiders manually.

Fight move doesn't even work. You give the rockos fight move to the front. They arrive, stop and get killed by warrior. You'd always have to give a fight move to the enemy base for it to "work", which is even more suicidal. Patrol is a viable alternative.

If limited move is too dumb, make it smarter and look at defense ranges. Or just don't chase past your origin with skirmishers.

**Comment by Aquanim** [comment]
>From what I've seen, hold position causes many more losses for newbies not knowing about the skirmishing ability/not having enough free APM than baiting.

Since skirmishers start on holdposition and so don't get baited at the moment, this is exactly what I would expect...

**Comment by GoogleFrog** [comment]
I think this is fixed. Discussion was had, PR was made an pulled.
