### ISSUE TITLE
Storage Issues

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1816]
Currently if you lose all your storage, resource bars show full metal and empty energy at 0 each.

I think storage should be max(1, storage) so that if you lose all your storage then resource bars will show full metal/energy at 1 each.

Apparently there is 5 'secret storage', which resource bars do not correctly display. I don't particularly like that because if it were to be displayed correctly then you'd end up with weird numbers like 505 energy.

It's also bad for AIs that merge because it's no longer practical to have the subordinate AIs send resources but the 5 storage per subordinate can end up adding up to a fairly significant amount of unspendable metal/energy.

**Comment by DeinFreund** [comment]
Giving away your commander shouldn't affect storage capacity at all. I can confirm that this glitches out ai resource bars and even got me multiple accusations of my ai cheating because the income was displayed wrongly.

**Comment by GoogleFrog** [comment]
Fixed. The secret storage is a lower bound so it is not added to your storage if you obtain more storage. Also the lower bound is 0.5.
