### ISSUE TITLE
Remove shift to make the camera scroll rapidly

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1817]
If you hold shift the camera scroll speed is increased. I have never wanted this when I notice it. I'm holding shift to queue structures or orders and suddenly my camera becomes unusable.

**Comment by GoogleFrog** [comment]
Ctrl makes the camera scroll slowly which is also unwanted.

**Comment by DeinFreund** [comment]
This is one of the only ways to control camera movement for recording videos (which is already insanely complex because of a lack of any ingame camera customization besides cofc which is glitchy and fps hungry). Please keep it as an option or even make it configurable.

**Comment by Licho1** [comment]
I use both shift and ctrl at times (even in game when i want cinematic feel)

**Comment by sprunk** [comment]
Unbind `movefast` and `moveslow`

https://github.com/spring/spring/blob/7760dfff1ab725ced8b4a922fe8ae5a1fe9fb0b9/rts/Game/UI/KeyBindings.cpp#L233

**Comment by GoogleFrog** [comment]
I don't care much about zoom speed.

**Comment by GoogleFrog** [comment]
This ceased to work. Perhaps the engine automatically sets the key if it is missing.
