### ISSUE TITLE
Boxes don't generate random seed sometimes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1820]
[f=0028125] Shutdown Widget - Startup Info and Selector
[f=0028125] [cawidgets.lua] Error: Error in Shutdown()
[f=0028125] [cawidgets.lua] Error: Error in Shutdown(): [string "LuaRules/Utilities/startbox_utilities.lua"]:226: bad argument #1 to 'randomseed' (number expected, got no value)
[f=0028125] [cawidgets.lua] Error: Removed widget: Startup Info and Selector

**Comment by GoogleFrog** [comment]
Well if it's prevented from crashing then it won't crash.

**Comment by sprunk** [comment]
The source of the problem still lives though.
