### ISSUE TITLE
Bezier Curve screws GL state

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1824]
In this game ( http://zero-k.info/Battles/Detail/443537 )

(see south in mid of game) It cloaks, but I cannot see the cloaker bubble. Sometimes I could see it but not often, most of the time it was just gone and I could not see the cloak range- But cloaker work because units had the typical white halo.
I had that on other maps too but not so often like on red comet.

**Comment by GoogleFrog** [comment]
I need a screenshot and your infolog.

**Comment by Jamanno** [comment]
Ok.
I tried to switch camera mode but it does not had any effect. 
Tilding the world does not bring back the bubble but it changes how many units I see under cloaker.
![screen00008](https://cloud.githubusercontent.com/assets/5669626/21961385/db02f646-db08-11e6-9bd9-9947b68c8439.png)
![screen00007](https://cloud.githubusercontent.com/assets/5669626/21961386/db05e27a-db08-11e6-8bd3-579d2677fe0c.png)
![screen00006](https://cloud.githubusercontent.com/assets/5669626/21961387/db0b9e2c-db08-11e6-8b05-6c83967ed17c.png)
![screen00005](https://cloud.githubusercontent.com/assets/5669626/21961389/db106baa-db08-11e6-8cd2-ff17bb5fdcb3.png)
![screen00004](https://cloud.githubusercontent.com/assets/5669626/21961388/db0e7dcc-db08-11e6-9674-958091de0835.png)
![screen00003](https://cloud.githubusercontent.com/assets/5669626/21961390/db11b302-db08-11e6-94a0-c98287f091ed.png)
![screen00002](https://cloud.githubusercontent.com/assets/5669626/21961391/db1aeef4-db08-11e6-8d9f-587de106677f.png)
![screen00001](https://cloud.githubusercontent.com/assets/5669626/21961392/db1d93a2-db08-11e6-9107-21bcdd51cdb8.png)
![screen00000](https://cloud.githubusercontent.com/assets/5669626/21961393/db22b148-db08-11e6-8811-1176625a2515.png)

**Comment by Jamanno** [comment]
infolog
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/706490/infolog.txt)

**Comment by mtroyka** [comment]
I've seen this issue. I think it's probably lups related but lups never leaves any traces in infolog.

**Comment by GoogleFrog** [comment]
Nope, cloakers don't use lups.

**Comment by GoogleFrog** [comment]
Useful information to have known, it is reproducible for everyone who watches this replay http://zero-k.info/Battles/Detail/443537

**Comment by GoogleFrog** [comment]
Capture breaks area cloakers. Teleport probably does too.

**Comment by GoogleFrog** [comment]
Teleporter is fine.
