### ISSUE TITLE
Invalid local colors when spectating

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1827]
If you spectate a game with simplified colors, all people are green.
Selected team should show "self" color instead like in a real game.

**Comment by GoogleFrog** [comment]
None of the players are the "self" colour when you spectate a game. This is working as intended as the "self" colour is reserved for units which you can control.

**Comment by sprunk** [comment]
Make selected spectated team blue (not teal) or something like that?

**Comment by Licho1** [comment]
Is is not working as intended, when you select unit you affectively are watching that team, you see his energy stats etc and you should see his units colored differently otherwise there is no feedback. It's a very annoying bug, previously it worked fine.

**Comment by mtroyka** [comment]
I don't recall team colors ever changing based on who you had selected as spectator, although they do change based on which ally team you have selected if you use /luaui reload.

**Comment by Licho1** [comment]
They were changing there was event and it worked.

**Comment by Anarchid** [comment]
Selected team showing up as "self" color or any "selfy" color would require the selected AllyTeam to also switch to green, or else you may have the selfy color surrounded by the selected team's allies which are still red.

I have never seen the thing @Licho is talking about since 2011.

**Comment by Licho1** [comment]
I don't know about gaia but I'm playing with simplified colors since forever and mostly speccing and the change for spectators is very racent and very annoying.
It's not a design decision, It's a bug, there were events made to specifically support this thing.

**Comment by GoogleFrog** [comment]
The change is since December 2014 https://github.com/ZeroK-RTS/Zero-K/commit/4bd9f4154cc1238f494827ef50ff40adc0589485. I remember that there was some discussion and it was intended. I think Shadowfury suggested the change.

I don't recall the widget ever changing team colours based on the currently spectated team. widget:PlayerChanged was only added to the widget recently so I am sure it was never a feature. Perhaps the engine has something built-in which does what you are describing and you had it enabled (my guess for this would be cmdcolors.txt).

**Comment by Licho1** [comment]
I can make a video that shows it working just a couple of versions ago without any change in widgets or associated things.

**Comment by sprunk** [comment]
4bd9f4154cc1238f494827ef50ff40adc0589485 was just making teamID = 0 not teal. It didn't update when selecting another team (you saw stats of non-teal team).

**Comment by sprunk** [comment]
Working as intended according to GF (and as remembered by everyone else).

Also no showcase video from Licho. Reopen if something appears.
