### ISSUE TITLE
Chili Share Widget consumes H key

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1828]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1383

> This is in conflict with Integral Menu which uses H for its hotkeys (e.g. ZH for Strider Hub). Both widgets are default, so they should not conflict.
> 
> The use of hotkey by Chili Share Widget is also unconfigurable, so i can't even disable this behaviour.

**Comment by ArchShaman** [comment]
On it.
