### ISSUE TITLE
Lagmonitor sometimes doesn't give back units to returning players

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1837]
Today I saw a game where Connetable did not receive their units back after coming back from afk.
Replay: http://zero-k.info/Battles/Detail/443884

**Comment by GoogleFrog** [comment]
Did he use commshare at all? It voids warranty regarding receiving your units.

**Comment by GoogleFrog** [comment]
Commshare wasn't used. Relevant messages:
 * [f=0003613]  -> User is already ingame
[f=0003619] Player Connetable left the game:  normal quit
 * [f=0003630] game_message: Giving all units of topf to Shyrka due to lag/AFK
 * [f=0004379] Connection attempt from Connetable

**Comment by GoogleFrog** [comment]
Connetable seemed to lose connection, his units were shared to Shyrka successfully. No units were returned when he reconnected.

**Comment by mtroyka** [comment]
That also happened in this game: http://zero-k.info/Battles/Detail/443722

Commshare was never used, but units were not returned after the player came back from afk, forcing said player to beg (and they still never got their units back).

**Comment by GoogleFrog** [comment]
Fixed I think.

**Comment by GoogleFrog** [comment]
![screen00142](https://cloud.githubusercontent.com/assets/1318249/22093426/b3e2e194-de59-11e6-8723-d9e02cbd352e.png)

**Comment by mtroyka** [comment]
I don't think it's acceptable for commshare to prevent you from getting units back.

If player A joins a squad, lags out, returns, and then leaves the squad, does that mean they get nothing?

If other people who aren't A join a squad on A's ally team, and A lags out and his units are given to the squad, when he returns does that mean he gets nothing?

**Comment by ArchShaman** [comment]
> https://cloud.githubusercontent.com/assets/1318249/22093426/b3e2e194-de59-11e6-8723-d9e02cbd352e.png

What's wrong with this picture?

>If player A joins a squad, lags out, returns, and then leaves the squad, does that mean they get nothing?

No. Commshare tracks the owner before merging the player. It takes a table of all the units you currently own, merges them, then merges you. Upon unmerge: it checks if these are still valid IDs and still allied and if so, it gives them back.

>If other people who aren't A join a squad on A's ally team, and A lags out and his units are given to the squad, when he returns does that mean he gets nothing?

Nope. At least they shouldn't. This could be a potential edge case though. Perhaps an idea to prevent this is use some sort of UnitRulesParam that lagmonitor assigns saying 'this is owned by player blah blah. Don't count it as this player owns it'?
