### ISSUE TITLE
comshare and afk-widget bug

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#1841]
http://zero-k.info/Battles/Detail/443887

i went afk, was not in any comshare group. my afk-units were given to highest elo player Sigero.

then (or before me leaving?) Sigero melted with comshare with some other players.

on return, my afk units stayed with sigero's group. i was left with no units. (friendly players later donated manually units to me so i continued playing)

**Comment by ArchShaman** [comment]
This battle was taken place on an older version of ZK. Try with zk:stable (1.5.1.10)

**Comment by GoogleFrog** [comment]
Units aren't returned to returning afk players in Zero-K v1.5.1.8. Already fixed. A bug would have potentially occurred if Sigero unmerged with someone.
