### ISSUE TITLE
Think about collideFriendly = false

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1842]
Forb maintains that collideFriendly = false would improve ZK without changing anything important. I am not so sure. It is worth thinking about. Note that collideFriendly = false merely makes projectiles not collide with your own units. Weapons would still have avoidFriendly = true so their aiming would be unaffected. In short they would aim as if collideFriendly were unchanged.

The purpose of this change would be to stop teamkill that occurs close to the barrel. See Behemoth team damage or old Moderator. The downside is that projectiles would pass through units leading to a few things:
 * Suspension of disbelief issues if noticed. Rockets passing through your own units would be particularly noticeable. It doesn't make sense for units to avoid aiming at each other if the shots don't collide.
 * Low accuracy or high flight time units would be particularly affected. Rogue, Recluse, Catapult. If the rockets comes in at a low angle the unit may avoid damage. However since the rockets have AoE it is unlikely to occur.
 * Potential removal of things that are nifty strategies waiting to be discovered. Not sure what.
 * Shadowfury333 wouldn't get to exclaim every few weekends about a stray shot hitting an ally.

May be worth trying out.

**Comment by Anarchid** [comment]
Note that when Forb applied this to evo this was also with avoidFriendly=false, resulting in starcraft weapon  physics. His verdict was that nothing of value was lost there, too.

I don't think this will give much benefit to ZK.

**Comment by Licho1** [comment]
How would ZK be improved? Accidental friendly fire are cool and support the physicality.

**Comment by Anarchid** [comment]
I thought about this some more. 

If weapons avoid allies, but cannot hit allies directly, this is inconsistent: why do they avoid allies if they can't harm them anyway? Projectile path obstruction becomes less discoverable as a feature.

If weapons don't avoid allies and cannot hit them, then it's starcraft physics. Shieldballs inherit the world.

If weapons avoid allies and can hit them, we have ZK.

If weapons don't avoid allies and can hit them, we have hilarity.

**Comment by sprunk** [comment]
I think it can be ok to try on the select few weapons that **do** have an aiming problem **and** would **not** cause much visual inconsistency.

For example:
 * Moderator (old). Teamkilled, but failure cases only happened near the barrel and were usually at the edge of the hitsphere where clipping would've still looked plausible.
 * NOT Rocko. Teamkills, but rockets flying right through stuff would look completely ridiculous.
 * Behemoth. Teamkills, but shots are angled so will usually fly over most units and not get much chance to collide.
 * NOT Rogue. Shots are angled so won't look bad but there was no teamkill in the first place.

**Comment by mtroyka** [comment]
I think tk was worst for:
-old moderator
-sniper
-penetrator

I haven't seen behemoth tk that often, unless it was placed stupidly and also not on top of a spire, and in that case you get what you deserve. It's also mostly avoidable even then by setting the behe to high arc.

**Comment by Anarchid** [comment]
Last time i used behe i teamkilled by setting it to high traj. It clipped two Swifts.

**Comment by mtroyka** [comment]
lol.. speaking of swifts maybe it should be applied to tacnukes and silencer. Having those smash into random allied aircraft is bad and not a particularly intuitive use of weapon physics.

Personally I don't much care for new moderator. Face laser is a lot less elegant than the actual gun looking thing it used to have, esp if there's a simpler solution to their teamkilling behavior. It just seems like a bad reason for changing a model (imagine a stubby looking sniper).

**Comment by sprunk** [comment]
Sniper sounds like a good candidate:
 * very high impact teamkills
 * projectile is fast: unlikely to go straight through hitvolume, usually would just graze the edge
 * projectile hard to see: makes -noclip projectiles way harder to notice
 * long sniper rifle on the model conveys long range: noclip does not require model changes.

However I'd consider Penetrator bad for this:
 * my experience is that it seldom teamkills.
 * the beam lasts long and does not sweep fire so it is fairly likely to accidentally hit an ally.
 * the beam is the most obvious thing on the screen so safely piercing allied units would majorly break immersion.

(Tac)nukes already noclip through allies and wreckage.

**Comment by Licho1** [comment]
TK is part of fun imo, no point having physical simulationm, aiming etc if there are no teamkills.

**Comment by GoogleFrog** [comment]
So there seems to be some agreement on:
 * Ridiculousness of being able to see projectiles pass through allies.
 * Cool physicality of teamkill.

Here is what I'd like. It doesn't exists in the engine but it would be nice to see how much agreement there is. If a projectile a projectile is created inside the hitvolume of an allied unit then it should not collide with that unit until it leaves the hitvolume. This seems to fix the teamkill cases that we care about fixing. Perhaps such a tag and tracking could be added to the engine.

For now I'll make Rocko shoot from halfway down its barrel. Something similar could apply to Spectre.

**Comment by mtroyka** [comment]
I'm afraid that changing the emit point will have undesirable graphical consequences. Also rocko isn't really a major offender in terms of TK. It doesn't hit allies often and when it does it's usually because they walked into its shot.

**Comment by GoogleFrog** [comment]
There can be TK in packs as it turns. Similar to Spectre. Fight a group of 20 in a clump against something that they swarm (for example other holdfire Rockos).

**Comment by GoogleFrog** [comment]
Rocko was aiming form it's right elbow. The elbow that is stuck all the way out to it's right, further from its body. Sniper was aiming from it's neck. I'll make them aim in line with their gun and see how they behave.

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/commit/b7435b94970a0baf350fffc2bf0c6f18fdf10dc8

**Comment by sprunk** [comment]
Teamkills from stupidity (units firing when clipping) can be fixed by proper aimpoints and checks, and the consensus about the other forms of teamkill (units walking into projectiles in-flight) seems to be that they're cool physics to keep.
