### ISSUE TITLE
People who never loaded/showed up become flashing NullAIs

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1846]

**Comment by GoogleFrog** [comment]
If a unit is created for an AFK team then it should be transferred to a non-afk team. Ideally there would be a mapping function somewhere availible to lagmonitor which gives it a hint about where to send the unit. Otherwise it will go to the highest elo team (with a series of fallbacks).

**Comment by sprunk** [comment]
Duplicate of #2114
