### ISSUE TITLE
Commshare issues

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1847]
* many widgets stop working (transport AI, autogroup, etc) .. it is recommended to re-initialize those (/reload is the temp fix). Probably just call initialize of all widgets 

 * commsharing players have much higher stats and awards chances

 * commshare UI is needlessly complicated, why is there a "leader" .. all you need is for A to express desire to share with B and if B expresses desire to share with A they are in. No leaders needed.

 * when spectating, if commshare gets enabled, deluxe player list crashes

**Comment by sprunk** [comment]
>commsharing players have much higher stats and awards chances

This is not related to comshare, it always happens when cooperating. For example if I assist someone else building a strider he will get all the stats and awards from it.

**Comment by Licho1** [comment]
I think it is related, because it counts both as single player, so one player can have 2x the damage output of normal player.  That does not happen with normal cooperation.

**Comment by ArchShaman** [comment]
> commshare UI is needlessly complicated, why is there a "leader" .. all you need is for A to express desire to share with B and if B expresses desire to share with A they are in. No leaders needed.

Leaders are no longer as important as they were once. Now they're just the 'face' of the operation. Players do not see the effects at all. The only special privileges leaders have are that they can kick people.

**Comment by ArchShaman** [comment]
> when spectating, if commshare gets enabled, deluxe player list crashes
@Licho1 can you confirm that this still happens in zk:stable?

**Comment by Licho1** [comment]
Re-tested autogroup, still happens

**Comment by GoogleFrog** [comment]
Obsolete ticket? Some of the issues persist and others do not. Some are UI issues, others are bugs, others are just tasks.

**Comment by sprunk** [comment]
Split the ticket.

> many widgets stop working (transport AI, autogroup, etc) .. it is recommended to re-initialize those (/reload is the temp fix). Probably just call initialize of all widgets
#3884

> commsharing players have much higher stats and awards chances
#1849

> commshare UI is needlessly complicated, why is there a "leader" .. all you need is for A to express desire to share with B and if B expresses desire to share with A they are in. No leaders needed.
#1809

> when spectating, if commshare gets enabled, deluxe player list crashes
(probably a ticket existed but I assume it's since been fixed and cba digging)
