### ISSUE TITLE
Supposedly, AFK auto give to non-afk players stopped working

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1848]

**Comment by sprunk** [comment]
Replay?

Note that you can disable the giveaway locally (it is a widget).

**Comment by Licho1** [comment]
http://zero-k.info/Battles/Detail/444141

**Comment by ArchShaman** [comment]
Duplicate of #1841 ?
Related: #1846 ?

**Comment by sprunk** [comment]
I looked at chatlogs and mojjj was not actually afk because he immediately responded when people tried to kick him.
