### ISSUE TITLE
Recursion errorr at line 3221 of terraform gadget.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1850]
This is a spGiveOrderToUnit inside a CommandFallback. This is the only spGiveOrderToUnit inside the terraform gadget so it is the only way constructors recieve repair orders on the terraunits. Clearly this call must be working most of the time. My theory is that CommandFallback can be called directly as a result of an order being given. This would cause the recursion errors in those rare cases. Possibly an engine bug, I don't know how to detect whether recursion is allowed here.

**Comment by KingRaptor** [comment]
Older version of #2256
