### ISSUE TITLE
Have Shadowfury333 test OBS with 64 bit spring

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1854]
* Look here: https://springrts.com/dl/buildbot/default/develop/103.0.1-519-g91b0000/win64/
 * Download spring_{develop}103.0.1-519-g91b0000_win64-minimal-portable.7z
 * Open chobby local data engine folder.
 * Rename the folder "103.0.1-519-g91b0000" to something (I suggest "103.0.1-519-g91b0000_32bit")
 * Put the contents of the download in a folder named "103.0.1-519-g91b0000".
 * Run chobby and use task manager to check that Spring is 64 bit.
 * Try to use OBS.

**Comment by dvr333** [comment]
OBS (at least old OBS) seems to work fine. Were you expecting any bugs or is this just a double-check?

**Comment by GoogleFrog** [comment]
Just a check.
