### ISSUE TITLE
Outlaw default state discussion

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1855]
An Outlaw on always-fire destroys wrecks and cannot be cloaked.

An Outlaw not on always-fire does not detect cloaked enemies.

I think I slightly prefer not always-fire as default but I don't think it's a clearcut decision.

**Comment by GoogleFrog** [comment]
I think the important factor is what new players will be yelled at to do more often. Pick one:
 * Turn off your Outlaws! I'm trying to reclaim!
 * Turn on your Outlaws to detect those cloaked things!

I think the most likely situation is the first, once people realize just how much reclaim you can lose to Outlaws.

**Comment by mtroyka** [comment]
What? Since when has anyone ever said to a new player anything besides "oh you're shields, build thugs and outlaws, and remember to turn your outlaws 'on'!"

**Comment by GoogleFrog** [comment]
Well, perhaps many people don't mind about reclaim. But I think the fact that Outlaws haven't been on by default is a factor.

**Comment by mtroyka** [comment]
I don't know if many people are even aware of their effect on reclaim, but the biggest enemies of a shieldball tend to be cloaked. ie ticks, roaches, scythes, skuttles, and to a lesser extent trollcoms, ultis and fields of wolverine mines. They also sweep out snipers if you get close enough and can dig up fleas to prevent scouting and harassment.

**Comment by Licho1** [comment]
Keep it on and disable effect on reclaim.
Forcing people to enable outlaw to perform their designed duty is silyl micro sink.

**Comment by Anarchid** [comment]
I like the effect on features because it allows me to mass clear forests on Altair Crossing. It also should be fairly visible now that features poof on death.

Outlaw's designed duty is a riot / force-multiplier. It performs this automatically by pulsing when enemies enter range.

**Comment by sprunk** [comment]
In my experience there are two types of new players:
 * the rare competitive newbie will probably keep units at front where reclaim exists.
 * the typical newbie is a porcnab and will just accumulate a shieldball in the corner, then get blown up by 1 skuttle when he moves out.

**Comment by Licho1** [comment]
I never ever noticed it cleans reclaims. Imo it's rather undesirable effect in majority of cases.

**Comment by mtroyka** [comment]
>I like the effect on features because it allows me to mass clear forests on Altair Crossing.

Trees die instantly when pretty much any unit comes in contact with them. The only time when trees cause a problem is if you want to build something on top of them, in which case the worker will reclaim them first which usually takes longer than just running the tree over. The worst case for that is facplops anyway, which is irrelevant to this discussion. For that matter I'm pretty sure even fleas can be used for clearing trees on most maps (since it may depend on feature settings or feature naming, as it applies to ZK's (s)tree(tlight) detection algorithms).

>I never ever noticed it cleans reclaims. Imo it's rather undesirable effect in majority of cases.

I think that's more of an argument for removing outlaw damage vs features than for setting outlaw to be turned off by default, particularly since outlaws' damage vs features is basically the only argument for having them be turned off.

**Comment by Anarchid** [comment]
Trees block fire on Altair. This renders turrets much less effective.

**Comment by mtroyka** [comment]
I've noticed turrets avoiding shooting through trees. Is there a way we can make them ignore trees? Dumb behavior is dumb, and if you chose a fac that isn't shields then you wouldn't even have outlaws as an option for dealing with that.

**Comment by Anarchid** [comment]
Reclaiming them also works, for the others. But Outlaw just makes them poof and i like the feel of that very much.

**Comment by Licho1** [comment]
Maybe it could also just destroy trees and not metal features?

**Comment by mtroyka** [comment]
I don't think it's possible to discriminate between energy-only features and features that contain metal. I also don't think avoidfeature is a good idea, at least not for statics. For mobiles avoiding features can also prevent wasted shots and unintended destruction of wrecks, but for statics it mostly just stops them from shooting at enemies that are in range.

**Comment by Anarchid** [comment]
> I don't think it's possible to discriminate between energy-only features and features that contain metal.

https://springrts.com/wiki/Lua:Callins#Damage_Controllers

**Comment by Licho1** [comment]
It looks to me like it is, if not we can hack around or add it to engine.

**Comment by mtroyka** [comment]
hm.. perhaps. The xPreDamaged functions might work, although it's definitely hackish.

**Comment by Anarchid** [comment]
UnitPreDamaged is already how Outlaw manages to not kill allies.

**Comment by mtroyka** [comment]
Wow. I thought for sure it was a weaponDef param.

**Comment by sprunk** [comment]
I'd make Outlaw treat all features as non-enemies and unfeature Altair for excessive forestry.

**Comment by GoogleFrog** [comment]
I'd leave Outlaw as is for reasons to not keep it always on (and reduce the hitvolume sizes on Altair).

**Comment by sprunk** [comment]
It looks like it was decided to keep status quo.

**Comment by GoogleFrog** [comment]
Actually, Outlaws now deal significantly less damage vs features. Previously slow damage was counted as real damage vs features as the alternative too work to implement. This basically only affects Outlaw.

https://github.com/ZeroK-RTS/Zero-K/commit/4408a3f24b92a85d99b521a482b380ebc90150e3
