### ISSUE TITLE
Merge player names

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1856]
Make an API widget which detects commshare and returns merged names, i.e., an AquaFrog generator. Make widgets such as tooltip and awards use these names. The first name could be the squad leader. Figure out a non-silly way to merge names.

**Comment by sprunk** [comment]
Most ways fail in some regard.

Actual "AquaFrog" style mangling:
 * very hard to make sensible names, even from "regular" words
 * outputs garbage when there's many people
 * what if there's an actual player called AquaFrog

"Aquanim + Googlefrog": too long for tooltips (even with 2 people)
"Aq. + Goo.": short but not really a "good" name
"Aquanim +1": does not show the composition

**Comment by Licho1** [comment]
Stupid idea, this wont work with server side tracking. Think harder.
