### ISSUE TITLE
Resource bars don't flash on estall when "no storage" is shown.

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1859]
http://zero-k.info/Battles/Detail/444280

After malric lost his com for a while he had greater metal income than energy. The metal warning message disappeared when he spent quickly enough but there should have been an estall warning at the same time.

**Comment by dvr333** [comment]
[This](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_chili_economy_panel2.lua#L641) is the relevant line of code, and cp.team_energyWaste is set [here](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_chili_economy_panel2.lua#L334) based on Spring.GetTeamRulesParam(), so it seems like the assumption is that this parameter is correct for 1v1 (as in, it equals energy excess).

**Comment by mtroyka** [comment]
So it seems like it's incorrectly only flashing on energy excess (which almost never occurs anyway) rather than on estall.

**Comment by sprunk** [comment]
With "no storage" there seems to be some flashing but it's limited to the 1px wide line (not text).

**Comment by mtroyka** [comment]
It flashes on metal excess but not on estall.
