### ISSUE TITLE
Have Licho test black window sleep with 103.0.1-529-gb68830c

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1860]
Latest engine seems to have fixed the black window bug that I was able to reproduce. Licho should test his screen sleep or VS coding version.

See https://springrts.com/mantis/view.php?id=5433

**Comment by sprunk** [comment]
The engine ticket is marked fixed and there was no negative feedback.

**Comment by Licho1** [comment]
Actually I had sortale? report just such bug recently and I had it too, but it's much more random and rare.
