### ISSUE TITLE
Commshare frustrations

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#1861]
- [x] Initial states

Initial states for Commshare seem to cause a lot of frustration. I propose one of the following solutions:

* All units are Inherit from factory.
* All units are default initial states.
* Try to find common (1/2 or more of commshare team) settings for the commshare team, else fall back to default.

This would reduce the frustration encountered in commsharing. None of the above will make a perfect solution, however, they attempt to alleviate it by preventing weird initial states that the leader may have.

- [x] Lack of selection viewing (as a default)

In addition, another common complaint is the lack of visual feedback of selected units by squad members. To solve this I may modify some selection viewing widget to show the selections of squad members. Ideally you'd have different colors (perhaps the original team color? Or something?) for different players. Or maybe a squad player list or something to represent these colors. Ideas would be welcome on this.

_I'll be adding more as I get more feedback on the matter. These two seem to be the major sources of frustration and I think they may be easy to knock out._

**Comment by GoogleFrog** [comment]
I'd neuter the initial unit states of non-leaders. That is, initial unit states should check whether you are the leader of your team every time it thinks about doing something (so immediately in UnitCreate etc...). I hope that leader aligns with who sent the first invite so people can coordinate as to who sets the states. At worse this prevents weird mergings of two peoples different states.

I looked at selection viewing and the selection send API widget was too messy for me to look at quickly. It is definitely something to add though. Widgets which view selections should have an additional option, view squad mates, that would become the new default.

**Comment by ArchShaman** [comment]
Sounds good. I'll take a look at what I can do.

>  I hope that leader aligns with who sent the first invite so people can coordinate as to who sets the states. At worse this prevents weird mergings of two peoples different states.

Yes, it does.

**Comment by sprunk** [comment]
>Whoever sends the invite is the one the recipient joins

According to a comment in #1858 this does not hold for squad-squad merge where the smaller team always joins the larger one.

**Comment by ArchShaman** [comment]
Hm.. yeah forgot about that. :D

**Comment by sprunk** [comment]
Initial states done https://github.com/ZeroK-RTS/Zero-K/commit/665a880c2ccd9ae318851b82b11a181c972355ee

**Comment by sprunk** [comment]
Selections done https://github.com/ZeroK-RTS/Zero-K/commit/cae37140b20120440a4fc2e08a680f8bae5c697d

**Comment by GoogleFrog** [comment]
Looks all done.
