### ISSUE TITLE
The Siren's sonic weapon sound doesn't fit

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1870]
The sound the Siren's sonic gun emits makes me think of a jump sound effect in an old-school platformer.

**Comment by Anarchid** [comment]
Browse freesound until you find a good candidate replacement sounds.

**Comment by Anarchid** [comment]
Perhaps one of these will fit. http://freesound.org/search/?q=laser&f=grouping_pack:%2213396_Weapons%22%20&s

Now you also have to come up with a fitting impact sound.

**Comment by Anarchid** [comment]
Doesn't seem that important i guess.

**Comment by Sgathec** [comment]
@Anarchid, @GoogleFrog, maybe this one? https://files.fm/u/nqd95f3b

**Comment by Anarchid** [comment]
I think on of laser02 sounds from the previous pack would be better. The problem with both this and that is that the weapon really also needs a matching impact sound.

**Comment by Sgathec** [comment]
What should the impact sound be like if the above sound is used?

**Comment by Anarchid** [comment]
The current sound went with the idea of "vibration damage and cracking". 
You can try that, or try a "liquid-sounding energy explosion".
Both of these would work regardless of what of the so far proposed sounds ends up used.

**Comment by Anarchid** [comment]
I tried to make a sound in the splashy liquid approach. I don't think it turned out well. Also the sound cloud copyright detector seems real good at finding copyright in white noise.

https://soundcloud.com/anarchid/sonic-splashboom?in=anarchid/sets/sonic-cannon-wip

**Comment by GoogleFrog** [comment]
@Sgathec it sounds a bit low and rushed.

**Comment by Sgathec** [comment]
Is it still more suitable than the current one? I could scale it easily to make it longer.

**Comment by sprunk** [comment]
981c56b31fcdf575676d33c576049053e1091220
