### ISSUE TITLE
Snapping to the unit radar icon while targeting could be unwanted

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1873]
Please consider allowing disabling the behaviour that automatically targets the unit radar dot after clicking beside it. However, I'm not sure if it can actually prevent targeting the real position of the enemy unit, but I suspect it could happen if the enemy unit is small. Besides, targeting the radar icon will cause the targeting of the attacking unit to follow the radar dot which is undesirable if one would like to keep firing at the same point.

**Comment by GoogleFrog** [comment]
Bring me up to speed. What is going on? Screenshots?

**Comment by Sgathec** [comment]
Radar dots are often off the actual location of the target enemy unit. One may want to scout the enemy and target the ground corresponding to the real location.

**Comment by Sgathec** [comment]
![targeting](https://cloud.githubusercontent.com/assets/2042701/22298186/4c708d3a-e328-11e6-9ef0-9bda2d095650.jpg)

**Comment by Anarchid** [comment]
Did you issue the order by left-clicking with a Fire command, or by right-clicking near the icon? Did you by any chance double-right-click?

**Comment by Sgathec** [comment]
I selected the Fire command and left-clicked.

**Comment by Anarchid** [comment]
This seems to be happening when X and Z coordinates of the target are sufficiently close to the target unit. It doesn't seem to depend on target footprint that much. Looks like engine.

**Comment by GoogleFrog** [comment]
BTW I've never reproduce this.

**Comment by Anarchid** [comment]
I can no longer reproduce this either on 103.0.1-540.

**Comment by sprunk** [comment]
@Sgathec can you still reproduce on latest?

**Comment by DeinFreund** [comment]
it would be nice if we could attack any ground position using the manual attack command. not snapping to enemies even when clicking on their model. currently one needs to use widgets to target specific parts of a unit, this should be possible for everyone.

for snapping we have right click attack.

**Comment by sprunk** [comment]
This ticket is for a bug with snapping. Whether snapping is desired at all is a related but separate design issue. Make another ticket.

**Comment by Sgathec** [comment]
@DeinFreund's comment explains this issue pretty well. There is no bug.

**Comment by sprunk** [comment]
I think I misinterpreted the first post. Which end of the white line did you click, A or B?

![ffs](https://cloud.githubusercontent.com/assets/2573076/24055824/e2feffa2-0b41-11e7-86d1-7b7b3f525dbc.png)

**Comment by Sgathec** [comment]
B.

**Comment by Sgathec** [comment]
Sorry, I think I explained inadequately by accident. I've modified the picture.

**Comment by sprunk** [comment]
Thanks, I previously assumed you clicked the other end of the line (which would be a bug, snapping from very far away).

Since this is now about UI design @GoogleFrog could probably say something. At any rate it's a bit of a pie in the sky though.

I think the best thing to do is to add a menu option (defaulting to off) which makes manual forcefire snapless. A modifier key would probably be better but we ran out of modifiers for that command.

**Comment by ashdnazg** [comment]
alt already does this more or less

**Comment by Sgathec** [comment]
I thought it might but I didn't test it. Now I plan to the next time I log in.

**Comment by sprunk** [comment]
If ALT works with singular dragless click then yes, it would solve the issue. I'm fairly certain that some modifiers require drag though (even a very tiny one).

**Comment by ashdnazg** [comment]
I indeed use drag.

**Comment by GoogleFrog** [comment]
Making this available only with Alt seems fine to me. It is a rare request.

**Comment by sprunk** [comment]
I tested and Alt already works for point click (including right click).
