### ISSUE TITLE
Economy panel error on load

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1874]
[f=-000001] Chili-Error in `Chili Economy Panel Default`:warningImage : [string "LuaUI/Widgets/chili/controls/control.lua"]:262: attempt to index local 'p' (a userdata value)

[f=-000001] stacktrace:

	[string "LuaUI/Widgets/chili/controls/control.lua"]:262: in GetRelativeBox

	[string "LuaUI/Widgets/chili/controls/control.lua"]:339: in AlignControl

	[string "LuaUI/Widgets/chili/controls/control.lua"]:372: in Realign

	[string "LuaUI/Widgets/chili/controls/control.lua"]:769

	...

	[string "-- $Id: camain.lua 3171 2008-11-06 09:06:29..."]:84

	[string "LuaUI/Widgets/api_chili.lua"]:110

[f=-000001] Removed widget: Chili Economy Panel Default

Here is an error that occured once. Dosen't make sense to me since the controls are userdata.

**Comment by sprunk** [comment]
Chili controls are tables (in this particular case the 'p' variable is the control's parent which is supposed to be another Chili object, ie. a table as well).

Userdata is a special type that is basically a pointer to some C++ object, and the Lua language itself has no builtin means of creating it (ie. it has to be provided through some Spring.Bla function). Things that are userdata in Spring (thus potential culprits) are Fonts and Screams (which are used by Chili API) and others which I doubt are involved (RBOs, FBOs, Zip file handles, PathFinder, rendering Materials, OpenGL occlusion queries, and the SendToUnsynced function).

**Comment by GoogleFrog** [comment]
They are userdata, not tables. type(p) == "userdata" confirms it.

**Comment by Anarchid** [comment]
`p` which is us userdata in this stack trace is assigned at https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/chili/Controls/control.lua#L256 from the control's parent.

Control inherits the parent reference from object. Object contains a SetParent function which checks whether the parent argument is in fact a table https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/chili/Controls/object.lua#L208 

This suggests that controls and objects are supposed to be tables, not userdata; that parents of controls and objects should be tables, not userdata; that the p variable at control.lua:262 should be a table, not userdata; that whatever the widget does to have this line end up attempting to index an userdata is erroneous.

**Comment by sprunk** [comment]
#2692
