### ISSUE TITLE
Recently it has become diffucult to select some units with mouse click.

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#1877]
Good example is ship factory. Clicking on wall areas of factory does not select it.

**Comment by mtroyka** [comment]
I've also seen this. Debris is also very difficult to select.

**Comment by GoogleFrog** [comment]
Dev engine fixes mouse raytraces such that you can mouseover and click on units exactly when their hitvolume is under your cursor. This makes them easier to select but is not great for offset factory models. At least, not great for people used to the old models.

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5258

**Comment by GoogleFrog** [comment]
Fixed https://github.com/spring/spring/commit/e2eeee6faa11c39c9945e12f21da8811b8f525fa
