### ISSUE TITLE
Mess with chicken difficulty

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1889]
Very easy chickens is hard for brand new players. There should not be any chicken assault in the first 10 or so minutes that can't be fought off with a poorly used commander. Very easy currently spawns about 20 chickens as the first wave and mixes in many chicken types. The current very easy may be better as easy.

I plan to have 4 difficulty levels for the quick skirmish menu. Very easy, easy, medium and hard.

**Comment by KingRaptor** [comment]
I have some ideas for an easier entry into a given chicken match, but I'm concerned about the already-large gap in difficulty between Very Easy and Easy. If it's too large you get a dead zone where one is too boring and the other too hard, which sounds like something certain to happen if "comm can solo waves during the first 10 minutes" is an actual design goal.

For the quick skirmish menu the chicken options could be:
- New "beginner" difficulty
- Current very easy
- Current easy
- Current normal

**Comment by mtroyka** [comment]
Very easy chickens is embarrassingly easy. :| If new players find it too difficult then the problem is not in chickens but everything that comes before that.

**Comment by sprunk** [comment]
What do you mean by "everything that comes before that"? You can go straight into a game and people often ignore tutorials.

**Comment by Anarchid** [comment]
More frequent but smaller waves are a way to go, imo.

**Comment by KingRaptor** [comment]
Generally speaking, do we think "did not touch tutorial or a previous RTS game" is a situation for which actual SP game options should exist?

**Comment by KingRaptor** [comment]
I've made Very Easy as easy as I'm prepared to go. Reopen if specific changes are desired.

(I now think that making "player has no armed units except poorly handled comm for 10 minutes" a playable state really doesn't make sense; if people don't know RTS and don't play the tutorials they have full liability as far as I'm concerned)
