### ISSUE TITLE
CPU usage values not being reported correctly

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#1890]
In both Deluxe Player List and the engine-level display from /info, many (but not all) players display CPU usage as 0%. This is presumably an engine issue. I believe it happened sometime in the last few weeks' worth of updates; around or after when we used 298.

I've checked with other players and they see the same thing; if somebody can confirm it's an engine issue then I guess it should be mantised.

**Comment by Anarchid** [comment]
Threading was touched in engine since 298 because the previous model was implicated in a desyncgate.

**Comment by Aquanim** [comment]
I am unsure how to interpret that statement - is that corroboration that engine changes are likely implicated?

**Comment by sprunk** [comment]
Yes.

**Comment by Aquanim** [comment]
Okay it's already mantised.
https://springrts.com/mantis/view.php?id=5441

**Comment by GoogleFrog** [comment]
Fixed in 103-570.
