### ISSUE TITLE
Check OD

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1895]
See http://zero-k.info/Battles/Detail/445556

**Comment by GoogleFrog** [comment]
32:54.

**Comment by mtroyka** [comment]
There were also several periods starting around the 25 minute mark where you were draining your energy storage (negative net income) and yet your mexes were still being driven at 80% OD. Near the start of the game there was also a point where you had more metal stored than energy and were getting OD. Both cases are definitely bad.

The fact that it was a team game might be related.

**Comment by GoogleFrog** [comment]
I think lastTeamOverdriveSpending is incorrect now that energy spent on OD doesn't even technically pass into storage.

**Comment by GoogleFrog** [comment]
I think this fixes it: https://github.com/ZeroK-RTS/Zero-K/commit/3bc6cf84f0028d0ed87b6fe4c8b51c1cdc7ab6c4
