### ISSUE TITLE
Epic Menu Search function crashes LuaUI

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1897]
1) Press Esc to open menu
2) press search on the bottom row
3) type anything and press enter
4) Game hangs for a dozen seconds, then LuaUI crashes.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/d25dacd6d162d07262010d0529c073f7e6b840c9
