### ISSUE TITLE
New goliath on fight move doesn't move into firing range

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1901]
It just moves close enough to fire the slow beam, but fails to get close enough to fire the main cannon and just sits in front of defender, waiting to die.

**Comment by mtroyka** [comment]
This might depend on relative heights, since slowbeam uses spherical range and its cannon is ballistic. That doesn't seem like it'd be easy to fix, either.

**Comment by DeinFreund** [comment]
In this case it happened on ccr, but of course a general fix would be preferred.

**Comment by mtroyka** [comment]
Well, one possibility would be to make slowbeam range slightly smaller. The other would be to use tactical ai to make goli dive slightly. I'm not sure which is worse. :P
