### ISSUE TITLE
Replay Controls and Attrition Counter use wrong skins

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1905]
http://imgur.com/JSmTK1A

Everything else was using the teal-outline skin, while those two widgets were randomly using the "evolved" (I guess?) skin instead.

**Comment by GoogleFrog** [comment]
Everything is using the evolved skin in that screenshot. That is what Replay Controls and Attrition Counter look like with Evolved. That is what the other panels look like with a non-default UI setup and Evolved. You can make a skin, put it in a local folder and use that if you like.
