### ISSUE TITLE
Resource bars no longer show pull

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#1906]
Instead they show "...". Also the arrows over the resource bars seem to be indicating pull instead of net income, which would make more sense.

**Comment by GoogleFrog** [comment]
Screenshot.

**Comment by mtroyka** [comment]
http://imgur.com/C6kOHQs

**Comment by GoogleFrog** [comment]
You need to make the resource bar slightly taller to give it the space to display that number.

**Comment by sprunk** [comment]
The "..." part is solved (caused by manually shrinking the widget).
The "pull instead of net income" part is #1834.
