### ISSUE TITLE
"Zed 2.2" has purple square lava bubbles.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1909]
Either
 * Fix the bubbles.
 * Remove the bubbles.
 * Remove the map.

**Comment by The-Yak** [comment]
https://springrts.com/phpbb/viewtopic.php?f=23&t=31159&start=20

This issue affects all lavamaps. It seems as if an engine update has changed the way /gamedata/ bitmaps are referenced.

I think adding the lavasplosion bitmap graphic gameside may be a fix for all lavamaps but I need to investigate further.

**Comment by The-Yak** [comment]
Wouldn't object to unfeaturing lavamaps either.

**Comment by ashdnazg** [comment]
I'm working on this

**Comment by ashdnazg** [comment]
Fixed https://github.com/spring/spring/commit/e323ef4a96a432e29e91a42724f6704406a385a7

**Comment by sprunk** [comment]
Thanks!
