### ISSUE TITLE
"Fancy skinning" option spam

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1914]
Most panels seem to have a fancy skinning option now. To me this seems like clutter because the real option is the choice of layout preset which changes these in bulk as individually choosing this per widget offers no visual consistency.

**Comment by GoogleFrog** [comment]
Fancy skinning is basically an internal option that exists because it is a nice interface for HUD presets to change skins.

**Comment by sprunk** [comment]
Yes, that's the point. I think it would be good if this didn't appear in the options menu.
