### ISSUE TITLE
Unit state on constructions dont work on default settings

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1917]
- start a starlight
 - click on/off to turn it off
-> nothing happens, button stays green and starlight activates when finished.

This should not happen, it should be possible to change unit state before completion.

**Comment by KingRaptor** [comment]
This issue occurs even with /luarules disable and /luaui disable. Is it a hardcoded engine behaviour?

**Comment by Anarchid** [comment]
Possibly this is due to `activatewhenbuilt` ?

**Comment by sprunk** [comment]
`activatewhenbuilt` just makes it toggle On when finished, but the block during nanoframe is applied indiscriminately I think.

**Comment by Anarchid** [comment]
Looks like [indeed](https://github.com/spring/spring/blob/7760dfff1ab725ced8b4a922fe8ae5a1fe9fb0b9/rts/Sim/Units/CommandAI/CommandAI.cpp#L717) engine blocks on/off command processing for nanoframes.  I guess this can be dealt with like cloak?

**Comment by sprunk** [comment]
13b9e40af170136a444a4b5c98bd00f2fe2086ec

**Comment by GoogleFrog** [comment]
I searched the issue tracker for some likely words when I made the commit. I did not find this ticket.
