### ISSUE TITLE
Default GUI: no key-way to cancel tab selection

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1924]
1) pick a tab using keybind, like x for econ
2) change mind
-> you are stuck and need to use mouse.

It should be possible to use some key to cancel current tab, it happens a lot when learning a game (or switching from gesture menu)

**Comment by Anarchid** [comment]
I think Esc either does it, or should do it.

**Comment by Licho1** [comment]
Escape didnt help/

**Comment by GoogleFrog** [comment]
Fixed previously.
