### ISSUE TITLE
Default GUI: area commands not visible when issued on minimap

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1925]
Repro:
1) select con
2) press W
3) drag a circle on minimap (not on map)
-> fail

**Comment by sprunk** [comment]
Engine. https://springrts.com/mantis/view.php?id=5619

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/43cbfe4506b7487886d091d4dc9093ec34d836a3
