### ISSUE TITLE
Enable F4 econ view by default

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1926]

**Comment by KingRaptor** [comment]
Do we want to turn economy view (required for right-click spot to build) on by default?

**Comment by Licho1** [comment]
Yes? It is ugly but very useful.

**Comment by dvr333** [comment]
It may be ugly now, but I think it could become quite pretty. Company of Heroes uses a similar economic UI on their control points, and it fits well.

**Comment by sprunk** [comment]
I agree to enable it by default. Feedback from some newbie:

>[19:21] Lukasmah: Wait, how can I tell where the resource points even are? I don't see anything recognisable until I select the metal extractor in the building menu
[19:22] Lukasmah: I won't have to use that all the time, will I? Am I missing something or is that just how that works?
[19:22] Lukasmah: Then again, some models have failed to render for me until I switched to compatibility mode, there may be more that still don't work
[19:23] Lukasmah: I mean, I guess this works, though it's mildly inconvenient

**Comment by GoogleFrog** [comment]
This is bad. Geos are super ugly and grid ranges are mostly irrelevant. Improve maps to show resource points.

**Comment by Porkch0p** [comment]
For the wreckage highlight, I've made a menu for its widget that doesn't change any defaults, but allows you to show and hide the highlights, control the brightness of the flashing wrecks, or hide the smaller wrecks for some performance improvement. Also, it adds the option to highlight reclaim before match start if you just want to see an overview of the map resources.

https://github.com/Porkch0p/Zero-K/tree/metalGlowOptions

**Comment by sprunk** [comment]
Feel free to make PRs, it lets us know that your stuff exists and makes it easier to review.
I made one for the `metalGlowOptions` branch: #3529
