### ISSUE TITLE
Remove lagmonitor fac workaround after applying new engine

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#1928]
I was kicked from a Commshare group and most if not all construction progress of a unit being built by a factory was cancelled. I suspect the unit was actually lost and the construction of a new unit was started. That can be costly if the factory was building a 99% Goliath for example.

I was also given a factory in another battle and the donator claimed the unit being built was lost.

**Comment by Anarchid** [comment]
Thing to check: whether automatically giving the built unit together with the factory circuments this.

**Comment by GoogleFrog** [comment]
Lagmonitor has a workaround for this issue. Perhaps write a unit sharing API to use this solution for both gadgets.

**Comment by sprunk** [comment]
Fixed in engine: https://github.com/spring/spring/pull/312

Also allows the removal of the lagmonitor workaround.
