### ISSUE TITLE
unitdefs_posts error, possibly bad download

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1933]
https://github.com/ZeroK-RTS/CrashReports/issues/73

**Comment by sprunk** [comment]
`[f=-000001] Error: 2, gamedata/defs.lua, [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/unitDefs.lua, error = 2, gamedata/unitdefs_post.lua, [string "gamedata/unitdefs_post.lua"]:113: invalid call to Include() after execution`

Include cannot fail under normal circumstances so bad download: nothing to do gameside. Possibly something could be done infra-side but eventually validity checks will be done by Steam so anything we do wrapper-side would be duplication.
