### ISSUE TITLE
Improve left click hold terraform

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1934]
Left-click-hold terraform is possibly enableable by default if it only works if the mouse is pressed and held near the location it is pressed. The UI issue comes from players discovering line build and hesitating during line build. This would remove their line build order and replace it with height selection.

This issue is solved if press and hold can only happen near the initial pressed location.

**Comment by sprunk** [comment]
Fixed according to this post: https://zero-k.info/Forum/Post/171623#171623 and reenabled by default.
