### ISSUE TITLE
Future engine breaking change reminder

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#1936]
https://github.com/spring/spring/commit/8dcb259fe4411adf573b8449c012865e924d0a6e

! Changed the order of AllowStartPosition parameters and added a new one:
Old: clampedX, clampedY, clampedZ, playerID, readyState, rawX, rawY, rawZ
New: playerID, teamID, readyState, clampedX, clampedY, clampedZ, rawX, rawY, rawZ

**Comment by GoogleFrog** [comment]
Add reverse compat to widget and gadget handler.
