### ISSUE TITLE
Remove start positon placement with save/load

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1940]

**Comment by KingRaptor** [comment]
Setting `StartPosType=0` in the startscript when loading widget does not appear to do anything.

**Comment by sprunk** [comment]
It should at least remove the need for click, and start the countdown immediately (because boxes use engine side stuff for that).

**Comment by KingRaptor** [comment]
To clarify: When I set `startpostype` to 0 it still uses 2 (as verified by echoing `Game.startPosType` after loading)

**Comment by sprunk** [comment]
Not an issue in engine save.
