### ISSUE TITLE
Purple heart award is geborked.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#1944]
How to reproduce: go into any 1v1 replay page that has one side reciving a purple heart and the other a complete annihilation award.
http://zero-k.info/Battles/Detail/446555?ShowWinners=True
http://zero-k.info/Battles/Detail/446533?ShowWinners=True

As you can see the losing player recived from 3 times more to 4 times more damage than the other managed to deal. Statistically this is possible if the losing player teamkilled their own units but if you see the replays that is not the case.

I suspect that it may count the resign explosions as actual dealt damage which they shouldn't.

**Comment by sprunk** [comment]
Purple heart counts health damage, not cost damage.

**Comment by Orfelius** [comment]
And Complete Annihilation counts cost damage? Apologies, I didn't know that.
