### ISSUE TITLE
Run luarules buildicon on Moderator

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1945]
![image](https://cloud.githubusercontent.com/assets/3822768/22978703/731b48f6-f39c-11e6-90f7-7a655cb0fa22.png) Is not how the current clockwork Moderator looks.

**Comment by mtroyka** [comment]
how about we revert to the old moderator and fix its stupid aimpoint instead? New moderator is hideous and derpy.

**Comment by Anarchid** [comment]
You can do that, too.

**Comment by mtroyka** [comment]
Actually I probably can't, or at least I have no idea how since I don't have local copies of the old model/texture/script. :|

**Comment by Anarchid** [comment]
Git has them. Just checkout the file(s) at previous hash.
