### ISSUE TITLE
Default GUI: chaotic sniper mark

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1950]
Make the game look like a giant bug:
http://i.imgur.com/CXceDDH.jpg

**Comment by GoogleFrog** [comment]
This looks like Sprungs recent sniper spotter widget. He said it did nothing by default though.

**Comment by Licho1** [comment]
He lied

**Comment by sprunk** [comment]
All epicmenu settings of the widget are set to disabled so that would point to a bug in epicmenu.

**Comment by sprunk** [comment]
d2e83bd769152dac4d3f56dc636e91d97b97b3dc
