### ISSUE TITLE
Default GUI: cannot tell self units from allies

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1951]
http://i.imgur.com/Bk0fs7L.jpg

Only 3 units here are mine..

**Comment by GoogleFrog** [comment]
Why are they all the same colour?

**Comment by Licho1** [comment]
They aren't default colors suck. Default is non-simplified colors and some in our scheme are just too similar.

**Comment by Licho1** [comment]
I would suggest (blasphemy!) switching self color to green.

**Comment by sprunk** [comment]
SC2 simplecolors have green self and humans are more sensitive to green, I like the idea.

**Comment by GoogleFrog** [comment]
I like the idea of self green too. Implementing.
