### ISSUE TITLE
DefaultGUI: erasa map drawings not bound

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1954]

**Comment by GoogleFrog** [comment]
I don't think this key needs to be bound by default. However, suggest a good default.

**Comment by Licho1** [comment]
You don't think?? What??  Go play some 10v10 game, it's crazy. I think deleting could be obscure like shift +~ 
Oh also for germans the ~ binding does not work, they don't have it on keyboard or something.

**Comment by GoogleFrog** [comment]
Map drawing is bound to ~ as well as something less convenient which is on every keyboard.

**Comment by GoogleFrog** [comment]
Bindings are 
				"Any+\\",
				"Any+`",
				"Any+0xa7",
				"Any+^",
