### ISSUE TITLE
Measurements about rejected connections

### ISSUE THREAD

**Issue by quantumv** [ZeroK-RTS/Zero-K#1955]
It would be useful to see data on connections rejected by the banlist, per day, broken down by IP and rule. This way we can rule out the banlist as the place where we are losing new players.

**Comment by Anarchid** [comment]
It might make sense, at this point, to reset the bans anyway. The people whom they were meant to deter are already either deterred (and the bans no longer relevant), or have no issues circumventing the bans.

**Comment by Licho1** [comment]
Yeah we should reset.

**Comment by sprunk** [comment]
Belongs to infra https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1724
