### ISSUE TITLE
Minimap massively broken@!#

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1958]
1) Enable left button to select stuff on minimap
2) order some unit something
3) select that unit using minimap (works)
4) give it order using space + minimap click -> fails
5) give it order using right click on minimap -> fails

--> RAGEQUIT!@#!

**Comment by GoogleFrog** [comment]
Works for me. Impart lua config.

**Comment by Licho1** [comment]
Caused by gesture menu + crash in queue insert. Close at will since it's related to non-defaults.

**Comment by GoogleFrog** [comment]
The crash is queue insert is still worrying though.
