### ISSUE TITLE
Game spams "X wins" at the end of the game

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K#1959]
See the ending of http://zero-k.info/Battles/Detail/447342, with "West wins" spam (not sure if the entirety of the spam got uploaded)

**Comment by KingRaptor** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/game_over.lua#L166

`gameover` is set to true when gadget:GameOver() is called. Is that breaking somehow? 
Maybe we ought to just remove the debug message.

**Comment by KingRaptor** [comment]
It seems that neither `gadget:GameOver()` nor `widget:GameOver()` are called when running ZK develop version on 103.0.1-648-g5775975. Engine issue?

**Comment by sprunk** [comment]
No longer happens, only a single message is sent (judging from various infologs from in https://github.com/ZeroK-RTS/CrashReports/issues).
