### ISSUE TITLE
Metal bar flashes red when full

### ISSUE THREAD

**Issue by quantumv** [ZeroK-RTS/Zero-K#1960]
At GDS, players were very confused by this. They think you're out of metal when it flashes red.

Possible solutions:
 * Don't make the metal bar flash when full
 * Make the metal bar flash white when full

**Comment by db81** [comment]
Or make the right edge flash instead of the whole bar.

**Comment by Licho1** [comment]
3 year old tester also got confused by this, he understood though that metal is full and he thought that something would explode and wanted to remove mines.
