### ISSUE TITLE
Game start countdown foils newbies

### ISSUE THREAD

**Issue by quantumv** [ZeroK-RTS/Zero-K#1961]
At GDS a player was unable to start the game because he placed the startpoint, waited, saw that the game didn't start, then tried placing another point, which reset the countdown, then tried over and over again.

Possible solutions:
 * Don't reset the countdown when a startpoint is placed
 * Allow the countdown to be reset no more than X times
 * Use a fixed countdown starting from the moment everyone has loaded

**Comment by sprunk** [comment]
I thought the third option has been in use since ever and never changed?

**Comment by Anarchid** [comment]
In SP, there may be no need for countdown at all. Place marker -> commander spawns.

**Comment by GoogleFrog** [comment]
Cannot reproduce. It seems like solution 1) is already in place.

**Comment by GoogleFrog** [comment]
"At GDS" so I assume it's old.

**Comment by Licho1** [comment]
There might be some slight confusion atm due to game "doing nothing" but indeed timer is not reset, so all is fine.
