### ISSUE TITLE
repair does not work when having reserve metal bar

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#1962]
caretakers won't repair when metal reserve is set. They only repair when you set those caretakers to high prio.
example: http://zero-k.info/Battles/Detail/447365

airplane repair near 20 min (or minute 29) or near ecopad they just stop to repair until I set high prio for caretakers. When you need more replays, please tell me

not sure if it has to do with reserve metal bar. I always use it. But it is a bug... :=)

**Comment by DeinFreund** [comment]
So you're still having plenty energy but metal is less than minimum reserve and they stop doing anything?

**Comment by Jamanno** [comment]
Yes.

**Comment by let4be** [comment]
Stumbled on this issue couple of weeks ago
Solved by putting my caretakers on high prio

**Comment by Jamanno** [comment]
putting caretakers on high prio is given as solution in the bug report.
Putting caretakers on high priority does not handle the situation well. The caretakers would build other things after the repair with high prio which is not wanted.

**Comment by let4be** [comment]
It was a workaround :D

**Comment by Jamanno** [comment]
near end, caretakers do not repair grizzly on middle island

http://zero-k.info/Battles/Detail/447740

**Comment by let4be** [comment]
gg, who's gonna fix it now? :D
