### ISSUE TITLE
Steam: Game won't open

### ISSUE THREAD

**Issue by danjreyes** [ZeroK-RTS/Zero-K#1963]
I can't get the game to open anymore on Steam. Here is the error I get in the Steam console.

```
Game update: AppID 334920 "Zero-K", ProcID 8476, IP 0.0.0.0:0
>>> Adding process 8476 for game ID 334920
Game removed: AppID 334920 "Zero-K", ProcID 8476 
No cached sticky mapping in ActivateActionSet.
```

This happened after I ran the game on Steam and couldn't get it to stop running (it stopped running from what I could see but Steam showed it as still running). I had to kill Steam from the Task Manager and restart Windows. After I did that I wasn't able to run the game again.

**Comment by Licho1** [comment]
Fixed

**Comment by Licho1** [comment]
(Start game verify to force updatE)

**Comment by danjreyes** [comment]
The update worked. I can start the game now. Thanks.
