### ISSUE TITLE
Units can be moving in place

### ISSUE THREAD

**Issue by MLanghof** [ZeroK-RTS/Zero-K#1965]
I just encountered this situation:
http://i.imgur.com/au7ha6h.jpg

The bandit was "stuck" moving into the mex wreck, rapidly bopping back and forth (well, not "stuck" stuck, just not making progress). A Zeus + Warrior + Rocko (CAI, presumably on fight) did not manage to kill it for over a minute because the predicted bandit movement didn't align with its actual (non-)movement.

**Comment by sprunk** [comment]
micro oppa micro skillz!

**Comment by sprunk** [comment]
There's been a ton of pathing changes during those 7 years, and in particular newest engine deals with pathing, so assuming this is no longer relevant.
