### ISSUE TITLE
Water 4 shore waves are tiny on some maps

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1971]
Switch default water to 4 + shorelines.
Why are shorelines missing?

That is about the only water that looks like a water from top down view.

**Comment by sprunk** [comment]
Perhaps base it on user settings?

0 on lowest
4 on low, medium, high(, highest?)
3 on highest? IMO water 3 looks better than 4 at low angles (subjective) but also it's a bit clearer so it's easier to see underwater units

Also, AFAIK the waves at shores are an integral part of water 4 so lack could probably point to some rendering bug

**Comment by Anarchid** [comment]
Water 3 does weird wrong reflections and doesn't understand spawned wakes. IMO, water 0 for lowest and 4 for everyone else.

**Comment by GoogleFrog** [comment]
As far as I can tell water 4 is the default.

**Comment by Licho1** [comment]
I will try to reinstall steam, but im running clean steam copy already. 
Shorelines are missing for sure though, original jK water used to look good and be pretty cheap.

**Comment by quantumv** [comment]
I also had an ugly default water in my clean steam copy. Typing /water 4 fixed it.

**Comment by Anarchid** [comment]
ZKL used to deploy standard sets of springsettings which all had water `4` except minimal. Apparently chobby wrapper fails at this task and uses spring defaults, which is water `1` (basic reflective).

@quantumv @Licho1 is this the case? Does the water you see have reflections?

**Comment by Anarchid** [comment]
I assume this is closed by https://github.com/ZeroK-RTS/Chobby/commit/4cb9bbe69935d838c71996e9e22bd02bdea1fae8

**Comment by Licho1** [comment]
Also add shorelines, its missing waves

**Comment by GoogleFrog** [comment]
It's not missing waves for me.

**Comment by Licho1** [comment]
I see them now appear very small/subtle but there is a thin white line. I remember them being much bigger/more visible. Perhaps its my memory fault or config change.

**Comment by GoogleFrog** [comment]
It's probably a mapside config. I know there are maps that have no shore waves for stylistic reasons.

**Comment by The-Yak** [comment]
Shorewaves can be turned on/off by maps with 		shoreWaves = true,

I'm not aware of any setting to change the size of them.

**Comment by sprunk** [comment]
As far as I can tell [the only thing that controls shore wave size is the heightmap](https://github.com/spring/spring/blob/develop/cont/base/springcontent/shaders/GLSL/bumpWaterFS.glsl#L186) so it's out of our control.

**Comment by Anarchid** [comment]
IIRC there's also a foam texture that is used for shore waves in water 4. Changing that may affect the visible size of shore waves, perhaps.

**Comment by sprunk** [comment]
Caustics is the "sun diffraction shining through low depth water" effect.

Like this https://ak8.picdn.net/shutterstock/videos/8009038/thumb/1.jpg
