### ISSUE TITLE
Crabe moves on its own

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1972]
Crabe moves on its own and does not move when ordered to move.

http://zero-k.info/Battles/Detail/447591?ShowWinners=True

**Comment by let4be** [comment]
Crabe was placed on terra spike - if you watch replay it constantly makes mini movements(like jittering) and does not properly move when ordered to(appears to be stucked on place)

**Comment by let4be** [comment]
maybe be related: https://github.com/ZeroK-RTS/Zero-K/issues/1965

**Comment by GoogleFrog** [comment]
Not related.

**Comment by sprunk** [comment]
Ancient engine (104-648). Also Crab has recently had some changes to make jittering not uncurl it (which should solve the main frustration): b3ada76905687861fdd06d69036f9aeb11069b75
