### ISSUE TITLE
Unit ranks appear broken

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#1973]
Do units not tech up anymore?

Also with rank it should give some minimal effect, like regen.

**Comment by let4be** [comment]
I do not see unit ranks anymore on such units as Big Bertha and ICBM...
It was very nice, motivating and useful feature instantly seeing how useful your nuke strike was, like nuke getting a star after 1st hit

**Comment by GoogleFrog** [comment]
I see unit ranks. They don't give any bonus and should not do so.

**Comment by let4be** [comment]
Have you checked such units as big bertha and nuke?
For some reason I never see unit ranks on them

**Comment by GoogleFrog** [comment]
Some of the events that cause a rank redraw are not triggered. See https://github.com/ZeroK-RTS/Zero-K/issues/1973
