### ISSUE TITLE
Feature request: F5 should NOT hide labels on map

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#1974]
I wanted to make a video without interface but with map labels... turned out to be impossible as F5 hides both interface and labels
We either need to preserve labels or add a separate hiding mode where interface IS hidden but labels are NOT

**Comment by sprunk** [comment]
F5 interface hide is an engine feature.

**Comment by sprunk** [comment]
I don't think this is going to happen, at least not ZK-side.

**Comment by sprunk** [comment]
As a workaround, if you want to get rid of the interface while keeping specific elements you can manually disable relevant widgets.
