### ISSUE TITLE
Sometimes com morph breaks the animation of commander

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#1976]
When commorph is finished the animation appears to be broken and commander moves like a static model
I've seen this recently but can't find replay right now, will update this if see again
Does anybody have a replay with this bug?

**Comment by sprunk** [comment]
Haven't seen this recently. This ticket is 7 years old so perhaps it was fixed in the meantime.

**Comment by GoogleFrog** [comment]
I would not be surprised if this was still an issue.

**Comment by sprunk** [comment]
If it gets reproduced then we reopen, sure. Right now the ticket is essentially unactionable unless somebody goes and spends time chasing ghosts that may not actually exists. I wanted to say "the replay is 7 years old" but the OP doesn't even have a replay.
