### ISSUE TITLE
Use TAB for big playerlist instead of map overview

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1979]
Any other ideas/objections? @dvr333 ?

**Comment by sprunk** [comment]
Perhaps make a poll asking whether people use the overview camera currently. As far as I can tell it is liked by people with extremely low APM (mostly bots players) so if it has its merits it could get relegated to another hotkey.

**Comment by Licho1** [comment]
lets bind it to M

**Comment by sprunk** [comment]
Would need to unbind Move command (Move hotkey is mostly useless but it's there for consistency, all basic commands have a hotkey).

**Comment by GoogleFrog** [comment]
Move needs a hotkey for those cases where right click would give a different command (in clumps of units). Tab for map overview is actually dangerous because pressing it can appear to break the camera.

**Comment by sprunk** [comment]
So probably it's best to remove the hotkey altogether (because regardless of which specific key it is, pressing it "breaks" camera).

**Comment by dvr333** [comment]
I mean, this is partly why I set up COFC to be able to zoom out into overview mode while still having the camera tilt when zoomed in. I realize COFC isn't and likely won't be default, but I think something similar was widgetized for the TA camera.

**Comment by GoogleFrog** [comment]
Looks like the chili share PR implemented this ticket in a broken way. I fixed it. Now tab brings up a playerlist.

**Comment by Licho1** [comment]
Yeah move needs a hotkey .. 
There has to be some free though.. alternatively we could make TAB for map and F1 or simialr key for playerlist.

**Comment by quantumv** [comment]
If I were looking for a player list, I'd try tab first.

I agree that map view is dangerous. Players can get stuck in it if they press the button accidentally. If it stays, it needs a big "X" button.

**Comment by GoogleFrog** [comment]
Is done.
