### ISSUE TITLE
Krow dgun keeps firing when stunned

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#1981]
http://zero-k.info/Battles/Detail/447735

Krow killed a scorpion after it was stunned.

**Comment by GoogleFrog** [comment]
There is a bit of a lack of consistency with burst and disarm/stun. Spring bursts don't care about disarm. They are interrupted by being stunned but resume after the stun wears off. Thunderbird has its burst interrupted and resumed by both disarm and stun. Krow seems to be immune to both.

**Comment by GoogleFrog** [comment]
Fixed Krow. Made a new ticket for other inconsistencies.
