### ISSUE TITLE
UI for building a structure and raised ground below it

### ISSUE THREAD

**Issue by nubtron** [ZeroK-RTS/Zero-K#1986]
How can we make the feature obvious for players? I couldn't figure out how to do it, nor could Licho.

**Comment by sprunk** [comment]
I don't think lack of knowledge about the feature is going to affect newbies much so it's probably fine if it only gets explained by some advanced tutorial.

**Comment by Licho1** [comment]
I had watched video and did it once, but then i forgot and i spent about 1 minute ingame trying to do it again and failed. Make it back on hold left click, that was easy to remember and explain.

**Comment by quantumv** [comment]
Sprunk, Terraforming is our top feature in marketing materials. We should make it easy for them to redo what the see in screenshots and trailers.

**Comment by sprunk** [comment]
>Terraforming is our top feature in marketing materials

Then change marketing materials. Terraform is not used much in actual games.

**Comment by Licho1** [comment]
Marketing isn't about what's of any use at winning game.
It's about what people percieve as fun and want to try. Very few things impress people, but terraforming did!

**Comment by sprunk** [comment]
Subset of #1986
