### ISSUE TITLE
Tab playerlist has many issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1989]
* Whitespace sucks.
 * Padding is bad.

**Comment by GoogleFrog** [comment]
I removed the outlines so padding is probably ok now.

**Comment by DeinFreund** [comment]
Is this still relevant? I'm keeping track of the forum thread for a future update, but I haven't seen any breaking issues.

**Comment by Licho1** [comment]
I thin k issues from this are ok.
