### ISSUE TITLE
Received one free extra commander.

### ISSUE THREAD

**Issue by quantumv** [ZeroK-RTS/Zero-K#1994]
The game froze while loading [(log)](https://github.com/ZeroK-RTS/CrashReports/issues/199). After rejoining, I had two commanders, at exactly the same point. 
I was playing a 3v3, 3 humans vs 3 ais.
[Server Replay](http://zero-k.info/Battles/Detail/447868)
[My Replay](https://github.com/ZeroK-RTS/Zero-K/files/801601/20170225_231110_Supreme.Battlefield_103.0.1-648-g5775975.develop.sdfz.zip)

**Comment by Licho1** [comment]
It was launch game -> 2 players loaded but 1 crashed during load (actualled freezed)
upon reconnecting, player who freezed got 2 commanders instead of 1.

**Comment by let4be** [comment]
Saw this couple of times in a regular team game, something lag/afk related

**Comment by sprunk** [comment]
Duplicate of #2058
