### ISSUE TITLE
Bugged pencil cursor

### ISSUE THREAD

**Issue by quantumv** [ZeroK-RTS/Zero-K#1997]
When I hold the map drawing key, a white box is shown in place of the pencil cursor.
The white box is also shown in the legend.

It doesn't actually happen all the time. In some matches it works fine.

**Comment by sprunk** [comment]
260403ded6a1657dbfefe7553188ac3f7e37bbb5

The pencil is now an actual cursor (as opposed to just a manually drawn sprite) which should solve the issue. Waiting with the close until the rewritten widget is enabled as the default.

**Comment by sprunk** [comment]
e949ad9bc36bf1c738db3aa4d4c49c1a00f2b821
