### ISSUE TITLE
Building not started after terraforming

### ISSUE THREAD

**Issue by T-Lama** [ZeroK-RTS/Zero-K#1998]
Sometimes con will not make building when using "hold to terraform", it just terraforms. GF said this was fixed, yet it seems it was not.
Here is replay, where my Welder has been ordered to build terraformed Gauss(north edge of the map, in mid), yet made only the terra and had to be ordered to build again. (at cca 20. min)

[http://zero-k.info/Battles/Detail/447615](url)

**Comment by Licho1** [comment]
Yeah, especially if you do ctrl + shift boxes it fails a lot.

**Comment by T-Lama** [comment]
Ooooh, I think I got it! The building will not be started if you start terraform at place, where the building cannot be place WITHOUT terraforming (ie, the the layout is marked yellow/red). Now that is stupid, seriously.

**Comment by sprunk** [comment]
5eb231dff4c3e5787f935e50d593edb1f2151547

**Comment by GoogleFrog** [comment]
Does not work for me. Alt+MMB works but alt click on integral menu and hold LMB to select height do not.
