### ISSUE TITLE
Wait or win placement is wrong

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2001]
I recall looking at this widget with the reskin. However, the "Win" button is not properly aligned with the text.

**Comment by KingRaptor** [comment]
Doesn't look obviously wrong to me: http://i.imgur.com/uKeRKlm.png

**Comment by GoogleFrog** [comment]
The issue only occurs when the widget is enabled normally. Hacking it enabled in the naive way does not reproduce the issue.
