### ISSUE TITLE
New player list eco data completely wrong

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2004]
1) shows incorrect spending/income data (must match other elements, like spectator eco data or ingame bars)
2) metal and energy bar are in wrong order. Since we use metal left, energy right, natural "verticalization" is metal on top, energy below.
3) metal bar should be blue and not gray

**Comment by DeinFreund** [comment]
1. now uses eco panel data
2. swapped
3. now blue

**Comment by KingRaptor** [comment]
Closable?

**Comment by DeinFreund** [comment]
I consider this fixed. Otherwise please update.
