### ISSUE TITLE
Endgame charts show wrong AI names

### ISSUE THREAD

**Issue by nubtron** [ZeroK-RTS/Zero-K#2007]
This was a 3v3, 3 bots vs 3 players. The three bots names are incorrectly shown as "Licho".
![iph4dbj](https://cloud.githubusercontent.com/assets/49084/23439902/36f6530c-fe19-11e6-92f2-0f5dff3102f7.jpg)

**Comment by sprunk** [comment]
Works for me locally (for both Lua and Skirmish AI's), possibly the lobby transmits the name incorrectly?
