### ISSUE TITLE
Many broken things in this screenshot of tab playerlist

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2008]
![screen00383](https://cloud.githubusercontent.com/assets/1318249/23465097/45d6e224-feeb-11e6-92de-36b76248e5eb.png)

**Comment by sprunk** [comment]
"Ramp spam"

**Comment by DeinFreund** [comment]
Looks like an outdated version. Reproduce or post replay link please.

**Comment by sprunk** [comment]
Closing as outdated (reopen if reproduced).

**Comment by DeinFreund** [comment]
I should probably give bots better avatars. I do like how clogger looks different on every spring install though.
