### ISSUE TITLE
Playerlist player multiplication

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2010]
Screenshots are failing, but upon connecting to MM game, KingStad who was spec also appeared as player on team 1

**Comment by DeinFreund** [comment]
Indeed, 
Spring.GetTeamList(allyteam) returns him as one of the players in that team. should I cache the result of who is in which allyteam at the beginning of game and reject any people that might "join" the allyteam during the game. Or not show resigned players?

**Comment by Licho1** [comment]
I think its wrong usage of existing functions. I remember there were several and it was possible to get accurate data just not very logical.

**Comment by DeinFreund** [comment]
I think I'm now doing the same as deluxeplayerlist, so it should work. But some testing would of course help.

**Comment by GoogleFrog** [comment]
Specs have an allyTeam and a team. You just need to filter them out of the lists.

**Comment by DeinFreund** [comment]
They are being filtered out now
