### ISSUE TITLE
General settings not remembered

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2018]
1) join running game as spec
2) disable crude player list
3) move chat to above minimap
4) quit
5) join different game -> none remembered

**Comment by GoogleFrog** [comment]
Intended, most player UI screenshots I've seen in past years have gaps on the edges from when Spring decided to start windowed once. Now all default panels have their locations set on load and the required default widgets are enabled.

To remember placement and activation of default widgets you need to select the HUD preset 'none'.

**Comment by Licho1** [comment]
Fixed by changing preset
