### ISSUE TITLE
Rename Trainer Commanders to their chassis type

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2019]
What was: static commanders, locked modules, predefined commanders with some still-locked modules equipped, called "trainers".

What is: dynamic commanders, no module locks (at least they haven't returned yet), any predefined commander is basically just a chassis with defaults. Still called trainers.

What should be:  dynamic commanders with available modules (all or some locked, but a minimal conf should be available) preselected, named simply "Recon Commander" etc.

**Comment by GoogleFrog** [comment]
The intention of the Trainers was to shame people into writing their own commander names on the site.

**Comment by Anarchid** [comment]
Wasn't it originally that people wouldn't quit game because of being stranded with a peashooter?

**Comment by Licho1** [comment]
Imo its ok.. people will at least ask how to do it and visit site. Site is now very disconnected from the game and it used to be the central hub of social activity. Having an incentive to go there is good imo.

**Comment by GoogleFrog** [comment]
I think this has merit, it would make the names less silly if they were just called "Strike Commander" instead of "Strike Trainer".

**Comment by KingRaptor** [comment]
Renaming "trainer" to "commander" could cause ambiguity with the trainer comm configs versus the chassis types. Is this deemed acceptable, or do we want something like "Strike Starter" instead?
(having trouble thinking of better names)

**Comment by Anarchid** [comment]
Strike Default would also work.

**Comment by CrazyEddieTK** [comment]
"Standard Strike Commander"

Gives the players some confidence that they're playing with a reasonable commander and aren't being penalized with a weak unit for being noobs, unlike "Trainer". But also gives them an invitation and incentive to learn about custom commanders, and encourages them to create their own loadouts.

**Comment by sprunk** [comment]
How about just "Strike"?

**Comment by GoogleFrog** [comment]
> "Standard Strike Commander"
Too long.

I like just "Strike" because it sounds generic without sounding like a handicap.

**Comment by Anarchid** [comment]
I'm tempted to suggest Support and Battle to make a comeback now that we have gotten rid of the reason behind Guardian and Engineer (which was eviction of the `armcom` model).

**Comment by CrazyEddieTK** [comment]
Need to fix these as well:

![image](https://cloud.githubusercontent.com/assets/7810334/26604126/52f9d3f0-4557-11e7-8302-75347521f02a.png)

I suggest:
 - Change the "TRAINER" unitpic stamp to "STANDARD COMMANDER"
 - Move the stamp from on top of the unitpic to the upper-right corner of the frame
 - Change the checkbox text to say "Show Only Your Customized Commanders" (and invert the checkbox logic).

Also, the name text ("Guardian", "Recon", etc) should be centered under the unitpic.

**Comment by CrazyEddieTK** [comment]
Also, the checkbox should have a tooltip reading "Log into the Zero-K.info website and select 'Home -> Commanders' to customize your commanders."

This would help new users discover the custom coms feature and how to access and use it.

**Comment by GoogleFrog** [comment]
I think the Trainer text is fine there.

**Comment by KingRaptor** [comment]
My ideal state involves moving comm config entirely offline (a Chobby UI is already partly implemented). The "trainers" can then just be predefined comms which the user can edit or delete.
