### ISSUE TITLE
Recloak seems to ruin Overwhelming Superiority 

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2021]
Overwhelming superiority sets cloaked units to be visible despite their cloak to the superior overwhelmer. However, decloaking and recloaking erases this inconvenience for the losing team.

The last 30 minutes of this [game](http://zero-k.info/Battles/Detail/448356) is MisterCasanova running from an afk Kingstad's DRP with his cloak commander and building things which then get shot the moment he leaves them.

It also looks like his radar jammer prevents those new things from being fired at. Perhaps overwhelming superiority doesn't mark those newly created units permavisible, or has failed in some other way.

**Comment by sprunk** [comment]
If recloak overrides AlwaysVisible I think that's an engine bug.

**Comment by ashdnazg** [comment]
A guess: com morphed after overwhelming and new units doesn't handle new units

**Comment by sprunk** [comment]
New units are supposed to be revealed: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/game_over.lua#L452

**Comment by ashdnazg** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/game_over.lua#L190
will fail in FFA as you may reveal several alliances.
Keep a table.

**Comment by sprunk** [comment]
That is by design ( see #676 ).

**Comment by ashdnazg** [comment]
the logic there probably failed somehow

**Comment by GoogleFrog** [comment]
Does not seem particularly important now that AIs resign.

**Comment by Anarchid** [comment]
At least the original game involved zero AI players, and was a FFA.

**Comment by sprunk** [comment]
FFA does not have Power Overwhelming at all (by design, see #676) so apparently there was never a bug. Reopen if reproduced in 1v1 or teams.
