### ISSUE TITLE
Krow (corcrw) has dgun labeled as FakeWeapon

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#2023]
corcrw_specialtrigger marked as FakeWeapon, thus ignored by CircuitAI.
But in practice corcrw_clusterbomb's reloadFrame is always 0, while corcrw_specialtrigger's is different after shooting and shows real value.
Was wrong weapon marked as fake? If no then how to identify real weapon?

**Comment by GoogleFrog** [comment]
Weapons are marked as fake with the purpose of keeping them hidden from various automatically generated manuals. If you want a weaponDefID I am not sure how you are going to get it.

**Comment by rlcevg** [comment]
As i understood [fake weapons](https://github.com/ZeroK-RTS/Zero-K/blob/55941370d36cb554967ede38b96f19b562381acb/gamedata/weapondefs_post.lua#L239) used as triggers for fight/attack behaviour (like bombers - dive). But krow's fake weapon (specialtrigger) has actual reloadStatus, and krow's non fake weapon (clusterbomb) doesn't have it, that is a bug.

**Comment by GoogleFrog** [comment]
You are inferring a purpose to the fake weapon tag that does not exist. Fake weapons can be used for absolutely anything (targeting, reload, leashing, LUS stuff etc..) and the tag/naming exists only to hide the weapon from unit guides and projectile lights. I spaced clicked on Krow and saw reasonable weapon descriptions so there is no bug in anything concerning ZK lua.

Weapons were never marked fake for the benefit of AIs because I did not know this is how AIs were parsing weapons. You're going to have to say what you want for me to fix this because it's a new interface for me.

**Comment by rlcevg** [comment]
Space-click shows "correct" data only because they look the same as fake_weapon data. If i change reloadTime of clusterbomb to 5s - it shows 5s but reloads 30.
And then what's the purpose of the [fake_weapon](https://github.com/ZeroK-RTS/Zero-K/blob/55941370d36cb554967ede38b96f19b562381acb/gamedata/weapondefs_post.lua#L239) custom param if not using it in special (fake) conditions?
How can i determine which weapon can fire (if fake_weapon custom_param doesn't mean anything)?

I need to be able to calc DPS of a unit, determine which weapon is actual DGun to get stats of it like reloadStatus.
In the past (and i think it still works for everything except krow) i could just ignore fake_weapon and process any other weapons.

**Comment by rlcevg** [comment]
Well, this sucks: [fake_weapon used only to filter stuff from displaying](https://github.com/ZeroK-RTS/Zero-K/blob/55941370d36cb554967ede38b96f19b562381acb/LuaUI/Widgets/gui_contextmenu.lua#L1132). And [DGun is hardcoded to slot 3](https://github.com/ZeroK-RTS/Zero-K/blob/55941370d36cb554967ede38b96f19b562381acb/LuaUI/Widgets/gui_chili_selections_and_cursortip_old.lua#L839).
Apparantly that's the only way to query DGun state, through hardcoded slot 3?

**Comment by sprunk** [comment]
I'm fairly sure removing the fake weapon and putting clusterbombs at slot 3 would be safe.

**Comment by rlcevg** [comment]
Theoretically issue remains. As i understood GoogleFrog: fake_weapon doesn't mean anything, except that it won't be displayed in gui. Such weapon may have non-zero (or zero, see corcrw_specialtrigger) damage and shoot. So there's no way to know which slot/weapon should AI query to get its reloadStatus of casual weapons.
And DGun should be queried only at slot 3 (which is fine if slot number won't be changed frequently).

But practically issue found so far only in corcrw.

Also I tried to replace specialtrigger by clusterbomb - it won't dgun at all, so i assume that hacky workaround is needed (or i'm simply a noob at lua).

**Comment by sprunk** [comment]
I'll check it out.
