### ISSUE TITLE
Locate sprunk

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2026]
What is your email?
(For GA access).

**Comment by sprunk** [comment]
GA?

**Comment by Anarchid** [comment]
Game Analytics

**Comment by sprunk** [comment]
?

**Comment by Licho1** [comment]
You just fixed a widget that deals with GA data, I assume you would like to see where is it sent and what it does.. It's really up to you..

**Comment by sprunk** [comment]
Sure, could be interesting.

gnurps@o2.pl

**Comment by Licho1** [comment]
Ok check your spambox
