### ISSUE TITLE
SPRINGIE.USER message spam

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#2027]
Everytime while the game is running and someone joins this message is displayed in the chat. Please get rid of it, it is really annoying. Also I'm not 100% sure the bug report belongs here or to chobby since I don't know what actually causes it. My bet would be that it is made by the new playerlist though.

**Comment by DeinFreund** [comment]
This is already merged now. It's a feature for the playerlist that already exists on the server, but the game wasn't updated yet.
