### ISSUE TITLE
Mex nanoframe stacking

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#2032]
Almost guide that tells us how to spawn multi-windgen farm at a single spot (high slope required):
http://zero-k.info/Battles/Detail/448668
Engine allows to place nanoframes of windgens over each other at high-slope spot.

**Comment by sprunk** [comment]
Windgens on slope also clip into terrain and look generally out of place: 
![fugly](https://cloud.githubusercontent.com/assets/2573076/23593087/8ff60002-020a-11e7-9f8a-8fa9df0392f0.png)

**Comment by rlcevg** [comment]
It's not about windgens only, replay shows also mexes.

**Comment by sprunk** [comment]
Sane maps don't have mexes on cliffs and stacking two mexes on the same spot outside speedmetal won't increase income so I think mexes are a lesser issue.

**Comment by rlcevg** [comment]
```
./amgeo.lua:37:  maxSlope                      = 255,
./armwin.lua:45:  maxSlope                      = 255,
./cormex.lua:43:  maxSlope               = 255,
./geo.lua:49:  maxSlope                      = 255,
./thicket.lua:33:  maxSlope                      = 255,
./wolverine_mine.lua:45:  maxSlope               = 255,
./fakeunit.lua:30:  maxSlope                      = 255,
./terraunit.lua:39:  maxSlope               = 255,
./asteroid.lua:22:  maxSlope                      = 255,
```
I wonder if it's possible to terraform high-slope and then stack up geothermal powerplants.
Terraform, man terraform!

**Comment by sprunk** [comment]
Geo fixed ZK side - like wind, it has no business having unlimited slope and probably looks even sillier. The alternative was to make it levelGround but that causes free terraform.

I think mex can wait for engine side fix for the reasons above.

**Comment by Topkack** [comment]
Dirtbag trolling galore!

**Comment by sprunk** [comment]
Might be related #3178

**Comment by DeinFreund** [comment]
This still happens
![supershield](https://i.imgur.com/mtaW6QB.png)

**Comment by GoogleFrog** [comment]
What is this?

**Comment by DeinFreund** [comment]
A few dozen Shields in the same spot. The constructors would never stop building and just put down more and more Shields.

**Comment by sprunk** [comment]
https://zero-k.info/Battles/Detail/748260

**Comment by sprunk** [comment]
The parts of spring/spring#516 that aren't in spring/spring#518 were the fix, apparently.

**Comment by GoogleFrog** [comment]
Yes, they were.

**Comment by sprunk** [comment]
Apparently windgens can stack again. f1b970ac14e9f60686c3986cad59771bf4ed3293 increased windgen slope tolerance but it was a long ago so it may require a very specific spot.

**Comment by sprunk** [comment]
beyond-all-reason/spring@0c7cd7080f7ea68f398f4f640001a1934135d880

**Comment by sprunk** [comment]
Maybe the above doesn't entirely fix it but the new ticket is /beyond-all-reason/spring#529
