### ISSUE TITLE
Massive lag spikes when someone resigns/goes afk and when game ends

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2038]
Consider watching this replay http://zero-k.info/Battles/Detail/448687
focusing your attention on mentioned conditions(resign/afk/game end) - for me it produces almost intolerable lag spikes, 
sometimes the whole game window freezes and it feels very jitterish when it does not

**Comment by GoogleFrog** [comment]
Run the widget profiler widget and watch what happens.

**Comment by GoogleFrog** [comment]
Who are you?

**Comment by GoogleFrog** [comment]
You should run widget profiler with the replay.

**Comment by lhog** [comment]
Is @let4be == Firepluk?

**Comment by let4be** [comment]
how do I run it?

**Comment by DeinFreund** [comment]
Still feels like #1796

**Comment by let4be** [comment]
Agree, #1796 doesn't seem to be fixed
anyone else experiencing the same issue?

**Comment by GoogleFrog** [comment]
Chili Share spikes in usage up by 2-3% whenever a spectator joins or a player resigns. In short, it is just as bad as the other playerlist widgets. Write a widget which doesn't delete everything and regenerate itself whenever an update is required. (Also remove almost all the global variables).

I hacked a fix onto the widget by making it only update when you want to look at it in https://github.com/ZeroK-RTS/Zero-K/commit/6deb0f7c9a88158334edb8e37a0188b462af4287. The bug should be gone provided you never press Tab. This version is live but "Sunday Lobster Pot" is still running the old version so most recent games would have still had the issue.

**Comment by DeinFreund** [comment]
So how did you measure the performance?

**Comment by GoogleFrog** [comment]
By running the widget profiler widget.

**Comment by let4be** [comment]
Gonna verify on the first massive game =)

**Comment by let4be** [comment]
so we've had some huge games in the past few days and I no longer see this issue at full scale
Though game end still lagging for me

Is there any particular reason we explode all enemy structures on game over? it could be hurting performance + I always find myself in a situation where I would like to have a quick glimpse at enemy structures before quitting the game

**Comment by sprunk** [comment]
>game end still lagging for me
>Is there any particular reason we explode all enemy structures on game over? (...)

#1648 

>so we've had some huge games in the past few days and I no longer see this issue at full scale

Good.
