### ISSUE TITLE
All units out of sudden became green

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2039]
How do I return everything to the previous color I used to have for years?...

**Comment by GoogleFrog** [comment]
Studies have shown that green is best

Create the file Spring/LuaUI/Configs/LocalColors.lua and fill it with: https://github.com/ZeroK-RTS/Zero-K/blob/83af046123d61ddd764600696456f7d3b8531554/LuaUI/Configs/ZKTeamColors.lua

**Comment by let4be** [comment]
Did exactly this - no change...

**Comment by let4be** [comment]
Oh I just failed with putting it into `config` instead of `configs`
Thanks! saved the say =)
