### ISSUE TITLE
CSound::GetSoundId: could not find sound: IncomingChat

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K#204]
missing sound id:

[f=0000000] [Sound] Warning: Sound incomingchat is missing file tag (ignoring)
[f=0000000] [Sound]  parsed 350 sounds from gamedata/sounds.lua
[f=0000000] [Sound] Error: Unable to open audio file: IncomingChat
[f=0000000] [Sound] Error: CSound::GetSoundId: could not find sound: IncomingChat

**Comment by sprunk** [comment]
Closable: silence is the correct behaviour.
