### ISSUE TITLE
Consider a cooldown on AFK giveaways, in case someone oscillates around AFK threshold

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2043]
Really frustrating experience, seeing ally constantly blink, going to afk/back from afk all happening within the short time frame...
http://zero-k.info/Battles/Detail/448868

Watch for AMPERSAND in the mid game
I guess his CPU hasn't been able to keep up with game sim anymore

Solution? afk/from afk possible max frequency should be reduced, like no more than 1 switch per minute

**Comment by sprunk** [comment]
Blinking: #1080
