### ISSUE TITLE
Hovers are able to climb hills on titan dual

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2044]
That is wrong.

**Comment by sprunk** [comment]
I don't think anything changed ZK side so probably engine.

**Comment by DeinFreund** [comment]
What hills? Vehicles could always go up on the corner hills.

**Comment by GoogleFrog** [comment]
Screenshot required. Hovers can path as much as vehicles, some of the ramps are quite shallow.

**Comment by Licho1** [comment]
Vehicles are meant to get there? How so.. it's pretty steep...

**Comment by DeinFreund** [comment]
Keep in mind even Wanderlust has many vehicle pathable ramps.

**Comment by sprunk** [comment]
Is there anything to be done here ZK-side? If TitanDuel hills give wrong pathing impression then I think it's a problem with TitanDuel texture.
