### ISSUE TITLE
Rocket passes through shield

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2049]
Look at this game http://zero-k.info/Battles/Detail/449175 at 1300, 4300 5:27.

**Comment by GoogleFrog** [comment]
Occurs at 1500 4300 7:14. Can be reproduced without luarules:
 * Get to the start of the game.
 * Pause
 * /skip 714.
 * /cheat
 * /luarules disable
 * Unpause.

https://zero-k.info/Battles/Detail/462808

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5656

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/f873597476f793bb1ef686301ebb22f4efb61dd1
