### ISSUE TITLE
Map Edge Extension is a major performance sink

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2055]
Regarding profiling results it consumes up to 50% of all resources(widget profiler) which causes 2x FPS drop
On machines with weaker GPUs or on super massive batles it may cause FPS drop down to 12-15 while when disabled FPS is comfortably holding above 30
I can reproduce it on 2 different PCs

kill or fix

**Comment by GoogleFrog** [comment]
What settings do you have for the widget?

**Comment by let4be** [comment]
If you mean the game settings itself(springsettings.cfg) I checked on ultra-preset(chobby, notebook with intel hd 620) and on everything-super-minimal(custom made conf) running on a PC with potato nvidia GPU

**Comment by GoogleFrog** [comment]
I mean the settings as shown below:

![screen00402](https://cloud.githubusercontent.com/assets/1318249/23791233/52e01cf0-05d6-11e7-9cff-985dfb893efc.jpg)
![screen00404](https://cloud.githubusercontent.com/assets/1318249/23791234/53cdac5e-05d6-11e7-9c3a-eb99cc14695b.jpg)

I have difficulty detecting the performance cost of edge extension. It looks like it is highly hardware dependent.

**Comment by let4be** [comment]
exterior effect: both grid and texture cause the same performance drop

**Comment by GoogleFrog** [comment]
Can you make screenshots similar to mine?

**Comment by Licho1** [comment]
Hmm grid too? Scary..

**Comment by let4be** [comment]
Can we have this disabled by default at least?...

**Comment by Licho1** [comment]
You mean fixed? It should be fixed and not disabled. There is no reason it should be expensive.

**Comment by GoogleFrog** [comment]
See my comment, it is not uniformly expensive. @let4be would have to tinker with it to see which bits can be disabled for poor GPUs.

**Comment by sprunk** [comment]
I have discovered that this widget is written very poorly. It tries to draw things *even when disabled* which can sometimes result in reusing other widgets' textures (sometimes even preventing them from being drawn in their original place!), in this example an entry from the widget list - see above (0, 0):

![extension_fail](https://user-images.githubusercontent.com/2573076/28374244-7cded1ba-6ca4-11e7-942f-eead4e4b9114.png)

**Comment by GoogleFrog** [comment]
Even with more thorough testing, involving reloading instead of disabling, I can't detect a difference.

**Comment by The-Yak** [comment]
I gain 4-5fps with cutaway as opposed to map_edge_extension with any settings.

Nvidia Geforce 840m

**Comment by sprunk** [comment]
What's your usual FPS? There's a difference between going 200→205 and 25→30 even though both are "gain 5".

**Comment by The-Yak** [comment]
Fully zoomed out at around any map with cutaway gives me ~45fps

Enable grid and it will instantly drop to ~35fps
