### ISSUE TITLE
PlanetWars structures not appearing ingame

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2057]
Data sent by the server:
http://zero-k.info/Battles/Detail/449439?ShowWinners=True

**Comment by GoogleFrog** [comment]
Works for me when I copy the planetwars modoption into local testing. The issue seems map (startbox API) specific.

**Comment by GoogleFrog** [comment]
[f=-000001] [Game::LoadGame][5] globalQuit=0 forcedQuit=0
[f=-000001] Error: LuaRules::RunCallIn: error = 2, GamePreload, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_planetwars.lua"]:340: attempt to perform arithmetic on field 'right' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_planetwars.lua"]:340: in function 'GamePreload'
	[string "LuaRules/gadgets.lua"]:987: in function <[string "LuaRules/gadgets.lua"]:985>
	(tail call): ?
[f=-000001] [LoadFinalize] finalizing PFS
