### ISSUE TITLE
extra com for afk-late-rejoiner

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#2058]
http://zero-k.info/Battles/Detail/449453

4hundred was afk at game start. 
i get his trainer com. 
he joins later, catches up, chooses a custom com and get his custom com. 
then the trainer com is also given to him.

**Comment by DeinFreund** [comment]
> [21:59] X: when one is considered afk in the beginning but then arrives immediately after start
> [22:00] X: its my established tactic

is being actively used to win PW

**Comment by sprunk** [comment]
I left the ticket alive because I thought the fix broke comshare before gamestart, but it didn't because that feature never actually worked.
