### ISSUE TITLE
Make planetwars use startbox API properly

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2065]
Currently the planetwars structure spawner randomly attempts to spawn structures over the entire map and culls them if the structure is outside a start box. This could be improved by telling planetwars the shape of the boxes.

Also, planetwars is supposed to spawn structures in slightly dangerous areas. The structures should generally be outside your box so they can be targeted. On a standard East vs West setup the structures should be around 1/4 to 1/3 of the way down the map from the defending faction.

**Comment by mtroyka** [comment]
Use the suggested start positions (ally and enemy) and pick points from ally start positions at a random angle generally towards the enemy start positions.

**Comment by GoogleFrog** [comment]
Current implementation can fail to find a position within the number of tries so I'm upgrading this to a bug.

**Comment by GoogleFrog** [comment]
Idea for API usage:
 * Take the average of the suggested start position for each time. At least one such position should exist on every map if I recall correctly. This results in a single (x,z) coordinate for each time.
 * Use the two coordinates to define a line segment.

Use the line segment to define rectangles which are parallel to the line segment. Rectangles should start and end at certain distances along the line (0.15 to 0.35 for allied, 0.35 to 0.65 for neutral) and be extended sideways such that their corners stop short of some buffer around the edge of the map. Try to spawn structures inside these rectangles, possible starting off small and increasing in size. All this will just require a little linear algebra.

**Comment by GoogleFrog** [comment]
As discussed with @sprunk, the startbox API should be able to return rectangles.
 * Startbox API should have a function GetPlanetwarsStructureArea(allyTeamID) which returns the area in which planetwars structures for that allyTeamID can spawn.

Startbox API should read some sort of GameRulesParams to get the following values. Some decent values are in parenthesis. 
 * Neutral box width (0.3)
 * Team box nera (0.2)
 * Team box width (0.25)
 * Map edge padding (400)

The width of a box is its width as a proportion of the distance between start coordinates of each team. The neutral box is centered on 0.5 and the team box has its edge closest to the team that owns it defined by team box near. The rectangles should be extended to each side such two corners of the rectangle are at distance map edge padding from the edge (all four corners will have this distance if the team start coordinates are orthagonal).

If the GameRulesParams are not set (because planetwars has not yet initialized) then the API could try reading the values from GG.PlanetWars, although, ideally nothing would try to be read before planetwars initializes.

The startbox API rectangle function will be used to spawn structures and may be used to show where structures can be. I don't really mind how the rectangle is returned provided it can do those things in a straightforwards way.

**Comment by sprunk** [comment]
WIP implementation remarks, are those okay?

 * the startbox gadget receives the config (width, near etc) as arguments to its GG function (since it needs to be called by the PW gadget anyway)
 * the returned table has the following format:

```
{
    [allyteamID] = {
        {x = 12, z = 34},
        ...
    },
    ...
}
```

Allyteam IDs are 0 (attacker), 1 (defender) and gaia's allyteamid (neutral).
The tables inside currently contain four points - the corners of the rectangle. A point is a table with keys 'x' and 'z'.

 * the rectangles are actually parallelograms because I suck at linear algebra
![box-fail](https://cloud.githubusercontent.com/assets/2573076/24334049/783815b8-1263-11e7-8d3f-6f60707aa0f6.png)

**Comment by GoogleFrog** [comment]
That API looks good. I didn't know whether startboxes has local data. What you've done makes sense for when it has no localdata.

That picture isn't a parallelogram, it is a trapezoid. I wanted a rectangle because:
 * The edge of the map is often a boring place to put a structure and often the edges are covered in sea.
 * It is easier to uniformly sample a rectangle than a trapezoid. Easy things are less prone to bitrot.
 * I don't want the API to look too general. A set of four points leads to dangerous thoughts along the lines of "why not send two points for a triangle or many points for interesting areas?". I want to API to be structurally limited in the types of shapes it can send because I don't plan on dealing with general shapes. This is a safety against people trying to extend it partially, because it looks extensible, without understanding its implicit limitations.

A rectangle can be encoded as a coordinate and two vectors representing the adjacent edges. This would quite clearly state that only parallelograms are supported. If we support trapezoids then it is a simple code change to make the API send arbitrary quadrilaterals. However, I'm not going to implement sampling for arbitrary quadrilaterals.

All that I've said is pretty minor though and mostly solvable with good function names and commenting. There are three options:
 * Do nothing beyond function naming and commenting. It's probably fine and I'm just writing paragraphs for no reason.
 * Limit the API structure to reflect what is handled.
 * Implement support for arbitrary polygons. This involves giving startboxes API a function which takes  a polygon and returns a random point within the polygon.
