### ISSUE TITLE
Puppy can't reliably hit glaives

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2067]
Those peewees are pretty nimble now, giving puppies a hard time tracking their movements.

Examples in http://zero-k.info/Battles/Detail/449605

**Comment by Licho1** [comment]
I think thats desirable .. stuff is meant ot miss..
if stuff hits 100% we dont need physics and complicated engine..

**Comment by DeinFreund** [comment]
Is this how @GoogleFrog  intended the glaive update? Puppy was already a very rarely seen unit in 1v1, this reduces its use cases even further. 

Skirmishers are meant to miss. Suicidal anti raider units not that much I think.

**Comment by GoogleFrog** [comment]
Puppy missing does seem problematic.
