### ISSUE TITLE
Graphical artifact during game start (map edges)

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2068]
![What is it](http://i.imgur.com/VM6egq7.jpg)

when I scroll camera a little it becomes normal

![as it should be](http://i.imgur.com/Ynec2N8.jpg)

**Comment by dvr333** [comment]
This is possibly an engine issue, I don't remember if the start locations are a ZK widget or also engine code, but the map edge graphics (i.e. the textures going straight down the side of the map) are engine code.

**Comment by Anarchid** [comment]
A possible workaround would be to cull starting boxes to not precisely include map boundaries.

**Comment by let4be** [comment]
any progress on this? 
Still seeing this buttugly artifacts

**Comment by let4be** [comment]
Not fixed. I saw this just yesterday with exact same eye ripping effect

**Comment by let4be** [comment]
where is my reopen button :(

**Comment by sprunk** [comment]
Which map?

**Comment by let4be** [comment]
Yesterday on titan duel

**Comment by sprunk** [comment]
I checked TitanDuel and didn't reproduce. Then I looked at the battle and it turned out it's from before the fix (v1.5.4.0, fix was in 1.5.4.1).
