### ISSUE TITLE
Ship fac invincible from Halberds

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2069]
![iomg](https://i.imgur.com/Q3xBQkq.png)

**Comment by DeinFreund** [comment]
Shots impacting the left side of fac on this image don't seem to do any damage.

**Comment by GoogleFrog** [comment]
There is no hitbox there and the aimpoint is far on the other side. I assume someone used attack ground.

**Comment by DeinFreund** [comment]
If there's no hitbox, remove this part of the model? It can look like a bug.

**Comment by Anarchid** [comment]
I don't remember it being attack ground, iirc the halberds were just parked there and fired at will. Certainly most of the shots they did while moving away also did no damage, except for those that were fired from structure's right side.

**Comment by DeinFreund** [comment]
This entire army including distant penetrators was firing at this factory for >10 seconds straight without doing a single bit of damage.
![fsd](https://i.imgur.com/Eop8RRX.jpg)

This factory is practically invincible to anybody who doesn't know the hitbox.
