### ISSUE TITLE
Fragment shader "successful compilation" spam

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2072]
https://github.com/ZeroK-RTS/CrashReports/issues/337

**Comment by dvr333** [comment]
This doesn't show up anywhere in the Lua, at least not verbatim.

**Comment by GoogleFrog** [comment]
Duplicate.

**Comment by sprunk** [comment]
Duplicate of what? It's not the same as #1930.

**Comment by GoogleFrog** [comment]
Oh ok.
