### ISSUE TITLE
F Ctrl+Drag doesn't split targets

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2082]
It used to be possible to split targets for a group of units by issuing an area attack (as in: fire) order while holding Ctrl.

This seems to be broken; Ctrl + Area Attack seems to issue no orders at all.

**Comment by Anarchid** [comment]
Apparently issue is fake news.
```
<Setokaiva[IVL]> wait a sec
<Setokaiva[IVL]> ctrl + attack DOES split the attacks
<Setokaiva[IVL]> I just tested it
```

**Comment by Licho1** [comment]
What? I didnt know that! Lol maybe one day someone will make wiki with all the crazy tricks that exist
