### ISSUE TITLE
Provide a list of maps where minimap is too dark

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2083]
http://i.imgur.com/l5Cs6aX.png

This only happens for players! For spectators it is fine..

**Comment by GoogleFrog** [comment]
It's map dependent and that map is not supported.

I already solved this problem but, as I said, it's map dependent. You need to provide a list of broken maps. See the minimap table in this example: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Configs/MapSettingsOverride/Zed%202.2.lua

**Comment by The-Yak** [comment]
This is a task that's better left to the mapper then the game, IMO. minimapTex = "mini.png" replaces the minimap ingame.

I think I've taken care of all the maps with this issue.

**Comment by GoogleFrog** [comment]
This is better handled by maps because the sun hax only works until the terrain is modified. If a maps terrain has sufficient modification that block of the minimap will be recalculated, leading to a block coloured with the current sun settings.
