### ISSUE TITLE
Planetwars - planet that has been captured can be attacked the second time

### ISSUE THREAD

**Issue by Vistritium** [ZeroK-RTS/Zero-K#2084]
We have taken the planet: http://zero-k.info/Battles/Detail/449966
But another attack was initiated before game ended and so there was another attack on same planet after it was caputed: http://zero-k.info/Battles/Detail/449972
We won but we gained nothing.

**Comment by DeinFreund** [comment]
I've already reported that here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1627

**Comment by Vistritium** [comment]
This is duplicate then.
