### ISSUE TITLE
Vamp slowing down looks too unreal

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2085]
When vamp slows down behind some unit, like a rapier, it looks like a bug. If it does not do proper sweeps it should have some other indication that its not a bug .. like vectored thrust..

**Comment by GoogleFrog** [comment]
Vectored thrust? Wings change shape already.

**Comment by Licho1** [comment]
then it could perhaps reduce flame from engines too

**Comment by sprunk** [comment]
#2113
