### ISSUE TITLE
transport AI on factory guard: only follow move, not attackmove

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2090]
It is meant to transport units following factory queue up to a command that isnt move..

So that you can for example queue 3 moves to move along some path and then fight to continue fighting.

This is also useful for quickly turning this feature "off" you just order your factory with "fight".

This used to work fine for years, but now transports transport units even with fight command breaking the usefulness totally.

**Comment by sprunk** [comment]
Tested, works correctly.
