### ISSUE TITLE
PlayerList is not on top

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2094]
It appears below minimap.

**Comment by KingRaptor** [comment]
The way Chili works means that minimap cannot draw under other Chili elements without also drawing beneath its own window (which would cause it to appear greyed out). 

Ideas to circumvent this: 
- Minimap gets its own skin where the inside of the Chili window is transparent
- Frame drawing is done entirely within the minimap widget and the Chili window just acts as an invisible holder

**Comment by Licho1** [comment]
* minimap is moved or hidden while playerlist is shown

**Comment by GoogleFrog** [comment]
Is this tab playerlist?

**Comment by sprunk** [comment]
Subset of #2691
