### ISSUE TITLE
Metal reserve not working as expected

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2095]
1) have a comm and a factory
2) have reserve set to 200 or so
3) have total income of about 12m and factory building something 
4) set commander to high priority and start construction

Result: commander builds at full speed, factory nearly stops, reserve is untapped.

Expected result: both commander and factory build at full speed, reserve tapped until at 0, then commander only builds at full speed.

That was the way it was originally intended and designed.

**Comment by KingRaptor** [comment]
The expected result stated in issue report is identical to having zero reserve. In both cases, both fac and comm build at full speed till storage is empty, then comm gets 10/12 share from having high priority and fac gets the remaining 2/12.

Changing to match the issue expected result would require that medium priority gets the first share of income metal, then have high priority takes from what's left + takes from reserve (if available; if not high priority goes first).

**Comment by Licho1** [comment]
Hmm I was convinced it used to work that way though.. maybe it was bugged before?

**Comment by DeinFreund** [comment]
AFAIK reserve storage was always exclusive to high priority units. No matter in what order the metal is taken, as soon as it dips below storage level, the low and medium priority constructions will stop.

Source: FFA

**Comment by sprunk** [comment]
I don't think there is any decision left to make here because if you do the thing described in the first post you effectively remove reserve.

**Comment by Licho1** [comment]
alright
