### ISSUE TITLE
Custom chickens may not function correctly

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#2097]
I've seen complaints with regard to the custom chickens being affected by bugs. The latest such complaint was written perhaps around 2-3 months ago. I believe a player said the chicken settings didn't do the expected. It would be good if someone tested if the mode works as intended.

**Comment by KingRaptor** [comment]
My testing found no issues (or at least no obvious ones) with any of the following mod options:
- Chicken spawn rate
- Burrow spawn rate
- Grace period
- Queen time
- Dragon time
- Burrow queen time
- Tech time mult

Or with the ones that aren't specific to Custom difficulty:
- Speed chicken mode
- Eggs mode

I suspect the error resulted from not actually using the Custom chicken AI.

**Comment by Sgathec** [comment]
Thanks for testing. Should this issue be closed now?

**Comment by KingRaptor** [comment]
May as well. Someone can post here or make new issue if they encounter bugs.
