### ISSUE TITLE
CAI doesn't use airplanes, lands them instead

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2104]
![landed](https://i.imgur.com/Siwgbxmg.png)

https://i.imgur.com/Siwgbxm.png

**Comment by DeinFreund** [comment]
There seem to also be a lot of idle units near the repair zone. They have been repaired but are just sitting around.

![units](https://i.imgur.com/DBglGcS.png)

**Comment by sprunk** [comment]
CAI is deprecated.
