### ISSUE TITLE
When commander morph ends, it breaks current construction

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2105]
1) have a comm queue build something that takes a long time with shift something else too
2) morph it
3) when morph ends, currenct construciton is aborted and comm moves to next job

This is a regression, it used to work

**Comment by KingRaptor** [comment]
Cannot reproduce in skirmish with several different order/build queues.

**Comment by let4be** [comment]
Same story here

**Comment by Licho1** [comment]
Maybe it needs multiplayer? I will try to replicate

**Comment by let4be** [comment]
any progress? bug still alive and kicking

**Comment by sprunk** [comment]
Submit a replay.

**Comment by let4be** [comment]
Hopefully this will fix the issue, because I saw it just day ago or so

**Comment by let4be** [comment]
https://zero-k.info/Battles/Detail/471414
Observe Firepluk for the first 3 minutes
Please, fix this shit already - it's super annoying

**Comment by GoogleFrog** [comment]
The most recent release is 7 days old.

**Comment by let4be** [comment]
sigh...
