### ISSUE TITLE
Riot comm ignores trident

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2106]
Riot gun comm is perfectly capable of targeting tridents, however it does not seem to be auto firing at them.

**Comment by KingRaptor** [comment]
Cannot reproduce with Guardian Trainer. Is a replay available?

**Comment by sprunk** [comment]
I can't reproduce either. Tried:
 * just riot gun
 * riot gun + napalm conversion
 * riot gun + 8x range module
In all cases Trident gets shot as soon as it is in range.

Reopen if there's a replay or repro steps.
