### ISSUE TITLE
Investigate some terraform bug

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2108]
Balgias: often having trouble with units trying to start on a terraforming order only to have them never actually start building it, then it doesn't cancel because ally nanos are trying as well, forcing me to mass select them and ctrl-d

**Comment by let4be** [comment]
I often encounter another weird terra related bug: I make pre-game queue(fac, mexes, solars, etc)
com plops the factory and starts "building" tho it's ready and can produce units, it and refuses to continue going on with the queue unless I cancel the queue and manually tell com what to do next

**Comment by GoogleFrog** [comment]
That is not related to this issue. Make a new one.

**Comment by let4be** [comment]
I suppose this can be this built-in into engine "terraform before building can be placed",
for facs it can plop factory and then start smooth ground beneath it, at least it looks like this

**Comment by sprunk** [comment]
Nothing actionable here.
