### ISSUE TITLE
can't adjust the sound volume of loadingscreen music

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#2112]
Currently the loading music volume cannot be adjusted anywhere. Neither in Chobby, nor in-game.

**Comment by let4be** [comment]
And for me this music lags and randomly pauses during the load...

**Comment by db81** [comment]
That seems like a small thing, but it's very annoying.

**Comment by sprunk** [comment]
314748472cbf3cc47e585fd15fb2b7721c0750ff
