### ISSUE TITLE
Probably a map crash at game start

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2116]
Some map spams feature errors which possibly crashes Spring. See https://github.com/ZeroK-RTS/CrashReports/issues/556

**Comment by sprunk** [comment]
Tabula v6.1

Possibly a failed springfeatures dependency?

**Comment by The-Yak** [comment]
Tested on Tabula 6.1 vs circuitAI on multiplayer host, couldn't reproduce.

**Comment by sprunk** [comment]
The crash or the error spam?

**Comment by The-Yak** [comment]
Neither happens. Neither FP_featureplacer or dualfog is used or included in this map and I have no idea how those errors were created.

**Comment by sprunk** [comment]
Thanks!
