### ISSUE TITLE
LogicDaemon Desync

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2118]
These games have a sync error detected for LogicDaemon

 * https://github.com/ZeroK-RTS/CrashReports/issues/372
 * https://github.com/ZeroK-RTS/CrashReports/issues/373
 * https://github.com/ZeroK-RTS/CrashReports/issues/374
 * https://github.com/ZeroK-RTS/CrashReports/issues/376
 * https://github.com/ZeroK-RTS/CrashReports/issues/377
 * https://github.com/ZeroK-RTS/CrashReports/issues/387

 * https://github.com/ZeroK-RTS/CrashReports/issues/557
 * https://github.com/ZeroK-RTS/CrashReports/issues/558
 * https://github.com/ZeroK-RTS/CrashReports/issues/559
 * https://github.com/ZeroK-RTS/CrashReports/issues/561
 * https://github.com/ZeroK-RTS/CrashReports/issues/564

Find the game and try to get their infolog.

**Comment by sprunk** [comment]
I've added the ones from #2075 (crash ticket numbers 372-387) to the list.

**Comment by GoogleFrog** [comment]
This still occurs:
 * https://github.com/ZeroK-RTS/CrashReports/issues/1519
 * https://github.com/ZeroK-RTS/CrashReports/issues/1521
 * https://github.com/ZeroK-RTS/CrashReports/issues/1522

We should try to get all the relevant data about LogicDaemon to the engine devs.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/1690

**Comment by GoogleFrog** [comment]
@ashdnazg what would you need to investigate this? Apparently they have cleared caches multiple times.

**Comment by LogicDaemon** [comment]
I can dump my whole ZK folder somewhere (to Mega for example) if it could help. 17.9 GB.

**Comment by ashdnazg** [comment]
I won't have time before monday

**Comment by LogicDaemon** [comment]
as some people already suggested (including @GoogleFrog), it maybe be caused by the network.
Specifically (and this is just my guess), ISP may be modifying traffic. Also, SORM.

I stopped posting desyncs recently (I reply "no" on the query), but it still happens occasionally. I can start posting again if wanted :)

**Comment by ashdnazg** [comment]
it can't be traffic

**Comment by GoogleFrog** [comment]
I was asking what else it could be if it occurs across multiple PCs. That it does occur is worth testing.

LogicDaemon is the only one who submits crash reports with an i3-6100. Also they say that the desyncs reproduce when rejoining.

**Comment by ashdnazg** [comment]
which of the infologs is Logic's?

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20i3-6100

The owner of an infolog can be checked by searching "using name". These aren't necessarily all of their infologs, these are merely all the infologs using i3-6100.

**Comment by GoogleFrog** [comment]
LogicDaemon in frame 18702
https://github.com/ZeroK-RTS/CrashReports/issues/1693

LogicDaemon in frame 23452
https://github.com/ZeroK-RTS/CrashReports/issues/1702

**Comment by LogicDaemon** [comment]
here is full one [infolog.txt.zip](https://github.com/ZeroK-RTS/Zero-K/files/1202919/infolog.txt.zip)

**Comment by GoogleFrog** [comment]
Another game:
https://github.com/ZeroK-RTS/CrashReports/issues/1977
https://github.com/ZeroK-RTS/CrashReports/issues/1978
https://github.com/ZeroK-RTS/CrashReports/issues/1981

**Comment by GoogleFrog** [comment]
And another:
https://github.com/ZeroK-RTS/CrashReports/issues/1987
https://github.com/ZeroK-RTS/CrashReports/issues/1988
https://github.com/ZeroK-RTS/CrashReports/issues/1989
https://github.com/ZeroK-RTS/CrashReports/issues/1990
https://github.com/ZeroK-RTS/CrashReports/issues/1991
https://github.com/ZeroK-RTS/CrashReports/issues/1993

**Comment by ashdnazg** [comment]
I'll try and have a look tomorrow, it might be useful to have a debugging session with @LogicDaemon where he'll use special builds

**Comment by sprunk** [comment]
Seems to have been solved (at least the few most recent desync reports containing `LogicDaemon` have him in the synced majority).
