### ISSUE TITLE
ShadowHandler shader compile error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2128]
https://github.com/ZeroK-RTS/CrashReports/issues/625

**Comment by sprunk** [comment]
It's an engine shader: https://github.com/spring/spring/blob/5a3e3616ef0b3a4896216170bdc5fff1cfaa4185/rts/Rendering/ShadowHandler.cpp#L177

**Comment by sprunk** [comment]
Should it even be mantised? If engine shaders fail then the user probably has obsolete gpu/drivers.

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5591
