### ISSUE TITLE
Teleported units get their firestate reseted

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2129]
Why when I teleport units with firestate do not fire(red) it gets reseted to fire at will(green)?...

**Comment by KingRaptor** [comment]
Nothing in the Djinn teleport gadget touches this (and it would be weird if it did), and couldn't repro in skirmish. Could you provide a replay?

**Comment by let4be** [comment]
I don't remember the exact game now, but you can reproduce this by trying by teleporting an ultimatum or scorpion... In addition they uncloak right after being teleported

**Comment by sprunk** [comment]
I think it's intentional that they decloak on teleport.

Decloaking units get set to Fire At Will but should revert to Hold Fire once they recloak.

**Comment by let4be** [comment]
fire state reset looks wrong to me...

**Comment by KingRaptor** [comment]
It's controlled by [a widget](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_cloakfirestate2.lua) whose config menu setting (not widget menu) is default off. If it's not off for you, try toggling it.

**Comment by GoogleFrog** [comment]
No feedback.

**Comment by sprunk** [comment]
possibly related? https://github.com/ZeroK-RTS/Zero-K/commit/0a165d5e991c8630b9994c50a194236af9f48c4f

**Comment by GoogleFrog** [comment]
Likely the cause.
