### ISSUE TITLE
No second com given in 2v1

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2138]
http://zero-k.info/Battles/Detail/453553

It was a custom battle so maybe these intentionally don't give extra coms, but in this case they shouldn't count for elo.

What is the intended behaviour?

**Comment by Licho1** [comment]
Same here
http://zero-k.info/Battles/Detail/453692

**Comment by DeinFreund** [comment]
@sprunk https://github.com/ZeroK-RTS/Zero-K/commit/6eedca46e41c826eb437674c528456e6c93b8584 maybe related?

**Comment by DeinFreund** [comment]
Wait why did you close this? In custom game mode this was never fixed.
