### ISSUE TITLE
After game starts, minimap turns dark and stops showing eco

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2142]
Before game starts, minimap looks normal and shows eco.
After it starts, it turns uber dark (invisible on my screen) and does not show eco:

http://i.imgur.com/pCjXjN9.png

PLEASE FIX THIS IT MAKES ME RAGE AND GAME UNPLAYABLE

**Comment by sprunk** [comment]
af65b8eefeb4e3d8cc352a9559a9b174899bfc9b
