### ISSUE TITLE
Unit AI button in Integral menu does nothing

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2144]
It doesn't even send a command that gadgetHandler:AllowCommand() sees. 

The base Spring command menu (after /luaui disable) works.

**Comment by GoogleFrog** [comment]
Which unit? Some have widgetside unit AI buttons.

**Comment by KingRaptor** [comment]
Tested with the following units (none of which work) in skirmish:
- Glaive
- Rocko
- Rogue
- Ravager
- Impaler
- Banisher
- Mace
- Catapult
