### ISSUE TITLE
Plopping a factory makes com queue "stuck"

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2149]
http://zero-k.info/Battles/Detail/453920

I plopped a factory and com did not proceed with the queue trying to smooth ground beneath the factory... I had to manually abort this nonsense and requeue everything
(look for Firepluk)

**Comment by GoogleFrog** [comment]
This is easier to solve than the general bug. When fac plop is used get the builderID of the factory and remove the factory build order from the queue of the builder. It will fix basically all cases.
