### ISSUE TITLE
Racketeer ignores set target

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2152]
* Spawn a Dante and a Goliath, set them to hold fire.
 * Spawn an Racketeer for the enemy team.
 * Set the Racketeer to repetitively walk between two points near the Dante and the Goliath.
 * Set target the Racketeer onto one of the other units.
 * Notice that Racketeer disobeys randomly.

This does not occur for more conventional units, such as Moderator. I have tried disabling various target priority and overkill prevention gadgets but it appears to have no effect.

**Comment by sprunk** [comment]
>tried disabling various target priority and overkill prevention gadgets but it appears to have no effect

Would imply engine.

**Comment by GoogleFrog** [comment]
Possibly, but with luarules disabled the attack commands were not changed at all. You may be right though as EMP has some hardcoded target override
