### ISSUE TITLE
Unsynced luarules out of memory when saving large game.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2153]
Windows cannot have colons in file names. Try to save a save game called "11:05" and lua will be unable to delete the file and then throw an out of memory error. However, the error appears to be non-fatal (possibly it takes out unsynced gadgets and they do little so I didn't notice).

**Comment by GoogleFrog** [comment]
This seems to occur regardless of incorrect filenames. Perhaps the gadget uses too much memory.

**Comment by GoogleFrog** [comment]
Added garbage collection during load. Requires testing on large games.

**Comment by sprunk** [comment]
Seems to be working well enough (and if there are still cases where the load is too heavy then we'll eventually learn about them through reports).
