### ISSUE TITLE
Night missions broken since Game.version was replaced with Engine.version

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2154]
mission_night.lua crashes on its compatibility check and takes out the whole mission. Possibly worked around here: https://github.com/ZeroK-RTS/Zero-K/commit/ae2f7711cbf460dfb0709dccd4c9202c0fe30eca

**Comment by GoogleFrog** [comment]
It is not as bad as this, missions were not broken since then. They were broken since planetwars used the startboxes API as the gadget removes itself when a mission is detected. I dislike this system, I don't know what exists in missions which is going to override gameside gadgets or widgets and where to fix the mission lua.

**Comment by KingRaptor** [comment]
Which missions exactly are broken? AFAIK most/all use fixed start positions, and losing the night widget damages presentation but isn't likely to take anything else out with it.

**Comment by sprunk** [comment]
Given https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/208376445837a9ad6d081cd010271636eb1ccf83, is this done?

**Comment by GoogleFrog** [comment]
I don't know how changes end up in missions. @KingRaptor I just noticed that the widget was broken by looking at logs. I did not experience a broken mission. Afaik no missions use this widget.

**Comment by sprunk** [comment]
Sunrise 3 does IIRC.

**Comment by KingRaptor** [comment]
Missions will need republishing for changes in Mission Editor gadgetry/widgetry to apply.

Since the issue is minor in the only known case and Sunrise is discontinued anyway, this can be closed.
