### ISSUE TITLE
Nano auto patrol broken

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2155]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_auto_patrol_nanos.lua#L156

> bad argument #1 to 'bit_and' (number expected, got table)

**Comment by GoogleFrog** [comment]
Broken by this https://github.com/ZeroK-RTS/Zero-K/issues/2154

**Comment by sprunk** [comment]
436b906ee1e9b885cc10c76567d7948994e9453c
