### ISSUE TITLE
Check/Fix slow vs features

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2165]
Slow damage should not damage wrecks. In effect this means that the units with mixed slow/normal damage should damage wrecks less by the appropriate amount. This is a difficult ticket to solve since default damage is dealt to both shields and wrecks and the default damage is already configured to work well against shields. Perhaps this is a rule that can be changed in armordefs? Does FeaturePreDamaged exist?

Solving this ticket would allow Racketeer, Thunderbird and Cutter (?) to no longer technically deal EMP damage (which hardcodedly doesn't damage wrecks) and would possibly fix Racketeer unit AI.

**Comment by sprunk** [comment]
As far as I can tell shields do not use 'default' damage at least in some cases (beamlasers, the removal of the 5 projectile hax).

Note that shields can have an armorclass other than 'default' so it should boil down to globally changing their armorclass.

**Comment by GoogleFrog** [comment]
Sounds good. When removing the 5 projectile hax I did change their default damage.

**Comment by sprunk** [comment]
Yes, to 0.
