### ISSUE TITLE
Commshare gadget gives units to wrong squad

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2167]
In this game I shared with TechAUmNu and received control over his units. Meanwhile all my units went to SnuggleBass.

https://drive.google.com/open?id=0B0FswUjncRt0TE5ReHBubW5fVE0

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/27f9735eef1a6cddeb4f5c46f5b9eee66207fb89#diff-17c21ce7ce2075c5adf900c1a15638fc
