### ISSUE TITLE
Check unsynced lua for performance issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2170]
I crashed unsynced lua trying to save game and my performance improved significantly. Check there for slow things. I think the offender is likely LUPS.

**Comment by CrazyEddieTK** [comment]
FWIW a few days ago LuaUI crashed while I was catching up rejoining a large game as a spec. After the crash I had no user interface whatsoever, not even camera control, and performance was much, much better.

**Comment by GoogleFrog** [comment]
Well yes, obviously. However you need the UI to play.

**Comment by CrazyEddieTK** [comment]
I wasn't suggesting disabling the UI as a performance improvement. I was adding a data point that yes, there might be slow things there.

**Comment by GoogleFrog** [comment]
I've added more LUPS quality settings:
 * Individual toggles for enabling/disabling aircraft jets and wing trails in chobby, used by presets: https://github.com/ZeroK-RTS/Chobby/commit/149b934d01c3af23bbc6758640f091a27f7ed718
 * Removed some of the less-required and more resource hungry particles on lower settings: https://github.com/ZeroK-RTS/Zero-K/commit/a1230332bd56f12fda5348d4427b35c1cfbbb32b

**Comment by sprunk** [comment]
537a6446481c4c6d4ad2dd4b6ff792ea73b143ca
