### ISSUE TITLE
Replay is different from played game

### ISSUE THREAD

**Issue by Vistritium** [ZeroK-RTS/Zero-K#2171]
We have played a game, then I watched replay.
The game from replay is different from the actual game. In replay we have lost commanders (me and Liam) but in real game they were alive. Enemy commander got sniped by pene.
http://zero-k.info/Battles/Detail/454569?

**Comment by ashdnazg** [comment]
Desync when watching replay

**Comment by DeinFreund** [comment]
Alternative replays!

**Comment by GoogleFrog** [comment]
@ashdnazg does this mean you are dealing with reporting etc.. this desync?

**Comment by let4be** [comment]
This is the alternative universe!

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/7d4117c5b0f10e7e87239fca546b3404b3c513b8 ?
