### ISSUE TITLE
Damaging lightning guns deal no damage to wrecks

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2172]
This is a fairly unimportant issue since these are highly unlikely to hit wrecks. The fix would be the unhardcode the engine to do 0 damage to wrecks with paralysis engines. The behavior can be replicated with armorDefs.

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/307

**Comment by sprunk** [comment]
It should be sufficient to just swap the weapon type (do realdamage and add extra paralyze with Lua instead of the other way around).

**Comment by GoogleFrog** [comment]
In the beginning, ZK had two weapons slaved to each other, damaging lightning and EMP lightning. This was highly inconsistent. I tried adding paralysis damage in UnitDamaged but I think it caused some issue with EMP timer and the damages were applied in the wrong order for maximum effective paralysis damage. I'd like to avoid going back to normal weapon + lua paralysis.

**Comment by sprunk** [comment]
Canceled to make way for the internal rename merge, needs to be redone on the new unit defs.
