### ISSUE TITLE
Scorchers suicidally charge at obscene distances

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2174]
It seems that Scorchers and possibly other raiders have fairly recently started automatically moving to attack enemies at fairly huge distances, larger than their line of sight. This makes controlling any armies where Scorchers are present much harder than it used to be.

This is not due to a change in their default movestate. The orders they get to charge seem to be move orders rather than attack orders on a specific target, so perhaps tactical AI is involved.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/5a460f2fc59440e8e990c6df8fe8166f093c27b5.
