### ISSUE TITLE
Daggers have difficulties finding a path outside of factories on flat terrain

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K#2178]
http://zero-k.info/Battles/Detail/455016

**Comment by Anarchid** [comment]
Is this  https://github.com/ZeroK-RTS/Zero-K/issues/1586 ?

**Comment by gajop** [comment]
tldr;
maybe, check the replay

**Comment by sprunk** [comment]
Ancient replay with many pathfinding advances since.
