### ISSUE TITLE
Buildings can get raw move commands

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2183]
Select a mobile and a static. Give them a move order (without obstacles so that raw move is used). The static also gets the move command (possibly overriding existing commands). In some cases it seems to disappear after a moment but sometimes it lingers. This is mostly an UX problem because the command is drawn so it misleadingly looks like it does something while it does not.

**Comment by GoogleFrog** [comment]
Remember to retain factory and air repair pad raw move commands.
