### ISSUE TITLE
Plop effect is covered in lines.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2189]
Map is Alien Desert, it is possibly map dependent
![screen00387](https://cloud.githubusercontent.com/assets/1318249/25438310/60c933bc-2adc-11e7-8161-5fb8770c2b80.png)
.

**Comment by Anarchid** [comment]
I think those are edge artifacts of the ground dust particles.

**Comment by GoogleFrog** [comment]
Yes. Look in george.lua.
