### ISSUE TITLE
Backslash color codes break with textboxes in test ZK

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2192]
http://i.imgur.com/1vnYHZz.png

Only "Raiders" is supposed to be highlighted in the paragraph. Instead it also highlights everything after the first line within the same paragraph. (And yes, it's sensitive to textbox width.)

Does _not_ happen in zk:stable.

This is quite significant since it affects mission presentation.

Can be tested with the [testing functions](https://github.com/ZeroK-RTS/Zero-K/blob/d814b3540194daf276c1b3ffbdb82a4e159b351c/LuaUI/Widgets/mission_messagebox_ZK.lua#L601-L613) in mission_messagebox_zk.

**Comment by GoogleFrog** [comment]
You have to use \255\255\255\255 instead of \008. I can fix someone gameside but idk if the missions require regenerating for a full fix.
