### ISSUE TITLE
ZK provides garbage as savefile name for AI

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#2193]
Real save:
/home/bob/.spring/Saves/TestSave.lua
/home/bob/.spring/Saves/TestSave.slsf

AI receives on save:
/home/bob/.spring/save-team0_id0.tmp
AI receives on load:
/home/bob/.spring/load-team0_id0.tmp

Does ZK even use engine's save/load system or it's pure/mostly lua?

It's also possible that AI save/load callbacks were broken during major refactoring or were never properly implemented actually.

**Comment by GoogleFrog** [comment]
ZK uses the only engine save/load that I am aware exists.

**Comment by rlcevg** [comment]
As ZK uses only engine save/load mechanics this issue may be closed.
/home/bob/.spring/save-team0_id0.tmp
/home/bob/.spring/load-team0_id0.tmp
apparantly valid buffers, and it's possible to read/write them through direct file operations, instead of using AI's **File** interface.
There are some engine issues related to saving mutiple AIs, but it's not ZK issue.
