### ISSUE TITLE
ZK doesn't reuse unitID on save/load

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#2199]
Spring.CreateUnit and Spring.CreateFeature supports unitID param.
But ZK for some reason doesn't use it and generates new unitID that makes it impossible for AI to associate data with unit.

**Comment by Anarchid** [comment]
The comment at https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/api_saveload.lua#L220 says that
```
		-- The 9th argument for unitID cannot be used here. If there is already a unit
		-- with that unitID then the new unit will fail to be created. The old unit
		-- do not immediately de-allocate their ID on Spring.DestroyUnit so some blocking
		-- can occur with explicitly set IDs.
```

Unsure if this is valid for situations where, as during a save load, all unitID's belong to freshly created units.

**Comment by rlcevg** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/api_saveload.lua#L513
Ehm, what is this thing doing here?

**Comment by GoogleFrog** [comment]
Maps can come with units or features. these exist by default when the game is loaded and must be removed. Removing old units and features also makes development easier. We're not going to be reusing unitID/featureIDs unless removing units and features beforehand is shown to work.

Use the unitRulesParam saveload_oldID.

**Comment by rlcevg** [comment]
This deserves a ticket on mantis. Spring should ignore any map's unit/feature because they're already saved in saparate unit/feature section of savefile.
