### ISSUE TITLE
Weird username in chat 

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2201]
![img](https://i.imgur.com/uqUcBiS.png)
![i](https://i.imgur.com/6u0lTjB.png)

**Comment by DeinFreund** [comment]
Corresponding infolog
http://paste.springfiles.com/view/648e7b6c

> [f=-000001] > SPRINGIE:User Slaab|armbanth|7_5||False||Federation|FR
> [f=-000001] > SPRINGIE:User Slaab|armbanth|7_5||False||Federation|FR
> [f=-000001] > SPRINGIE:User granateboy|corsent|4_1||False|ZC||CH
> [f=-000001] > SPRINGIE:User granateboy|corsent|4_1||False|ZC||CH
> [f=0001487] > SPRINGIE:User cleanrock|chicken_drone|6_0||False|||SE
> 

The user message isn't being sent for all players. This would override names given in start setup (which is probably borked).

**Comment by Aquanim** [comment]
This bug appears to affect chat and tab-playerlist widgets, but Deluxe playerlist is unaffected.

**Comment by sprunk** [comment]
Stuff said in #2219

>This is likely due to the editbox change and some interaction with colour characters.

>filch can also break chat. It looks like "d(<filch>" and can be seen at the start of this replay http://zero-k.info/Battles/Detail/456716.

**Comment by DeinFreund** [comment]
This is an effect of #2236
