### ISSUE TITLE
Check FFA maps with boxes

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2202]
Playing a FFA on duke nukem crashes gadgetry. On game start no commanders are spawned.

http://paste.springfiles.com/view/619edbee

```
[f=-000001] Error: LuaRules::RunCallIn: error = 2, Initialize, [Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/start_boxes.lua"]:22: attempt to index local 'box' (a nil value)
stack traceback:
        [C]: in function 'Include'
        [string "LuaRules/main.lua"]:32: in main chunk
```

**Comment by DeinFreund** [comment]
I wouldn't call lack of commander spawning "minor" and "UX" but whatever..

There seemed to be a similar but different bug on FFA maps with boxes. There it would simply fail some minor gadget leading to the "ready" button having to be pressed at game start, but everything else worked. So if you're testing for this bug you might wanna look out for that as well.

**Comment by DeinFreund** [comment]
What exactly did you fix with your commit?

**Comment by sprunk** [comment]
I made the PW gadget not ask the box gadget for (possibly non-existent) boxes outside PW games, which is a lazy workaround that relies on the assumption that PW maps all have boxes #0 and #1 set. The 'proper' fix would be to add checks to box-side code but that would be more than 1 line so I don't want to do it blindly through github.

**Comment by sprunk** [comment]
>There seemed to be a similar but different bug on FFA maps with boxes. There it would simply fail some minor gadget leading to the "ready" button having to be pressed at game start, but everything else worked.

I locally checked Throne and Mearth, with shuffle modoption {nil, auto, allshuffle} and couldn't reproduce this.

**Comment by DeinFreund** [comment]
Apparently Duke worked in MP too. I'll return if I encounter something like this again, otherwise it's probably fixed.
