### ISSUE TITLE
Tick <-> Anti-Raider interaction

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2204]
Tick currently stuns most riots and turrets, this means while being a defensive unit it has to be deployed in mostly open terrain. Damage falloff also causes it to hit close-by defenders harder than some attackers that might be just at the border of its range.

What would speak against reducing Tick's stun damage and falloff to make sure it only affects raiders? This would allow placing it under turrets or using it together with riots/heavies.

**Comment by Anarchid** [comment]
I like Tick being able to stun Thug and Outlaw.

**Comment by sprunk** [comment]
Imp (Tick) has a smaller diameter than Stardust range so it can sit under any turret safely. Having low enough damage to be safe to mix with Reaver (Warrior) etc sounds interesting but from a design PoV steps on Limpet's toes and from a balance PoV would require a very large numerical change, fragile.
