### ISSUE TITLE
Dualfog fails to load with maps launched from Chobby

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2207]
Can be reproduced with both Fairyland and Siberian Divide. These same maps can be loaded from spring.exe and latest ZK with no errrors.

> [f=-000001] [gadgets.lua] Error: Failed to load: gui_dualfog_gadget.lua  ([string "LuaRules/Gadgets/gui_dualfog_gadget.lua"]:132: attempt to index field 'version' (a nil value))

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/981320/infolog.txt)

**Comment by GoogleFrog** [comment]
I highly doubt that this is chobby related. I think it is due to the Game and Engine table changes. Does the game have any access to luaGaia? If not then this is unfixable gameside.

**Comment by The-Yak** [comment]
I'll try and diagnose this better and make an engine ticket.

**Comment by GoogleFrog** [comment]
> I think it is due to the Game and Engine table changes

See https://springrts.com/mantis/view.php?id=5455. The reason is known and the simple solution is known. The only thing you could get out of a mantis ticket would be the reintroduction of the keys into the Game table, for backwards compatibility.
