### ISSUE TITLE
Orbit guard issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2212]
Use orbit guard with 5 Bandits and one Roach. The units don't hold a circle correctly. Possibly the issue is with setting wanted max speed.

**Comment by GoogleFrog** [comment]
This may also be causing a performance issue.

**Comment by sprunk** [comment]
>Units now call CommandFallback when they finish their move goal. This causes the units to circle out of order since the order is determined by the order in which they call CommandFallback.

**Comment by sprunk** [comment]
67265fb57fe23353064534992dfcca928cd3e8a2
