### ISSUE TITLE
Units move uncontrollably

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2216]
Similar to #2174 I've experienced scorchers giving themselves suicide orders into enemies more than 500 elmos away. This doesn't only apply to scorchers but in some way seems to affect other units as well.

Scalpels like to dive into defenses or banishers in order to get a shot off. Penetrators turn in infinite circles while trying to kite the enemy razor's kiss.

**Comment by GoogleFrog** [comment]
Make a demonstration replay, otherwise I doubt I'll look at it. Your description of the issue is too vague for me otherwise. I could spend lots of time spawning some simple situations and get nothing.

**Comment by DeinFreund** [comment]
https://drive.google.com/open?id=0B0FswUjncRt0cVgtQXpCRmkzRVU
Scorchers, Rockos, Rogues going rogue and attacking into defenses without a direct order nor being attacked by the defense.

Was astonishingly easy to reproduce. Build a LLT. Place a rocko next to it (outside of range). The rocko will get an attack order onto the llt and move into range, possibly killing itself. Same goes for scorchers.

**Comment by hedgehogsthateat** [comment]
Unit AI bug?

**Comment by DeinFreund** [comment]
Indeed.

**Comment by GoogleFrog** [comment]
Scorcher fixed. The rest seems intentional, I don't know why you would want those units set to anything but hold position either. Perhaps the defaults should be changed to hold position?

**Comment by DeinFreund** [comment]
That didn't happen some versions ago and it makes skirmisher AI unusable. Limited move for skirmishers meant stay still and retreat if an enemy comes close, not suicide into enemies ahead.

**Comment by GoogleFrog** [comment]
Find the version that has the behaviour you want.

**Comment by Topkack** [comment]
ahh so thats why i found light vehicle to be unplayable

**Comment by sprunk** [comment]
> Penetrators turn in infinite circles while trying to kite the enemy razor's kiss.

Sounds like #4461

> Find the version that has the behaviour you want.

Didn't happen

> Scorcher fixed. The rest seems intentional

Looks like everything actionable has been done.
