### ISSUE TITLE
Autogroup waits for queue

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2217]
Autogroup waits for the factory's waypoint queue to finish before assigning units to their groups. This means that you have to decide between using waypoints or autogroups, because otherwise the autogroup is too delayed to be usable.

Even without a waypoint, the 3-5 second delay means that one usually has the unit added to a group manually before it gets added automatically
.

**Comment by CrazyEddieTK** [comment]
This is controllable by an option setting. Settings/Interface/Control Groups -> Immediate Mode

**Comment by DeinFreund** [comment]
Although, they never get added in the other case. If they are given a command before reaching factory waypoint, even if they are stopped they won't be added to the group.
