### ISSUE TITLE
Make TA and COFC cameras use the same smoothscroll slider

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2218]
Camera options were poor and very user un-friendly. Now they have advanced to being a mess. The smoothscroll widget toggle option was replaced with a tickbox that only appears if the widget is disabled. The widget is disabled in my main game, have not tested default. Selecting COFC disables the smoothscroll widget, causing further mess. If you enable the smoothscroll widget after COFC disabled it then middle click scroll is completely broken.

**Comment by sprunk** [comment]
Being disabled for existing people was fixed: https://github.com/ZeroK-RTS/Zero-K/commit/c5d09567495297702678040fae862874106294f9

I will probably be able to check this out today or tomorrow evening and definitely during the weekend.

**Comment by GoogleFrog** [comment]
COFC disables smoothscroll so if COFC is supposed to be selectable there is an issue.

**Comment by sprunk** [comment]
The solution is to make COFC disable the Smoothscroll behaviour (but not the tickbox nor the widget).

**Comment by CrazyEddieTK** [comment]
COFC implements smoothscroll internally, disabled by default. Having the smoothscroll widget and COFC both enabled is probably a nightmare.

COFC has a function which detects if the smoothscroll widget (and also 'Hybrid Overhead' and 'Complete Control Camera', which I think are deprecated / removed?) is enabled and warns you every 480 frames to disable it.

**Comment by sprunk** [comment]
Smoothscroll widget is for the TA camera.

**Comment by sprunk** [comment]
Both smoothscrolls (TA and COFC) should probably use the same setting slider.

**Comment by sprunk** [comment]
Moved to #2185, "Menu camera settings", as a sub-task.
