### ISSUE TITLE
4hundred sometimes breaks chat

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2219]
Whenever 4hundred says something with a white name the chat is broken with nonsense characters before their name. This is likely due to the editbox change and some interaction with colour characters.

**Comment by GoogleFrog** [comment]
filch can also break chat. It looks like "d(<filch>" and can be seen at the start of this replay http://zero-k.info/Battles/Detail/456716.

**Comment by sprunk** [comment]
Duplicate of #2201
