### ISSUE TITLE
Check and set ROAM=1 when it works on dev engine

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2220]
Apparently the cliffs of Onyx Cauldron have some issue.

**Comment by Aquanim** [comment]
http://i.imgur.com/Ht1thnQ.jpg
this seems right
http://i.imgur.com/s2uoUYv.jpg
this seems wrong

The terrain mostly looks like the first image but flickers into the second when camera is moved/zoomed.

**Comment by Anarchid** [comment]
Try playing with terrain detail options. This looks like ROAM LoDding to me.

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5551#c17612

TL;DR:
 * spikey terrain handled badly by ROAM > 0
 * ROAM = 0 should be a performance improvement though

**Comment by sprunk** [comment]
ROAM = 0 applied (as a default in Chobby) without any obvious performance regression. Close?

**Comment by GoogleFrog** [comment]
I don't believe that there is no regression. An action related to this is still required.

**Comment by GoogleFrog** [comment]
ROAM works and is reenabled https://github.com/ZeroK-RTS/Chobby/commit/ca1f012327d2177a7f872d3b0bdc0a280747ae42
