### ISSUE TITLE
Attack command

### ISSUE THREAD

**Issue by Radavvadra** [ZeroK-RTS/Zero-K#2224]
May have been reported before but auto attack overrides player attack command meaning the only way to be sure a unit shoots the right target is to put it on hold fire.

**Comment by GoogleFrog** [comment]
Replay?

**Comment by Radavvadra** [comment]
I will have a look but its present in every game in the last couple of months most obvious with berthas they kind of shoot random stuff unless on holdfire.

**Comment by Radavvadra** [comment]
I will have a look and post if i find an obvious example.

**Comment by Radavvadra** [comment]
I will be on the lookout for a good replay to demonstrate this.

**Comment by Radavvadra** [comment]
http://zero-k.info/Battles/Detail/457171?

**Comment by GoogleFrog** [comment]
Firing at radar was disabled for the sniper (see the fire radar state toggle). Also the curvature of the terrain blocks the shot when the sniper was further down the hill. I think the sniper performed fairly well given the behavior that was set for it.

This replay is not showing the issue reported in the opening of the ticket. The sniper did not fire at a different unit while able to fire on its attack target. To demonstrate the bug I want to see a unit with attack command and a clear like of fire to its target fire at a different unit instead.

**Comment by Radavvadra** [comment]
meh I guess we missed the effect of terrain sorry this Isn't hard to replicate but more tricky to demonstrate the replication (or I'm just useless at play testing)

**Comment by Radavvadra** [comment]
8:06 sniper shoots a closer target while having an order to shoot at a different target. http://zero-k.info/Battles/Detail/457246?

**Comment by Radavvadra** [comment]
21 mins in firewalker wastes shots twice on mines (the first time also setting fire to friendlies) before being told to hold fire. https://zero-k.info/Battles/Detail/457456

**Comment by GoogleFrog** [comment]
http://zero-k.info/Battles/Detail/457246 the sniper was set to Fire at Will at the last moment.

**Comment by GoogleFrog** [comment]
https://zero-k.info/Battles/Detail/457456 the firewalker is not yet in range of its targets when it wastes its shot on the mines. I have not yet seen a failure case.

**Comment by sprunk** [comment]
All cases shown so far have been valid.
