### ISSUE TITLE
debug log

### ISSUE THREAD

**Issue by Radavvadra** [ZeroK-RTS/Zero-K#2225]
debug log reports de sync for at least one player every game but no noticeable desync occurs games are also recorded on the site.

**Comment by sprunk** [comment]
I'm not sure if this is of any use without actual logs or replay examples.

**Comment by Radavvadra** [comment]
https://zero-k.info/Battles/Detail/457440

**Comment by sprunk** [comment]
I think wrapper incorrectly giving a false positive would be an infra issue?

**Comment by sprunk** [comment]
Made an infra ticket.
