### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Radavvadra** [ZeroK-RTS/Zero-K#2226]
random CTD when playing multiplayer game.

**Comment by Jamanno** [comment]
http://paste.debian.net/932213/

**Comment by DeinFreund** [comment]
Reported: https://springrts.com/mantis/view.php?id=5552

**Comment by Jamanno** [comment]
changing engine back to .19 did not make any problems anymore

**Comment by DeinFreund** [comment]
Apparently already a known issue, no idea why we're still using this spring version..

**Comment by GoogleFrog** [comment]
764 is pretty crashy too, just apparently for less vocal people.

**Comment by GoogleFrog** [comment]
Fixed in 900 apparently.
