### ISSUE TITLE
Dante missile launch smoke broken in 103-900

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2229]
The smoke that Dante emits when it launches a missile is now thrown up into the sky with high velocity instead of appearing in bursts around its arms.

**Comment by Anarchid** [comment]
In general whole classes of CEG seem bad. Compare jump sparks and commander HMG spikes.

**Comment by GoogleFrog** [comment]
Reported here https://springrts.com/mantis/view.php?id=5561

@Anarchid I have no idea what you are trying to say.

**Comment by GoogleFrog** [comment]
Probably fixed in engine.
