### ISSUE TITLE
Sprunk opened the gate to merge hell

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2231]
We're currently in merge hell with the internal unitdef rename branch. The recent changes affecting unitdefs etc... need reverting.

**Comment by sprunk** [comment]
alright

**Comment by sprunk** [comment]
Done, check if okay now.

**Comment by GoogleFrog** [comment]
What was done?

**Comment by sprunk** [comment]
Force pushed the head from before my commits.

**Comment by sprunk** [comment]
I'd put your two commits on top of f7f0d004a282bf4a5e4bb83072db67e and force push that.

**Comment by GoogleFrog** [comment]
Ok, all done. I merged internal rename to prevent this in the future.
