### ISSUE TITLE
Mace on attack order doesn't attack.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2238]
It goes into range, then drives backwards until it is out of range again and stays there.

**Comment by KingRaptor** [comment]
Can't repro in current version testing. Is this still an issue, and if so, can you provide circumstances (target unit type and whether any other enemies that may affect unit AI are present) where this occurs?

**Comment by DeinFreund** [comment]
Can't reproduce anymore.
