### ISSUE TITLE
Feature Request - Spawning AI for Sandbox

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2242]
The Sandbox mission needs a different AI. It should be similar to the Chickens AI in that it can spawn a number of enemies which are continuously given fight commands towards the closest player units. The difference, though:

- It spawns normal ZK units instead of chickens
- Spawning is under the control of the player

There should be a few large buttons on the screen: "Spawn land enemies" "Spawn air enemies" "Spawn sea enemies" "Spawn defenses". Each time the player presses one of the buttons the AI spawns an appropriate set of enemy units (randomly selected from a reasonable and varied collection of unit compositions) and sends them off to fight the player. Spawned defenses can be built around the AI Commander (which would otherwise do nothing, like Null AI) and/or build a mex on an empty metal spot and put defenses around it, perhaps even spawning mobiles which patrol the defended area. Perhaps also have a box with a radio button to select the difficulty / size of the spawn ("Easy"/"Moderate"/"Hard"/"Suicidal").

This would make the Sandbox more interesting and more useful as a training aid. The Sandbox should be an important part of a new player's introduction to Zero-K. We should encourage players to use it and we should make it more worth their while to do so.

The AI could be included as an option to add to skirmishes ("Trainer AI") so that players could set up their own sandboxes on their choice of maps.

**Comment by sprunk** [comment]
Related: #1253

**Comment by CrazyEddieTK** [comment]
Closing this. I've come to think that a Very Easy AI (as discussed [here](https://github.com/ZeroK-RTS/Zero-K/issues/2179) and [here](http://zero-k.info/Forum/Thread/24239)) is a better approach for giving new players room to experiment.

If we implement that well, then Sandbox doesn't need to be an official mission, and anyone who wants to do a sandbox can make their own skirmish with Inactive AI. #1253 would still be a good addition, but it would be for development and testing or for advanced users to play around with, and not part of the official introduction / training mission sequence that we present to new players.
