### ISSUE TITLE
Dukes are no longer animated and can't attack

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2248]
Is this due to an engine update or maybe related to some change within zk? The dukes receive attack orders and glide towards their targets, but are unable to fire a shot.

http://zero-k.info/Battles/Detail/457709

(Applies to the Duke Nukem 4 map)

**Comment by Anarchid** [comment]
Sounds like broken unitscript. Impart infolog.

**Comment by Anarchid** [comment]
Sounds like broken unitscript.

**Comment by sprunk** [comment]
If someone figures out a trivial ZK-side fix then it will be accepted, however this is not a ZK issue (even if caused by change in ZK, warranty is void for unofficial maps).

**Comment by GoogleFrog** [comment]
This ticket had me worried. I recalled reading a ticket about Ducks being unable to attack (likely broken LUS) and thought it was something that needed fixing for the tournament. However when I searched the tickets for 'duck' I couldn't find anything so I thought I hallucinated the ticket.
