### ISSUE TITLE
Terraform order recursion error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2256]
[f=0031125] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=CommandFallback trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3216: GiveOrderToUnit() recursion is not permitted

https://pastebin.com/e7Gi2yry

**Comment by sprunk** [comment]
I'll see if engine can be made to allow recursion.

**Comment by GoogleFrog** [comment]
Still occurs.

[f=0010042] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=CommandFallback trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3216: GiveOrderToUnit() recursion is not permitted

**Comment by sprunk** [comment]
Duplicate of #2522.

**Comment by sprunk** [comment]
? Same issue.

**Comment by GoogleFrog** [comment]
Disallowing recursion isn't a crash.

**Comment by sprunk** [comment]
I see. That other ticket actually has two different terraform errors and I only saw the first one.

**Comment by sprunk** [comment]
ZeroK-RTS/CrashReports#2094
