### ISSUE TITLE
Map edge extension is broken on Mininuggets_v2

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2260]
"Texture" is the only broken setting. "Curvature Effect" does not change whether the texture is broken.
![screen00447](https://cloud.githubusercontent.com/assets/1318249/26566991/e5502d98-453a-11e7-883d-b3bf5873ee3e.jpg)

**Comment by The-Yak** [comment]
Older map converter solutions had compression models that would do nasty things to maps like this if set too high. 

Thankfully this is easy enough to fix mapside by just opening the map in SpringMapEdit and saving it again. I'll do a quick detailing with same settings as Chicken Nuggets 5 and upload a new version.

This can be closed.
