### ISSUE TITLE
Right leg of Dirtbag goes far underground at the start of its walkscript

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2262]

**Comment by sprunk** [comment]
74c1ba3f9707edbdafb995f7d22d67caba680028

**Comment by KingRaptor** [comment]
Oh dear, that Dirtbag script wasn't actually supposed to go in there.

Although I'm not sure whether it should be reverted, modified (to restore Dirtbag walk style unique-ness) or left as it is.

**Comment by sprunk** [comment]
19442b3622437becab73dd043184930ee14d2f8a

**Comment by sprunk** [comment]
#4251
