### ISSUE TITLE
Fix COB script wrecks

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2265]
All COB scripts need to be changed to return the desired corpsetype number, so that badly overkilled units turn to debris instead of wreckage. See [Mantis 5590](https://springrts.com/mantis/view.php?id=5590) for details.

[This](https://github.com/spring/spring/commit/48bbcd799d2e5c01806b105d1fedf0d23285d962) Python tool may be of interest.

**Comment by GoogleFrog** [comment]
I feel like I already ran this script in 1e8fd374d362e9e6f321b3561820deaf9d00d584.

**Comment by KingRaptor** [comment]
Either it didn't work or someone recompiled the scripts afterwards (although what are the odds that they did all four of the scripts I tried, I dunno)

In any case, the .bos source files should be modified as well in light of the latter possible scenario.

**Comment by GoogleFrog** [comment]
I want there to be no further compiling of bos. As far as I'm concerned the files exist to ease the conversion of scripts into lua.

**Comment by sprunk** [comment]
>someone recompiled the scripts afterwards (although what are the odds that they did all four of the scripts I tried, I dunno)

https://github.com/ZeroK-RTS/Zero-K/commit/095a6b9bcd80e2add3dca64303e954aa4f99c112
