### ISSUE TITLE
Hammers given force fire can fire instantly even when pointing other way

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2266]
1) make a hammer
2) let it face south
3) give it force fire north ... it insta fires even without turning

It makes it look unphysical and buggy, also happens with lasers like pene, bantha, anni etc

**Comment by GoogleFrog** [comment]
I was only able to reproduce this with Hammer, Halberd and Jack. The latter two sort of animate and it is hard to spot that anything is wrong, I wouldn't change them. Pene, Bantha and Annihilator work fine.

**Comment by Licho1** [comment]
It happens with pene and HLT if they react fire (not force fire) afaik.

**Comment by sprunk** [comment]
Hammer had already been fixed earlier 5561599d78ab91704724be5f037a6578f0e9276a.
