### ISSUE TITLE
Check area reclaim

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2279]
Apparently broken, puts orders at the end of the queue. I suspect 5eb231dff4c3e5787f935e50d593edb1f2151547

**Comment by KingRaptor** [comment]
Random observation: My tutorial's area reclaim was broken until I made the command blocker gadget whitelist CMD.INSERT (and REMOVE, although I don't think that was needed).

**Comment by sprunk** [comment]
That would explain it.
