### ISSUE TITLE
Chili Enhancement: Complete SetPos Options

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2282]
Chili SetPos() takes x, y, w, and h. But unlike New() it doesn't take right or bottom. This means you can create correctly-positioned controls which are impossible to correctly _re_position without creating them over again from scratch.

SetPos should take all six possible boundary-specifying parameters. And if #2281 is implemented, SetPos should take center and vcenter as well.

**Comment by sprunk** [comment]
Use `SetPosRelative` with negative `x`.

**Comment by CrazyEddieTK** [comment]
Negative ``x`` sets the left edge of the object a fixed distance from the right edge of the container. ``right`` sets the right edge of the object a fixed distance from the right edge of the container. They're not the same; they behave differently when resized.

**Comment by sprunk** [comment]
Everything can be done with `x` and `w`, though when emulating `r` you'll need to take into account the other variable:

| From | To  |
|---|---|
| x = 1<br/>w = 2 |x = 1<br/>w = 2|
| x = 1<br/>r = 2|x = 1<br/>w = -(1+2)|
| r = 1<br/>w = 2|x = -(1+2)<br/>w = 2|
