### ISSUE TITLE
Situation specific performance issue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2283]
This game has poor performance: http://zero-k.info/Battles/Detail/458881

I think it is due to an uncommon situation that occurred in the game as opposed to a generally occuring problem. Three candidates are:
 * Endgame graph update spam (already fixed). I ran the profiler comparing this version and the fixed version but found little difference.
 * Area guard. A large area guard occurs on the bottom of the map. The units bunch up against the map edge and misbehave. Area guard is misbehaving in general though.
 * Tremor. This game sees quite a few Tremors.

The highest strain in the profilers is area guard.

**Comment by sprunk** [comment]
Area guard seems to have been optimized since (e26f32b7b999c90bab2f469ccb0a6a0af1cfaa10 and a bunch of table allocation commits later), graphs were apparently already fixed by the time the ticket was made and Tremor gets made regularly nowadays with little complaints. Replay is ancient anyway.
