### ISSUE TITLE
Endgame window doesn't always appear

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2285]
See the comments under battles:
 * http://zero-k.info/Forum/Post/175392#175392
 * http://zero-k.info/Forum/Post/175408#175408
 * http://zero-k.info/Forum/Post/175411#175411

@CrazyEddieTK

**Comment by CrazyEddieTK** [comment]
Maybe a runtime error?

If for some reason statsSubPanel = WG.MakeStatsPanel() doesn't succeed during widget:Initialize() in gui_chili_endgamewindow.lua, then later on there are unguarded calls to statsSubPanel.whatever.whatever which will crash the widget.

But that's just a guess. It's worked every time for me. Is there some way to get an infolog when people get this problem?

**Comment by GoogleFrog** [comment]
[f=-000001] Loaded widget:  Simple Settings     <gui_simple_settings.lua>
[f=-000001] [cawidgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_chili_endgraph.lua"]:282: attempt to perform arithmetic on a nil value
[f=-000001] [cawidgets.lua] Error: Removed widget: Chili EndGame Window
[f=-000001] Loaded widget:  Chili EndGame Window  <gui_chili_endgamewindow.lua>

**Comment by CrazyEddieTK** [comment]
Unguarded call to an engine function:

    local graphLength = Spring.GetGameRulesParam("gameover_historyframe") or (Spring.GetTeamStatsHistory(0) - 1)

I'll fix it when I next have dev time, unless someone else does it first.
