### ISSUE TITLE
Flea burrows while attacking

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2292]
Fleas burrow and stop shooting with attack order in place. See attached file.

P.S. It's inconvenient that Infra doesn't save my test replays. Not sure why, but it could be one of the three: 1) Null-AI in place 2) !cheats 3) Custom game

[20170606_215922_AlienDesert_103.0.1-1026-geb88c51 develop.zip](https://github.com/ZeroK-RTS/Zero-K/files/1056113/20170606_215922_AlienDesert_103.0.1-1026-geb88c51.develop.zip)

**Comment by GoogleFrog** [comment]
Unfortunately a game has to end to be saved. I don't think burrowing when attacking is a problem as long as they continue to fire when burrowed.

**Comment by lhog** [comment]
I can't recall about the replay I attached, but I had a few games finished in a proper way: I self-D-ed the other side and undid !cheats, so the game showed me endgame graphs.

```I don't think burrowing when attacking is a problem as long as they continue to fire when burrowed.```
It's exactly the point of the ticket: fleas burrow, cloak and eventually stop shooting.
