### ISSUE TITLE
Official name for 'features'

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2295]
Wrecks, trees, rocks etc - the technical term for them is 'features' but that is a horrible name for regular users. Figure out a decent official name. "Reclaimables"?

**Comment by CrazyEddieTK** [comment]
Can we just say "Wrecks, trees, rocks, etc" ?

Where are you proposing to use the official name? The wiki? Tutorials? "Features" works for technical people digging behind the scenes, and "rocks and trees" works for regular users.

**Comment by sprunk** [comment]
Wiki and tutorials, ingame tooltips.
I guess "wrecks rocks trees etc" works but is somewhat unwieldy.

**Comment by Anarchid** [comment]
Some other RTS games call map objects of this kind "doodads". When planted by a mapper, they are decorations or even "furniture". Playing off the reclaimable aspect, they could be "materials", "scrap", or some synonym. However, some features are not reclaimable and even non-interactive (like featuremexes). 

The remaining distinction is not being active (like buildings, units, etc) while being an object. So i guess you could call them environment objects.

**Comment by CrazyEddieTK** [comment]
Or even just "objects".

Example use in a tutorial:

"When a unit is destroyed it leaves behind wreckage. This wreckage can be reclaimed for valuable metal. Most other objects found on maps, such as rocks and trees, can be also be reclaimed. Hard objects like rocks and minerals usually provide metal; softer objects such as trees and plantlife provide energy when reclaimed. Reclaiming map objects can be an important source of additional resources, especially early in the game when your income from metal extractors and power plants is still very low."

**Comment by Aquanim** [comment]
To my mind, "doodad" describes something whose primary purpose is decoration. While that is descriptive of some features (say the formations on Akilon or the mex decorations on Coagulation) and perhaps should be used to describe those features I think it's misleading when applied to resource sources which on some maps have a very significant impact on the game.

I don't think that "features" is a catastrophically bad name though. I'd say that in a vacuum it conveys a little more information tha "object" does.

**Comment by sprunk** [comment]
I think the most precise thing to use is "reclaimables", my original probem with that name was that you cannot use it to describe the reclaim command itself, but there an explicit "wrecks trees rocks etc" can do.
