### ISSUE TITLE
epicmenu search is broken (NOT case sensitivity)

### ISSUE THREAD

**Issue by Gyslain** [ZeroK-RTS/Zero-K#2296]
![1](https://user-images.githubusercontent.com/11692729/26991543-0ef8747a-4d5b-11e7-9182-6d35bcee4794.jpg)
![2](https://user-images.githubusercontent.com/11692729/26991546-11f19a08-4d5b-11e7-87c2-19abcf9bae0e.jpg)

**Comment by sprunk** [comment]
Does "Glaive" (capitalized G) work? There used to be an issue about case sensitivity (#1878) but it is marked fixed.

**Comment by Gyslain** [comment]
"Glaive" doesn't work either.
