### ISSUE TITLE
Investigate Chili slider float error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2298]
[f=0000134] Error: gl.CreateList: error(2) = [string "LuaUI/Widgets/cmd_mex_placement.lua"]:669: invalid option '%.' to 'format'

Set "Display digits" to minimum then enable 'Show Income as Icon'. Mess around with the "Display digits" setting while mex view is enabled and you will probably see this error.

**Comment by sprunk** [comment]
This was caused by the slider value being 3.99999976 instead of 4. Using explicit `step = 1` does not fix this. Which places you have to click to reproduce appears random but any given pixel reproduces 100% of the time. Looks like a Chili slider bug.

**Comment by GoogleFrog** [comment]
Sliders aren't guaranteed to return integers. Perhaps that should be an option in the slider.
