### ISSUE TITLE
Warnings/Errors when starting Zero-K (LuaMaterial + Shaders on Linux/Mesa)

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K#2299]
I get these warnings when i start zero-k:
[f=-000001] Deferred Rendering Widget: blurshaderH71 failed to compile!
[f=-000001] 0:19(18): error: could not implicitly convert operands to arithmetic operator
0:19(2): error: operands to arithmetic operators must be numeric
0:19(2): error: could not implicitly convert error to float

[f=-000001] Deferred Rendering Widget: blueShaderV71 failed to compile!
[f=-000001] 0:19(18): error: could not implicitly convert operands to arithmetic operator
0:19(2): error: operands to arithmetic operators must be numeric
0:19(2): error: could not implicitly convert error to float

[f=-000001] Deferred Rendering Widget: Failed to create bloom shaders!

and: Edit: the below fixed as #2406 

~~[f=0000001] Warning: LuaMaterial: incorrect uniform type for "ShadowParams", got: mat4 expected: vec4
[f=0000001] Warning: LuaMaterial: incorrect uniform type for "TeamColor", got: vec3 expected: vec4
[f=0000001] Warning: LuaMaterial: incorrect uniform type for "ViewMatrix", got: mat3 expected: mat4
[f=0000001] Warning: LuaMaterial: incorrect uniform type for "CameraPos", got: mat4 expected: vec3
[f=0000001] Warning: LuaMaterial: incorrect uniform type for "SunDir", got: unknown expected: vec3~~

**Comment by GoogleFrog** [comment]
Attach infolog.

**Comment by abma** [comment]
sorry, spring doesn't currently on linux for me.

on windows i get the same errors with ati drivers:

http://paste.springfiles.com/view/raw/b788e744

**Comment by sprunk** [comment]
@abma there have been some shader fixes since, it would be appreciated if you tried to reproduce now.

**Comment by abma** [comment]
seems better:
http://paste.springfiles.com/view/raw/b521140e

[f=-000001] Loaded widget:  Chili Global Commands  <gui_chili_global_commands.lua>
[f=-000001] Warning: [OPENGL_DEBUG] id=2000 source=SHADER_COMPILER type=ERROR severity=HIGH msg="glCompileShader failed to compile a GLSL shader with the following shader info log: 'Vertex shader failed to compile with the following errors:
ERROR: 0:18: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:19: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:28: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:29: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:31: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:34: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: error(#273) 6 compilation errors.  No code generated

'"
