### ISSUE TITLE
Error: [GetSolidObjectDecalType] Could not load object-decal from file "unittextures/"

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K#2300]
Error: [GetSolidObjectDecalType] Could not load object-decal from file "unittextures/"
[f=0007330] Error: [GetSolidObjectDecalType] Could not load object-decal from file "unittextures/turretsunlance_decal.dds"

to reproduce: /cheat + /give all

**Comment by GoogleFrog** [comment]
Is that one error? What does infolog look like?

**Comment by sprunk** [comment]
+ 68f5501e6fe70e8be58688eac1499364f7cff2ba
