### ISSUE TITLE
lua mem leaking after /give all

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K#2301]
when i type /cheat + /give all it seems lua memory is leaking:

FPS drops to 1 (debug build) and lua memory usage increases ~3MB per second until the luaui gets killed by spring because it hits the 800MB limit.

**Comment by GoogleFrog** [comment]
Works for, I'm looking at "[7] Lua-allocated memory" in debug view. It fluctuates around 70MB to 90 MB as various things explode and settles down to 67MB.

**Comment by abma** [comment]
i tried with a release build: there i didn't hit the limit but i got peak lua memory usage of 400MB or so.

i guess its heavily bound to low fps / high cpu load.

**Comment by GoogleFrog** [comment]
Perhaps this occurs only on Linux. See: https://zero-k.info/Forum/Thread/24254

**Comment by sprunk** [comment]
spring/spring@95cd496c
