### ISSUE TITLE
Suspicious commander category

### ISSUE THREAD

**Issue by rlcevg** [ZeroK-RTS/Zero-K#2309]
Commanders have next category:
```land, mobile, terraform, stupidtarget, mine```

Can someone explain what ```terraform, stupidtarget, mine``` is doing here? Why not give those categories to any heavy unit?

I'm interested because it breaks CircuitAI logic, by making commanders look stupidtargets.

**Comment by sprunk** [comment]
Which commanders? Any?

**Comment by rlcevg** [comment]
Strike comm lvl0++ for sure. I'll test others.

**Comment by GoogleFrog** [comment]
What is a 'next category'? Have you checked that all units do not have that category according to the AI interface? I can't see anything that would set those categories for commanders.

**Comment by sprunk** [comment]
I ran this code:
```
for id, ud in pairs(UnitDefs) do
	Spring.Echo(ud.name)
	for cat, value in pairs(ud.springCategories) do
		Spring.Echo("\t" .. cat)
	end
end
```

and commanders are listed as having LAND and MOBILE. Only terraunit has TERRAFORM, only Claw has MINE.

Possibly engine sends them wrong to AI somehow?

**Comment by rlcevg** [comment]
Now i look stupid. **Sorry**. I shouldn't work with code so late and I misinterpreted call to CircuitAI function by engine API call. The bug is in CircuitAI.
