### ISSUE TITLE
Crash when internet disconnects

### ISSUE THREAD

**Issue by Fortnox** [ZeroK-RTS/Zero-K#2312]
My internet sometimes disconnects intermittently. Tonight I was playing a single-player game against bots and the game crashed the moment my internet disconnected. Infolog here: https://pastebin.com/dmjqjxae

**Comment by GoogleFrog** [comment]
Is this the right infolog? It looks like an ordinary exit.

**Comment by Fortnox** [comment]
Is the infolog per session & overwrites previous ones? If so I've lost the previous one because I launched the game shortly afterwards. I'll see if I can recreate the problem or if it happens again soon.

**Comment by sprunk** [comment]
Infolog is per lobby session, yes.

**Comment by Fortnox** [comment]
Sorry, forgot to update. I have intentionally tried to recreate by disconnecting wifi without any success. It may be situational or something else may have occurred. Since I don't have the log you may want to close. If it happens again I'll grab the log and raise another issue.
