### ISSUE TITLE
Constructors on default factory assist should count as idle

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2314]
If a factory has "Auto Assist" turned on, newly-built constructors that are guarding the factory should still be counted as idle if they have not received any further orders. They should be included in the count of idle constructors in the Core Selector widget, and pressing the "select an idle builder" button or hotkey should cycle through them along with the other idle constructors.

This should not apply to any units that have been given an explicit Guard order, only those still acting on the implicit Guard order given by the factory.

**Comment by Aquanim** [comment]
Personally I use that toggle exceptionally rarely but I would enquire with people who do make frequent use of it before making this change.

**Comment by Licho1** [comment]
I think they should not be idle. Idle are units which complted they order.
So for example units that finished factory queue command and are sitting still.

**Comment by CrazyEddieTK** [comment]
If you have Auto Assist turned on, constructors will never finish the factory queue command and will never become idle.

IMO the main reason to use Auto Assist is not to have all of your constructors assisting the factory, but rather:
 - To prevent them from marching to the front lines with the rest of your army, and
 - To make sure they're doing something useful while they're hanging around in your base waiting for you to task them with something more important (like construction)

The second of these would be easier to accomplish if they could be selected with Z (select-an-idle-builder) while they're hanging around, even though they're technically not idle.

**Comment by Licho1** [comment]
I think its too hacky to treat unit with ongoing order as "idle". After all what if you wanted to keep 5 cons assisting it.. 
You would then need to skip all 5 of them.
Imo it should stay as it is.
If you want temporary assist you can also use fight command.

**Comment by CrazyEddieTK** [comment]
If you want to keep them assisting the factory you can give them an explicit Guard order, and then they won't be counted as idle. Only the initial implicit order given by the Auto Assist configuration setting would be considered "idle".

**Comment by Licho1** [comment]
Likewise you can also NOT enable auto assist or use fight command for this purpose.
This would mean you can simply select non con units produced by factory (either using the new hierarchical box select or autogroup).

Making exception to idle seems very silly to me.

**Comment by GoogleFrog** [comment]
I disagree with everything @CrazyEddieTK said in this ticket.

**Comment by sprunk** [comment]
How about a toggle for core selector? "Treat autoassisting cons as idle", default off.

**Comment by CrazyEddieTK** [comment]
Reopening in hopes someone will find a toggle acceptable.

**Comment by Licho1** [comment]
My policy towards requests with which main devs disagree is - close ticket and if people are interested enough they will make PR ... otherwise its ticket creep leading to feature creep leading to bug report creep leading to ticket creep leading to ..

**Comment by CrazyEddieTK** [comment]
Will put on my personal list to PR eventually.
