### ISSUE TITLE
AI-only teams should resign when they've lost

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2315]
When the "overwhelming economic advantage" is triggered, all ZK-supported skirmish AIs should recognize the event and offer to resign (if and only if their team contains only AIs). If the winning team is a single player, they should be shown a dialog box to accept or decline the offer. If the winning team has multiple players, the game should spawn a vote: "Accept opponent's resignation offer?".

Declining or ignoring the offer does nothing, giving the human players the fun of totally annihilating their enemy. Accepting the offer causes every opposing AI to resign, sparing the human players the tedium of hunting down every last solar and Razor.

**Comment by mtroyka** [comment]
that requires a gadget to allow AIs to resign, although it would conveniently allow for offloading the resign behavior to the game rather than implementing it in the ai (which btw fails to work in mixed-ai or mixed-ai-host teams).

**Comment by Anarchid** [comment]
> that requires a gadget to allow AIs to resign

A CallRules for an AI to voluntarily resign (rather than self-destruct all units or some such) does not sound complicated.

**Comment by CrazyEddieTK** [comment]
> i also kind of like different AIs have different resignation conditions as parts of their personality

From a user perspective, you want all the AIs to resign together or you want none of them to resign. So if there are different AIs on the enemy team, there needs to be some rule by which the joint team resignation condition can be identified.

Perhaps this: "If > 50% of the AIs on an AI-only team are prepared to resign, the team resign is offered. If the humans accept, all AIs resign, regardless of their individual conditions." That would mimic the human-based !voteresign.

If the resign offer is declined the AIs all continue fighting until the end, regardless of their individual resign conditions. AIs should play according to the preferences of the humans.

**Comment by Anarchid** [comment]
What happens when the AI is on a player team?

**Comment by mtroyka** [comment]
This also poses a problem for merged ais, since ais which have merged will never resign (since they own nothing and get no messages about ally activities). If ais merge by resigning then more than half of the ais are likely to resign at the start of the game which would trigger a resign vote against that team.

**Comment by CrazyEddieTK** [comment]
> What happens when the AI is on a player team?

If you mean on the same allyteam as human players: AIs that are on the same side as humans should never resign. And, of course, they should not get a vote in !voteresign (which, of course, they do not currently).

> This also poses a problem for merged ais

If an AI merges and can no longer determine whether or not its normal unmerged resign condition would be met, then it should show its resignation status as "abstain". If > 50% of _non-abstaining_ AIs show their status as "resign", or if there are no non-abstaining AIs, then the team resign should be offered.

**Comment by Anarchid** [comment]
> ais which have merged will never resign (since they own nothing and get no messages about ally activities

They can resign, or vote for resign on command of their master.

**Comment by GoogleFrog** [comment]
Gadgets don't need any external help in causing arbitrary teams to resign. AIs need not know about this.

**Comment by mtroyka** [comment]
>They can resign, or vote for resign, on command of their chosen master instance.

Not possible. The ai framework does not actually support AIs sending commands to one another. Merging as-is is accomplished entirely implicitly using player IDs and reading the startscript. There's no active coordination involved.

**Comment by Anarchid** [comment]
> Not possible.

Would it be useful to have an ai intercom function? Something like AI1 -> CallRules -> LuaRules -> SkirmishAIMessage -> AI2?

**Comment by CrazyEddieTK** [comment]
> Gadgets don't need any external help in causing arbitrary teams to resign. AIs need not know about this.

Simply forcing an all-AI team to resign when the overwhelming advantage condition is reached is a good idea and should be easy to do.

This would be especially helpful to new players. They tend to play against AIs, and hunting down Razors is annoying. A new player might not even notice that there's a lone Defender or Solar tucked away in the corner, even with the globallos enabled, and they'd just be confused and frustrated that the game is still going even though they've won.

I'd add this to the release milestones.

My original suggestion about offering a resignation and allowing the humans to accept or reject is more complicated than necessary and doesn't really add any value. The overwhelming-advantage point is a good place to end the game no matter what; the humans will have had a chance to stomp all over the AI base and blow up most of what's there, so there's no need to give them the option to wander across the map rounding up all the strays.

Allowing AIs to determine their own resign conditions should be considered a separate feature request. AI authors who want this should open a new issue.

**Comment by GoogleFrog** [comment]
I don't think it is good to do on overwhelming advantage. This can often be triggered by completing a superweapon and it would be a bit poor for the AI to resign just as the player has their superweapon. People like to mess around.

I would make AIs resign when they have no constructors or factories.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/95928fb3371141dffd923adcbf30a41d6ccee88a.
