### ISSUE TITLE
Widget Request - Temporary Auto Assist

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2318]
I'd like a widget which does the following:

 - Detects when the following two actions take place within close proximity (say, two seconds):
    - Auto Assist is turned on for a factory, having been off previously
    - One or more constructors are added to the front of the factory's build queue
  - Turns Auto Assist back off when the last of the added constructors is built

The scenario in which I'd like to use such a widget: Auto Assist is off and constructors are being sent to the front lines, but I need additional constructors in the base. Select the factory, turn on Auto Assist, and alt-queue the constructors I need. Once they're done, any other constructors that get built will be sent to the front lines as before while the ones I alt-queued will stay in the base.

This widget would save a small amount of micromanagement of having to remember to reselect the factory and re-disable Auto Assist before any other constructors are built.

**Comment by GoogleFrog** [comment]
With that UI I don't want to support such a widget. It sounds too obscure and hard to tell what is going on.

**Comment by sprunk** [comment]
Coredev disagreement -> closing.

Reopen if you come up with a significantly better UI.

**Comment by GoogleFrog** [comment]
I'm not supporting the widget in the sense that I don't want it enabled or to put forth any work to integrate it into integral menu. Usually widget requests like this are solved by the requester writing their own widget then possibly cleaning it up and making a PR.
