### ISSUE TITLE
0 storage means metal flow algo goes bugged and you almos hae no resources flowing to build damn storage sigh

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2319]
Rant in #zk:

>[niktu] whoever bright idea was that lossing com cripples your resource usage (because 0 storage) should be flogged
>[niktu] teh problem is 0 storage means metal flow algo goes bugged and you almos hae no resources flowing to build damn storage
>[niktu] and the more resource flow you have, the more minimal storage you need to mage priority/team flow resurce to work ok ...  if you have fac or two stalling almost completly just because you lost your com lategame, this is damn bug and inability to build storage in few seconds, even thou you have more than enough mexes, is frigging game bug
>[niktu] if your resource priority/whatever engine completly bugs out on 0 storage, you give player minimal storage that makes it work, until you fix problem other way
>[niktu] i'm not gonna mention that it cripples peopel ability to get decent stealth base rebuild in FFA games, so it has more impact there
>[DeinÜberwachenderFreund] you get hidden 5 storage
>[Skasi] niktu just build a storage duh
>[Skasi] it's not that hard
>[Skasi] do it 5m into the game and you should be fine usually
>[niktu] with 0 storage it IS actually hard
>[niktu] especially when you have cons, facs building all over teh map and prioritisation is brainded because of lack of storage
>[Skasi] @DeinÜberwachenderFreund really? I thought you got 0 storage, but that all income could still be spent perfectly provided you have the builtpower (and vice versa)
>[niktu] if you have NOTHING else goin on, it seems like you have very little usable metal flow to build storage (bugs), which gets even worse if anything else happens on map that tries to build/repair
>[Skasi] SO BUILD A STORAGE
>[niktu] so no, "just build a storage" doesnt work as well as you think it should
>[niktu] waiting a minute till your thortled storage is built, when you shoudl have it up in seconds (because you use 2 cons, and have plenty enough of mexes), while freezing your repair/terrra/build capabilities for that time  is NOT ok in my book
>[Skasi] it's 100 frikkin metal.. that's basically an LLT
>[niktu] skasi, dammit, its not fuking case of amount of metal .. its case of "no matet rhow many mexes you have, your buildpower gets cut down to 1 to 1.5, good luck finishing that fucking storage before enemy finishes you"
>[niktu] ... try to loose all you storage and com and build storage, and then tell me how easy it is
>[niktu] ... try to go though all map and stop all your cons and nanos repairing /doing whatever, just so you have that LIMITED, BUG RIDDEN BP, so you can actually finish that damn cheap storage
>[niktu] ... and god have mercy on your sould if you have any unit/building actually using energy (shields/cloacks)
>[Skasi] why would I? I don't need to try that
>[Skasi] also, protip: priority button
>[niktu] if FUCKING proprity woudl work in this situation i wouldnt be ranting
>[niktu] but i guess you have no idea that priority algo gets fucking out of window when it doesnt have enough storage to work properly sigh

**Comment by CrazyEddieTK** [comment]
Perhaps constructors/facs/mexes should have storage equal to one or two seconds of their income?

... base income only, not including overdrive.

**Comment by DeinFreund** [comment]
It is indeed a major nerf to the viability of FFA comebacks. One used to be able to reclaim metal in order to rebuild mexes, now one has to first wait 5-8 minutes to finish a storage at 0.2 income.

**Comment by Anarchid** [comment]
Hide storages in Norway if you expect to be pwned.

**Comment by sprunk** [comment]
The last two posts are irrelevant to this ticket.

**Comment by GoogleFrog** [comment]
As far as I am aware construction works at zero storage. I require a replay to be motivated to do anything for this quality of ticket.

**Comment by DeinFreund** [comment]
It's not exactly clear to me what this is about. By using proper priority, one can still have his full income available in 1v1. In team games I'm not sure whether receiving energy from allies works without storage, as it's already unreliable when having storage.

Besides actual bugs, I think the complaints are mostly caused by the actual removal of storage. While it might seem like the game is about resource flow, central mechanics like reclaim and constructors aren't optimized for it. Workers need the ability to access metal in batches between movement, reclaim would require an overly expensive buildpower overhead to work.

**Comment by sprunk** [comment]
This ticket is not about having 0 storage by itself.

It's about being unable to spend your income at 0 storage, which would be a bug (since you're supposed to be able to).

**Comment by DeinFreund** [comment]
I don't think it's a bug, but it's just incredibly annoying to give wait commands to all builders. Priorities have been a little unreliable without reserve storage. Is this about priorities then?

**Comment by sprunk** [comment]
Possibly. Priorities are supposed to work even at 0 storage. The ranting dude says he knows about priority (see 2nd and 3rd line from the end) but I wouldn't fully trust that - there is no information whether the limited BP affects only his high-prio storage or everything else, so there is the chance that he misused priority (or some other factors were in play, eg lacking energy).

As Googlefrog said this ticket is not really actable upon unless someone imparts a replay.

**Comment by GoogleFrog** [comment]
Read the ticket please.

**Comment by CrazyEddieTK** [comment]
Has anyone tested building and priorities with 0 storage lately?

Also, off-topic, but - @DeinFreund:

> One used to be able to reclaim metal in order to rebuild mexes, now one has to first wait 5-8 minutes to finish a storage at 0.2 income.

If things are in fact working correctly, you should be able to build a storage (or anything else) using reclaim, even at zero storage. Put two constructors on reclaim, you'll get a max income of 10 m/s. Put two more constructors on construction, you'll have 10 buildpower and won't waste anything due to lack of storage. Ten seconds later your new storage is done.

If this isn't working for you, then perhaps construction at zero storage really is bugged. Someone should test to confirm one way or the other.

**Comment by sprunk** [comment]
>[niktu] http://zero-k.info/Battles/Detail/460375
>[niktu] also has zero-storage priority problem in about 5-6 mins in teh game (i put notification)
>[niktu] i had 4 income, fac on low priority, and building sotrage at high or medium priority ... flow to storage was about 1.4 instead 4

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/b4b3f328bfb8ad945d29fdf514fa810b8ad2f054.
