### ISSUE TITLE
Unit info takes a while to show on mouseover

### ISSUE THREAD

**Issue by SpongeTheGlaive** [ZeroK-RTS/Zero-K#232]
When moving your cursor over a unit the information for that unit takes a second to display. This can be quite inconvenient when checking things like exact unit health in the heat of battle.

**Comment by Orfelius** [comment]
Wasnt' it fixed? Mayby close then?

**Comment by Skasi** [comment]
No this was not fixed. Fix would be:
"Fix tooltip delay to be based on what is underneath the mouse cursor instead of checking whether the cursor is perfectly still."

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/d79903a1c2475faf632fd32f7c614e1e31e16c0c
