### ISSUE TITLE
Strikecom pregame marker renders in dismembered state

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2321]
This is probably because the recent engine changed options for the way assimp Collada (.dae) models are rendered in bind pose. 

Fortunately it doesn't seem to break animations, or the model after Create.

**Comment by Anarchid** [comment]
Likely cause: https://github.com/spring/spring/commit/b61915b575046ec71eb1c33cebae6bdb9dc79b5f

**Comment by sprunk** [comment]
.dae caught me slippin

**Comment by sprunk** [comment]
These .dae buildings might be affected as well, through blueprint and ghost site: Gauss, Starlight, Basic Geo.

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/7d99d7c4242678cb37c51c5cad75941fc31a242c
