### ISSUE TITLE
game freezes every now and then

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#2324]
not only for me, game freezes with current engine (two versions ago too)
103.0.1-1048-g97abd14
Zero-K v1.5.6.5

It has nothing to do when debug messages appear in F8. Sometimes yes, but sometimes it freezes anyways for a short moment

**Comment by sprunk** [comment]
infolog?

**Comment by Jamanno** [comment]
https://pastebin.com/vWcYPByd
http://zero-k.info/Battles/Detail/460364
I picked up some timestamps when I paid attention, there can occur other freezes because I did not watch all the time:
The freezes happen even when I put off minimap, zoom in to only water or zoom in to only one windgen or whatever. Also they appear when I use chobby or flobby or minimal settings or ultra settings.

``
3:44
3:55
4:16
4:44
4:52
5:09
5:47
16:23
20:19
``

How would I post my springsettings.cfg which are actually used ingame?

**Comment by Jamanno** [comment]
wait. I see that on youtube as well. Let me figure out the graphics card settings before.

**Comment by GoogleFrog** [comment]
Apparently this is a battle in which it occurs for niktu http://zero-k.info/Battles/Detail/460375

**Comment by GoogleFrog** [comment]
Do you see the freeze issue when watching replays? How likely is it that many people have poor graphics settings?

**Comment by Jamanno** [comment]
I reinstalled my graphics card driver after purging it completely and now it works without freezes. But I cannot really tell for others since I have i7 maybe they get the lags because of unsatisfied hardware specs?

**Comment by sprunk** [comment]
Graphics driver issue.
