### ISSUE TITLE
Selections: consider showing more info

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2325]
With multiple units selected, the only shown information is health and dgun reload (as bars). A unit can be fairly crippled despite having full health so consider whether it would be good to show more info:

 * very long reload weapons such as Penetrator (if DGuns have a bar these might as well)
 * shield (another form of health, possibly the more important one for shieldball. Ideally somehow shown on main health bar, like protoss)
 * emp/disarm state (blue/yellow tint?)
 * armor state (as an icon, or white tint? see also #2066)
 * cloak state (transparency? gray tint?)
 * has transportiee state (icon? quarter size buildpic? see also #1983)
 * drone count for carriers (direct measure of carrier combat capability. numerical X/Y? bar?)

A drawback is that the icons are fairly small so adding stuff would potentially make them cramped.

**Comment by CrazyEddieTK** [comment]
The bars can be made thinner, perhaps even to the point of being merely thick lines.

**Comment by Licho1** [comment]
I think that shields are self explanatory with color - same with armored state (unit anim).
I would be worried overloading the user with thousand meaningless bars.

**Comment by sprunk** [comment]
They're self-explanatory if you're looking at the units inworld but you can have units selected in multiple places or be zoomed out.

Selection gives a nice overview of your units in one place regardless of how they are located inworld.

**Comment by mtroyka** [comment]
That only works if you don't have so many units/unit types selected that they get combined into stacks. When that happens per-unit data is no longer meaningful and any group data is pretty misleading at best.

**Comment by sprunk** [comment]
Sure, that also affects the existing health and reload bars.

**Comment by Anarchid** [comment]
Group data can be meaningful fore health and reload. For health, it can either show average health, or the proportion of units by color-coded health cohorts. For reload, it could show the share of units that are currently armed.

**Comment by sprunk** [comment]
Duplicate of #2676
