### ISSUE TITLE
Awful performance in team games

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2334]
I was having about 5 fps with regular drops to 1 during the whole game: http://zero-k.info/Battles/Detail/460868

The same for other games of the same playercount as well.

![1](https://i.imgur.com/mHMx9rw.jpg)
![2](https://i.imgur.com/YHBioF8.jpg)

**Comment by Anarchid** [comment]
Is this on an intel gpu?

**Comment by DeinFreund** [comment]
Nvidia. Over- or underclocking doesn't even measurably affect fps, because the load is minimal.

**Comment by DeinFreund** [comment]
But good call, I just noticed my intel cpu was no longer going above 2 ghz for some reason(Fixed by a restart). Still, my cpu maxes out at 3.2 ghz, so this would only be a negligible 50%(2-3fps) improvement. This game should really run a lot faster. There's also the hardware trend of going towards high core count low clock rate CPUs like ryzen or i9.

If you can see some troublemakers from these screenshots it'd be nice to know. For example the particle system is something I'd expect to offload most work onto the GPU.

**Comment by GoogleFrog** [comment]
@DeinFreund is an outlier here. What happens if you run the replay?

**Comment by DeinFreund** [comment]
Debugscreens: https://imgur.com/a/VigsK
Uncompressed images: http://www.mediafire.com/file/qcvxxh5dufj3kdd/temp.zip

The replay runs at ~15 fps now. A lot smoother but still far from enjoyable for microing units. I'm not so sure how to read these debug screens, so what is the major offender here? 

It looks like Draw is using 50% of the frame time. Is this caused by a slow CPU, too much geometry, too many objects on screen or a general Spring problem with many units?

**Comment by Topkack** [comment]
can confirm, happens sometimes

do you run factory panel by any chance?

**Comment by GoogleFrog** [comment]
Create a new ticket if this occurs.
