### ISSUE TITLE
Freeze on selection

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2336]
The player izirayd has an issue in which the game freezes on unit selection. They show the issue in these two videos:
 * https://www.youtube.com/watch?v=0raf2Nn__Wk
 * https://www.youtube.com/watch?v=sVCKrpKEcMc

Commenting on the video should be a way to gather feedback. The second video shows the lua memory usage jump by 20MB when the commander is selected, probably because the old selections widget is awful. Their memory usage quickly drops by 20MB so perhaps they are memory limited so some expensive and thorough GC is occurring. My rewrite has been targeted at issues such as these so I will first make a stable and ask them to re-test.

I can't reproduce a 20MB memory usage jump upon unit selection with the old widget. They also have an old UI so possibly have some broken widget enabled.

My other idea is that loading/playing the unit selection sound causes the freeze. However it appears to occur with multiple different selection sounds and the order confirmation sounds are unaffected.

**Comment by oriongame** [comment]
Hello, if you need help with emulate its bug, i help you

**Comment by GoogleFrog** [comment]
Help would be appreciated. cleanrock reported this issue as well and found that it was fixed by disabling the old selections widget. I'll hard-disable the old widget and hard-enable the new one because apparently the switch between the widgets was not perfect.

**Comment by oriongame** [comment]
Bug fixed, good work Frog :)
