### ISSUE TITLE
Process latest maps

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2338]
TheYak released some new map updates. They should be applied.

http://zero-k.info/Maps/Detail/56105
http://zero-k.info/Maps/Detail/56106
http://zero-k.info/Maps/Detail/56104
http://zero-k.info/Maps/Detail/56103
http://zero-k.info/Maps/Detail/56107

**Comment by GoogleFrog** [comment]
Related: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1747

**Comment by The-Yak** [comment]
Intersection, Trojan hills, Titan, Red Comet could be added to this list as well.
http://zero-k.info/Maps/Detail/55922
http://zero-k.info/Maps/Detail/55923
http://zero-k.info/Maps/Detail/55932
http://zero-k.info/Maps/Detail/55928

**Comment by GoogleFrog** [comment]
@DeinFreund the MM workflow involves making sure that infrastructure will actually pick up on the changes to which maps are featured.

**Comment by DeinFreund** [comment]
That's why I asked. I heard it needs a server or even lobby deploy. Could you write a short description or is it going to change again soon? I could make a PR to add the description to the map featuring interface.

**Comment by GoogleFrog** [comment]
A short description of what? The ticket is "figure out how to update MM maps and then implement it" and for me neither of these are complete.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/1777

**Comment by sprunk** [comment]
Done, needs Chobby minimaps now.
