### ISSUE TITLE
pathing is broken

### ISSUE THREAD

**Issue by LogicDaemon** [ZeroK-RTS/Zero-K#2339]
this game http://zero-k.info/Battles/Detail/461034
warlord didn't respond to move commands, roamed on its own (near battle end)

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1100334/infolog.txt)

[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K/files/1100333/infolog_full.txt)

**Comment by GoogleFrog** [comment]
Infolog is good but for a pathing problem I need different information. Ideally a link to a battle replay with exact position, time and unit description.

**Comment by LogicDaemon** [comment]
edited

**Comment by GoogleFrog** [comment]
I don't know when the battle is going to end before I watch the replay. I don't know which warlord. I need the time to within 10 seconds and the position to within 300 elmos. Hold space to see the coordinate of a position.

**Comment by GoogleFrog** [comment]
@LogicDaemon

**Comment by LogicDaemon** [comment]
I've seen your comment, sry, didn't have time yet to watch the replay. Will
do soon.

**Comment by LogicDaemon** [comment]
okay, game time is 24:13.
After watching the replay I see why Warlord it moved that weirdly – shallow water. There were some erratic Reef movements too, but that's known and expected, so no problem there.

Sorry for panicking.

**Comment by sprunk** [comment]
It's probably still an issue if units can get into such bad areas in the first place but I guess that's a nontrivial engine problem.
