### ISSUE TITLE
Zero-K running slow on Debian 8

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K#2340]
32 GB of RAM and 4GB of vram, but the game gave me an error reporting it saw 1GB of vram or less. I am running on a RX470 and an Ivy Bridge Core i5

`sudo dmesg | grep drm > drm.txt`
[drm.txt](https://github.com/ZeroK-RTS/Zero-K/files/1100372/drm.txt)

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1100376/infolog.txt)

**Comment by DeinFreund** [comment]
There's a problem with the drivers/GPU detection. Here's what your infolog reports:
```
	SDL version : 2.0.2 (linked) / 2.0.1 (compiled)
	GL version  : 3.0 Mesa 10.3.2
	GL vendor   : VMware, Inc.
	GL renderer : Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
	GLSL version: 1.30
	GLEW version: 1.9.0
```
The Rx470 should be OpenGL 4.5 and have some reference to ATI in is vendor string. Any idea what might be causing VMware to show up? You're not running some kind of virtualization are you?

Have you installed AMD drivers?

**Comment by Oflameo** [comment]
I had to build a new Kernel to get the new Mesa driver so the Rx470 would actually work on Debian 8. My best bet is that something in a newer X11 server was also needed to make the hardware work to its fullest potential and the VMWare is a default that is filled in when the system doesn't really know.

My in place OS upgrade is taking forever to calculate the conflicts, so I am going to have to rebuild my OS. If Zero-K runs well on Debian 9, which is the freshly released current stable, you can just tell everyone to upgrade their OS to solve the problem.

**Comment by let4be** [comment]
can we already remove this stupid warning from engine?
Each time I start up a chobby I also get this warning because guess what...
chobby uses spring

**Comment by Oflameo** [comment]
Someone remove the old error. Now it is clearly misidentifying my drivers as virtual.

**Comment by GoogleFrog** [comment]
Engine devs indicate that your system is misconfigured. https://springrts.com/mantis/view.php?id=5626

**Comment by Oflameo** [comment]
I have Debian 9 installed and now it is preforming even worse. Now it crashes outright. I did remember to install mono, sdl and opencl as directed by these instructions https://zero-k.info/Wiki/Download. 
[drm.txt](https://github.com/ZeroK-RTS/Zero-K/files/1117372/drm.txt) I ran dmesg | grep drm > drm.txt as root, because my system is so fresh I didn't configure sudo yet. Also, here is infolog again. 
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1117375/infolog.txt)

**Comment by Oflameo** [comment]
I figured out something I could do that may help. I did a `strace` of the process while it is starting and failing. 
[strace.txt](https://github.com/ZeroK-RTS/Zero-K/files/1122934/strace.txt)

**Comment by sprunk** [comment]
The engine ticket has already been closed with the following comment:

>Oflameo is using *vmware* mesa GL drivers outside of a VM, while running an RX470 GPU released last year. This seems like a system misconfiguration and it confuses Spring.

**Comment by Oflameo** [comment]
@sprunk, Look at the Debian 9 drm.txt. 
```

[    5.607447] [drm] initializing kernel modesetting (POLARIS10 0x1002:0x67DF 0x1682:0x9470 0xCF).
[    5.860691] [drm] RAM width 256bits GDDR5
[    5.860702] [drm] amdgpu: 4096M of VRAM memory ready
[    5.860703] [drm] amdgpu: 16032M of GTT memory ready

```
I agreed with @GoogleFrog off ticket to try installing Debian 9 and see if it resolved the issue. It is actually worse when I am clearly using POLARIS10 https://en.wikipedia.org/wiki/AMD_Radeon_400_series now and I can no longer play the game. Are you saying that I should open a new ticket here, a new ticket there, or that the POLARIS10 driver is not for https://en.wikipedia.org/wiki/AMD_Radeon_400_series, but for VMvare?

**Comment by sprunk** [comment]
I think what the engine dev said is that this driver is for VMware. Best to make a mantis ticket I think, ZK itself can't really do anything.

**Comment by Oflameo** [comment]
I am not sure either way. @GoogleFrog would know better than me, but he will be way more busy than me in general so I should try to handle it without him. I am going to try the Distro's version of spring and then vanilla spring and see if anything different happens then I will open a ticket based on what the source seems like.

**Comment by sprunk** [comment]
Mantised https://springrts.com/mantis/view.php?id=5634
