### ISSUE TITLE
Selection boxes terminating in chili elements sometimes end up selecting nothing

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2342]
I drag this kind of selection box and release the mouse button.
![image](https://user-images.githubusercontent.com/3822768/27517969-f98d5a62-59dd-11e7-927d-6497908339c9.png)

Briefly, every unit in the box appears in selections. Then, in some cases, it disappears completely; in other cases a single flea ends up selected. 

This is not related to selections hierarchy because disabling that widget maintains the behaviour. It does not seem to happen when no chili element is clipped (e.g. if i draw the selection box upwards rather than downwards).

**Comment by GoogleFrog** [comment]
All chili elements or just when your mouse release is on a button?

**Comment by Anarchid** [comment]
It doesnt always happen when i mouseup on selections, so button is more likely. Possibly the case where one flea is left selected is mouseup on a flea unitpic?

**Comment by sprunk** [comment]
Anarchid said something that sounded relevant:

>also remember my "unplayable broken box selects". So that's mouse pointer bouncing
>unsure if should hack OS to have debounce, or to hax new mouse
>mousedown-mouseup causes two click events instead of one due to sensor being made out of physics
>usually compensated on hardware level, but entropy accumulation causes bounce delay to increase and hardware is hardwired to a specific bounce suppression threshold

Looks like not a ZK issue.

**Comment by Anarchid** [comment]
This doesn't seem to affect anyone else and also happens in other software. So i'm pretty certain it's click bounce.
