### ISSUE TITLE
Set dev engine 1134

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2347]
I built the engines but ran out of time to test and apply them. Generally the process involves running an AI game and then being available for the next 4 or 5 hours to set the engine back if it is broken. If it is not done I will likely do it on the weekend.

This particular engine is required because other engines won't work for 45% of our playerbase. It is here https://springrts.com/dl/buildbot/default/develop/103.0.1-1134-gbe1c786/

**Comment by DeinFreund** [comment]
Seems to run well enough.

**Comment by GoogleFrog** [comment]
Done.
