### ISSUE TITLE
Setting factory priority and plane landing behaviour under Unit Behaviours (default states) doesnt work

### ISSUE THREAD

**Issue by Topkack** [ZeroK-RTS/Zero-K#2348]
facs stay on normal and planes dont land

**Comment by KingRaptor** [comment]
My observations:
* Factory land/fly state works
* Unit land/fly doesn't inherit from factories (always lands)
    * Non-inherit initial states work
* Factory nanoframe build priority works
* Factory constructor build priority doesn't inherit from builder (always high priority)
    * Non-inherit initial states work

I'll take a look at the issues I identified. If you're getting different results than the above, please provide instructions to reproduce.

**Comment by GoogleFrog** [comment]
Build priority is not supposed to inherit from factory.

**Comment by KingRaptor** [comment]
I've fixed all the sub-issues I found/was informed of. Reopen if any more are found.
