### ISSUE TITLE
Zero-k loading screen sometimes looks weird

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2350]
![image](http://i.imgur.com/cg2Zj6G.png)

if u're into blue:
![wtf](http://i.imgur.com/gzgYFWz.png)

related:
https://github.com/ZeroK-RTS/Chobby/issues/273

I'm seeing this only when playing from notebook(integrated video on i7 7500u)
so far no issues ingame, just those glitches with loading window and chobby

**Comment by DeinFreund** [comment]
Looks better than default loading screens imo.

**Comment by let4be** [comment]
Looks like a highway to nowhere, - pretty much about zk development

**Comment by GoogleFrog** [comment]
Infolog.

**Comment by GoogleFrog** [comment]
I don't think you have enough vram for chobby and a load screen.

**Comment by let4be** [comment]
This one is from notebook with intel cpu/gpu, for video it always uses the system ram (16 gb)
I'm pretty sure system has more than enough ram

**Comment by sprunk** [comment]
I don't think there's anything ZK can do. Possibly Chobby could.

**Comment by let4be** [comment]
but I wasn't low on vram, integrated video has WHOLE system ram available and there were more than enough of those...
