### ISSUE TITLE
Accomodate changed shield visuals

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2352]
Something in the engine between 103-1048 and 103-1134 seems to have changed shield visuals. This should be investigated. Modifications to shield colours may be required or maybe it is worth a report.

**Comment by sprunk** [comment]
Shields now take `r g b a` instead of `r g b`: https://github.com/spring/spring/commit/216f8bf1b2925d54553db355e2a6ab4018b878ad

Probably posts'able.

**Comment by DeinFreund** [comment]
![visuals](https://i.imgur.com/b0HuiPu.png)
