### ISSUE TITLE
Solars always open after damage wears off, even if they were closed before

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2355]
The open/close gadget overrides any manual input. If you force them close they open again after taking damage, if you open them they close when taking damage. There should be a unitAI toggle to disable this.

**Comment by sprunk** [comment]
>if you open them they close when taking damage

This is intentional. It makes raiding Solars incur some minor economic cost even if they don't die (which is the usual case).

>If you force them close they open again after taking damage

That's bad. The only effect taking damage should have on a closed solar is to prevent manual open during the 8s (it should not open it up at any point).

**Comment by DeinFreund** [comment]
What if you have a 99.9% detri but your solar is force closed causing you to lose? You should have the ability to tell your units what to do.

**Comment by sprunk** [comment]
If you lose because someone closed your solar then it's your fault for not taking Solar closability into account and playing around it (protecting solars, making more, using different generator type, ...).

It's the same as shield link or overdrive - it just happens, you are supposed to play around it.

**Comment by DeinFreund** [comment]
Then why is there a button? An on-off button implies I'm able to control my solars. Shields don't have a link/unlink button.

**Comment by sprunk** [comment]
You can control what state the solar will revert to when the damage block wears off.
