### ISSUE TITLE
Solar on/off button: signal temporary block

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2357]
Solar's on/off toggle button could signal that it won't be responsive during the damage block because apparently people might attempt to open it up and think it's bugged when it doesn't work. See #2355

**Comment by GoogleFrog** [comment]
Maybe the ability to manually on/off Solar should be removed? That, technically, fixes the poor unit AI that solars have at the moment (not closing the frame before they take damage).

**Comment by sprunk** [comment]
Sounds good.
