### ISSUE TITLE
Gravity beams: ground friction exceedingly high

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2359]
They don't seem to obey Newton's laws at all. It's easy to lift up units, but pulling them across straight terrain is impossible.

In http://zero-k.info/Battles/Detail/461645 a Sumo fires both rays at a Firewalker and doesn't move him a bit. (Screenshots to follow)

**Comment by DeinFreund** [comment]
![sumo](https://i.imgur.com/JqRs1HJ.png)

As you can see the sumo had a clear shot but the Firewalker was completely unaffected.

It seems like there is some kind of really strong friction with the ground. Whenever the force vector lies close to flat on the ground, units are near impossible to move, yet they can be flung about when pulling them from above.

**Comment by sprunk** [comment]
I think this has always been the case.

**Comment by DeinFreund** [comment]
The friction coefficient being above unity is rather unintuitive. Would it be possible to change that so that all units that can be lifted up can also be pushed/pulled?

**Comment by sprunk** [comment]
Possible but not easy. You'd need to detach a unit from the ground to overcome friction which has to be done only if the unit would actually be pushable (else newton stops det), but it might be hard to know whether that is the case because engine physics is a black box.

**Comment by DeinFreund** [comment]
> You'd need to detach a unit from the ground to overcome friction

This sounds so (physically) wrong. Without a ground connection there is no more friction, so even heavy units would be helpless as soon as affected by a gravity beam. There should be a force of friction which depends on the ground and unit's mass and allows the unit to move at will and a force applied by the gravity beam. As soon as the gravity beam's force overcomes the friction, the unit starts sliding with the difference of the forces. At the same time it can still move at its normal speed, just while also sliding. Then we can finally moonwalk on MoonQ20x.

Without some way of approximating this, Sumo just feels like a way too random unit. How can we explain it pushing striders twice its weight off the map while also failing to dislodge lightweight support units.

**Comment by sprunk** [comment]
Currently either you're attached to the ground and are unaffected by grav, or are detached at which point can't move on your own at all.

Changing this to make movement the sum of forces sounds like a nightmare though. What about pathing, weapon leading prediction?

**Comment by DeinFreund** [comment]
Pathing just tells the unit where it wants to go, it's up to the unit to apply its method of movement to follow this path. Prediction can also be done by AI and widgets that completely ignore pathfinder, just looking at derivatives of position is all that is needed. A physics engine shouldn't move units via anything other than newton's law (=forces) imo. 

Anyway this isn't how Spring works, so I suppose some kind of workaround via Lua is needed. In the worst case just do it as you proposed and lift up units as soon as their weight times coefficient of friction is smaller than the gravity beam's strength.

**Comment by sprunk** [comment]
>it's up to the unit to apply its method of movement to follow this path

Yes but currently units assume they can only be moving in the direction of their heading (not sideways or at an angle). It would need a complicated engine patch. Ultimately Spring is not a physics engine, it's an RTS engine and the physics are mostly gimmicks.

>just do it as you proposed and lift up units as soon as their weight times coefficient of friction is smaller than the gravity beam's strength

Yes but that is not trivial either. You'd need to reimplement impulse handling in Lua.

**Comment by DeinFreund** [comment]
We could also reposition the beams to be on the top and bottom of sumo instead of the sides. This would make pulling/pushing units easier as they'd be pulled/pushed upwards.

**Comment by sprunk** [comment]
Related: https://github.com/ZeroK-RTS/Zero-K/commit/72f11bf1ade64e5ca540dd2693b51886e1ae6df2

**Comment by sprunk** [comment]
Closing because this ticket is buried, changing engine friction is scary (for leveler reasons), and  #4473 is more useful because in addition to acknowledging the problem it has a specific implementation proposal.
