### ISSUE TITLE
Terraform block creation bug?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2361]
"Terraform bad number detected, SetTooltip, nan" then nothing. A hang?
 * https://github.com/ZeroK-RTS/CrashReports/issues/1448
 * https://github.com/ZeroK-RTS/CrashReports/issues/1449

**Comment by sprunk** [comment]
ZeroK-RTS/CrashReports#2094

**Comment by sprunk** [comment]
Doesn't look actionable, engine 103 and no replay.
