### ISSUE TITLE
Zero-K failing to start on Debian 9

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K#2363]
I have Debian 9 installed and now it is preforming even worse. Now it crashes outright and I never make it into the lobby. I did remember to install mono, sdl and opencl as directed by these instructions https://zero-k.info/Wiki/Download. 
[drm.txt](https://github.com/ZeroK-RTS/Zero-K/files/1117372/drm.txt) I ran `dmesg | grep drm > drm.txt ` Also, here is the new infolog.
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1117375/infolog.txt)
I also have an strace. [strace.txt](https://github.com/ZeroK-RTS/Zero-K/files/1122940/strace.txt)

**Comment by sprunk** [comment]
Same driver as under the previous ticket.

**Comment by Oflameo** [comment]
It must be a spring error because the OS is using POLARIS10 not VMware. Compare the drm with the infolog. Mainline spring's lobby starts just fine. 
[springlobby.log.txt](https://github.com/ZeroK-RTS/Zero-K/files/1125277/springlobby.log.txt)

Where in my OS does it say that I am using VMWare, My DRM makes no reference to VMWare?

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5634
