### ISSUE TITLE
A structure in close to the exit of a factory can block the factory

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2370]
Units that leave factories are automatically given a move order by the engine to just outside the entrance of the factory. This order is inserted before their command queue. If there is a structure on the location of this move order then units will jitter around the structure, never reaching it. This is something I can easily imagine new players doing.

CMD_RAW_MOVE has handling in place to detect and solve move orders that are issued in situations such as these. Perhaps a solution is to replace the engine move command with CMD_RAW_MOVE. Perhaps the engine command can be deleted entirely. Should not be too hard.

**Comment by lhog** [comment]
Maybe also block construction of anything else in tiles that are in front of the factory entrance?

**Comment by GoogleFrog** [comment]
No, not that. Bad UI.

**Comment by sprunk** [comment]
Even if they were normally shown as blocked when placing (like mex spots)?

**Comment by lhog** [comment]
Yept I meant what @sprunk said ^^

**Comment by GoogleFrog** [comment]
What about when you place your factory and there is already a structure in the vital point? What if there is terrain? A blocking feature? In general I don't want there to be configurations that you can only make by building structures in a particular order. The structure building rules should be simple.

**Comment by GoogleFrog** [comment]
To reproduce:
 * Make an East facing shield bot factory.
 * Make an LLT directly in front of the factory with enough space for a Stardust to fit in.
 * Make a Rogue.
