### ISSUE TITLE
These blues are pretty close together

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2374]
![screen00466](https://user-images.githubusercontent.com/1318249/27984897-6efed3fc-6424-11e7-9634-eeedcfcddfe1.jpg)

**Comment by KingRaptor** [comment]
How about this?

![Color preview](http://i.imgur.com/Dx481aP.png)

**Comment by GoogleFrog** [comment]
I don't understand that image.

**Comment by KingRaptor** [comment]
That's from the new [team color previewer](https://github.com/ZeroK-RTS/Zero-K/commit/ebc929d1120fdf04a626c1c15bed920943e8d360). 

I assume the one marked "old" is the problematic one (having too much resemblance to the blues in the second and/or sixth rows); the one marked "new" is my proposed change.

**Comment by GoogleFrog** [comment]
So you have added a new ally colour, the one labelled 'new', and propose to replace the one labelled 'old' with this colour?

**Comment by sprunk** [comment]
KR says yes.

**Comment by sprunk** [comment]
Personally I think the better replacements would be last two colours (with the new one going at the end instead).

**Comment by KingRaptor** [comment]
Decided the color rearrangement is as good an idea as any, implemented with thanks.
