### ISSUE TITLE
Deprecated things in CUS

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2375]
Occurs on all luarules loads.

[f=-000001] [Modular Comm Info] Warning: Modular Comms API warning: Comm data entry for player Player is empty or in invalid format
[f=-000001] Custom Unit Shaders:, 0(32) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(40) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(47) : warning C7533: global function shadow2DProj is deprecated after version 120
0(60) : warning C7533: global variable gl_TexCoord is deprecated after version 120
0(78) : warning C7533: global function textureCube is deprecated after version 120
0(111) : warning C7533: global variable gl_FragColor is deprecated after version 120

[f=-000001] Unsynced LuaRules: finished loading

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/1484

**Comment by sprunk** [comment]
ZeroK-RTS/CrashReports#916
