### ISSUE TITLE
Rockos on fight move don't skirm near multiple enemies

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2376]
In http://zero-k.info/Battles/Detail/462206

After minute 7, when my rockos on fight-move reach the factory, they stay close to it even as the shotgun com approaches and kills them. It's visible during two different assaults, where the rockos stay in the base instead of skirming away from the nearby enemy. Might be caused by them targeting factory or builders.

**Comment by GoogleFrog** [comment]
When units are on fight (ie, with a non-manually given command) their skirm behaviour is written to be based on the nearest enemy. Hopefully this a is a bug in that detection. Otherwise this is Pie In The Sky if you want skirmishers to take multiple enemies into account.

**Comment by GoogleFrog** [comment]
All the failure cases in that replay involve a Solar being the closest unit to the Rocko. They don't skirm Solars so the Rockos don't move.

Currently autoskirm ignores the actual attack command of the Rocko in favour of the closest unit in the case where the attack command was not manually issued. Some simple hax to fix this case would be to use the target of the attack command when the closest unit is a STUPIDTARGET. The harder solution is a more advanced look at all nearby enemies without sacrificing performance. In my experience GetUnitsInCylinder is expensive even for relatively small cylinders.

**Comment by DeinFreund** [comment]
I'd recommend a different distance function. For example CSI does skirmishing by only looking at the armed enemy which has closest (distance - his range).

**Comment by GoogleFrog** [comment]
It's using Spring.GetUnitNearestEnemy. Read above.

> The harder solution is a more advanced look at all nearby enemies without sacrificing performance. In my experience GetUnitsInCylinder is expensive even for relatively small cylinders.

**Comment by DeinFreund** [comment]
How is GetUnitNearestEnemy faster? I would expect both to need the same quadtree lookup for small radii. Could we implement finding the unit to retreat from in spring?

**Comment by DeinFreund** [comment]
Even if this is possible, for the meantime taking the attack target sounds like a good workaround.

**Comment by GoogleFrog** [comment]
Maybe nearest enemy is cached. Maybe it's not faster. All I know is that it is a task to compare them because I have seen the cylinder check be slow in the past.

**Comment by GoogleFrog** [comment]
Easy part done.
