### ISSUE TITLE
Unit Rename Brainstorming

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#2379]
@GoogleFrog wants to finish renaming units to get rid of the remaining OTA names. The goal is to make Zero-K feel like a _new_ game that's a "spiritual successor" to TA (like SupCom, PA, and Ashes) rather than simply a _mod_ of TA. This will be important for the Steam release and concomitant publicity push.

I, GF, @Aquanim, and others have been brainstorming about the renames here: http://etherpad.springrts.com/p/renames

I'm opening a ticket to get greater visibility and encourage participation from the developers and other interested parties (especially @dvr333, who has to say these names out loud more than anyone else). Comments and suggestions are welcome either here or on the etherpad.

**Comment by CrazyEddieTK** [comment]
@GoogleFrog - I think I am done for now, pending further feedback. All the units are covered, I've incorporated everyone's feedback or pushed back with justifications where I thought it appropriate, and where there are multiple viable candidates I've listed my favorites.

I think at this point you need to provide additional feedback, solicit additional input from others, or make some decisions.

If you'd like I can compile all the changes into a single coherent list for easy review, but I'm holding off on that until you give us your opinions on what we have so far.

**Comment by GoogleFrog** [comment]
Thanks, I'll take a look.

**Comment by GoogleFrog** [comment]
Are you going to have a look?

**Comment by Anarchid** [comment]
Suggestion: `Rovers` for LV.

**Comment by CrazyEddieTK** [comment]
Been tied up, will review and add further remarks later today.

**Comment by CrazyEddieTK** [comment]
Provided responses to about two-thirds of the recent comments. More later.

As I've responded, I've moved the comments out of the compiled unit list and into a separate comments section, and marked which units still need further discussion and/or decisions made.

**Comment by CrazyEddieTK** [comment]
Responded to all recent comments, updated status of all units on the master list.

I think you should actively solicit additional input from others, both to provide more feedback on the current proposals and to generate more ideas for names where we still need them.

I encourage anyone reading this ticket to take a look at http://etherpad.springrts.com/p/renames and to offer comments where you think they'd be helpful. Skip to the section about two-thirds of the way down labeled "Provisional Full Renamed List of Units and Factories"; everything above that is early brainstorming and is now effectively superseded.

**Comment by Anarchid** [comment]
I think if you are renaming Light Vehicle Factory to Rover Assembly, the it also makes sense to update unit descriptions to use the term "Rover" instead of "Vehicle".

**Comment by GoogleFrog** [comment]
No updates?

**Comment by CrazyEddieTK** [comment]
Not much has changed since my last comment above. There's been a small bit of discussion on a few points, and you've suggested Sylph for Rocko, Machete for Cobra, and pushed back on Caltrop and Harriers.

I think I've provided all of the input that I have to provide at this time; anything else I'd say would just be repeating myself.

You need more opinions, more ideas, or more decisions.

**Comment by GoogleFrog** [comment]
I've got the last comment on a lot of it.

**Comment by CrazyEddieTK** [comment]
Added feedback based on your tentative choices.

I wish we could get input from more people than just you, me, Aquanim, and whoever is writing in green.

**Comment by GoogleFrog** [comment]
I think @sprunk is in green. I wish people would enter their names using the top right colour selector.

**Comment by GoogleFrog** [comment]
Done. Application is mostly done too.
