### ISSUE TITLE
Bantha on attack command skirmishes

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2382]
When giving an attack command to a bantha, he actively retreats to anni range and only uses his laser instead of closing the distance and using his zeus guns. This is unlike most units, where an attack command only walks into range but doesn't skirmish. I.e. rockos need fight command to skirmish.

It would be nice to have a command that simply makes Bantha chase the selected enemy with all his guns in consideration. For skirmishing behaviour there's both limited/free move state and fight command.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/5b23260b5edb0523199dc6939188b22e322fdad6  related?

**Comment by GoogleFrog** [comment]
I intend this behaviour and it is consistent. If you leave Bantha to its own devices it sits at max range and fires its Anni, since it is weak at close combat for its price.

> This is unlike most units, where an attack command only walks into range but doesn't skirmish. I.e. rockos need fight command to skirmish.

You are incorrect.
