### ISSUE TITLE
Stardust has pause between shots

### ISSUE THREAD

**Issue by versus666** [ZeroK-RTS/Zero-K#2385]
The problem is very noticeable on chicken games. 
Basicly if not manually selecting the targets for each turret, each round, suicidal chicken games (and easier too) quickly drive to dismay, whatever the number of turrets.

_ two or more turrets have VERY strange target choices, usually NOT shooting at the closest chickens but the farthest ones closing on ANOTHER turret, totally DISMISSING the 10 others nibbling itself. Nice cover but that quickly lead to two wrecks and lot of frustration.
_ the turret has a micro pause between target change, it's noticeable and selecting the targets manually with an attack zone remove that pause. And the bad aiming but that's not a sane fix.

I'd say it's a problem with unit_target_priority and/or stardust should be included in the "Proximity weapon special handling (heatrays)" but I have no idea how to change that.

**Comment by GoogleFrog** [comment]
The pause is likely the speed of slow update and not fixable without engine or some hax.

**Comment by GoogleFrog** [comment]
I tested and Stardust shoots every three frames. Retarget delay is likely fixed by the aim speed update.
