### ISSUE TITLE
Flak uses hunkered aimpoint

### ISSUE THREAD

**Issue by versus666** [ZeroK-RTS/Zero-K#2386]
1.5.7.2 and before:
A newton built in contact to a flak completely disable the later. Once the newton is reclaimed the flak is operational as expected. Certainly related to collision volumes and might affect other defenses too.

**Comment by versus666** [comment]
I tried with convols enabled to verify if there was really an overlap somewhere and it worked right. Tried some build combinations : newton a bit up or down (not altitude), newtons on two sides, newtons built before the flak, after the flak, before the flak fired, after the flak fired. Same.
I love when this game make me look like a fool ! :D
Anyway I 100% saw a flak inactive with a newton next to it and flyers happily dancing around that  worked ok once the newton it was reclaimed.
I'll try to find the demo and provide a video if possible.

**Comment by sprunk** [comment]
To some extent, adjacent units are supposed to make them obstruct each other's line of fire as long as the models look like they should.

**Comment by versus666** [comment]
Yeah, I know but here the flak was down, not moving, totally inert. And once I removed the newton the turret got up and began shooting the same flyers that was flying around for the last 10 secs.
I'm really puzzled.

**Comment by GoogleFrog** [comment]
Flak probably needs to aim as if it is extended because that is the position from which it will be firing.

**Comment by KingRaptor** [comment]
I'll add an elevated aimpoint to .s3o and unit script.

**Comment by GoogleFrog** [comment]
I've had a closer look and the only issue here seems to be that Flak aims from its hunkered position. Gauss and Razor correctly have a raised aim piece.
