### ISSUE TITLE
Team energy sharing leads to 0 energy income without storage

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2389]
In http://zero-k.info/Battles/Detail/462440 I lost my commander, afterwards constructions on high priority would be stuck at ??? until my teammate increased his energy production. Even though I was supposedly getting 0.5 E (Economy panel).

So not only was I not getting half of my teammates income, I was effectively getting no energy income whatsoever until building a storage.

**Comment by GoogleFrog** [comment]
Factories make 0.3 energy per second, this income is received in a lump. They spend 0.333 energy per frame that they are building, they cannot spend a smaller amount. The 0.3 income is sent away after a second of not spending it. Your ally was stalling so never shared you the energy required to have more than 0.3.

**Comment by GoogleFrog** [comment]
I was able to reproduce the issue. There are minor fluctuations so it takes some high speed and luck for construction to settle down to "???".

**Comment by DeinFreund** [comment]
My problem wasn't after the ally build a geo, it was the complete lack of progress even though I had 0.5 E income (weaver + fac). From 1:30 to 1:45 the factory didn't do any construction. Is this what you fixed?

**Comment by GoogleFrog** [comment]
Yes, I watched it a few times.

I said "your factory was working at time X". That doesn't imply I think that it was working all the time. Perhaps this is more a note to myself.
