### ISSUE TITLE
Set default build spacings

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2394]
Good default build spacings should be set. For example Solars should have no spacing. This fixes some pathfinding issues because if you make a grid of Solars at spacings two it is likely to cause your constructors to become stuck. However, only people who don't know how to set spacing make such grids.

**Comment by Licho1** [comment]
It could also be set for lotus etc

**Comment by GoogleFrog** [comment]
I set a default build spacing of 4 unless it is overridden by the custom param. I chose 4 because it makes for pathable bases when you drag lines of defenses. If the default is too high there is the risk that people won't shift+drag far enough to realize that line building is a feature. Also, if the default is high it would be a pain to manually reduce it for each structure if you like to use low spacing.
