### ISSUE TITLE
Consider reverting the Flea 20% embiggen

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2397]
Both models could be increased by about 20% to make them less hard to spot. The hitvolumes of these units are already too large for their models so the only balance change should be the higher and longer Flea gun.

**Comment by GoogleFrog** [comment]
The issue is that they are 3DO.

**Comment by GoogleFrog** [comment]
I may have been wrong about Flea, it costs 20 after all.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/18fac2b4cb635d5afee940521a6fb32ff80d722a
