### ISSUE TITLE
Issue with Command Raw Move in unsynced widget profiler?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2399]
Command Raw Move has 0.7% usage in unsynced lua. The only callins are DefaultCommand and Initialize. Here is the code for DefaultCommand:
`function gadget:DefaultCommand(targetType, targetID)`
	`if not targetID then`
		`return CMD_RAW_MOVE`
	`end`
`end` 

Widget profiler is misreporting?

![screen00423](https://user-images.githubusercontent.com/1318249/28197074-e2133dfc-6897-11e7-894a-229f86e2e29a.jpg)

**Comment by sprunk** [comment]
Profiler issue. See #2836
