### ISSUE TITLE
LuaMaterial warnings spam

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2406]
Does this come from ZK or from Engine?
```
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "ShadowMatrix", got: unknown expected: mat4
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "SunDir", got: unknown expected: vec3
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "ShadowParams", got: unknown expected: vec4
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "ViewMatrix", got: unknown expected: mat4
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "CameraPos", got: unknown expected: vec3
[f=-000001] Warning: LuaMaterial: incorrect uniform type for "TeamColor", got: unknown expected: vec4
```
It appears on start and every time /luarules are reloaded.

I tried to find where "SunDir" is mentioned in ZK and only found it in ghost_sites, although the warnings above look to have nothing to do with that widget & shader.

**Comment by lhog** [comment]
Probably related or same issue: https://github.com/ZeroK-RTS/Zero-K/issues/2299

**Comment by sprunk** [comment]
Why remove `ModelMaterials_103/Shaders/default.lua`? Looks good otherwise.

**Comment by lhog** [comment]
Q: ```Why remove ModelMaterials_103/Shaders/default.lua```
A: It's same as ```ModelMaterials/Shaders/default.lua```  and not used anywhere (even by 103 stuff). Therefore it should not exist in order to not confuse people like me.
