### ISSUE TITLE
Silo missile under construction can change pad after loading savegame

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#2408]
If a missile is being built on pad 3, and the pad 2 missile is launched/destroyed, the missile under construction will still be on pad 3 after the save is loaded, but will be moved to pad 2 once the game starts.

**Comment by GoogleFrog** [comment]
In which situation is this important?

**Comment by KingRaptor** [comment]
Well, it could matter if someone sets up the silo such that one pad is just slightly in range of a specific target and the other is just slightly out of it.

Otherwise, I guess the only issue is that it looks slightly weird at start.

**Comment by sprunk** [comment]
Solved via engine save.
