### ISSUE TITLE
Zed 2.2 is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2411]
Desync and '[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=DrawWorld trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/minerals.lua"]:121: attempt to call upvalue 'glSmoothing' (a nil value)'

https://github.com/ZeroK-RTS/CrashReports/issues/1530
https://github.com/ZeroK-RTS/CrashReports/issues/1529
https://github.com/ZeroK-RTS/CrashReports/issues/1528
https://github.com/ZeroK-RTS/CrashReports/issues/1527

**Comment by The-Yak** [comment]
https://github.com/ZeroK-RTS/Zero-K/issues/2305#issuecomment-307690147

**Comment by The-Yak** [comment]
Time to feature Zed 2.3?

**Comment by sprunk** [comment]
Unfeatured 2.2, featured 2.3.
