### ISSUE TITLE
Gauss projectile is destroyed too early

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2414]
This Slasher does not take any damage from the Gauss. Probably Sprungs overshoot gadget needs some leeway.

![screen00474](https://user-images.githubusercontent.com/1318249/28304835-c3eacac8-6bdc-11e7-85c5-d8a91981601f.jpg)

**Comment by sprunk** [comment]
It already destroys the projectile too late in the flat land case though.

**Comment by sprunk** [comment]
Also note that in addition to the gadget, all gauss type weapons are affected by #938

**Comment by lhog** [comment]
Remind me why gauss weaponType cannot be changed to LaserCannon?

- This change does not seem to affect any visual representation of Gauss shot
- Makes Gauss units shoot high altitude objects, so solves https://github.com/ZeroK-RTS/Zero-K/issues/938
- Preserve bouncing behavior

**Comment by sprunk** [comment]
I think there was an issue with LaserCannon bouncing (possibly just visual). IIRC @Anarchid found it so might be able to say more.

**Comment by Anarchid** [comment]
Last time i tried it resulted in this. The image conveniently provides versioning and timestamp. The entirety of the patch applied to the test article is change of commander's gauss weapon from `Cannon` to `LaserCannon` and addition of visual parameters to make the LC projectile look decent.
![image](https://user-images.githubusercontent.com/3822768/28413677-25a0c77a-6d51-11e7-9de0-8e75e8c8897d.png)

**Comment by lhog** [comment]
Nowadays visuals don't look broken, except that LaserCannon produces no perpendicular "warps" on bounced projectile (upper dagger has cannon, lower dagger has LaserCannon):
![screen00008](https://user-images.githubusercontent.com/1476261/28417550-304235be-6d61-11e7-8493-613487c09f78.jpg)

Also one is to make sure that range divided by per frame projectile speed is a round number. Otherwise the weapon range gets reduced by the amount of per frame projectile velocity.

Other than that I can't find other issues.

**Comment by sprunk** [comment]
Try shooting at the ground just under Dagger.

**Comment by lhog** [comment]
![screen00009](https://user-images.githubusercontent.com/1476261/28419966-4efc016c-6d69-11e7-80e1-4598cf4574a2.jpg)

**Comment by Anarchid** [comment]
Oh. I now realise that most of the visible gauss is particle trail which has no issues with bouncing, unless you changed projectile graphics. Which is fine if the purpose of the change is to fix simulation rather than visuals.

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/341a8e2ff2e8f646fc48cee20412c66fd2727e53 allows a fairly haxless implementation using LaserCannon.

**Comment by darloth** [comment]
I think I have another reproduction of this - the replay https://zero-k.info/Battles/Detail/473499 at 38% (7:13 in) the Gauss stays open to fire consistently at a dagger, without hitting it.  I checked that it was in visual range, and it is, so it ought to be accurate as the dagger is entirely stationary.

**Comment by sprunk** [comment]
I checked `LaserCannon` recently and there were still CEG failures (shooting very close didn't always leave the post-bounce part of the trail).

**Comment by sprunk** [comment]
4d187f9979c6cd0fa5d57c1b16051c3da2d287fa
