### ISSUE TITLE
Opponents are unable to build mex in campaign

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2417]
I tried playing the campaign and in every mission except the first, the opponent cannot build any  mexes (in the first mission, the mexes are prebuilt).

Presented with this situation, CircuitAI simply marches its only combat unit towards the player start zone, not building anything.

**Comment by Aquanim** [comment]
This is as intended.

Most of the levels don't actually exist yet, they're just there as placeholders for the galactic map. The first (few) levels have mex building disabled for a reasonable difficulty curve.
