### ISSUE TITLE
ZK 1.5.7.7 : nanoframe death error lead to end in endgame graphs (sudden 0 values @time of crash)

### ISSUE THREAD

**Issue by versus666** [ZeroK-RTS/Zero-K#2418]
[f=0046679] Error: LuaRules::RunCallIn: error = 2, UnitDestroyed, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_nanoframe_death.lua"]:88: attempt to call field 'SetFeatureResources' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_nanoframe_death.lua"]:88: in function 'ScrapUnit'
	[string "LuaRules/Gadgets/unit_nanoframe_death.lua"]:127: in function 'UnitDestroyed'
	[string "LuaRules/gadgets.lua"]:1465: in function <[string "LuaRules/gadgets.lua"]:1461>
	(tail call): ?
[f=0046710] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/endgame_graphs.lua"]:188: attempt to perform arithmetic on local 'buildProgress' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:188: in function 'RegenerateNanoframeValues'
	[string "LuaRules/Gadgets/endgame_graphs.lua"]:217: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:1014: in function <[string "LuaRules/gadgets.lua"]:1012>
	(tail call): ?

The latter error being repeated every 30 frames till the end of the game.

**Comment by sprunk** [comment]
What engine?

**Comment by versus666** [comment]
103.0 but you already made a commit.
