### ISSUE TITLE
Investigate a deync

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2424]
The desync in these two reports does not look bogus on a first glance. Find the battle, see if it is reasonable, and probably report on mantis.

https://github.com/ZeroK-RTS/CrashReports/issues/1549
https://github.com/ZeroK-RTS/CrashReports/issues/1550

**Comment by sprunk** [comment]
```
[f=0008592] Fatal: [Game::ClientReadNet][LOGMSG] sender="diddlydarnman" string="[spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={805306582,805306368}bytes"
[f=0008592] Sync error for diddlydarnman in frame 8478 (got fa9f9a80, correct is 8f031e7)
```
Duplicate of #2387 - Lua OOM desync.
