### ISSUE TITLE
Images for possible camera tilt issue.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2428]
![shieldsdeleted](https://user-images.githubusercontent.com/1318249/28506551-8cf55924-706f-11e7-912a-b3831f76f9ab.jpg)

Shields have been deleted for this screenshot.

![shieldsdeletedtilted](https://user-images.githubusercontent.com/1318249/28506552-8d752a00-706f-11e7-8359-a37cf40cf7a2.jpg)

This is the same setup but with a small tilt on the camera. Notice that almost all the units in view are drawn as icons.

![clearedtopdown](https://user-images.githubusercontent.com/1318249/28506544-8288a41e-706f-11e7-8f80-8adf899ff2eb.jpg)

Now I have destroyed the units that were icons in the titled screenshot and models in the top down screenshot.

![clearedtilt](https://user-images.githubusercontent.com/1318249/28506545-828f6a42-706f-11e7-8bea-263d711fd1b9.jpg)

The tilted screenshot has better FPS.

![clearedtopdownshields](https://user-images.githubusercontent.com/1318249/28506543-8287e9b6-706f-11e7-85c5-e68483d0b3ac.jpg)
![clearedtiltshields](https://user-images.githubusercontent.com/1318249/28506542-8287abae-706f-11e7-80b7-035bc46481f4.jpg)

Here I spawned 100 shielded units in the top left corner of the map.

![verycleartiltedshield](https://user-images.githubusercontent.com/1318249/28506547-853158e6-706f-11e7-8bf3-051cd38da0d6.jpg)
![verycleartopdownshield](https://user-images.githubusercontent.com/1318249/28506548-8531e658-706f-11e7-9cef-ef6ddc17a309.jpg)

Here I tried clearing even more area around the view. The effect becomes harder to see when there are fewer units in the game.

**Comment by GoogleFrog** [comment]
The ticket exists to hold images for this ticket: https://springrts.com/mantis/view.php?id=5672

![veryclearminortopdown](https://user-images.githubusercontent.com/1318249/28506918-1ff30576-7072-11e7-8141-1065cdd35335.jpg)
![veryclearminortilt](https://user-images.githubusercontent.com/1318249/28506919-2218f824-7072-11e7-98b4-2ab071070488.jpg)

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=5672 resolved.
