### ISSUE TITLE
Racketeers should anticipate that target's disarm is almost worn off

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2445]
Racketeers targeting priorities should gain ability to see that disarm is almost worn off.

Otherwise they spend shots on unidentified radar dots and only consider previously disarmed targets when disarm is no longer in place. Currently the only workaround is manual targeting via attack or set target

I could do this myself, but unit_target_priority.lua scares me off, so @GoogleFrog you better do it.

**Comment by GoogleFrog** [comment]
How do you reproduce this? Do you spawn two Racketeer and two Bandits and put one of the Bandits out of LOS but in radar coverage?

I presume you would do something like this https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua#L140. Then change this https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua#L253 based on attackerWeaponDefID

**Comment by lhog** [comment]
I reproduce this by having several racketeers (2 or more) on team 0 and two defenders on team 1.
Next I put radar in a way that both are in LoS, then put second radar so that one turret is visible and another is in the radar coverage. Then I self-D first radar. So you have two targets one in LoS, another is identified. Finally set rackets on Fire at will, and observe they only consider in LoS Defender as a priority target when disarm damage has worn off. That is in line with the current code, so not a bug, but wrong behavior.

>I presume you would do something like this https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua#L140. Then change this https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_target_priority.lua#L253 based on attackerWeaponDefID

I know where to put it, I don't know how to choose the cryptic numerical constants that are everywhere in the file and not break other stuff.

**Comment by lhog** [comment]
After a few hour long tries, I'm even more concerned I can't do that myself:
Calls to GetUnitStunnedOrInBuild(unitID) are nested if GetDisarmWeaponPriorityModifier is called, so things become more complicated. I cannot balance magic numbers in such way that a target with 3-4 seconds left before disarm expiry is getting a priority again.

**Comment by lhog** [comment]
Thank you!
