### ISSUE TITLE
Zombies error that kills game

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2446]
https://github.com/ZeroK-RTS/CrashReports/issues/1619

**Comment by GoogleFrog** [comment]
Crashes in LuaRules and then an OOM, most likely caused by the crashes.

https://github.com/ZeroK-RTS/CrashReports/issues/1617
https://github.com/ZeroK-RTS/CrashReports/issues/1616

**Comment by lhog** [comment]
I don't see any obvious reason for this crash, so it would be nice to see it happening alone, i. e. without tons of preceding errors in other gadgets.

**Comment by sprunk** [comment]
Triplicate.
ZeroK-RTS/CrashReports#1617 and ZeroK-RTS/CrashReports#1616 are caused by #2438.
ZeroK-RTS/CrashReports#1619 is #2443.
