### ISSUE TITLE
Update solar aoplane

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2464]
I need a solar model which looks like how solar looks ingame. Then I can run the aobaker on it.

**Comment by sprunk** [comment]
This should do: https://github.com/ZeroK-RTS/Zero-K/blob/aaaa0db7eded622aed1b7e52240c06435eacb378/Objects3d/arm_solar.s3o?raw=true

**Comment by GoogleFrog** [comment]
I had to rotate the solar by 45 degrees and extend the arms manually in upspring.
