### ISSUE TITLE
Inconsistent graphics settings selection

### ISSUE THREAD

**Issue by C0rn3j** [ZeroK-RTS/Zero-K#2470]
Selecting a setting sometimes works, sometimes doesn't. I'd say it has about 1/3 - 1/4 chance to work.

https://youtu.be/-2oLAa3jVkM

Using Arch Linux, GTX 1080 Ti with proprietary Nvidia drivers.

**Comment by sprunk** [comment]
Thanks, moving to the lobby repo where this belongs https://github.com/ZeroK-RTS/Chobby/issues/301
