### ISSUE TITLE
Consider removing hold position by default for many standard units

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2475]
I've seen new players use Rocko and they are quite hurt by the hold position by default. Hold position means that Rocko will only use unit AI when told to attack move. An idle Rocko or a Rocko with a force fire command will not use unit AI. Many skirmishers and artillery are set to hold position by default, I now think this could be removed.

My reasoning for setting hold position was as follows:
 * To prevent baiting of long ranged units into turret range.
 * To prevent units 'refusing' to attack a target which is blocked. If you put a Warrior in the middle of a 500 elmo radius plateu with steep ramps and tell Rockos to use unit AI on it they will never shoot at the Warrior because they are blocked by the terrain.

**Comment by mtroyka** [comment]
The unit start state ui is now also much better for managing that across bulk unit types for people who want different behavior. Anyway what made you decide to change your mind on this issue?

**Comment by GoogleFrog** [comment]
Watching new players with Rocko. If they ignore the Rocko or give it an attack command it has stupid behaviour.
