### ISSUE TITLE
d-gun commander is utterly broken

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#2481]
can no longer fire thru obstacles(wrecks/enemy units) which kind of makes it very hard to use
http://zero-k.info/Battles/Detail/466267
here com is trying to dgun mex behind factory, pressed like 20-30 times
died trying dgun did not fire even once

before it could, but there was some bug with adv targetting system not extending the range of disintegrator gun(showed the extended range, did not fire if pressed dgun in the extended zone)

can not reliably target sumo, I had a game where I tried to hit sumo 3 times, 
2 times it dealt like 1% or less damage - it just seems like dgun goes below the sumo dealing zero or minimal damage
(no replay, but should be easy to reproduce)

what's going on?

**Comment by GoogleFrog** [comment]
Reported: https://springrts.com/mantis/view.php?id=5715

**Comment by let4be** [comment]
What about sumo? I don't think this is supposed relation between disintegrator gun and sumo
dgun supposed to counter big and heavy units, sumo is definitely big and heavy, yet still you will die 10 times before do any damage to it with dgun

**Comment by GoogleFrog** [comment]
Sumo works for me. It barely touches the ground so if you shot at the ground it would not take much damage. If you shoot at the middle of Sumo it almost dies.

**Comment by let4be** [comment]
how do I differ those 2 in-game?
I press D and then click on sumo and it misses...
Will try to find a replay today later

**Comment by GoogleFrog** [comment]
Fixed (I assume) https://github.com/spring/spring/commit/d3226687044e9b633791ef9ab4af56ec4cbd692f.
