### ISSUE TITLE
Bombers don't work with manual attack command

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2483]
![bug](https://i.imgur.com/LyMwfow.png)

When trying to attack an unspotted underwater target, bombers will refuse to fire even with a direct manual fire command. They will start reloading (shows reload bar), but no bomb is dropped and the bomber doesn't have to return to the airpad for its next run.

**Comment by GoogleFrog** [comment]
The reloading will simply be their shield checker. What happens when they attack ground on the sea?

**Comment by DeinFreund** [comment]
They just fly over the target and the reload bar appears. Then they come back for another run and everything repeats.

**Comment by GoogleFrog** [comment]
Could be related to the changes to free line of fire. The next thing to do is to check the two versions mentioned in https://springrts.com/mantis/view.php?id=5715.

**Comment by GoogleFrog** [comment]
Seems to be https://springrts.com/mantis/view.php?id=5715.

**Comment by GoogleFrog** [comment]
Fixed (I assume) https://github.com/spring/spring/commit/d3226687044e9b633791ef9ab4af56ec4cbd692f.
