### ISSUE TITLE
Consider removing CTRL as the "queue x20" fac modifier

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2485]
In a factory, SHIFT works as x5 both when mouse clicking and when using a hotkey to queue.
However, CTRL works as x20 when clicking but as a regular order/selection command when hotkeyed.

For example in a cloaky fac, SHIFT+D is queue 5 jethro but CTRL+D is self-destruct.

Consider whether to drop CTRL as the x20 modifier. For:
 * would prevent accidents like CTRL+D
 * not very useful: SHIFT already exists for bulk orders and thanks to Repeat there isn't much use for 20+ in a row
 * frees up a modifier key for something else if need be

Against:
 * the hotkey labels disappear when CTRL is held so the UI does convey it
 * oldschool TA people do use it (eg Randy doesnt use repeat and instead queues 100 with CTRL+SHIFT)

**Comment by gajop** [comment]
+ It's a good thing that clearly the hotkey labels disappear when you press ctrl.
Other state-changes (like repeat) are also bound to ctrl-key

**Comment by GoogleFrog** [comment]
I'm against. I think it is a not very harmful form of backwards compatibility and I think many people use the mouse clicking factory UI. The hotkeys disappear, which conveys enough.

**Comment by sprunk** [comment]
Alright.
