### ISSUE TITLE
Attrition Counter feedback

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2491]
When speccing a game, i observed one team having 80% attrition rate while the other had 75%; this seemed to happen in other games too, including ones where players did not use any weapons liable to kill enemies out of sight. Obviously, in a zero-sum game, such numbers should not be possible, and since i was a spectator, i should have had perfect information anyway.

Additionally, the one game i've so far played with the widget enabled after rewrite, an 1v1, continuously displayed 0% for me despite staging multiple successful engagements and then drowning the enemy in Glaives.

**Comment by sprunk** [comment]
Self-damage is counted as a loss for attrition but not as a kill for the enemy so 80/75 is legit (one team kills 80, loses 75 from enemy and 25 from self, the other team kills 75 loses 80 from enemy and 20 from self).

Attribution of every death to the enemy won't work in FFA. However in hindsight I think it was probably better for the 1v1/teams situation.

I'll investigate the 0% when possible (likely September 5th or 6th, ie after tankfac), feel free to revert the rewrite in the meantime if it reproduces often.

**Comment by Anarchid** [comment]
I was able to replicate in a duel vs AI.

**Comment by Anarchid** [comment]
Rewrite seems to still be reverted, close?
