### ISSUE TITLE
Updating chobby fails

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2496]
https://i.imgur.com/pae4tfm.jpg

Chobby downloads new ZK sdz to 100% and then spits out this error. I've been able to replicate this twice now.

EDIT: the screenshot in question shows an error for 1.5.8.3, I have tested this version of ZK archive by launching spring-1285 directly and the game works.  Chobby now loads okay so mabye this error could suggest a restart

**Comment by Licho1** [comment]
You pressed the cancel button.

**Comment by Anarchid** [comment]
Something very similar happens to me on linux. Each time i start chobby for the first time, a download error happens and chobby aborts. Second start is always successful.

**Comment by sprunk** [comment]
Infra ticket: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1808
