### ISSUE TITLE
Gather UI clickthrough failure hard data

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2499]
Missing buttons on the UI often causes your selection to be deselected. It is friendlier to not clicks on empty UI space in the game world. Mouse release (area commands, selection etc..) should be registered still. This could be optionally disabled.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/5182a3956add1f5c142699dd2036216ff8edee55

**Comment by Licho1** [comment]
Nooo please do not do it! I stop noticing gui soon and often do click through GUI panels

**Comment by sprunk** [comment]
@GoogleFrog

**Comment by GoogleFrog** [comment]
I need hard data to reverse this. I don't think such data will be gathered.

**Comment by Licho1** [comment]
Las thing was we dont block RMB and MMB and block LMB when no command is selected

**Comment by Licho1** [comment]
Ok here are my data: i click it twice yesterday on the gui.
It sure beats data from a newbie missing the button once.

**Comment by sprunk** [comment]
#2656
