### ISSUE TITLE
Global commands: allow to remove some of the buttons

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2511]
It is possible to resize it so that it hides the newly added Attrition and Stats buttons. The minimum width should include those buttons if they're supposed to be always visible.

**Comment by sprunk** [comment]
They aren't supposed to be always visible, they are just supposed to be visible in the default preset and defaults don't care about resizing.

Someone who tinkers with the UI might want to remove them (through Ctrl+F11) and shrink the GBC.

**Comment by DeinFreund** [comment]
But then why can't I remove more than that? Why just those two buttons? I don't really want any of those buttons visible, but that's not an option either.

**Comment by sprunk** [comment]
>For me a simple checkbox "Disable Global Commands" would suffice. All it has to do is hide the entire panel.

Disable the widget then?

**Comment by DeinFreund** [comment]
Last time I tried that this also disabled "hidden" features (accessible via keybinds).

**Comment by GoogleFrog** [comment]
The pie in the sky milestone is for things that would be good to implement but would have too low of an impact to be worth the predicted complexity of the task. This task would be easy but it feels dangerous to implement. Perhaps it can be behind the advanced settings tickbox.

My misgivings with an epicmenu option to hide the global commands bar is that I don't want "standard" customization to involve removing the command bar. There are things on the command bar that don't have hotkeys by default and setting up those hotkeys is somewhat advanced.

**Comment by sprunk** [comment]
@DeinFreund I added a way to hide the panel but since @GoogleFrog does not want it in the menu you'll have to manually edit your config file.

`Spring/LuaUI/Config/ZK_data.lua`, find the epicmenu subsection, add `epic_Global_Command_Bar_hide = true`.
