### ISSUE TITLE
Chickens recursion error

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2516]
Zero-K v1.5.8.3
103.0.1-1336-g61d1146

https://github.com/ZeroK-RTS/CrashReports/issues/1950

>[f=0000702] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCreated trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_spawner.lua"]:430: GiveOrderToUnit() recursion is not permitted
>stack traceback:
>	[C]: in function 'spGiveOrderToUnit'
>	[string "LuaRules/Gadgets/unit_spawner.lua"]:430: in function 'UpdateBurrowTarget'
>	[string "LuaRules/Gadgets/unit_spawner.lua"]:1011: in function 'UnitFinished'
>	[string "LuaRules/gadgets.lua"]:1432: in function 'UnitFinished'
>	[string "LuaRules/gadgets.lua"]:1421: in function <[string "LuaRules/gadgets.lua"]:1410>
>	(tail call): ?
>	[C]: in function 'GiveOrderToUnit'
>	[string "LuaRules/Gadgets/cmd_raw_move.lua"]:600: in function 'ReplaceMoveCommand'
>	[string "LuaRules/Gadgets/cmd_raw_move.lua"]:615: in function 'UpdateMoveReplacement'
>	[string "LuaRules/Gadgets/cmd_raw_move.lua"]:664: in function 'GameFrame'
>	[string "LuaRules/gadgets.lua"]:1014: in function <[string "LuaRules/gadgets.lua"]:1012>
>	(tail call): ?
>

**Comment by KingRaptor** [comment]
eea9797cc29234f3987cbec1d601228eb65941a3
