### ISSUE TITLE
Default command on damaged constructors should be guard, not repair

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2518]
When you select a constructor and right click on a constructor or factory your aim is almost always to assist the constructor or factory. Currently the default command is repair on damaged targets which leads to people thinking that they told their constructor to assist but in fact the constructor will stop following the target once it has full health.

Possibly, we could leave repair but insert a guard command after it.

**Comment by mtroyka** [comment]
doesn't guard repair anyway?

**Comment by sprunk** [comment]
Guard does repair, but repair doesn't guard.

**Comment by GoogleFrog** [comment]
I have found this behaviour annoying. I think it may only be good for factories. Time will tell.

**Comment by sprunk** [comment]
I'll make it a customizable widget.
