### ISSUE TITLE
Potential cmd_retreat error

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2519]
Not necessarily real because it's in the middle of a desync.

https://github.com/ZeroK-RTS/CrashReports/issues/1995
Zero-K v1.5.8.3
103.0.1-1336-g61d1146

>[f=0042127] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=RecvLuaMsg trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/cmd_retreat.lua"]:133: table index is nil

**Comment by GoogleFrog** [comment]
Desync doesn't matter. Each player is still running a sane game state.
