### ISSUE TITLE
Consider making airpads implicit gunship retreat zones

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2521]
See https://zero-k.info/Forum/Thread/24351

Airpads could become implicit retreat zones for gunships. In OTA, patrolling gunships automatically used airpads when below X% health, and new people seem to generally expect that buildings that can repair garrisoned stuff are good at it. Planes use airpads by default and newbs might not know the differences between the two aircraft types.

On the other hand, airpads' actual role is rearm and repair is just a convenience feature bolted on top. Having gunships take up pads is potentially harmful because that takes up slots for bombers who might need rearming and is strictly inferior by far to a nanotower.

Since retreat is synced, having the behaviour as a global toggle would be somewhat fragile, but since there seems to be a large difference between newb expectations and efficient play I think it would still be best to have it.

A softer version of this would be to make gunships land on airpads that are inside an explicit retreat zone. I don't think there's anything questionable here. Possibly this one deserves a separate subticket.

**Comment by GoogleFrog** [comment]
The primary reason gunships don't retreat to airpads is that it becomes a source of automatic trolling. Player A has planes, Player B has gunships. Player B sets their gunships to retreat and sets some retreat zones. Player A makes a forward airpad to rearm their bombers. The players are now automatically trolling each other:
 * Player A is annoyed that Player Bs gunships are taking up valuable space on their froward airpad.
 * Player B is annoyed that their gunships are being directed away from the BP they set up around their retreat zone.

Neither player is at fault. However, neither player has any way to work around this issue. The planes player wants to make airpads (or have their team make them) but the placement of the pads puts restrictions on the placement of retreat zones by the gunship player. Therefore this ticket at least requires a way to disable gunships from automatically using pads. The default UI paradigm seems to support putting a state toggle on the airpad itself.

I'm starting to think that this is pie in the sky. As far as I recall, the retreat behaviour for planes is equivalent to automatically pressing the 'return to airpad' button.The button has nothing to do with the retreat gadget and is, in many ways, much more advanced. Each airpad has a capacity and keeps track of its incoming aircraft so when you press the button your planes will be sent to the closest pad with a free spot, not merely the closest pad. The retreat gadget simply sends the units to the closest retreat zone. If gunships could go to both retreat zones and airpads they would need to ask for the closest free pad and then only go there if there is no closer zone.

**Comment by sprunk** [comment]
>I think the real issue may be that it looks like a good idea to make airpads for gunships.

I think so too, but that sounds very hard to solve because the intuition for a servicing station is that it primarily repairs. Most other RTS also implemented such buildings that way (OTA airpad; but also eg RA Service Depot).
