### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2522]
https://github.com/ZeroK-RTS/CrashReports/issues/2094

Find the replay

**Comment by GoogleFrog** [comment]
[f=0069970] Morjor unpaused the game
[f=0071293] Terraform bad number detected, SetTooltip, nan
[f=0071293] Terraform bad number detected, SetTooltip, nan
[f=0071293] Terraform bad number detected, SetTooltip, nan
[f=0071294] Terraform bad number detected, SetTooltip, nan
[f=0071294] Terraform bad number detected, SetTooltip, nan
[f=0071294] Terraform bad number detected, SetTooltip, nan
[f=0071297] Terraform bad number detected, SetTooltip, nan
[f=0071297] Terraform bad number detected, SetTooltip, nan
[f=0071297] Terraform bad number detected, SetTooltip, nan
[f=0071297] Warning: [Watchdog] Hang detection triggered for Spring 103.0.1-1408-gaba49d2 develop.
[f=0071297] Warning: 	(in threads: {main,load,audio}={1,0,0})
0x00400000	spring

**Comment by sprunk** [comment]
Two bugs here but both already have a ticket.

There's `[f=0036617] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=CommandFallback trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_terraform.lua"]:3199: GiveOrderToUnit() recursion is not permitted` which is #2256.

There's also `Terraform bad number detected, SetTooltip, nan` which is #2361.
