### ISSUE TITLE
Disambiguate sounds

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2524]
Some units use identical sounds (for example Firewalker and Wolverine).

These would ideally use different sounds.

We can make a ghetto differentiation by changing their pitch in `sounds.lua`.

**Comment by Anarchid** [comment]
Something like this for Wolverine? https://freesound.org/people/qubodup/sounds/187542/

**Comment by sprunk** [comment]
Duplicate of #2592
