### ISSUE TITLE
Retreat icon: chicken might be bad

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2528]
https://github.com/ZeroK-RTS/Zero-K/commit/2a4917ef796324aaa10fabfd70f1ae52510fecd3 made retreat icon consistently the yellow chicken.

I think the chicken is a bad icon:
 * in ZK "chicken" generally represents the tower defense faction. This is extra bad because in those games there are two buttons with chicken pictures on the global bar.
 * potentially confusing for non-native speakers, requires the knowledge of the "chicken out" idiom.
 * weird shape. 90 only differs from 60 by the head and a small part of tail, it's somewhat hard to tell these two at a glance.

**Comment by Anarchid** [comment]
Another idea: running man with or without fire or other associated hazards, as seen on the typical "escape" symbols:
![image](https://user-images.githubusercontent.com/3822768/30911009-9b7dc866-a38f-11e7-91f6-949b3eab441a.png)
