### ISSUE TITLE
Check whether all units have `AimWeapon` defined

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2531]
The general case of #2530.

**Comment by Anarchid** [comment]
I've grepped lua scripts and found two scripts that seem to belong to armed non-suicide units and don't have AimWeapon:
```
.//dynamicCommander.lua
.//bomberriot.lua
```

**Comment by Anarchid** [comment]
Some blatantly obsolete files also have this issue but i don't know if they are actually used or are orphans whose units migrated to lus. Again, only counting things that look armed, dangerous, and non-suicidal:

```
.//chicken.bos
.//chicken_digger.bos
.//chicken_digger_b.bos
.//chicken_dodo.bos
.//chicken_drone.bos
.//chicken_drone_starter.bos
.//chicken_leaper.bos
.//chicken_listener.bos
.//chicken_listener_b.bos
.//chickenblobber.bos
.//chickenc.bos
.//chickend.bos
.//chickenf.bos
.//chickenr.bos
.//chickens.bos
.//chickenspire.bos
.//tankarty.bos
.//tankcon.bos
.//tankheavyarty.bos
```

**Comment by sprunk** [comment]
BOS might have `AimPrimary` (`Secondary`, `Tertiary`) instead, these are acceptable.
Also, only weapons with `forwardOnly` are broken.
