### ISSUE TITLE
Hold-LMB Skydust does not work

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2532]
`<Licho> hmm i tried ZK but hold left to change height of structure does not work by default
<Licho> i will try resetting again maybe i got some leftovers somewhere`

**Comment by GoogleFrog** [comment]
Works for me https://youtu.be/ItIdm6kPehk

**Comment by sprunk** [comment]
@Licho1 reopen when more feedback comes.

Remember that the time-to-hold is longer than before (now 1s, I think it used to be 0.3 initially) and that there is less lenience for moving the mouse during that time (because it interfered with line-build).

**Comment by Licho1** [comment]
Yeah I will try fresh again
