### ISSUE TITLE
Fix map hardness under nanoframes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2534]
There is a gadget which changes the terrain type under unit nanoframes, to make them impassible. The hardness of arbitrary terrain cannot be controlled. See:
 * https://github.com/ZeroK-RTS/Zero-K/commit/32b94f4ae033068cea9ee6e2374235083ba9ea60
 * https://springrts.com/mantis/view.php?id=5790

**Comment by sprunk** [comment]
>hay gurl, are you a nanoframe? cause i cant control my hardness

The terraintype solution was reverted so this is no longer a problem: https://github.com/ZeroK-RTS/Zero-K/commit/a3131e722620ab020b5d9b775ef4a648947fa96c

The engine also now allows controlling hardness if we need it for other use: https://github.com/spring/spring/commit/845701ba97edf31aa94460fdd4cf239132b1dc1d

**Comment by GoogleFrog** [comment]
Note that using that engine is infeasible for the foreseeable future.
