### ISSUE TITLE
Spring.GetGroundInfo and Spring.GetTerrainTypeData: interface change

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2535]
https://github.com/spring/spring/commit/6971132e6cc5be34d1715b3282302c98f07b0728#diff-57d7b828470c238f6a9a94cc004a222fR18

will break the new nanoframe impassability feature https://github.com/ZeroK-RTS/Zero-K/commit/32b94f4ae033068cea9ee6e2374235083ba9ea60

**Comment by GoogleFrog** [comment]
As far as I'm aware, the dev engine is unusable in anyway https://github.com/spring/spring/commit/4c87e94f640c31238b814190dbe611cb662a17dd.

**Comment by cleanrock** [comment]
Any chance you can make a branch for post 104 so we can test engine with zk ?
Just fixing the spGetGroundInfo calls by inserting a "_," made it possible for me to run my CircuitAI-CAI test game.
I know more fixes are needed for the GL overhaul.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/e8ad068a1f733e722fdd9c53c4a265a34111e432
