### ISSUE TITLE
Have unit outlines enabled as a default setting

### ISSUE THREAD

**Issue by beamer159** [ZeroK-RTS/Zero-K#2537]
How many units does the red player have in the picture below?

https://i.imgur.com/tjmzKl0.jpg

Unit visibility can be an issue at zoom levels just before icons appear. This problem can be made worse with certain terrain types. The unit outline option seems to be the most unobtrusive way to enhance unit visibility. Compare the picture above with the picture below:

https://i.imgur.com/rYO163H.jpg

All of the units pop out much better. However, this option is hidden away in the advanced settings of Graphics -> Unit Visibility. Practically no new player will find this setting without help, which is a problem since it is so helpful to see all your units.

I suggest that unit outlines be enabled by default because unit visibility on the map should be one of the most critical aspects of any RTS to get right.

**Comment by GoogleFrog** [comment]
Check whether the widget has issues. With these types of things they often just fall short of the level at which they could be enabled with no issues. I think the outlines may look really unusual at low angles.

It is worth looking into though. Unit visibility is something I've been meaning to re-asses. Apparently the GDS feedback was mixed on whether to enable outlines.

**Comment by sprunk** [comment]
Perhaps the icon distance is just too low?

**Comment by Licho1** [comment]
Unit outlines were universally disliked on live show at GDC conference.
Do not do it.

**Comment by The-Yak** [comment]
For unit visibility, an alternative idea to enabling outlines would be to enable spotter without enemy circles by default.

Has a bonus effect of making cloaked units look nicer

I find it surprising to hear outlines were disliked, were outlines on thinnest possible settings, no scale? That's the only way I  personally like them.

**Comment by sprunk** [comment]
152b98d7e17d9cabf09cdbf406007249a39b4679
