### ISSUE TITLE
ComboBoxes in menu not working properly in some cases

### ISSUE THREAD

**Issue by Firestorm01X2** [ZeroK-RTS/Zero-K#2540]
OS: Win 7 X64
To reproduce:
Start game=>Multiplayer=>Battle List=> Host Game. In Host Game window try to change "Game Type"
**Also it appers to happen in with any Combobox in menu.**

Expected:
Game type item in cobobox changed properly

Actual:
Combobox opens and shows items but after click on ComoBox items combobox just closes but do not change item. Looks like area for clicking in combobox item do not relate to it actual size because sometimes it works properly. Bug appears in Borderless window menu mode.
[Zero-K.zip](https://github.com/ZeroK-RTS/Zero-K/files/1352684/Zero-K.zip)

Bug almost dissapeared after changing Menu Winows mode to Windowed and back bo Borederless Window. But sometimes still happens. 
Probably it is related with focus.
Sometimes bug still happens:
https://youtu.be/cohwFklhwts?t=36

**It was much worse before and happened all the time.**

**Comment by sprunk** [comment]
Thanks for the report. I've moved it to the Lobby/Menu section (this here is for the game proper).
