### ISSUE TITLE
F5 is making some widgets draw everything before terrain

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2544]
https://i.imgur.com/mHWsHaQ.jpg

I have noticed this issue with both outlines and map extension grid.

**Comment by GoogleFrog** [comment]
Outlines did not do that when I last checked.

**Comment by sprunk** [comment]
Map Extension has some sorf of spillover where it can draw stuff that belongs to other widgets (see https://github.com/ZeroK-RTS/Zero-K/issues/2055#issuecomment-316417970 ) so possibly the GL context might carry over as well?
