### ISSUE TITLE
Movement onto wrecks is randomly blocked

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2547]
Give a move command onto a wreckage. Sometimes the unit will sit stationary and not complete the move order. This is with the raw move command, however, the blocked destination should be causing a pathfound move to be given as a fallback. A fight order will be instantly canceled in the same situation.

This is reasonably easy to reproduce with a Lotus wreck about 600 elmos from a Puppy. The distance seems to be important so perhaps the search level is affecting the bug. allowRawMovement may have an effect on frequency but the issue can be reproduced with it enabled or disabled.

**Comment by GoogleFrog** [comment]
Engine bug: https://springrts.com/mantis/view.php?id=5803

I suspect that 103.0.1-1431-g0934acd is the last working version. The dev engine is unusable so I don't know how useful the bug report will be. A fix branch would be ideal but as far as I know there has never been one. If there is an engine fix we could look into building a custom version of the engine. Otherwise I think it is worth reverting to 103.0.1-1431-g0934acd and replacing all the inbuilt downloading with wrapper downloading as a bug with downloads was fixed post 103.0.1-1431-g0934acd.

**Comment by sprunk** [comment]
The new engine has some other useful things so I think it's worth looking into a fix branch.

**Comment by GoogleFrog** [comment]
Apparently this has been fixed. It requires some testing. Here are the two commits that are required:
- https://github.com/spring/spring/commit/5777dd9292b4fb13955bf9ee81a1213f2dfea186
- https://github.com/spring/spring/commit/0139916d0e27ad670c8eeedcb29ad7bbbb4beae3

Once verified it is worth looking into incorporating those commits. Here is the commit for the version used by ZK: https://github.com/spring/spring/commit/f03115b594b04995aca4e13b8dccc456a2eb607c. It looks like dev engine becomes unusable at https://github.com/spring/spring/commit/4c87e94f640c31238b814190dbe611cb662a17dd which is just a few commits after the version that we use. There are perhaps three useful features/fixes between the version in use and the unusable versions. If we want to use things those features/fixes it would be best to first set those develop versions on the server to make sure that there are no issues.

@ashdnazg what is the likelyhood of being able to put the two path fixes in a post 104.0-7 fix branch? I already think that no engine dev cares about our crash reports since almost all of the engine crashes with usable stacktraces are graphics related and those systems are being redone.

@sprunk I want a fix branch for necessary changes, not those that are merely useful. Useful changes are usually features and are likely to make their own bug reports. Bug reports from a fix branch would be a huge hassle. I prettymuch only want a fix branch for issues that would make me consider reverting our engine to an older develop version. The issue in this ticket stems from merging a feature (inbuilt raw move) and making 104.0 shortly afterwards with little time for testing (there was a gap of around 50 commits that were not built).

**Comment by GoogleFrog** [comment]
While we are looking at fixes, this may be important: https://github.com/spring/spring/commit/49f60dfea913a290f1cbbed52f8c41b9df5ddd54. SetConfigFloat is new and hopefully fully optional.

**Comment by GoogleFrog** [comment]
https://github.com/spring/spring/commit/a255f7fd194cd23ec0f002b68463d00ba9027aec may be a fix related to the other two commits.

**Comment by GoogleFrog** [comment]
@ashdnazg says that they can make a branch based on a list of commits to use. Here are the commits since head: https://github.com/spring/spring/compare/104.0...HEAD

ZK is on 104.0.1-7-gf03115b so we are already using the following commits since master. They should be included
 - https://github.com/spring/spring/commit/711dcee20eb0301e8aab18ecaca53b380e5cb433
 - https://github.com/spring/spring/commit/8a74b03eabd1942f3c81f828914aa5d7937cdd73
 - https://github.com/spring/spring/commit/4c0e647fb8fb986d79d0b1db36acc6ac73fcad7b
 - https://github.com/spring/spring/commit/3e67c491f5eaa91592d4358b40e487fbbfda5594
 - https://github.com/spring/spring/commit/513773048379a3e923a525246665dc456eac7452
 - https://github.com/spring/spring/commit/440aa274df3b90aa9553e26ac5d5646b4c1f0e9a
 - https://github.com/spring/spring/commit/f03115b594b04995aca4e13b8dccc456a2eb607c

**Comment by GoogleFrog** [comment]
@sprunk comment with amendments to my list.

**Comment by sprunk** [comment]
Bugfixes:
 * https://github.com/spring/spring/commit/5cc17fa2d457e60066a393d6610350f01774bdf3
 * https://github.com/spring/spring/commit/a7d33e9acca36cf757d0f90f9c82ce8cf8144d50 (not bugfix but prerequisite to the one below)
 * https://github.com/spring/spring/commit/dc7507ce88fe56038922a6fe7ed4e6f1341ef888
 * https://github.com/spring/spring/commit/28ca17088f97964f577a071f8fb12371647a5d1f (unsure whether caused by post-104 changes or not)
 * https://github.com/spring/spring/commit/709a8b412ed77560df9fb193b7b4a2acc059c7ab

Not bugfixes:
 * https://github.com/spring/spring/commit/845701ba97edf31aa94460fdd4cf239132b1dc1d and https://github.com/spring/spring/commit/6971132e6cc5be34d1715b3282302c98f07b0728 map hardness Lua calls (we're using those so keeping the interface up-to-date simplifies things for the future)
 * https://github.com/spring/spring/commit/33de5ce85ec7db94e8a381e71286b3409b1aab2c and https://github.com/spring/spring/commit/e622dbb9b2f4a5b8886e2d7d40a2b68cf53c489a GetLuaMemoryUsage - useful for various OOM problems ()
 * https://github.com/spring/spring/commit/1fc7397aeffdcad1e411465501c3c6307f917e21 /specfullview generates an event - allows for some optimisation (IIRC Lups polls about it every frame)
 * https://github.com/spring/spring/commit/bc04cfc97999625076f93ad81d9ce1ce7d6b4e4f allows KR to record the trailer without sound speedup shenanigans

Things not yet in engine:
 * https://github.com/spring/spring/pull/350 allows to fulfil some parts of #2556
 * https://github.com/spring/spring/pull/342 allows a clean implementation of #2517 and #2518

**Comment by GoogleFrog** [comment]
I don't want to touch the minimap rendering fix (https://github.com/spring/spring/commit/28ca17088f97964f577a071f8fb12371647a5d1f) because it involves rendering.

I don't want to touch camera fixes (eg https://github.com/spring/spring/commit/709a8b412ed77560df9fb193b7b4a2acc059c7ab) because I have heard of no camera bugs and they could possibly stray into rendering.

The non-bugfixes look ok. They just carry the normal risk of introducing bugs and making us repeat this process. @ashdnazg says that they are willing to take that risk and deal with issues. I don't think we're going to be using any engine changes for the trailer unless the change can be made to run an old replay.

I do not want to include any commits which have not been merged to develop.

Some more commits:
 * Here is a fix for {Set,Get}ConfigFloat https://github.com/spring/spring/commit/41f7e7bd5f7c231ce74a38fa477910759cc123dc 
 * Here is a small commit that claims an improvement to load speeds for sdp archives https://github.com/spring/spring/commit/f2399e7b7b0169ae6e08dedb2292f9ea94baefba
 * This commit allows files to be rescaned, for cases where they are moved manually of via the wrapper https://github.com/spring/spring/commit/62d3bb6f3484e0ede7d794a3a063c69580ee2bfd. I don't know whether it is useful.

**Comment by sprunk** [comment]
* https://github.com/spring/spring/commit/711dcee20eb0301e8aab18ecaca53b380e5cb433
 * https://github.com/spring/spring/commit/8a74b03eabd1942f3c81f828914aa5d7937cdd73
 * https://github.com/spring/spring/commit/4c0e647fb8fb986d79d0b1db36acc6ac73fcad7b
 * https://github.com/spring/spring/commit/3e67c491f5eaa91592d4358b40e487fbbfda5594
 * https://github.com/spring/spring/commit/513773048379a3e923a525246665dc456eac7452
 * https://github.com/spring/spring/commit/440aa274df3b90aa9553e26ac5d5646b4c1f0e9a
 * https://github.com/spring/spring/commit/f03115b594b04995aca4e13b8dccc456a2eb607c

This brings us to 104.0.1-7-gf03115b.

* https://github.com/spring/spring/commit/f68d055f200a4ce515432b36c6506117b5c2fcb9
* https://github.com/spring/spring/commit/196f45208d233a7f994b0836640a0ac4b4161dd2
* https://github.com/spring/spring/commit/845701ba97edf31aa94460fdd4cf239132b1dc1d
* https://github.com/spring/spring/commit/6971132e6cc5be34d1715b3282302c98f07b0728
* https://github.com/spring/spring/commit/33de5ce85ec7db94e8a381e71286b3409b1aab2c
* https://github.com/spring/spring/commit/e622dbb9b2f4a5b8886e2d7d40a2b68cf53c489a
* https://github.com/spring/spring/commit/5cc17fa2d457e60066a393d6610350f01774bdf3
* https://github.com/spring/spring/commit/a7d33e9acca36cf757d0f90f9c82ce8cf8144d50
* https://github.com/spring/spring/commit/dc7507ce88fe56038922a6fe7ed4e6f1341ef888
* https://github.com/spring/spring/commit/fdbdfe4977df8101a238326f050161a207381a84
* https://github.com/spring/spring/commit/1fc7397aeffdcad1e411465501c3c6307f917e21
* https://github.com/spring/spring/commit/49f60dfea913a290f1cbbed52f8c41b9df5ddd54
* https://github.com/spring/spring/commit/5777dd9292b4fb13955bf9ee81a1213f2dfea186
* https://github.com/spring/spring/commit/0139916d0e27ad670c8eeedcb29ad7bbbb4beae3
* https://github.com/spring/spring/commit/a255f7fd194cd23ec0f002b68463d00ba9027aec
* https://github.com/spring/spring/commit/41f7e7bd5f7c231ce74a38fa477910759cc123dc
* https://github.com/spring/spring/commit/62d3bb6f3484e0ede7d794a3a063c69580ee2bfd
* https://github.com/spring/spring/commit/f2399e7b7b0169ae6e08dedb2292f9ea94baefba

PRs (only if they also end up in develop):

 * https://github.com/spring/spring/pull/342
 * https://github.com/spring/spring/pull/350

**Comment by sprunk** [comment]
>I don't want to touch camera fixes (eg spring/spring@709a8b4) because I have heard of no camera bugs and they could possibly stray into rendering.

This one already affects rendering:

https://i.imgur.com/KQLA2PU.jpg

(see https://springrts.com/mantis/view.php?id=5805 )

**Comment by ashdnazg** [comment]
indeed, https://github.com/spring/spring/commit/709a8b4 should be in

**Comment by sprunk** [comment]
added to the list

**Comment by ashdnazg** [comment]
I'm also adding:
https://github.com/spring/spring/commit/e6aa01612d88a348bfafdf238ddf453a9dfb1c99
https://github.com/spring/spring/commit/a6a8be4a8a773fcbdfc80df07c494a7b857daf85
https://github.com/spring/spring/commit/75b7e4a53b0580c55da53ec1ac9d3e1c0e326d24
https://github.com/spring/spring/commit/9ca7fd3e163ef159f22ad42e95c932b146ac832e
https://github.com/spring/spring/commit/eb35cc677f0d4221327aa1950ec9102cbe9ad2ee

https://github.com/spring/spring/commit/9d8dda91fc766bc3d6bd3e3784e1f1f34843018d
https://github.com/spring/spring/commit/e9789a7a66a5497c244e04bf27b2bb171e410d5b

https://github.com/spring/spring/commit/d61cdb1479de138286c36ba14888263c87f17a23
https://github.com/spring/spring/commit/17a5deaebd218b622aa833eda0299111d30f4f08
https://github.com/spring/spring/commit/cc986584f065ee48fcd610035ad8d3a5a28378d3

https://github.com/spring/spring/commit/cbf41336ae51688fddb99703e34e98c30d6845be
https://github.com/spring/spring/commit/727d896f15b7c8ddfb4bc08887196aa7339eb183

https://github.com/spring/spring/commit/cf67e7ca2eea857e1760fdf9e3c4f0fa66c37f6c

https://github.com/spring/spring/commit/a3077a566bc655551be5d1f32984c137bd266611



https://github.com/spring/spring/commit/409dc374a104372032b6a6ca6d332919059548b0
https://github.com/spring/spring/commit/d9d3f8a4043f93f68b69d7c6e3353f8c49b290b9
https://github.com/spring/spring/commit/4b85028cb5869b8e3a7d19503337732045dd87d4
https://github.com/spring/spring/commit/01af51b77962661839a580049f25cd26710ae331
https://github.com/spring/spring/commit/ee180e4431c76c1e711d1f89599f0e7f19669266
https://github.com/spring/spring/commit/d62a196a41020e99fa40d21677ac8a7d73bea351
https://github.com/spring/spring/commit/7c35528eebd8f0234cf116df049991e32835fbaa
https://github.com/spring/spring/commit/fb002800b8b0ecaf94d958ff4fe231936a210df0
https://github.com/spring/spring/commit/58fd2b2813647fd23e5588a85c64cf1e0429de1d

https://github.com/spring/spring/commit/846139ce17dc4b42c6ee3f45ec9fe734badb4d55
https://github.com/spring/spring/commit/205994c8a6e17d6d246f9381d3cbe42952c3ae25

https://github.com/spring/spring/commit/8c3e2e1298c5722b81335589518d7657662c6067

https://github.com/spring/spring/commit/ba8c2b9d818434dd866f4f07ae6d93c7f3d875c3

https://github.com/spring/spring/commit/bc04cfc97999625076f93ad81d9ce1ce7d6b4e4f
https://github.com/spring/spring/commit/164b5c9f011b7f8bcc68a9bbc027e28df74f2739

https://github.com/spring/spring/commit/b191059c62f8b005be3b1620e70813648b9254c0

https://github.com/spring/spring/commit/b191059c62f8b005be3b1620e70813648b9254c0
https://github.com/spring/spring/commit/152625e4ab5b69ad80d1adeb432bb4e4956b4bb6
https://github.com/spring/spring/commit/8f413a6a5bb497709bbd5df709e72b2952f7f075
https://github.com/spring/spring/commit/ef732616e809b540f0b1314f00cea23d30f84014
https://github.com/spring/spring/commit/08877c8314fcc67722138f295716e3c3800d329d

https://github.com/spring/spring/commit/49b9177a45a6d0a15313cd4708d97402bd6762b1
https://github.com/spring/spring/commit/98cca2f4a7e22f166b7dc2cb2ff8acae675e8e49
https://github.com/spring/spring/commit/2c14bcf31f907e4ceadb82fc0cb0643d5e20bcbf

**Comment by GoogleFrog** [comment]
That is a lot of commits. There are now changes to fonts, audio and GL. Have you included everything that isn't directly related to the GL4 upgrade? The risk here would be too high for me but you can make this version and I'll try it out. I'm yet to be convinced that bug reports about the branch will be useful.

**Comment by ashdnazg** [comment]
Are there changes to GL? I'm pretty sure there aren't

**Comment by GoogleFrog** [comment]
Engine is live.

**Comment by sprunk** [comment]
#engineLives
