### ISSUE TITLE
Builder trying to vacate construction area walks into factory, fails to make progress

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#2551]
```
<Firepluk> so, I think pathfinding related
<Firepluk> I made a queue of solars but my com was standing on one
<Firepluk> so when it tried to build it, com had to go out of this zone
<Firepluk> and guess where it tried to go?
<Firepluk> inside my factory which it couldnt do
<Firepluk> so queue literally frozen
<Firepluk> it could not go into factory and could not continue building...
<Firepluk> need to find replay I guess
```

**Comment by dchilot** [comment]
http://zero-k.info/Battles/Detail/471545

**Comment by hedgehogsthateat** [comment]
Does anyone know where I might be able to look for the bug?

**Comment by Sgathec** [comment]
What makes units vacate the construction area?

**Comment by let4be** [comment]
Yea, this is exactly this replay I was complaining about!
queue was totally locked due to this pathing bug

**Comment by GoogleFrog** [comment]
A pathfinding issue has been fixed since so this needs to be reproduced in sterile conditions. Perhaps bugger off is broken again.

**Comment by sprunk** [comment]
Both pathing and bugger-off have received many changes since. Also reported by Firepluk who doesn't play anymore so unlikely there would be feedback.

**Comment by let4be** [comment]
lob
