### ISSUE TITLE
New trailer stuff

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2552]
This issue is here to hold links and such pertaining to the new trailer project(s).

**KR's Nuclear Winter trailer**
Files are in [Google Drive](https://drive.google.com/drive/folders/0B9K5PLVfeWZvemlkcE5qb28xR0k?usp=sharing). Includes raw .flv videos (shot with OBS), Shotcut project and other odds and ends.
[Current draft on YouTube](https://www.youtube.com/watch?v=aqkr-qhPbSU&feature=youtu.be)

**KR's Tabula Trailer**
[Script by GoogleFrog](http://etherpad.springrts.com/p/zktrailer)
Files are in [Google Drive](https://drive.google.com/drive/folders/0B9K5PLVfeWZvamRwcmRFZXRFa0U?usp=sharing)

**Extension to Sprang trailer**
[Current draft on YouTube](https://www.youtube.com/watch?v=nVinDab3Tu4)
Files are in [Google Drive](https://drive.google.com/drive/folders/0B9K5PLVfeWZvcEFLRVo2bHE4NTQ?usp=sharing)

[Etherpad with some stuff](http://etherpad.springrts.com/p/zktrailer)

Others working on a trailer can put their stuff here as well (although a new issue may be preferable).

**Comment by The-Yak** [comment]
Nice footage. Some of the shadows in that youtube draft look very low quality.

**Comment by The-Yak** [comment]
Last youtube link under "Extension to Sprang trailer" is broken.

**Comment by KingRaptor** [comment]
Oops. Fixed, thanks!

**Comment by KingRaptor** [comment]
Trailers have been finalized for Steam; closing this issue.
