### ISSUE TITLE
Look at this beginner AI game

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2553]
http://zero-k.info/Forum/Post/177298#177298

**Comment by sprunk** [comment]
I took a look.

The bot's army consisted of 1 rocko and 1 jethro which wandered the map a bit and then returned to its base where the rocko died in the 17th minute when the player attacked. The AI then made a replacement rocko which soon died alongside the cloakyfac. The AI comm escaped and made a 2nd base with a spiderfac which produced a scary army consisting of 1 Flea which protected its base from the player's Grizzly (the fac tried to make a Tarantula but didn't manage to). The spiderfac base died but the AI com again escaped with a contingency plan: it made a 3rd base with vehfac which produced 1 Dart (at about 25 minutes) escorted by 1 Crasher. This was the last base.

The defense of the AI base consisted of up to 5 LLT's and one HLT (in all bases, the player was shy to attack). Against the first base the player sent a handful (about 5-7) Archers which died to this defense. Later there was a Grizzly which mopped the first base up. The second base (spiderfac) managed to also get a HLT and killed the damaged Grizzly but by this time the player had Warriors, Scythes and Scallops. These waited around and the third base died to a Dante.

The AI economy was up to 7 mex+solar pairs, at some point also a nano. The whole base tended to be small and cozy, about 2000 elmo in diameter.

**Comment by GoogleFrog** [comment]
Sounds good.
