### ISSUE TITLE
Get rid of or mass rename voices

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2557]
https://github.com/ZeroK-RTS/Zero-K/tree/master/LuaUI/Sounds/Voices

Ctrl - F "arm" - 211 results
"core" 128 results

**Comment by sprunk** [comment]
I'd be for removal, the voices are mediocre at best.

**Comment by GoogleFrog** [comment]
These files are from somewhere that isn't TA, I don't know where. They are for the unused voices widget.

Renaming filenames goes beyond this. Model and texture names are generally pretty awful.

**Comment by sprunk** [comment]
CEGs, too #2190
