### ISSUE TITLE
Terrain rendering bug

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2563]
https://i.imgur.com/mox13hF.jpg

https://i.imgur.com/ILYYjFz.jpg

17:00 18 Oct 2017

https://pastebin.com/kNJSwvZh infolog

**Comment by ashdnazg** [comment]
ATI card?
try UsePBO=0

**Comment by sprunk** [comment]
`[f=-000001] [cawidgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_pausescreen.lua"]:147: bad argument #3 to 'glLoadFont' (number expected, got userdata)`

Doesn't look related but is a GL call so possibly pollutes GL state somehow?

**Comment by ashdnazg** [comment]
no, isn't related

**Comment by sprunk** [comment]
User says `UsePBO=0` fixed it.

**Comment by ashdnazg** [comment]
I wish I had an ATI card to actually debug this nonsense.
It doesn't make sense that PBO's won't work on ATI
