### ISSUE TITLE
Pause screen bug

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2564]
`[f=-000001] [cawidgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_pausescreen.lua"]:147: bad argument #3 to 'glLoadFont' (number expected, got userdata)`

https://pastebin.com/kNJSwvZh infolog

**Comment by sprunk** [comment]
Puzzling. The relevant code does not pass anything for the 3rd arg:
`myFont = glLoadFont( fontPath, fontSizeHeadline )`

**Comment by ashdnazg** [comment]
it's in engine, I'll fix it

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/206a105383b5ebfd44c94805ec38881e29b6e2cc thanks!
