### ISSUE TITLE
Strider hub bug

### ISSUE THREAD

**Issue by T-Lama** [ZeroK-RTS/Zero-K#2575]
Happened to me more than once that Strider hub does not allow to build units anywhere in its' range, but shows they can be built outside the range, making it completly useless.

**Comment by sprunk** [comment]
Find a replay where this happens.

**Comment by T-Lama** [comment]
http://zero-k.info/Battles/Detail/473266
Does that every time on this map on that exact spot.
Also it seems ATV striders (Scorp and Funnel) can be made, while others not.

**Comment by GoogleFrog** [comment]
Engine bug: https://springrts.com/mantis/view.php?id=5814

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/b3b1628d3e35df53437fae6d98e306a17e370430
