### ISSUE TITLE
Construction beam does not show correct, as is cloak and singularity does not shine.

### ISSUE THREAD

**Issue by miturion** [ZeroK-RTS/Zero-K#2580]
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1405026/infolog.txt)

[Imgur](https://i.imgur.com/YcvahGv.png)

Spring settings:

High + compatabilty mods and ATI Compatability

3DTrees = 0
AdvMapShading = 0
AdvUnitShading = 0
AllowDeferredMapRendering = 1
AllowDeferredModelRendering = 1
BuildWarnings = 0
BumpWaterAnisotropy = 2
BumpWaterBlurReflection = 1
BumpWaterDepthBits = 32
BumpWaterReflection = 2
BumpWaterTexSizeReflection = 256
CamMode = 1
CamTimeExponent = 4.0
CamTimeFactor = 1.0
CubeTexSizeReflection = 256
CubeTexSizeSpecular = 256
CubeTexSpecularExponent = 100
DisplayDebugPrefixConsole = 0
DualScreenMiniMapOnLeft = 1
EdgeMoveDynamic = 0
EdgeMoveWidth = 0.003
FPSFOV = 90
FSAA = 1
FSAALevel = 8
FontSize = 18
ForceDisableShaders = 1
Fullscreen = 0
GrassDetail = 9
GroundDecals = 5
GroundDetail = 70
GroundDetailBias = 8
GroundScarAlphaFade = 1
HangTimeout = 5
HardwareCursor = 1
InitialNetworkTimeout = 0
InputTextGeo = 0.26 0.73 0.02 0.028
LODScale = 1.000
LODScaleReflection = 1.000
LODScaleRefraction = 1.000
LODScaleShadow = 1.000
Language = en
LastSelectedMap = Tropical
LastSelectedMod = Zero-K $VERSION
LastSelectedScript = Commanders
LinkBandwidth = 0
LogFlush = 0
LogSubsystems = 
LuaAutoModWidgets = 1
LuaShaders = 0
MaxDynamicMapLights = 0
MaxDynamicModelLights = 0
MaxParticles = 25000
MaxSounds = 32
MaximumTransmissionUnit = 0
MiddleClickScrollSpeed = -0.005
MinimapOnLeft = 1
MouseDragScrollThreshold = 0
MoveWarnings = 0
NormalMapping = 1
OverheadMaxHeightFactor = 1.39999998
OverheadScrollSpeed = 50
ReconnectTimeout = 0
ReflectiveWater = 4
RotateLogFiles = 1
ScreenshotCounter = 3
ScrollWheelSpeed = -25
Shadows = 1
ShowClock = 0
ShowFPS = 1
ShowPlayerInfo = 0
SmoothLines = 3
SmoothPoints = 3
SplashScreenDir = ./MenuLoadscreens
TeamHighlight = 0
TreeRadius = 1500
UnitIconDist = 151
UnitLodDist = 9999
UseDistToGroundForIcons = 1.10000002
UsePBO = 0
VerboseLevel = 10
Version = 2
WindowPosX = 0
WindowPosY = 23
WindowState = 1
WorkerThreadSpinTime = 5
XResolution = 1280
XResolutionWindowed = 1280
YResolution = 1024
YResolutionWindowed = 961
snd_general = 100
snd_volmaster = 14
widgetDetailLevel = 2

**Comment by GoogleFrog** [comment]
I think you are using compatibility mode. This is expected behavior for compatibility mode. What I want you to do is to disable standard compatibility mode and enable "ATI/intel compatibility". Then restart the lobby and say whether the map texture bug occurs and attach your infolog.

**Comment by miturion** [comment]
Ah ok. Then there is no problem anymore. Everything shows correct.

The reason I enabled compatibility mode was that I got some map glitch.
Advise from others to enable compatibility mode solved it. I dont see the
map glitch anymore even without compatibility mode, so case solved :).

2017-10-23 1:49 GMT+02:00 GoogleFrog <notifications@github.com>:
