### ISSUE TITLE
Unit default states.

### ISSUE THREAD

**Issue by Radavvadra** [ZeroK-RTS/Zero-K#2583]
Could we have a revision to default unit firestates.
Catapult to hold fire.
Black dawn to hold fire.
Halberd to hold fire.

**Comment by sprunk** [comment]
These are fire-at-will on purpose. It is more important that units fire at all than it is to optimize their fire.

**Comment by KingRaptor** [comment]
Extending from what Sprung said: From a newbie-friendliness perspective (something I got from all that work on tutorials) hold fire should be considered "advanced mode" and thus not on by default.

**Comment by Anarchid** [comment]
> old fire should be considered "advanced mode" and thus not on by default.

It is on by default for bombers, ostensibly because bombers do not automatically chase targets like other idle units who will engage when they have nothing better to do.

It could be good to have bombers able to attack automatically when idling. They do seem to do this on Attack (move) orders.

**Comment by sprunk** [comment]
See #2346

**Comment by Radavvadra** [comment]
Well new players shouldn't be using.

**Comment by Radavvadra** [comment]
Well new players shouldn't be using catapult anyway.
