### ISSUE TITLE
Content error desync

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2588]
https://github.com/ZeroK-RTS/CrashReports/issues/2364
https://github.com/ZeroK-RTS/CrashReports/issues/2365

[f=0014145] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCreated trace=[Internal Lua error: Call failure] Include() could not load 'LuaRules/Configs/customcmds.h.lua'
stack traceback:
	[C]: in function 'sp_CallAsUnit'
	[string "LuaRules/Gadgets/unit_script.lua"]:309: in function 'CallAsUnitNoReturn'
	[string "LuaRules/Gadgets/unit_script.lua"]:710: in function 'UnitCreated'
	[string "LuaRules/gadgets.lua"]:1415: in function <[string "LuaRules/gadgets.lua"]:1410>
	(tail call): ?
[f=0014153] [Sound] Error: [LoadSoundBuffer] unable to open audio file "sounds/weapon/missile/heavy_aa_hit.wav"

Corrupt download?

**Comment by sprunk** [comment]
```
LuaRules/Configs/customcmds.h.lua
sounds/weapon/missile/heavy_aa_hit.wav
objects3d/commsupport5.s3o
objects3d/commsupport5_dead.s3o
```
Multiple missing files from various areas. Very likely corrupt download.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1817

**Comment by GoogleFrog** [comment]
Should be fixed by the new download method.
