### ISSUE TITLE
Expand MapSettingsOverride with Spring.SetWaterParams

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2589]
A big problem with a lot of current maps is poor choice of waterplanecolor, resulting in an ugly colored and/or extremely bright background to the map extension grid. Example map with this issue is Living Lands. A nice texture but bright white fog and background is hard on the eyes, making it harder to focus.

Map extension grid is best used with a black to near-black waterplanecolor, along with proper fogstart, fogend, and fog color settings for a nice edge glow. See Otago 1.1 as an example https://i.imgur.com/ivoNEGZ.jpg

A lot of these maps are featured, used in campaign, played frequently, but there is way too many with this problem to conceivably make new versions of every one.

Would it be possible to expand existing map setting overrides with Spring.SetWaterParams?
 
https://springrts.com/wiki/Lua_UnsyncedCtrl 

I see that it requires cheating, that may be a problem.

**Comment by sprunk** [comment]
It doesn't require cheating.
