### ISSUE TITLE
Allow Chobby to load without internet connection

### ISSUE THREAD

**Issue by scooterx3** [ZeroK-RTS/Zero-K#2594]
Not sure if this goes for Windows, but for Linux, I find that when I run the Chobby executable, it requires a check-in to the server for updates. If it can't connect, it just doesn't launch. 

The request is to allow it so that even if I don't have a connection, I can still get in. That way I can at least play against bots when I don't have an available internet connection.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1851
