### ISSUE TITLE
Default-improve 0AD pines and maybe other bad trees

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2599]
Follow-up to #1669. Many maps use 0AD pines; our engine tree replacement are v2 of that model (ie. looks roughly same but is much superior in quality). These could be default-improved as well, similar to engine trees.

Possibly other custom trees which are ugly could be replaced as well.

**Comment by GoogleFrog** [comment]
Is this now done?

**Comment by sprunk** [comment]
Not yet.

**Comment by sprunk** [comment]
I have discovered that this is not automatable. Maps sometimes use different models under the same feature name, for example there's `ad0_pine_2_xxl`, for whom DSD Deluxe uses the winter variante but Otago uses the autumn one. 

Keeping the ticket open for now because I still want to provide the replacements (just not automatically use them).

**Comment by sprunk** [comment]
As far as I can tell most modders just pick features from other recent/featured maps, so I think the way to distribute the better model would be via modern maps.
