### ISSUE TITLE
Check whether streaming works

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2603]
@dvr333 reported some problems with streaming with 104.0.1-55. It is important that streaming works so this is worth following up on.

**Comment by dvr333** [comment]
Some more details:
The specific issue is fps dropping to about 20 when capturing with OBS (doesn't matter which version or whether it's Studio or Classic)
Running the game in fullscreen or borderless window will cause the issue, as will running it in a window forced by external program to native resolution. However, if said program makes it not native res even by a pixel (ex.1920x1081) then there are no fps issues. 

I've yet to test Manual Borderless with a non-native res setting, nor other games at native res.

**Comment by Anarchid** [comment]
Spring has been using SDL2 since about 98.0, so it's likely not SDL2.

Try to see if there's any difference between 103 and 104?

**Comment by dvr333** [comment]
103-691 seemed to have the same issue yesterday, but I don't recall it having issues when it was contemporary. I can test other 103 versions tonight to be more thorough.

**Comment by GoogleFrog** [comment]
I made this video recently with OBS v0.655b and borderless: https://www.youtube.com/watch?v=EwX87L7CPcA. I have two screens so technically the borderless window was only taking up exactly half my screen space.

We also have a response on the casting crash: https://springrts.com/mantis/view.php?id=5828. Apparently it was a swap buffers crash and it is recommended to disable the steam overlay for ZK while casting.

**Comment by dvr333** [comment]
Well, native resolution of one monitor was what I meant, which Borderless Window automatically does.

I'm thinking it might be f.lux causing the issue. That being installed is the only major difference between now and the last time I was casting regularly.

**Comment by GoogleFrog** [comment]
@dvr333 seems to have streamed fine more recently.
