### ISSUE TITLE
[Linux] Cannot select any dropdown menu items in the Options, mouse pointer is offset slightly (related?)

### ISSUE THREAD

**Issue by fuxoft** [ZeroK-RTS/Zero-K#2605]
I have two Linux bugs that might be related.

First, the Display Mode cannot be changed to anything else than "Borderless Window". When I click the selection, I can see the four possible values but clicking any of it just closes the selection window and does not change "Borderless Window" to anything else. (I actually cannot change any menu options, see the update below!)

As a result of this, I have my XUbuntu top toolbar onscreen all the time (in menu and ingame), which obscures the part of the game screen (i.e. the game runs fullscreen and the XUbuntu toolbar is overlaid on top of it). During all of this, the game thinks that my mouse pointer is about 1 cm lower than it actually is. I.e. when I want to click on something, I have to click 1 cm lower. 1 cm seems to correspond to the height of my XUbuntu toolbar.

**Comment by Anarchid** [comment]
This is a known issue with borderless on linux. Just use fullscreen instead.

Are you compensating for the toolbar-sized shift when clicking the other options?

**Comment by fuxoft** [comment]
@Anarchid As explained above, I am unable to switch to anything else than "Borderless window". I am compensating the mouse position and I see that other options can be selected (there is a dark brown border around them). But when I click to select any of those 4, "Borderless window" remains selected no matter what I do.

**Comment by fuxoft** [comment]
**IMPORTANT UPDATE:** I actually cannot change any options in any submenu! I can toggle checkboxes and move sliders but I cannot change anything that is selectable using submenus.

**Comment by Anarchid** [comment]
Can you please pastebin the contents of your `springsettings.cfg` found in the directory where you installed ZK?

**Comment by GoogleFrog** [comment]
This bug has been reported occasionally. I don't know what would cause mouse clicks to fail on dropdown menus but not fail on anything. The framework used for the UI is at such an abstracted level that I do not see how there can be a platform-specific bug with clicking on a particular UI element. Spring is serving mouse clicks to lua without any knowledge about what is going on in lua.

This is the type of bug that I do not think will be solved unless someone who has the bug is able to investigate it closely.

**Comment by fuxoft** [comment]
@Anarchid Of course, here is the file: https://pastebin.com/F3BSYDdb

Manually setting "Fullscreen" to 1 solves the problem with mouse offset (the top border of game window is now right below the toolbar and they are not overlapping). But it does not get rid of the toolbar completely.

Clicking on dropdown menu items still does not work.

**Comment by fuxoft** [comment]
@GoogleFrog I don't understand Mono but I am very proficient in Lua, if that helps.

**Comment by GoogleFrog** [comment]
Dropdown menu item selection is likely to purely be a lua problem. If you are feeling keen you could clone the main menu repository, https://github.com/ZeroK-RTS/Chobby, to <install directory>/games/zkmenu.sdd. To run the development version of the menu run the chobby wrapper with the argument 'dev'.

The UI framework is called chili, here is the file for dropdown menus: https://github.com/ZeroK-RTS/Chobby/blob/master/libs/chiliui/luamenu/chili/chili/controls/combobox.lua. I would start by checking which mouse actions are registered in combobox using Spring.Echo to output to the file infolog.txt that can be found in the install directory.

**Comment by fuxoft** [comment]
@GoogleFrog OK, I have done that and I can now play with it. Can I manually force flushing the output to infolox.txt? The output is buffered so when I watch the file using "tail -f" in another terminal, I don't see the latest output.

**Comment by fuxoft** [comment]
What I am seeing so far is that whenever the function "ComboBox:Select(itemIdx)" is called, itemIdx is always zero...

**Comment by Anarchid** [comment]
I think i just bumped into the dropdown issue myself. 

In my case i was able to select the item by holding the mouse after pressing the dropdown, and then dragging it to release it on the desired item, while clicking to open and clicking to select did not work.

If this matches the behaviour you experience, then i suspect some events may be swallowed unjustly.

**Comment by fuxoft** [comment]
@Anarchid Unfortunately, this does not work for me. When I do whan you describe, releasing the mouse button has no visible effect at all. I have to perform a second click to actually select an item in the dropdown menu (and close it). This is the same in the stable version and the development version.

**Comment by Anarchid** [comment]
*Two* separate failure modes on one component? Now this just keeps getting weirder and weirder.

**Comment by GoogleFrog** [comment]
I was able to reproduce this on windows by clicking on things in a certain way. I assume the click handling for linux varies such that clicking like this is common.
