### ISSUE TITLE
[Linux] Mono keeps running when the game shuts down

### ISSUE THREAD

**Issue by fuxoft** [ZeroK-RTS/Zero-K#2606]
When I start the game from the terminal window (using "mono Chobby.exe") and then quit it, the terminal says "Chobby.exe Information: 0 : Chobby closed connection" but mono keeps running and command prompt never appears. I always have to use Ctrl+C to get back to the command prompt.

**Comment by sprunk** [comment]
Moved to the proper repo https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1905
