### ISSUE TITLE
Does not work on Debian 9

### ISSUE THREAD

**Issue by rwe87ywuifhwuirewhui** [ZeroK-RTS/Zero-K#2608]
After following [your installation instructions](http://zero-k.info/Wiki/Download), the game doesn't start on Debian 9.

1. the game tries to self-upgrade each time I click on "Zero-K.exe". Is is possible to avoid this self-upgrade and just start the game?
2. Spring aborts with error code 1: `[GR::CreateGLContext] error ("Could not create GL context: BadValue (integer parameter out of range for operation)") creating main GL3.0 compatibility-context`
3. after the crash, the shell is stuck in an infinite loop searching for Steam `[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed. [S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.`. I don't use Steam, so how can I stop this?

**Comment by gajop** [comment]
Seems like you don't have OpenGL drivers that support 3.x .
Consult the Debian manual on how to install newer drivers for your GFX card if that's possible.

**Comment by sharpaper** [comment]
Is there any option to run in "compatibility mode" using OpenGL 2.x? Maybe with some features disabled, or some glitches, but not crashing?

**Comment by GoogleFrog** [comment]
No. Spring does not support anything lower than OpenGL 3.0. Since OpenGL 3.0 is already old no support for anything lower than it is going to be added. If this ticket is just about missing OpenGL then it can be closed.

**Comment by sprunk** [comment]
There are 2 more issues but they belong to infra.

**Comment by sprunk** [comment]
1)
>the game tries to self-upgrade each time I click on "Zero-K.exe". Is is possible to avoid this self-upgrade and just start the game?

No (that exe is just a wrapper which needs to download the actual game content).

2) As people said above, you need OpenGL 3.0.

3) See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1872
