### ISSUE TITLE
Thunderbird rearm time might be too low

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2609]
Currently Thunderbird rearms in a few seconds. This makes it very powerful when near a base, perhaps too powerful.

**Comment by Aquanim** [comment]
This seems like a reasonable direction to make Thunderbird worse, if such a thing is desired.

**Comment by sprunk** [comment]
9c806f339d4cfd796b134d962f8575190f89a70e
