### ISSUE TITLE
"Zoom in here" doesn't care about location

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2612]
![screen00538](https://user-images.githubusercontent.com/1318249/32685818-15296938-c6ed-11e7-9a25-d41cbf82e1ab.jpg)

Zooming in to the center of the map in the camera tutorials satisfies the zoom in here objective. This is probably on @KingRaptor.

**Comment by KingRaptor** [comment]
ZeroK-RTS/Chobby/commit/eed0fbea8c7c6b48630928048ca6d9e68964533e

Corresponding fix for non-campaign tutorial soonish.
