### ISSUE TITLE
Dominatrix usability

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2615]
Dominatrix is a bit annoying to use. Whether you hang onto a newly captured unit in the middle of combat depends heavily on which Dominatrix deals the final blow. A Dominatrix which is about to die is counterproductive when it deals the final blow. A unit can kill an arbitrary number of Dominatrices if it, each time it is captured, happens to kill the Dominatrix that just captured it.

My solution is to randomly give control to nearby allied Dominatrices when a Dominatrix dies. The radius would be fairly small, 200-300 elmos or so. This would mean to take back control of your units you would have to kill an entire clump of Dominatrices. Of course, Dominatrix would have to be nerfed in other ways if this change is to be applied.

**Comment by Aquanim** [comment]
By reclaiming (or even killing for reclaim/rez) my Dominatrices can I transfer all ownership to a single Dominatrix which I then park somewhere safe?

A different idea is if a unit has just been released by a Dominatrix, set it to 99% capture. As a bonus this is consistent-ish with other status effects.

**Comment by GoogleFrog** [comment]
In a sense the lack of control is bad UI but I don't think the UI is the place to improve. Any UI for determining which Dominatrix deals the final blow would be too finicky to use. My approach is to reduce the importance of dealing the finial blow.

Sure, you could reclaim your Dominatrices but reclaim is only 50% efficient and resurrect takes a lot of time, energy and specific infrastructure. I assume that with this change nanoframe Dominatrices would not lose control, I do not recall how this works now.

99% capture still puts another Dominatrix up for an additional 8s reload time. It is a decent idea though and is simple. Maybe it is all that is required.
