### ISSUE TITLE
Mission zero checks/changes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2623]
- Check whether command insert properly prevents locked commands.
- Give people access to the force fire and move commands after they have built five Glaives. Many people requested more freedom at this point and teaching attack move is not highly vital.
- Maybe add another enemy unit.

**Comment by sprunk** [comment]
When I tried the tutorial knew beforehand that entire commands can be blocked but I didn't know that legal commands are also blocked for improper targets (eg. in the "do a line move zigzag" part, all move commands that are not onto the marked spots are blocked as well, even if they move the units closer to the goals) which looked bugged at first. I think it would be good if blocked commands gave an indication that they are registering correctly but are blocked for the purpose of tutorial.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/ed4cb4a534df184221e214b158131a049a96d387

**Comment by KingRaptor** [comment]
N.B. I was planning to do the command blocked notification as well, but that will require more work. Also I don't have any good ideas other than text briefly floating at the location where the blocked command was issued.

**Comment by sprunk** [comment]
Remember [the old command FX that would draw a bouncy diamond of sorts](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_command_indicator.lua)? This, but a red X.

**Comment by GoogleFrog** [comment]
Done.
