### ISSUE TITLE
Invalid units can have teleport commands queued onto Lamp

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2630]
For example structures can have a teleport order if you right click on a Lamp with mobile units selected. These orders should be blocked.

**Comment by sprunk** [comment]
Possibly related #2621

**Comment by GoogleFrog** [comment]
![screen00580](https://user-images.githubusercontent.com/1318249/32987808-5e580ac6-cd49-11e7-9c8f-13bf7c463313.jpg)

Even more serious than expected.

**Comment by sprunk** [comment]
Looks like a check for buildings already existed:

https://github.com/ZeroK-RTS/Zero-K/blob/3689b575366c90e27abd4bfa74ed1c91257e86c5/LuaRules/Gadgets/unit_teleporter.lua#L307-L313

However there is a typo that prevented it from working (`unitDefID` misspelled with uppercase `U`).
