### ISSUE TITLE
Metal icon is missing/fails rendering

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2636]
![miss](https://i.imgur.com/MM7jEqM.png)
![ims2](https://i.imgur.com/mJgUX71.png)

**Comment by DeinFreund** [comment]
http://paste.springfiles.com/view/38a7fbf9

Maybe related to LoadingMT?

**Comment by DeinFreund** [comment]
Now it's back again.

**Comment by sprunk** [comment]
[According to hoko it's an engine bug fixed in latest.](http://zero-k.info/Forum/Post/186377#186377)
