### ISSUE TITLE
Default color scheme not suitable for spectating

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2638]
1) "default" makes this colors https://i.imgur.com/tK4AO5P.jpg
2) simplified does not alter colos based on current team selection, making all players appear same color when spectating

**Comment by GoogleFrog** [comment]
What is wrong? One team is blue-ish and the other team is red-ish. Are you applying simplified through the top left dropdown? In my experience it made different allyteams have different colours.

**Comment by sprunk** [comment]
I interpret 1 as "the allied colours are all dark and the two greens are dull and mould-like". This sounds valid.

I interpret 2 as a duplicate of #1827.

**Comment by Licho1** [comment]
Yes two greens look very very similar, more contrasting colors should be in the palette.
