### ISSUE TITLE
Chobby would benefit from an ability to press ctrl-F10

### ISSUE THREAD

**Issue by Topkack** [ZeroK-RTS/Zero-K#2644]

**Comment by GoogleFrog** [comment]
I am able to press Ctrl-F10 while chobby is running.

**Comment by Topkack** [comment]
I mean customize UI like you are able ingame

**Comment by GoogleFrog** [comment]
That is something + F11. Also, I really don't think it would benefit.

**Comment by sprunk** [comment]
I agree with @GoogleFrog. Also, this is the wrong repository.
