### ISSUE TITLE
Chicken shields sometimes don't appear

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2646]
See https://imgur.com/a/qtmc5

**Comment by Connetable** [comment]
I am wondering whether the shield is not only non-apparent, but also non existent in the game. They seem to die very fast.

**Comment by KingRaptor** [comment]
Rafflesia doesn't seem to have the issue. I have been unable to determine what causes the difference from Toad.

**Comment by Connetable** [comment]
What is Rafflesia ?

**Comment by KingRaptor** [comment]
> What is Rafflesia ?

Chicken static shield (`chicken_rafflesia`)

Addendum: Toad shield appears to indeed work (tested with LLT shooting from outside the shield), just not drawn.

**Comment by Connetable** [comment]
At least "balance" is not affected then.

**Comment by sprunk** [comment]
5471d768381ef876f7f6d0e418e7e1a2d37e925f
