### ISSUE TITLE
Replace 3do models

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2652]
Ideally the remaining 3do models would be replaced. They are fairly low quality and harder to work with. They aren't completely terrible so this is not urgent and requires modeling work (scarce commodity).

Here's the list:

Currently used models of used units:
- [ ] `shiptorpraider.3do` **Hunter** (Torpedo boat)
- [ ] `Armtick.3do` **Imp** (EMP bomb)
- [ ] `roost.3do` **Chicken roost** (Chicken spawner)
- [ ] `noruas.3do` **Ultimatum** (Anti-strider)
- [ ] `subtacmissile.3do` **Scylla** (Tactical missile sub)
- [ ] `ARMcybr.3do` **Likho**  (Heavy bomber)
- [ ] `armartic.3do` **Faraday** (EMP turret)
- [ ] `armcrabe.3do` **Crab** (Heavy spider)
- [ ] `corgrav.3do` **Newton** (Gravity turret)

---
Models of unused units 
- [ ] `shiptransport.3do` **Surfboard** (transport/fireplatform ship)
---
Unused models
- [ ] `lazer.3do` Old Starlight
- [ ] `armcom5.3do` Old Strike Commander size clone
- [ ] `armcom4.3do` Old Strike Commander size clone
- [ ] `armcom.3do` Old Strike Commander size clone
- [ ] `armcom2.3do` Old Strike Commander size clone
- [ ] `armcom1dark.3do` Old Strike Commander size clone
- [ ] `armcom3.3do` Old Strike Commander size clone

**Comment by Anarchid** [comment]
Armcom\d is not used anywhere to my knowledge, has a replacement in strikecom adn should not have been counted.

**Comment by sprunk** [comment]
`/dev/null` is a valid replacement in such case.

**Comment by Anarchid** [comment]
Oh, i thought corgrav was the gravity strider.

**Comment by sprunk** [comment]
Gravities `gorg` was an outlier and had not been counted.

**Comment by Phytophyte** [comment]
Is there a more preferred file format?

**Comment by Anarchid** [comment]
I would recommend Collada (.dae) initially. It can be converted to Spring's own s3o format once the model is finalized.

Some unit name translations:
* `noruas.3do` - Ultimatum

**Comment by GoogleFrog** [comment]
This is quite a useless list. The unused models should be culled. There should be a distinction between units that need redesigned models and those that just need a technical update. I prefer technical updates because much less can go wrong and less work is required of me.

**Comment by Anarchid** [comment]
I've updated the list to clearly separate unused things from everything else.

I don't think any of the models in the "actually used* list fully *require* a redesign. However i also think that all of them could benefit from a redesign as long as the new design is good.

**Comment by sprunk** [comment]
Duplicate of #4667.

> This is quite a useless list.

\<snarky remark.txt\>
