### ISSUE TITLE
Lua OOM

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2660]
https://github.com/ZeroK-RTS/CrashReports/issues/2775
https://github.com/ZeroK-RTS/CrashReports/issues/2776
https://github.com/ZeroK-RTS/CrashReports/issues/2777
https://github.com/ZeroK-RTS/CrashReports/issues/2778
https://github.com/ZeroK-RTS/CrashReports/issues/2779
https://github.com/ZeroK-RTS/CrashReports/issues/2780
https://github.com/ZeroK-RTS/CrashReports/issues/2781
https://github.com/ZeroK-RTS/CrashReports/issues/2782
Crashed multiple people

Replay:
https://drive.google.com/open?id=1RIvzblXX-UGHuQ62dH7bzSgx6WmfnOEp

**Comment by sprunk** [comment]
Ancient version, many advances to Lua memory management since then (tripled pool size + some GC tinkering)
