### ISSUE TITLE
Disable space to show tooltip while chatting

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2664]
Whenever you press space in a chat message there is a flash of tooltip under the mouse cursor.

**Comment by sprunk** [comment]
Needs https://github.com/spring/spring/pull/358

**Comment by GoogleFrog** [comment]
You mean needs massive hax.

**Comment by sprunk** [comment]
No, just add `and not Spring.IsUserWriting()` here:
https://github.com/ZeroK-RTS/Zero-K/blob/601955e87e50f1c2cc68659cbbcf6afc900f05dd/LuaUI/Widgets/gui_chili_selections_and_cursortip.lua#L2067

**Comment by GoogleFrog** [comment]
https://github.com/spring/spring/pull/358 is an unmerged pull request to an engine that has not been tested in quite some time.

**Comment by GoogleFrog** [comment]
Not fixed for practical purposes.

**Comment by sprunk** [comment]
Done in engine.
