### ISSUE TITLE
Tremontane Map File Required

### ISSUE THREAD

**Issue by Mafiasto** [ZeroK-RTS/Zero-K#2667]
Hey guys, Loving the game! Been playing the campaign, but whenever I go to play Tremontane I get a message saying the map file is required, and will download, But it does this every time I click it and doesn't download anything. Hopefully the snip below shows it. If it matters, I got the game off the site, and I run it on windows. I tried reinstalling and restarting the game and campaign, still nothing. 
![capture](https://user-images.githubusercontent.com/34495163/33917009-d0cb619c-df79-11e7-8105-84331d7b8ca8.PNG)

**Comment by The-Yak** [comment]
User manually deleting map file and trying again resolved the issue.

**Comment by GoogleFrog** [comment]
The map was Avalanche v3.1 http://zero-k.info/Maps/Detail/56103. Some logs would be nice because recent changes were made to map downloading which check hashes for file corruption safety.

**Comment by GoogleFrog** [comment]
Wrapper or chobby.

**Comment by Mafiasto** [comment]
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K/files/1556835/infolog_full.txt)
Here's the info log as requested GoogleFrog. It's posted on the other one as well.
