### ISSUE TITLE
Pressing "Reset Hotkeys" in ingame menu has broken some shortcuts for me

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2669]
Tab is now bound to both overhead view and player menu, holding tab to see the menu triggers rapid camera zooming up/down. Yet in Settings/Hotkeys/Camera, Overview mode is set to None.

F5 no longer hides interface. Can't find any function to bind show/hide interface.

**Comment by sprunk** [comment]
[Could you check whether Ctrl+F1, F2... F5 change camera?](https://github.com/ZeroK-RTS/Zero-K/issues/2562)

**Comment by The-Yak** [comment]
None of those do anything.

**Comment by GoogleFrog** [comment]
This looks like an old epicmenu feature, I don't trust it.

**Comment by Topkack** [comment]
I guess i have the same "problem" just never knew what caused this

**Comment by The-Yak** [comment]
Tab menu is nearly impossible for me to use now. Someone please tell me how to fix this.

**Comment by sprunk** [comment]
Go to `(Zero-K install folder)/LuaUI/Configs/` and delete `zk_keys.lua`.

**Comment by The-Yak** [comment]
No apparent change after deleting zk_keys.lua. Tab still causes camera to rapidly move up/down.

**Comment by The-Yak** [comment]
Screenshot bindings are also broken. f12 is bound to jpg screenshot but pressing does nothing.

**Comment by sprunk** [comment]
Try deleting both `LuaUI/Config/zk_keys.lua` and `LuaUI/Config/zk_data.lua`.

**Comment by sprunk** [comment]
Try deleting both `LuaUI/Config/zk_keys.lua` and `LuaUI/Config/zk_data.lua`.

**Comment by GoogleFrog** [comment]
> Tab is now bound to both overhead view and player menu, holding tab to see the menu triggers rapid camera zooming up/down.

Oh, you are using COFC. All bets are off in that case.

**Comment by Anarchid** [comment]
I am using COFC and i dont have this issue currently. But i also did not press reset. IIRC COFC may have a setting to suppress tab overview.

**Comment by The-Yak** [comment]
I think this can be closed by https://github.com/ZeroK-RTS/Zero-K/commit/ea61a4dbe3dd5c7f83b64b39297faac7b6f5cf6d
