### ISSUE TITLE
Chobby blackout on Skirmish button press

### ISSUE THREAD

**Issue by T-Lama** [ZeroK-RTS/Zero-K#2672]
There is a very rare bug, where Chobby goes black screen with cursor only, after pressing some of the buttons/tabs with last being the Skirmish button (maybe it takes 2 presses there, where first do nothing, not sure about that).
It is not easy to reproduce that consistently, sadly.

[20171116051410_infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1564521/20171116051410_infolog.txt)

(Crap, now I see there is a whole category for Chobby issues, pls move this thread :P )

**Comment by GoogleFrog** [comment]
That infolog does not have any errors in it and I think this bug must be an error. Look at adjacent log files in case you uploaded the wrong one.

**Comment by sprunk** [comment]
No feedback and wrong repo. If this happens again, make the new ticket in Chobby repository: https://github.com/ZeroK-RTS/Chobby/issues/new
