### ISSUE TITLE
Energy is not shared correctly

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2674]
It is possible for one player to have 60 income and 0 usage (except for OD)
And second player having ~0 income.

Energy is meant to be shared within team before it is used for OD.

**Comment by GoogleFrog** [comment]
I think I need a replay or a precise list of units to spawn for some nullAIs.

**Comment by GoogleFrog** [comment]
Likely fixed https://github.com/ZeroK-RTS/Zero-K/commit/05690852f2da24b9e31116bf682b66fb7bd00783.

**Comment by DeinFreund** [comment]
http://zero-k.info/Battles/Detail/482698

I spent 5 minutes building a storage at 0.4 m/s while none of my 9 teammates felt like giving me any energy. We had energy going into OD instead.

**Comment by GoogleFrog** [comment]
Almost your entire team was stalling energy and you had approximately zero energy going to overdrive.
![screen00002](https://user-images.githubusercontent.com/1318249/34852661-ea9e6ec6-f783-11e7-8b08-09aa00fd681b.jpg)

**Comment by DeinFreund** [comment]
I don't know how you define no OD, but this looks like OD to me:
![nood](https://i.imgur.com/DnQlYB1.png)

This mex alone is using more energy than I'm getting at all:
![mex](https://i.imgur.com/CV0knn6.png)

Ingame time of screenshots 11:13

**Comment by GoogleFrog** [comment]
It's good that you have said a time.

**Comment by GoogleFrog** [comment]
This situation was resolved.

**Comment by Licho1** [comment]
I think it should be shared like metal is. It helps with team cooperation.
