### ISSUE TITLE
static beam instead of nano-build-cloud & settings are resetted every restart

### ISSUE THREAD

**Issue by Ubimo** [ZeroK-RTS/Zero-K#2682]
Sigero and I do not see the smoke nano-build-cloud since today. It's a static beam effect.
We both have AMD cards,

Also graphics settings do not stick after lobby restart. Graphic settings always gets resetted.

**Comment by mojjj** [comment]
settings in general are reseted on chobby restart. icon distance, custom label draw shortcut,...

**Comment by GoogleFrog** [comment]
Attach infolog.txt and IGL_data.lua. Check the state of ATI/Intel Compatibility 

Graphics settings persist for me correctly. Icon distance and label draw shortcuts are not configured in the menu so attach zk_keys.lua and zk_data.lua as well.

**Comment by Ubimo** [comment]
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1574926/infolog.txt)

[IGL_data.lua.txt](https://github.com/ZeroK-RTS/Zero-K/files/1574932/IGL_data.lua.txt)

**Comment by Ubimo** [comment]
rename IGL_data.lua.txt to IGL_data.lua

**Comment by GoogleFrog** [comment]
Wait a bit while I make jumpjets, then retest.

**Comment by Ubimo** [comment]
What?

**Comment by GoogleFrog** [comment]
Try with the recent release.

**Comment by Ubimo** [comment]
There was no new release via steam...

**Comment by Ubimo** [comment]
Graphics setting still reset after chobby restart...

**Comment by Ubimo** [comment]
I uninstalled steam version and installed non-steam version. All OK now.
