### ISSUE TITLE
Most water setting overrides don't work

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2683]
surfacecolor and absorb work so far that I've tested. The rest return Unknown array key errors.

planecolor is also known not to work but this is due to current engine limitations.

Sorry for monster infolog: http://paste.springfiles.com/view/9f90171a

Ctrl-f gfx_sun for relevant errors.

Example config for Aum: http://paste.springfiles.com/view/62e3750a

**Comment by sprunk** [comment]
`minColor` needs capital C, same with `baseColor`. `fresnelPower` is spelled correctly but is a number, not table.

The correct spelling and data types for all keys can be found [here](https://github.com/spring/spring/blob/1bb6c5a160897fa32228cf8e00c3bf9f7c46f5a5/rts/Lua/LuaUnsyncedCtrl.cpp#L1082).

**Comment by The-Yak** [comment]
Thanks sprung, that seems to have fixed all errors.
