### ISSUE TITLE
Idle event not triggering

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2685]
1) build a factory, give it a command (move, fight whatever)
2) build several units

Units clump and stop moving. However, those units that could not get exactly to the point wont trigger idle event.

This breaks autogroup (among other things).

**Comment by Licho1** [comment]
I dont want to enable instant add because i want units to first get to designed point

**Comment by Licho1** [comment]
I also believe its 100% fixable, because units do lose this command. When path clears they dont move at all.

**Comment by GoogleFrog** [comment]
Cannot reproduce https://youtu.be/G5yCS_a4obs

**Comment by Licho1** [comment]
Thats very odd i will try to make a test case, im getting this with bots (glaives etc)

**Comment by Licho1** [comment]
I am still getting this with cloak bots a lot in real games.

**Comment by GoogleFrog** [comment]
Replay?

**Comment by Licho1** [comment]
[20180112_181448_Hide_and_Seek_v03_104.0.1-92-g4409317 maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/1627954/20180112_181448_Hide_and_Seek_v03_104.0.1-92-g4409317.maintenance.zip)

**Comment by Licho1** [comment]
Another game here, at around minute 16, factory has fight command and units clump and stop triggering event.
http://zero-k.info/Battles/Detail/482956

**Comment by GoogleFrog** [comment]
Worked around.
