### ISSUE TITLE
Two replays with buggy attack order behavior

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K#2693]
This is a reminder for @GoogleFrog to check those once he's back from his vacay.

http://zero-k.info/Battles/Detail/480027
http://zero-k.info/Battles/Detail/480033

**Comment by GoogleFrog** [comment]
Crab http://zero-k.info/Battles/Detail/480011.

**Comment by GoogleFrog** [comment]
Crab, maybe Impaler. http://zero-k.info/Battles/Detail/480010
