### ISSUE TITLE
Kick does not work

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2695]
See this replay: http://zero-k.info/Battles/Detail/480186

EDIT: Infolog http://paste.springfiles.com/view/e31e751f

**Comment by sprunk** [comment]
Not a bug. That was a vote to kick a person called `2plus2is5 for waste metal in picket`. This is by design, all specified words need to be found in the nick.

Possibly this design could be changed though, feel free to make a ticket in the infra repo.
