### ISSUE TITLE
Incosistent missile storage display

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2696]
Format is different in menu icon and in hovering icon info:

https://i.imgur.com/SOLMOa5.png

See here 3/7 vs 3/10 , one shows max other shows remaining.

**Comment by sprunk** [comment]
What should the format be?

 * `0/10`, `3/7`, `10/0`?
 * `0/10`, `3/10`, `10/10`?
 * `0+`, `3+`, `10`? Most of the time you have 100 missiles queued which is not reachable in a normal game so the real information is whether more missiles are being built or not.

**Comment by GoogleFrog** [comment]
Do 0/10, 3/7, 10/0 simply because a new missile is not queued upon firing.

**Comment by Licho1** [comment]
I think format should be current/max
Thats the most natural format people expect from the "/" sign.

**Comment by sprunk** [comment]
023a987a55c0dea2327cf0fa1ecbdb41c7986b5c
