### ISSUE TITLE
Initial units in campaign start with stockpile max zero

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#2700]
See planet 55 (trinity) planet 57 (scylla and reef). Ideally behaviour should be consistent with creating stockpiling units normally by building them.

Current normal behaviour is max stockpile 100; this is generally always desirable in the case of Scylla or Trinity, but may not be in the case of Reef.

**Comment by Aquanim** [comment]
This also applies to Artemis (no mission yet).

**Comment by GoogleFrog** [comment]
Stockpile is applied by a widget and pregame units are spawned before luaUI. The widget is likely failing to detect existent units when it loads. This is not entirely trivial to solve (simply iterate units in Initialize) because stockpiles should not increase on luaUI reload.
