### ISSUE TITLE
Deselecting units by type with the unit bar at the bottom of the screen has strange behavior

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2701]
(1)ctrl a select all units
(2)observe all units listed by type at the bar on the bottom, observe tooltip instructions
(3)Shift+Right click to deselect units by type deselects more then what's clicked
(4)middle-click instructions in tooltip are incomplete "Middle-Click: Go To"

**Comment by Anarchid** [comment]
(4) seems to be a valid way to express "Zoom to this unit".

**Comment by GoogleFrog** [comment]
Here is a completion for your instructions:

(-1) Start a game and choose a commander

(0) Spawn 20 glaive, ronin and reaver.

Cannot reproduce. Make a video or more detailed instructions. Say what is selected at each step instead of using references.
