### ISSUE TITLE
Unit roster for Unit Marker

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2704]
I received a complaint that "screamer label doesn't work" and added it: https://github.com/ZeroK-RTS/Zero-K/commit/66c9613ab68717325b4232a35bad55efbb9148df

However on a second look it turns out that Artemis (ie screamer) has never actually been there, and that other dangerous buildings (Lucifer/Anni, Desolator/DDM) are missing as well so possibly this was by design. It would be good to know what the rationale for excluding them was.

**Comment by Sgathec** [comment]
Please include all units that cost more than or equal to 1600 metal (Crab) as options. If Swifts scout an enemy base, the revealed units are visible only for a couple of seconds. I think the Crab is the cheapest one worth adding considering there are maps that have only a little bit of metal.
