### ISSUE TITLE
Scorcher has inconsistent damage when turning

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2705]
Scorchers seem to be able to turn faster than they can rotate their turrets, thus taking care of their rotation is important when microing, especially in early game 1v1. For example a charging scorcher will win against one that turns around and tries to kite, because turning around leads to not being able to fire for a short period.

As ZK vehicles and controls are designed such that careful orientation is not required, would it be possible to uncouple vehicle rotation from turret rotation or increase the weapon turn rate?

**Comment by Anarchid** [comment]
At least on some units, turret position is supposed to matter, for example Minotaurs. Scorchers, though, should be able to aim fast, imo.

I think Fantomas is getting its turret decoupled from its chassis. Didn't try testing it yet.

**Comment by sprunk** [comment]
>Scorchers seem to be able to turn faster than they can rotate their turrets,

As far as I can tell the turret actually turns faster but only updates once per slow update.

**Comment by DeinFreund** [comment]
Both scorchers will full hp:
![1](https://i.imgur.com/PWDJR4g.png)

Blue scorcher starts turning, his gun is completely (~80 degrees) off target:
![2](https://i.imgur.com/ECYCHqp.png)

Blue scorcher finishes turning, has lost half health and done nearly no damage during turn:
![3](https://i.imgur.com/wPXID7e.png)

Red scorcher wins with 50% health remaining:
![4](https://i.imgur.com/VOdiwFp.png)


I think it'd be fine if scorcher would consistently win when charging forward, supporting the aggressive theme. But currently it's a split-second difference that turns effective kiting into suicide, making it inconsistent at best.

**Comment by sprunk** [comment]
52ff9b4cb608e6da8ff19cc527af1adc84a784d2
