### ISSUE TITLE
Mission not working

### ISSUE THREAD

**Issue by PicassoCT** [ZeroK-RTS/Zero-K#2706]
I tryied to run one of those Test Mission Objectives - its not working at all.

https://github.com/ZeroK-RTS/Zero-K/blob/16d3a72de91a51c7074e4d4364b315d22fd6beb5/LuaUI/Widgets/mission_objectives.lua#L272

Its always good to see mad men at work ;)

**Comment by KingRaptor** [comment]
Is this issue report meant to reference the meme, or did you have an actual issue with using the widget?

(Hi Pica! But GitHub ain't a place for telling jokes, you know...)

**Comment by PicassoCT** [comment]
Not a actual Issue... understood- its all serious buisness- as serious as hairless monkeys floating on a rock playing games can get ;9
