### ISSUE TITLE
Do something about blastwing opening

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2710]
Blastwing opening is true cancer on some maps (Ravaged, Isle of Grief on top of my head).

Defending party cannot really do anything to scout it out and make any prevention timely. Even a proactive picket fails, because blastwings approach from cliff side and they are very likely to hit mexes even if shot by picket. After an early eco is destroyed, then the rest of the game becomes uphill struggle. No fun.

http://zero-k.info/Battles/Detail/482377
http://zero-k.info/Battles/Detail/482437

Please consider some change to the unit mechanic or stats.

**Comment by Anarchid** [comment]
My ideal solution to this is gunship physics such that gunships don't have scary unlimited vertical velocity when climbing hills. Their total speed should obey their maxVelocity, taking the vertical component into account. This means that the Blastwing will have to slow its horizontal velocity to climb, and will have to re-accelerate after ascending the cliff, giving defenders the time to shoot it.

Ofc that needs an engine change.

**Comment by lhog** [comment]
Related to what @Anarchid wrote: https://springrts.com/mantis/view.php?id=5864

**Comment by sprunk** [comment]
>Blastwing opening is true cancer on some maps (Ravaged, Isle of Grief on top of my head).

Solution: unfeature Ravaged :þ

**Comment by sprunk** [comment]
Tangentially related (if the path to go is redesign blastwing): #1572

**Comment by sprunk** [comment]
Very related: #2364

**Comment by GoogleFrog** [comment]
Do I have to say something for this to be an acknowledged issue? This has always been the case.
