### ISSUE TITLE
Panther explosion speed is unintuitively slow

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2711]
I would expect the panther (the tank with stun gun) death explosion to spread near instantly, instead it takes nearly a second to actually stun nearby units. Could the explosion velocity be increased?

**Comment by sprunk** [comment]
`tankheavyraid` has EMP explosion so is less like `shieldbomb` and more like `cloakbomb`, which also has slow explosion.

**Comment by DeinFreund** [comment]
The explosion speed should match the animation speed.
