### ISSUE TITLE
Bring back large cursors

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2713]
It makes some sense for large (eg 4K) screens. They are likely to break but that is fine as long as they are hidden behind the advanced toggle.

**Comment by GoogleFrog** [comment]
Don't bring them back, make an option to make the current ones larger.

**Comment by GoogleFrog** [comment]
Done https://github.com/ZeroK-RTS/Zero-K/commit/72746d32708ad48160f6b052d70b2478eafd685f
