### ISSUE TITLE
Maps should signal when they are ready to handle borders

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2722]
For example "Zed" map generates nice lava infinite borders. We generate fake terrain outline over it, which makes it look ugly without reason:
https://i.imgur.com/wCfouqm.jpg

Maps should be able to signal that they are ready to render border.

**Comment by The-Yak** [comment]
It's already possible to disable map borders on islands. It's just not set by default.

**Comment by sprunk** [comment]
[Already exists. Maps that draw their own border can place `nomapedgewidget.txt` in the root folder to prevent the builtin border rendering.](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/map_edge_extension.lua#L18)
