### ISSUE TITLE
First and third ally colours are a bit too similar.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2725]
![image](https://user-images.githubusercontent.com/1318249/35019987-f011ccba-fb7d-11e7-989c-6f1bafd61dea.png)

**Comment by sprunk** [comment]
I think this is mostly an issue with Solar (blue diffuse and hardly any teamcolor). Other units and the minimap look fine.

Still, it's easy to fix by moving the third colour somewhere to the bottom of the list, as the next two colours are very distinct. This loses the "no green teammate" feature but it's not terribly important.

**Comment by GoogleFrog** [comment]
I also had the issue with icons while zoomed out. Perhaps the blue and purple are too close for red maps.

**Comment by sprunk** [comment]
I think the best thing to do is to shift [4-7] to be [3-6] and put current 3 as the new 7.

The cost is that you can get a green ally in MM but the ally-green is fairly distinct from self-ally so should be okay. Alternatively 3 and 7 could swap places.
