### ISSUE TITLE
Units on hold position stutter towards targets

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2729]
https://drive.google.com/open?id=1an-fCm97_O1071QTGFKDXuIxqqQxVnL8

Units on hold position are still given an attack command on enemies within range, this leads to Outlaw and Detriment slowly moving towards their target. This is with smart AI turned off.

This replay was recorded using 104.0.1-141-gae5ba3c, the same applies to 104.0.1-92 except the detriment seems to be affected much more visibly there.

**Comment by GoogleFrog** [comment]
This gadget causes this bug as its primary purpose https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/hax_mantis_5852.lua.
