### ISSUE TITLE
Transportability rule simplification.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2736]
Everything that costs less than 1200 should be light transportable. Cost is the clearest delimiter.

**Comment by GoogleFrog** [comment]
Made a PR but the callin seems to do nothing. https://github.com/ZeroK-RTS/Zero-K/pull/2802

**Comment by springraaar** [comment]
bad idea. That'll include minotaurs and jacks.

won't that even include level1 commanders?

**Comment by GoogleFrog** [comment]
And what is wrong with that?

**Comment by springraaar** [comment]
means you can bypass their mobilty issues and drop them on the enemy base by paying just a small premium from the transports, less than 20% of the unit's cost. They're much harder to take out than 200M riots

**Comment by GoogleFrog** [comment]
I do not expect there to be a large problem, and transports are not highly used as-is. Besides, the high mass of the units in question will make for a low transport speed.

**Comment by sprunk** [comment]
41ae36490188745359e48396426e36e18cd3d563
