### ISSUE TITLE
The default move command from factory exiting can make units stuck if there is something blocking that move command

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#2742]
In this battle, I placed a solar generator a little bit infront of my cloaky factory. This made units pause as they got finished and tried to exit the factory. This delay severely increased the pause between units being produced and severely crippled my ability to make Glaives.
http://zero-k.info/Battles/Detail/485089
https://imgur.com/ofNNke8

**Comment by sprunk** [comment]
A more lenient version of #1586 where units are just delayed instead of fully blocked.

**Comment by GoogleFrog** [comment]
The small move order is automatically placed by the engine. It is detected and replaced with raw move, which is why the Glaive is not stuck permanently. We could look into whether the small move order is required at all.
