### ISSUE TITLE
Phoenix has no jet flame

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2743]
https://i.imgur.com/Y8E1qDs.png

It used to have a flame.
Default settings, nvdia card.

**Comment by GoogleFrog** [comment]
Infolog?

**Comment by Licho1** [comment]
Happens only to phoenix, other crafts are fine
https://i.imgur.com/QdFHnEf.png

[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K/files/1689886/infolog_full.txt)

**Comment by GoogleFrog** [comment]
This was caused by some steam cloud settings nonsense.
