### ISSUE TITLE
Ultimatum: consider return fire by default

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2744]
Unit's should be sensible by default.
Ultimatum tries to target enemy owl and fires dgun on it.
Thats not reasonable.
Also it should probably default to return fire, being a cloak unit that reveals itself on attack.

**Comment by Anarchid** [comment]
> Thats not reasonable.
It is, however, awesome when it works.

**Comment by sprunk** [comment]
Shooting Owl would be fine as long as it hits (so I consider that part a duplicate of #3714). Keeping the ticket open for the returnfire default.

**Comment by sprunk** [comment]
Precluded by e235cc21c44ff206672147662001dc4917c4f214 et al
