### ISSUE TITLE
Campaign markers are rendered on top of UI elements

### ISSUE THREAD

**Issue by Palmer--** [ZeroK-RTS/Zero-K#2751]
![untitled](https://user-images.githubusercontent.com/11057262/35782195-ef79e8c0-09f4-11e8-9c1c-20d84f56a529.png)

**Comment by KingRaptor** [comment]
Was waffling on this for a while, eventually decided to make the text draw under the GUI most of the time while having the arrows indicating offscreen markers still draw on top.

Thanks for bringing this up!
