### ISSUE TITLE
Ground Chickens units don't shoot anymore

### ISSUE THREAD

**Issue by versus666** [ZeroK-RTS/Zero-K#2761]
Missed a week of play and now the chickens ground units don't fire anymore. No melee, no arty, no spikers, no lobbers. Flyers seems ok tho, as is the Queen. Judging from the (lack of) animation of the Cockatrices they don't even AIM anymore so I think the commit #2ad19f149ca5f3c746b5e332370daf89f67da8b9 "Applied rapid reaim time to almost all units" may have something to do with this.

Infolog show no error relative to units, lua or AI ingame.
Spring 104.0.1-151-g11de57d maintenance
Chobby v1.6.2.5
Zero-K v1.6.2.6

**Comment by Licho1** [comment]
damn

**Comment by Licho1** [comment]
GoogleFrog thats why feature freezes and "fix criticals only" policies are needed pre release... many bugs get revealed after significant time
