### ISSUE TITLE
Stop doesn't cancel Set Target command on Likho

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#2763]
For some reason, Stop commands doesn't cancel the Set Target command on Likhos like it does for other units.

**Comment by sprunk** [comment]
Maybe tangentially related: #1164

**Comment by GoogleFrog** [comment]
Maybe it is because set target has to be issued manually for bombers. The widget may be filtering out all commands.

**Comment by GoogleFrog** [comment]
Fixed at some point.
