### ISSUE TITLE
pyro doesnt fire while jumping

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#2764]
Pyro is unable to fire when jumping 
To test: 
Walk pyro into llt range to kill llt.
Get another pyro and llt:
Jump pyro into llt range.

Walking into range leaves pyro with 10% more hp, showing that pyro does not fire during the time of its jump. Perhaps targeting needs fix?

**Comment by GoogleFrog** [comment]
Works for me. Replay.

**Comment by sprunk** [comment]
I can't reproduce. I think this may have been a real issue back when reaim took 15 frames (because a jump is a sudden jolt of movement so invalidates the aim) but not so with fast reaim.
