### ISSUE TITLE
Lobster-shogun horrible inconsistency

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#2774]
It is now possible to lobster transport shogun.
However hercules cannot transport a shogun.

This sould be mitigated by making all ships transportable again.

**Comment by GoogleFrog** [comment]
Doesn't seem like horrible inconsistency to me. Shogun can also be stopped by Placeholder or Newton. Transports are doing some lifting and have limits. But I don't mind either way.

**Comment by Licho1** [comment]
It was of course exageration, because it is quite silly to see shogun lifted by lobster.
My point is, that between lobster and hercules, if only one of them should be able to lift a battleship, it should be the hercules.
So making them both shogun-capable sounds like a good solution to me.
