### ISSUE TITLE
Units don't move onto wrecks

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2777]
Give a unit a move command onto a wreck and it will not move if it is too close. I have observed this at a distance of 200 elmos. Raw move should be able to detect and solve this issue.

**Comment by GoogleFrog** [comment]
This seems hard to reproduce.

**Comment by GoogleFrog** [comment]
A Glaive onto a Stardust death clone seems to reproduce the issue if the Glaive is within 200 elmos.

**Comment by Licho1** [comment]
I see it as a problem.
Wrecks are meant to block a movement of certain units and clog battlefield for llighter stuff.
Glaive crushing wreck of tank is bad.
- it looks unnatural 
- it destroys valuable metal
- it goes counter original idea of wrecks

**Comment by GoogleFrog** [comment]
That is not the topic of the ticket.
