### ISSUE TITLE
cant jump off surfboard

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#278]
fix should be easy (steal force unload from air transports and use it before jump if jumper is surfing).
i might do it on the weekend.

**Comment by xponen** [comment]
can I try? I have experience with Air Transport drop and jumpjet gadget.

I think its simply done by calling the following:
local env = Spring.UnitScript.GetScriptEnv(unitID)
Spring.UnitScript.CallAsUnit(unitID,env.DropUnit,cargoUnitID)

Going to try it first and possibly will inspection jumpjet gadget (maybe tweak some comment or something).
