### ISSUE TITLE
Antinuke doesn't fire

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#2781]
Reported by Znack/Godde on Zero-K v1.6.2.9 
![prob](https://i.imgur.com/BycMOEg.jpg)
Antinuke don't defend against incoming nukes.

**Comment by DeinFreund** [comment]
Replay: https://drive.google.com/open?id=1N4OLZ8YfFfggTsZjh0ktzIo_wVvboN5X

**Comment by GoogleFrog** [comment]
Actually fixed.
