### ISSUE TITLE
Investigate and consider replacing sounds from free-loops.com

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2784]
A long rant on copyright infringement in open-source games has been posted on github https://github.com/saniv/free-game-art/blob/master/foss-copyright-infringement-records.md

Zero-K is specifically mentioned, apparently the site free-loops.com has ripped off some commercial sources and ZK uses some sounds from this place.

Based on our origin.txt files, this site is credited for 6 sound files.

https://github.com/ZeroK-RTS/Zero-K/search?utf8=%E2%9C%93&q=freeloops&type=

teleport_loop.wav - freeloops
bot_move.wav - freeloops
amph_move.wav - OpenGameArt and Freeloops
heavy_bot_move.wav - Golgotha and freeloops
radar_select.wav - freeloops PD
torpedo.wav - Kanoba & freeloops

**Comment by sprunk** [comment]
They're kosher until proven otherwise, and the rant gives no concrete data. They're here to stay.
