### ISSUE TITLE
Implement some form of anti-bait

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2789]
Replace the Return Fire firestate with High Priority Only. This acts like Hold Fire against low priority units and Fire At Will against high priority units. All units have a priority (low or high) that is per enemy team. Some useful default would be set and players could toggle priorities themselves with a targeted global command.

**Comment by GoogleFrog** [comment]
To do this cleanly we need something like AllowUnitTarget in the engine. Returning false from this callin would treat enemies as if they are in the noChaseCategory.

**Comment by GoogleFrog** [comment]
In some cases we need to be able to dynamically modify bad target cats. See artillery vs patrolling mobiles: https://github.com/ZeroK-RTS/Zero-K/issues/2835

**Comment by GoogleFrog** [comment]
See: https://zero-k.info/Forum/Thread/28760

See: https://zero-k.info/Forum/Thread/32384

Especially see:
![image](https://user-images.githubusercontent.com/1318249/102668571-55a09880-41e0-11eb-8d1a-338dde343591.png)

**Comment by GoogleFrog** [comment]
Instead of making one big complicated state, there could be three underlying states which are configured by a visible state. Alternately, there could be 4 generic state and units could have their state be configurable through initial states.

**Comment by Licho1** [comment]
Or we could just go back which I think makes most sense..
Smart AI + 3 state switches.
It's a lot of buttons but I feel myself missing something ever since the change.
Mainly return fire for lots of units (lancer, ultimatum, other cloakers) or proper control over hold-fire like behavior.

**Comment by sprunk** [comment]
Implemented in #3886 and polished by GF.
