### ISSUE TITLE
No way to replace your dead commander

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#2795]
Please consider a method to obtain a new commander after your original one has been destroyed. I think one should only be able to have one at a time because a host of commanders looks odd since the unit is a bit like the "leader" of one's army. I think having a good way to replace a fallen commander would increase the entertainment value of the game if you're inclined to play in a commander-oriented manner.

**Comment by PicassoCT** [comment]
Eject capsule to safety and rebuilt? Not very TA-ish though

**Comment by sprunk** [comment]
Commander being unique is by design.

**Comment by Sgathec** [comment]
Maybe they could be resurrectable then, but I consider that problematic due to wrecks being freely reclaimable by anyone and it seems no one can own them.
