### ISSUE TITLE
Unit collision damage is too high after recent changes

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2796]
[This change](https://github.com/ZeroK-RTS/Zero-K/commit/7e8bc1337dc7b79307e551da35d2676f4f16b6c9#diff-cb807d19caa79f541732e1882dfaaf9c) causes enemy units, that hitting jumpsumo/turretimpulse, deal too much collision damage.

http://zero-k.info/Battles/Detail/487655

**Comment by Sgathec** [comment]
Hello, @lhog, could you approximate the damage verbally, please? I wouldn't like to watch such a long replay.

**Comment by lhog** [comment]
Around 1530 dmg per hit, if hit by a ronin.

**Comment by lhog** [comment]
Tried this today with @Godde and couldn't reproduce it anymore.
Was there some change?

**Comment by KingRaptor** [comment]
[v1.6.2.3 changelog](https://zero-k.info/mediawiki/index.php?title=V1.6.2.3) says it was fixed then.

Thanks for reporting!
