### ISSUE TITLE
The plop icon can persist after plopping

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#2797]
Please look at Alcur after he plopped his second factory. The plop icon could have been only a visual bug.

http://zero-k.info/Battles/Detail/487720

**Comment by sprunk** [comment]
![alcur](https://user-images.githubusercontent.com/2573076/39099501-67a9b050-467c-11e8-9031-cffd7c881322.jpg)

You used the plopless first commander to build the second factory so it was built normally. The green build order line is hard to see in the screenshot but you can clearly see the plopful comm having a move order.
