### ISSUE TITLE
Units recloak extremely fast unless damaged

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2800]
I'm speccing a game of ZK in which:
- Conjurers constantly recloak *while building things*. 
- Ultimatums recloak after firing a shot before they complete the firing animation - fast enough that e.g. a Paladin cannot retaliate before they recloak.
- A sniper decloaked by walking into another sniper, killed it, and then recloaked before the debris hit the ground.

However, damaged units still take the usual while to recloak.

**Comment by Anarchid** [comment]
Also:
- Gremlins practically stay cloaked while firing

**Comment by sprunk** [comment]
I think the solution would be #2801 but I won't be able to test for the next ~6 hours.

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=5906

https://github.com/spring/spring/commit/aa6a76e045e65e165007acac93d4f7ecca91d4fb

**Comment by GoogleFrog** [comment]
Fixed.
