### ISSUE TITLE
Fix fractional frame reload times

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2811]
Weapons that have reload times set in factions of a frame have issues:
 * Their theoretical DPS is misreported in the context menu (and probably on wiki).
 * They are more liable to change their DPS via engine changes.
 * They behave differently with slow damage.

For example the Stardust with 0.12 reload time fires every 3 frames usually but fires every 7 frames when slowed. This means that its weapondef is not being sanitized before it is read by the attributes gadget. See https://github.com/ZeroK-RTS/Zero-K/commit/b23326b36fb8c107fdb37c14c4453829db2f0195.

When changing a weapondef make sure to use empirical DPS to ensure that its DPS is unchanged.

**Comment by sprunk** [comment]
No weapon with fractional frame reloadtime was affected.

One weapon with "exact" frame reloadtime was affected. Commander LG def says `1 + 25/30` reloadtime (= 55 frames) but actually was 54 frames. Now it has 55 as stated in def.
