### ISSUE TITLE
EpicLawn map load error

### ISSUE THREAD

**Issue by jiefue** [ZeroK-RTS/Zero-K#2813]
When play skirmish load EpicLawn map error ，the game crashed !

the map link :http://zero-k.info/Maps/DetailName?name=EpicLawn&

**Comment by GoogleFrog** [comment]
Can you attach your infolog?

**Comment by jiefue** [comment]
have upload infolog_full yet , is this ok?

**Comment by sprunk** [comment]
I predict the infolog to say the map was just too big.

**Comment by GoogleFrog** [comment]
The map may just be broken. It has no support.

**Comment by jiefue** [comment]
Bty , what is the map size upper limitation of the game ?

**Comment by sprunk** [comment]
Game has no limit but your PC might be too weak.

**Comment by sprunk** [comment]
Nothing can be done gameside. Possibly the infra could stop accepting shitmaps but apparently we take pride in [our](http://zero-k.info/Maps/Detail/9844) [wide](http://zero-k.info/Maps/Detail/37741) [map](http://zero-k.info/Maps/Detail/34488) [pool](http://zero-k.info/Maps/Detail/30133).
