### ISSUE TITLE
Fealthas says that they have FPS drop on camera movement

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2819]
Apparently their FPS drops from about 60 to 20 when they zoom or scroll. They think it is the new engine.

**Comment by Licho1** [comment]
I have it same but i dont think its new engine, i have what i call "scrolling lag". It might be engine but probably last good one was pre 0.91 :-)

**Comment by GoogleFrog** [comment]
They said that they have some general windows bug with 3D apps.
