### ISSUE TITLE
Players going AFK appears to make the game laggy

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#2822]
I believe some people have been complaining about the whole game slowing down because of someone having his/her units automatically transferred to another player.

**Comment by GoogleFrog** [comment]
Then use the latest version and do a large manual unit transfer to test. Otherwise you're just guessing.

**Comment by Sgathec** [comment]
@The-Yak says it happens many times in http://zero-k.info/Battles/Detail/489353 . 

He told me that the player Connetable going AFK makes it happen the first time.
