### ISSUE TITLE
Allow option to disable "return fire" firestate.

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#2831]
Toggling between hold fire and fire at will can be useful. I have never wanted to use return fire though, and it ends up being just an extra click that you have to do.

**Comment by sprunk** [comment]
You can rightclick to go back from Hold Fire to Fire At Will (it cycles in the other direction).

**Comment by GoogleFrog** [comment]
There is already a widget for this.

**Comment by Fealthas** [comment]
Which one?

**Comment by sprunk** [comment]
Settings / Interface / Commands / Enable return fire state
e235cc21c44ff206672147662001dc4917c4f214
