### ISSUE TITLE
Vamps/hawks/whatever

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#2832]
When these units fire, due to the added glow of weapons, they turn completely white/blue. Its manageable if there are like 1 or 2 hawks, but once you get more it becomes very difficult to see what is happening.

Solution:
Reduce max possible brightness of this effect.

This also happens for dantes, ravagers, scorchers, glaives. Their weapon lights overpower everything else.

**Comment by sprunk** [comment]
Duplicate of #1968

**Comment by GoogleFrog** [comment]
That is not a feasible solution.
