### ISSUE TITLE
Claymore barrel shenanigans in dev engine

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#284]
They home back to the launch point
http://zero-k.info/Battles/Detail/299817

**Comment by Orfelius** [comment]
I can't relate to the past behavior of the unit (because engine fails to download) but the bug seems to have escalated into bouncy hell of depthcharges. See the replay for proof: http://zero-k.info/Battles/Detail/350038

**Comment by Orfelius** [comment]
It seems like the bouncy hell has reappeared as witnessed in this video: https://youtu.be/DuTfp7GE1Y8?t=19m30s
However so far I was unable to replicate that behaviour.

**Comment by GoogleFrog** [comment]
This bug is that manually dropped depthcharges home back to the Claymore if they are dropped in water. It is also an old report. If you find something new make a new report.

**Comment by sprunk** [comment]
The new thing is no different to homing missiles cirling in the air after killing a plane.

**Comment by Orfelius** [comment]
Is it a desired effect though?
It still looks ridiculous.

**Comment by Anarchid** [comment]
Maybe there is a more general version of this: are circling missiles good? We have the technology to make them retarget - into nearby enemies, into grouns, or into currentVector*infinity - on loss of their unit target.

**Comment by sprunk** [comment]
Claymore could receive burnblow.

**Comment by GoogleFrog** [comment]
I am not sure whether Claymore can receive engine burnblow, the tag has weird behavior.
