### ISSUE TITLE
Apparently lagmonitor handles wrong units

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#2840]
http://zero-k.info/Battles/Detail/490546

>Recieve units because ally is afk, when he returns most of his stuff is returned to him but not all and a few of my units are given to him

**Comment by Fealthas** [comment]
Its always like 1 unit too. I suspect its an off by 1 error somewhere.

**Comment by The-Yak** [comment]
In this game some units were given to me, when player returned all units were given back except for a felon.

http://zero-k.info/Battles/Detail/493253

**Comment by sprunk** [comment]
I watched 490546.

![1](https://user-images.githubusercontent.com/2573076/38336425-0a6cc616-3862-11e8-8820-7086d44544df.jpg)

This is how stuff looks like after the afker came back. Kingstad kept 6 Swifts, 2 Solars and a Fusion that "belonged" to the afker. However he was the one to actually build them, see the base right at the start of the afk:

![2](https://user-images.githubusercontent.com/2573076/38336415-03d83cd6-3862-11e8-8732-e0908c111d77.jpg)

At some point he tried to give back the extra Swifts and mistakenly gave away the 2 tanks marked on the first screenshot as well (you can see they haven't been given away by lag monitor, also note "I gave away 8 units" chatline = 6 Swifts + 2 tanks).
![3](https://user-images.githubusercontent.com/2573076/38336427-0cd6f70a-3862-11e8-8945-2b0857aba721.jpg)

Everything works as intended.
