### ISSUE TITLE
Big Bertha and Zenith will not fire if their Line of Fire is blocked by wreckages

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#2859]
For some reason, Big Bertha and Zenith will not fire if there are wrecks in their Line of Fire.

https://github.com/ZeroK-RTS/Zero-K/blob/e5af1ce8e1f7cd19f95c69e531d7c7db7de2316c/units/staticheavyarty.lua
 avoidFeature = false,
Is it supposed to be:
 avoidFeature = 0,
?

**Comment by sprunk** [comment]
```lua
avoidFeature = false,
avoidFeature = 0,
```
Those are supposed to be the same unless engine has a massive bug.
