### ISSUE TITLE
Units cannot cloak in transports

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2862]
Units used to be able to be cloaked while in transports. I think this was good. Now they cannot and it is likely a change due to the gadget handling of cloak.

**Comment by sprunk** [comment]
There doesn't seem to be a meaningful delay. Tested with trans+pyro and heavytrans+det. In both cases the unit seems to be cloaked alongside the transport when entering the cloak bubble. Unloading and loading doesn't break cloak. Units still obey damage rules though (if you drop the unit onto ground and it takes fall damage then it will not immediately cloak when picked up).
