### ISSUE TITLE
Featuremaker some more maps

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2864]
https://zero-k.info/Maps/Detail/57330 Lava Highground 2.11

https://zero-k.info/Maps/Detail/57331 SapphireShores_Dry_V2.2

http://zero-k.info/Maps/Detail/57388 Incandescence 2

**Comment by Aquanim** [comment]
Onyx Cauldron 1.9 was featured a while ago.

I prefer Otago 1.1's metal layout for the campaign mission in which it appears, and as a 2v2 map for Planetwars (Otago 1.2 would be fine for 3v3 but that's not the easiest slot to put it in).

The non-bot-pathable and bot-pathable cliffs on Living Lands 4 are not easy to distinguish based on appearance.

I can replicate the Columbia Basin AI bug, see http://zero-k.info/Battles/Detail/492840

**Comment by sprunk** [comment]
@The-Yak Columbia Basin startbox config has no startpoints defined, at least 1 needs to be present.

**Comment by The-Yak** [comment]
I will fix Columbia, thanks.

RE Living lands: indeed the texture has not improved on this aspect, it's the same story in currently MMed version.

RE Otago: I'd love to be able to support multiple metal configs on the same map, but I don't know what the best approach would be.

Also looks like currently used maintenance build no longer crashes with dynamic water on Aetherian 1.7.

**Comment by sprunk** [comment]
Otago:
```
local v11_config = {bla}
local v12_config = {bla}

if Spring.GetModOptions().planet or Spring.GetModOptions().singleplayercampaignbattleid then
    return v11_config
else
    return v12_config
end
```

**Comment by The-Yak** [comment]
How can I test if the planet and singleplayer modoptions are working in my config? They aren't present in adv options.

**Comment by The-Yak** [comment]
Updated op

**Comment by sprunk** [comment]
Featured/MM'd most of them, updated OP with the remaining ones.

Near-release feature freeze is now in effect so they will probably have to wait until after that.

**Comment by sprunk** [comment]
MM maps appear to be automatically included in the Steam build so I think we can go back to mapfeaturing MM maps through the web UI as long as it's done right before a stable.

There are no longer enough people to ddos the server with downloads when a map isn't available through Steam so I think we can go back to mapfeatuing Featured and lower maps on demand.

**Comment by The-Yak** [comment]
I added Incan 2, removed Otago 1.3 and HS v06

**Comment by sprunk** [comment]
Done, sorry for the delay.
