### ISSUE TITLE
I wish to block KingRaptor from making any further save/load changes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2875]
I have fixed one full luarules crash so far (https://github.com/ZeroK-RTS/Zero-K/commit/acf297d794f206b4c2fa6554e4d08d1f9b844cf4) and just encountered a main menu crash on attempting to save the game.

![image](https://user-images.githubusercontent.com/1318249/38229445-20f77514-374c-11e8-82af-08ae901549d3.png)

**Comment by GoogleFrog** [comment]
I also don't want to add any save/load features myself. Only the things which can cause a continued broken gamestate should be fixed.

**Comment by Histidine91** [comment]
"Done"
