### ISSUE TITLE
User has flickering camera and overall lag on GeForce GTX 970M Win10

### ISSUE THREAD

**Issue by ghost** [ZeroK-RTS/Zero-K#2886]
>OzzyKampha
 Today at 9:54 AM
hi, the game is flickering when i move the camera and it also lags overall on a windows 10 machine. Any solutions?
TheMooseIsLoose - Today at 9:56 AM
what is your graphics card?
OzzyKampha - Today at 9:56 AM
gtx 970m
TheMooseIsLoose - Today at 9:56 AM
update nvidia drivers if you haven't already
OzzyKampha - Today at 9:57 AM
newest driver
TheMooseIsLoose - Today at 9:58 AM
share infolog?
it will be generated in your Zero-K directory after a game
OzzyKampha - Today at 10:05 AM
20180408170009_infolog.txt
26.23 KB
TheMooseIsLoose - Today at 10:07 AM
"[ChiliFX] Error: ChiliFX not loaded. Spring has failed to detect GLSL support on your system."

but     GL renderer : GeForce GTX 970M/PCIe/SSE2 is detected?

Infolog: https://cdn.discordapp.com/attachments/278805140708786177/432586737341038592/20180408170009_infolog.txt

**Comment by SSS135** [comment]
I have similiar issues on Windows 10, GTX 840M. Overall FPS is ok, but it looks like game render frames in wrong order i.e. it should render frames 1, 2, 3, 4, 5 but instead renders in 1, 3, 2, 5, 4 order, or something like that. Tried different settings and disabled threaded optimizations in nvidia control panel.

**Comment by sprunk** [comment]
There's been engine changes since then and there's no really actionable info here.
