### ISSUE TITLE
Bad default settings on fresh install of steam Zero-K on Solus 

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#2893]
After a fresh install of ZK on linux my graphics settings are set to "Custom" despite not having customized graphics at all. The custom settings include ultra quality 8192x shadows, high antialiasing, many things that kill performance.

Jumping straight into the folsom tutorial mission, I have slideshow tier performance in the opening cutscene.

After exiting from first game many buttons become unclickable in Chobby, and the cursor on screen wasn't the same as the apparent mouse position.

Attached the freshly generated springsettings.cfg, renamed to txt for github support. Attached infolog generated from first game as well.

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1895724/infolog.txt)

[springsettings.txt](https://github.com/ZeroK-RTS/Zero-K/files/1895697/springsettings.txt)

EDIT1: I have discovered the cursor being in different position from mouse is exclusive to windowed lobby mode. I can fix/break by toggling to borderless window and back again.

**Comment by GoogleFrog** [comment]
I set the default deployment settings to medium. https://github.com/ZeroK-RTS/Chobby/commit/912b168b652675b36e1f35fa802fd6150f56c7b4
