### ISSUE TITLE
Constructor units get stuck on newly constructed buildings

### ISSUE THREAD

**Issue by maackey** [ZeroK-RTS/Zero-K#2895]
This happens with normal constructors as well as commanders. Most often its constructors getting stuck while building some sort of energy building and holds up the queue indefinitely. 

https://youtu.be/17NiyBYIK-g -- example video

**Comment by GoogleFrog** [comment]
State all the versions of various things used.

**Comment by GoogleFrog** [comment]
This looked just like the bug that was fixed here: https://github.com/ZeroK-RTS/Zero-K/commit/76b01809eaf638514755b3d37324df7d5dfa41ee
