### ISSUE TITLE
Nanobeam bugs on compat. graphics preset

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2900]
Nanobeams using the NanoLasersNoShader class (used for the compat. graphics preset in Chobby) have a number of issues:

- They disappear after about 1 s when player is spectating. Pausing and resuming the construction restarts the beam. Can be reproduced with `/cheat /spectator /godmode`.
- They often don't aim correctly ([screenshot](https://i.imgur.com/w73XiXY.jpg))

**Comment by lhog** [comment]
Is there a specific reason nanobeams/nanolasers are drawn as LuPS?
The engine default implementation is not that terrible and works on every GPU I have tested it so far, including Linux open-source AMD, Nvidia and Intel drivers
