### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by maackey** [ZeroK-RTS/Zero-K#2902]
![memory-leak](https://user-images.githubusercontent.com/3486898/38771437-71c32e5e-3ff1-11e8-969d-b8457fef74ef.png)

[20180414183047_infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1910718/20180414183047_infolog.txt)
Edit: wrong infolog

**Comment by sprunk** [comment]
The picture shows a flat line on the memory graph; old engine version; Chobby is suspect (ZeroK-RTS/Chobby#694).
