### ISSUE TITLE
Specific save/load issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2905]
See thread: http://zero-k.info/Forum/Thread/25090

**Comment by KingRaptor** [comment]
All done

**Comment by KingRaptor** [comment]
One more todo: restore control groups

**Comment by KingRaptor** [comment]
0b145785235146ee18854127a2b61e533ce6f180
68ffc599e8d3d3659051c903ea055f6d22bcef54
