### ISSUE TITLE
Mission widget error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2906]
https://github.com/ZeroK-RTS/CrashReports/issues/4132

[f=0041433] Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=MissionEvent trace=[Internal Lua error: Call failure] [string "LuaUI/Widgets/camera_beautyshot.lua"]:48: bad argument #2 to 'random' ([spring_lua_unsynced_rand(lower, upper)] empty interval)

**Comment by sprunk** [comment]
Widget source is in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/MissionEditor/MissionEditor2/MissionBase/LuaUI/Widgets/camera_beautyshot.lua

Looks like it receives data from some mission trigger so fortunately just one mission will need fixing.

**Comment by GoogleFrog** [comment]
Another https://github.com/ZeroK-RTS/CrashReports/issues/4159

**Comment by sprunk** [comment]
Apparently `math.random` parses the arguments as unsigned so negative values result in empty interval due to min > max.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/5dd38c28935df3016243a0c8bc22a8058904f1b9
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/232fcbab229b945dd1842abb9e3405cfbba0c64c
