### ISSUE TITLE
Roc LUS error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2913]
See https://github.com/ZeroK-RTS/CrashReports/issues/4135

**Comment by KingRaptor** [comment]
```[f=0023882] [Game::ClientReadNet][LOGMSG] sender="ni" string="could not load model "chicken_roc.s3o" (reason: [S3OParser] could not find model-file objects3d/chicken_roc.s3o```

Model exists in repo. Download corrupted?

**Comment by sprunk** [comment]
The LUS error stems from the missing model. Corrupt download.
