### ISSUE TITLE
Add more hotkeys to hotkeys submenu

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2921]
- Map overlay hotkeys (currently in interface).
- Control group and autogroup. This will be fiddly.
- Building starter, currently hardcoded to Q.

**Comment by sprunk** [comment]
Also other hardcodees:
 * `BCV` skydust https://github.com/ZeroK-RTS/Zero-K/blob/94a6db8178edc9ff3cfb996f960206299134d4ce/LuaUI/Widgets/gui_persistent_build_height.lua#L69-L71
 * `X` blast radius https://github.com/ZeroK-RTS/Zero-K/blob/173e65a95d5800ed9c6653e249819e872092feed/LuaUI/Widgets/gui_blastRadius.lua#L111

Stuff to keep in mind: groups also use hardcoded `` ` `` https://github.com/ZeroK-RTS/Zero-K/blob/9c1d737b818f635d14516d393a0b9964d07163a3/LuaUI/Widgets/unit_auto_group.lua#L314 and are hardcoded in COFC as well https://github.com/ZeroK-RTS/Zero-K/blob/5c07781973c6718bdcfd42c4f487831a19288a5c/LuaUI/Widgets/camera_cofc.lua#L2674-L2676

**Comment by GoogleFrog** [comment]
Fixed (except blast radius which seems to be inoperable) because new player testers requested this and I realized that hotkeys in the hotkeys menu teaches people about the UI.

**Comment by GoogleFrog** [comment]
Wow it is not inoperable, but it is super confusing.
