### ISSUE TITLE
Tab-specific grid key settings not obvious, Obvious key settings not clearly tab-agnostic.

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#2923]
I experimented with setting up non-grid hotkeys recently, and I found that any hotkeys set in the hotkeys menu are global. That is, they work whether or not their respective tab is selected. I realize that internally this is because there are no tabs because of the way TA did it, but the default integral menu has tabs, and it's unpleasantly surprising to have hotkeys not respect the active tab, since it really looks like it should.

**Comment by GoogleFrog** [comment]
Already dealt with. Look in this submenu:

![image](https://user-images.githubusercontent.com/1318249/39061678-76afb790-4508-11e8-94d8-37764a9c2ff6.png)

**Comment by dvr333** [comment]
What I mean is that I can't set arbitrary hotkeys and still have them respect tabs. That is, I can't set, say, Defender to S and set Solar Plant to S.

**Comment by GoogleFrog** [comment]
When did you last look? This is recent.

**Comment by dvr333** [comment]
I last looked a week ago. It looks like those custom overrides are what I'm looking for. Sadly, they don't handle non-alphanumeric keys consistently. If I set stuff like '[', ';', '-', etc. it doesn't recognize them or convert them to the proper SDL keysym that the grid keys use.
