### ISSUE TITLE
Sometimes charged shields fail to block enemy projectiles

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#2936]
I noticed every now and then shields don't block the enemy projectiles, although they are charged so they should.

Is this a known issue?

[20180422_045648_TitanDuel 2_104.0.1-358-gb58f0bb maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/1935151/20180422_045648_TitanDuel.2_104.0.1-358-gb58f0bb.maintenance.zip)

**Comment by GoogleFrog** [comment]
No.

**Comment by GoogleFrog** [comment]
Well ShieldPreDamaged is not called so I expect it is engine.

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=5964

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/62515cfbce63bd66a48654b69bfb37ecc75bbbd8
