### ISSUE TITLE
Lists of featured map changes for steam.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2945]
[unfeature.txt](https://github.com/ZeroK-RTS/Zero-K/files/1936763/unfeature.txt)
[shipped.txt](https://github.com/ZeroK-RTS/Zero-K/files/1936764/shipped.txt)
[list.txt](https://github.com/ZeroK-RTS/Zero-K/files/1936765/list.txt)
[featured.txt](https://github.com/ZeroK-RTS/Zero-K/files/1936766/featured.txt)

**Comment by Anarchid** [comment]
![image](https://user-images.githubusercontent.com/3822768/39116985-77572006-46ee-11e8-8e22-fa15ef9bbd9a.png)
What does featured.txt mean? If it means "feature these maps" then `unfeature.txt` and` feature.txt` are in a race condition.

**Comment by sprunk** [comment]
Featured is currently featured. Unfeature is (featured - shipped).

**Comment by Anarchid** [comment]
Is this just a note-keeping ticket, or should unfeature.txt be inflicted upon database?

**Comment by sprunk** [comment]
Pre-Steam map pool freeze has been unfeatured.
