### ISSUE TITLE
Leveled dyncomms gain +4/+6 resource production on save/load

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#2949]
1. Start a skirmish game with any commander
2. Upgrade comm to level 2 (no modules required)
3. Save and load
4. Comm now produces 4 more metal and 6 more energy than it did before
5. Repeat steps 3 and 4, M/E output keeps increasing

**Comment by Anarchid** [comment]
Epic

**Comment by GoogleFrog** [comment]
Occurs with no modifications in campaign mission 2 as well.

**Comment by GoogleFrog** [comment]
I called it steam milestone because it removes the ability to save/load the game without feeling like a cheater.
