### ISSUE TITLE
Deluxe Player List can cause total luaui failure

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#295]
Don't know why but on occasion chili deluxe player list breaks the entire luaui. Not even BA-eque stuff will remain. You are left with a completely blank UI. No minimap. No nothing. Its like you pressed f5 but it has a chat.

**Comment by sprunk** [comment]
Can't reproduce and the ticket does not contain any useful info. Deluxe Player List has also been modified since. Close?
