### ISSUE TITLE
Default state of chasing for airplane factory is roaming

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#2954]
I think I change that state to maneuver several times across several games
and I don't think you want it to be roaming
the default state for all other factory are maneuvers
not to mention how easy it is to bait plane
and I was unable to make a change that last multiples games

**Comment by GoogleFrog** [comment]
Factories have a movestate and units also have a setting to either use their own movestate or inherit from the factory. This may have been your initial states issue.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/f97aa956f4d3da0e25a6711715d5b82e8ed8ee80
