### ISSUE TITLE
Avoidable reclaim the resurecting blockade.

### ISSUE THREAD

**Issue by wubber** [ZeroK-RTS/Zero-K#296]
If ally is ressurecting anything u can avoid the reclaim blockade by placing any building undernearth teh rezzing wreck. The cons will start preparing ground to place new building, thus reclaim eveything, including the wreck which is being rezzed.

**Comment by Anarchid** [comment]
Iirc there was something done to make reclaim 'disabled' the default option when someone was already resurrecting a wreck.

**Comment by sprunk** [comment]
There has never been any intent to completely block it, or to even block any more than the engine does by default. It's only there to prevent accidential reclaim through are-reclaim. At any rate, the block exists fully engine-side. Closable.
