### ISSUE TITLE
Glaive hit and leading problems

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#2970]
In this game I engage a Glaive from rANDY with half health near the middle of the map at 1:40.
http://zero-k.info/Battles/Detail/497773
My Glaive get the initial jump on his Glaive and starts firing and doing damage earlier than his. I turn to follow his Glaive to ensure the kill. However, with a sliver of health left for rANDYs Glaive, my Glaive misses completely while firing ahead of rANDYs Glaive that is just going straight while running alongside it.
From my testing, it is more often that the Glaives miss ahead of other Glaives rather than firing behind the Glaive. This makes me think there is a problem with leading.

**Comment by Godde** [comment]
From some further testing, it seems that Veterancy makes Glaives more accurate on the move.

**Comment by sprunk** [comment]
Related #1881

**Comment by GoogleFrog** [comment]
That change does not affect Glaive, and what exactly was the problem that required the removal of predictBoost?

**Comment by GoogleFrog** [comment]
Hang on, now I see the _posts. This removes aim spreading which is a useful feature for things like Rogue. It is not good to apply it universally!

**Comment by sprunk** [comment]
That's why `if not`

**Comment by GoogleFrog** [comment]
I think I looked at this and found no issue.
