### ISSUE TITLE
Buildings not being given back on AFK return?

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#2971]
See https://steamcommunity.com/app/334920/discussions/0/1696045708649227177/ and follow up

**Comment by sprunk** [comment]
I'm fairly sure it's about the feature where you get to keep stuff that AFKer started but you finished.

**Comment by sprunk** [comment]
No details so I'll assume the above (but if somebody manages to contact that guy, extract details, and they turn out to be something else then feel free to reopen). The general undesirability of the feature should be covered by #3077.
