### ISSUE TITLE
Matchmaker Accept/Reject

### ISSUE THREAD

**Issue by maackey** [ZeroK-RTS/Zero-K#2973]
The option to accept or reject a matchmaker game is flawed. No information is provided on what type of game is available, or who the opponents are -- there is no information to provide reasons for a choice. 

Once you join the queue you should be placed automatically within a game when one is available. No further action should be necessary. If you are not ready or willing to play a game, you should not be in the queue. There is already an option to leave matchmaker queues if this is the case. 

When a game has started from the queue, the player should be suspended from all queues until the game is over, at which point the player is placed back into whichever type of queues they had selected.

**Comment by sprunk** [comment]
Accept is needed to make sure the person isn't AFK when the game is created. People often expect the searching to take many minutes and go do something else in the meantime. Or something happens (eg phone) and they forget to cancel queue.

Reject is mostly so that there's an obvious alternative to Accept, it would probably not be needed if there was a clock with the countdown.

**Comment by GoogleFrog** [comment]
Accept/Reject is not a choice, it is an AFK test and a way to see if the player is still actually available to play.

**Comment by Licho1** [comment]
If its AFK it should be AFK. 
It is possible to test for AFK by just changing periodically and treaty "recently checked" people as being ready to start.

**Comment by maackey** [comment]
Don't we already automatically check for AFK ingame? Why do we need the player to take action to say they are not AFK? If you walk away from the queue and are AFK the system can just drop you from the queue or prevent matches until you come back.

**Comment by GoogleFrog** [comment]
There is no AFK checker which is up for the task. Maybe you're reading a book or making tea but can jump back into the room and click accept within 15 seconds of hearing the noise. It is also not intuitive to be booted for failing to do whatever we might call "AFK".

What I'm considering is removing 'Reject' and just letting it timeout if you're not there. Thoughts?

**Comment by Licho1** [comment]
There can be good enough AFK check:
1) check keyboard mouse, if there is movement, treat it as non-AFK
2) if there is no movement, ask user every 5 minutes, with popup similar to ACCEPT/REJECT now, it will annoy and spam much less.

But removing reject is a good solution for now.
