### ISSUE TITLE
Linux Crash on 32 player game straight at game start

### ISSUE THREAD

**Issue by vvolas** [ZeroK-RTS/Zero-K#2978]
Demo is 0 bytes size. Crashes multiple times on same spot straight at start.
I m using flobby. 

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/1958022/infolog.txt)
[infolog.txt_crash.txt](https://github.com/ZeroK-RTS/Zero-K/files/1958023/infolog.txt_crash.txt)

**Comment by sprunk** [comment]
One of the infologs is OOM, both are old engines (287 and 271).
