### ISSUE TITLE
Group selection affected by selection rank

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#2983]
repo step:

assign constructor + high rank units [e.g. commander] to a group [e.g. group 1]
press group selection button [e.g. press "1"]
the constructor is not selected

@GoogleFrog said: not intended behavior

**Comment by sprunk** [comment]
Incomplete fix: 75b47e8cfd73893cd3e167085242107cc3f55f04

**Comment by Histidine91** [comment]
Completed in 643f40abf1ad8a252d0a9519e243bf26c169fb68
Thanks for report!
