### ISSUE TITLE
Please make global chat default in 1v1

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#2986]
I see streamers that doesn't know that their chat is allychat in 1v1.
All-chat should be default in 1v1.

**Comment by Licho1** [comment]
good point.. iremember it was ..

**Comment by Licho1** [comment]
it was something like sendconsolecommand allchat  .. dont remember but i think old console had it hacked

**Comment by sprunk** [comment]
`Spring.SendCommands("chatall")`

**Comment by GoogleFrog** [comment]
What happened is that this particular version of Spring sucks at getting playerlists during initialization.
