### ISSUE TITLE
Look into offensiveness of kamikaze award

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2988]
![image](https://user-images.githubusercontent.com/1318249/39427541-721a73a2-4cc7-11e8-8623-ef7f315b4850.png)

https://steamcommunity.com/games/334920/announcements/detail/1651009712413798600

They may well have a point and it is not like we are using the flag to match any art style of visual consistency. Whoever made the award just picked that image.

**Comment by KingRaptor** [comment]
Replaced in all known locations (ZK, Chobby, site), awaiting stable.
