### ISSUE TITLE
Consistent crash on Fields of Isis

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#2989]
Vermind's crash as per http://zero-k.info/Forum/Post/183871#183871

Infolog (with Intel card): https://pastebin.com/8B4MkjPt

At line 1625:
[f=-000001] [CrashHandler] Error: Segmentation fault (SIGSEGV) in spring 104.0.1-287-gf7b0fcc maintenance
[f=-000001] [CrashHandler] Error: Halted Stacktrace for Spring 104.0.1-287-gf7b0fcc maintenance using libunwind:
[f=-000001] [CrashHandler] Error: This stacktrace indicates a problem with your graphics card driver, please try upgrading it. Specifically recommended is the latest version; do not forget to use a driver removal utility first.

Apparently Vermind has the latest drivers available for Ubuntu 18.04.

This crash occurs when playing Fields of Isis in a skirmish or in the Snitch campaign mission.

**Comment by KingRaptor** [comment]
Apparently fixed user-side: https://zero-k.info/Forum/Post/184021#184021
