### ISSUE TITLE
LiquidOxygg may contribute sounds

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2991]
![image](https://user-images.githubusercontent.com/1318249/39436814-736f7606-4ce2-11e8-8863-d9449b67ec1b.png)

Also translations.

**Comment by sprunk** [comment]
Related https://github.com/ZeroK-RTS/Zero-K/issues/2492

**Comment by sprunk** [comment]
Relevant information (for both LiquidOxygg if he shows up or anybody else) are in #2492 and some results are in #3100.
