### ISSUE TITLE
Host this file somewhere and edit page

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2995]
https://zero-k.info/mediawiki/index.php?title=Mod_Creation
[zk.sdd.zip](https://github.com/ZeroK-RTS/Zero-K/files/1963055/zk.sdd.zip)

**Comment by GoogleFrog** [comment]
[LocalColors.zip](https://github.com/ZeroK-RTS/Zero-K/files/1963835/LocalColors.zip)

**Comment by KingRaptor** [comment]
Done?

**Comment by GoogleFrog** [comment]
You tell me. When I set the links on that wiki page I linked to the files hosted in this ticket. Mediawiki should have its own file hosting so all the resources can be kept in one place if we need to move something.

**Comment by KingRaptor** [comment]
Alright, hosted on MediaWiki:
[zk.sdd.zip](https://zero-k.info/mediawiki/index.php?title=File:Zk.sdd.zip)
[LocalColors.zip](https://zero-k.info/mediawiki/index.php?title=File:LocalColors.zip)

(for future reference, the file upload page is [here](https://zero-k.info/mediawiki/index.php?title=Special:Upload); poke me if the file extension you want is not supported)

**Comment by sprunk** [comment]
Done
