### ISSUE TITLE
Subs could be given minDepth equal to other ships

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#2998]
Currently, submarines which pass shallow water become targetable by surface weaponry, presumably because they are pushed by the sea bottom:

- Obtain a submarine (Seawolf or Scylla) on one team 
- Obtain a few Cutters (or any other non-waterweapon units) for the other team 
- Move all of these onto a patch of sea with depth around -17
- Observe Cutters firing at the submarine. Mostly they miss, but things like the Scalpel become quite good at antisubbing in such circumstances

If they are doing this at their current maxDepth, there's also not that much difference if they also do it at -6, the maxDepth of all other Shipyard units.

**Comment by Anarchid** [comment]
Perhaps this could be a feature. Subs could pass shallows like other ships (up to depth -6), exposing them to surface fire if they choose so (like Amphibs). It should be fairly possible to make them climb automatically. 

A super-version of that would be them having altitude control options like Ravens - e.g. Surface, Submerge, Dive Bottom, Auto

**Comment by sprunk** [comment]
Related? #3052

**Comment by Anarchid** [comment]
#3052 is different. UnitAI doesn't know when it should consider a visible and in-range enemy unit a valid or invalid target based on the waterweapon status. E.g. submerged Ducks will gleefully "chase" a terraformed Urchin.

**Comment by sprunk** [comment]
#3909
