### ISSUE TITLE
Hotkeys to remove from autogroup aren't loaded properly

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#2999]
If a custom hotkey is set to "remove from autogroup", it won't stick. It will show up as the correct key in the menu, but using it will have no effect. It works fine when it is first set, just not when the game is restarted (as in Exit To Lobby followed by Start). Instead "remove from autogroup" goes back to using alt+backquote.

**Comment by sprunk** [comment]
ac01539217f0ddf17b4f1eb97994f4f75f9d16e0
