### ISSUE TITLE
Large grey square drawn in world

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#3005]
Reported by Yaluzan: https://media.discordapp.net/attachments/432874986064052235/441572217759989760/unknown.png

> It was caused by a picket wreck at around 6:47

Apparently problem goes away when the wreck is reclaimed.

**Comment by Yaluzan** [comment]
http://zero-k.info/Battles/Detail/508559?

**Comment by sprunk** [comment]
>[14:21] Yaluzan: Hold on i need someone to kill another picket so i can get a closeup
[14:22] Histidine: Wait, it's temporary?
How long does it last?
[14:23] Yaluzan: It was caused by a destroyed picket and dissapeared when it was reclaimed

>[19:30] Patrick: @Yaluzan around what time did it happen? I wanna see xD
[19:30] Yaluzan: that was 6:47

**Comment by lhog** [comment]
Can it be seen in replay? I watched the battlefield around 6:47 time, but was unable to see anything outstanding.

**Comment by Yaluzan** [comment]
Yeah i'm pretty sure it was just a one time graphical bug. I just checked the replay another 2 times and there was nothing there...

**Comment by KingRaptor** [comment]
Closing for now, then; reopen if fresh cases observed
