### ISSUE TITLE
Stockpile UI stuff

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3007]
http://zero-k.info/Forum/Thread/25250

Gist:
 * change initial stockpile from 100 to [configurable through initial states]
 * add an option to maintain missile count (ie. queue up +1 stockpile each time one is fired)

**Comment by SteelBlueZK** [comment]
https://zero-k.info/Forum/Thread/31723

Bump.

It seems that units continually stockpile in a widget [here](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_stockpile.lua#L26), The gadget that controls stockpiling (Needs no changes) is [here](https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_stockpile.lua). So any UI hooks should probably be an edit to the Widget unit_stockpile.lua.

**Comment by pengvado** [comment]
#https://github.com/ZeroK-RTS/Zero-K/pull/4010

**Comment by GoogleFrog** [comment]
Fixed.
