### ISSUE TITLE
Fix out-of-range targeting

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3011]
Apparently the HLT not firing error was fixed in the dev engine by making out of range enemies always have lower target prioritization. We will likely need to put something in allowWeaponTarget to replicate this. Perhaps the default priority will indicate whether the enemy is in range or not.

**Comment by sprunk** [comment]
The default priority gets multiplied x100'000x for those targets.

**Comment by GoogleFrog** [comment]
So the default priority should be easy to detect?
