### ISSUE TITLE
I still default to ally chat in 1v1

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3022]
My dev test accounts did not do this in my 1v1 battleroom. No idea what the difference is.

**Comment by gajop** [comment]
Yep, can confirm this thing is still happening. Why?

**Comment by sprunk** [comment]
Maybe related d962621404f3498fd7bf77d376d6e8c27161053f ?

**Comment by GoogleFrog** [comment]
The bug was probably deleted in that commit.
