### ISSUE TITLE
Cannot search Replays on Spectator

### ISSUE THREAD

**Issue by maackey** [ZeroK-RTS/Zero-K#3024]
I was trying to find a battle for a strange bug that occurred when starting a game but can't find it because I wasn't a "player" in the game.

**Comment by sprunk** [comment]
This belongs to infra, made a ticket over there https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2267

It's intentional, see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/141, but it should probably become a checkbox.
