### ISSUE TITLE
Fancy shield shader not appearing

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#3027]
I have default ZK over steam.
Tried changing details to ultra and back a few times.
It shows the non-shader texture varient it seems instead. 
No fancy wobbling one with hits.

**Comment by GoogleFrog** [comment]
Settings and infologs?

**Comment by Licho1** [comment]
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K/files/1979211/infolog_full.txt)

[springsettings.cfg.txt](https://github.com/ZeroK-RTS/Zero-K/files/1979216/springsettings.cfg.txt)

**Comment by GoogleFrog** [comment]
Is shield effects shader set to default in the graphics menu? What does your lups.cfg look like?

**Comment by Licho1** [comment]
Yes it is set to default. I was also changing it to simple and back a few times. 
My lups is steam default (+set to ultra)

[lups.cfg.txt](https://github.com/ZeroK-RTS/Zero-K/files/1979733/lups.cfg.txt)

**Comment by GoogleFrog** [comment]
lups config says it should be shown.

**Comment by Licho1** [comment]
It shows the old glass with hex grid.

**Comment by Licho1** [comment]
Ok I cannot replicate it.
It wasn't the fancy shader, fancy shader has smaller hexes, and wobble. 

It was old shield with old texture.. But It was when i was catching up some game, perhaps they used old ZK?

If i create skirmish game, fancey shader loads for me.
