### ISSUE TITLE
Chili Selections & CursorTip v2  <gui_chili_selections_and_cursortip.lua> - crashing constantly

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3029]
[f=0007874] [cawidgets.lua] Error: Error in Update(): [string "LuaUI/Widgets/gui_chili_selections_and_curs..."]:2126: attempt to index local 'fd' (a nil value)
[f=0007874] [cawidgets.lua] Error: Removed widget: Chili Selections & CursorTip v2

... Happens randomly (very often) during my playthroughs. Manually reloading widget helps, but the issue manifest itself very often (sometimes, widget crash just seconds after re-enabling), so it is very inconvenient work-around.

Despite some "debugging" I was not able to find a pattern for what "trips" it - it doesn't seem to be related to pointing cursor or anything in particular, or any event happening in battlefield.

Version used:
linux64/104.0.1-287-gf7b0fcc

Full infolog:
https://zerobin.net/?01299a8035e83450#VML/LxBsQcnO2R11xxq6jTyQ+uuzM7NyGu/MhR0bi0A=

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/c96c8721fc2f9d67a9d96623d448873ac7cbd7e0
