### ISSUE TITLE
Unfeature/remake mininuggets

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3031]
http://zero-k.info/Maps/Detail/56553, see https://steamcommunity.com/profiles/76561198026153422/recommended/334920

I've already removed the infringing models from ZK repo (134b4d6662e374f6aa6b34327c25036f124dacae) but the map comes with its own copies.

Ping @GoogleFrog because there was some sort of moratorium on changing map status so presumably he'd like to know about it before anything gets done.

There's the larger question of what to do with copyright infringing content, we're probably not supposed to mirror such map on our server, would need quality control on upload. See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/237

**Comment by GoogleFrog** [comment]
Unfeature will make it hard to access but still downloaded to peoples computers. Remake is the easiest?

**Comment by sprunk** [comment]
Getting rid of the current version has to be done regardless. Remaking is an optional step that can be done in addition.

Making it hard to access is the most we can do. Under the current state of infra is is impossible to prevent downloads (even if we remake the map) and I don't expect any infra changes to happen in that direction.
