### ISSUE TITLE
Cyclops didn't want to fire at enemies.

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#3034]
In this battle http://zero-k.info/Battles/Detail/517378 at 18:30, one of my  Cyclops didn't want to fire at the enemy Pickets near the south entrance to my base even though I ordered it to do so.

It might have something to do with it being on retreat but I have not been able to reproduce it.
https://imgur.com/thz7lGy

**Comment by sprunk** [comment]
1db1ce91f1152c2b4ea354df7749715be264794c
Duplicate of #2982
