### ISSUE TITLE
Missile Silo error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3041]
https://github.com/ZeroK-RTS/CrashReports/issues/6792

**Comment by sprunk** [comment]
Looks like the actual source of the bug is this line: https://github.com/ZeroK-RTS/Zero-K/blob/13eaa110aa0985f58020400efd71adf157657a6b/LuaRules/Gadgets/unit_missilesilo.lua#L215 when a silo is loaded with all slots filled.

**Comment by KingRaptor** [comment]
Do you think the nil check should be moved from the LUS to gadget?

**Comment by sprunk** [comment]
I believe it's best to handle incorrect values as soon as they can be identified as such. It's not strictly better as it takes a bit more mana though.
