### ISSUE TITLE
Launcher UI layout breaks on low window size

### ISSUE THREAD

**Issue by Palmer--** [ZeroK-RTS/Zero-K#3042]
You can currently make the launcher window really small. Making it too small breaks UI element layouts.
![broken layout](https://user-images.githubusercontent.com/11057262/39827477-50f66d14-53b8-11e8-92fe-77820b34b1eb.png)

**Comment by Palmer--** [comment]
It appears I have created this issue for the wrong repository. Closing this and opening a new issue in Zero-K-Infrastructure instead.

**Comment by sprunk** [comment]
![image](https://user-images.githubusercontent.com/2573076/39828169-60c925cc-53ba-11e8-9919-e46edc79e8fd.png)

**Comment by Palmer--** [comment]
[Link for corresponding issue.](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2273)
