### ISSUE TITLE
Font glitch (Steam beta branch)

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#3047]
Examples from tutorials:

- https://i.imgur.com/3N44Za4.jpg
- https://i.imgur.com/K2d3bPj.jpg
- https://i.imgur.com/j6ZvLVr.jpg
- https://i.imgur.com/LhEZaAo.jpg

(notice that which elements are effected is not consistent)

At some point the issue spread to Chobby as well (simple skirmish setup buttons), but I lost the screenshot. 

Infolog: http://paste.springfiles.com/view/679f1de0

**Comment by GoogleFrog** [comment]
Don't we have that. We are on https://github.com/spring/spring/commit/0e66a0a7873900b29f97374b974cb241873cf618 iirc. Check what is set.

**Comment by GoogleFrog** [comment]
Oh, we are not on that. I did not press the "make default" button. That version apparently needed a redo so I won't set it yet. Don't touch the engines as they might break everything, the test site looks a lot like stable infra.

**Comment by sprunk** [comment]
We're on a recent engine and nothing seems to get reported so presumably spring/spring@b89847c worked.
