### ISSUE TITLE
add Option to remember UI-position

### ISSUE THREAD

**Issue by karstengo** [ZeroK-RTS/Zero-K#3048]
currently you are aware of that UI-positioning gets  NOT remembered.
Maybe it works for just the same game... but a "save-Option" would be nice.
When I played with flobby it was no problem. But I am not sure what settings I miss. 
I can provide other logs... but do not know where to start,...

It would ne nice if you can choose UI options for current game or even profiles... may some people need differende PROFILES for 1 vs 1 or 3 vs 3 or > 5 vs > 5

**Comment by GoogleFrog** [comment]
Settings/HUD Presets -> Set preset to None.

**Comment by sprunk** [comment]
No feedback.
