### ISSUE TITLE
Player resigned by giving away units

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3050]
A player crashed mid-game, his units were automatically given to an ally by afk gadget. The ally gave the units back to the player, expecting him to continue playing. The player then rejoined. 

During the catch up, the player saw his units being idle and uncontrollable. So while it was still catching up, he gave the units back to his ally again. At this point, the units turned into "Abandoned units", controlled by "noname". The player had resigned by giving his units away during catch up.

 * It shouldn't be possible to give units back to an afk/disconnected ally, otherwise there's no way to get them back.
 * Maybe it shouldn't be possible to give units during catch up, if this can cause a resign. 

Video of the incident: https://www.twitch.tv/videos/260111016

**Comment by sprunk** [comment]
dbb390f708517c99ffcbb7b7a498fa8f59a1bd23?

**Comment by DeinFreund** [comment]
Wtf I thought we wouldn't do that

**Comment by DeinFreund** [comment]
Apparently there are more cases of people being resigned without even giving any units.

https://zero-k.info/Battles/Detail/526754
https://github.com/ZeroK-RTS/Zero-K/issues/3051

**Comment by sprunk** [comment]
B526754 is inactivity win. Others seem to be resign due to dbb390f708517c99ffcbb7b7a498fa8f59a1bd23, this is intended.
