### ISSUE TITLE
I want to write a language pack for this game.

### ISSUE THREAD

**Issue by dongasai** [ZeroK-RTS/Zero-K#3057]
I'm a real RTS fan,I'm also a coder.I love this game,but my English is low.I hope I can play this game(higher
),I also hope that more partners can play this game.

Are there any tutorials for developing language packs?

**Comment by sprunk** [comment]
https://www.transifex.com/zero-k

**Comment by dongasai** [comment]
I am about to finish the translation. Who will censor the entries that have been translated? @Saktoth

**Comment by dongasai** [comment]
I have completed all translation entries, hoping to review and update them as soon as possible.

**Comment by sprunk** [comment]
Implemented in #3391, available on Linux distributions.
Making it available on Windows is a task covered in #3119.

China will grow larger.
