### ISSUE TITLE
Check consistency of commander level numbers

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#3060]
Apparently the website configuration, the commander itself, and the level-up notification have some inconsistency. I'll investigate exactly what the problem is later unless somebody else picks this up first.

**Comment by sprunk** [comment]
See third checkbox in #1749

**Comment by Aquanim** [comment]
That seems like the wrong issue.

**Comment by sprunk** [comment]
Oops, meant the infra ticket: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1749
