### ISSUE TITLE
Recursion in transport float

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3063]
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowCommand trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_transport_pickup_floa..."]:218: GiveOrderArrayToUnitArray() recursion is not permitted
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowCommand trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_transport_pickup_floa..."]:218: GiveOrderArrayToUnitArray() recursion is not permitted
[f=-000001] 117
[f=-000001] 117
[f=-000001] 117
[f=-000001] 117
[f=-000001] 117
[f=-000001] 103

https://github.com/ZeroK-RTS/CrashReports/issues/7557

**Comment by KingRaptor** [comment]
Gameframe numbers suggest it's save/load specific, although the solution isn't clear.

**Comment by sprunk** [comment]
IMO the solution is to poison the various `GiveOrder` calls. I've wanted to do this for some time due to multiple tickets which are effectively duplicates (#3065 #3056 #3063 #2765 #2702 #2965 #2779 #2516 #2256 #2117 ) but I haven't had the time to test properly and it's something that shouldn't be done without extensive testing. Here's what I've been thinking:

```lua
local goQueue = {}
local goCount = 0
local inGiveOrder = false

for _, name in pairs({"GiveOrderToUnit",
                      "GiveOrderToUnitMap",
                      "GiveOrderToUnitArray",
                      "GiveOrderArrayToUnitMap",
                      "GiveOrderArrayToUnitArray"}) do
    local origFunc = Spring[name]
    Spring[name] = function(...)
        if inGiveOrder then
            goCount = goCount + 1
            goQueue[goCount] = {origFunc, {...}}
        else
            inGiveOrder = true
            origFunc(...)
            local goIndex = 1
            while goIndex <= goCount do
                local go = goQueue[i]
                local goFunc = go[1]
                local goArgs = go[2]
                goFunc(table.unpack(goArgs))
                goQueue[i] = nil
            end
            goCount = 0
            inGiveOrder = false
        end
    end
end
```

**Comment by GoogleFrog** [comment]
Some gadgets may well rely on orders being given immediately. This is not easy to check.
