### ISSUE TITLE
Investigate awards

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3069]
https://zero-k.info/Battles/Detail/527114

BPH with 20 million, probably something happened to terraunit.
CA looks suspiciously low as well.

thread https://zero-k.info/Forum/Thread/25471

**Comment by sprunk** [comment]
Silly modoptions.

**Comment by Sgathec** [comment]
I have seen someone get the Complete Annihilation award without having done the highest damage according to the graph at the end.

**Comment by sprunk** [comment]
Replay.

**Comment by Sgathec** [comment]
It doesn't seem extremely rare. Maybe I get lucky tonight and it happens or one of my recent games contains the bug.

**Comment by Sgathec** [comment]
Hmm, perhaps I made a mistake in fact.
