### ISSUE TITLE
autorepair module is insane

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3071]
http://zero-k.info/Battles/Detail/535225

Firepluk 's trollcom at level 11 had +391hp/s regeneration. please fix asap someone!

**Comment by sprunk** [comment]
culprit https://github.com/ZeroK-RTS/Zero-K/commit/23326cdd08b315671cdb1fca6947540311e31542#diff-018196cfdc4b966a0b4c7a2886586809L43

**Comment by springraaar** [comment]
waaaait...so commander regen scales with build power increase %?

**Comment by sprunk** [comment]
:owl:
