### ISSUE TITLE
Plan for automatic pause/unpause behavior when using menus

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#3073]
Thread: http://zero-k.info/Forum/Thread/25342

The posts there suggest that anything that opens F10 or F11 menu should pause, but nothing should unpause except a specific Pause keypress. 

However, I am 99.999% sure that if we do that, someone will get stuck in the paused state after using the menu and not know how to unpause, despite the big (but mostly transparent) pause message in the center of the screen.

Ideas?

**Comment by KingRaptor** [comment]
c6ebd951b7e832ada0e64cdf3657f9ddafb7f0e0: pauses when save/load menu is opened, and adds a separate option for auto-unpause on menu close (default on). This satisfies both Renthrak and Brackman's needs.

I think this could be closed for now? Reopen if further configuration is needed, or there are any other widgets that open their own menus but do not pause.

**Comment by sprunk** [comment]
Looks good
