### ISSUE TITLE
The charge in shield bars is hard to see

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3086]
The purple color on the dark grey or black bar background results in a hazy shield charge display unless the camera is close.

Could the charge color RGB distribution be changed to (255, 0, 180) for example?

**Comment by lhog** [comment]
Can you test the suggested changes yourself first?

You would want to mess with the following lines: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Configs/lups_shield_fxs.lua#L6-L7

See http://zero-k.info/mediawiki/index.php?title=Zero-K:Developing (Modifying the game) for instructions how to setup a local copy of the game.

**Comment by Sgathec** [comment]
I could modify the code to test, but couldn't I just instead take a few screenshots and recolor the bars?

**Comment by sprunk** [comment]
Sounds good. If it gets accepted then you'll still need to make a real screenshot though because it won't necessarily have that exact color ingame (the bar itself has a gradient, things like fog can affect the colour etc)

**Comment by sprunk** [comment]
Reopen if screenshots with specific suggestions appear.
