### ISSUE TITLE
Lower game start timer

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#3087]
At least for 1v1 MM games. Currently you have like **180** seconds to pick a spot to drop your commander. This is too much - when you click accept in the lobby this means you are ready to play and it is expected you will be there. This game countdown time is not the time to go to the bathroom or something like that.
Drop to something more reasonable like 20s.

**Comment by sprunk** [comment]
Moved to infra https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2309
