### ISSUE TITLE
Games can end in a draw 

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3092]
I have witnessed games ending in a draw at the very beginning myself.

This is what BigMac claimed on #zk:
[22:55] BigMac: there is this bug when someone exits to lobby during commander choose and rejoins its a draw

More information: http://zero-k.info/Forum/Thread/25489

**Comment by KingRaptor** [comment]
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2286
