### ISSUE TITLE
Units not respecting attack orders

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#3094]
Some units will not fire upon what you tell them to , despite target being in range. They seem to switch to other things.
Can be seen in the first pyro raid a few minutes in:
[replay](http://zero-k.info/Battles/Detail/541653)

**Comment by Fealthas** [comment]
This is a MAJOR BUG.
http://zero-k.info/Battles/Detail/544305?
Happened again here.

**Comment by KingRaptor** [comment]
Fine, relabelled. 

(My policy is that only things like CTDs and units completely ceasing to function (as opposed to shooting at a target other than the specified one) get the bug label)

**Comment by Fealthas** [comment]
Another occurrence. About 75% in. Snipers told to target felons, somehow never do.
http://zero-k.info/Battles/Detail/545095

**Comment by GoogleFrog** [comment]
The Pyro shot a bit and then decided it was not in range. Perhaps a targeting gadget? There was recently a change to import some engine logic into target selection.

**Comment by Fealthas** [comment]
In the 2nd replay it happened around 19:10. Bantha had attack order on caretaker and just did not fire.

**Comment by SteelBlueZK** [comment]
Attack orders in general seem super wishy washy. https://drive.google.com/open?id=1ZJtBj3a-MMlHrt2js56DKBBg6KZNvKqk Here is a test game where I spawn a bunch of solars messing the pathing up and have some glaives attack certain structures. Things seem to work for a while, but in complicated scenarios the path-finding to targets seems really weird, and in some cases glaives just give up on even chasing their target. Oftenthey won't even be in range, or all they have to do is advance a couple steps forward. Generally, once they have a LOS unbound by terrain they'll stop, even if there are units blocking LOS.

**Comment by GoogleFrog** [comment]
First note: do not generalise behaviour from Solars to other units, as they are in many no chase cats.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/46513696-31756d00-c89d-11e8-8918-bb89da060173.png)
![image](https://user-images.githubusercontent.com/1318249/46513717-4225e300-c89d-11e8-89e5-126d9fd5a4de.png)
I don't see a problem in http://zero-k.info/Battles/Detail/544305?.

**Comment by GoogleFrog** [comment]
I don't see any evidence that set target stopped working.

**Comment by sprunk** [comment]
Reopen if a new replay appears.
