### ISSUE TITLE
Feature Request: Time limit before same type vote.

### ISSUE THREAD

**Issue by darloth** [ZeroK-RTS/Zero-K#3096]
Very often people will mapvote immediately after a map is voted in.  This immediately ties up the voting slot, which a) prevents people from starting the game unless someone ends the vote, and b) can often entirely ignore the results of the previous vote.

A related issue - people can mapvote for the map already selected, and then that vote has to be processed before the game can start or anyone can vote for another map!  

If we could get an ideally customizable limit on how often votes of the same type can be made (perhaps something like 20 seconds since end of mapvote for person who actually started that mapvote, 10 seconds before anyone else can mapvote? These times probably work fine for other vote types) I think this would mitigate the issue.  

People could then vote in a map, and know they had 10 seconds to startvote, before someone else can vote to change it.  If a mapvote passes and enough people don't want that one, they'll vote no to startvote, and then be unable to startvote for another small chunk of time, in which time someone else could mapvote, or they could just wait if the no-vote was for some other purpose.

It would also eliminate people revoting immediately after their vote is denied, which is currently possible and annoying.

**Comment by sprunk** [comment]
Belongs to infra repo https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2311
