### ISSUE TITLE
Lichos drop bomb on innapropriate targets

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K#3106]
http://zero-k.info/Battles/Detail/546363

My lichos fired by themselves...
27:30 One drops its bomb on a grizzly for no reason.
28:40 - licho drops bomb on pene despite target clearly being the domi.

It seems when you give licho an attack order(as in red, force fire command) it will drop bomb on anything in its path to that target.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/40699062-94cd1890-6415-11e8-9847-cd5deb4a69dd.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/40699088-bccfe66a-6415-11e8-9ffb-1fc1c678cc71.png)

**Comment by GoogleFrog** [comment]
- Lihko has attack command on Grizzly. So it fires.
- Lance blocks Lihko. It fires at Dominatrix but hits Lance.

I see no issues here.

**Comment by Fealthas** [comment]
Yeah, you're right. I miscliked in the first scenario.

For the second, I guess it is just pene hitbox being tall. I've never experienced that being a problem before though.
