### ISSUE TITLE
save campain progress online - port to new installation

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3107]
http://zero-k.info/Forum/Thread/25600

"Just changed to a new client a few days back and I frowned upon knowing that all my progress were gone and tells me that the progress is actually saved locally instead of being saved along your player stats and stuff. It would be nice if we could have this saved online instead of offline. "

**Comment by MystesofEternity** [comment]
This is TaurusSilver
No, I am using a standalone client outside of steam.
So does this mean that campaign is saved through steam cloud? Guess that can't be helped on my case I guess.

**Comment by Licho1** [comment]
Yes saving is onyl done via steam. Sorry.
