### ISSUE TITLE
Archer impulse randomly makes target units unable to move

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3116]
This is a way too janky behaviour for a trivially spammable unit. The move lock "ability" is also completely unpredictable and as far as i know, unintentional. Two archers shooting each other will sometimes result in one archer immobilised while the other runs around joyfully. 

Sometimes it is capable of immobilising units as big as Grizzly, other times it can't immobilise a raider.

I think it would be best to replace the Archer impulse push mechanic with a non-impulse displacement and without ungluing the target unit from the surface.

**Comment by sprunk** [comment]
Should be remedied by sonic Archer #4041
