### ISSUE TITLE
Terraform commands self destruct before they're completed

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3118]
Terraform commands sometimes abort themselves for apparently no reason before actually reaching the targeted height. Maybe they are also wrongly initialized.

Check minute 6 here: https://zero-k.info/Battles/Detail/552804

**Comment by FeXoR-o-Illuria** [comment]
I can confirm this bug.

**Comment by sprunk** [comment]
410 Gone
