### ISSUE TITLE
Implement Chinese translation

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3119]
The [Chinese translation](https://www.transifex.com/zero-k/zero-k/language/zh_CN/) for ZK has quietly reached completion on Transifex.

![image](https://user-images.githubusercontent.com/3822768/40967025-bae3ec12-68ba-11e8-9323-559098105475.png)

There are two steps required to integrate it:
- [x] Collect the resources, arrange them into a PR, and add Chinese to options
- [ ] Figure out how to trigger fontconfig generation on Windows in a user-friendly way, and disseminate this information to users. I guess this could be a Chobby button of some sort.

**Comment by GoogleFrog** [comment]
@Anarchid there is no documentation that I can find on how to do fontconfig generation. Attach that information to this ticket.

**Comment by Anarchid** [comment]
`spring --gen-fontconfig` enables (and forces) creates the fontconfig cache on Windows.

**Comment by zuokaiyi1** [comment]
" Chinese translation"This link has been 404

**Comment by Anarchid** [comment]
It probably requires a Transifex login. It works for me: 
![image](https://user-images.githubusercontent.com/3822768/60802771-5ecfae00-a182-11e9-92b3-47f32ae30b0d.png)

**Comment by southern-dust** [comment]
Does anyone still working on Import Chinese Translation? (On Windows

**Comment by Anarchid** [comment]
A language switcher was added to lobby which should allow it to be restarted with an appropriate command once the language switches to Chinese, but the actual part has not been added. 

Feel free to take the project up.

**Comment by southern-dust** [comment]
> 
> 
> A language switcher was added to lobby which should allow it to be restarted with an appropriate command once the language switches to Chinese, but the actual restarting with `--gen-fontconfig` part has not been added.
> 
> Feel free to take the project up.

Thanks for your working! I wanna to test this change but how can I do this?
I tried Zero-K:Developing[http://zero-k.info/mediawiki/index.php?title=Zero-K:Developing] and Mod_Creation[http://zero-k.info/mediawiki/index.php?title=Mod_Creation] , but these instruments were confused.
Waiting for your reply, thanks!

**Comment by Anarchid** [comment]
Apparently `--gen-fontconfig` does nothing. 

https://springrts.com/mantis/view.php?id=6444

**Comment by KagurazakaNyaa** [comment]
> Apparently `--gen-fontconfig` does nothing.
> 
> https://springrts.com/mantis/view.php?id=6444

Looks like it has been fixed in version 106.0.1
https://github.com/spring/spring/commit/2225f0f1cf68870167bd606666a61d01c11b4f09

**Comment by Anarchid** [comment]
https://github.com/spring/spring/commit/2225f0f1cf68870167bd606666a61d01c11b4f09 is the commit that __introduces__ this problem.

**Comment by sprunk** [comment]
a642bdbf485a8d7dd80bc996743b08c4c3e11ad9 & 79df49d9d720bef07b942e232c8e86c99add730b
