### ISSUE TITLE
Units can crawl under air pads and be invisible and indestructible without amphbots

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3121]
I built 4 airpads on the water, and they were getting destroyed for seemingly no reason until I saw 2 ducks under them, AFTER two got destroyed. I don't think I need to explain why this is a problem

**Comment by F4Tornado** [comment]
Makes sense, but I think you should be able to tell whats happening before its too late.

**Comment by GoogleFrog** [comment]
Hard to spot underwater occlusion is part of the reason that water-only weapons (torpedoes and depth charges) pass and aim through allied units.

**Comment by F4Tornado** [comment]
But I still think you should know whats happening, and I didn't know water weapons do that.
