### ISSUE TITLE
Incorrect constructor count

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K#3123]
Sometimes ZK shows incorrect constructor count, as seen in this battle, after my com died: http://zero-k.info/Battles/Detail/558510

I'm not sure if I managed to take a proper screenshot, but it was varying from 2~1, and would stay at 1 even if my only con was working.

https://i.imgur.com/F7FIPfO.png

**Comment by sprunk** [comment]
Replay 404'd.
