### ISSUE TITLE
hivemind glitched after I crashed and rejoined

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K#3142]
http://zero-k.info/Battles/Detail/567871

All newly created units were put under the non-existing team control...

**Comment by ashdnazg** [comment]
I won't be surprised if it's a combination with the afk unit giver.

**Comment by sprunk** [comment]
Engine is misbehaving: https://springrts.com/mantis/view.php?id=6039

Alternatively, callins to detect people quitting and rejoining could be made accessible for a Lua solution: https://github.com/spring/spring/pull/369 (would also need `SyncedPlayerAdded` and `Removed`, but so far no feedback even on `Changed`)

@ashdnazg

**Comment by sprunk** [comment]
Duplicate of #3142 (actually the other way around but that one has a fresh replay)
