### ISSUE TITLE
Lua recursion error

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3148]
https://github.com/ZeroK-RTS/CrashReports/issues/11187
```
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowCommand trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_transport_pickup_floa..."]:219: GiveOrderArrayToUnitArray() recursion is not permitted
```

**Comment by Histidine91** [comment]
This gadget seems to run off voodoo. I couldn't even get the "unload into water" thing to work more than once in current stable, so had no way of telling if the fix works.

(in principle it should, but I've been bitten by _that_ notion enough times already)

Anyway, I guess I'll close this for now. Reopen if seen to persist.
