### ISSUE TITLE
User request: expose more parameters for chicken custom

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3151]
Some things are hardcoded at the moment. I've got requests specifically for `queenHealthMod` and `waveSizeMult`, possibly some others could be done as well.

**Comment by Histidine91** [comment]
Added a few modoptions (max tech was previously available to startscript, but not modifiable in lobby).

Thought of exposing the min/max aggro as well, but I decided it would bloat the modoptions menu with values whose function (and "sane" value range) aren't obvious.

**Comment by sprunk** [comment]
Looks done. I think including more would require changes to Chobby modoption UI because else the sheer number of tweakable knobs would become overwhelming. Possibly https://github.com/ZeroK-RTS/Chobby/issues/105
