### ISSUE TITLE
Allow spaces between disabledunits +

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3152]
Disable units modoption does not allow spaces. `Mace+Halberd` is kosher but `Mace + Halberd` is not.

**Comment by ArchShaman** [comment]
modoptions.disabledUnits = modoptions.disabledUnits:gsub(" ","")?

**Comment by sprunk** [comment]
`Big Bertha`

**Comment by ArchShaman** [comment]
modoptions.disabledUnits = modoptions.disabledUnits:gsub("%s++%s*","+")?

**Comment by Anarchid** [comment]
What you really want to do is to `trim` each substring separated by the `+`. 

While lua doesn't have built-in string trim, there's a bunch of [copypaste](http://lua-users.org/wiki/StringTrim) available.

**Comment by Anarchid** [comment]
Won't that match nothing because `++` never occurs anywhere?

**Comment by Anarchid** [comment]
`%s+`  one or more space characters
`+` - unescaped "one or more" quantifier

Pattern parse error, and if you fix that, you still fail to match things like `Scorcher+   Big Bertha` because the "one or more" is not satisfied. 

`%s*%+%s*` should work i guess.

**Comment by sprunk** [comment]
`:gsub("^%s*",""):gsub("%s*+%s*","+"):gsub("%s*$","")` probably

**Comment by Anarchid** [comment]
At that point you my as well just [trim5](http://lua-users.org/wiki/StringTrim) the string tokens after split maybe.
