### ISSUE TITLE
Check unit build priorities

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3166]
http://zero-k.info/Battles/Detail/577856

Some strange stuff was going on in this game. When I was trying to build a singu with High Priority, my GS factory was eating up metal despite it being on low priority. Is this an engine bug or a zk bug?

Note later on that the behavior "corrected" itself.

**Comment by ArchShaman** [comment]
Theory about what happened:

Firepluk at one point stated that there was something wrong when storage was completely depleted, maybe this is an instance of this bug?

**Comment by sprunk** [comment]
ZK bug (engine has no builtin priority). The battle is 31 minutes so a rough timestamp would be good.

**Comment by ArchShaman** [comment]
[f=0024761] <_Shaman> seems unit priorities are fucked up

There's a rough time stamp.

**Comment by sprunk** [comment]
404

**Comment by sprunk** [comment]
nvm there's a local link

**Comment by sprunk** [comment]
Old engine.
