### ISSUE TITLE
Check startbox names

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K#3168]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Configs/StartBoxes/FrozenPlanetV3.lua

The start boxes are named "North/South" in the config file, but the start boxes are actually east and west.

**Comment by sprunk** [comment]
Actually that was an autogenerated name so there might be more lurking. @Anarchid

**Comment by DeinFreund** [comment]
If you check the script, also fix the FFA boxes please. All of the 4 way corner maps have a broken southwest box.

**Comment by Anarchid** [comment]
> If you check the script, also fix the FFA boxes please

I think that got fixed earlier (mostly manually but one case escaped manual detection). Any surviving examples?

**Comment by DeinFreund** [comment]
Sandcastles 2

**Comment by Anarchid** [comment]
As per actual issue: The script that i have on this machine assigns empty names to maps which are neither `!split` nor `!corner` - it doesn't try to figure out which direction they are. FrozenPlanet is one such map:

```
7446,FrozenPlanetV3,8,8,"!clearbox
!addbox 0 0 15 100 1
!addbox 85 0 15 100 2
"
```

Possibly there's some other version of the script (on another machine) which tried to guess names for `!addbox` maps. Or possibly something else generated them.

The list of maps which used to be `!addbox` is [here](https://pastebin.com/3Pb15fUD).

**Comment by sprunk** [comment]
I took a look at cb57d4f6ca1acbbd3c5c1d1e764fe641c3140379 and everything except `FrozenPlanetV3` looks correct. Reopen if something is found.
