### ISSUE TITLE
Unit optimizations

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3169]
Tremors and Nimbuses need to be optimized, they cause extreme lag in matches with lots of players.

**Comment by ArchShaman** [comment]
Can you define "lag" better here? Do you mean high network ping or FPS loss or input lag? Are you playing on steam with steam overlay disabled?

**Comment by ArchShaman** [comment]
Are you using steam version of the game?

**Comment by F4Tornado** [comment]
Yes, its like what happens when you start spectating a game thats already
started.

**Comment by ArchShaman** [comment]
Okay. What you mean to probably say is that the large volume of projectiles needs to be changed because they cause framerate issues in larger quantities. Right?

**Comment by ArchShaman** [comment]
That input lag is actually from steam overlay. This is a known bug. See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2322

**Comment by F4Tornado** [comment]
Disabling the steam overlay fixed the input lag, and it seemed to fix the frame rate lag, but not the ping lag.

**Comment by sprunk** [comment]
Tremor and Nimbus tend to appear in games that are already performance-heavy so this is probably a correlation/perception thing. I think the only real actable-upon issue here might Tremor's ground smoothing (and then only to some extent, some cost is engine repathing which is out of our control).

**Comment by F4Tornado** [comment]
I agree with that, but I notice the lag really start to get bad when tremors or nimbuses start getting used.

**Comment by Histidine91** [comment]
I think Nimbus could fire fewer higher-damaging shots to some extent without significantly affecting balance. Tremor could too in principle, but some of its effect relies on saturation and AoE effects so would be more complicated.

**Comment by ArchShaman** [comment]
>Disabling the steam overlay fixed the input lag, and it seemed to fix the frame rate lag, but not the ping lag.

Good to hear. Dunno about ping problem. /shrug

**Comment by darloth** [comment]
Seems like a reasonable thing to announce to me.  I've seen a few streamers complain about this issue, and had it myself, and never realized it was steam overlay based until I read this issue.

**Comment by sprunk** [comment]
I haven't seen any proof that it is specifically Tremor or Nimbus that cause disproportionate load themselves as opposed to generally being inclined to appear on porcy games that are already perf-heavy.
