### ISSUE TITLE
Vote kicking somewhat broken

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3179]
In a a game, someone voted to kick me only so they could use my units, everybody voted no though, but it's still a problem. I suggest requiring a reason why they want to kick you, and if it gets passed, someone looking at the game to see if the kick was justified, and if it wasn't, punishing the player who started the vote.

**Comment by sprunk** [comment]
You can already put in a reason and we already punish unjustified kicks if they get found. Also wrong repo.
