### ISSUE TITLE
Saveload: morphing not saved

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3180]
Affects commanders https://zero-k.info/Forum/Thread/25871

Most likely also the aura bots and geo.

**Comment by BadLucKWyvern** [comment]
If saved while morphing, the morph is interrupted, and the mortp isn't possible anymore, but precedents morphs are saved (they aren't lvl1)

**Comment by Histidine91** [comment]
4a34b8168adf75b0ec48dfde578d0fe53eaa9b97
