### ISSUE TITLE
LuaRules Errors lead to desync

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3185]
The errors all seem to be along the lines of being unable to load/find resources. 

Errors: http://paste.springfiles.com/view/367602c7
Full infolog: http://paste.springfiles.com/view/e7463830

**Comment by DeinFreund** [comment]
I'm fairly sure I don't have a corrupt download, as those files usually exist. Something must've messed up spring during the run. After a restart it could load everything just fine again.

**Comment by ArchShaman** [comment]
I also got something messed up on my end during a little shitcode testing for my troll map. A continous vomit of [f=0001708] Error: [Watchdog::ClearTimer(num)] Invalid thread 0.

**Comment by sprunk** [comment]
Some pool archive structure is destroyed right before the errors:
```
[f=0008658] [~CPoolArchive] name="D:\Software\Steam\steamapps\common\Zero-K\packages\f84b548d952977a137539a93bb8bad99.sdp" numZipFiles=7605 sumInflSize=673240kb sumReadTime=1248ms
[f=0008658]     file="unittextures/gritty1.dds" indx=7004 inflSize=5461kb readTime=40ms
```
I don't know whether the engine is at fault to do that mid-game. AFAIK Steam is supposed to get the entire packed archive though, not pool pieces, so possibly either Chobby or Wrapper is misbehaving as well to allow this in the first place.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/02a62484d172cc485273639946167f7b450dd496 could've solved it. If not, make a new ticket in chobby/infra repo because this is a distribution problem.
