### ISSUE TITLE
Can't play downloaded maps in multiplayer

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3187]
I have a downloaded map I want to play in multiplayer, but it only works when the game is passworded. If it's not passworded, it says "no such map can be found".

**Comment by sprunk** [comment]
This is by design: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/7463add8bde58cedfc5bd3d85f0b8cd14abe4b78

Also this is the game content repo so if you want to challenge this design then make a ticket in the infra repo: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/new

**Comment by F4Tornado** [comment]
Now I can't play it if it is passworded.

**Comment by sprunk** [comment]
Describe it in a ticket in the infra repo.
