### ISSUE TITLE
Campaign commander slots can get corrupted

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3201]
Here's another case of Lvl 4 commander with only lvl 3 slots being available. Apparently it stems from a file corruption. 

https://steamcommunity.com/app/334920/discussions/0/1696045708651463798/?tscn=1533662647

Would it be possible to check if the loadout makes sense and try to fix it if it doesn't (e.g. lacks levels)?

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/issues/627
