### ISSUE TITLE
ALT-SHIFT-Q builds leaving gaps

### ISSUE THREAD

**Issue by bish0polis** [ZeroK-RTS/Zero-K#3204]
Building Storage or Caretaker blocks with SHIFT and maybe ALT?  It seems to be skipping for me.  Usually if I build a 2x2, I'll miss 1-2; it's that bad!  Separately, did the ability to SHIFT-drag to build Storage units suddenly get blocked or broken?  Anyone else seeing issues with mass building like that?

**Comment by DeinFreund** [comment]
This is intentional. You can adjust spacing using the x and z keys during the line/rectangle placement. For caretakers there's a default spacing because otherwise they would chain explode. The same counts for many energy generators.

**Comment by bish0polis** [comment]
A good guess, but it's not just interleave distance.  What I mean is, 

What we place/request/queue:
```
XXXXXXX
XXXXXXX
```

What's built:
```
X XXXX 
XXX X X
```

Even a line can be affected
Requested:   
`XXXXXXXX
`
Built:
`XXXXX_X_
`
To be clear, units queued to be built, for which visual feedback (the placement square/marker) indicates a unit will be built there, sometimes don't get built at all.  

As for specifically the storage unit, no combination of Z or X will allow for a second one to be placed anywhere on the same screen while holding SHIFT.  Can I reset a per-unit spacing tunable somehow and see if - for the storage unit - it's a setting that's so far past an upper limit that it can't come back?  (there IS an upper limit, right?)

**Comment by bish0polis** [comment]
This happens often with Air Ctors and often with [Q], as [Q] is the greatest thing around.  Are you sure it's a pathfinder issue?

The exact moment when the wireframe marker disappears is when a constructor is ready to apply resources and instantiate the form:  the wireframe marker disappears instantaneously (ie no waiting for motiles to clear) and the ctor unit will just move-on to the next queued item.  

No idea on the max interleave between Storage units, and whether I can reset just its value?

**Comment by DeinFreund** [comment]
Could you post a replay of this issue? I'm not sure I understand correctly what you mean.

**Comment by bish0polis** [comment]
No, I can't seem to figure the UI and force a replay, either through a magical key to create a room or not.  Is there a commandline I can use to get those local replays in a portable state?  

Reinstalled game.  Same behaviour.

1. start blockwars-FFA v25 with a lame UI
2. create airport, mines, solars
3. create ONE air ctor unit
4. using alt-shift-q, drag to create a 4x12 block of caretakers, observing no obstruction/yellow indicators
5. wait, observing 4-6 nanoframes not created
6. using shift, attempt to create a line of Storage , observing only one structure queued.

I can provoke this all day;  I just can't seem to figure the UI today to get a shareable replay, and rage is setting in.

**Comment by bish0polis** [comment]
A fresh install, deleting entire F:\SteamLibrary\steamapps\common\Zero-K tree, to hopefully re-enable replays if they're missing.

 - lowest graphics, to accidentally fix the missing cursor bug
 - windowed, so it can go to the other display because .#2018 
 - start game, download blockwars-FFA 2.5 
 - beginner AI
 - start. 
 - create airport, shift-build two caretakers (x once for 0 interleave), solars, mexes (same 0-interleave via X a few times).
 - air ctor shift-alt-q builds 4x9 block with 0 interleave
   - gaps as shown once building completes
 - build another 4x8, alt-shift-q, hitting Z once to add interleave
   - gaps here too

No replay created when searching after Exiting to lobby (done without thinking; sorry).

I'm sure I'm still doing something wrong, but I'm just not seeing where I could have messed it up.

![image](https://user-images.githubusercontent.com/13486046/43997200-828e4ac4-9d8a-11e8-97ca-a07c2e6bff30.png)

**Comment by Histidine91** [comment]
Reproduced the issue: [20180812_120011_BlockWars-FFA V2_104.0.1-287-gf7b0fcc maintenance](https://www.dropbox.com/s/ac1e0uxq5kv2m91/20180812_120011_BlockWars-FFA%20V2_104.0.1-287-gf7b0fcc%20maintenance.sdfz?dl=0)

[screenshot](https://i.imgur.com/wyOigyj.jpg)

Note that building _without_ Q does not display the error. UnitCreated is not called for skipped buildings. 

My suspicion is that the builder is being given a stop order before the nanoframe is actually created. I plan to look into this further.

**Comment by bish0polis** [comment]
@Histidine91 , Thanks for getting a replay available!  

I'm sure i could get the bug to pop out without Q, but now I can't on my fresh install.  And hey, that's great news, today!  ;-)   I can accept I was hallucinating (it's very warm here) and we can call it done.

**Comment by Histidine91** [comment]
Devised a fix for next ZK version, thanks for report!
