### ISSUE TITLE
Replace resign on quit by improved inactivity win

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3212]
- [ ] Pause the game when inactivity win is available
- [ ] Assure inactivity win window is always in foreground, so it can be clearly seen
- [ ] Allow inactivity win once ping exceeds 10 secs as well as on a dropped connection
- [ ] Remove resign when clicking "Exit to Lobby" in the main menu

**Comment by GoogleFrog** [comment]
Pausing when inactivity is detected is a regression. Imagine 8v8.

If resign on quit is removed then inactivity should be flagged immediately upon quitting.

**Comment by DeinFreund** [comment]
This is for the inactivity win. You can see in the PR that it only kicks in if all players of the enemy team are dropped or have a ping > 10 seconds. This is nothing I ever see happening in 8v8.

**Comment by GoogleFrog** [comment]
I'm just reading what the ticket says without stopping to load too much of the context back into my memory.
