### ISSUE TITLE
Make terra and patrol commands use max 8 params

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3218]
Engine allows this for now but it might stop being the case in the future.
https://github.com/spring/spring/commit/10f807a1ce959dd4b4f019754406379da6212da8

**Comment by GoogleFrog** [comment]
As far as I understand, the engine now has special pooled handling for commands with more than 10 parameters. Given the work this took I don't expect this to change. I would also fight a practical limit to the number of parameters that can be added to a command. Perhaps terraform is implemented unreasonably, but I can imagine cases (in some other game) where it would make sense to add custom commands with 10s of parameters.

**Comment by GoogleFrog** [comment]
Confirmed that the engine has a special handler for many-parameter commands. Closing.
