### ISSUE TITLE
rezzing non-underwater units underwater.

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3220]
http://zero-k.info/Battles/Detail/599598

underwater gauss is too strong. also x4 armour. also underwater has no artillery....

suggestion: underwater rezzed units are constantly disabled or max slowed or rezzing not possible or terraspike autocreated to lift building over water or sth else...

**Comment by mojjj** [comment]
btw, does antinuke work when rezzed underwater?

**Comment by sprunk** [comment]
The trivial fix is to make Gauss floating. IIRC this doesn't require making it actually buildable on sea but that could also be considered (regardless of whether we're forced to do it).

**Comment by Anarchid** [comment]
I have a Munsell Gauss model lying around. No texture modifications, a bunch of pieces to adjust altitude.

![image](https://user-images.githubusercontent.com/3822768/44395834-c3baef00-a543-11e8-8de6-0e2d8600fda8.png)
