### ISSUE TITLE
Label text is white in the chat log, despite only being visible to allies

### ISSUE THREAD

**Issue by darloth** [ZeroK-RTS/Zero-K#3225]
It should be green, like almost every other only-allies informative message.

**Comment by GoogleFrog** [comment]
I disagree, because it is good for labels to be distinctive.

**Comment by darloth** [comment]
Ok.  Can we compromise on a colour that isn't white?

White isn't particularly distinctive, there's lots of white in the chat log.

Dark green?  Cyan?

**Comment by sprunk** [comment]
@darloth the option to use green will still be there under `Settings/HUD Panels/Chat`.

**Comment by darloth** [comment]
Thankyou for letting me know there is the option, I will certainly use it for myself.

However, my original comment stands - if label text is meant to be distinctive, I don't believe white is sufficiently distinctive.  Up to you in the end, but there are many other colours it could be.
