### ISSUE TITLE
Swift can land on planefac buildpad

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3228]
It happened today after I removed one plane from the factory queue which cleared it. I queued one plane of a different type very soon. The factory didn't do anything despite that. I didn't know how to get it to build again because it didn't have a Wait command active. A new air factory had to be built.
http://zero-k.info/Battles/Detail/603250

**Comment by sprunk** [comment]
![screen00020](https://user-images.githubusercontent.com/2573076/45933725-02085b80-bf93-11e8-9c47-c4e45b159a01.png)
Swift managed to land on the buildpad somehow. The factory script needs BUGGER_OFF (or maybe a filled yardmap would do?)

**Comment by sprunk** [comment]
Weird, it does have BUGGER_OFF already. Possibly its radius is not large enough to actually reach the unit because of how offside it is?
