### ISSUE TITLE
Adv Targetting System + noExplode bug

### ISSUE THREAD

**Issue by Bla1** [ZeroK-RTS/Zero-K#3233]
Adv Targetting systems seem to have no effect on the commander's DGun. I stacked 8, and even though the range UI shows that the range is increased, when I actually fire the dgun, the plasma thingy disappears before it reaches the end of the range.

**Comment by sprunk** [comment]
Flamethrower is also affected. It does not immediately disappear at the original range edge but loses piercing ability.

Engine issue, https://springrts.com/mantis/view.php?id=6038

**Comment by sprunk** [comment]
https://github.com/spring/spring/commit/93b22d069897c80901857b3aa450c255724bf9d9
