### ISSUE TITLE
Cyclops has a useless sidearm on the model

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3234]
~~Let's give it Leveler cannon because now the model looks odd.~~

**Comment by Histidine91** [comment]
My suggestion was Gremlin AA laser: 
- Won't affect the sensitivities of ground combat balance; can be suitably insignificant in general
- Has a good appearance and position for it (top of turret)

**Comment by Anarchid** [comment]
Gremlin sidearm ranks second in my mind after "just hide or remove the thing".

**Comment by ArchShaman** [comment]
Why not give it a mace laser tower side arm that can only target AA. Color it purple, because purple makes things stronger and faster.

**Comment by sprunk** [comment]
How about a slowbeam? It already has a slow component on the cannon, we could separate them.

(hide it)
