### ISSUE TITLE
Deliberate toning down Fire At Will teamkilling programmatically

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3235]
I think the damage caused by Fire At Will friendly fire can be reduced by considering the area damage done by weapons. The code could also predict unit movement based on its current characteristics and the velocity of the weapon projectile. Additionally, it could check whether there are units in the way.

If the player still wanted to attack the target unit, an express Attack order would bypass the code that is meant to lessen teamkilling.

However, rules such as these may cause units to fail to shoot at crucial moments, but I think there's a chance they would work. The last two methods sound too laborious to implement for the gain and the possible performance hit, although the first one seems fine.

**Comment by Anarchid** [comment]
Target avoidance is an engine mechanic. This is a Spring Engine feature request.

**Comment by sprunk** [comment]
I believe this is a ZK request (see snipers not firing at radar and other uses of `gadget:AllowWeaponTarget`) but the ticket is nevertheless not useful.

I don't think accidental teamkills (of the variety where the damage to self greatly and obviously exceeds comparative damage to enemy) are common enough to warrant doing anything. There's always the performance cost, and then depending on whether you do it as a state toggle or hard-enable it there's either the cost of UI clutter or the cost of units misbehaving in a hard to predict way. Teamkills where the damage is not
