### ISSUE TITLE
Consider enhancing the Dominatrix capture link looks

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3243]
The current line looks a bit dull and it can penetrate the terrain geometry. It could be replaced with team-colored glowing spheres going into the captured unit that stay above the ground.
![balls](https://user-images.githubusercontent.com/2042701/45590686-c3492480-b946-11e8-900f-220ffbc80e37.png)

**Comment by sprunk** [comment]
Preventing the leash from being obscured by the ground sounds good. I wouldn't go as far as guaranteeing no ground penetration though, probably just disable depth checks.

The line is, in a way, supposed to be dull. It should be immediately obvious which unit is connected to which domi and I think the balls make it less clear than the lines - curvature makes it harder to follow for a distant unit, the balls look somewhat more like inworld entities than UI, and in the case with multiple domis and nearly-overlapping leashes it would be much harder to tell which balls are for which leash.

**Comment by Anarchid** [comment]
It's conceivably not that difficult to bump up vertices of the leash strip to always be higher than groundY.

**Comment by sprunk** [comment]
What for? Curved leash is harder to follow.

**Comment by Anarchid** [comment]
It's already curved, though, looks like a bezier? Clamping the control vertices to aboveground should keep the curve aboveground while still reasonably smooth.

**Comment by GoogleFrog** [comment]
The leash is a bezier iirc. Dull is good, don't overwhelm the player with information that they don't always want.
