### ISSUE TITLE
Make Gauss buildable on sea

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3244]
Gauss now has a cool floatation pillar (d860b491122cd832bdff5eb1504540ce64e03c83) but it is wasted as it cannot be built on sea (only appears if wreck is sunk and rezzed).

**Comment by Sharkgamedev** [comment]
What was the final decision on this? I know in #4008 it was mentioned that this was simply to prevent an op underwater gauss and that they should not be buildable on water, does that mean this issue should be closed?

**Comment by sprunk** [comment]
There doesn't seem to have been any explicit decision but if there had to be one it would probably be to stick to the status quo. Sea is perpetually hated and perpetually receives redesigns so it may be useful to keep the ticket around for the next time something needs to be done though.

**Comment by sprunk** [comment]
Maybe sea Gauss is an obvious enough thing to try when touching sea that it doesn't need a ticket after all.
