### ISSUE TITLE
Minor sea chicken improvements

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3252]
Chickens were never designed for sea and ultimately these won't change that but they seem like a low mana way to improve the situation:
 - [ ] give chicken projectiles the ability to pierce water.
 - [ ] probably make melee chickens walk underwater (because the juicier eco buildings don't float)
 - [ ] #sonarLives
 - [ ] there are reports that chickens have some sort of slowdown on water, check whether this is true and remove.

**Comment by ArchShaman** [comment]
I've got a branch that's working on the issue. Basically I've changed the following:

* Melee units walk underwater. (Taken from the duck unitdef)
* Goo and spores now pierce the water.
* All chicken units now have sonar = sight.
* Dodo now walks underwater. (It's a "melee" unit, right?)
