### ISSUE TITLE
Check huge metalmult values

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3262]
![image](https://user-images.githubusercontent.com/2573076/46300132-3c7d8400-c5a3-11e8-9781-0142015eab5c.png)

**Comment by ArchShaman** [comment]
Hm, it looks like at some point, the mex highlighter (?) widget should switch over to text. Probably would be safe at 100+ income. Past here one could do k,mil,bil,tri and equiv. 
EG:
1000 -> 1k
10000 -> 10k

Although past 10 thousand per second income, I think we can safely call it "infinite" metal as nobody will ever be able to create an economy with 1bil pull cuz engine limitation of 1600 units per player would put the maximum draw of 15,980 metal per second, assuming free energy.

**Comment by Anarchid** [comment]
Imo:
1) Show bars until there are at most 4
2) Show digits until at most 999
3) Show "k" until at most 99k
4) Go full scientific notation above that because you're astronomical anyway, e.g. `8e10`

**Comment by ArchShaman** [comment]
IMO similar to Anarchid's idea, but past 15k, just have it display as ∞.

**Comment by sprunk** [comment]
I made a fix before your suggestions appeared (but didn't commit it to master at the time) so they didn't get in. Here's what I did
![image](https://user-images.githubusercontent.com/2573076/46443995-38529180-c770-11e8-8b56-3329e82c0279.png)
