### ISSUE TITLE
Fleas can gain cloak while moving without Iris somehow

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3268]
http://zero-k.info/Battles/Detail/624088

You can later on see me trying to replicate it but with no success.

**Comment by ArchShaman** [comment]
Permacloak here is where they do not uncloak when moving around. (It seems like the walking animation function isn't called because they get stuck in the burrowed position). I actually used this to spy on fenrave in this battle.

**Comment by sprunk** [comment]
Duplicate of #3548
