### ISSUE TITLE
The Tabula-v6.1 grass is orange

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3270]
The grass of the featured map "The Tabula-v6.1" is orange. Isn't that erroneous since the map doesn't have an autumn theme?

**Comment by sprunk** [comment]
It seems intended given the map has orange lighting/atmosphere and a desert in the middle.

**Comment by sprunk** [comment]
Feel free to make an alternate version though, but remember grass is always greener on the other side :P

**Comment by The-Yak** [comment]
Tabula doesn't have any grass color set, so grass shader grabs colors from current position on map. That's why grass is turning orange on the sand.

Trivial to fix but needs a map release.
