### ISSUE TITLE
Nuke refuses to fire

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3278]
![image](https://user-images.githubusercontent.com/1318249/46934620-25ab5700-d0a4-11e8-888b-732eb667d57b.png)

http://zero-k.info/Battles/Detail/620987

It later fired at 31:47.

**Comment by Licho1** [comment]
It thinks it will hit the wall?

**Comment by GoogleFrog** [comment]
It is a starburst launcher with no qualms about harming or hitting allies. I didn't think that anything would stop it from firing. The ticket still needs to be verified by cheating and godmoding into the game at the appropriate time.

**Comment by sprunk** [comment]
The replay is gone.
