### ISSUE TITLE
Context menu: death explosions

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3281]
It would be good to see the explosion radius and damage of all notable buildings. For example,
- Wind/Tidal Generator
- Singularity Reactor
- Fusion Reactor
- Energy Pylon
- Factories
- Geothermal Generator
- Advanced Geothermal Generator
- Desolator
- Lucifer
- Detriment
- Paladin
- Missile Silo
- Ultimatum

**Comment by sprunk** [comment]
Use the `stats_show_death_explosion` unit def custom param.
