### ISSUE TITLE
It is very common in 2v2 MM for people to drop before or shortly after game start

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3283]
Due to the low activity I'm not sure what should be done about this. Could this be automatically detected and forwarded to the server so we could possibly implement some penalty for quitting games in the future?

**Comment by sprunk** [comment]
This seems like an infra ticket but I am closing it instead of moving because a penalty nominally exists and I don't think "people often drop" is still true anymore.
