### ISSUE TITLE
Snitch/Roach don't die when colliding with other units at high speeds

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3288]
When you build a roach/snitch cannon, it often happens that roaches collide with other units and bounce off. They only explode once they hit the ground and don't receive meaningful damage from collisions with units.

They should: 
- Not be elastic, so they lose all kinetic energy on a collision. 
- Die when flying at roach-cannon speeds and hitting something.

**Comment by GoogleFrog** [comment]
Apparently attackerID is now given in unit-unit collisions. 
![image](https://user-images.githubusercontent.com/1318249/47262216-1017b080-d52e-11e8-94ac-ec4901fc3fc1.png)
