### ISSUE TITLE
Can't move mouse outside of ZK window

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K#3292]
I have a 3 monitor setup, and I can't use it since when playing or spectating, I can't move my mouse outside of the screen. I suggest adding an option for that, or building that option into the "windowed" mode.

**Comment by ArchShaman** [comment]
This is a nonissue I believe.

To "fix" this behavior type /grapmouseinput (or whatever it is)

**Comment by Licho1** [comment]
Alt-tab also fixes it or pressing window button.

**Comment by sprunk** [comment]
1f4a4b4288d59d889e27ccec84fae0a9cb7ea03b

(the setting has since moved to `Settings/Interface/Mouse Cursor`)
