### ISSUE TITLE
Designing a New Likho Model

### ISSUE THREAD

**Issue by Phytophyte** [ZeroK-RTS/Zero-K#3293]
Okay, let's see if we can pick this up from [the forum](https://zero-k.info/Forum/Thread/27179?page=1). Here's three concepts for the stealth-bomber-with-a-singularity-face Likho. Which direction do we want to take this?

![lc4](https://user-images.githubusercontent.com/34325211/47272369-39ded080-d54a-11e8-8e87-9b0fda419dba.png)

**Comment by Anarchid** [comment]
All of these are great IMO. I slightly prefer the hull design on the first one though.

**Comment by sprunk** [comment]
3A and 3B have this banana/boomerang shape like Raven. Current Likho has a recognizable bulky shape with those two engines around the middle - 3C looks the most similar. I think keeping the unique shape would be the best.

**Comment by GoogleFrog** [comment]
I agree with @sprunk regarding the wings, and really like the non-wings parts of 3C. The wings are good too, but I don't like them as much as the center. I think I'd be happy with 3C.

**Comment by Phytophyte** [comment]
All right, here's a version with more angular wings, like our Likho Classic.

![likho_concpets_5](https://user-images.githubusercontent.com/34325211/47588109-b26ad600-d92a-11e8-807f-3ba9a90c3305.png)

**Comment by Anarchid** [comment]
I think there's an extremely little chance that someone will confuse a glowing singu-ball Likho with a Raven simply because their wings look kinda similar. 

That said, 4A is good. If you're still taking recommendations, i'd prefer the rear wings to be at a sharper angle to the flight direction.

**Comment by GoogleFrog** [comment]
5B is my favourite so far. It is bulky enough to convey its higher weight, and has interesting greebles while remaining consistent. The launch chamber is nice an open and obviously faces forwards.

**Comment by Anarchid** [comment]
+1 to locking on 5B.

**Comment by sprunk** [comment]
My favourite so far is 5B as well.

**Comment by Licho1** [comment]
I like 5B about same as 4A. 3C looks too much like a fighter

**Comment by Phytophyte** [comment]
I suppose the good thing about hashing out the design first is that I don't need to continuously flood with posts to get direction. Anyway, here's the model as it stands--make suggestions if you like.
![likho_2_1](https://user-images.githubusercontent.com/34325211/50026437-912f7900-ffae-11e8-9352-5951963d1a71.png)
![likho_3_](https://user-images.githubusercontent.com/34325211/50026438-912f7900-ffae-11e8-903b-0b239697801a.png)

**Comment by Phytophyte** [comment]
Visual Production Update!  Texture is coming along nicely; gonna give people a chance to see the direction I took while I put the finishing touches on it.

Standard View
![likho_e_2](https://user-images.githubusercontent.com/34325211/53281624-4db16380-36f1-11e9-9548-3a868cb6692b.png)
Planned Grounded Position
![likho_e_1](https://user-images.githubusercontent.com/34325211/53281627-50ac5400-36f1-11e9-9d72-c374b4ecd981.png)
Engine View
![likho_e_3](https://user-images.githubusercontent.com/34325211/53281629-54d87180-36f1-11e9-9550-0f4af1457ff9.png)
Above View (with rail slider in launched position)
![likho_e_4](https://user-images.githubusercontent.com/34325211/53281630-573acb80-36f1-11e9-8482-e94630fb8332.png)

**Comment by sprunk** [comment]
Looks like not gonna happen.
