### ISSUE TITLE
Abort MM games when opponent not present on game start

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3294]
MM games with one player missing shouldn't be started, especially 1v1. As a bonus it would be nice if a message could be sent to the server, informing about who didn't actually load in.

**Comment by DeinFreund** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2432

**Comment by sprunk** [comment]
This should be doable completely server-side? The server knows who loaded and who didn't (through `SPRINGIE:READY`) and can abort the game on its own (through `/exit`).

**Comment by DeinFreund** [comment]
Yes, check the above PR
