### ISSUE TITLE
Rover factory is very easy to block

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3301]
![blockedfac](https://i.imgur.com/6VrYPAX.png)

It seems the rovers can't exit to the side of the factory.

**Comment by Anarchid** [comment]
Yep, looks like the sides are blocked:
```
xoooooox 
xoooooox 
xoooooox 
xccccccx 
xccccccx 
xccccccx 
xccccccx 
xccccccx
```
"x" is a weird character that looks quite cargo-culted here. This is what wiki says about "x" though:

> `o` - 'Obstacle' - Always closed, blocking, **all other chars are treated the same way**.

So essentially the sides are always block.
