### ISSUE TITLE
Solar tries to open too early

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3304]
Get a Flea to attack a Solar. Every 7 or so seconds it will attempt to open. Ideally each new damage instance should reset its automatic opening timer.

**Comment by n42k** [comment]
I was able to reproduce this issue, except I found it will attempt to open every 4 seconds, which is what is defined here: https://github.com/ZeroK-RTS/Zero-K/blob/master/units/energysolar.lua#L22, and used here: https://github.com/ZeroK-RTS/Zero-K/blob/master/scripts/energysolar.lua#L96.
