### ISSUE TITLE
Proconsole 2 problems

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#332]
- The text wiggles around when the button is pressed.
- This wiggle can even occur after the button is pressed twice, the spacing of the expanded view can change between instances of expansion.
- The text starts very far from the left side of the widget, this wastes a lot of space.
- Lines which are too long either clip into the side or fail to wrap at all.

![proconsole2](https://cloud.githubusercontent.com/assets/1318249/4874147/6908c70c-6240-11e4-806b-2acfc13cb77c.png)

**Comment by sprunk** [comment]
Related: #464

**Comment by sprunk** [comment]
Is this still an issue?

**Comment by GoogleFrog** [comment]
At least the first two issues are still present. I am not sure about the rest.

**Comment by GoogleFrog** [comment]
I don't think we're ever going to use proconsole 2.
