### ISSUE TITLE
Absolute damage falloff is unaffected by modified heatray range

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3322]
Commanders with range modules and heatrays deal approximately zero damage when shooting beyond the unmodified range of the heatray. The heatray may have a fixed reduction in damage based on flight time. This damage reduction should be updated to reflect its new range. Another thing to check is the effect of damage modules.

It would be best to do this in the engine. Perhaps the damage reduction per flight-time parameter could be exposed to SetUnitWeaponState.

**Comment by sprunk** [comment]
`Spring.SetUnitWeaponDamages(unitID, weaponNum, "dynDamageRange", range)` ?
