### ISSUE TITLE
Player level and ranking is not updated in game

### ISSUE THREAD

**Issue by 610th** [ZeroK-RTS/Zero-K#3323]
My level and ranking is not updated in game. I have to restart the game to see new levels and rating. Not super important, but definitely a bug. The level is updated on my user webpage.
![player_level_bug](https://user-images.githubusercontent.com/29798428/48034215-c39fb800-e15e-11e8-8aff-8089481547fa.jpg)

**Comment by ArchShaman** [comment]
This is a chobby issue.

**Comment by sprunk** [comment]
Probably fixed by the linked commit ZeroK-RTS/Zero-K-Infrastructure@ae2cdf2e5ca3a905d00de1791b05f64149c2f336.
