### ISSUE TITLE
Map texture issue with latest engine version

### ISSUE THREAD

**Issue by Collserra** [ZeroK-RTS/Zero-K#3329]
Playing on the test version "Zero-K test-14821-00cc6f1" I get texture issues with maps; the heights of all landscaping seem to be fine, but the textures are all messed up. I included screenshots.
![zerok](https://user-images.githubusercontent.com/6074608/48308503-a428d680-e534-11e8-8373-aa148ac8d754.png)

![screenshot 12](https://user-images.githubusercontent.com/6074608/48308522-11d50280-e535-11e8-815e-e714aae9e407.png)

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/2569025/infolog.txt)

**Comment by GoogleFrog** [comment]
Can you attach an infolog?

**Comment by Collserra** [comment]
Sure

**Comment by GoogleFrog** [comment]
How about now? What does enabling compatibility mode do? Sending a bug report via the Help submenu and linking it here would ensure a complete infolog.

**Comment by Collserra** [comment]
Hey,
The map texture issue was only present when testing on "Zero-K test-14821-00cc6f1". The last two updates that've pushed (the update slightly after benchmarks and now the most recent engine update) the maps have been working fine for me. I can oad "Zero-K test-14821-00cc6f1" and try again if you like?

**Comment by GoogleFrog** [comment]
I am fairly sure the issue was caused by testing the dev engine.

**Comment by sprunk** [comment]
@Collserra any feedback? Recently a new engine was applied and nobody seems to have complained about this issue so I'd assume it is fixed unless proven otherwise.

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=6072

https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/widgets/chobby/components/configuration.lua#L231
