### ISSUE TITLE
Harpies ignore force attack ground

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#3336]
Harpies were ordered to force attack ground (where there was a suspected cloaked bot) instead they were shooting units moving undernearth it despite being in range to fire at ground.

http://zero-k.info/Battles/Detail/642923?   roughly around minute 6:30  far left

**Comment by GoogleFrog** [comment]
Cloaked enemies block line of fire. Is that the bug? https://springrts.com/mantis/view.php?id=6068

**Comment by Licho1** [comment]
Sounds like it

**Comment by sprunk** [comment]
Mantis #6068 solved.
