### ISSUE TITLE
Cutter is unable to fire at max range

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#3337]
https://imgur.com/Sf9Vj9Q.png

**Comment by Godde** [comment]
Cutters will tend to move into range if given an attack command and fire away but if given a attack command within range but near max range, they tend not to fire.

**Comment by GoogleFrog** [comment]
It's probably the fault of the terrible model.

**Comment by sprunk** [comment]
cc6f0f17f3d081119dc09aec5862907cfb9b8062
