### ISSUE TITLE
[Artificial Stupidity] nimbus can be tricked into following into enemy range

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#3353]
* send nimbus with fight order
 * it will correctly target and engage at max range
 * the attacked unit is marked as set target 
 * if attacked unit moves back nimbus will follow ignoring anything else stupidly dying to any short range unit nearby

**Comment by Licho1** [comment]
Is the default meant to "set target" I don't recall engine using explicit set target.

**Comment by Anarchid** [comment]
Settarget doesn't cause unit to chase even if set.

**Comment by Licho1** [comment]
Why does it auto set target though? Same happens with racketeer overrding manual attack command.
