### ISSUE TITLE
[Artificial stupidity] racketeer with static unit kill order can switch target wasting its shots

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#3354]
* build a racketeer
 * tell it to attack enemy HLT
 * let enemy unit come closer to racketeer
 * racketeer will set target to closer unit, ignoring the HLT
 * racketeer won't change its mind even if set target unit moves back, behind the HLT

**Comment by GoogleFrog** [comment]
There isn't enough information here. What is in LOS? How do you tell it to attack? I doubt it is using the set target mechanic.

**Comment by Licho1** [comment]
The racketeer had standard attack on unit - HLT.  Racketeer auto "set target" to unit which wandered closer to it.
Its similar to nimbus behavior which was also automatically using "set target"

**Comment by sprunk** [comment]
Maybe relevant fe100c42370f3e9242dce7ba0efb72379b11cb54

**Comment by GoogleFrog** [comment]
Well this doesn't happen now. Also, I don't know of any gadget that sets set target.
