### ISSUE TITLE
Lobster need manual fire.

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#3358]
Lobster needs manual fire to be microed properly. I use Settarget and the lobster will keep attacking the same targets after given other commands.

**Comment by GoogleFrog** [comment]
I do not understand the words in this ticket. The main thing is that I do not know whether manual fire refers to firing manually or the command. The title is not a sentence, is this a request or a bug report?

The set target bit requires a replay.

**Comment by Godde** [comment]
This is a feature request. I think Lobster need "Fire Special Weapon" command.
I have enabled "Keep overriden attack target"/"Keep target". This means that the lobster will continue to fire at the same target or the same spot until given a "Stop" command.
