### ISSUE TITLE
Terraform campaign mission may be broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3362]

**Comment by FeXoR-o-Illuria** [comment]
For me the missile silo stoped firing after the first shot.
(I don't know what version that was. I also don't know for what exact reason this ticket have been opened.)

**Comment by sprunk** [comment]
![image](https://user-images.githubusercontent.com/2573076/74241187-c97a3680-4cdb-11ea-97a1-542fbcca584e.png)

Apparently the shieldfac is owned by `noname` and gets no metl share (found by [ffc] )

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/7cd821bb684ce205172e14cc634c3f9a069e3908
