### ISSUE TITLE
Weapons for level 1 commanders

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3364]
Each chassis should spawn with one of its weapons equipped. The weapon should be an "average" weapon, not one of the particularly exciting choices. I see little benefit in the current situation, and a few problems.
- New players do not know about the morph button. Showing them the morph button should not be a significantly higher priority than it is now.
- Lack of knowledge about morph leads to the common noob-trap situation in which a commander dies to many fewer raiders than it should.

**Comment by GoogleFrog** [comment]
Weapons should become free with this system, which is a fairly small change as the morph cost can be increased.

**Comment by sprunk** [comment]
Replace peashooter with beamlaser across the board?

**Comment by GoogleFrog** [comment]
Sounds fine, do all commanders have beam laser?

**Comment by sprunk** [comment]
Yes

https://github.com/ZeroK-RTS/Zero-K/blob/ac326110393424cd2e309f4ee4ca1569ae4b3d99/LuaRules/Configs/dynamic_comm_defs.lua#L77-83
