### ISSUE TITLE
Jugglenaut can no longer target Archers for some reason

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3375]
http://zero-k.info/Battles/Detail/653480

**Comment by sprunk** [comment]
>\[20:32\] terve886: also, what I noticed, is that Archers returned true with Spring.GetUnitWeaponTarget  isUserTarget while other units returned false
\[20:32\] terve886: so that is probably related

**Comment by Anarchid** [comment]
Archer had only a single target category: `SINK`. Jugglenaut's `onlyTargetCategory` does not include sink. Every other amphib unit has target categories `LAND SINK`.
