### ISSUE TITLE
Disarmed blockade runners should armor up

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3376]
The first few minutes of this battle has a Halberd attack on the north-east island that could have done serious damage if the Halberds had armored up once disarmed.
http://zero-k.info/Battles/Detail/653049

**Comment by Anarchid** [comment]
That's a bug then. Crab, Desolator, Lucifer, Gauss, Razor are prevented from armoring up when disarmed.

**Comment by GoogleFrog** [comment]
Being able to change armour state while disarmed is not intended behaviour. I would not call it a bug though as the issue is that nobody has gotten around to updating the LUS.
