### ISSUE TITLE
Allow keypresses to be disabled for Gesture menu and Integral menu

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#3381]
Feature request: I would like to disable keypresses and only use my mouse with Gesture menu.
Also, when I press the different tabs in the build menu(Econ, Defence, Special, Factory), they will take keypresses. I would like to be able to disable that.

**Comment by dvr333** [comment]
Settings/Hotkeys/Command Panel/Disable Grid Keys will stop the build menu hotkeys, as for the rest, just hit Escape when clicking on the relevant hotkey option in Settings/Hotkeys and that will clear them.
