### ISSUE TITLE
Let's allow custom games!  disabled unit field max char limit

### ISSUE THREAD

**Issue by treebark001** [ZeroK-RTS/Zero-K#3387]
Hello,

Objective:  Allow for more varied Zero-K gameplay (think custom games in Starcraft and Warcraft 3).  Do this with an easy fix

Situation / Problem:  When making a custom game and using advanced options there is a disabled field that allows you to disable units using the internal Zero-K unit name using '+' as a delineator.  Right now, it has a max character limit.  Most people use this to take away a couple units, however it would cause for more varied gameplay by also allowing the inverse, only allowing a couple units.  In order to do this though, we need to increase the acceptable character size that players can input into that field. 
Attached is a jumpbot custom game that I wanted to try out, however when I copy paste that text it simply disappears when hitting the apply button.

Outcome:  By allowing this fix, players on the forums could create their own custom games and this would increase community cohesion and varied gameplay.

Thank you. 

[jumpbot.txt](https://github.com/ZeroK-RTS/Zero-K/files/2706232/jumpbot.txt)

**Comment by sprunk** [comment]
Sounds like it's either a lobby or lobbyserver problem. Moved the ticket https://github.com/ZeroK-RTS/Chobby/issues/662
