### ISSUE TITLE
The cheating menu doesn't function in MP

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#3389]
The cheat sheet appears but does nothing. Steps to reproduce:
 
1. Create a passworded cooperative room.
2. Add an inactive AI.
3. Start the game.
4. Execute !hostsay /cheat.
5. Click on the button that opens the cheating menu.
6. Try to click on the menu buttons.

**Comment by Anarchid** [comment]
Host cheats dont' require hostsay after cheat mode is active. IIRC the only ones that do are `godmode` and `globallos`.
