### ISSUE TITLE
Dynamic water crash

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#3396]
User Someone64 had nVidia graphics driver crashes at game start that were eventually resolved by turning off dynamic water. The following properties were observed:

- Crash could be reproduced after starting a game without dynamic water, by typing `/water 2` twice.
- Dynamic water could only be disabled by editing ZK_data.lua, it did not appear to obey lobby settings at all.

Crash log: ZeroK-RTS/CrashReports/issues/19151

My preferred solution is to just remove dynamic water setting from all GUI elements that can set it. Even when it works, it doesn't look particularly good and has poor performance.

Someone should also figure out why it's not obeying lobby options. Also the fact that it stores config options in three different places (springsettings.cfg, ZK_data.lua, IGL_data.lua) is a mess that needs to be fixed eventually.

**Comment by Histidine91** [comment]
Removed from Chobby in ZeroK-RTS/Chobby/commit/825ce852274906a8f853056c15598d9bce5329ad

**Comment by sprunk** [comment]
Someone64's last login is 3 years ago so we can't get feedback. Very old engine too. Hopefully BAR people have since run into it.
