### ISSUE TITLE
Consider Giving Krow Sonar + Make Clusterbombs water weapons

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#3398]

**Comment by GoogleFrog** [comment]
Waterweapon cluster bombs would constitute a large nerf against surface units and, due to the spread, variably useful against underwater units.

**Comment by sprunk** [comment]
That too, but even given same depth you might see substantially different results across multiple uses.

**Comment by Anarchid** [comment]
Raven has much more of a case for sonar. It is already equipped with a waterweapon, so currently represents an exception to the rule of "having a waterweapon means having a sonar".

**Comment by sprunk** [comment]
Looks like this specific implementation won't be in.
