### ISSUE TITLE
Use standard spherical distance for Lobster linking to prevent creating space elevator

### ISSUE THREAD

**Issue by Lasica** [ZeroK-RTS/Zero-K#3401]
Another solution could be ignoring the momentum of unit  or making it unable to shoot when airborne.

Watch Zenfur:

http://zero-k.info/Battles/Detail/675947

**Comment by GoogleFrog** [comment]
Spherical is terrible quality of life. Fixed with an alternate method. https://github.com/ZeroK-RTS/Zero-K/commit/ca1d69bad1ec804e0b24e0d2884e419ef7149460
