### ISSUE TITLE
Hotbinds: No ability to remove binding from units/buildings to build.

### ISSUE THREAD

**Issue by perkel666** [ZeroK-RTS/Zero-K#3403]
As thread title says. I like to play wsad for camera but i can't do it because there is no ability in hotbinds to change default keys for unit/building production.

I can't find anywhere QWERT etc. for units production.
There is menu that seems to look like it should change that but i have all none and yet there are still bindings.

**Comment by GoogleFrog** [comment]
What have you tried so far?

**Comment by perkel666** [comment]
> 
> 
> What have you tried so far?

I set up every single binding to none and yet still i have production of units and buildings with qwert etc.
Is there other UI option to change bindings ?

**Comment by GoogleFrog** [comment]
Send the files in LuaUI/Config as well as a screenshot of the configuration menu that you used.

**Comment by perkel666** [comment]
Thanks for input. I figured it out. Turns out that you need to check off "grid" option in hotkeys.
I still need to figure out how to disable grid for buildings but at least units now are not a problem.
