### ISSUE TITLE
FR: Auto exit matchmaker when game starts

### ISSUE THREAD

**Issue by Lasica** [ZeroK-RTS/Zero-K#3404]
When game starts as non spectator the game should quit the matchmaker queue automatically.

**Comment by Licho1** [comment]
Can be done purely server-side

**Comment by sprunk** [comment]
Done lobby-side (so you can still bring back old behavior in options, for example if you're usually just joining battles to watch as a spectator and would still prefer to play MM) https://github.com/ZeroK-RTS/Chobby/commit/8be4ccaa5cca9c018e355028a667412dcd87e13f
