### ISSUE TITLE
Figure out tacnuke fudge math for widget access

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3406]
The task here is to figure out the specific math that could be applied to projectile (position+velocity) that both:
 (1) prevents triangulating the source.
 (2) allows to predict impact location.

The current solution achieves (1) but not (2).
Having no filtering at all achieves (2) but not (1).

**Comment by sprunk** [comment]
Widgets can no longer read projectiles at all.

**Comment by GoogleFrog** [comment]
I think the solution is to write unit AI as if the fudge exists without ever going to the trouble of implementing it.

**Comment by sprunk** [comment]
This wasn't just about unit AI (but yes, dodge AI just makes units dodge the tacnuke). There's also the issue of being able to roughly triangulate the silo. Humans can both see the projectile and hear the sound so have a rough idea where it is.

**Comment by GoogleFrog** [comment]
The rough idea that humans can get is what I'd want the unit AI to approximate.
