### ISSUE TITLE
Engine: Greater control over BuggerOff shape

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3414]
Factories appear to cause BuggerOff in a cone extending from the midpoint of their footprint. This inflexibility is an issue because, to prevent blocking, factory yardmaps can extend far beyond their model. The Hovercraft factory is particularly problematic.

Units are able to block factories when they walk to the back, since this puts them behind the cone. The engine fix for this would be more control over the shape and origin of BuggerOff. There may be better solutions, if not, then a feature ticket should be made on mantis when it is appropriate to make feature tickets.

**Comment by sprunk** [comment]
5049d9a2bf562bbacda2591f6257200d16dc813c
