### ISSUE TITLE
Bomber <> Strike interaction is confusing

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3415]
A strike commander will start out with 3200 health, so 4 bombers will often barely not kill it. All it takes is for the commander to wiggle around a bit and he'll survive with single digit hp. It might be nice to slightly tweak the numbers so it clearly dies to 4 bombers or doesn't.

**Comment by GoogleFrog** [comment]
Commanders have 5 hp/s autoregen. I believe this is the cause of the commander surviving. I think it will consistently survive unless the bombers hit it within one second.

**Comment by DeinFreund** [comment]
Why not give the Commander 3201 hp then to make it clear? It reduce hp to
make it at least a few seconds? Having to micro the bomber timing with sub
second accuracy is asking a bit much.

**Comment by sprunk** [comment]
Do something like `800*N`→`800*N + 50` like Recon already had in the past 9bbb3fbacba11310cb34996712c7385ad237d36f ?

**Comment by GoogleFrog** [comment]
Sure, I just wanted to state the facts as I see them.

**Comment by sprunk** [comment]
8d0e287a723aea85cd57b5576afe7fcf01901911 changes starting healths, nobody starts at `800*N` health anymore.
