### ISSUE TITLE
Remove spray angle from Scorpions "LIGHTNING" weapon

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#3423]
Scorpion main weapon "LIGHTNING" gun has sprayAngle = 700.
This makes it miss at times even against large targets as the Scorpion seems to be aiming at the edge of the enemy collision volume. This causes a pretty large random factor where a target might escape just because the Scorpion missed a few times.
I'd argue that it is a too large random factor that is bad for the game and feel when using Scorpions.

**Comment by Fealthas** [comment]
This sort of randomness adds nothing meaningful to the game, except for maybe frustration.

**Comment by Anarchid** [comment]
All Lightning Guns have this afaik. Therefore this should be a question about whether all lightning guns should not have inaccuracy.

**Comment by GoogleFrog** [comment]
I don't think we need to generalise that far, weapons are allowed to have varying characteristics. I wouldn't say that Knight should be able to always hit Glaives. I'd say that Scorpion shouldn't be so inaccurate that it can't hit the side of a Wasp at max range.

**Comment by Godde** [comment]
Knight and Panther always hits Glaives.

**Comment by Anarchid** [comment]
I've seen them miss. They also miss fairly Darts reliably (which is great because it makes Dart>Blitz more of a thing).

**Comment by Godde** [comment]
You must be living in the past. When I test Blitz vs Darts, Blitz hits like 90% of the time.

**Comment by Anarchid** [comment]
10% dodge rate is fairly noticeable for me.

**Comment by Godde** [comment]
"They also miss moving Darts fairly reliably"
Correction: They also hit moving Darts pretty reliably.

**Comment by sprunk** [comment]
>I'd say that Scorpion shouldn't be so inaccurate that it can't hit the side of a Wasp at max range.

It looks like sprayAngle 700 is already accurate enough not to miss the side of a Wasp at max range:
![image](https://user-images.githubusercontent.com/2573076/80321811-816da900-8820-11ea-88bd-e70416087be2.png)

**Comment by GoogleFrog** [comment]
Well I'd say the spray angle is intentional.
