### ISSUE TITLE
Emissary sometimes fails to reach full speed after firing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3431]

**Comment by GoogleFrog** [comment]
Check whether this affects Crab and Fencer. Some sort of WaitWait or set wanted max speed change may be required in the LUS.

**Comment by Anarchid** [comment]
Definitely affects Crab.

**Comment by GoogleFrog** [comment]
To reproduce
- Spawn an Emissary 
- Spawn an enemy LLT at the East edge of the range of the Emissary
- Order the Emissary to move South.
![image](https://user-images.githubusercontent.com/1318249/54255245-6b187580-45ab-11e9-8c1c-e365f8d60ea8.png)
