### ISSUE TITLE
Make unit outline widget cheaper.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3436]

**Comment by sprunk** [comment]
There are now like 3 versions of the widget (see #3574) and they use a shader instead of redrawing units manually so presumably they are faster. @lhog confirm?

**Comment by lhog** [comment]
Yes, there are three versions. None of them are ideal because of aliasing. If I stumble upon some solution, will update.

**Comment by sprunk** [comment]
Cheap shader seems to have got in. a93c58afb63620b374ec706109d0cf227513dde3
