### ISSUE TITLE
Detriment OKP bug

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3439]
I got a report that Detriment's OKP affects all of its weapons and sometimes leads to it completely disengaging a nearby target. When the Gauss guns don't have other targets I think they should always be firing - they might be able to kill a turret before the missiles impact.

**Comment by DeinFreund** [comment]
Replay: https://drive.google.com/open?id=1mD5aAUWUA8HlxeuDQToIGPKMKregT4du
At the beginning you can see the detriment holding fire against multiple stingers and waiting for the missiles to arrive instead.

**Comment by GoogleFrog** [comment]
I wasn't aware that Detriment had OKP. Looks like it snuck in via a PR and applies to all weapons. The 'doomed' low target priority state should cover the rest.
