### ISSUE TITLE
Improve new Hunter texture

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3441]

**Comment by Anarchid** [comment]
Improve *how*?

**Comment by sprunk** [comment]
Discord logs say:

![image](https://user-images.githubusercontent.com/2573076/53703906-396b1600-3e17-11e9-98fa-ff7db9070f34.png)
>the ship models don't exactly fit together, but it by far fits with them the least

I interpret this as a request to make it less rubber and more metal plating.

**Comment by Anarchid** [comment]
Not a fan of this guesswork.

**Comment by GoogleFrog** [comment]
The texture is just mostly matte grey and lacks precision when it interacts with the geometry. It reminds me of a bodysuit in character.

**Comment by Phytophyte** [comment]
The matte finish was a conscious choice, to try and imitate the sleek visuals of the speedboats the model was based off of (how well I did or did not do notwithstanding; that was the idea).  I can take another attempt at some point to try a plated, metallic approach.

It would help if we could agree on a few points to help guide additional attempts:
- The current texture is 512 x 512.  Should the next texture be bumped up to 1024 x 1024?
- Is the current surface area of team-color good, or should I try to have more or less area be team-colored?
- Which existing ship model would it be best to try and imitate the visual style of?

**Comment by Anarchid** [comment]
Turns out the first pass didn't load the specular model due to lack of a metafile.

https://github.com/ZeroK-RTS/Zero-K/pull/3471

**Comment by sprunk** [comment]
This was about the old catamaran Hunter attempt.
