### ISSUE TITLE
Finish Hunter firing animation

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3443]
Hunter should fire the same torpedo model that sits in its barrel, and the torpedo should disappear and reappear during the sequence.

**Comment by Phytophyte** [comment]
After seeing the Hunter model in action, I wonder if maybe the turret is a bit too complex for such a tiny unit?  The split rails with exposed torpedo is interesting but can be hard to read quickly; a solid barrel could better telegraph the Hunter's aim and reload while in-game.

**Comment by Anarchid** [comment]
https://github.com/ZeroK-RTS/Zero-K/pull/3471
