### ISSUE TITLE
Look into healthbars performance

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3447]
![image](https://user-images.githubusercontent.com/1318249/54071848-7f682400-42c6-11e9-9167-7d3443c62b48.png)

**Comment by Porkch0p** [comment]
Looked into this and have a potential optimization in #3535

**Comment by GoogleFrog** [comment]
Thanks, but that doesn't seem relevant. The default icon distance is 151 and only non-icon units are processed by healthbars.

**Comment by sprunk** [comment]
Duplicate of #3839
