### ISSUE TITLE
Live units being reclaimed under area-reclaim command

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3453]
Seems to have started happening with the 1060 engine. 

Doesn't happen always, haven't tried to properly replicate yet. 

Possibly either beginning or end of the mouse path during area reclaim drag needs to be on the unit to trigger it. I don't think i have seen chained orders (attempts to reclaim more than one unit), so perhaps this is the Godde-click thing misbehaving.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/999239b93e9ebf467c346597234ccb11ab4d8e70
