### ISSUE TITLE
Disappearing build options

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3454]
At least two players (myself and izirayd) experienced build options disappearing from factories in http://zero-k.info/Battles/Detail/694195

Here's izirayd's account of the problem with a very imprecise timing (in russian).
![image](https://user-images.githubusercontent.com/3822768/54124698-c875c080-440b-11e9-89ec-c1e504bc227d.png)

Basically "if i click on the button, the button disappears from the factory".

This starts to happen after resurrection becomes a fairly dominant mode of economy in that game, so possibly it's rez-related.

**Comment by sprunk** [comment]
дубликат #3513, закрываю )
