### ISSUE TITLE
Look at constructor bug

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3466]
https://zero-k.info/Battles/Detail/696271

**Comment by GoogleFrog** [comment]
Also possibly here https://zero-k.info/Battles/Detail/696328

**Comment by sky-orange** [comment]
I've attached my config folder as requested, in case it's a widget thing:
[Config.zip](https://github.com/ZeroK-RTS/Zero-K/files/2975200/Config.zip)

**Comment by sprunk** [comment]
Engine 104.
