### ISSUE TITLE
Performance issue for a player

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3468]
mati#2960 reports a performance issue that has always existed. They get very low framerate and cannot run benchmarker.

Here are there settings: https://github.com/ZeroK-RTS/CrashReports/issues/20731

I had them make some screenshots of this game: https://zero-k.info/Battles/Detail/691590

![image](https://user-images.githubusercontent.com/1318249/54487243-d2099780-48e7-11e9-946a-3d0b6d798524.png)

![image](https://user-images.githubusercontent.com/1318249/54487245-d635b500-48e7-11e9-9510-11f2d4dcc60e.png)

![image](https://user-images.githubusercontent.com/1318249/54487246-d930a580-48e7-11e9-8c6a-8cff365abc43.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/54487383-835cfd00-48e9-11e9-976c-4c785291f66e.png)

**Comment by GoogleFrog** [comment]
I had them run this replay: https://zero-k.info/Battles/Detail/696742

![image](https://user-images.githubusercontent.com/1318249/54487576-c6b86b00-48eb-11e9-9425-65c0b9df5373.png)

![image](https://user-images.githubusercontent.com/1318249/54487581-d33cc380-48eb-11e9-9e9d-2ada8a864f94.png)

![image](https://user-images.githubusercontent.com/1318249/54487585-e059b280-48eb-11e9-800d-fd34e48fae74.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/54487638-65dd6280-48ec-11e9-8286-8d687e6af15a.png)

**Comment by sprunk** [comment]
Four year old ticket from engine 104, probably no longer relevant.
