### ISSUE TITLE
Ctrl+MMB orbit rotation in COFC doesn't work at high zoom-in levels

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#347]
To replicate: find any units, zoom in, hold control, hold mmb, move mouse. 
Try the same without zooming in.

It used to correctly work at all zoom levels somewhere prior to introduction of supcom-style tiltzoom, so possibly related.

**Comment by Orfelius** [comment]
Seems to work properly now. Holding MMB+Ctrl+moving mouse on orbit rotation in COFC seems produce the same result regardless when zoomed in or out.

**Comment by Anarchid** [comment]
https://www.youtube.com/watch?v=q_A1GNx0M9M
