### ISSUE TITLE
Nuke impacting a flying unit at altitude over 20 elmo spawns no effect

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3477]
See https://www.youtube.com/watch?v=6mTYu0A04uk

To replicate, place an enemy Nimbus over the silo and launch. Krows and Athenas will still trigger the CEG because they're low enough that the `ground` bit triggers.

The attempted solution in https://github.com/ZeroK-RTS/Zero-K/pull/3476 does not work.

**Comment by GoogleFrog** [comment]
There is a gadget that relates to nuke explosions, I think it may exist because otherwise the explosion would appear on antinukes.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/exp_no_air_nuke.lua

**Comment by sprunk** [comment]
Removing gadget and doing `air = false, unit = true` to CEG might work.

**Comment by Anarchid** [comment]
The (different) explosion appears on antinuke interception correctly. Though maybe that's the explosion of antinuke's weapon, in which case the correct solution is to:

- Remove antinuke explosion from weapondef
- Remove nuke explosion from weapondef
- Remove nuke explosion logic from CEG
- Have the gadget SpawnCEG a correct explosion

**Comment by GoogleFrog** [comment]
I would rather use the engine, if able.

**Comment by Anarchid** [comment]
There is no CEG qualifier for an effect that occurs when either of these happen:
- Explosion due to the projectile being intercepted by another projectile
- Explosion 200 elmo above ground (the `ground` bit only gives you 20 elmo).

Meanwhile, the gadget already exists - this approach just repurposes it.

**Comment by Anarchid** [comment]
Nevermind i'm stupid:
> Removing gadget and doing air = false, unit = true to CEG might work.

Intercepted by anti? `air`, don't spawn nuke (but spawn antinuke) explosion
Hit ground? `ground`, spawn mushroom
Hit water? `water`, spawn white cap 
Hit unit? `unit`, spawn mushroom

So as long as new funnelweb shields count as `unit` this should work yeah. Otherwise gadget.

**Comment by Anarchid** [comment]
Tested the CEG-driven approach. It fails on Funnelweb shields. Gadget it is.
