### ISSUE TITLE
COFC breaks randomly

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#348]
Two errors Ive found for COFC (91.0, untested in other versions):
[f=0000000] [cawidgets.lua] Error: Error in GamePreload(): [string "LuaUI/Widgets/camera_cofc.lua"]:980: attempt to perform arithmetic on field 'fov' (a nil value)
[f=0000000] [cawidgets.lua] Error: Removed widget: Combo Overhead/Free Camera (experimental)

[f=0026625] [cawidgets.lua] Error: Error in MouseWheel(): [string "LuaUI/Widgets/camera_cofc.lua"]:766: attempt to index local 'cs' (a boolean value)
[f=0026625] [cawidgets.lua] Error: Removed widget: Combo Overhead/Free Camera (experimental)

The second one may be if i had applied enough pressure while scrolling down to cause a middle click + scroll maybe?

**Comment by KingRaptor** [comment]
Can assume fixed? Closing...
