### ISSUE TITLE
Non-moving constructor

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3488]
![image](https://user-images.githubusercontent.com/1318249/54888792-68474a00-4ef4-11e9-908f-a7761c9a446d.png)

This constructor moves towards its build goal for a second, then stops. It may be to do with the move order it had to a similar location a few seconds ago. /skip 360

https://zero-k.info/Battles/Detail/699891

**Comment by sprunk** [comment]
Ancient engine.
