### ISSUE TITLE
Crab does not uncurl when told to move

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3489]
In this game around 10:00 the Crab moves at its slow speed without uncurling. This may already be fixed by https://github.com/ZeroK-RTS/Zero-K/commit/699b30c05bf4ebb20f719058241099d15390095b

https://zero-k.info/Battles/Detail/699891

**Comment by sprunk** [comment]
Assuming fixed by 699b30c05bf4ebb20f719058241099d15390095b

**Comment by GoogleFrog** [comment]
What I really want is reliable start and stop moving events from the engine.
