### ISSUE TITLE
Kodachi became stuck in a nanoframe

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3494]
https://zero-k.info/Battles/Detail/701676

I think the Kodachi moved onto the Solar nanoframe just as the nanoframe was created. This may be related to the nanoframe-growing gadget.

**Comment by sprunk** [comment]
I tried to reproduce but was not creative enough to do so. The replay is from 104 and a lot of pathing changes happened since then so perhaps reopen if there's a more recent occurence.
