### ISSUE TITLE
In-client Replay Browser should have more info

### ISSUE THREAD

**Issue by darloth** [ZeroK-RTS/Zero-K#3496]
Currently the in-client replay browser tells you:
1) the map played
2) the time of the replay
3) the game version.

This set of information is not really all that useful, especially since this replay list isn't even limited to games you played or spectated, but contains other replays you watched later.

I propose it should at LEAST have the players in the game (show first 2-4 sorted highest ranking?  Then the rest as a tooltip) and ideally have a filter toggle for replays you personally played in.  Having the maps show an image tooltip would be nice too, unsure how viable that is in that menu, not totally necessary.

Game length would also be a good one to add.  There may be more.

**Comment by sprunk** [comment]
Moved to the correct repo: https://github.com/ZeroK-RTS/Chobby/issues/677
