### ISSUE TITLE
Reclaim orders are inserted at the end of the queue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3499]
This is probably due to the click+drag tweak widget. The problem is not present with luaUI disable.

Put a Welder near an enemy LLT and tell it to area reclaim. If it has an attack order on the LLT then it will attack the LLT before reclaiming.

**Comment by GoogleFrog** [comment]
It's not "Unit Target Command Helper".

**Comment by sprunk** [comment]
This also affects at least Area Mex and is because a stop command is used to clear the queue in those cases, at which point (before the actual reclaim or areamex order is given) the engine sees an idle unit and gives it an attack command. The attack command seems to go away after 2-3 seconds.
