### ISSUE TITLE
Use LUS to tell gadgets when a unit has fired

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3509]
There is a gadget that uses ProjectileCreated for every projectile, but only uses the unitID parameter. It would be better if the unit_script gadget told the gadget handler directly when a unit fires. Those few remaining COB units could be configured to still use the ProjectileCreated workaround.

See https://github.com/ZeroK-RTS/Zero-K/commit/5fa7e24961ee205e52f0ca6524e6b80fe2859b73

**Comment by sprunk** [comment]
What's the advantage, won't either method mean every single projectile results in a Lua function? If it's about also causing `ProjectileDestroyed` then maybe we should request a `SetWatchProjectileDestroyed` and `SetWatchProjectileCreated` from the engine.

**Comment by sprunk** [comment]
Relevant: https://github.com/spring/spring/commit/79463b01221b1fd8397f4e1e0001af18a39d6ab6

**Comment by GoogleFrog** [comment]
I was more thinking about jumpjets. See https://springrts.com/mantis/view.php?id=6200

**Comment by Anarchid** [comment]
It would be cool if this was also available to widgets (with all the requisite los status checks), e.g. for things like "fire my impaler once at this location".

**Comment by sprunk** [comment]
Fire Once sounds like a command that could exist. I believe there was supposed to be a modifier for a regular attack command to do this (and for manual fire to keep attacking, basically inverting those) but looking at engine code it doesn't seem to be the case.

**Comment by sprunk** [comment]
I made an engine PR https://github.com/spring/spring/pull/447

**Comment by Anarchid** [comment]
Brutal!

**Comment by sprunk** [comment]
Keep in mind ZK uses the meta modifier (aka spacebar) for command insertion so if the engine PR gets through this still needs some sort of UI work to wrap this new old feature.
