### ISSUE TITLE
Build options and command randomly start disappearing in long game

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3513]
There are a lot of these errors:
```
[f=0266414] Warning: [CmdDescrCache::GetPtr] too many unique command-descriptions
```
Infolog: http://paste.springfiles.com/view/8b36cb1d
Replay: http://zero-k.info/Battles/Detail/706197?

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=6167

**Comment by ashdnazg** [comment]
did any of you try watching the replay to see if it reproduces?

**Comment by sprunk** [comment]
Engine fault in stockpile: https://springrts.com/mantis/view.php?id=6201

Explains why it only appears in long-ass FFAs (Screamer has a widget to keep queuing up missiles, and each combination of X ready and Y queued causes a new command description).

**Comment by sprunk** [comment]
spring/spring@d3cc0739089f3fc95c11dd83a2d92f35736515b9

**Comment by Anarchid** [comment]
Seems to be happening still. Unsure if the fix is shipped in this engine version, so not reopening ticket for now. 

http://zero-k.info/Battles/Detail/719428

**Comment by sprunk** [comment]
1156 doesn't yet have the fix.
