### ISSUE TITLE
Units that fire from different locations use the wrong location to check if the projectile is unblocked

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#3516]
A unit such as Thug or Siren that alternately fires from wither gun checks from the last weapon point that fired, then fires from the next weapon point. What this means is the game may fire a projectile even if it's path is obstructed by a friendly unit. Sorry if I don't know what the terminology is in the code.

Video to support. https://www.youtube.com/watch?v=ukTCMtWo3bc

Another case from https://zero-k.info/Battles/Detail/707171
https://imgur.com/a/SzpbHUv
This is basically the frame of when a siren attacks a duck. This is probably what causes all the times I bitch about sirens friendly firing.

**Comment by SteelBlueZK** [comment]
I've done more testing and I now have a list of all the units I could consider.

It seems Rouge and Reaver both are absolutely correct. The cannon it's aiming from is the one that fires. Reaver sometimes can attack ground and hit an alied init head on with it's projectiles, but it seems to work fine. Shogun also seems to be fine, when the front and the back turrets fire, the aimpoints update mid fire-cycle to the next barrel. The middle turret, however, seems to be off by 1 for some reason? it starts it's aimpoint in the 2nd cannon , but it fires 1-2-3 like the others.

Welder and Envoy fire the opposite cannon that they're aiming from, and play the animation for firing from the cannon that it aimed from. This looks a little jarring in game when you pay super close attention, but welder has such a high RoF and Envoy's cannons are so close together that it's fairly unnoticeable that the projectile comes out of the static cannon instead of the animated cannon when playing. These units also rarely friendly fire in a way that you would care too much about.

Hermit, Thug, Minotaur, Ogre, Siren sonic gun, Palidin lightning cannons, and Detriment gauss gunsfire from the cannon opposite the one that's aiming. This means that they can friendly fire allied units and not attack enemies they have a clear shot on. In Detriment's case, it's such a hulking monstrosity I would rather it fire it's gauss guns through allied units no matter the cost just for sheer epic value. Minotaur always fires a 2 round burst, so it matters less. 

Also, Fencer, Recluse, Nimbus, Revenant, Hercules, Tremor and Stinger fire from the wrong barrel, but for varying reasons that does not matter. Units like scalpel, firewalker, and duck which fire both barrels in sync are excluded.

**Comment by SteelBlueZK** [comment]
Further demonstration of friendly firing occurring this time in a real battle https://www.youtube.com/watch?v=-14kH2cPkeg

in battle https://zero-k.info/Battles/Detail/710697

**Comment by SteelBlueZK** [comment]
I mentioned previously that envoy's firing bug does not mater in the scheme of things. I was wrong.

Here's another battle and video of things going wrong. 
https://zero-k.info/Battles/Detail/736720
https://www.youtube.com/watch?v=WGKCVUFqIj8
Note in the video's first 'act' a siren takes like 66% damage from direct hit friendly fires. The AOE damage it takes is understandable, the direct hits are not. The scallop is also remarkably nimble, because most of my shots do not hit anywhere near it.
the second incident has some strange geometry.
The last incident is an example of a siren moving past a stationary ally, and hiting it instead of a far off target.

I also want to mention that I've seen ogres face-smack my commander and other more minor incidents over the last couple months. Felon also suffers from this bug.

**Comment by SteelBlueZK** [comment]
Just an update on this issue, here is a more clear video on the bug. I hope with the documentation I provided anyone can replicate it.

https://streamable.com/xq56y

**Comment by SteelBlueZK** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/241028edab7778035e25ce1f10f6764c44a97a93

https://github.com/ZeroK-RTS/Zero-K/commit/4ef3af73e7394dfd63278b13b0b986374d3f2ce8

https://github.com/ZeroK-RTS/Zero-K/commit/79820ee93455863ede643637aeeaaf62ef13c3a6

**Thug**, **Envoy**, **Ogre**, **Hermit**, **Siren**, and **Detriment** are fixed. Welder and Envoy's cannon effects now match where the projectile was fired from.

**Palidin** is the last egregious case(ligtning cannons), while Recluse, Revenant, Fencer, Nimbus, Hercules, Tremor, Stinger Shogun and some others still have the problem, the animation are fine and a fix won't help at all for a unit like Tremor or stinger, where I have never seen and can never imagine seeing the fix actually affect gameplay in any way over the course of 1000 games.

**Comment by Anarchid** [comment]
Issue sounds closeable then?

**Comment by SteelBlueZK** [comment]
I say once I or someone else fixes paladin it's closable.

**Comment by SteelBlueZK** [comment]
https://github.com/ZeroK-RTS/Zero-K/pull/3695
AFAIK everything else is trivial. closeable.
