### ISSUE TITLE
Investigate Deferred Rendering staying active when Disabled

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K#3531]
I'm testing a fresh install of Zero-K on a potatografx machine at minimum graphics + default settings. This one effect seems to have a super high performance cost, is not affected by chobby graphics settings, and is optional for gameplay purposes. 31 FPS jumps to 43 in-game

![Shader on - 31 FPS](https://i.imgur.com/EKs6GwZ.jpg)
![Shader off - 43 FPS](https://i.imgur.com/rNdaHAY.jpg)

**Comment by Porkch0p** [comment]
Turning off HDR entirely jumps the FPS to about 48.

**Comment by Porkch0p** [comment]
In the same scene without the economy overlay active, FPS jumps from 35 to 70

**Comment by Porkch0p** [comment]
This may actually be a bug related to deferred rendering in Chobby and ZK, because having that setting off in Chobby still allows the widget handling HDR/Bloom to perform calculations in-game. 

Changing the state of Deferred rendering in Chobby doesn't change the state of the Deferred Rendering widget.

**Comment by Porkch0p** [comment]
Should be handled in #3534. The widget is active by default, and was flagging deferred rendering to be enabled at the start of every round. This version defers to chobby without changing graphical settings.

A small bug - if the graphics settings are changed in chobby mid-match, the widget does not enable or disable the Deferred Rendering effects until the next round.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/6061ec17c7a1ab0b099fb4d2ac2c49c7ca359e40
