### ISSUE TITLE
Widow fails to deal damage

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3533]
https://zero-k.info/Battles/Detail/713640
Minotaur takes no damage at 4:10 in the middle of the map

**Comment by terve886** [comment]
http://zero-k.info/Battles/Detail/749365
Around 3:23 my Widow fails to deal any damage against mushroomraider's Ogre.

**Comment by GoogleFrog** [comment]
This still occurs. See the second Widow shot in this game vs. Jack. http://zero-k.info/Battles/Detail/757822

**Comment by GoogleFrog** [comment]
[20190812_061219_Quicksilver 1_104.0.1-1344-g07bdbaf maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/3499633/20190812_061219_Quicksilver.1_104.0.1-1344-g07bdbaf.maintenance.zip)

**Comment by sprunk** [comment]
https://springrts.com/mantis/view.php?id=6280

**Comment by sprunk** [comment]
spring/spring@4139f2e148105ab05780022f729ed5647e4879b6
