### ISSUE TITLE
crash every game since today's update

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3549]
i crash every game since today. https://pastebin.com/pTazX73K

ubuntu 16.04, zerok64 started by shell, steam

**Comment by GoogleFrog** [comment]
Got a replay of the game?

**Comment by mojjj** [comment]
e.g. http://zero-k.info/Battles/Detail/717322

**Comment by mojjj** [comment]
rejoining running game (4 mins into the game). load screen passes, map is viewed. luaui present. then error popup: out of memory.  lua_errmem
https://pastebin.com/K2ek3NnU

**Comment by mojjj** [comment]
NorthChileanG gets the same error when using ubuntu (without steam)

**Comment by mojjj** [comment]
deleted game and redownloaded portable. no more crashes. lost all configs...

**Comment by mojjj** [comment]
fixed by reinstall. http://zero-k.info/Forum/Thread/28297
