### ISSUE TITLE
Units are selected when changing tabs in build menus

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K#3555]
Noticed some undesired behavior with the build menus where it can accidentally select construction units and factories.

Additional cons and factories are being selected (as if it were a shift-click add-to-selection) through the tabs at the top of the integral menu as the tab changes. The commander seems to have an exception to this behavior. Has probably has caused a few "WTF why are my units going there?" moments while playing.

Video can explain it better than I can.
https://www.youtube.com/watch?v=WKF3eBX93LQ

**Comment by GoogleFrog** [comment]
My guess is that the commander immunity is due to the selection rank widget.
