### ISSUE TITLE
Deselect retreating units and exempt them from selection keys

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#356]
When unit retreats, and you give it an order, its instead queued _AFTER_ reetreat area.
This is HIGHLY undesirable and its in fact how it was at first until this got fixed...

Units are not meant to not listen to direct commands _ever_

**Comment by GoogleFrog** [comment]
The rename was confusing and I think retreat works fine as is. Your orders given to retreating units tell them what to do after they finish being repaired.

**Comment by Licho1** [comment]
I think that losing control of unit (until you switch awkward retreat swithc) is very annoying and not very intuitive.

**Comment by sprunk** [comment]
This should now be fairly easy. Add a toggle that automatically sets retreating units to selection rank X.

**Comment by Licho1** [comment]
You are missing the point, its not removed from selection group..
Who keeps selecting units in the battlefield?
I like never do that.. just using autogroup + numbers.

**Comment by GoogleFrog** [comment]
What is a selection group? Do you mean control groups? I don't use control groups or retreat so I don't know how they should interact. I don't think retreat should remove your units from their control group because then they will never be readded. Do you effectively want selection hierarchy to treat retreating units as selection rank 0 and deselect them when retreat begins but otherwise let them be fully controllable? Should giving them an order cancel their retreat?

**Comment by sprunk** [comment]
The way I'd see it (and how I parse Licho):
 * when retreat starts, deselect the unit from current selection
 * be effectively selection rank 0 as long as retreating - preventing reselection
 * keep in ctrl+group - makes sure the unit is easy to access once healed
 * obey direct commands, but don't cancel retreat - keep the retreat at the end of the queue.

**Comment by Licho1** [comment]
More or less what sprunk says...

Basically what I do is to use numbered groups (1-9) for selecting unit.. for example when I have gunship group on 8, I don't want 8 to select retreating units by default.
But I do want option to select them and give them different order, without awkward changing of retreating mode.

**Comment by GoogleFrog** [comment]
This sounds good, I think retreat will be more useful.
