### ISSUE TITLE
grabinput disables itself permanently when the cursor leaves the window.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3560]
I recall this being the result of an engine change. The grab input widget will need to spam grab input when it detects the mouse cursor re-entering the window.

**Comment by sprunk** [comment]
d001cf727ea1e0457d19c255d29a461d65c21332 ?

**Comment by GoogleFrog** [comment]
Yes. I previously fixed this ticket. The fix (and possibly other grabinput behaviour) was broken by some broken logic here: https://github.com/ZeroK-RTS/Zero-K/commit/bb1fcfd9736eb2caa82b90212f5e9e2f0f7f2498#diff-f3df08068b550f02cb9ba3cd4dba1b20
