### ISSUE TITLE
Funnelweb shield nearly invisible on lowest graphics settings

### ISSUE THREAD

**Issue by mvollrath** [ZeroK-RTS/Zero-K#3562]
Was spectating Fields of Isis on a laptop at lowest graphics settings and noticed that I couldn't see a Funnelweb shield at all.  When it came to the edge of the map I noticed it has a barely visible sphere of darkness around it.

To reproduce:
* Set graphics to "lowest" preset in lobby.
* Load Fields of Isis.
* Make funnelweb.

**Comment by danfireman** [comment]
This should be fixed now that https://github.com/ZeroK-RTS/Zero-K/pull/3557 has been merged.

**Comment by sprunk** [comment]
Reopen if still an issue.
