### ISSUE TITLE
Make maneuver less furstrating

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3568]
Idle units set to maneuver can currently chase enemies or move back indefinitely. Units should instead move a fixed distance away and return to their idle position when their target is dead or moves far away. This requires:
- Detection of when a unit becomes idle, and the storage of that location.
- Detection of when a unit is given a player order (so it isn't idle).
- Interception and clamping of all chasing commands and move goals. This includes engine move goals and tactical AI commands.
- Returning to the idle location, probably with a Fight command.

**Comment by Cat-Lady** [comment]
"Detection of when a unit becomes idle, and the storage of that location."

Units that are set on patrol order should also respect engage states - maneuver should have it return to original patrol route on same situations where standing unit returns to "idle" state place.

**Comment by GoogleFrog** [comment]
<ni> is there any way to have units automatically move back to their original position if they move out of place under a maneuver order?  I would like units i place somewhere on the map to stay there except if they get attacked, then they engage and pursute the attacking units under the maneuver movement type but then once the attacker is destroyed or they move too far away they go back to their starting postion where i initially moved them

**Comment by GoogleFrog** [comment]
I guess.
