### ISSUE TITLE
building stack bug

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3571]
queueing buildings to a group of cloakie cons, suddenly i had 6 stinger nanoframes at the same location. stinger refused to force-shoot (dunno if it shot at all as there were no enemies)

video: https://gofile.io/?c=K3Y5au

replay from http://zero-k.info/Battles/Detail/722415

was behind minute 30 at lower part of center beach

**Comment by sprunk** [comment]
spring/spring@7cd04e709d52cec18231cff4413f8ddaefb5adb7
