### ISSUE TITLE
Terraform failure to complete bug

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3593]
http://zero-k.info/Battles/Detail/730715

**Comment by Cat-Lady** [comment]
Happens to me quite a lot in 1 vs 1, so probably not related to ally units/terraforms.

In my case, always seem to happen with "old" terraform orders, that were not completed by the builder that placed it originally, for whatever reason (like, constructor died). Not able to reproduce on a whim, and not sure what causes the terraform to "rot", really.

**Comment by GoogleFrog** [comment]
Link games with exact times @Cat-Lady, as that game is too long.
