### ISSUE TITLE
Highlighting reclaimables in eco overlay doesn't work

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3596]
Since last change (making highlighting reclaimables being possible when having constructors selected and making that the default), it is not possible to bring back old behavior (reclaimables highlighted when eco overlay active) - despite such option being present.

Selecting the "when eco overlay enabled" option makes reclaimables being highlighted all the time (even without eco overlay enabled).

**Comment by Porkch0p** [comment]
Looks like there are some quirks in zero-k around the economy overlay and the 'metal map viewmode'. A number of code paths refer to the map mode being set to 'metal' but in practice it doesn't seem to ever get set that way, and the economy overlay for geothermals has additional conditions to trigger that this widget didn't have added. I would have sworn that it worked correctly before, but this could have slipped through as well.
