### ISSUE TITLE
Next player engine testing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#360]
Track these tickets as engine testing will be worthwhile when they are resolved. They are both common stuck unit bugs.
http://springrts.com/mantis/view.php?id=4605
http://springrts.com/mantis/view.php?id=4606

**Comment by sprunk** [comment]
All of these tickets are now fixed.

**Comment by Anarchid** [comment]
The "engine upgrade" milestone is basically done seeing how ZK seems to be on 98+ to stay.
