### ISSUE TITLE
Fire Once: figure out availability

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3603]
I added Fire Once to all units that can Attack but this has some cost (performance and more importantly command panel clutter). Some units don't really need the command (eg Bandit).

Figure out which units should have the command.

**Comment by GoogleFrog** [comment]
Give it to units with reload time 3s or more. This captures Dagger, which may like the command for diving a mex and running away.

**Comment by GoogleFrog** [comment]
No longer an issue. See https://github.com/ZeroK-RTS/Zero-K/commit/2f827a1e439c532f43659f3bc366d3f8a219a320
