### ISSUE TITLE
Singleplayer Skirmish fails with not enough memory in dev mode

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3607]
Steps to replicate:
- start chobby in dev mode
- singleplayer -> skirmish
- pick Thornford as map 
- keep the default AI
Result: LuaUI fails to load because "not enough memory".

**Comment by Anarchid** [comment]
Launching the same scenario directly = without chobby, results in working ZK.

**Comment by sprunk** [comment]
ZeroK-RTS/Chobby#694

**Comment by Anarchid** [comment]
While this issue was previously closed essentially as what mantis calls FEEDBACK, it can now be closed as RESOLVED, as the problem seems to have gone away.

**Comment by sprunk** [comment]
That's actually bad because maybe it still wastes an unreasonable amount of memory and might silently be affecting people who aren't fluent enough to report it.
