### ISSUE TITLE
[Co-op] Campaing empty maps - lua crashes?

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3622]
Most of the time, when trying to host co-op campaign on my son's machine, we end up in empty map and characteristic yellow "ready" button, that seems to appear when luaui crashed.

Infolog from my son's machine:
https://zerobin.net/?54442fa8c5a10394#etR0JV7q3U0RBS9piNov04KbIo34m7zxovhUZx9SZkA=

Infolog from the machine connecting as client:
https://zerobin.net/?0443fde1f1937ff0#uxlIuRZ96X9cyP6Qrbv5+HkkYveGPOg8ArCZVlMFeXQ=

Curiously, it is not 100% reproducible - sometimes, we managed to fire up the missions just fine. What is more strange, is that when I start the game from my machine, it usually starts fine, with the "failed" state being as rare as the working one in the opposite case.

**Comment by Cat-Lady** [comment]
It turns out it is the elusive issue of old ZK version being loaded for campaign only (multiplayer works fine) when ZK was installed via the ancient .deb file from itch.io (now removed):

`using game: Zero-K v1.7.3.7`

**Comment by sprunk** [comment]
ZeroK-RTS/Zero-K-Infrastructure#2525
