### ISSUE TITLE
Fresh steam install pulls wrong engine version

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3623]
User Barbatboss03 report getting this:

https://media.discordapp.net/attachments/278908415756206080/591666691935567908/unknown.png?width=1275&height=718

...after fresh steam install (linux version). It is worth stressing that I wasn't getting the same error doing fresh steam installs in two machines yesterday and today. Barbatboss03 install attempt is from today, he tried removal and reinstall without success.

**Comment by Cat-Lady** [comment]
#3624 Seems to be a continuation duplicate of this.

**Comment by sprunk** [comment]
duplicate of #3624 (actually the other way around but that one has more info)
