### ISSUE TITLE
Steam linux install gives wrong engine error

### ISSUE THREAD

**Issue by BarbatBoss03** [ZeroK-RTS/Zero-K#3624]
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/3315352/infolog.txt)

**Comment by BarbatBoss03** [comment]
after reinstall and no merge with windows(proton) version i still have the issue
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/3315410/infolog.txt)

**Comment by BarbatBoss03** [comment]
full infolog of the install as of now:
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K/files/3315439/infolog_full.txt)

**Comment by sprunk** [comment]
Stuff said in #3623:

>User Barbatboss03 report getting this:
>https://media.discordapp.net/attachments/278908415756206080/591666691935567908/unknown.png?width=1275&height=718
>...after fresh steam install (linux version). It is worth stressing that I wasn't getting the same error doing fresh steam installs in two machines yesterday and today. Barbatboss03 install attempt is from today, he tried removal and reinstall without success.

**Comment by sprunk** [comment]
Infra issue (or maybe chobby? idk) but I assume it would be hard to get feedback by this point. Also sounds like something that would've gotten readily fixed.
