### ISSUE TITLE
Reclaiming non-scrap is slower than expected

### ISSUE THREAD

**Issue by toveri** [ZeroK-RTS/Zero-K#3626]
When reclaiming live units/buildings, or partially built ones, the speed is only half of the expected. Example, commander reclaiming placed factory uses 10 BP/s but reclaims 5 metal/s. Expected reclaim speed is 10 metal/s, same as with wrecks, rocks etc.

I think this has to do with reclaiming live things only giving 50% of invested metal, but it being implemented so that reclaiming is done at half speed.

**Comment by GoogleFrog** [comment]
Yes, and it is intended. If it takes a constructor 30s to make a structure then it takes 30s to reclaim it.
