### ISSUE TITLE
Bombers cannot reach units on extremely high sheer spikes

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3632]
Apart from being unable to actually bomb the target - and doing weird glitched "phasing" - raven in this replay, actually, shows a weapon reload progress for a moment, despite not dropping bomb (and being, actually, mid air).:
http://www.mediafire.com/file/02sczn86al623uy/20190626_092127_Red_Comet_v1_104.0.1-1251-g69e556f_maintenance.sdfz/file

**Comment by GoogleFrog** [comment]
I don't care much about this particular bug as you will never see this case in practise.
![image](https://user-images.githubusercontent.com/1318249/60161431-f22be980-983a-11e9-8b70-7a4e8af20f8c.png)

Fixing this would require constant terrain height checking and cruiseAlt modification. There is likely some sort of look-ahead in the engine that would need to be subverted. I expect that all other units that are technically bombers would do this.

I did not notice a reload bar and you did not post a time.

**Comment by GoogleFrog** [comment]
Here are some hints:
- This ticket barely covers what you were talking about, as it is about an example that will basically never come up.
- Use /cheat /godmode /spectator /nocost /give to rapidly make units and proper terraform.
- Do not set any modoptions, use NullAI.
- Give positions and times for particular bugs. Provide screenshots of these times.
- Upload files to github directly instead of dodgy external sites. Everything can be zipped.

**Comment by danfireman** [comment]
Is this game an example of the issue? http://zero-k.info/Battles/Detail/738293

South got some Crabes to the mountain on the right next to North's base and the Nimbuses couldn't hit the Crabes.

**Comment by Aquanim** [comment]
That sounds like *an* issue but this issue is specifically about bombers (i.e. planes).

**Comment by GoogleFrog** [comment]
This ticket is about bombers reaching units on extremely high sheer spikes. Tickets have specific topics. Why not open a ticket for the Nimbus issue?

**Comment by Cat-Lady** [comment]
You're wrong, GoogleFrog - I have both seend and experience the bug in countless games involving ravens and crab spikes. It doesn't happen only on super-high 0-cost terraform spikes, it tends to happen every time target is higher than the raven tries to dive (it hits pillar with its nose mid-dive - it is actually easier with real pillars, that are thicker at lower parts), resulting in strange "super speed elevator" to higher attitude, like one presented in the demo, and instant attempt to lower altitude, repeated ad-infinitum.

Actually, it doesn't even require a spike - some featured maps have terrain elevations high enough to be hit by the bug just due to "diving" from lower ground up the steep hill
---

As for the reload bar, it appears just after first attempt to bomb, at initial contact.

**Comment by GoogleFrog** [comment]
The standard is that if you want to make a report about a common situation that affects real games then you should demonstrate the bug in a situation that can occur in real games.

**Comment by GoogleFrog** [comment]
I'm calling this fixed with https://github.com/ZeroK-RTS/Zero-K/commit/9e601fb50f727b69e694da585fdb5ae78362f238.

I have not tested the issue on very high tiny sheer squares. Reopen if a reasonable failure case is found.
