### ISSUE TITLE
Gunships - add defensive strafing?

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3633]
gunships tend to strafe when shooting something. Maybe they should automatically strafe when something tries to attack them, especially, incoming Ravens?

**Comment by GoogleFrog** [comment]
I suspect that all gunships that chase bombers already do this. Test whether the strafing is actually useful.

**Comment by Cat-Lady** [comment]
Closing as part of housecleaning.
