### ISSUE TITLE
Constructors getting move orders on their own during co-op campaing.

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3635]
While playing co-op campaign with someone - and *only* then - commander and constructors tend to, seemingly randomly, get move orders not issues by any player (double, tripple, quadruple... etc. checked). In fact, they are so prevalent in their "random" move order, that it sometimes ends in both players trying to "wrestle" said unit into obedience (like, not going straight to the enemies). They, also, can do things like stopping construction they are performing, to wander around.

It is 100% move order - no attack, no reclaim, visible on UI (with things like shift held = commands visible).
Things attempted to circumvent:

1. Giving "stop" order, by one, or both players. Unit stops, then randomly starts to go to same point again

2. checking widgets - no third party ones active, no non-default ones active, nothing that should give constructors move orders active. Nothing differing from regular gameplay, where issue isn't present for any player participating.

3. changing move and fire state - completely ignored by "the issue".

The issue is hard to reproduce reliably (yet common) - there are matches where it is seemingly a problem, requiring one or two cancel per match, and there are fights where you constantly "wrestle" your commander/other builders (Walchice, the lab defending mission, was worst offender so far, issues were happening 100% times there).
***

I thought about recording match or something like that, but not much comes from that (seemingly) it just looks like unit got regular move order, except that in reality it wasn't coming from player.
***

If there is anything sensible I can do to help debug - I'm willing to spend time doing it for this issue, so pointers welcome.

**Comment by GoogleFrog** [comment]
Here are some things you could do:
- Work on reproducing the bug reliably.
- Check your widgets for those disabled constructor AI widgets.
- Write a widget to check whether the orders are CMD.MOVE or CMD_RAW_MOVE in the replay.
- Both run $VERSION and posion luaUI and luaRules to echo the widget or gadget that issues move orders.
- Make a toggleable debug for the previous thing (like debugecon or debugterra).

**Comment by sprunk** [comment]
Instructions imparted, reopen if there are findings.
