### ISSUE TITLE
Watch this replay and check whether terraform broke

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3637]
http://zero-k.info/Battles/Detail/738142

**Comment by Cat-Lady** [comment]
Terraform wasn't broken in this battle, and no one suggested that it was. Steel_Blue was mentioning different problem in different battle (in a little chaotic digression comment).

The problem, in case of this battle, was that AI sees and tries to nuke leftover, unfinished terra orders by players - even before having "numerical advantage" to see them.

the problem Steel_Blue mentioned was that *after* getting numerical advantage, his Ravens tries to bomb terra orders, when issues area attack order (and were unable too, but kept trying).

**Comment by sprunk** [comment]
>the problem Steel_Blue mentioned was that after getting numerical advantage, his Ravens tries to bomb terra orders, when issues area attack order (and were unable too, but kept trying).

bb0bfed26d7a5818cc5c634cbcdf351bd88f284b

>http://zero-k.info/Battles/Detail/738142

Duplicate of #3627
