### ISSUE TITLE
Southern shallows of (symmetrical) onyx cauldron are now unpassable for constructors, while northern work OK

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3640]
https://zero-k.info/Battles/Detail/739583

Visible very close to start of match - spider constructor on south can't pass shallows (despite manual attempts and repositioning), while northern one passes them no problem. Tested Mason with same results.

**Comment by sprunk** [comment]
>are **now** unpassable

Is this about a change in behaviour (if yes, got a replay of the old behaviour?) or just about the asymmetry?

**Comment by Cat-Lady** [comment]
I definitely wasn't having such problems when playing on this in the past. Unfortunately, I can't pinpoint exact moment of change more precisely than "somewhere during last two months, maybe". When was Onyx Cauldron changed last?

In any case, I think that it wasn't intentional to have southern side handicapped by not being able to reach "island" mexes/pass southern shallows with factories other than cloaks, shieldbots, and amphs.

**Comment by Anarchid** [comment]
Last change to Onyx was 17 months ago. The pass depths were last changed [2 years ago](http://zero-k.info/Forum/Post/175614#175614) to accommodate Reef use.

**Comment by Cat-Lady** [comment]
Closing as part of housecleaning.
