### ISSUE TITLE
Units trying to shoot badger mines hurt allies/waste shoots

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3648]
When some units are under fire by badgers, they try to shoot spotted badger mines. More often that not, it causes harm:

1. Units waste shoots on closest mine "enemy", needing to reload before shooting real opposition (or just wasting another shoot on another mine).

2. Units with AoE or DoT hurt own allied units. Clear example of this is any unit with napalm, that will set parts of own group on fire (happens all the time with commanders having any_weapon+napalm)
---

In theory, it can be remedied by hold fire state - in practice, it hinders battle capability, having to set every target manually.

Ideally, units that have instant reload time and no AoE should be only ones shooting badger mines, and only if there is no other enemy in range. Low hanging fruit version of the fix would be having all units ignore badger mines, until explicitly targeted (kind of like Phoenix doesn't try to bomb air units, unless manually told to do so).

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/issues/2789

I disagree on a strict reload time limit. A Stinger is often able to mitigate some of the damage dealt by Badger bombardment by killing mines.

**Comment by GoogleFrog** [comment]
Duplicate https://github.com/ZeroK-RTS/Zero-K/issues/2789
