### ISSUE TITLE
Crabs on flat ground get into lopp of changing targets.

### ISSUE THREAD

**Issue by Cat-Lady** [ZeroK-RTS/Zero-K#3649]
Take crab engaging ogree + two blitzes. Player sets target to Ogre via "T", or manual attack command.

Expected outcome:
1. Crab shoots the slow-moving Ogre, until it is dead. Blitzes circling around crab have no effect on crab targeting.

Actual outcome:
1. Crab targets the Ogre, but circling blitz momentary gets in between crab and manually targeted Ogre.

2. Instantly, crabs targets closest enemy without "blocked" line of fire - usually, a blitz that is 90+ degrees from intended Ogre target.

3. After portion of a second, interfering blitz moves away from the line between crab and Ogre - crab instantly "forgets" he was changing targets, and tries to target Ogre again.
---

Final outcome:
Crab wiggle his turret impotently, not shooting at all, or shooting once per ~3 regular reload times.

Of course, it is affecting all situations where crab is on same elevation that targets - ogre and blitzes was just an example. Incidentally, crabs on spires are less affected by it, cause they usually have unobstructed view to target.

---

Possible solutions:

1. Preferable - make crabs (and other AoE, heavy hitting, long reload shooters) ignore enemies getting into their line of fire between them and selected target, and "just shoot". Of course, same shouldn't apply to ALLIES getting in between.

2. Less preferable, but probably easier - make crab turrets rotate faster, so the "wiggling" doesn't affect unit performance so much.

**Comment by GoogleFrog** [comment]
Enemies do not block line of fire checks. If you demonstrate that occurring then we have an engine bug report to make.

**Comment by Cat-Lady** [comment]
All right - I am 100% positive it happens, had players witnessing it, etc, so shouldn't be hard to reproduce, I'll take some syntetic battle for it.

**Comment by Cat-Lady** [comment]
Closing as part of housecleaning.
