### ISSUE TITLE
Soft remove the bad terraform structure placement UIs

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3650]
There are four ways to place terraform prior to construction.
- Hold Alt while selecting a structure from the build menu.
- Click and hold LMB without moving the mouse for a second when placing the structure.
- Press Alt+MMB while placing the structure.
- Press B while placing the structure.

The former two UIs invoke a rectangle level terraform UI that has the user set the level of the terrain prior to placement, just like normal terraform. The latter two UIs show a green box over the blueprint that indicates the height of the terraform command. The box can be raised or lowered with Alt+MouseWheelUp/Down and C/V (similar to how Z/X changes horizontal build spacing).

The former two UIs are bad and I tried to remove them before, but there was backlash. My idea now is to make the bad UI optional and disabled by default.

**Comment by Anarchid** [comment]
I find the modifier soup approaches to be unintuitive and undiscoverable.
