### ISSUE TITLE
Broken auto-group

### ISSUE THREAD

**Issue by teodias** [ZeroK-RTS/Zero-K#3652]
http://zero-k.info/Forum/Thread/28587?postID=204873

>If I try to add my Athenas to group Alt+4 it doesn't work.
After building more Athenas I have to add them manually.
This is not how it should work.

Here's `infolog.txt` and LuaUI settings: [logs&settings.zip](https://github.com/ZeroK-RTS/Zero-K/files/3373740/logs.settings.zip)

**Comment by mojjj** [comment]
adjust the title to something meaningful, add a detailed description...

**Comment by GoogleFrog** [comment]
I support this message.
