### ISSUE TITLE
Bug: Sudden accelerating (and exploding) Funnelweb

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3655]
At 19:29 in this battle: http://zero-k.info/Battles/Detail/745563

A Funnelweb is given a command to move a little bit away from the spire it's on.

Shortly before it would reach the base of the spire it seems to lose its grip on the spire and fall (a short distance), crushing the units below it, then accelerate at high speed away from the spire, crashing into a Jugglenaught about 200 elmo away from the spire and exploding.

**Comment by danfireman** [comment]
The Funnel is going sufficiently fast that, if I move the Juggle out of the way, the Funnelweb will hit the valley wall and then go flying about 2000 elmo up into the air...

**Comment by danfireman** [comment]
Moving the little units at the base stops the Funnelweb losing its grip and shooting off.

**Comment by sprunk** [comment]
Engine 104, many pathing changes since then.
