### ISSUE TITLE
(Minor Bug) (GUI) (Campaign) Commander protecting objective is not ticked on mission completion

### ISSUE THREAD

**Issue by psypherium** [ZeroK-RTS/Zero-K#3658]
![Screenshot from 2019-07-19 21-40-04](https://user-images.githubusercontent.com/12213882/61532787-4eff7600-aa6e-11e9-87df-eaa0150faf35.png)

If victory is achieved, the "Protect Your Commander" objective should be ticked.

**Comment by GoogleFrog** [comment]
Failure is always an option. It doesn't make much sense if you won the mission but die 0.1 seconds later to an exploding Singularity Reactor. I think it would be fine to tick objectives when the game ends unless they fail.
