### ISSUE TITLE
Investigate performance of B748292

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3661]
From as early as 13:00 performance was sometimes fine and sometimes not so fine.

http://zero-k.info/Battles/Detail/748292?

**Comment by Licho1** [comment]
Since server was under extreme RAM pressure that result in CPU overload perhaps it affected spring too

**Comment by sprunk** [comment]
Ancient replay and there's reasons to believe server was having issues at the time
