### ISSUE TITLE
(Minor) (GUI) "Lowest Difficulty" stat is incorrect

### ISSUE THREAD

**Issue by psypherium** [ZeroK-RTS/Zero-K#3664]
![Screenshot from 2019-07-22 00-58-42](https://user-images.githubusercontent.com/12213882/61592935-ae02ed80-ac1c-11e9-9f8e-7c3f5a71b8cd.png)

Start a new campaign, complete the first planet on normal difficulty, and the stats will show like in this picture.

**Comment by sprunk** [comment]
Thanks, moved to the campaign lobby repo: ZeroK-RTS/Chobby#713
