### ISSUE TITLE
Lua error chicken queen not recreated correctly

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3666]
https://github.com/ZeroK-RTS/CrashReports/issues/23059

**Comment by sprunk** [comment]
I believe the only case where this can fail is the unit limit (which is a wontfix). I've added some debug info.

**Comment by sprunk** [comment]
I think this can be closed for now. Reopen if the error reappears and the debug info shows there was no unit limit exceeded.

**Comment by sprunk** [comment]
Wasn't wontfix after all!
