### ISSUE TITLE
Gauss does not aim straight and the projectile does not come from its muzzle

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3670]
![image](https://user-images.githubusercontent.com/1318249/61942389-a48ed200-afdc-11e9-8d4b-9d7c247bb35a.png)

**Comment by Anarchid** [comment]
Looks like for some reason the "virtual" set of things resists being `Turn`ed by LUS. Hmmm.

**Comment by GoogleFrog** [comment]
I think you may be unaware of my recent commit, but your message is too dense for me to decipher.

**Comment by Anarchid** [comment]
![image](https://user-images.githubusercontent.com/3822768/63228461-eab20c80-c1fb-11e9-9d64-58f1f01bc36d.png)

**Comment by Anarchid** [comment]
I had to move the proxies to match how the actual geometry looks when it's crooked after unfurling. This caused some height difference that was previously unaccounted for. Either way, the `Empty` pieces used for aiming are now also the ones used for shooting. They are never moved; all unpacking is purely for aesthetics and no longer affects aiming aside from inflicting an unpack delay.
