### ISSUE TITLE
Queue bug

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#3679]
https://drive.google.com/file/d/1ZiAuS7PXR5iNKcGNkqcmbWIFKaEtwhaw/view?usp=sharing

"[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_prevent_lab_hax.lua"]:333: attempt to compare number with nil"

**Comment by sprunk** [comment]
c1f71ed9438c436f3d20f9b3489ca7108d8b1034
