### ISSUE TITLE
AI won't load, skirmish/campaign ends instantly

### ISSUE THREAD

**Issue by Skirmisher** [ZeroK-RTS/Zero-K#3700]
I'm unable to play any skirmish matches or campaign missions besides the first one; the AI is "defeated" immediately upon starting the match. Squinting at the log, I see a message seeming to indicate the AI isn't being specified or loaded properly:
```
Error: [FetchSkirmishAILibrary] unknown skirmish AI   specified
```

Playing Zero-K 1.7.8.3, Spring version 104.0.1-1344, on Fedora 30. Used the "semi-portable" archive from the itch page; however, running the shell script to invoke the provided executable caused a crash, so I've been invoking the Mono binary directly with `mono` instead.

**Comment by GoogleFrog** [comment]
Check what is in Zero-K/AI/Skirmish. I suspect that some files have failed to be deployed. Do links in the lobby open your web browser?

**Comment by Skirmisher** [comment]
The top-level directory has no "AI" folder, but there's one under `engine/linux64/<spring version>`, though I don't know if that's relevant.

I can open the news posts from the lobby home just fine.

**Comment by GoogleFrog** [comment]
Something is stopping the wrapper from creating that directory.

**Comment by Skirmisher** [comment]
Hmm, I don't see what would be doing that; it was installed in my home directory by the itch app with normal permissions, and it clearly set everything else up fine. I'll try running the launcher in a clean directory, though.

**Comment by Skirmisher** [comment]
Redownloaded everything in an empty directory through the launcher, and it seems to have worked correctly this time. A bit odd, but oh well. Sorry for the trouble!
