### ISSUE TITLE
What is the current memory requirments?

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K#3708]
Someone on the FSF member forums just asked me what the game requirements are. I looked them up on the [Itch.io site ](https://zerok.itch.io/zero-k)and it has the storage requirements but not the memory requirements. Do we know the current memory requirements or do I need to do some profiling and use it to update the documentation?

**Comment by sprunk** [comment]
See https://store.steampowered.com/app/334920/ZeroK/

>Minimum: Memory: 4 GB RAM
>Recommended: Memory: 8 GB RAM
