### ISSUE TITLE
Fix Dgun leading

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3714]
One solution is to replace Dgun with LaserCannon. LeadLimit could be investigated. Alternately, the engine could be changed.

http://zero-k.info/Forum/Thread/28722

**Comment by sprunk** [comment]
https://github.com/spring/spring/pull/473

**Comment by sprunk** [comment]
c8d9efd1161f72336f60fbb206a3de423ac9b39b
