### ISSUE TITLE
Archer behaves like it's always on empty charge

### ISSUE THREAD

**Issue by aeonios** [ZeroK-RTS/Zero-K#3723]
I noticed this recently, although I'm not sure when it broke, but archers no longer seem to fire properly. They kind of sputter like they're always out of charge, and dunking them in water doesn't help. Not really sure what's going on with that.

**Comment by Aquanim** [comment]
Working as intended as of [url=http://zero-k.info/Forum/Thread/27500?Search=&User=&grorder=&grdesc=False&grpage=1]version v1.6.12.0[/url].
