### ISSUE TITLE
Emissary and Cerberus try to shoot through terrain

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#3724]
Similar to BB #2675
I don't think these two meaningfully change the terrain though, and their attempts at firing through terrain often causes team damage.

**Comment by aeonios** [comment]
This apparently also applies to penetrator. I've seen a lot of friendly fire issues as well lately, most noticeably with defenders.

**Comment by sprunk** [comment]
fbf61c5c3f6a84511241e57a4dc6680c87e25e6e for Emissary
