### ISSUE TITLE
Rank Icons crash

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#373]
The numbers are raw newxp echoed from Ranks API.

[f=0015147] 0.087636917829514
[f=0015150] 0.091447219252586
[f=0015153] 0.095257520675659
[f=0015156] 0.099067822098732
[f=0015159] 0.099999994039536
[f=0015159] [cawidgets.lua] Error: Error in UnitDestroyed(): [string "LuaUI/Widgets/unit_icons.lua"]:174: attempt to index local 'data' (a nil value)
[f=0015159] [cawidgets.lua] Error: Removed widget: Rank Icons 2
[f=0015159] 0.19999998807907
[f=0015160] 0.099999986588955

**Comment by sprunk** [comment]
Fixed by https://github.com/ZeroK-RTS/Zero-K/commit/4f190ab68bf0fab1f8e6fdf20d57270ced4645f6
