### ISSUE TITLE
Physical damage doesn't keep slow %

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3735]
Apparently damaging a slowed unit will increase its slow %. In the past this seemingly didn't happen (but if I'm reading the code right, it actually used to in the rare case when physical damage kept being inflicted after the slow started decaying), which got changed in 2707bcdd000a6bcceab0ab0b587c35f1c5220c0d.

Presumably this should be changed to keep slow % just like the other status effects but I'd like @GoogleFrog to confirm.

**Comment by GoogleFrog** [comment]
Slow percent has always been intended to change alongside health changes (equivalently, slow damage does not scale with health changes). This is because it is a continuous status effect rather than a boolean one.

**Comment by sprunk** [comment]
Great.
