### ISSUE TITLE
Constructors behaving badly

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3752]
In [this battle](https://zero-k.info/Battles/Detail/788120) at around 2 mins into the game my commander finished building a mex and moved on to start building the next mex, but an order to return to the original mex persisted. It then proceeds to go to the other mex, almost finish building the mex, then attempt to return to the position of the first mex.

Using spec control to insert an extra order to build a solar initially seemed to indicate that the commander had been given orders of "go to first mex, go to second mex, go to first mex, go to second mex":
![image](https://user-images.githubusercontent.com/6192259/67907112-c2854900-fb6e-11e9-93b7-53c54c100ce2.png)

But watch what happens once the com has nearly finished the second mex:
![image](https://user-images.githubusercontent.com/6192259/67907283-4f300700-fb6f-11e9-8c7d-15eff7bbb4a5.png)

This kind of odd behaviour around constructors has been going on since early this year, 1-3 times per game every few games, this is simply a particularly notable recent example.

I have no extra widgets installed beyond the default ones. I think the the only widget I have enabled/disabled that wasn't enabled/disabled by default is the one to place markers on special enemy buildings. OrangeSky also noticed the same issue.

**Comment by GoogleFrog** [comment]
There is nobody called danfireman in that game.

**Comment by GoogleFrog** [comment]
At around 4900 3700 2:00 a mex is completed and its command appears to not be removed. At around 4900 3100 2:35 the commander stops constructing a mex to try to place the mex with the duplicate order. I never see a queued Solar.

**Comment by danfireman** [comment]
> There is nobody called danfireman in that game.

danfireman = dyth68

> I never see a queued Solar.

The extra solar was inserted using `/cheat` when watching the replay in order to try and determine what was going wrong with the orders. I figured I should include some of my own investigation into the weirdness.

**Comment by GoogleFrog** [comment]
Sorry, forgot to close this. I fixed the common case of duplicate orders, a full fix will require a lot of work in the command insert widget.
