### ISSUE TITLE
Lobster tosses units in a different fashion when said unit is touching sloped ground.

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#3757]
https://zero-k.info/Battles/Detail/789787

lobster on flat ground tosses units in such a way that they land translated based on lobster attack vector.  When units are standing on sloped ground, the translation is modified somehow that's consistant, but no longer the lobster attack vector.

Note not shown in replay mid-air units are treated normally as if they were launched from level ground from {x,y,z} location.

Edit: Bonus feature a couple tosses of a mass of thugs at the end of the replay. possibly related, possibly something else.

**Comment by GoogleFrog** [comment]
Perhaps this is related to unstick? I don't recall any gadget that explicitly adds ground normals to impulse.

**Comment by SteelBlueZK** [comment]
Whenever the lobster rework, applying horizontal acceleration over time after launch, occurred, this no longer appears to be an issue.
