### ISSUE TITLE
Conjurer decloak radius

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#3767]
Conjurer can have 2 different decloak radiuses, it's 'normal' state of default, and an increased deecloak radius as of a recent buff alowing for a small area cloak field.

Following these steps, you can glitch a conjurer to have the larget decloak radius when areacloak is not active.

0: default con, cloak activated, and a damage source(allied com HMG/enemy com lazer were my tests)
1: activate areacloaker.
2: cause a decloak via taking damage.
3: turn off the areacloaker before conjurer re-cloaks.
4: when conjurer recloaks, it keeps the larger cloaking radius instead the default 75.

Toggling personal cloak has no effect on cloaking radius. togleing the conjurer's cloak field on makes the situation normal, and turning it off from there properly resets the decloak radius. Conjurer entering another cloak field resets the decloak radius to default 75. toggleing personal cloak has no effect on decloak radius in a bugged state.

**Comment by GoogleFrog** [comment]
That is annoying. Perhaps I should just make it 75 in all situations.

**Comment by GoogleFrog** [comment]
Cannot reproduce.
