### ISSUE TITLE
Phantom will sometimes fail to fire

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3770]
At 18:39 in [this game](http://zero-k.info/Battles/Detail/796708) a Phantom in the top middle controlled by dyth68 is is given an order to attack a Firewalker that is at fairly close range and with a clear LoS. However, it is not until 18:48 that it actually fires, despite not being in cooldown.

This has been an issue in a number of other games, but is most obvious here.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/69000644-f7dbb600-0926-11ea-82f6-e3d1327d3b20.png)

**Comment by GoogleFrog** [comment]
Whenever it was given an attack order it would get a move order from tactical AI, interrupting the attack. Phantom has lots of back-and-forth issues like this. Perhaps there should be a behaviour parameter that causes a unit to only autoskirm if it is reloading or finished reloading recently.
