### ISSUE TITLE
Game crashes on invalid tweakUnits string

### ISSUE THREAD

**Issue by DieGoldeneEnte** [ZeroK-RTS/Zero-K#3773]
When starting a game with a invalid tweakUnits string (like "LOBSTER:!" or similar) the game crashes while loading the lua rules.
I suspect the problem is the use of non base64 character ('!').

To reproduce just start a game with the tweak units setting as above.

**Comment by GoogleFrog** [comment]
A base64 conversion crash could be worth fixing. In general, we're not going to be able to prevent all load crashes that overwriting unitdefs can cause.
