### ISSUE TITLE
Merlin no longer able to fire after game load

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K#3778]
https://steamcommunity.com/app/334920/discussions/1/2659871169526243980/

**Comment by Sharkgamedev** [comment]
I was able to reproduce this - no errors were logged to the console
However, it seems that ALL merlins lose the ability to fire after a load in a singleplayer game - no special cases needed,

Steps to reproduce
1. Start a singleplayer skirmish
2. Use /cheat /give 1 striderarty to spawn a merlin (Tested with naturally building a merlin as well)
3. Save game
4. Load the game and the merlin will no longer be able to fire 

I'll look into it.
