### ISSUE TITLE
Spec control cheat is broken

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3789]
#### User story
As a lonely player I want to try and see how well some unit combinations work against other unit combinations in battle (e.g. 3 Reavers vs 20 Glaives). A year ago I could do this via the spec control cheat.

#### Reproduction steps
1. Start a new skirmish game of null AI vs null AI with yourself as a spec
2. Activate cheats ("/cheat")
3. Open up the cheat GUI
4. Click the "Global spec control" tick boxes
5. Click on the commander that is NOT selected by default ("Null AI (1)" for me)
6. Right click somewhere to order that commander to move.

#### Expected behaviour
The commander clicked on is selected (with the green circle around it and toolbar at the bottom of the screen) and orders can be given to it. Similarly with "Null AI (2)".

#### Actual behaviour
The commander is selected, but no orders given to it are carried out. The "Null AI (2)" commander CAN be given orders.

**Comment by GoogleFrog** [comment]
You need to be a spectator to select the commander.

**Comment by danfireman** [comment]
Ah, wasn't aware of that. Just tried it out and unfortunately the control seems to only work with the initially selected team.

Amended bug report to state that.

**Comment by sprunk** [comment]
3230a638b1c5ff0cd5025e60980a9a3d7eb918dc

**Comment by GoogleFrog** [comment]
Ah I never knew it had parameters. I always just send 'godmode' with my widget.
