### ISSUE TITLE
Add a way to mark allied airpads unusable

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3790]
See title. People sometimes place airpads in places where you wouldn't want your planes to be. Reef especially has an airpad sidearm that doesn't go together well with its combat proximity.

**Comment by sprunk** [comment]
Some UI proposals.

1) Separate global command which just tags airpads (or untags if already tagged). Simple but causes a bit of a clutter since it only is useful when you're a planes player in multi.

2) Use the retreat command to tag. Reduces clutter but the double use might be confusing and is hard to convey.

3) Make planes require the airpad to be in a retreat zone to be eligible for plane landing; make retreat zones containing an airpad ineligible for land units; make static airpads place a retreat zone by default (optionally? can be toggled userside). This unifies the usage to remove the problem from 2, but overwhelms newbs by placing some confusing circles and the ruleset becomes a bit opaque. Reef becomes only really usable when stationary and requires some retreat zone placement micro since retreat zones don't move alongside it, this may well be a good thing.

4) Same as 3 but also make retreat zones unit-targetable to solve Reef. This has the downside of requiring more mana but a commander or a funnel probably make decent retreat zones.

**Comment by Sharkgamedev** [comment]
@sprunk 
I like these ideas, although
Not saying that I think this is a superior option or anything but I disagree about 1 adding clutter, it's just one pretty small button in the top left of the screen, where there's already some free space IIRC,

**Comment by sprunk** [comment]
The reason there's some free space there is because we've been refraining from successively adding one pretty small button at a time.

**Comment by Sharkgamedev** [comment]
Yeah, that's fair.

**Comment by GoogleFrog** [comment]
How about giving air units an 'avoid airpad' command that can be targeted on an airpad to toggle whether all air units avoid a particular airpad. This uses as much of the command API as possible. Airpads that are to be avoided could have an overhead icon when rearming units are selected (and optionally on shift, like the movestate icons).

**Comment by Sharkgamedev** [comment]
Do you mean something that would show up under the orders tab on an air unit or it would be in with the unit retreat at % priority and other controls area? Either way I like the idea a lot.

**Comment by sprunk** [comment]
Orders tab, not the toggleable states.

**Comment by GoogleFrog** [comment]
Under the orders tab, if it is to be targeted command.

**Comment by Sharkgamedev** [comment]
I really like the idea of having it in the orders tab.
