### ISSUE TITLE
claymore force fire

### ISSUE THREAD

**Issue by seedship** [ZeroK-RTS/Zero-K#3795]
Since claymore mines aren't able to move on land, it would be intuitive that if you give a force fire order on land, the claymore will move to where you say to attack and drop its bomb there, like a bomber would.

However, instead it just stays in its current position and does nothing... I think this doesn't make any sense

http://zero-k.info/Forum/Thread/29734

**Comment by seedship** [comment]
I guess this is closed by the new update

**Comment by sprunk** [comment]
7807360ea3f2922334649bf9006cf01c2d053729 probably
