### ISSUE TITLE
Crab when continuously damaged by hermits fails to fire

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#3804]
Today while playing a round of zero-k, I had a crab engage a dozen or so hermits. About half way through the engagement, the hermits started "hitlocking" the crab -- that is to say apparently they deal enough impulse (theoretically) to dislodge crab slightly and cause it to "redeploy" repeatedly.

The battle in question can be found here: http://zero-k.info/Battles/Detail/839559 with the engagement in question happening at around 11:00-13:00 on the hill in the center east part of the map.

**Comment by Arch-Shaman** [comment]
Replicated in local replay (server didnt save)

[20200222_052233_Snowbound v1_104.0.1-1435-g79d77ca maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/4239351/20200222_052233_Snowbound.v1_104.0.1-1435-g79d77ca.maintenance.zip)

**Comment by GoogleFrog** [comment]
It looks like two things came together:
 - For some reason, Crab's script makes it unable to fire while changing state.
 - Spring spams StopMoving script callins at stationary units that are taking damage (probably due to impulse).
