### ISSUE TITLE
Tactical AI: units dont avoid chicken Leaper

### ISSUE THREAD

**Issue by Lasica** [ZeroK-RTS/Zero-K#3820]
Chicken Leaper one shots everything into oblivion and nothing tries to run from it.

Reduce impulse damage to around 1500 while we're at it.

**Comment by sprunk** [comment]
d3832806f32b014600177623fb1bc24b98cf4eee for avoiding Leaper.

The impulse is by design (it mostly makes the kick more hilarious, which is totally a sufficient reason to keep it).
