### ISSUE TITLE
Implement widgetside XP

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3823]
This way:
 - only the people who think XP is any useful pay the perf cost
 - LoS haxes are automatically taken care of (currently for example in a 3-way FFA if player A fights with player B, player C can tell because A's units have some XP)

**Comment by GoogleFrog** [comment]
Unless XP is enabled by default, then essentially everyone pays the performance cost.

**Comment by Licho1** [comment]
I disagree I think we should reinstate XP effect. RoF was fine
