### ISSUE TITLE
Scorcher/mex bug report

### ISSUE THREAD

**Issue by cellf11** [ZeroK-RTS/Zero-K#3824]
the situation happened around 10min/35~39% progress bar I think,where I sent the units unprotected area SW/down-left.

[20200310_031419_TitanDuel 2_104.0.1-1435-g79d77ca maintenance.zip](https://github.com/ZeroK-RTS/Zero-K/files/4310807/20200310_031419_TitanDuel.2_104.0.1-1435-g79d77ca.maintenance.zip)

**Comment by GoogleFrog** [comment]
What is the bug?

**Comment by cellf11** [comment]
I killed conjurer they've just built a mex there,mex animation stopped before it fully open so left half buried,unable to target for scorchers it seemed.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/76485715-606c1700-6471-11ea-87c0-c58d24fca4a5.png)

![image](https://user-images.githubusercontent.com/1318249/76485763-7da0e580-6471-11ea-9ef5-d85be3dc48d3.png)

Circuit manages to build a mex on the same spot three times. Two of them are complete, and when one dies it creates a blocking wreck. I have no idea about the AI interface and it is likely impossible to do this bug the same way without an AI.

**Comment by sprunk** [comment]
https://zero-k.info/Battles/Detail/870595
"last unit that needed to be killed was an enemy mex inside jaspers mex, in the north"

**Comment by sprunk** [comment]
spring/spring@4a97df4f98c3d9afcd9b21d4062e91d96b3a4da8
