### ISSUE TITLE
Make Hunter torpedo bigger

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3833]
I sometimes find sea battles annoying because it is hard to see what is shooting at what. Hunter torpedoes are essentially invisible so it looks like units randomly die. It is hard to judge the effectiveness of your units while this is the case.

Maybe Urchin torpedo could be a bit larger too.

**Comment by Anarchid** [comment]
Seawolf missile is quite visible - i think a CEG replacement would do more here than model scaling.

**Comment by sprunk** [comment]
94b80a66ad60d0a759a84ae399566075f3d0c3db et al, can be closed?
