### ISSUE TITLE
Tacticool ui preset proposal 

### ISSUE THREAD

**Issue by TRONAS** [ZeroK-RTS/Zero-K#3848]
![screen00010](https://user-images.githubusercontent.com/62997926/78180510-28019c80-7463-11ea-8999-7f826e167ba5.png)
![screen00013](https://user-images.githubusercontent.com/62997926/78180532-3485f500-7463-11ea-8978-0d0c5fe497d0.png)
![screen00014](https://user-images.githubusercontent.com/62997926/78180544-3b146c80-7463-11ea-9d1b-f691ffe142ab.png)
![screen00001](https://user-images.githubusercontent.com/62997926/78180576-46679800-7463-11ea-9c25-9000e9ac35f6.png)
![screen00002](https://user-images.githubusercontent.com/62997926/78180615-52ebf080-7463-11ea-9edc-05e1d0bb081f.png)
![screen00004](https://user-images.githubusercontent.com/62997926/78180645-5c755880-7463-11ea-8fb1-92396f671706.png)
![screen00005](https://user-images.githubusercontent.com/62997926/78180687-68611a80-7463-11ea-8895-73df09dd3aaf.png)
![screen00006](https://user-images.githubusercontent.com/62997926/78180715-74e57300-7463-11ea-95e6-fb6aa60b5287.png)

**Comment by GoogleFrog** [comment]
What is the technical side of the proposal? Couldn't this exist as a zk_data and zk_order file that is attached to page on the wiki explaining the UI? This would be akin to the various deep-settings overhauls I've seen for starcraft 2.

If this is to be included in the game in any sense then you're proposing an advanced version of the 'HUD Presets' widget. I would put this UI outside simple settings and a 'reset to defaults' button would need to exist in the same submenu,

**Comment by sprunk** [comment]
Why bundle "camera shakes disabled" and "autogroup set to 1-raiders etc" in the same preset, what do they have in common?

**Comment by GoogleFrog** [comment]
It looks like a settings overhaul preset. I think the intent is that it be a 'hardcore default' in the sense that advanced players can try out a bundle of settings created by even more advanced players that achieve a particular goal.

My interpretation is why I am doubtful as to whether this should be in the game at all. In other games things like this usually exist on wiki pages. Here are some examples of super advanced players developing bundled customisation:
 - https://wiki.step-project.com/Main_Page
 - https://drive.google.com/drive/folders/1ui2HNwaUa4FkHzRwATgXHNVEpolLNOzA
 - https://tl.net/forum/sc2-strategy/404476-fleet-keys-refined-hotkey-systems

I think making and applying a bundle for ZK is quite easy already. The installation instructions for this bundle would be to replace your zk_data and zk_order with the files provided in the bundle. Unless there are unseen technical difficulties with creating the bundle (perhaps some local user data is in zk_data) then I don't know if this ticket requires anything.

**Comment by TRONAS** [comment]
So this kind of maxing out of the ui should live on wiki in the form of a guide. gatcho

The transparent panels, disposition of them and minimap callapsability could still be made into a preset. 
It would keep things similar to default but improve visibility by a lot.
like this;
![screen00015](https://user-images.githubusercontent.com/62997926/78220673-4054d400-74c2-11ea-8392-4b558cb1d0b3.png)
