### ISSUE TITLE
Game failed to start on twin lakes park

### ISSUE THREAD

**Issue by ghost** [ZeroK-RTS/Zero-K#3860]
https://hastebin.com/qedijuloxe.md

![screen00034](https://user-images.githubusercontent.com/1368663/78461260-a8ebae80-7684-11ea-8e51-45a4588a971d.png)

No replay generated. Boxes appeared on map but spawns could be put anywhere. All commanders failed to appear so game was exited.

**Comment by sprunk** [comment]
OOM

**Comment by GoogleFrog** [comment]
Attach your replay.

**Comment by The-Yak** [comment]
[20200404_142124_Twin Lakes Park 1_104.0.1-1435-g79d77ca maintenance.sdfz.zip](https://github.com/ZeroK-RTS/Zero-K/files/4432774/20200404_142124_Twin.Lakes.Park.1_104.0.1-1435-g79d77ca.maintenance.sdfz.zip)

**Comment by sprunk** [comment]
Old engine and the hastebin is dead, I don't think much value can be got here.
