### ISSUE TITLE
Crabs uncurl when attacked

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3861]
https://zero-k.info/Battles/Detail/864724
At 11:30 in this battle a crab in the top left is hit by Ogre shots and repeatedly uncurls (and is eventually given an instruction to retreat, which leads to a final uncurling and death).

**Comment by GoogleFrog** [comment]
That is not a replay link.

**Comment by danfireman** [comment]
Apologies for the fail :(

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/commit/2bdc8d0e511b0347cbb83d4fab9f7f2097e029ca

**Comment by Arch-Shaman** [comment]
Is this still an issue?

**Comment by GoogleFrog** [comment]
The issue is now that it has been hacked around. The hack probably fails sometimes or causes other issues.
