### ISSUE TITLE
Strike commander rotates around its feet in midair.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3872]
I fixed this for most units, but dae is a pain. The change is to move the root piece to his centre of mass without changing anything else.

![image](https://user-images.githubusercontent.com/1318249/78963420-cca66d00-7b3a-11ea-8a12-d90eed3182f2.png)

See: https://github.com/ZeroK-RTS/Zero-K/commit/144fe99dddb9e00ed2bed356700237710dc4dceb

**Comment by Anarchid** [comment]
> The chance is to move the root piece to his centre of mass without changing anything else.

![image](https://user-images.githubusercontent.com/3822768/78991858-979e1880-7b42-11ea-95a3-c3a8b0c1ae5a.png)

Apparently that's not the whole story.

**Comment by Anarchid** [comment]
![image](https://user-images.githubusercontent.com/3822768/78993202-dbdee800-7b45-11ea-8f0d-a19ac17b962e.png)

**Comment by sprunk** [comment]
Change the root to be in the middle of the model but also move every child piece of the root (and thus indirectly everything else) upwards?

**Comment by Anarchid** [comment]
> Change the root to be in the middle of the model but also move every child piece of the root (and thus indirectly everything else) upwards?

Then the root, and thus the rotation pivot, is still at the base relative to the other pieces. Except that instead of swimming in the ground as with the "move origin to middle" approach, you get flying through the air. And if you snap that to the ground you get the current situation.

The current situation seems to also affect all of the commander s3o models. At least this is what i see when i launch them with a lobster like in the issue description.

**Comment by GoogleFrog** [comment]
> Apparently that's not the whole story.

It's the whole story for s3o. A root piece at (0,32,0) is 32 elmos above the ground and is rotated around in midair. Idk how dae works and not supporting such a thing would be quite the limitation.

Your picture of the Engineer Commander shows nothing to me that I don't already know. The ticket is on rotating around non-centre of mass while flying. The commander's centre of mass could reasonably be just above ground level and you don't have the default selection widget, so it is impossible to tell if it is configured incorrectly.

**Comment by GoogleFrog** [comment]
> The current situation seems to also affect all of the commander s3o models. At least this is what i see when i launch them with a lobster like in the issue description.

As I wrote in my simultaneously written comment, I disagree. The ticket reads "Strike commander rotates around its feet in midair." and that is the issue. If the pictures that I have provided are confusing the matter then just ignore them. Run a test yourself to see what units rotate around when flying.

**Comment by Anarchid** [comment]
I think i see what you mean. But it's [url=https://vimeo.com/406199885]surprisingly difficult[/url] to observe.

**Comment by Anarchid** [comment]
Apparently the root issue is that assimp generates its root piece at `0,0,0`, called Scene. 
Fortunately, the metafile can offset that.
