### ISSUE TITLE
GS fac: ugly-ass nanopiece

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3878]
GS fac has this floating, untextured, low-poly-plague-doctor-shaped thing as a nanopiece. 
![image](https://user-images.githubusercontent.com/2573076/79057860-56068e00-7c66-11ea-8d5b-2b4342fec9ad.png)
Ideally it would be removed but there would need to be some new nanopiece. Possibly the four pillars? But they don't look like nanopieces.

**Comment by GoogleFrog** [comment]
It will have to be the tops of the pillars.

**Comment by Anarchid** [comment]
GS fac is pretty much ugly everything
