### ISSUE TITLE
Tilde in front of spectator's name, all chat goes to debug console

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#3887]
See https://github.com/ZeroK-RTS/CrashReports/issues/29878

I saw this happen to somebody else a week or so ago but thought they had just chosen an invalid name.

Possibly related to joining a battle room *just* before the game starts.

**Comment by sprunk** [comment]
Tilde means that somehow the user skipped getting verified by the server as a battle participant (joining a battleroom just in time sounds like a plausible way to achieve this). ZK dedi is configured such that you can connect with any name but you get a tilde if you aren't verified (engine feature). Dedi should probably get `AllowSpectatorJoin=0` in its config.

**Comment by sprunk** [comment]
This is effectively a duplicate of ZeroK-RTS/Zero-K-Infrastructure#789
