### ISSUE TITLE
Lockup and hang in big teams game 

### ISSUE THREAD

**Issue by ghost** [ZeroK-RTS/Zero-K#3890]
...after user polska_plPL joins

https://paste.springfiles.com/view/075b607e

http://zero-k.info/Battles/Detail/877747?

**Comment by The-Yak** [comment]
Another one: https://paste.springfiles.com/view/68ab1f2e

**Comment by sprunk** [comment]
The other one doesn't seem to have anyone joining at that frame so hopefully it was just a coincidence.

**Comment by GoogleFrog** [comment]
Try luarules disable on the frame before the lockup.

**Comment by sprunk** [comment]
Ancient engine.
