### ISSUE TITLE
Cloakers defaulting to high priority causes permanent E-stall

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#3899]
When a large number of cloakers (area cloakers, phantoms, etc) are present and E production is destroyed, players will find themselves unable to build for no reason they understand.

This behaviour looks like a bug to these players (at least 8 separate people have told me they thought this was a bug). And not just for new players, even experienced ones will not understand why if they don't speak English and thus had no one to tell them: e.g. rewdrfe2 at 35 minutes onwards in this battle: https://zero-k.info/Battles/Detail/880372

Proposed solution: The cloaks of phantoms, Iris and similar should default to medium priority

**Comment by GoogleFrog** [comment]
Sure.

**Comment by GoogleFrog** [comment]
No PR?

**Comment by GoogleFrog** [comment]
You know, personal cloaking doesn't even have a misc priority. PR that.

**Comment by GoogleFrog** [comment]
Technically players can build while cloaking is draining energy. Players could not build while cloakers were at high priority and taking all the energy. I will call this fixed.

**Comment by danfireman** [comment]
Ah, sorry about now replying.

I don't get github notifications so I only see replies when I happen to decide to look at the issues list or PRs.
