### ISSUE TITLE
Bind Menu button to escape by default.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#390]
Current default preset makes F10 as a menu button while escape has been used as an menu button for decades now. This set up is very counter-intuitive and confuses players (me included) as it closes the integral bar.

**Comment by Orfelius** [comment]
I kinda see the reason behind it now (having played SC 2 a little).
But if the cancelation feature may stay imo it should not make the menu element (I dont know how the widget operating it is called) close and open since it will flicker every time you want to cancel an order.

**Comment by sprunk** [comment]
This is mostly a design decision, consensus required.

**Comment by GoogleFrog** [comment]
I went ahead and did this with no memory of this ticket. Escape and F10 now do exactly the same thing: toggle the menu. There is no bar hiding.
