### ISSUE TITLE
Double-Click attack-move

### ISSUE THREAD

**Issue by danylo-dubinin** [ZeroK-RTS/Zero-K#3901]
https://github.com/ZeroK-RTS/Zero-K/blob/05ef2fb52234eea43515e00dbf323578c75767c6/LuaUI/Widgets/cmd_doubleclick_attackmove.lua#L38

I found double click tolerance very high, so just disabled the widget and replaced it with the same one but with `* 0.1` as a quick hack. 

And then I investigated a bit and found that the [`DoubleClickTime` value is in milliseconds](https://springrts.com/wiki/Springsettings.cfg#DoubleClickTime) and the function which is used to compare times in the code ([`Spring.DiffTimers`](https://springrts.com/wiki/Lua_UnsyncedRead)) returns seconds, so I think there is a bug - multiplication has to be division?

**Comment by sprunk** [comment]
`toleranceTime` has to be in seconds (since it's compared to `DiffTimers` without further scaling).

So to get, for example, a value of 0.3 (seconds) from the equivalent value of 300 (ms) returned by `GetConfigInt` you'll have to multiply the 300 by 0.001 which seems to be what's happening.

**Comment by danylo-dubinin** [comment]
Oh, indeed

**Comment by sprunk** [comment]
You can just edit the `DoubleClickTime` springsettings entry to `30` if you want it 10x smaller.

**Comment by danylo-dubinin** [comment]
Yeah, found it. Thanks for advise
