### ISSUE TITLE
Consider not slowing transports based on cargo mass

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#3908]
Transports are currently most powerful when empty or when carrying light bombs. Removing the system that reduces their speed based on the mass of their cargo would be a relative nerf to these situations. Here is what I am considering:
 - Make transports a bit slower than they are currently, but make cargo not reduce speed. I think it is fine if Reaver/Scallop drops are faster. Herc could be quite slow as we have to out for the transport speed of Detriment.
 - Make empty Charon a bit faster than it is currently, without changing Herc too much. This buffs logistics and makes a slow full-Herc less annoying to deal with. Ideally both transports would receive the same proportional speed boost when empty compared to full.

**Comment by Licho1** [comment]
I would agree with this. Didn't like the mass based speed.

There could also be a temp speed boost possibly as part of eject (the eject could accelerate transport in given direction before ejecting unit).

**Comment by Anarchid** [comment]
Ironically enough, the mass-based speed nerf happened because Vindicator was used to as a way to nearly unstoppably deliver **very heavy** bombs instead - e.g. suicide drops into dense enemy base on Azure FFA.

**Comment by Sgathec** [comment]
Could the influence of mass be weakened instead of removed entirely?

**Comment by GoogleFrog** [comment]
Technically any equation is possible. The closer you move to giving each unit type a uniquely calculated transport speed the more arbitrary the system becomes.

This is what happens currently:
```			local effectiveMass = mass[tudid] + (Spring.GetUnitRulesParam(unitID, "massOverride") or mass[unitDefID])
			local speedFactor = math.min(1, 2 * mass[tudid]/(effectiveMass))```

**Comment by Anarchid** [comment]
Herc couod have Nimbus speed in mass-free rule. This is both faster than its current speed of "almost slower than walking", but not fast enough for "unstoppable delivery of big bomb"

**Comment by sprunk** [comment]
b671f60d24b14154504b272db477d736a21788be
