### ISSUE TITLE
Starlight self-burial

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#3916]
A Starlight whose beam is leaving the folded position temporarily terraforms itself down. This can be lethal when it is, for example, built on lava.

Here are some observations as to the cause:

- The beam **is** blocked by the structure's colvol, but that doesn't prevent it from very slowly sliding downwards.

- Pointing the beam just outside the structure's footprint, or on the footprint while missing colvol, causes a faster, constant, downwards movement.

- Pointing the beam slightly more outside causes the structure to instead climb upwards.

- If the beam is targeted with an attack ground command on an area of footprint covered by colvol, the charged mahlazor Crater Puncher burst moves the structure down even despite being blocked by terraform.

I suspect that Groove Cutter just has too much AoE and its cratering reaches the center of the unit. A possible workaround that does not require terra snapping to be polled that frequently is to replace it with terraintype modifications - have structures plop a square of infinite hardness below them, and remove it when they die.

**Comment by sprunk** [comment]
Possibly the periodic check that brings structures bacc to original height should happen more aggressively for Starlight?

**Comment by Anarchid** [comment]
Aggressive polling just for SL is one solution. I do think the infinihard terraintype approach could solve it for everything though, while also possibly saving perf by removing the need to poll entirely.

**Comment by sprunk** [comment]
One table per starlight is fine.

**Comment by GoogleFrog** [comment]
Making terrain impassible could screw with the pathfinder. Use 138?

**Comment by GoogleFrog** [comment]
Hardness modification for all terrain under structures could be a thing to put in the terraform gadget. If the pathfinder is screwed with in a good way then it could even be made impassible.

**Comment by sprunk** [comment]
Units can't path under Starlight anyway so that shouldn't be a worry. On the other hand applying it universally doesn't seem possible since some facs' midpoints need to be pathable (eg. hoverfac).

**Comment by Anarchid** [comment]
`typemap_options.lua` could parse the mapinfo of the currently loaded map, check the used terrainType ID's, and generate separate "passable, indestructible" and "impassable" terraintypes, then export their ID's.

This retains any extant typedefs and typemaps as much as we want. Meanwhile, indestructible yet passable avoids screwing with pathfinder and yardmaps.

**Comment by GoogleFrog** [comment]
> Units can't path under Starlight anyway so that shouldn't be a worry.

Assuming that structures and terrain cause exactly the same type of inability to path is very dangerous.

Obviously a universal application would not include factories. They have their own hax. Perhaps they should have impassible terrain under their impassible bits, or just left as they are.

**Comment by GoogleFrog** [comment]
I just thought of a blocker. Map hardness is probably readable outside LOS.At a minimum this would require Starlight to do the change only when it turns on (as it becomes globally scouted).

**Comment by Anarchid** [comment]
> Map hardness is probably readable outside LOS.At a minimum this would require Starlight to do the change only when it turns on (as it becomes globally scouted).

In that case it seems more practical to just have Starlight check for deformation more frequently. 

It already essentially "polls" each frame whether to EmitSFX the beam or not.

**Comment by danfireman** [comment]
![image](https://user-images.githubusercontent.com/6192259/167949083-e8e9a1a8-513f-467f-9bb4-4f5bd91ed4fa.png)
The starlight burying has gotten a whole lot worse

**Comment by GoogleFrog** [comment]
I am doubtful that the contents of this ticket are still relevant. Open an updated ticket so that we don't take two year old stuff as facts.
