### ISSUE TITLE
Lots of desync in this teams all welcome game

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K#3935]
http://zero-k.info/Battles/Detail/895561?

borblezorb41 constantly desyncs, and other players occasionally desync.

**Comment by The-Yak** [comment]
Another http://zero-k.info/Battles/Detail/895571?

**Comment by DeinFreund** [comment]
I recently enabled 64 bit engines, are they using them? Should be in infolog.

**Comment by GoogleFrog** [comment]
Last steam build was a month ago, so the 64 engine change is not live yet.

> borblezorb41 constantly desyncs, and other players occasionally desync.

Desync is only detected pairwise so occasional desync by other players is likely just pairwise desync with borblezorb41. Have him validate files.

**Comment by GoogleFrog** [comment]
Such consistent and early desyncs indicate that his install is broken.

**Comment by sprunk** [comment]
No recent complaints so assuming fixed.
