### ISSUE TITLE
Playerlists: show dead people consistently

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#3938]
In the picture below, playerlist on the right says everybody is \<Dead\> but the one the left differs between dead and abandoned. Playerlists would ideally show people consistently. https://zero-k.info/Battles/Detail/896119
![image](https://user-images.githubusercontent.com/2573076/82441536-5df3f200-9a9e-11ea-9658-186abbe99e86.png)

**Comment by GoogleFrog** [comment]
The playerlist on the left looks very non-default, it doesn't even seem to use chili. If players want to install custom widgets that generate conflicting playerlists then that is their problem. The playerlist on the right is the default and declared the teams dead, which seems correct to me, so I don't see a problem here.

**Comment by sprunk** [comment]
I agree that we don't care about custom widgets but isn't the one on the left https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_advplayerslist.lua?
