### ISSUE TITLE
Remove Economy Panel Warning

### ISSUE THREAD

**Issue by dahn-zk** [ZeroK-RTS/Zero-K#3940]
For experienced players there should be an option to remove Economy Panel Warning, imo:
![eco-warning](https://user-images.githubusercontent.com/20540273/82563627-1180e300-9b80-11ea-8478-2ce09de15f40.png)
It is an unnecessy UI space waste after a few hours/days/week of plays, after a person already understands the economy system of the game.

**Comment by sprunk** [comment]
Build/use more constructors to ~spend your metal~ remove the warning.

**Comment by dahn-zk** [comment]
@sprunk, sorry, i cant tell yet if u r serious or joking.

**Comment by sprunk** [comment]
A checkbox somewhere in the options that disables the warning is probably fine, but if somebody sees the popup often enough to be annoyed by it then that person is the popup's target audience, so I am not sure. Possibly it could be made not to appear by default on some excessing conditions that are "normal" though, for example on speedmetal or high metalmult modoption.

**Comment by dahn-zk** [comment]
A small clarification: I'm willing to contribute with adding such option, just want to come to a consensus with maintainers ZK org members first.

---

> if somebody sees the popup often enough to be annoyed by it then that person is the popup's target audience, so I am not sure. Possibly it could be made not to appear by default on some excessing conditions that are "normal" though, for example on speedmetal or high metalmult modoption.

By disabling it for speedmetal and high metalmult:
- What's _high_ metalmult? 
- How to differentiate between speedmetal and non-speedmetal map? What if someone wants to make a map with 20 regular mex spots in each starting position, would it be considered a speedmetal map?
- What about mod maps where you don't necessarily need to use metal?
- What if I simply want a fun game with friends where nanoflow-able units except commanders are disallowed?

Popup's audience: I'm seeing it often enough to be annoyed and willing to make an issue and write this. :) But I'm far from being it's audience. Just a few of uncountable reasons:
- Playing big team games, loosing a factory or a commander to a scythe raid. Firstly, a person has fucked up and might be quite upset at it, secondly, a game yells at him/her telling what to do which is sometimes not even correct if he/she lost all build power. In such case the notification would also need to suggest asking for a constructor from a teammate.
- Being a cheese player, going for a risky comm push in 1v1 or small teams and loosing it. Again this isn't a time for having my UI showing me gameplay tips.
- Any other shit which happens in game. You might simply lose your wind farm to a raid start estall and excess metal. You already know what to do, do you want your UI to waste some space for you because it can? Not listing anything that can happen to a player at the moment and in future we might even have new scenarios in which the reason for excess is not directly lack of buildpower or its utilization.
- A pedant person who values clean UI. It doesn't look good to me and I'm sure I can find people who think the same. Even when some website ar application tries to guide me through UI interactively with option to skip I feel stupid and disrespected as a user, because I might know how shit works from some other media or the language of that UI is similar to some other application (or game).

**Comment by GoogleFrog** [comment]
I prefer a tickbox that almost nobody will touch to a more complex change in behaviour that hides it by default in some cases. The latter could be better in the ideal scenario, but I expect it to silently break in practise.

**Comment by thomas11111111** [comment]
you can disable it by moving you energy stall warning slider all the way down and metal warning all the way up

**Comment by sprunk** [comment]
I am unsure if setting them to 100 (or 0) % completely disables the warning (since there is the hidden extra storage than can put you above the nominal cap) but making those two values exceptional cases sounds better than a checkbox.

**Comment by sprunk** [comment]
![image](https://user-images.githubusercontent.com/2573076/84720258-de165600-af7d-11ea-898e-3717dc3e4f1f.png)
