### ISSUE TITLE
Lagging really badly

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#3948]
i7 2600k, 32gb ram, gtx 1060
springsettings.cfg
https://pastebin.com/WE3n2zKc

late game I get 3-5 fps most of the time, some games I drop to single frame numbers hovering about 1 fps

early game runs super smooth

**Comment by GoogleFrog** [comment]
Send an infolog. Making a bug report through Help in the menu sends it all.

**Comment by let4be** [comment]
https://pastebin.com/iwzRFEaz

**Comment by let4be** [comment]
I tried pressing prtscr during game but it's broken and doesn't take screenshot... I forgot which command in console to take screenshot, why prtscr is not working?...

**Comment by Arch-Shaman** [comment]
Is this still happening?

**Comment by sprunk** [comment]
I couldn't find anything useful in the infolog. Marking as duplicate of #2148 (same user, also perf issues)
