### ISSUE TITLE
Mexes not rendered on the minimap correctly

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#395]
On this setup, minimap lacks mexes. They are completely invisible even in eco mode

**Comment by GoogleFrog** [comment]
Does it still occur? Is it consistent for maps?

**Comment by sprunk** [comment]
Try disabling the map edge extension widget (through F11 not F10). It's known to screw up other widgets' GL calls.

**Comment by GoogleFrog** [comment]
Fixed.

**Comment by sprunk** [comment]
For the record https://github.com/ZeroK-RTS/Zero-K/commit/f7a180a9a6e42d8e41441f35f93a91471b002846
