### ISSUE TITLE
Selection hotkey wanted; select unloaded transports

### ISSUE THREAD

**Issue by thomas11111111** [ZeroK-RTS/Zero-K#3953]
""

**Comment by Arch-Shaman** [comment]
I have a widget that filters unloaded/loaded transports atm as well as adding select all loaded/unloaded transports. Where might I add its code to?

**Comment by GoogleFrog** [comment]
You can just add a widget that adds a hotkey option entry.

**Comment by Arch-Shaman** [comment]
Understood. I'll pr that today then.

**Comment by Arch-Shaman** [comment]
PR'd. I've had this on standby for a few days now for testing purposes. I've removed the athena selection, etc in the original widget because those can probably be done via that one line fix you hinted at.
