### ISSUE TITLE
Hotkey : Select all Athenas

### ISSUE THREAD

**Issue by thomas11111111** [ZeroK-RTS/Zero-K#3961]
""

**Comment by Aquanim** [comment]
Is there something wrong with putting Athenas on an autohotkey? Alt-number or whatever it is.

**Comment by thomas11111111** [comment]
It is limited to numbers, takes up an autogroup slot. Athena is special enough to use a hotkey that is easily accessible. 
There are only 5 autogroups that dont recquire to check the keyboard to accurately press. 
also transports, owls and raptors have a hotkey

**Comment by GoogleFrog** [comment]
This is a one-line change that would be perfect for @thomas11111111 to investigate and implement..

**Comment by GoogleFrog** [comment]
Why was this closed?

**Comment by thomas11111111** [comment]
missassessed

**Comment by thomas11111111** [comment]
missclick
