### ISSUE TITLE
Show WAIT state as hovering icon

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#397]
When a unit is set to Wait the rotating hourglass is currently only drawn in the unit center (making it extremely hard to see at close zoom) when having the unit selected and holding Shift.

This needs to be changed:
Draw the hourglass overhead a unit and ALL THE TIME, just like the Facplop and DDM/Anni/...'s Needs-Energy-Grid icons.

When doing this think twice before removing the currently displayed hourglass. Removing it would make it impossible for players to see the Wait state when zoomed out. (Hovering icons either don't show up when unit-radar-icons are drawn or they are hidden behind it.) Perhaps certain unitstates like Wait should be drawn over the unit-radar-icon at all time.

**Comment by CarabusX** [comment]
I was thinking about the same thing. The Wait command may be confusing for newbies and needs to be more noticable.
Drawing the hourglass icon is not problem. But can the engine-drawn hourglass be even removed? Do we have any control about rendering of command queues?
