### ISSUE TITLE
Lobster

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#3992]
The problem is. Again. 

Lobster disables range and speed for any unit. Units are balanced because they have properties. For example range. For example speed. If the unit has bad speed or range, it is likely to have better stats in the other properties. For example dps.

Scallops get another benefit, as they have 2 guns and a penalty to be required to dive up to use their main gun. Plus they leave the water and are immune to torpedos and water bombs for the time they immediately have both their dps available. 

How can i emphasize this issue any further without raging?

GF. Can we hear your points again to defent the current state and find suggestions to fix this. I like the unit but it breaks everything.

**Comment by mojjj** [comment]
http://zero-k.info/Battles/Detail/923129

**Comment by GoogleFrog** [comment]
Iirc my most recent thoughts are here: http://zero-k.info/Forum/Thread/31559

In short I think the following could take Lobster in a good direction:
 - Slightly reduced range. This makes Lobster armies a bit more vulnerable while getting into position, without removing the cliff-climbing or defense assault abilities.
 - Significantly increased cost. This makes launching a Lobster with the ball (for quick retreating) an expensive thing to do. I think the case where a Lobster is launched in and then away is much harder to fight against than an army that is just launched in.
 - More reload time. This makes them less deadly when used on offense and less useful as transports.

**Comment by mojjj** [comment]
Probably semi-helpful.

What about
Reducing throwing capabilities to 3? units per lobster
Lobbed units get disarmed for 3 seconds
Reducing range significant to match default jump range

**Comment by GoogleFrog** [comment]
- I dislike reduced throwing capacity because it makes the unit fiddlier to use. There is the additional requirement of moving the right units into range and making sure they are the ones that will be launched.
 - I dislike disarm because it is anti-synergy. I would rather have things be weak and good when used together than strong with an explicit way of making them bad when combined. I think a range reduction is a more natural way to nerf its use in combat.

**Comment by Arch-Shaman** [comment]
Requires feedback since the latest stable?

**Comment by sprunk** [comment]
Assuming the substantial nerf (incl. +50% cost) in 55ef5fa55f65a624f38690314ae8a746a22b1db9 did the trick.
