### ISSUE TITLE
Increase recloak delay for units without personal cloak

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4005]
Units seem to decloak after 3.3 seconds. Units without personal cloak could increase this to 5 or 6 seconds. This is a simple alternative to https://github.com/ZeroK-RTS/Zero-K/issues/3972.

**Comment by Arch-Shaman** [comment]
This looks small, simple and straight forward. I can take it on if you approve.

**Comment by GoogleFrog** [comment]
You can, if you can do it within two hours, use a customParam set in unitdefs_posts for units that are able to cloak, and deal with commanders that acquire a personal cloak module.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/3605a75e0f8aadde3ffd3a4aad5a231d05efccac
