### ISSUE TITLE
Gauss buildable on water

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4008]
This has been driving me nuts for some time. Why isn't gauss able to be built on water since it has legs in water now?

**Comment by Licho1** [comment]
If everything is buildable in water whats the point of water then? Just an area ships cannot leave?

**Comment by Feugent** [comment]
Gauss was never intended to be buildable on water.
Gauss got legs so you can no longer rez them to (OP) underwater gauss, but have them being on water instead.

**Comment by sprunk** [comment]
Duplicate of #3244
