### ISSUE TITLE
Athenas can't be built on water

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4014]
They probably should be built on water. I looked at the unitdef but I dont see why it's not buildable on water.

**Comment by Arch-Shaman** [comment]
I've tried maxdepth, editing the movement def, etc, but could not get athena to be built on water.

**Comment by sprunk** [comment]
Engine issue, PR'd a fix (was unsure whither so I did both)
spring/spring#562
beyond-all-reason/spring#30

**Comment by sprunk** [comment]
beyond-all-reason/spring@ccace37e001e1a8c8bc7fd4dede6b062bdf21b2b
