### ISSUE TITLE
Investigate Save/Load Problem

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K#4016]
Crash reports seem to be coming in for some people while saving/loading. Was able to create a very basic 1v1 skirmish save file that crashed on load. Two seconds of gameplay, with more than 5mb of data saved. Save file attached.

[Save File and Infolog](https://github.com/ZeroK-RTS/Zero-K/files/4945239/saveplusinfolog.zip)

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/32568

**Comment by sprunk** [comment]
![image](https://user-images.githubusercontent.com/2573076/88201500-d2d2dc00-cc47-11ea-8178-9b3b43dafc7f.png)

**Comment by Porkch0p** [comment]
Though it seems the change has broken compatibility when loading older save files at some level. http://zero-k.info/Forum/Thread/31750

> started a new single player game yesterday, saved and loaded it several times...woke up this morning and went to play...Save game was gone...nice... 

https://github.com/ZeroK-RTS/CrashReports/issues/32628
> [f=-000001] Warning: [LSH::LoadGameStartInfo][REL] file was saved by incompatible engine version "104.0.1-1529-gffcc8d2 maintenance"
> [f=-000001] Warning: [Game::Load][6] forced quit with exception "Metadata checksum error: Package file was saved with a different version"

**Comment by GoogleFrog** [comment]
The fact that saves are potentially compatible across versions at all is surprising to me.
