### ISSUE TITLE
Airfac airpad inconsistency

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4036]
Airpad which comes with the factory is all weird and gross. Unlike with normal pads, It's difficult to reliably deal damage to the landed bomber (doesn't take dmg from Swift laser, largely blocks Raptor dmg from straight above).

**Comment by Arch-Shaman** [comment]
Perhaps the colvol can be edited to not include the airpad?

**Comment by GoogleFrog** [comment]
There is no solution short of a remodel as the model looks like it blocks the pad.
