### ISSUE TITLE
Coms walking into Outlaw AOE bugs

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#404]
Either a bug or an oddity:
- coms walking into a friendly outlaw aoe will decloak once then recloak.
- com will flash in the gui (with idle coms as if it was being damaged) (may be spectator only?)

See Corvus_Corax -- ~23 minute mark in http://zero-k.info/Battles/Detail/311863

**Comment by Anarchid** [comment]
Replication failed or replication method went 404.
