### ISSUE TITLE
Fighter pullup error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4061]
`[f=0000488] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitCreated trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_fighter_pullup.lua"]:28: [SetMoveTypeData] unit 9294 has incompatible movetype for SetAirMoveTypeData
stack traceback:
	[C]: in function 'spMcSetAirMoveTypeData'
	[string "LuaRules/Gadgets/unit_fighter_pullup.lua"]:28: in function 'UnitCreated'
	[string "LuaRules/gadgets.lua"]:1445: in function <[string "LuaRules/gadgets.lua"]:1440>
	(tail call): ?`

https://github.com/ZeroK-RTS/CrashReports/issues/33320

**Comment by sprunk** [comment]
Looking at some later lines this seems to be caused by Zero-Wars
`[f=0000759] [i18n] Error: No translation found for "heroduck.description"`
