### ISSUE TITLE
Disable sharing to inactive teams

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4068]
https://zero-k.info/Forum/Thread/31958

**Comment by Arch-Shaman** [comment]
I guess this is a share dialogue fix or do you also want it game side?

**Comment by GoogleFrog** [comment]
There is a sharing gadget that enforces this type of thing.

**Comment by Arch-Shaman** [comment]
Got it. Just repurposed some commshare code to detect afk/dead team here and applied it to the allied check part.
