### ISSUE TITLE
Missile Silo not playing launch sound

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4074]
A well known issue of Missilo Silo being a sleazy bag of misfortune. Sometimes, especially during consecutive launches, Silo doesn't play a launch sound, which is sorta crucial for the opposing team. This seems to happen to **all** players on the server (nobody hears the sound when the bug occurs).

**Comment by Anarchid** [comment]
The sound probably has a long tail and a low maxConcurrent.
