### ISSUE TITLE
[Feature] Overdrive 'status' display?

### ISSUE THREAD

**Issue by Sharkgamedev** [ZeroK-RTS/Zero-K#4081]
I recently discovered on the wiki that the colours in the economy display mean something - 

If a grid is pink or violet—Make sure you have some excess energy and connect Metal Extractors and energy structures together.

If a grid is light blue or green—Keep adding energy.

If a grid is yellow or red—The grid is inefficient. Spread out the energy by expanding the grid to connect more Metal Extractors.

I feel this is not really all that apparent and it is hard to remember all those colours. Do you think it would be helpful to have something under the little economy display that comes up when you hover over the energy info on the top bar that would give a short 'status' update? 
E.G. Expand Energy production
I've been a long time player and have always wanted to contribute somehow to zero-k maybe a small task like this could be a good way to start? I'm just looking for thoughts on whether or not this would be a useful thing or if its something that just I want.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/92186669-de4a3180-ee9a-11ea-8067-de84e60f69c3.png)
Are you thinking of adding a line of text here that says things like "Add more energy" or "Add more metal"? That seems fine.

**Comment by Sharkgamedev** [comment]
> ![image](https://user-images.githubusercontent.com/1318249/92186669-de4a3180-ee9a-11ea-8067-de84e60f69c3.png)
> Are you thinking of adding a line of text here that says things like "Add more energy" or "Add more metal"? That seems fine.

Yes that's exactly what I was thinking of!

**Comment by GoogleFrog** [comment]
Why was this closed? I don't see such a line of text in my screenshot.

**Comment by sprunk** [comment]
Note: second-to-last line is "overdrive efficiency", the screenshot is a bit unfortunate but the number changes color with the same meaning as the grid. Maybe putting that line at the end with the text would be a better place (rather than weaving it somewhere among numerical stats)?

**Comment by GoogleFrog** [comment]
Some newlines could be inserted to sort the stats into income/expense/storage. Overdrive expense, efficiency, and a new advice line (connect mexes, connect energy, make energy etc..) could be grouped at the bottom of expense so it stands out.

**Comment by Sharkgamedev** [comment]
> Why was this closed? I don't see such a line of text in my screenshot.

Oh sorry I thought it was standard to close things like this - should I reopen it?

And these are some good ideas!

**Comment by GoogleFrog** [comment]
A ticket is closed when there is nothing more to do, either the feature exists or won't exist. When you closed the ticket it looked like you thought no change was required.

**Comment by GoogleFrog** [comment]
Team and local should remain as the highest level separation because things like OD efficiency don't even make sense on an individual level. What you have looks reasonable, except Construction, Other, and Waste are also expenses, and perhaps Team Store should have a newline.

**Comment by Sharkgamedev** [comment]
> Team and local should remain as the highest level separation because things like OD efficiency don't even make sense on an individual level. What you have looks reasonable, except Construction, Other, and Waste are also expenses, and perhaps Team Store should have a newline.

Hmm I'm still a little confused here. Are you saying keep the structure like

Local Energy Economy
   Content
Team Energy Economy
   Content

Or do like

Income
   Local income
   Team income
Expense
   Local expenses
   Team expenses
Storage
   Local storage
   Team storage

**Comment by Sharkgamedev** [comment]
> Team and local should remain as the highest level separation because things like OD efficiency don't even make sense on an individual level. What you have looks reasonable, except Construction, Other, and Waste are also expenses, and perhaps Team Store should have a newline.

Oh and yes i'll make sure to add those to the expenses. As for income: innate and community, generators, reclaim, and then should increase and pull be seperated or you think they are better like they are now next to each other for pure readability?

**Comment by Sharkgamedev** [comment]
Ok everything should be ready and if I did it right the pull request ready for review.
