### ISSUE TITLE
Order of commands on the tab is not stable

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4105]
![image](https://user-images.githubusercontent.com/2573076/92995509-9e232880-f504-11ea-94b9-2b76bf3a20f0.png)

![image](https://user-images.githubusercontent.com/2573076/92995512-a4b1a000-f504-11ea-9235-0ffcb41b66ff.png)

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/36423892c18d774f417140bdb584bbf9ad9b2dcf
