### ISSUE TITLE
Strider hub nanoaim inconsistent.

### ISSUE THREAD

**Issue by Sharkgamedev** [ZeroK-RTS/Zero-K#4107]
It seems that the strider hubs aim is really inconsistent and will not turn towards any newly placed striders, however, it does rotate for guard and repair commands.

Is this a known issue?

**Comment by Arch-Shaman** [comment]
To my knowledge, it's been one of those issues where the behavior is so minute and been there for so long that it's become normalized. Seek answers in the unitscript.
