### ISSUE TITLE
New sharemode crashes 

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4112]
Sharemode decided that every play in the game resigned at the very start of the game, then spammed the infolog with errors each frame.

[sharemodeBugAndReplay.zip](https://github.com/ZeroK-RTS/Zero-K/files/5251053/sharemodeBugAndReplay.zip)

**Comment by Arch-Shaman** [comment]
Hm.. judging by the log here it looks to be some sort of pregame disposal. Investigating.
