### ISSUE TITLE
Units on limited move return to a previous position after finishing their move order.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#4123]
Sometimes units like to start moving by themselves after finishing a move order. Maybe this is caused by the new limited move not registering the new position?

Example in https://zero-k.info/Battles/Detail/961583

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/0f1a0b02524254f531d9ea26b2935e03320c4895

**Comment by GoogleFrog** [comment]
I think it was related to the cut down AI that was added to units without tactical AI (such as Halberd) being so cut down that it go dormant while the unit isn't idle and miss the fact that it was given a manual order.
