### ISSUE TITLE
Disabling room boss's voteless kick command in rooms that have at some point been unpassworded

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K#4140]
Would be best if voteless kicks by room bosses were disabled in rooms that have at some point been unpassworded, because this is against the CoC in most cases where it happens.

If an unpassworded room becomes passworded again, the voteless kick command should stay disabled, to prevent circumventing this with temporary !setpassword.

**Comment by Arch-Shaman** [comment]
Infra issue.

**Comment by sprangg** [comment]
Oops, posted to the wrong place. I'll close this and reopen it at infra.

**Comment by Arch-Shaman** [comment]
Alright sounds good. Was going to do it for you, but you got it handled.
