### ISSUE TITLE
Tooltips need to display a Shield bar

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#415]
Tooltips for shielded units such as Convict, Thug, Aspis and Commanders should display a bar similar to the HP bar showing current/max shield in the unit tooltip. The color could either be purple to be the same as the shield bar displayed over unit heads, or blue to be the same as shields in many other games (so players are familiar).

**Comment by Skasi** [comment]
Shield bar is still not displayed in the units tooltip!

**Comment by GoogleFrog** [comment]
Don't want to make the tooltip too large. The BP bar is not displayed there either.

**Comment by Skasi** [comment]
If size is the only issue then the shield bar could be added behind the current health bar and the health bar width reduced as necessary.
