### ISSUE TITLE
Gunship strafe option should be in default ui

### ISSUE THREAD

**Issue by Feugent** [ZeroK-RTS/Zero-K#4160]
Being unable to e.g. stop locusts from strafing into defense range while attacking sth. barely outside of def range is very frustrating.
Its pretty much impossible to have advanced gunship play without strafe control.

**Comment by GoogleFrog** [comment]
I really doubt many people knew about the toggle, so showing it doesn't exactly resolve this frustration. Perhaps it should be tied to hold position in the default UI. I guess the current toggle won't hurt too much so it can appear by default. it's easier than solving the underlying issue.
