### ISSUE TITLE
You should be able to play the game without an internet connection

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4170]
Right now if the zero-k updater can't check for updates it doesn't launch the game.

You should be able to play the game offline and over LAN without an internet connection.

Expected behaviour:
-after launching the game, if  the updater can't connect online, it should just start the game anyway
-there should also be a "skip and launch game" button on the updater that the user can press to skip having to wait for the update to fail and launch the game right away

**Comment by Arch-Shaman** [comment]
Wrapper issue?

**Comment by deee167** [comment]
> 
> 
> Wrapper issue?

I think so.  It should be a simple fix to the wrapper.

**Comment by sprunk** [comment]
If it was simple it would have already been done by somebody.  See the discussion linked below.

Duplicate of ZeroK-RTS/Zero-K-Infrastructure#1851

**Comment by deee167** [comment]
Can this still be implemented.  There is no reason why you should not be able to play this game without an internet connection even LAN should work from a user's perspective.

**Comment by GoogleFrog** [comment]
This ticket isn't relevant. See the infra ticket linked above.

**Comment by deee167** [comment]
> 
> 
> This particular ticket isn't relevant as it is in the wrong repository and a duplicate. We're not saying it shouldn't be done. See the infra ticket linked above.

Then can you please move it to the correct repository or open the other ticket you linked.  I would like this feature/issue fixed.

Thank you.
