### ISSUE TITLE
Cheat command forever enables enemy vision

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4176]
Enabling cheat with /cheat forever allows you to see opponent's units even in fog of war and when they are cloaked.  This can be see in skirmish vs an AI.

Enable cheats with /cheats.  Then use the icon for cheats and even when you uncheck enable cheats and even type /cheat again to disable, save the game, load the game, etc.  you will forever be able to see all units of the AI including cloaked ones.

**Comment by Arch-Shaman** [comment]
This is likely because /globallos was used at some point.

**Comment by deee167** [comment]
I have no idea what you are talking about.  I didn't use any/globallos command.

Here is what I did:
start a skirmish game vs an AI
type /cheat
click on the yellow icon in the top left
spawn some units for myself (didn't use any other cheats)
unchecked the enable cheat checkbox that was enabled by default in the cheats GUI
typed /cheat to disable cheats (this made the icon for cheats disappear)
saved the game
loaded the game
I could still see all enemy units at all times including cloaked ones

In every other RTS that I have ever played, you don't get full map vision just be enabling cheats.  The only way to enable full map vision is to explicitly enable it on purpose.

Please change this behaviour.  Only the cheats I select should be enabled.  The game shouldn't assume I want some cheat that I in fact don't.

Thanks

**Comment by Sharkgamedev** [comment]
> I have no idea what you are talking about. I didn't use any/globallos command.
> 
> Here is what I did:
> start a skirmish game vs an AI
> type /cheat
> click on the yellow icon in the top left
> spawn some units for myself (didn't use any other cheats)
> unchecked the enable cheat checkbox that was enabled by default in the cheats GUI
> typed /cheat to disable cheats (this made the icon for cheats disappear)

There is a button right under enable cheats for enable globallos, if you were to actually hit the enable cheats button the icon would have disappeared without you having to put the command back in, you must have accidently clicked on enable globallos.

**Comment by deee167** [comment]
> 
> 
> > I have no idea what you are talking about. I didn't use any/globallos command.
> > Here is what I did:
> > start a skirmish game vs an AI
> > type /cheat
> > click on the yellow icon in the top left
> > spawn some units for myself (didn't use any other cheats)
> > unchecked the enable cheat checkbox that was enabled by default in the cheats GUI
> > typed /cheat to disable cheats (this made the icon for cheats disappear)
> 
> There is a button right under enable cheats for enable globallos, if you were to actually hit the enable cheats button the icon would have disappeared without you having to put the command back in, you must have accidently clicked on enable globallos which is right under it. This is not a behaviour in the game afaik and I have never had it happen to me, I'm 90% sure it's that otherwise it's a bug.

There is no button right under enable cheats for globallos.  There is a space then 3 checkboxes and none of them say globallos.

Also unchecking "enable cheats" DOES NOT remove the cheats button from the GUI.  I'm sure I hit the correct checkbox.  Just in case, I just re-tested it now and verified that unchecking enable cheats DOES NOT remove the cheats icon from the top left.

**Comment by Sharkgamedev** [comment]
> > > I have no idea what you are talking about. I didn't use any/globallos command.
> > > Here is what I did:
> > > start a skirmish game vs an AI
> > > type /cheat
> > > click on the yellow icon in the top left
> > > spawn some units for myself (didn't use any other cheats)
> > > unchecked the enable cheat checkbox that was enabled by default in the cheats GUI
> > > typed /cheat to disable cheats (this made the icon for cheats disappear)
> > 
> > 
> > There is a button right under enable cheats for enable globallos, if you were to actually hit the enable cheats button the icon would have disappeared without you having to put the command back in, you must have accidently clicked on enable globallos which is right under it. This is not a behaviour in the game afaik and I have never had it happen to me, I'm 90% sure it's that otherwise it's a bug.
> 
> There is no button right under enable cheats for globallos. There is a space then 3 checkboxes and none of them say globallos.
> 
> Also unchecking "enable cheats" DOES NOT remove the cheats button from the GUI. I'm sure I hit the correct checkbox. Just in case, I just re-tested it now and verified that unchecking enable cheats DOES NOT remove the cheats icon from the top left.

My bad then, I could have sworn that was the case. The checkbox does not say globallos on it, but something similar.

**Comment by deee167** [comment]
> 
> 
> > > > I have no idea what you are talking about. I didn't use any/globallos command.
> > > > Here is what I did:
> > > > start a skirmish game vs an AI
> > > > type /cheat
> > > > click on the yellow icon in the top left
> > > > spawn some units for myself (didn't use any other cheats)
> > > > unchecked the enable cheat checkbox that was enabled by default in the cheats GUI
> > > > typed /cheat to disable cheats (this made the icon for cheats disappear)
> > > 
> > > 
> > > There is a button right under enable cheats for enable globallos, if you were to actually hit the enable cheats button the icon would have disappeared without you having to put the command back in, you must have accidently clicked on enable globallos which is right under it. This is not a behaviour in the game afaik and I have never had it happen to me, I'm 90% sure it's that otherwise it's a bug.
> > 
> > 
> > There is no button right under enable cheats for globallos. There is a space then 3 checkboxes and none of them say globallos.
> > Also unchecking "enable cheats" DOES NOT remove the cheats button from the GUI. I'm sure I hit the correct checkbox. Just in case, I just re-tested it now and verified that unchecking enable cheats DOES NOT remove the cheats icon from the top left.
> 
> My bad then, I could have sworn that was the case. The checkbox does not say globallos on it, but something similar.

There is a global vision thing.  Maybe that's what you are talking about.

In any case, unchecking enable cheats doesn't seem to behave as you or I expect it.  Sounds like that part is a bug.

As for the enemy vision, I wonder if it has to do with revealing the enemy if my forces are overwhelming, but I thought that used to disable itself once the enemy built more forces didn't it?  Not sure if this is the cause of this yet, but maybe since I cheated some units in.  Will have to play more to see and test it.

**Comment by Arch-Shaman** [comment]
Globallos is the engine term for Global Vision.

And yes, overwhelming advantage does enable vision of all enemy units. You can check if this is globallos by looking to see if the map is completely lit up or if there's fog of war still.

**Comment by deee167** [comment]
> 
> 
> Globallos is the engine term for Global Vision.
> 
> And yes, overwhelming advantage does enable vision of all enemy units. You can check if this is globallos by looking to see if the map is completely lit up or if there's fog of war still.

Doesn't enemy vision of units disable once the overwhelming advantage goes away?

This might be the overwhelming advantage so it might not be an issue.  However there is still an issue with the icon for cheats not going away when you uncheck cheats.

**Comment by Arch-Shaman** [comment]
That would be purely a widget problem and not backend. This is something you could probably do. It's relatively minor.

**Comment by sprunk** [comment]
Some remarks:
 * the yellow cheat button doesn't go away from the top bar when you disable cheats, this is by design. It's so that you can re-enable cheats easily again and as a soft "this match is tainted" indicator (not being present for the first time is also because it saves on interface button clutter since most games won't have cheats enabled, and partially because manually typing some `/command` gives the HACKERMAN vibes).
 * the `/cheat` mode, or equivalently the "Enable cheats" checkbox on the cheat menu, only toggles the possibility of toggling other cheats, but not their effects (meaning that if you tick "Global vision" or "Instant build", and then untick "Enable cheats", the global vision or instant build effects will stay and you will be unable to disable them).
 * overwhelming advantage is permanent and doesn't go away. I am not 100% certain but it's probably by design since it's a soft victory condition and you're supposed to just mop the floor at that point. 
 * I can't reproduce the global vision just from `/cheat` alone without spawning anything.

As far as I can see everything relevant is behaving as supposed to. If you could confirm that just `/cheat` (without spawning anything, or at least without reaching overwhelming advanrate) doesn't reproduce the bug then I'd close.

**Comment by deee167** [comment]
> 
> 
> Some remarks:
> 
>     * the yellow cheat button doesn't go away from the top bar when you disable cheats, this is by design. It's so that you can re-enable cheats easily again and as a soft "this match is tainted" indicator (not being present for the first time is also because it saves on interface button clutter since most games won't have cheats enabled, and partially because manually typing some `/command` gives the HACKERMAN vibes).
> 
>     * the `/cheat` mode, or equivalently the "Enable cheats" checkbox on the cheat menu, only toggles the possibility of toggling other cheats, but not their effects (meaning that if you tick "Global vision" or "Instant build", and then untick "Enable cheats", the global vision or instant build effects will stay and you will be unable to disable them). This is just how the engine works so it's not something we can do much about either way.
> 
>     * overwhelming advantage is permanent and doesn't go away. I am not 100% certain but it's probably by design since it's a soft victory condition and you're supposed to just mop the floor at that point.
> 
>     * I can't reproduce the global vision just from `/cheat` alone without spawning anything.
> 
> 
> As far as I can see everything relevant is behaving as supposed to. If you could confirm that just `/cheat` (without spawning anything, or at least without reaching overwhelming advanrate) doesn't reproduce the bug then I'd close.

Thanks for the explanation.
I can't confirm right now if just /cheat enables this, it seemed to be more when i disable cheating that it enabled global vision but that might just be a delay from spawning units perhaps.  I can't confirm for sure right now, but it's likely that spawning units gave the global vision.

Was there an update to the game in the last 3 or so days, as I can't load any saved game anymore.  The game just crashes to desktop.

**Comment by Arch-Shaman** [comment]
According to github it doesn't seem so.

**Comment by deee167** [comment]
> 
> 
> According to github it doesn't seem so.
> 
> The current work stands to be a minor or major patch, so in all likelihood there'd be patch notes on site. Usually the only thing that doesn't generate patch notes are hotfixes.

I think there was a hotfix to fix this: https://github.com/ZeroK-RTS/Zero-K/issues/4175 but if there was it broke loading saves completely.  Can you please look into it.  I can't load any of my saves I want to play.  Thanks

**Comment by sprunk** [comment]
Assuming the vision was a result of overwhelming advantage.
