### ISSUE TITLE
Option to disable the idle timer

### ISSUE THREAD

**Issue by deee167** [ZeroK-RTS/Zero-K#4177]
Is the idle timer still in game?  Just got back into the game recently but I remember there was a timer that would give control of all your units to someone else if you don't move your screen/mouse in a little bit.

I would like an option to disable this in options permanently.

I like playing games in multiplayer with people I know and we have fun VS AI's.  It's bad when the game takes away control for all my units just because I'm enjoying a nice fight.  Then I have to move the mouse to get control back.  It de selects what I had selected and displays notification etc.   This is really bad.  I get why this makes sense in a competitive multiplayer game, so I would like the option to turn it off in options for all the games I play.  That way everybody can play how they like.

EDIT:
There seems to be an option "Enable Inactivity Sharing".  Can someone confirm that unchecking this will indeed disable anybody losing controls of their units while idle in that game?

Can anybody enable this option when joining a game or does it have to be enabled by the host of the game?

Thanks.

**Comment by Sharkgamedev** [comment]
> EDIT:
> There seems to be an option "Enable Inactivity Sharing". Can someone confirm that unchecking this will indeed disable anybody losing controls of their units while idle in that game?
> 
> Can anybody enable this option when joining a game or does it have to be enabled by the host of the game?
> 
> Thanks.

Unchecking enable inactivity sharing will disable the behaviour, I'm not too knowledgable on who can control what but Afaik the host is the only one that can control anything - players can vote on options to be changed but the host still has to except it.

**Comment by deee167** [comment]
> 
> 
> > EDIT:
> > There seems to be an option "Enable Inactivity Sharing". Can someone confirm that unchecking this will indeed disable anybody losing controls of their units while idle in that game?
> > Can anybody enable this option when joining a game or does it have to be enabled by the host of the game?
> > Thanks.
> 
> Unchecking enable inactivity sharing will disable the behaviour, I'm not too knowledgable on who can control what but Afaik the host is the only one that can control anything - players can vote on options to be changed but the host still has to except it.

Oh that's right.  I forgot about the vote system.  Does that mean that people could vote on enabling or disabling this feature while in game?

**Comment by Arch-Shaman** [comment]
It's a modoption, so you must set it before game.

**Comment by deee167** [comment]
> 
> 
> It's a modoption, so you must set it before game.
> 
> You can do so by `!setoptions enablelagmonitor = false`
> 
> Players can do setoptions safely. If the host does it, no vote is necessary. If players do so, the vote will need to pass.
> 
> Since this is already implemented, this issue can be closed.

Thanks
