### ISSUE TITLE
[ZK:Test] Lua error in unit_jumpjets.lua

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4178]
[f=0025335] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=UnitDamaged trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_jumpjets.lua"]:481: attempt to index local 'jump_dir' (a boolean value)
stack traceback:
	[string "LuaRules/Gadgets/unit_jumpjets.lua"]:481: in function 'UnitDamaged'
	[string "LuaRules/gadgets.lua"]:1534: in function <[string "LuaRules/gadgets.lua"]:1519>
	(tail call): ?

Replication method:
1.) Load up ZK:Test
2.) Get a few jump jet units.
3.) Have them jumping while they're about to get killed.
4.) Error occurs.

**Comment by Arch-Shaman** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/657bc0eed57ffe80fbff8d0c0d64681a84aa194c

I traced the changes back to this hm.

**Comment by GoogleFrog** [comment]
I removed a table spam because it seemed to no longer have a purpose, but it did have a purpose. Maybe there is a Spring.GetSomething that can replace it.
