### ISSUE TITLE
Unit Level Ups is full of errors

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4191]
https://github.com/ZeroK-RTS/CrashReports/issues/35279
[20201114_221714_EvoRTS-New_Iammas-v05_104.0.1-1544-ge1f249f maintenance.sdfz.txt](https://github.com/ZeroK-RTS/Zero-K/files/5540580/20201114_221714_EvoRTS-New_Iammas-v05_104.0.1-1544-ge1f249f.maintenance.sdfz.txt)
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/5540581/infolog.txt)

**Comment by pts1667** [comment]
this should fix most of the errors I think
http://zero-k.info/Maps/Detail/59304

**Comment by GoogleFrog** [comment]
I fixed many of the script piece errors here: https://github.com/ZeroK-RTS/Zero-K/commit/5f6da2f62326003f87ec725a31a22777830d01ee

Carrier drones needs to be updated to have an API for replacing the points to drones.

**Comment by GoogleFrog** [comment]
Updated: https://github.com/ZeroK-RTS/Chobby/commit/95421b6a70e3487615b552210f436f3b56705202

**Comment by GoogleFrog** [comment]
I think https://github.com/ZeroK-RTS/Zero-K/issues/4183 is all that remains, but then the mutator would still need updating to use it.
