### ISSUE TITLE
Units target Badger mines before Badgers

### ISSUE THREAD

**Issue by izirayd** [ZeroK-RTS/Zero-K#4197]
Why lancers and firewalkers are trying to shoot the mines of the badger and not the badgers themselves?

**Comment by Arch-Shaman** [comment]
This issue needs renaming to "Badger mines confuse unit AI" or something along those lines.

**Comment by Arch-Shaman** [comment]
Feedback wanted: 
Behavior occurs still after anti-bait? (v1.9.3.0)
