### ISSUE TITLE
Why is Funnelweb faster than Knight?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4201]

**Comment by sprunk** [comment]
According to b5f95bcd22af765534700a03cac6d8cc2293dcbb it's so that it can keep up with Dante.

**Comment by GoogleFrog** [comment]
It's a giant constructor that wants to flee when enemies attack, so surely it should be pretty slow.

**Comment by sprunk** [comment]
I agree with the above and I think that being able to keep up with Dante is not really an important trait for Funnel (since striders don't need to complement each other as much as units from the real facs do).
