### ISSUE TITLE
Check whether factories close their yardmap while stunned

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4210]
See https://zero-k.info/Battles/Detail/998115

**Comment by Arch-Shaman** [comment]
Solved by https://github.com/ZeroK-RTS/Zero-K/commit/0ea9f478c7cc827c0514780cb47beae672925bd9 ?

**Comment by sprunk** [comment]
There's still #4279 as a reminder for the engine side of the task.
