### ISSUE TITLE
Archer mission (Blackmire) has outdated unit tip

### ISSUE THREAD

**Issue by Birdulon** [ZeroK-RTS/Zero-K#4219]
References old water gun which no longer exists.
![image](https://user-images.githubusercontent.com/5397662/101356774-80d5de80-38e8-11eb-85ae-6410a8d17731.png)

**Comment by sprunk** [comment]
ZeroK-RTS/Chobby@0e436e1c8aa889f32d32b219569d40f9bc79cc2c
