### ISSUE TITLE
Space + click to show unit stats should work on more location

### ISSUE THREAD

**Issue by matheod** [ZeroK-RTS/Zero-K#4221]
Space + click is an awesome feature for new player.

However, it does not work on every location, it would be nice if it could be added everywhere.

Missing location:

- On selected units icons
![image](https://user-images.githubusercontent.com/339611/101417573-3b1b1500-38ec-11eb-9ec2-23633d782ec9.png)

- On queued units
![image](https://user-images.githubusercontent.com/339611/101417621-4ec67b80-38ec-11eb-939f-520a815a8d28.png)

- On selected unit
![image](https://user-images.githubusercontent.com/339611/101417642-584fe380-38ec-11eb-93a6-075ff7d78365.png)

- On objective / tutorial screen
![image](https://user-images.githubusercontent.com/339611/101417689-71f12b00-38ec-11eb-8a49-2397f5dd1a0a.png)

**Comment by Birdulon** [comment]
Should probably edit to include "show unit stats" in the title as my expectation was related to the other use of space+click - inserting orders at the beginning of the existing queue!

**Comment by Birdulon** [comment]
I should also mention that I've started work on this and should have a PR ready a bit later, before anyone else jumps on it.
![image](https://user-images.githubusercontent.com/5397662/101439220-021e8700-3964-11eb-91ea-892cb9a3a263.png)
