### ISSUE TITLE
Potential fire at radar recursion

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4229]
https://github.com/ZeroK-RTS/CrashReports/issues/36241

[f=0018377] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=AllowWeaponTarget trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: [GiveOrderToUnit] recursion not permitted
stack traceback:
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Gadgets/unit_dont_fire_at_radar.lu..."]:104: in function 'AllowWeaponTarget'
	[string "LuaRules/gadgets.lua"]:1334: in function <[string "LuaRules/gadgets.lua"]:1310>
	(tail call): ?
	[C]: in function 'spGiveOrderToUnit'
	[string "LuaRules/Utilities/ClampPosition.lua"]:57: in function 'GiveClampedOrderToUnit'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:987: in function 'DoUnitUpdate'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1017: in function 'UpdateUnits'
	[string "LuaRules/Gadgets/unit_tactical_ai.lua"]:1032: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:957: in function <[string "LuaRules/gadgets.lua"]:955>
	(tail call): ?

**Comment by GoogleFrog** [comment]
This is a tricky one. It looks like issuing a FIGHT command can cause AllowWeaponTarget to trigger instantly, and thus prevents more commands being issued in AllowWeaponTarget.

**Comment by sprunk** [comment]
Engine now allows some recursion.
