### ISSUE TITLE
Save/load error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4233]
https://github.com/ZeroK-RTS/CrashReports/issues/36260

[f=-000001] Synced LuaRules: starting loading
[f=-000001] [gadgets.lua] Error: Failed to load: api_saveload.lua  ([string "LuaRules/Gadgets/api_saveload.lua"]:75: table index is nil)
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=1)][pcall] file=LuaRules/gadgets.lua error=2 ([string "LuaRules/Gadgets/mission_galaxy_campaign_ba..."]:1088: attempt to index local 'customKeys' (a number value)) ptop=3 cenv=0
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/draw.lua"]:26: in main chunk

**Comment by sprunk** [comment]
Few lines earlier:
 >[f=-000001] [PreGame::AddModArchivesToVFS][server=0000000064ff6f20] using game "Zero-K v1.6.9.0" (loaded=0 cached=0)
