### ISSUE TITLE
AllyTeam namer doesn't know what to do with Adamantine Mountain

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4238]
![image](https://user-images.githubusercontent.com/1318249/102437394-92e51900-406e-11eb-915c-95b2d7de06c6.png)

**Comment by Anarchid** [comment]
Clan or top player's name are picked in case the startbox gadget does not set the `allyteam_long_n` GRP. 

This could be because the map's startbox config fails (ZK repo has adamantine mountian 1, not 2), or because it's a custom game with weird allyteams.

Link battle?

**Comment by GoogleFrog** [comment]
http://zero-k.info/Battles/Detail/1010519

**Comment by Anarchid** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/906492eea879e4cb06cf1054b75efcb239cfb6c8 seems to affect `Adamantine Mountian V1`, while the linked battle is on `Adamantine Mountain 2`?

**Comment by sprunk** [comment]
Right
