### ISSUE TITLE
Better Defense circles needed for amph warfare

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#424]
Currently when playing with anything amphibian defense ranges drawn can not be relied upon for precise army movement because circles are only drawn above water and not on the ground surface below water.

To clarify:
Build two torpedo launchers in a deep ocean, build them far enough apart to leave a small gap between their range circles. Share them to an enemy player.
Now try to use the defense range drawn for them to move one or multiple Ducks through the gap without taking damage.

Another example is using Bouys and Scallops to kill torpedo launchers from afar without being inside the defense range of other nearby torpedo launcher (or when using Bouys even Defenders).

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/22d95187555be3077ce24ec661c4957daa477a9e

**Comment by sprunk** [comment]
Should be on top of water, but still under units.

Current behaviour:
![image](https://user-images.githubusercontent.com/1318249/74837409-8b34e500-5375-11ea-8d34-05f6b8f52a31.png)

**Comment by GoogleFrog** [comment]
Movement and construction orders are given onto the water surface, so I disagree with this ticket for the purposes of moving into range and precise construction. The Duck case is regrettable but unavoidable if we're to pick a consistent visualisation.
