### ISSUE TITLE
Queuing move orders after bombing seems broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4241]
Area attack two mexes like this.
![image](https://user-images.githubusercontent.com/1318249/102594350-2fd8ac80-416a-11eb-8f2c-bb817a2ed58f.png)

One of the Ravens does not follow the move order.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/102594633-8d6cf900-416a-11eb-86e5-37feb9fbd500.png)
The issue is that a second move order still exists.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/102595165-4a5f5580-416b-11eb-850c-0ac68fe58e83.png)
There is a widget that removes the duplicate attack commands of a split attack (Ctrl for split) but it does not seem to work on custom formations. This is how I hit the bug originally.

There is a question as to whether split attack should have its commands removed, or whether bombers should use their future move queue when retreating.

**Comment by GoogleFrog** [comment]
```
		 --This remove all but 1st attack order from CTRL+Area_attack if user choose to append new order to unit (eg: SHIFT+move),
		 --this is to be consistent with bomber_command (rearm-able bombers), which only shoot 1st target and move on to next order.
		 
		 --Known limitation: not able to remove order if user queued faster than network delay (it need to see unit's current command queue)
```
This too.

**Comment by GoogleFrog** [comment]
- Unmodded click single/multi: Attack point
 - Unmodded drag single/multi: Attack list of targets in the area, same order for all selected units.
 - Ctrl click single/multi: Attack point swapping the meaning of commandFire.
 - Ctrl drag single/multi: Attack list of targets in the area, cycle lists so the initial targets differ between selected units.
 - Alt click single/multi: Attack point.
 - Alt drag single: Attack a line of points, never getting to subsequent points unless the weapon is commandFire.
 - Alt drag multi: Selected units attack points spread on a line.
 - Ctrl + Alt click single/multi: Attack point once.
 - Ctrl + Alt drag single: Attack a line of points, swapping the meaning of commandFire
 - Ctrl + Alt drag multi:  Selected units attack points spread on a line, swapping the meaning of commandFire

**Comment by Licho1** [comment]
Happens with normal multiple unit attack (area attack to select multiple targets) + move
Or with fight + move.
Bombers skip the move in such cases and head straight back.

**Comment by GoogleFrog** [comment]
I think what I want is for bombers to search for move commands. If their queue is [attack fight attack etc move move] then every time they drop a bomb they should do the move at the start of their queue.
