### ISSUE TITLE
Odd 'white noise' texture in bottom left. (Potentially Unit Level Ups fault)

### ISSUE THREAD

**Issue by Sharkgamedev** [ZeroK-RTS/Zero-K#4245]
Reported by player TheoDiaz. He is in the discord server under the same name if you would like to contact him.
Important note: It seems he was running Unit Level Ups on the games in which it occurred, however, there have been other games with Unit Level Ups where it didn't occur. I'm unsure if this is a problem with Unit Level Ups (Hence why I have created this issue) but I have already pinged PressTab about it to see if he has any info.

We had a small conversation there, I've tried to bring the most relevant details into this issue, but if you would like to dig through that you can here: https://discord.com/channels/278805140708786177/432874986064052235/789211043171139584

Image of the problem:
![image](https://user-images.githubusercontent.com/29334908/102645823-1109f400-4131-11eb-88da-2c9b3ffa635d.png)

I asked him to send his infolog and he did however it doesn't contain any of the battles which the error occurred in, so I didn't include it. If you still want it you can find it on discord. I've asked him to tell me if it happens again, in which case I will add the infolog here.

He says it grows and shrinks as well as gets lighter and darker along with zoom level.
Happens on multiple maps too.
He is using standalone version, not steam and says it started happening a few days ago although it does not occur every game.

**Comment by sprunk** [comment]
Potato?

> [f=-000001] Error in [Outline Shader] widget: Deferred shading is not enabled or advanced shading is not active

> [f=-000001] Deferred Rendering (gfx_deferred_rendering.lua) requires  AllowDeferredMapRendering and AllowDeferredModelRendering to be enabled in springsettings.cfg!
```

**Comment by Porkch0p** [comment]
Looks to be a high end system lacking in potato flavor.
> Physical CPU Cores: 8
Logical CPU Cores: 16
Intel i7-10700F
GeForce RTX 2070 SUPER/PCIe/SSE2
[ 1] 2560x1440x24bpp@165Hz

**Comment by Porkch0p** [comment]
Floomby is also affected by this glitch. For what it's worth, comparing with a recent [error log](https://github.com/ZeroK-RTS/CrashReports/issues/41197) of theirs shows both user configs have no value set for deferred map/model rendering instead of 
> AllowDeferredMapRendering = 1
AllowDeferredModelRendering = 1

**Comment by sprunk** [comment]
Seems to be `Outline Shader`? Pictures by @Porkch0p 

![image](https://user-images.githubusercontent.com/2573076/127399257-77994629-c2b0-4fbe-b303-17ef615b4ff3.png)

![image](https://user-images.githubusercontent.com/2573076/127399289-9ea5b234-ebf2-4cc4-8823-8f6a66197590.png)

**Comment by Porkch0p** [comment]
Also it was possible to reliably prevent it from appearing by setting Deferred Rendering in graphics settings to 'On'

**Comment by Porkch0p** [comment]
The black texture does appear to be incorporating sections of a texture atlas. For Ronin it looks to be taking from https://github.com/ZeroK-RTS/Zero-K/blob/master/unittextures/spherebot1.dds

**Comment by sprunk** [comment]
Seems fixed by a2182704d16081898a7fa512db0182f799ff52a6
