### ISSUE TITLE
Old Falsell map missing in a Steam install 

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4253]
http://zero-k.info/Forum/Thread/32693

**Comment by Arch-Shaman** [comment]
[f=-000001] [VFS] Error: [SpringVFS::AddArchive<this=00000000482886f0>] failed to open archive 'Hide_and_Seek_v03' (path 'C:\Program Files (x86)\Steam\steamapps\common\Zero-K\maps\Hide_and_Seek_v03.sd7', type 3)
[f=-000001] [~ScopedOnceTimer][PreGame::StartServer] 96ms
[f=-000001] [WatchDog::DeregisterThread] deregistering controls for thread [main]
[f=-000001] Error: [ExitSpringProcess] errorMsg="[AddArchiveWithDeps] failed loading archive 'Hide_and_Seek_v03', dependency of 'Hide_and_Seek_v03'." msgCaption="Spring: caught content_error: " mainThread=1
[f=-000001] Error: [Watchdog::ClearTimer(id)] Invalid thread 4 (_threadId=0000000000000000)
[f=-000001] [SpringApp::Kill][1] fromRun=0
[f=-000001] [ThreadPool::SetThreadCount][1] wanted=0 current=3 maximum=4 (init=0)
[f=-000001] 	[async=0] threads=3 tasks=0 {sum,avg}{exec,wait}time={{0.000, 0.000}, {0.000, 0.000}}ms
[f=-000001] 	[async=1] threads=3 tasks=2 {sum,avg}{exec,wait}time={{0.000, 0.000}, {0.997, 0.498}}ms
[f=-000001] 		thread=1 tasks=1 {sum,min,max,avg}{exec,wait}time={{0.000, 0.000, 0.000, 0.000}, {0.000, 0.000, 0.000, 0.000}}ms
[f=-000001] 		thread=2 tasks=1 {sum,min,max,avg}{exec,wait}time={{0.000, 0.000, 0.000, 0.000}, {0.997, 0.997, 0.997, 0.997}}ms
[f=-000001] [ThreadPool::SetThreadCount][2] workers=0
[f=-000001] [SpringApp::Kill][2]

Relevant info from crash report

**Comment by Anarchid** [comment]
Most likely the map is absent in distribution.

**Comment by Nameless-Monarch** [comment]
> Most likely the map is absent in distribution.
> To test: do a fresh install and see if it's present.

Verifying game files fixed it, there were 5 missing items.

**Comment by Arch-Shaman** [comment]
The screenshot of the error box suggests a circular dependency (why is this communicated so poorly)

**Comment by Licho1** [comment]
Circular dependency could be a major issue. Backend should make sure there is no such dependency. Opening to investigate further.

**Comment by Anarchid** [comment]
The archive for Hide and Seek v3 does not contain *any* dependency definitions.

**Comment by GoogleFrog** [comment]
I see no reason to believe that error message. It is probably just trying to tell us something else.
