### ISSUE TITLE
Allow disabling communism mode

### ISSUE THREAD

**Issue by shirazmatas** [ZeroK-RTS/Zero-K#4268]
I feel like in custom lobbies people should have the ability to toggle how metal should be shared (All, mexes and overdrive, only mexes, none). Such feature would be greatly appreciated among my friends when we'd like to play in a specific way.

**Comment by GoogleFrog** [comment]
The core design of the economy assumes communism. Additional assumptions in the design and implementation cement communism to the point that removing it would be a relatively large task, on the scale of editing most of the overdrive gadget and a few associated widgets. There isn't a simple concept of ownership in the code, instead, the primary concept is the shared pool. Numerous design decisions would be required for non-communism in addition to the code changes.

Far larger subprojects have been completed in ZK development, so I'm not saying it is impossible. I'm just saying why I'm unlikely to do it and giving a sense of the task for someone who wants to pick it up. Making a mod that removes communism would be much simpler than making an option, as an option has to not be too burdensome to maintain for it to make it into the ZK repository.

**Comment by Licho1** [comment]
Making a mod does not sound that hard - worst case you play it without OD, priorities and morphing using engine resources only :-)
I would suggest closing this ticket if main devs have no intention of doing it.
