### ISSUE TITLE
Add search by name to map selection dialog

### ISSUE THREAD

**Issue by Ambulanss** [ZeroK-RTS/Zero-K#4274]
Currently there are a lot of maps to choose from. It would be nice to be able to filter them by name. The search could move the view to the map with the most similar name or filter all maps and leave only those whose names contain the searched string.

Just in case I wrote something unclear, I mean this dialog:
![obraz](https://user-images.githubusercontent.com/33929397/105638374-3396d780-5e6a-11eb-915d-d4ab1073f9cd.png)

**Comment by Arch-Shaman** [comment]
This belongs in Chobby

**Comment by Sharkgamedev** [comment]
This might be a easier thing to do with night watch, which to my knowledge already does a little bit of a fuzzy search.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Chobby/commit/eff053ff11a8e45a66b968c7395a9b4807276305
