### ISSUE TITLE
Investigate disarm award

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#4280]
In https://zero-k.info/Battles/Detail/1041395 I would have been the largest dealer of disarm damage (with Thunderbirds) and the award was indeed given to me, 450 million disarmed value seems on the large side though. Is the award just bugged or is this what Thunderbird's massive over-disarm looks like?

**Comment by floomby** [comment]
Yes that number is probably wrong. I will look at it and see what is going on.
