### ISSUE TITLE
Lagging behind on large games - Single Core to Multi Core?

### ISSUE THREAD

**Issue by JanStaelens** [ZeroK-RTS/Zero-K#4283]
Noticed the game seems to only utilise a single core fully?
I'm wondering if it's possible to move some aspects of the simulation multi-core.
Perhaps simulating the AI players could be offloaded to several cpu cores? 

My friends and I, we often play 'comp-stomp' games where we are definitely pushing the simulation and processing to its max. 
2 to 4 human players vs 3 to 5 brutal/eco AI aren't out of the question. Sometimes with X2 mass & power.
We disable certain units like the Merlin as we've noticed it can cause heavy lag in numbers (same as Nimbus, tremor, anything with many individual particles). We also often disable the game ender super weapons like zenith to really have a good tug of war.

Games seem to run fine for my friends who have high single core clock speed. However for us who have multiple cores with lower clock speed the game sometimes quickly desyncs and won't catch up. Last game I was 30-40 minutes behind and only caught up at the very end after blindly nuking most of the map.  CPU and Ping were both in yellow and red for the whole game.

I wanted to take a look myself in the code, but I don't have the experience and knowledge in LUA. I'm mostly a .NET developer.

**Comment by GoogleFrog** [comment]
As far as I know there is some multithreading. It is C++ in the engine if you want to look into it, not Lua.

Am I correct in saying that you're talking about slow computers not keeping up with the game, and not desyncronisation of gamesate?

**Comment by JanStaelens** [comment]
> 
> 
> As far as I know there is some multithreading. It is C++ in the engine if you want to look into it, not Lua.
> 
> Am I correct in saying that you're talking about slow computers not keeping up with the game, and not desyncronisation of gamesate?

That's what it feels like. The local simulation seems to gradually lag behind the other players/server as the match gets more units and the simulation gets more complicated. I can see a full core getting used completely when this is happening and reducing the unit count (through massive destruction of course) will eventually fix the problems.

Any mouse click I do, is still getting done immediately for the other players. For example, though on my screen the Trinity says a nuke is ready in 1 min 30 s.  If my game is 1 minute and 30 seconds behind, I can ask my friends over voice chat and they'll indicate a missile is sitting ready to go. If I then click on 'launch' it will actually fire the nuke on their screen in real time. For me it will fire 1 minute and 30s later, once the missile is actually ready.

(I ended up continuing to play like that, it was an interesting playstyle that's for sure)

I don't have the best CPU, but nothing too bad either I think. It's why I'm thinking having it spread the load and utilise more of the hardware could be interesting. Unless there are some debug items I could investigate in the next massive match that would assist in pinpointing my bottleneck?

Intel Core i7-2600 CPU  3.4GHZ (8 CPUs)

**Comment by Licho1** [comment]
You are actually lagging one after another. There is no actual server. It's just players. Anyway, yeah there is plenty of room for multi threading in engine. Isolated expensive functions could be run using all cores, thats probably the easiest way to start with it.

There was also fairly advanced project to push rendering to second thread that however required rewrite of all LUA so was abandoned.

**Comment by sprunk** [comment]
This is a long-standing and wide-reaching engine issue that ZK has little control over so I think the ticket is not useful. The BAR engine guys seem to be trying to do something in that direction.
