### ISSUE TITLE
Minimap Start Boxes widget - OpenGL issue?

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K#4285]
After enabling DebugGL = 1 in springsettings, I tracked down the only 'High' priority error I could find listed to the startbox widget. Whatever the cause is, it's being called repeatedly.

`[OPENGL_DEBUG] id=1280 source=API type=ERROR severity=HIGH msg="GL_INVALID_ENUM error generated. <mode> is not a valid polygon mode.`

Disabling the minimap_startbox_new widget prevents the error from being logged. Tested on multiple Nvidia systems with Medium preset.

![startbox-opengl-high-error](https://user-images.githubusercontent.com/49832728/106724465-dddecf80-65cd-11eb-9416-793fd7818f66.png)

**Comment by lhog** [comment]
s/GL.LINES/GL.LINE/
