### ISSUE TITLE
Consider Badger

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4288]
Badger gained at least 25% DPS when its 5th bomblet was fixed. It potentially gained more by also fixing the delayed Claw firing issue. It may be too good now and require a nerf. DPS is simple and reverts the change. It could also be slower while its gun is not stowed.

**Comment by Anarchid** [comment]
Seems to have been dealt with?

**Comment by sprunk** [comment]
NERFED :put_litter_in_its_place:
9ae4cca131f5e09c3aa1f80a772b5f23f234eedc
