### ISSUE TITLE
Check antinuke range

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4302]
https://zero-k.info/Battles/Detail/1054878

**Comment by Arch-Shaman** [comment]
I've concluded an investigation into this battle and report no antinuke shenanigans. However, I did find an edge case (and @sprunk reported a fix elsewhere) where there would have been a lua error.

Investigation concludes that Firepluk failed to scout a second anti that was hidden in fog. He scouted one antinuke (at about 4 o clock from center) and nuked into north, which had a fog hidden anti.

What Firepluk sees:
![image](https://user-images.githubusercontent.com/48730089/111411556-28656880-86b1-11eb-8f2e-808364cd6c31.png)

Reality:
![image](https://user-images.githubusercontent.com/48730089/111411585-361aee00-86b1-11eb-9040-c88fa1f8de33.png)

**Comment by sprunk** [comment]
Thanks.
