### ISSUE TITLE
Terraform projects not always working

### ISSUE THREAD

**Issue by Kingstad** [ZeroK-RTS/Zero-K#4312]
Following http://zero-k.info/Forum/Thread/25135
Its an issue that has been around for a long time. I never did know how to consistently recreate it.
Will try to remember to link games where this occurs:
http://zero-k.info/Battles/Detail/1056817
23:15
At bottom of the map queued sky-desolator with 3 conjurers that doesn't get the terraform it was meant to get

**Comment by Sharkgamedev** [comment]
> Following http://zero-k.info/Forum/Thread/25135
> Its an issue that has been around for a long time. I never did know how to consistently recreate it.
> Will try to remember to link games where this occurs:
> http://zero-k.info/Battles/Detail/1056817
> 23:15
> At bottom of the map queued sky-desolator with 3 conjurers that doesn't get the terraform it was meant to get

Does this have anything to do with when a previous terraform 'object' get's hidden underneath the terraformed terrain and if it wasn't previously qued unselectable?

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/109272838-88f94680-7865-11eb-8973-9bfa78a6ad5a.png)

![image](https://user-images.githubusercontent.com/1318249/109272900-9a425300-7865-11eb-9510-f39b2d7c6f60.png)

This Caretaker built the terraform for a bit, but then switched to the Caretaker nanoframe. The terraform killed itself after being ignored.

**Comment by Sharkgamedev** [comment]
> ![image](https://user-images.githubusercontent.com/1318249/109272838-88f94680-7865-11eb-8973-9bfa78a6ad5a.png)
> 
> ![image](https://user-images.githubusercontent.com/1318249/109272900-9a425300-7865-11eb-9510-f39b2d7c6f60.png)
> 
> This Caretaker built the terraform for a bit, but then switched to the Caretaker nanoframe. The terraform killed itself after being ignored.

This does not seem intuitive, that a terraform would kill itself when ignored, is there some way to signal a terraform is about to die to the user better?

**Comment by GoogleFrog** [comment]
Well they are drawn with lua now, so perhaps some pulsing when they are about to expire?

**Comment by Sharkgamedev** [comment]
> Well they are drawn with lua now, so perhaps some pulsing when they are about to expire?

Sounds good. Perhaps a separate issue should be created for this?
