### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by Sharkgamedev** [ZeroK-RTS/Zero-K#4315]
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/6055315/infolog.txt)
It's the bottom battle in the info log. Just a normal game with some terraforming and then suddenly sync errors started popping up and that was that. Not sure how it will look in the replay but after I finished building the bridge/block off on the south side of the map I clicked the builders and gave them the order to go build some mexes elsewhere and that's when it happened.
https://zero-k.info/Battles/Detail/1062712

Please note in the crash report I got it sent by force quitting and also I had tried rejoining the game at the time so the logs will reflect that unlike the one above focused only on the desync.
https://github.com/ZeroK-RTS/CrashReports/issues/38551

**Comment by Sharkgamedev** [comment]
I should mention those infologs are from the client or my secondaryflyer account as you can tell and here is a crash report from the host of the game, on my main account.  https://github.com/ZeroK-RTS/CrashReports/issues/38552

**Comment by sprunk** [comment]
Ancient engine, many desyncs fixed since. Hopefully this is one of them.
