### ISSUE TITLE
Engine Bug: Units sometimes fail to follow factory waypoint

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4317]
Sometimes units do not seem to receive orders to follow the factory waypoint. I found nothing unusual in gadget:AllowCommand, except that the CMD.MOVE commands that the engine usually issues for waypoint-following do not reach gadget:AllowCommand. This is probably an engine bug, but I am storing it here for retrieval if or when engine dev resumes.

The gameside solution is as follows. Detect the specific command queue that signifies the bug and then manually copy the queue to the unit. This commit solves the problem: https://github.com/ZeroK-RTS/Zero-K/commit/ced80d60ca28ecf1fabd44f9f643ed95a9e2e956

The issue can be reproduced with the parent of the above commit and the following replay: [20210228_164454_FolsomDamDeluxeV4_104.0.1-1544-ge1f249f maintenance.sdfz.txt](https://github.com/ZeroK-RTS/Zero-K/files/6056437/20210228_164454_FolsomDamDeluxeV4_104.0.1-1544-ge1f249f.maintenance.sdfz.txt)

Pause and do /skip328. The next Rogue to leave the factory exhibits the bug.

![image](https://user-images.githubusercontent.com/1318249/109412645-4c605300-79fd-11eb-8e5b-f26f936449de.png)

**Comment by sprunk** [comment]
The replay is two years old and from 104, but engine development resumed and there have been many pathing changes since.

Disable the gameside commit and report to engine if still happens?

**Comment by sprunk** [comment]
Workaround exists so the bug is solved -> closing. Perhaps the fix can be moved from game to engine though: #5169 (new ticket because this one is buried)
