### ISSUE TITLE
Crab "ignores" move order and curls up on hillside

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K#4318]
It seems to try to move up the hill-side while constantly curling/uncurling.

![image](https://user-images.githubusercontent.com/6383332/109859103-e540d980-7c5c-11eb-9cab-47eb59b030a0.png)
In http://zero-k.info/Battles/Detail/1064327 from minute 8:21 onwards with multiple move orders to a similar position.

**Comment by Arch-Shaman** [comment]
I suspect the 2d distance is too short so raw move just shrugs and says it's arrived? This looks to be about... 20 - 50 elmos away from what I guess?

**Comment by GoogleFrog** [comment]
I messed with Crab recently. The start/stop code is very finicky.

**Comment by GoogleFrog** [comment]
Stopped for a bit after reaching the destination then was told to move again here.
![image](https://user-images.githubusercontent.com/1318249/110079244-fa447680-7ddc-11eb-8d10-389b2c1c7c6e.png)

**Comment by GoogleFrog** [comment]
Self-cancelled move order here.
![image](https://user-images.githubusercontent.com/1318249/110079320-13e5be00-7ddd-11eb-8ae2-3b9f440db1ae.png)

**Comment by GoogleFrog** [comment]
Reissued and another self-cancel.
![image](https://user-images.githubusercontent.com/1318249/110079407-2f50c900-7ddd-11eb-92c9-be241337c620.png)

**Comment by GoogleFrog** [comment]
Unpacked then sat back down with move order.
![image](https://user-images.githubusercontent.com/1318249/110079489-4a233d80-7ddd-11eb-8a6b-86563e6d1545.png)

**Comment by GoogleFrog** [comment]
Fixed itself.
![image](https://user-images.githubusercontent.com/1318249/110079632-76d75500-7ddd-11eb-9f13-79dddba7fba2.png)

**Comment by GoogleFrog** [comment]
Cannot reproduce.

Were you using CMD.MOVE or some other ancient tech?

**Comment by DeinFreund** [comment]
> Were you using CMD.MOVE or some other ancient tech?

Not as far as I'm aware. I'm trying to stick close to stock. Raw move generally works for me with right click. This weird behavior from crab is very inconsistent, so I don't think I'd be able to reproduce it myself either. It happens just frequently enough to lose trust in the interface.

**Comment by GoogleFrog** [comment]
There was a change and possibly even a new ticket.
