### ISSUE TITLE
Nimbuses sometimes get a stroke when firing at Lotus

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4337]
Now that I've seen that one twice as well, - Nimbus sometimes stops firing after getting an attack order. Seemingly this only happens when targeting Lotus, at least from the games I've witnessed.
https://zero-k.info/Battles/Detail/1070209, ~20% runtime. Middline Nimbus gets a force-attack order on Lotus and doesn't do much of anything (doesn't fire a single shot actually).
https://zero-k.info/Battles/Detail/1055590, ~85% runtime. The attack moved Nimbus at NW corner switches target for a Lotus and stops attacking after a few shots.

**Comment by Arch-Shaman** [comment]
https://zero-k.info/Battles/Detail/1055590 may be unavailable

**Comment by Arch-Shaman** [comment]
Aimpoint seems to be out of range.
![image](https://user-images.githubusercontent.com/48730089/112246303-d2507200-8c28-11eb-813b-2a6914177cac.png)

**Comment by Arch-Shaman** [comment]
![image](https://user-images.githubusercontent.com/48730089/112246408-ff048980-8c28-11eb-8b46-c231d2d44c01.png)
unit state during this.
