### ISSUE TITLE
Reclaim issue on Desert Rumble

### ISSUE THREAD

**Issue by palimpsestate** [ZeroK-RTS/Zero-K#4338]
https://zero-k.info/Battles/Detail/1070289 - In this game I built a constructor at the start, ordered it up my ramp, and set it to reclaim. It seemed to strongly disagree with my sense of how pathing should work, walking back down my ramp and into my base to take the reclaim that I wanted . I give it move and reclaim orders two more times, the third time it decides to completely ignore my reclaim orders for two sets of reclaim and then walk to the back area of the base to reclaim the rocks I've queued for reclaiming instead of the metal+energy reclaim towards the front.

**Comment by sprunk** [comment]
Pathing issue on engine 104 -> no longer relevant
