### ISSUE TITLE
Raven (corshad) doesn't even need to target to drop bomb, unexpected by newbies!

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#434]
In this thread http://zero-k.info/Forum/Thread/10172 newbies complain how this spontaneous/knee-jerk bomb release behaviour of Raven (corshad) is difficult for them to manage.

I acknowledge that Pro player use this behaviour to their advantage (just move bomber over enemy unit). (saw this in youtube)

I don't mean to nerf Pro player, but shooting without aiming might sound weird?

**Comment by sprunk** [comment]
Close? Bombers work exactly as expected so not much can be done apart from the aforementioned widget (which noone seems to have attempted so far).
