### ISSUE TITLE
Game crashes after update v.1.9.30: "GR: Create GLContext" Errror

### ISSUE THREAD

**Issue by codmocodmo** [ZeroK-RTS/Zero-K#4341]
![image](https://user-images.githubusercontent.com/47275368/110690304-16348780-81e4-11eb-960e-6d0bca868eef.png)

After the latest update Zero-K crashes. 
I'm on Linux (Manjaro).

**Comment by codmocodmo** [comment]
After a restart the game launched normal. So it seems to be occur just sometimes...

**Comment by sprunk** [comment]
Perhaps it was just a badly deployed update? Ticket doesn't seem to have anything directly actionable.
