### ISSUE TITLE
Bombs get stuck on fight move with Smart AI enabled

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#4343]
In http://zero-k.info/Battles/Detail/1069599, all Imps leaving my factory start dancing on some spot shortly after leaving. The rally point queue is a Fight order. 

There are no enemies around to avoid, so they seem to be doing this just because.

This seems to be very similar to the way that Limpets sometimes crawl around the center of the map on Fight in Zero Wars.

Turning off the light bulb button fixes this.

**Comment by GoogleFrog** [comment]
Bombs have low LOS and fight is basically equivalent to Move as far as the engine is concerned, so always jinking is intended behaviour. Give them move commands to make them not jink. Idk how to solve that for factories as I never tell mine to Fight. If always jink is a bad default then make bombs default to no AI.

**Comment by GoogleFrog** [comment]
Looks like bombs already default to no AI.

**Comment by Anarchid** [comment]
> Bombs have low LOS and fight is basically equivalent to Move as far as the engine is concerned, so always jinking is intended behaviour. Give them move commands to make them not jink. Idk how to solve that for factories as I never tell mine to Fight. If always jink is a bad default then make bombs default to no th.

The issue is not that they jink while moving towards target, but that they enter some kind of a loop in which they jink on the same spot indefinitely, without advancing.

> Looks like bombs already default to no AI.

Aha, looks like i need to update my settings then.

**Comment by GoogleFrog** [comment]
An option of questionable utility is disabled by default. Seems fine.
