### ISSUE TITLE
Transports fail to unload

### ISSUE THREAD

**Issue by pengvado** [ZeroK-RTS/Zero-K#4347]
If I have a Charon carrying a Phantom, and tell it to unload. Charon decreases altitude until Phantom's feet are dragging on the ground... and then doesn't let go. It just hovers there at low altitude, with the unload order still in queue, but not doing it.

Fails every time for Phantom or Knight. Fails sometimes (nondeterministically?) for Felon, Placeholder, Firewalker, or Ettin. (The obvious pattern is that these are the tallest transportable unit-models.) Fails for all but the tiniest units if the unload location is close to the load location so that Charon doesn't reach cruising altitude in between.

Hercules exhibits the same bug, but with a different set of transportees. Hercules carrying Detriment fails to unload every time. Fails only sometimes for Paladin, Dante, Juggle, Grizzly, Felon, Knight, or Phantom.

"D" to force drop still works as intended.

**Comment by Licho1** [comment]
I also noticed that. Seems to be engine issue, happens with manual area unload as well

**Comment by PezzoGuy** [comment]
Don't know if it's relevant but whenever you use the Unload command, two unload waypoints are created: One where you clicked and one right above/below it.

**Comment by Arch-Shaman** [comment]
I've queued this bug for investigation.

**Comment by Arch-Shaman** [comment]
http://zero-k.info/Battles/Detail/1081014

**Comment by IndeIrae** [comment]
https://zero-k.info/Battles/Detail/1082726, closer to the endgame, Hercules drags Dante from center island to northern frontline and fails to land it properly

**Comment by floomby** [comment]
https://zero-k.info/Battles/Detail/1081014 is another one. In the middle of the game when attempting to unload a paladin. Hercules procedes to get killed cause it wont unload.
