### ISSUE TITLE
Attack-ground surface vs UW location discrepancy

### ISSUE THREAD

**Issue by pengvado** [ZeroK-RTS/Zero-K#4348]
If you give an attack-ground command and aim at water, your click is interpreted as clicking on the sea-floor. However, all of the artillery weapons for which attack-ground is useful, explode at the water-surface instead. Of course, the amount of discrepancy in targeting location depends on camera angle.

Widgets/gui_attack_aoe.lua interprets your click as being on the water-surface, thus drawing the AOE circle in the wrong location. Likewise Widgets/gui_antinuke_coverage.lua, which can greenlight a target that's actually blocked by a known antinuke.

If I wanted to change the widgets to match the current behavior of attack-ground, that would be an easy patch. But it would make more sense to change attack-ground to use water-surface, and I have no idea how to implement that.

**Comment by GoogleFrog** [comment]
The engine is responsible for this and I think it would be messy to hack around. Does your proposed behaviour make sense when you give an attack-ground command to an Archer and a Buoy? What about a Scallop? What about attack lines? Is the same done for move orders and all other orders? This would make a mixed selection of boats and amphs line-move in a disjointed way. There is more to think about with a behaviour change.

For now I think it would be best to make the offending widgets (nuke coverage etc) line up with the reality of the engine.

Perhaps there could be a depth-finder widget that draws a line from the sea floor under the cursor to the surface.
