### ISSUE TITLE
https://zero-k.info/Maps/Detail/8366 has issue with teaming up players

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4358]
For being 3rd most popular FFA map, especially for larger numbers of players, has a weird issue: seems to always team up players in pairs after crossing 8 player threshold, altho it's supposed to have 16 starting locations. Works like intended in single player, idk what the problem here is.

**Comment by sprunk** [comment]
Was tagged as 8-way in infra, fixed.
