### ISSUE TITLE
Crab stuck pathing over wreck on spiretop in B1079833

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4362]
https://youtu.be/4D7UIsOEzlk

**Comment by Arch-Shaman** [comment]
I cannot explain what this is, so @sprunk or @GoogleFrog may need to edit the title here. It looks like the crab is "stuck" issuing pathing commands repeatedly or something?

**Comment by sprunk** [comment]
As far as I can tell the pathfinder would rather try to walk via the top of the hill because flat is fast (despite it being unpathable due to the wreck there) than walk through the sides of the cliff. Probably engine.

**Comment by Arch-Shaman** [comment]
Probably right.

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/commit/c916e953735a8da87b43f9b595473fbeca39fec2

**Comment by sprunk** [comment]
Pathing on an ancient engine -> no longer relevant.
