### ISSUE TITLE
Endless terra bug

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4364]
One of the four ancient horsemen of terra unreliability. Well known occurrence, when nearly finished ~85-99% terra suddenly demands endless BP be poured into it, causing one to waste resources into the void.

**Comment by sprunk** [comment]
Replay?

**Comment by IndeIrae** [comment]
https://zero-k.info/Battles/Detail/1079834, ~60%-ish runtime iirc (you'll see a caps msg from me about scythes), me and Anar go to terra our respective Singus. Both projects get bugged terra, I notice it, Anar does not and ends up feeding something in the range of extra 1-2k to the jank gods. Visually it looks as if terrain bumps up and down, while inputted expected cost value is way over projected.

I can probs dig up more if needed, it's a pretty common thing.
