### ISSUE TITLE
Endless tera bug 2.0

### ISSUE THREAD

**Issue by IndeIrae** [ZeroK-RTS/Zero-K#4372]
https://zero-k.info/Battles/Detail/1086447, at ~35% runtime I begin digging a ditch for ~~myself~~ geo in ES corner. It stops at ~99%, after taking twice the projected cost, and begins to sip at my life force similar to #4364 (I clearly have suprlus of BP at the moment it happens). Since this was on the test build I assume the fix to the other ticket doesn't stop this case.

**Comment by GoogleFrog** [comment]
Terraform down to 91 elmos on that spot.
