### ISSUE TITLE
Artemis unable to fire.

### ISSUE THREAD

**Issue by TechAUmNu** [ZeroK-RTS/Zero-K#4375]
See replay http://zero-k.info/Battles/Detail/1087436 
about halfway through on left bottom sea. Built Artemis, but it won't fire. 

Tried all anti bait settings, wouldn't fire even if I manually targeted it.

**Comment by GoogleFrog** [comment]
The Artemis was built at height zero, and its AimFromWeapon piece is at the very bottom of the model. It thought it was aiming from underwater.

**Comment by GoogleFrog** [comment]
Fix https://github.com/ZeroK-RTS/Zero-K/commit/cd9c8fea253dee4a0b541962510c7d30ca52876a
