### ISSUE TITLE
Fix Dagger and Bolas icons

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4383]
Dagger and Bolas are Raider/Support rather than Scout/Raider. The only reason is a desire to not change the Dagger icon. Factories with two fairly normal raiders (ie Rover and Tank) follow the Scout/Raider icon scheme so Hover should be made to fit. There are probably a bunch of things that need updating to do this.

**Comment by sprunk** [comment]
6d2f8b2140370612d3e30ae592df4a0d91c6cc1d
