### ISSUE TITLE
Check selection rank complete disable

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4392]
> [raaar] settings  > interface > selection : i have unit seletion filter disabled already

Apparently the above is not sufficient to disable selection ranks.

**Comment by springraaar** [comment]
I've tested on a game with unit selection filter disabled
- drag-box select does select everything : OK
- morphed com and units keep group (possibly unrelated) : OK
- ctrl-z  after having commanders+builders+cons selected deselects builders and commander : FAIL

**Comment by GoogleFrog** [comment]
That is just how ctrl+Z behaved from 2016 to 2018. Reset your hotkeys or edit the appropriate line of zk_keys.lua.

Fixed: https://github.com/ZeroK-RTS/Zero-K/commit/e491bebbeda255319de1b994ce548452b54a59b2

Reopen if a problem is found.
