### ISSUE TITLE
Glaive gets stuck in corner of map

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4394]
https://zero-k.info/Battles/Detail/1105696

Around 14 min in there is a glaive that decides to travel along the top border of the map, getting stuck in the top left corner after a while. No commands were given or shown. Looks like it tries to chase something that is outside of the map. I marked it.
-- katastrophe, from thread.

**Comment by sprunk** [comment]
Sounds like either raw move overshoot (in which case it's #3653) or some other pathing failure (in which case it's made obsolete by being made on engine 104).
