### ISSUE TITLE
Siren brain freeze

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#4404]
At 08:57 near {5000,1000}  in [B1118036](http://zero-k.info/Battles/Detail/1118036), a Siren is briefly given a guard order on a Buoy, at which or near which time it becomes fully unresponsive. The guard order is replaced by a move order within the second and the move order is received into the unit's queue,  but the move order is not acted upon. The same happens to at least any Move, Attack and Fire orders issued subsequently. 

While in this state, the unit proceeds to drift forward at about 1/4th of its usual speed.

The condition lasts for about ten seconds, until the afflicted Siren receives enemy fire at 09:10. Unfortunately, that also causes it to be out of position, and it starts moving towards seabottom at 09:14.

The replay does not seem to log any lua error messages contemporaneous with the siren brain freeze.

**Comment by Arch-Shaman** [comment]
I presume it had some sort of command attached to it?

**Comment by sprunk** [comment]
Sounds like an engine 104 issue with movement, which makes this ticket unactionable.
