### ISSUE TITLE
Caretaker on patrol can be stuck trying to reclaim wreck that is out of range

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#4422]
when a wreck fly through the range of a caretaker on patrol [due to inertia or explosion], the caretaker is stuck on that reclaim command and will not automatically change to any other task.

**Comment by Kieldro** [comment]
ya I've seen caretakers get stuck when given reclaim command that are out of range many times

**Comment by sprunk** [comment]
#4681
