### ISSUE TITLE
AFK detection broken?

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4423]
https://discordapp.com/channels/278805140708786177/432874986064052235/853784654759198751

Dave[tB] — Today at 7:55 PM
seems like afk detection is a bit broken with this patch\
had now two games in a row that have a person afk for > 2 minutes
and not detected or units given away

cabinboy — Today at 8:16 PM
games are https://zero-k.info/Battles/Detail/1134549 and https://zero-k.info/Battles/Detail/1134557 with lordoftrolls and webfreak respectively

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/ebe5c5b410b7dbaa20a7fedc38537a5fab4040dd
