### ISSUE TITLE
Factory queue - not possible to remove queued units

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#4425]
https://i.imgur.com/UOn2rji.png

**Comment by Arch-Shaman** [comment]
I think this was intentional as a recent discovery makes it possible to do very bad things here?

**Comment by mojjj** [comment]
well nice. we lost a 110 min game because of this. could not unqueue an eos and add a quake to be able to kill terrorformed DRP. http://zero-k.info/Battles/Detail/1135225

**Comment by GoogleFrog** [comment]
I tried all combinations of modkeys and buttons and was unable to reproduce.

**Comment by mojjj** [comment]
oops. my fault. i mean the other left. the right left. the right mouse button
