### ISSUE TITLE
Allyteam handicap options

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4428]
An area of lobby options could contain options for handicaps. I think the most consistent would be something equivalent to a per-allyTeam cost multiplier. Income multiplication has the fewest cases but I don't know how to deal with rez or reclaim. Perhaps just metal income could be multiplied, or even just mex income (very simple). Modified unit costs may be the most transparent as they could be replicated on the UI. Wreck value should probably be unaffected, as should cost-derived things like target priorities.

**Comment by Licho1** [comment]
It is cleanest to the user, but if you are looking for something with least side effects, then it is metal income multiplier I think

**Comment by GoogleFrog** [comment]
Metal income including reclaim? I am unsure how to implement it for reclaim.

**Comment by Licho1** [comment]
I would just ignore reclaim

**Comment by sprunk** [comment]
Change reclaim BP?

**Comment by Arch-Shaman** [comment]
What we did in FW was flat out multiply storage, bp and income (m&e).

**Comment by GoogleFrog** [comment]
What exactly do you mean by income?

**Comment by Arch-Shaman** [comment]
All base resource generation (ie: base mex income, innate commander,
solars). Not OD.
