### ISSUE TITLE
Matchmaking queue has graphical issues

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#4435]
![image](https://user-images.githubusercontent.com/6192259/123554282-26fb1000-d777-11eb-99b5-38fe8a6951f4.png)
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/6722078/infolog.txt)

**Comment by GoogleFrog** [comment]
[f=-000001] [LuaMenuController::Reset] using menu archive "Chobby v1.9.6.2"

This is what an outdated chobby looks like.
