### ISSUE TITLE
After match chat has disappeared

### ISSUE THREAD

**Issue by danfireman** [ZeroK-RTS/Zero-K#4436]
![image](https://user-images.githubusercontent.com/6192259/123554871-1f893600-d77a-11eb-980b-73dc5cf69cdd.png)
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K/files/6722090/infolog.txt)

**Comment by Arch-Shaman** [comment]
Thank you for your report (and nice, infolog!). 
I think it should probably be a Chobby (in-game lobby) or infrastructure issue, though.

**Comment by GoogleFrog** [comment]
I'm not entirely sure why this would be caused by an outdated chobby, but it works for me with the update.

See https://github.com/ZeroK-RTS/Zero-K/issues/4435

Open a new ticket if you have trouble updating.
