### ISSUE TITLE
Nvidia gtx 970 + ultra details - aircraft jets not visible

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#444]
LUPS aircraft jets dont work on this high end card. Also white trails go missing randomly but /reload fixes trails. Jets are never visible...

**Comment by GoogleFrog** [comment]
I fixed something to do with jets being invisible for spectators. I have not noticed any invisible jets since then. Reopen with better settings etc.. if it occurs still.
