### ISSUE TITLE
Raven balance ideas

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4453]
While air is in a pretty good spot, I think it could be improved by Raven being slightly better in high density situations. At the moment Likho tends to dominate even for things that Raven should in theory be better at: sniping high value targets with more health than a Likho bomb.

Touching Raven is pretty dangerous so takes time and attention. In lieu of time and attention I am writing down a few ideas.
 - Increase based speed and increase the severity of the dive slowdown. This should make it better at penetrating defenses and bombing static targets without increasing survivability when bombing light to medium units on the fringes of AA.
 - Increase rearm time and decrease cost. Energy drain per run is 10 times rearm time so this pushes Raven later in the game when more infrastructure exists. It also buffs suicide runs, as no energy will be spent.

**Comment by Licho1** [comment]
From silly ideas, perhaps it could get "suicide attack" option with Z - basically slamming where the bomb would normally land, increasing damage significantly but losing the craft. Though there are enough suicide units in ZK to make it much fun..

Another idea could be "pre bomb" shield - basically increase survivability until it drops the bomb.

**Comment by sprunk** [comment]
Non-diving Raven happened which likely had some effect in the desired direction, but people still seem to prefer Likho.

**Comment by GoogleFrog** [comment]
I have seen a lot more Raven since dive was removed. It seems to be more reliable and have a larger niche, so I think it worked. 

Pre-bomb armour sounds like it could work for a heavy depth bomber.
