### ISSUE TITLE
Widget description issues.

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4489]
### unit_nostuck_infactory.lua

"Always move unit away from factory's build yard & `r`emove an accidental build-unit command given to unit in factory. This prevent`s` case of unit stuck in factory & to make sure unit can complete their move queue."

### unit_teleport_ai_2.lua

"(up to 600elmo, HLT range) and teleport them when it shorten`s` travel time. "
"This only appl`ies` to your unit`s` & allied beacon`s`."

### unit_jumper_jumpOverObstacle.lua

" Jumper`s` automatically jump over terrain or buildings if it shorten`s` walk time."

### unit_tree_reclaim.lua

No author.

### tipdispenser.lua

"v0.4 Teach`es` you to play the game, one tip at a time"

### map_draw_blocker.lua

"`B`locks map draws from spa`m`mers"

### gui_teamhighlight.lua

No author or description.

### ui_savegame.lua

No description.

### gui_replace_cloak_con_order.lua

"Prevents constructor accidental decloak in enemy territory by replacing Repair, Reclaim and Rez with Move. `.`\n\nNOTE:Use command menu or command hotkeys to override."
Extra period to be removed.

### gui_persistent_build_spacing.lua

"`F`ixed pre-game, added mouse wheel and previsualization options(Helwor)"

### gui_lups_stats.lua

No description.

### gui_ingame_guide.lua

No author or description.

### gui_chili_share.lua

"Press H to bring up the chili share menu."
Key is now tab, not H.

### gui_chili_resource_bars.lua

No description.

### gui_chili_economy_panel2.lua

No description.

### dbg_gadget_profiler_new.lua

No description.

### dbg_widgetprofiler.lua

No description.

### dbg_startbox_editor.lua

Bad description.

### dbg_deferred_test.lua

No author or description.

### dbg_chili_profiler.lua

No author or description.

### dbg_chili_inspector.lua

No author or description.

### gfx_lups_manager.lua

No description.

### cmd_newton_firezone.lua

"v".. (versionNum) .."Adds the Firezone command for Newtons. Allies in an area are targeted."
Space required after versionNum.

### cmd_customformations2.lua

"\n `M`ouse drag draw various command on ground."

### cmd_commandinsert.lua

"[v" .. version .. "] Allow`s` you to add command`s` into existing queue. Based on FrontInsert by jK"

### cmd_area_attack_tweak.lua

"\n• `A`utomatically filter out ground target for AA units."
Additionally, the bullet points in this aren't displayed, at least not in Alt+F11.

### unit_default_commands.lua

No author or description.

### unit_healthbars.lua

"Gives various information` ` about units in form of bars."

### unit_dynamic_avoidance_ex.lua

" Avoidance AI behaviour for constructor`s`, cloak`ers`, ground-combat unit`s` and gunships.\n\nNote: Customize the settings by Space+Click on unit-state icons."

### unit_blobshadow.lua

"`S`hows blob shadows"

### unit_showallcommands_2.lua

"Provide ZK Epicmenu with Command visibility options. Go to \255\90\255\90Setting`s`/ Interface/ Command Visibility\255\255\255\255 for options."

### unit_resurrect_congregate.lua

"Automatically send resurrected unit`s` to nearby blob of allied units. (1 Blob = 5 ground units within 300 elmo radius, Congregating range: 3000 elmo)"

### unit_oneclick_weapon.lua

No author or description.

### Other

• Some widgets have their author as "GoogleFrog", some as "Google Frog".
• camera_cofc.lua and init_start_point_remover.lua have names that overlap their checkboxes in Alt+F11.

**Comment by sprunk** [comment]
Thanks for trudging through these and spotting the issues!
