### ISSUE TITLE
Enabling the player to remove commander modules

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#4497]
The modules the player chose initially can become less useful due to the state of the battle changing and disadvantages such as speed penalties. It is impossible to build another commander too. Would you frown on a way to remove modules and get some resources back?

**Comment by GoogleFrog** [comment]
This feels like feature creep to me. Refunding could easily become something that is optimal but so tedious and minor that people don't bother with it.

**Comment by Licho1** [comment]
Yeah I woudlnt do it.

**Comment by sprunk** [comment]
Weighing in the long-term negative effects is part and parcel of choosing a module.
