### ISSUE TITLE
Building air units makes ground units nearby scatter

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4501]
Building an airplane or gunship unit seems to make units in the area clear space for them to be produced. This makes sense to get other ground units out of the way when they're created, but doesn't make sense for air units which immediately take off.

An example of this that I often find is trying to keep a funnelweb next to the airplane factory to support it with buildpower and shield, ordering the factory to produce an air unit makes the funnelweb move out of the way, displacing the shield and losing its buildpower temporarily.

**Comment by sprunk** [comment]
Bugger off radius and placement is hardcoded so would probably require engine changes or airfac remodel.

**Comment by GoogleFrog** [comment]
Sounds like a simple flag to add to the engine.
