### ISSUE TITLE
Reorder Cloaker and Adv Radar in Special tab

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#4514]
The current order of buttons in Integral Menu is:
1. 55M Radar
2. 420M Cloaker
3. 400M Adv. Radar

It seems to be like that as a leftover from times where Adv. Radar costed 500M.
Imho it would make much more sense for the order to be:
1. 55M Radar
2. 400M Adv. Radar
3. 420M Cloaker

because this way:
- buttons are in the order of increasing cost
- the two radars are together, which make sense as these are fuctionally very similar

If you approve this change I can make a PR.

**Comment by sprunk** [comment]
I've heard voices that the buffed adv radar quickly becomes a no-brainer so another solution is to just nudge it back to 425+.

**Comment by GoogleFrog** [comment]
425 is pretty un-round at such magnitudes. 440 is the next closest round number and seems fine.
