### ISSUE TITLE
/cheat /godmode enemy.selected control grouping crashes game

### ISSUE THREAD

**Issue by CodeLich** [ZeroK-RTS/Zero-K#4532]
If i enter 
/cheat
/godmode
/globallos
Then select enemy unit, and assign hotkey, for example ctrl+4, it will crash game for me ( it becomes unresponsive )

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/commit/ed5dab80bbd3146456e9dc63042d379c2a3f53d5 (not yet adopted but nothing to do here anymore)
