### ISSUE TITLE
Disarm doesn't disable radar / radar jammer / active sonar on some units

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#4533]
Some units retain full radar / radar jammer / sonar range even when disarmed.
These units are:
- athena
- cloakcon
- spidercon
- shipaa
- staticantinuke
- striderfunnelweb
- some static comms (comm_recon, comm_hunter)
- some PW buildings (pw_interception, pw_warpjammer)

On the other hand there are some units that lose radar/jammer/sonar when disarmed.
These units are:
- staticradar
- staticheavyradar
- staticsonar (unused)
- staticjammer
- cloakjammer
- planescout (Owl)
- shipcarrier
The list of these 7 units is hardcoded in unit_attributes.lua gadget, which makes the whole difference.
The list probably shouldn't exist for radar/radar jammer units as simply all of them should lose radar/jammer when disarmed.

**The situation is more complicated for sonar units.**
From the lists above these units have sonar:
- athena
- planescout (Owl)
- shipaa
- shipcarrier
- staticsonar (unused)
But apart from these, all ships, amphs, hover, comms
 (static and dynamic) have sonar too, and their sonar range remains even when unit is disabled.
 I assume this is intentional since the sonar is part of unit LOS underwater.
 While for units like Owl or Athena the sonar is an extra ability and probably should disable when unit is disabled.
 
 I will make a PR addressing the issue with radar/jammer and separately with sonars.

**Comment by CarabusX** [comment]
Added a PR to fix this: #4534

**Comment by Anarchid** [comment]
> I assume this is intentional since the sonar is part of unit LOS underwater.
While for units like Owl or Athena the sonar is an extra ability and probably should disable when unit is disabled.

Keeping in mind that sonar coverage is entirely invisible to the player, i would prefer if it was immune to disable for all units.

**Comment by CarabusX** [comment]
> Keeping in mind that sonar coverage is entirely invisible to the player, i would prefer if it was immune to disable for all units.

Sonar coverage is visible on the minimap as blue range circle when the unit is selected.

I kept disable-able sonar for Owl, Athena and (unused) Static Sonar, as the first two are air units that dont move in water so sonar is not the essential part of their los, while for Sonar Station, the sonar is the only ability it has.
Earlier the 3 exceptions were Owl, Sonar Station and Reef, but Reef was inconsistent as all ships have sonar but only Reef could have it disabled. And it felt like the Athena is missing since it us basically cloaked Owl for sonar use case.

**Comment by CarabusX** [comment]
Can be closed I think, since the PR was merged.

**Comment by sprunk** [comment]
<#sonarLives intensifies>
