### ISSUE TITLE
cloaking and jump bugs

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#454]
the game exited so i up my local replay and infolog
https://dl.dropboxusercontent.com/u/23979348/spring_static/replays/cloackererror/20141221_153503_Tumult_91.sdf
https://dl.dropboxusercontent.com/u/23979348/spring_static/replays/cloackererror/infolog.txt

problems:
--sfire's trollcom areacloker was not operating. i killed the com and rezzed it, it didnt work on me either, also morphed from 4>5 and still not working

--athena cloak was random not working, and it was not an energy issue. on sfire and me.

--jack and sumo once refused to jump. sumo remained in "atttempt to jump" position, could not move sumo or jack (replay time when defending against tank pulk near my jump factory

**Comment by sprunk** [comment]
Most likely fixed by now; infolog is full of errors related to water and refueling gadgets that had since been fixed so presumably the other issues stem from LuaRules being fried. Close and reopen if still happens?

**Comment by Anarchid** [comment]
^
