### ISSUE TITLE
/take - permanent ownership for afk-units disables rejoining players

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#457]
this overrides the 2nd com or factory plop assignment, which is done to distribute the com/fac of afk players.

the difference is, it is permanent and the units are not given back if the person is (re-)joining later. So, if you are late you cannot participate the game. 

it is scriptable and already abused with calling cyclic in short times. example at http://zero-k.info/Battles/Detail/316898.

**Comment by xponen** [comment]
I think this can be fixed by preventing unit transfer from inactive team (except if lagmonitor gadget requested it).

This won't block unit sharing because player who can share unit is active player (not inactive).

**Comment by xponen** [comment]
closed because fixed by blocking /take
