### ISSUE TITLE
COFC camera problems

### ISSUE THREAD

**Issue by VoltWarrior** [ZeroK-RTS/Zero-K#4576]
Dear all developers of Zero-K !
I write this comment to report issues of COF camera usage. There are bugs and also limited features that you can fix or add them in. For example, when I activated the 3rd person tracking view function of the COF camera, it allowed me to look up and down but I couldn't rotate the camera around the player. Sometimes when I exited and then entered again it bugged out of the map and I saw only background although I tried to press Ctrl+Tab and switch to default camera, the solution that I could do was exit the game and enter again. I think the COF camera is a best alternative camera for people who want to play RTS on 3rd person view or also content creators, so if there is an update patch to fix these problems, the COF will be a best function replace the rotatable overhead camera
I hope that my comment will be read and you can reply to me on Discord
Sincerely
Player Volt_Warrior

**Comment by GoogleFrog** [comment]
I'm sorry but the COFC code scares me and I don't really support it. Perhaps @dvr333 has something to say?

**Comment by dvr333** [comment]
I didn't even realize this was a feature, and honestly I'm not sure why it's here other than a likely experiment from when FPS camera was a thing. Honestly, this feature should be removed from COFC and made into its own camera mode, as the method of controlling both the camera and the game is completely different in a 3rd-person over-the-shoulder perspective than in a top-down perspective

**Comment by sprunk** [comment]
I think it was for making hype-building cinematics that look nothing like usual gameplay, like here from 0:24s onwards https://www.youtube.com/watch?v=t_Ga5F4onc8

**Comment by VoltWarrior** [comment]
@GoogleFrog  @sprunk  @dvr333 To be honest, I'm a new Vietnamese RTS content creator (particularly is Youtuber) and I really love your game. I am using some functions that I asked in Discord to make a movie from this game, and then I found COFC is a good function for making my scenes more cinematic, but I understand that the COFC is being less used in normal game, so I will try to adapt to these problems and do my best as possible to make many epic scences, the COFC update just like a waste of your time and also effort. But if there was an update, me and other content creators could feel it more professional. So in general, I think that you can fix it or not depend on your choices, just focus on updating the balance of the game and also more unit. I am also hoping that more units are made and it will go with epic highlights, too.

**Comment by dvr333** [comment]
For what it's worth, the standard unit tracking function does allow you to rotate the camera around freely. It doesn't do the tracking from behind such that the unit changing direction changes the camera direction, but it would let you have more flexibility over the camera while tracking a unit than the 3rd person tracking feature.

**Comment by GoogleFrog** [comment]
Ah, I saw this

> I think the COF camera is a best alternative camera for people who want to play RTS on 3rd person view or also content creators, so if there is an update patch to fix these problems, the COF will be a best function replace the rotatable overhead camera

and thought that you needed to argue that obscure COFC functions are good for playing the game for this ticket to get off the ground.

>  I am using some functions that I asked in Discord to make a movie from this game, and then I found COFC is a good function for making my scenes more cinematic, but I understand that the COFC is being less used in normal game, so I will try to adapt to these problems and do my best as possible to make many epic scences

This sidesteps the need for any such argument and makes things much simpler. I don't want to hunt down bugs in COFC or bring it up to the level of polish required for it to replace the main camera. I don't want to mess with things in ways that may break it for existing users. But I'm happy to crudely merge or hack off bits of its functionality provided they are gated behind increasingly obscure options. Making rotation happen while tracking units sounds exactly like this type of thing.

Here you go, the new options can be distinguished via this commit: https://github.com/ZeroK-RTS/Zero-K/commit/1bbd6c12057624a8850fa22af6dcad0648d63d73

You can download the latest version of the camera and install it by following this: http://zero-k.info/mediawiki/index.php?title=Widget_Configuration#Using_custom_widgets

**Comment by VoltWarrior** [comment]
@GoogleFrog thank you for the advice, I really appreciate.

**Comment by sprunk** [comment]
Assuming the new options worked alright.
