### ISSUE TITLE
I get a victory once I start a bot match 

### ISSUE THREAD

**Issue by eleKai** [ZeroK-RTS/Zero-K#4596]
Hi all,

I'm using the portable .exe file on Windows OS,

At first, I launched the installation from the .exe file in Downloads directory, 
Then I wanted to move it to another, I moved the game files file by file to another folder, 
And I think the problem starts here.. 

I want to know what happened exactly to let others with the same issue get the right solution,

For me, the solution that solved this is by creating new folder, move the .exe portable file only, and launch it to reinstall all

**Comment by GoogleFrog** [comment]
This makes sense to me. If you manually copied `configversions.json` across but didn't copy AI then the lobby would have thought that the AIs were deployed when they were not. If you try to start an AI game without the AIs deployed then it will crash.

**Comment by GoogleFrog** [comment]
I'm going to assume that was the cause.
