### ISSUE TITLE
Understand an OKP error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4603]
As far as I can tell, frames cannot have an element inserted that lacks fullDamage. Perhaps the gadget is sent nil fullDamage from somewhere, but then surely OKP would crash earlier. Also I fired all the units that appeared in the attached replay and none had nil fullDamage at the start of CheckBlockCommon. 

`[f=0028641] Error: [LuaUnitScript::RawRunCallIn][LuaRules::BlockShot] error=1 trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_overkill_prevention.l..."]:241: attempt to perform arithmetic on local 'dataFullDamage' (a nil value)`

http://zero-k.info/Battles/Detail/1284564

Workaround: https://github.com/ZeroK-RTS/Zero-K/commit/f393614cf94ed554e21a3c5cb3050b1b2960a53a

**Comment by sprunk** [comment]
Claymore has two technical weapons and only one of them used the broken constant which is presumably why naive testing did not reveal the bug.

**Comment by GoogleFrog** [comment]
Claymore seemed to be the cause.
