### ISSUE TITLE
Tank treads sometimes disappear completely after some point in game

### ISSUE THREAD

**Issue by Dave-tB** [ZeroK-RTS/Zero-K#4610]
This results in only seeing the black, criss-crossing lines of the unit outline widget instead.  This is especially visible on Ettin and kodachi, but seems to happen on other tanks (ogre) as well (only it is hidden by their model geometry).

![screen00145](https://user-images.githubusercontent.com/90851364/150829093-91e22f33-eb06-477b-927e-163f72ac3b72.png)
![screen00146](https://user-images.githubusercontent.com/90851364/150829114-6d44cf4b-a09b-4026-be69-62472a51927b.png)
![screen00148](https://user-images.githubusercontent.com/90851364/150829343-e5f27af4-6559-4b48-ab06-ed34552e81c6.png)

**Comment by GoogleFrog** [comment]
Report on engine.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/151324475-5835fb62-41d5-4208-885a-03a35d9b3945.png)

This plane plate lost its pad.

**Comment by GoogleFrog** [comment]
![Uploading image.png…]()
Without outlines.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/151324875-19566b04-d7bf-415b-812b-93baec2f2701.png)
Treads disappear immediately on unit creation.

**Comment by GoogleFrog** [comment]
Before:
![image](https://user-images.githubusercontent.com/1318249/151325006-b0c7ec6b-2f54-4dca-9237-15c2ec315280.png)

After:
![image](https://user-images.githubusercontent.com/1318249/151325030-1efab271-11b5-4be5-a42f-a285f57429a5.png)

**Comment by sprunk** [comment]
These look like things that are "animated" by having overlapping pieces with different textures and iterating over them via `Hide` and `Show`. Seems like the hide works but the show doesn't.

**Comment by GoogleFrog** [comment]
Yes.

**Comment by sprunk** [comment]
beyond-all-reason/spring@085299e24cf4d63c51f05568d2ee72986c8ca372
