### ISSUE TITLE
Game launches windowed at the wrong resolution when user is alt-tabbed

### ISSUE THREAD

**Issue by Dave-tB** [ZeroK-RTS/Zero-K#4611]
On Windowed mode (lobby) and fullscreen (ingame):

When watching a replay from website, either lobby goes fullscreen or game launches as windowed.

**Comment by GoogleFrog** [comment]
Cannot reproduce.

**Comment by Dave-tB** [comment]
Found why and when this was happening:

If a game starts while I have the lobby in the background or minimized, the game starts in a window, at the same resolution as the lobby.  This is annoying because I have to fix my UI, and if I am a player I have to exit and re-enter the game.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/issues/4697
