### ISSUE TITLE
Stop Lance from hovering up and down to decrease risk of friendly fire

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#4636]
When Lances hover up and down, the aimpoint might be at its' peak when starting to fire, and while the hover descends, the beam might hit a unit that was previously not in Line of Fire.

8 second video:
https://youtu.be/h7fPVS3Drz0
13 minute video:
https://youtu.be/jgzC0aZ_3NU

**Comment by SteelBlueZK** [comment]
Poor fix that bends the model in a way it probably shouldn't bend. 
https://cdn.discordapp.com/attachments/296254538363568130/945074728849268756/2022-02-20_16-49-15.mp4
https://cdn.discordapp.com/attachments/296254538363568130/945074152618987540/2022-02-20_16-45-59.mp4

**Comment by SteelBlueZK** [comment]
From discord conversation:

https://cdn.discordapp.com/attachments/296254538363568130/945117317229056040/Screenshot_20220221-023702_One_UI_Home.jpg

Anarchid: What if, when aiming or firing, this piece compensates
[7:39 PM] Anarchid: or even all the time
[7:39 PM] Anarchid: body moves up 1 elmo, turret moves down 1 elmo
[7:40 PM] Anarchid: like suspension

**Comment by GoogleFrog** [comment]
I thought about this a while ago and hit a similar impasse:
- Hovercraft should hover.
- The model lacks the piece hierarchy to manipulate its neck in a satisfactory way.

How about checking whether the following looks ridiculous: Interrupt Lance hover when it fires to make it hover upwards not downwards. If its below its usual max height then simply hover towards max height. When it reaches max height make it hover upwards slowly. With the right amount of smoothing these movements will probably like fine.

**Comment by SteelBlueZK** [comment]
https://user-images.githubusercontent.com/8924181/154908497-0c32e862-9297-4d3e-9b3b-3b7944cbc488.mp4

The 'undesirable' thing about this hoverarty3 fix is that it lance will more often than not stop moving at maximum height in the bobble animation. But lance will **always** be ascending or not moving vertically relative to it's ground height when firing mahlazer.
