### ISSUE TITLE
Right click mex placement cancellation is inconsistent with regular cancelling

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#4645]
When you mouse over a metal extraction point(for a context sensitive mex placement), hold right mouse button, and then hold left mouse button, the mex placement command is not cancelled as it is for other context sensitive mouse commands. If the right mouse button is released before the left mouse button, the mex build command will go through which is inconsistent with other context sensitive mouse commands.
The standard for context sensitive commands is that they are cancelled as soon as the left button is pressed and not on release.
![bild](https://user-images.githubusercontent.com/1059579/156572968-313f0380-0fa5-497e-8768-96d92c2a59e2.png)

**Comment by GoogleFrog** [comment]
Cannot reproduce. There appears to be an inconsistency with right click mex and other context commands, but I don't see anything like what you describe. Write the steps of the entire process as a list of dot points, then comment on the step which you think demonstrates a bug.

**Comment by Godde** [comment]
I was probably confused about this issue due to some inconsisties described here:
https://github.com/ZeroK-RTS/Zero-K/issues/4647
Closing this issue.
