### ISSUE TITLE
Pressing shift removes factory's orders

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4652]
1. Order factory to guard a unit
2. Shift press a hotkey to produce 5 units
3. Factory removes its guard order
4. Newly produced units have no orders

**Comment by sprunk** [comment]
F10 / Settings / Unit Behaviour / Shift removes constructor guard

**Comment by GoogleFrog** [comment]
"Shift removes constructor guard" should not apply to factories. The widget is just meant to unstick constructors which people think they gave a shift queue to.
