### ISSUE TITLE
GL4 outlines give features outlines when near units

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4655]
![image](https://user-images.githubusercontent.com/1318249/159104089-d6a1c012-d165-4d99-915d-e44d64dec6fb.png)

See the trees here.

**Comment by Beherith** [comment]
You could write a material index into the misctex buffer in cus and test for that, when testing for units :)

**Comment by GoogleFrog** [comment]
> You could write a material index into the misctex buffer in cus and test for that, when testing for units :)

I don't know what this means.
