### ISSUE TITLE
Minimap does not show selection box 

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#4666]
1) enable minimap selection (left click select)
2) try to select units via minimap

Selection works, but selection box is not drawn over minimap.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/162552086-1ae2ad15-f4fd-4eda-9b04-8eeb621e797a.png)

I see a faint black box. Persists with luaui and luarules disabled. I suspect an engine regression which screws the GL state prior to drawing the box.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/162552136-9505f090-1e39-43cf-8d71-b9e450185d97.png)

Map marker notification is also black.

**Comment by sprunk** [comment]
Seems fixed now (both with LuaUI enabled and disabled).
