### ISSUE TITLE
Some units randomly have alternate skins

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4669]
In this game: https://zero-k.info/Battles/Detail/1340511

I saw Firewalker look like this:
![image](https://user-images.githubusercontent.com/1318249/162601783-dcba344f-7054-43d1-b5c2-784c61450204.png)

Dave and Niartoloc saw Jack look like this:
![image](https://user-images.githubusercontent.com/1318249/162601791-efcb9456-96b0-4cbe-9f90-826c5cd52418.png)

Perhaps it is a skinning experiment from ages ago.

**Comment by Arch-Shaman** [comment]
http://zero-k.info/Battles/Detail/1348062

![image](https://user-images.githubusercontent.com/48730089/164080531-142ee9b2-3440-481b-b8a7-08ccb2a3ea7e.png)

**Comment by Arch-Shaman** [comment]
![image](https://user-images.githubusercontent.com/48730089/164532021-05c8416d-cbee-46d9-af00-aae2838de2e8.png)
Encountered today in http://zero-k.info/Battles/Detail/1349021

**Comment by GoogleFrog** [comment]
Can you reproduce it?

**Comment by Porkch0p** [comment]
The first locust built at game start in https://zero-k.info/Battles/Detail/1351624 looks like this for me. It's solar-powered.
![spring 2022-04-24 13-02-22-43](https://user-images.githubusercontent.com/49832728/164992452-5db1ca4c-c581-483d-b1d1-367faff085a5.png)

**Comment by adams164** [comment]
I am also seeing this locust mis-texture:
![image](https://user-images.githubusercontent.com/868774/167993844-a23cf54d-d0cd-45f8-93fd-7bfa326b7e4b.png)
Shows up unpredictably, but repeatable in replays such as https://zero-k.info/Battles/Detail/1361061

**Comment by SteelBlueZK** [comment]
More from discord:
https://cdn.discordapp.com/attachments/278805140708786177/991272911556063242/unknown.png
unknown look
https://cdn.discordapp.com/attachments/278805140708786177/991404519541973103/unknown.png
unknown look
https://cdn.discordapp.com/attachments/296254538363568130/992541644308090890/unknown.png
this might be the same colors of the strike skin renegade
https://cdn.discordapp.com/attachments/278805140708786177/992771870682259517/unknown.png
unknown
https://cdn.discordapp.com/attachments/278805140708786177/993901943690903552/unknown.png
the same solar texture
https://cdn.discordapp.com/attachments/278805140708786177/996183947820138566/unknown.png
unknown
https://cdn.discordapp.com/attachments/278805140708786177/998371307550949436/unknown.png
looks like the same unknown from above
https://cdn.discordapp.com/attachments/432874986064052235/999884729572675694/unknown.png
definately support skin zebra
https://cdn.discordapp.com/attachments/432874986064052235/1000612729440178297/unknown.png
definately  looks like guardian skin steel to me
https://cdn.discordapp.com/attachments/296254538363568130/1004134525217034270/unknown.png
strike com chitin

**Comment by GoogleFrog** [comment]
I think this was fixed https://github.com/ZeroK-RTS/Zero-K/commit/3daf8f5fae1cb14e795a8ecb88feb577778fb32c

**Comment by SteelBlueZK** [comment]
https://cdn.discordapp.com/attachments/432874986064052235/1011107403938398278/unknown.png

Jack texture, very obvious by the underside texture showing

**Comment by sprunk** [comment]
There hasn't been a stable.
