### ISSUE TITLE
Minimap not visible and black box in center of screen

### ISSUE THREAD

**Issue by Heldenstein-0** [ZeroK-RTS/Zero-K#4677]
Edit: infolog deleted

Also pressing Menu (F10) or Lobby (F11) buttons on top right of the screen does not open the corresponding menus.
Disabling the minimap panel corrects this behaviour.

**Comment by Arch-Shaman** [comment]
[infolog(1).txt](https://github.com/ZeroK-RTS/Zero-K/files/8512992/infolog.1.txt)

**Comment by Porkch0p** [comment]
It seems like it's probably an issue showing up on high resolution screens. If you've got Game Interface Scale set to something higher than 100, I would try resetting it to 100 until the next update is pushed, it may resolve the minimap problems.

**Comment by Porkch0p** [comment]
Reported to be fixed by downloading 1.10.4.1 stable.

**Comment by sprunk** [comment]
Assuming the above is true given there was no feedback otherwise.
