### ISSUE TITLE
cmd_customformations2 & gui_selection_hierarchy crash constantly since 1.10.4.0

### ISSUE THREAD

**Issue by versus666** [ZeroK-RTS/Zero-K#4680]
[t=00:05:48.850207][f=0003664] [cawidgets.lua] Error: Error in CommandsChanged(): [string "LuaUI/Widgets/gui_selection_hierarchy.lua"]:376: attempt to index field 'params' (a nil value)

[t=00:05:48.850252][f=0003664] [cawidgets.lua] Error: Removed widget: Selection Hierarchy

[t=00:05:48.850957][f=0003664] [cawidgets.lua] Error: Error in CommandsChanged(): [string "LuaUI/Widgets/cmd_customformations2.lua"]:996: attempt to index field 'params' (a nil value)

[t=00:05:48.850985][f=0003664] [cawidgets.lua] Error: Removed widget: CustomFormations2

Also the error :
[KeyBindings] Warning: Bind: could not parse key: Any+rightparen 

(Any+rightparen ,  no typo) seem related to cmd_customformations2.

**Comment by amnykon** [comment]
It's not crashing for me. What units are you selecting? How do I reproduce this issue?

**Comment by GoogleFrog** [comment]
It looks like something is editing entries of widgetHandler.customCommands, which propagates back into the widgets that add custom commands.

**Comment by versus666** [comment]
You got it !
My bad; I use a quite old widget that just at the end reset the state commands, so just commenting these few lines fixed the problem without apparent adverse effect. But I'm puzzled, why did that problem manifested itself far after gui_selection_hierarchy & cmd_customformations2 were modified ?
