### ISSUE TITLE
Setting a unit state too fast using zk_keys.lua in multiplayer results in toggling behaviour

### ISSUE THREAD

**Issue by Godde** [ZeroK-RTS/Zero-K#4683]
When I play a hosted multiplayer battle, if I double press the hotkey to "Hold fire"/"firesstate 0", it toggles the behaviour rather than always setting it to the desired state. This does not happen in a non-hosted skirmish singleplayer game.
If I bind the command in the ingame menu, it works as desired and I don't get the toggling and I can press the hotkey how many times and how fast I want without it toggling back and forth.
It seems binding specific states to hotkeys is somewhat broken if you don't bind them through the menu but try to use zk_keys.lua directly.

In the zk_keys.lua, these lines can be found:

{"firestate 0", "M+q"},

{"epic_layout_handler_fire_state:_set_hold_fire", "k"}

https://pastebin.com/HnL1GkZ7

**Comment by GoogleFrog** [comment]
I recall this being a result of instant state toggling, and fixing it by putting a bit of code between state setting hotkeys and the engine. If binds via epicmenu work then I don't see that there is a bug to fix. Editing zk_keys.lua directly is not necessarily supported, and it looks like by editing the hotkeys in epicmenu you've discovered the action string that works correctly.
