### ISSUE TITLE
[crash] Game expects internet connection to start

### ISSUE THREAD

**Issue by CitrusWire** [ZeroK-RTS/Zero-K#4689]
I'm using a build from the website on Windows, and as soon as I start it I get:
![image](https://user-images.githubusercontent.com/72134064/167469720-67e14854-b397-476e-ad71-f101038704b2.png)

Problem is, the game doesn't have internet access. So after about I minute I get:

![image](https://user-images.githubusercontent.com/72134064/167469689-829107a5-e1bc-43dc-9271-b1078b9965b3.png)

I press "ok" and the game quits, making it impossible to start the game. While this may not technically be a crash, from a user perspective it's the same thing.

**Comment by Licho1** [comment]
For offline gaming please use either steam (set it to offline mode after download) or version from itch. Game cannot start without critical files.

**Comment by CitrusWire** [comment]
> For offline gaming please use either steam (set it to offline mode after download) or version from itch. Game cannot start without critical files.

I'm confused. I used the "portable downloader" from: https://zero-k.info/Download - Everything has already been downloaded, yet the game still won't start without an internet connection. It *has* all the files locally (9383 files totally 1.36 GB), but it still refuses to start without doing the internet thing.
