### ISSUE TITLE
luaerror in unit_proximity_targetting

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4704]
[t=00:32:35.715537][f=0063510] [Game::ClientReadNet][LOGMSG] sender="hoaqhieu08" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_proximity_targetting...."]:55: attempt to perform arithmetic on local 'x2' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:55: in function 'DistanceSq'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:79: in function 'GetTargetToClosest'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:122: in function 'funcToApply'
	[string "LuaRules/Gadgets/Include/IterableMap.lua"]:131: in function 'Apply'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:169: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:967: in function <[string "LuaRules/gadgets.lua"]:965>
	(tail call): ?"

See: https://zero-k.info/Battles/Detail/1376633 (I believe this is related to the recent starlight targeting pr)

**Comment by danfireman** [comment]
So there's a unit which is in line of sight but has a nil position coordinate? 🤯

**Comment by johnsonjsyuen** [comment]
![image](https://user-images.githubusercontent.com/44350915/171065821-51ab379a-b519-412f-a785-118174221f39.png)

**Comment by mushroomraider** [comment]
here is the error from my log:


[t=02:28:47.772173][f=0046596] [Game::ClientReadNet][LOGMSG] sender="Xamoguitar" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_proximity_targetting...."]:55: attempt to perform arithmetic on local 'x2' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:55: in function 'DistanceSq'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:79: in function 'GetTargetToClosest'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:122: in function 'funcToApply'
	[string "LuaRules/Gadgets/Include/IterableMap.lua"]:131: in function 'Apply'
	[string "LuaRules/Gadgets/unit_proximity_targetting...."]:169: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:967: in function <[string "LuaRules/gadgets.lua"]:965>

**Comment by danfireman** [comment]
The error occurs around 35:13 when the starlight reaches a random force fire point:
![image](https://user-images.githubusercontent.com/6192259/171290149-ee804b8f-5b4f-4b4f-8ac6-6d2392f64901.png)

I suspect this bertha on the plains to be the culprit instead:
![image](https://user-images.githubusercontent.com/6192259/171290392-393f9a1b-f624-47b1-ab4e-a9275e9e51db.png)
