### ISSUE TITLE
Remove self-destruct blocker?

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K#4722]
At the moment the self-destruct blocker in LuaRules/Gadgets/unit_self_destruct.lua auto-resigns the player if (assuming I am reading it correctly) they attempt to delete more than 80% of their existing units (plus some other condition which seems like it is generally going to be met). 

Especially since it resigns you without warning, this occasionally results in behaviour that is unintended and unrecoverable by the user. For example a dedicated cloaked-Snitch player could quite plausibly run into this. A weirder recent example: in http://zero-k.info/Battles/Detail/1399819? richardjam13 attempted to self-D a bunch of tidals (so that the enemy would not discover the nearby area cloaker) and was quite perplexed when this resulted in an instant resignation.

Improvements would be a confirmation of some kind, or just tightening the resignation criteria.

Alternatively it could just be removed. As per the final comment in the gadget:
> Perhaps it would be good to just block the self-D command but not resign (forcing veterans to learn the new methods, which would ultimately allow us to remove the block as well). ]]

This particular piece of muscle memory is probably a lot less common than it was in 2009.

**Comment by sprunk** [comment]
It no longer resigns so the main task here (prevent unexpected resign) is done.

After 3aefd76eac2517c73bb30bd80c015a14c5075424 OTA veterans will also no longer have the muscle memory of Ctrl+AD for resign so maybe it's fine to remove completely? If not then the ticket can be closed.

**Comment by GoogleFrog** [comment]
Old hotkeys still exist, and I don't see any need to remove it.
