### ISSUE TITLE
Helberd cannot be built above underwater cliffs by Athena

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K#4738]
Despite being a hovercraft.

**Comment by sprunk** [comment]
I can't reproduce with just water.

I can reproduce when there is a slope on the seafloor that the Halberd wouldn't be able to path on if there was no water. Engine issue.

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/pull/334

**Comment by sprunk** [comment]
Fixed in engine.
