### ISSUE TITLE
targeting underwater Amph factory

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#4746]
https://zero-k.info/Battles/Detail/1423046

player notices halbird will target an amph factory that is underwater even when it has no chance of hitting it.

the simplest fix is to make modelradius smaller, because maximum targetable negative y = -modelradius - 6

However, projectiles do not explode at y=0, they explode when y < 0 meaning some amount of water penetration will happen, as well as AOE being fully effective through water. A crusader will want to fire at a sunken amph factory that is deeper than the absolute maximum a halberd can hit, but AFAIK all units must target the same place.
<img src="https://cdn.discordapp.com/attachments/278908415756206080/1009176547757916260/unknown.png">

In this clip the angle of the projectile affects if it hits the factory or not

https://streamable.com/lx46er

modelradius = "42"

This feels like a decision of design.

**Comment by sprunk** [comment]
28494b4d9f7a8c8c9e8100f9082fa0d1846e08df
