### ISSUE TITLE
Feature request: Anti-nuke overlay similar to overdrive overlay

### ISSUE THREAD

**Issue by SteelBlueZK** [ZeroK-RTS/Zero-K#4750]
Tinyspider points out it's difficult to tell antinuke capeabliities by enemies just by the thin grey lines. Suggests to make a clear boarder of entire antinuke range the way you can tell the boarder of your overdrive.

**Comment by sprunk** [comment]
Is this insufficient? Works with a nuke nanoframe.
![image](https://user-images.githubusercontent.com/2573076/185532459-c384a1ff-6204-405e-8a88-f83a1b4a5fd6.png)

Maybe the white border could just be EXTRA THICC like so?
![image](https://user-images.githubusercontent.com/2573076/185533015-7b82c393-22e0-4f53-ade9-8186aefdce1d.png)

**Comment by GoogleFrog** [comment]
Thicker sounds good. The internal coverage of antinukes is important so I don't want to lose the information of where the overlaps are.
