### ISSUE TITLE
Lichos dev diary thread page=1 every other thread page=2144

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#476]
Hey,
click on ZeroK Forums every thread link has page=2144 in the params except:
http://zero-k.info/Forum/Thread/6692?page=1

this thread is sticky too, maybe it has to do something with that

**Comment by ArchShaman** [comment]
This belongs under Zero-K Infrastructure.

**Comment by Jamanno** [comment]
Yeah, I cannot move it...

**Comment by ArchShaman** [comment]
I made an issue in the correct area. You can close this one now.

**Comment by Anarchid** [comment]
Closed.
