### ISSUE TITLE
Consider making right click on unit in factory cause a guard order on the factory

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4762]
This could make assisting less confusing for new players. Shift-queuing a command already removes guard orders on factories from the start of constructors queues, so the guard would not get in the way.

**Comment by Licho1** [comment]
Why would right click on unit cause guard order on factory (different unit)? Or you mean to prevent people right clicking on unit rather than factory itself? 
Don't like that, I sometimes give such order on unit that is still being constructed.

**Comment by sprunk** [comment]
The problem being solved here is that newbies sometimes don't realize that they are clicking the unit being built instead of factory - maybe they don't realize unit is "really there" and not just an animation, or maybe they just click a factory without precision and happen to click the unit by accident.

**Comment by GoogleFrog** [comment]
Having to click off-center on a factory to assist it is a bit unintuitive.

**Comment by Licho1** [comment]
I would prefer better visualisation of "target" rather than removal of useful feature (chaining commands on uncomplete unit).

**Comment by sprunk** [comment]
Some other approaches that don't remove the useful feature:
 * option in settings, default to "guard factory"? Then newbs get the intuitive behaviour but people can still enable "guard unit" once they need it.
 * right-clicking the unit defaults to guarding the factory, unless there is already a "guard factory" order, then it targets the unit? Essentially, require double-click to target the unit.
 * right-clicking the unit defaults to guarding the factory, press G (or click the Guard command on the panel) to manually target the unit?

**Comment by GoogleFrog** [comment]
I recall shift-clicking elsewhere after a guard command on a factory cancelling the guard command. This would retain the repair-then-move on behaviour automatically.
