### ISSUE TITLE
Outline renders over healthbar

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4770]
![image](https://user-images.githubusercontent.com/2573076/199857552-88b878e2-4239-4642-a3e8-cca2ae6584ee.png)

**Comment by sprunk** [comment]
Somewhat related: #4254

**Comment by GoogleFrog** [comment]
I'm not so sure I dislike this.

**Comment by sprunk** [comment]
I think I mostly dislike that it can obscure the text but don't mind obscuring the bar.
