### ISSUE TITLE
Some odd minimap bug

### ISSUE THREAD

**Issue by alexpyattaev** [ZeroK-RTS/Zero-K#4776]
Hi! I'm having some silly minimap issue where it only shows units and buildings in the upper right corner of the minimap. Mexes are highlighted everywhere. Latest video driver amdgpu for Linux Kernel 6.1
Attached are a couple of examples from different maps.
![screen00030](https://user-images.githubusercontent.com/5932526/202138961-00818d38-9c46-47ab-85b0-a4150af79882.png)
![screen00028](https://user-images.githubusercontent.com/5932526/202138985-57945caa-7fe6-4be2-877c-74e082db4d0b.png)

**Comment by lhog** [comment]
AMD GPU specific issue.
Fixed in upstream engine, not much ZK can do besides updating.

**Comment by alexpyattaev** [comment]
Good to know! Thanks!
