### ISSUE TITLE
Why does autogroups only allow some buildings?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4779]
@Licho1 do you have any comment on this? https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_auto_group.lua#L21

Autogroups seems to only group missile silo missiles, no other structures. I would remove this limitation (as the default) but I don't use autogroups so I am hesitant to do so. I see why the limitation may have existed in the past, but I think we now have two things solving some of the issues that may have existed.
- Units no longer automatically inherit the group of their factory (by default).
- Selection ranks make filtering out irrelevant structures much easier.

**Comment by sprunk** [comment]
989f4218362a19fbf91eeee4f6ba7865ef2b059f

As far as I can tell the widget originally only supported units (perhaps necessitated by `widget:UnitFromFactory` or waypoint logic, or perhaps because there just aren't really any good autogroupable buildings) and then you added the limited selection of missiles.

**Comment by GoogleFrog** [comment]
Ah. Why not UnitFinished instead of UnitFromFactrory? This will miss striders too right? I suppose the widget widget was written before Strider Hub.

**Comment by sprunk** [comment]
It already supports striders via `UnitFinished`. I think the `UnitFromFactory` part could be straightforwardly dropped under existing constraints as long as the `UnitFinished` part handles regular factory units.

As far as I can tell the main differences between `UnitFinished` and `UnitFromFactory`, other than who receives them, are:
 * `UnitFromFactory` receives some sort of parameter that lets it distinguish whether the unit's order queue was its own or inherited from factory. Autogroups don't care where the queue comes from though.
 * there's a modrule where a unit can stay in factory after being built, to get repaired to full health if it was damaged during construction. In that case `UnitFromFactory` is called when the unit finishes the repair, not the build. Irrelevant for ZK.

**Comment by Licho1** [comment]
Yes I think it should be switched to UnitFinished and yes it ignores striders.
I see no reason why to restrict autogroup only to some buildings, if people want to use it for buildings.

Regarding logic, it should put unit to group after its initial order queue is done (order queue added before unit is completed). It should also not add unit to group if it was already assigned to different group.
