### ISSUE TITLE
new/updated holiday backgrounds

### ISSUE THREAD

**Issue by Kingstad** [ZeroK-RTS/Zero-K#4792]
More intense halloween background:
![zerok_battle_HALLOWEEN v 0 95 Darker yet darker jpg](https://user-images.githubusercontent.com/25781794/206885095-a0d299e4-154d-4d68-a356-273ef5065029.jpg)
Winter background (separate to christmas one):
![zerok_battle_WINTER v0 93 jpg](https://user-images.githubusercontent.com/25781794/206885123-2b00b466-51d3-4f78-b42d-8e17fca2c426.jpg)
New years background. relatively saturated as it might be online the shortest?:
![zerok_battle_New Years eve v0 8 medium saturation](https://user-images.githubusercontent.com/25781794/206885128-b2d9518a-bdff-4772-b969-473ad68538a5.jpg)

**Comment by GoogleFrog** [comment]
What are the dates?

**Comment by Kingstad** [comment]
oh that's up to me? I suppose the most controversial would be the winter one as its not universal, but winter here would be from December 1 to february 28 [1/12 - 28/2] (or we could say January 30 if that seems too much). Christmas one is currently set at [18/12 - 31/12], fine. New years might be December 30-January 7 [30/12 - 7/1].
Idk if halloween could be for all of spooktober?

**Comment by GoogleFrog** [comment]
I am dubious of making a long lasting seasonal background, and I don't know what is wrong with existing halloween.

**Comment by Kingstad** [comment]
this is just darker halloween with RTX turned on, I think it looks better but I know you prefer lower contrasts for a background. If winter gets used at all idk what period of time makes sense if its up for only a short while, perhaps December 1 - December 18?

**Comment by sprunk** [comment]
January for generic winter? December already has Christmas, and February is filled with other seasonal things that somewhat remove the winter mood regardless of whether they would make appropriate lobby backgrounds (valentines, carnival)

**Comment by Kingstad** [comment]
woah where can I go for february carnivals? Anyway then after new year background is out its 3 weeks of winter background before january is over, is that sufficiently short? It's fine by me at any rate
