### ISSUE TITLE
Commander range thoughts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4793]
Long ranged commanders still seem to be a problem, in that they put commanders outside their role (tanky/riot) and are reasonably effective. Stacking range can result in a commander that does a significant number of things better than Grizzly.

The tricky thing with range is that its power is non-linear. There are a lot of high DPS units up to around 400 range, so more range than this is a big power jump. At 500 range the commander comfortably outranges LLT and many skirmishers. Beyond 500 range there isn't much value to be had until the commander starts outranging Stinger and long ranged skirmishers/supports at 650 range. So I don't think a commander having 500 instead of 600 range is a significant loss of power. Most of the power comes from getting to 500. My guess is that, if someone calculated the in-practice DPS of various units, there would be a sharp dropoff across these boundaries for similar weapon types.

Here are some units compared to three morphs of strike commander.
<html><body>
<google-sheets-html-origin>

Name | Cost | Health | Range | DPS | Speed | Health/Cost | DPS/cost
-- | -- | -- | -- | -- | -- | -- | --
Grizzly | 2000 | 8400 | 600 | 250 | 45 | 4.200 | 0.125
Phantom | 750 | 560 | 700 | 88.3 | 42 | 0.747 | 0.118
Fencer | 145 | 530 | 600 | 52.2 | 0 | 3.655 | 0.360
Moderator | 240 | 480 | 420 | 46 | 57 | 2.000 | 0.192
  |   |   |   |   |   |   |  
Cheap strike | 1550 | 5200 | 429 | 288 | 42 | 3.355 | 0.186
Mid strike | 2200 | 5800 | 503 | 288 | 42 | 2.636 | 0.131
Top strike | 2900 | 6400 | 528 | 228 | 44 | 2.207 | 0.079

</body>
</html>
Cheap has four range and one speed module. Mid has seven range and one speed. Top has eight range and three speed. They each have 2x beamlaser. Mid seems the most interesting.

Compared to Grizzly, the mid cost commander is a bit more expensive, slightly slower, has a bit less health, has 500 instead of 600 range, and slightly more DPS/cost. This would already be questionable, since a commander shouldn't be doing approximately well as units. However, Grizzly has a lot less DPS in practice. I commented on range to raaar and he said that continuous fire isn't a benefit since it doesn't scale, that if you make a few Grizzlies it is mitigated. But on reflection this isn't true. Grizzly overkils significantly against most targets. There is no way it is using more than 2/3rds of its damage, and I would not be surprised if it only used half its damage, on average. With this estimation, the mid cost commander has more than twice the DPS of Grizzly.

Fencer and Moderator also have precise long ranged damage. Fencer has Grizzly range and 3x the on-paper DPS/cost, and avoids overkill nicely, but pays for it by being light and unable to move while firing. Moderator has significant DPS/cost too, but it has 10s reload and doesn't outrange LLT.

I would be quite happy if the ability to outrange LLT were relegated to specialised weapons with clear drawbacks, such as Rocket Launcher and Missile Launcher. This implies a hefty range module nerf. There are a few options.
- Range module +7.5% -> 4% makes beam laser cap out at 435 range. This is a small number though and might make range module too specialised.
- Range module could give a flat bonus rather than percentage. This would make it more useful with low ranged weapons. For example, it could give +15 range (current gives +24.75 for beam laser) to make beam laser cap out at 450. This would let riot cannon reach 405 range though, which could be concerning. 405 range isn't quite skirmisher-level, but it takes a bit of leeway to outrange something.
- Some sort of hybrid, which seems terrible but may end up being a good middle ground. For example +2%,+8 would give beam laser a limit of 446, and riot cannot 394. Barely seems worth the complexity.
- Reduce the maximum number of range modules. This was suggested by raaar but surely he didn't mean to do so without a buff to compensate. Still, reducing the modules alongside a full-stack nerf would make each module feel better. However, this makes long ranged commanders happen earlier in games, and it is inconsistent. I could get behind reducing all module limits to 6 though, with some buffs to compensate many of them. Even 6 of the current range modules caps beamlaser at 478 range. I would like to reduce the maximum speed commanders can reach though.
- Reduce beamlaser range. I would rather not do this, I think it works well with the early game and has good interactions with riots.
- Give range module some massive penalty. Perhaps it could reduce damage, but it's damage would have to go down a lot to be relevant.

**Comment by GoogleFrog** [comment]
This ended up very discussion-y so I made a thread http://zero-k.info/Forum/Thread/35938

**Comment by sprunk** [comment]
002dffd31945e0e617b5e385eeb3b71d41c02c67, ed81130f4facaaaf956fe1a5a78137cdb4439870 et al
