### ISSUE TITLE
Auto-groups feedback

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4804]
* ~~apparently persistence across games can be surprising. Add a checkbox in options? Should probably still default to persist because usually your habits stay the same and factories follow similar role archetype rosters.~~ Checkbox already exists. Perhaps the feature was just discovered by accident, gotta ask.
 * there was a claim that setting autogroup on some units also sets them on others without meaning to, but I heard this second-hand. This is mostly a reminder to myself to dig further.

**Comment by Licho1** [comment]
I dont think this is true. I am using autogroup all the time and never had it applied to unselected unit types.

**Comment by sprunk** [comment]
Yes, I also think something else happened (maybe mistakenly had more units selected?). I'll try to get the guy to reproduce.

**Comment by sprunk** [comment]
I didn't manage to get any feedback and I assume this was just a mistake on the reporter's part.
