### ISSUE TITLE
Claymore on Fight can get stuck on sea mexes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4805]
I had a game where my Claymores were stuck a bit out of range of sea mexes.

**Comment by sprunk** [comment]
Managed to reproduce 2 different cases:
 * fighting a sea mex from sea at the edge of the range leaves the Claymore just not shooting.
 * fighting a sea mex from land makes Claymore use the sea version of its weapon, which is dropped and not hurled (making it likely to get stuck on land) and which has less ability to bounce/slide across land (making it possible to explode prematurely via some sort of expiration).

http://zero-k.info/Battles/Detail/1540370
