### ISSUE TITLE
Retreat feedback

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4810]
Currently the gap between 30% and 65% states is fairly awkward. A bunch of suggestions were made:

 * add a 50% state. This could just be added in the straightforward way. I'd be somewhat wary of bloat but 50% is a very sensible value.
 * add some way to let people customize these values. For example, a ton of retreat states (for example at 5%, 10%, 15% etc), then use the skip/hide mechanism that hides Roam and Return Fire so that all but the current default three (or four with 50%) are hidden. People can then modify their set if they want custom values. Sounds hacky though. Keep in mind these can't be customised so easily because retreat is synced.

**Comment by sprunk** [comment]
More user feedback: asking for an option for units to stay at retreat point.

Implementationally the feature is trivial (make the move command not inserted but given in the non-shift way that overrides the whole queue), the difficulty is that retreat is synced so it would probably have to be a unit state (bad, clutter). Perhaps that is good behaviour to just apply without an option though.

**Comment by GoogleFrog** [comment]
The state toggle palette is quite limited. Wouldn't an extra state cause us to run out of colours? Extra states also seems like too much bloat. I wouldn't mind just shifting 30% to 40%. Perhaps 99% should be 95% instead too.

**Comment by sprunk** [comment]
Duplicate of #5249
