### ISSUE TITLE
Use animated cegs

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4812]
Has anyone looked into this yet?

Forb linked this: https://www.saschawillems.de/creations/explosion-texture-generator/

Apparently animated ceg is used via `animParams = [xTiles, yTiles, animLength in game frames]`. The last value can be variable, eg `[4,4,10 r5]`.

**Comment by sprunk** [comment]
Precedent for fire seems to exist so now it's just a matter of finding good use cases and copypasting the CEG def. 85cebc30f9f296895f76cd0955a6fb63ef902f6e
