### ISSUE TITLE
Modoption for extra commanders

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4814]
Groups of friends want to play team games with uneven teams (say 3v4). They use custom rooms because they want to control who is on which team, but they would also like the smaller team to get an extra comm (the request was to make uneven team games as even as possible).

This sounds like a good opportunity for a modoption (under Start) to spawn extra comms, like in team rooms. It doesn't really matter who gets the comm (they can share it around), so give it to the highest ranked player as per normal. I am a bit concerned that the existing extra comm system is server-side. The gadget that spawns extra comms would have to check whether there is any server-side extra comm business, and if not, then check the modoption and figure out its own extra comms. The modoption could even have a state to ignore the server-side comms (so the options would be off, autodetect, on).

**Comment by Licho1** [comment]
since custom goes through server server can also add it (it knows the modoptions as well)
