### ISSUE TITLE
Late-game Performance Drops from Strider Weapons

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K#4842]
Tested on an AMD CPU, AMD GPU, Linux (Steam Deck)

Sim Speed and FPS plummets if a small number of striders continuously fire their primary weapons. The effect is visible in late-game replays and 1v1 vs Null AI. 

Performance temporarily recovers when the Lua garbage collector runs, then rapidly declines if still in combat.

[Debug overlay showing with dantes firing](https://imgur.com/a/hTJckns)
[Infolog for steam deck hardware](https://pastebin.com/matanKAd)

Known units affected: **Dante** (3 at once), **Scorpion** (also 3), **Detriment** (2)
Massed groups of Pyro and Scorcher seem unaffected.

FPS is reduced from an otherwise capped 60 into the single digits.

_**_Tweaking Garbage Collector settings to Higher Stability_**_ in both [GC Rate](https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/configs/gameConfig/zk/settingsMenu.lua#L1253) dropdown boxes removes this effect for up to 9 dantes at once. This may be more of a workaround than a fix though.

**Comment by GoogleFrog** [comment]
Before.
![image](https://user-images.githubusercontent.com/1318249/226148289-702facfd-1691-45e2-8bef-15315764e16f.png)

After.
![image](https://user-images.githubusercontent.com/1318249/226148301-27aa5737-a4e6-4f4e-a792-d2a1eea89f9d.png)

**Comment by GoogleFrog** [comment]
Try it out now. I will also tweak the GC settings.

**Comment by Porkch0p** [comment]
Retested with newest version. Spawned in 9 dante/scorp/detri, and it's looking good. Sim speed and FPS remaining stable with recommended GC.

**Comment by GoogleFrog** [comment]
Thanks.

**Comment by Porkch0p** [comment]
One more unit spotted - the problem with sim speed is also happening when a commander equipped with dual Machine Guns enters combat. Nimbus and Stardust seem unaffected.
