### ISSUE TITLE
Contrast Adaptive Sharpen with UI scaling blacks out part of the screen.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4850]
I have heard reports of CAS causing part of the screen to be black when used with UI scaling. Any ideas @badosu ?

**Comment by badosu** [comment]
Hm, I'm unaware of this issue. I'll take a look at it when I can, thank you for reporting!

The steps are: finding and increasing scaling option on ZK, enabling CAS, correct?
