### ISSUE TITLE
Units Lose Ability to "Personal Cloak" due to bug with new queueing system

### ISSUE THREAD

**Issue by Dave-tB** [ZeroK-RTS/Zero-K#4858]
Steps to reproduce:
1. build a personal cloak unit under an area cloak
2. move unit out of area cloak before it actually cloaks (while in queue maybe?) 
result: unit loses ability to cloak!

![image](https://user-images.githubusercontent.com/90851364/228392253-087b5e6e-ac0b-424a-8830-d54f0c6a3cc1.png)

**Comment by GoogleFrog** [comment]
Looks like https://github.com/ZeroK-RTS/Zero-K/commit/cddf9d70ecdc7784731eb4d3f30fa78a8197f5a0 already fixed it.

Also note that personal cloak units don't interact with the queue.
