### ISSUE TITLE
Modoption for whether spectators can global chat.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#486]
This modoption would control whether players can see spectator chat and chat relayed from Springie. It would have 3 options; specs can chat, specs cannot chat and autodetect (the default) which would stop chat in FFA (at least). This would probably be best implemented in cawidgets.lua. Perhaps Springie integration would be best for the relay chat part of the option. The default chat widgets should properly indicate to spectators whether the players will see what they say.

**Comment by Skasi** [comment]
Fixed by https://github.com/ZeroK-RTS/Zero-K/commit/3395893e0fde796451ab93a614e669d42557873a?
