### ISSUE TITLE
detailtex2.bmp is missing from bitmaps

### ISSUE THREAD

**Issue by Dave-tB** [ZeroK-RTS/Zero-K#4860]
Resources.lua is supposed to have a fallback for maps that don't specify a detailtex.  It references a "detailtex2.bmp" but that is missing from bitmaps.  Some gpus will not be able to render map textures without this.  It could be a plain greyscale image or something like this that many maps use:

![image](https://user-images.githubusercontent.com/90851364/229268819-3bdd7a26-55ef-470c-bc98-deb9475ff30b.png)

**Comment by GoogleFrog** [comment]
Sounds fine, PR it in?

**Comment by sprunk** [comment]
Is it really missing? It's in basecontent. https://github.com/beyond-all-reason/spring/blob/BAR105/cont/base/bitmaps/bitmaps/detailtex2.bmp

If engine isn't picking it up perhaps that's some VFS bug?

**Comment by Dave-tB** [comment]
huh, BAR doesn't have the issue, but they have their own detailtex2 in bitmaps

**Comment by Dave-tB** [comment]
![image](https://user-images.githubusercontent.com/90851364/229304518-9869cb44-4ad2-4713-9232-80db0a02ec09.png)

It's an engine bug that is fixed in 1544.
