### ISSUE TITLE
Reported missile silo queue weirdness

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4884]
> if you want to try to replicate it, here's what makes it happen to me: first you fill up all 4 slots of the missile silo. then you turn on missile queue and queue up at least 3 different types of missiles. then wait a moment. for me this makes them get shuffled around for some reason

**Comment by sprunk** [comment]
This is because a filled silo just drops build orders. With repeat they get back to the queue though, so the queue just cycles (otherwise it gets emptied). Requiring 3 types is probably because the rate of the cycling aligns with the queue panel refresh rate in a sort of stroboscopic effect.

**Comment by GoogleFrog** [comment]
Oh, well dropping orders is bad. It seems solvable via not setting the factory to be "open" if there isn't space.
