### ISSUE TITLE
Commshare luaerrors

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#4893]
[t=00:55:54.286227][f=0010901] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/engine_compat.lua"]:197: attempt to concatenate local 'playerID' (a nil value)
stack traceback:
	[string "LuaRules/engine_compat.lua"]:197: in function 'spSetPlayerRulesParam'
	[string "LuaRules/Gadgets/game_share_mode.lua"]:511: in function 'DisposePlayer'
	[string "LuaRules/Gadgets/game_share_mode.lua"]:620: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:984: in function <[string "LuaRules/gadgets.lua"]:982>
	(tail call): ?

**Comment by Arch-Shaman** [comment]
#4894 attempted fix -> Feedback wanted.

**Comment by sprunk** [comment]
Assuming fixed, will reopen if there's issues after all
