### ISSUE TITLE
Bug: Unit disable -> containing factory useless

### ISSUE THREAD

**Issue by dennistruemper** [ZeroK-RTS/Zero-K#4897]
Hi, thanks for your work on this game.

I do not want this bug to be lost inside the crash report issues, and it is not a crash report, so I will link it here.
[https://github.com/ZeroK-RTS/CrashReports/issues/65670](https://github.com/ZeroK-RTS/CrashReports/issues/65670)

Seems like the Lua stack trace might help. The file pointing to seems to be redisigned recently. Maybe @sprunk is intrested in this report?

My friends and I like to play against AI, but on a big map it might be a good idea to disaple puppy to prevent hundreds of useless extra units. This is how we found this bug.

Thanks a lot,
Dennis

**Comment by dennistruemper** [comment]
That was fast, thank you a lot @sprunk

**Comment by sprunk** [comment]
cheers m8
