### ISSUE TITLE
Think about the Lua memory modrule

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4911]
There's a recently added modrule, `system.LuaAllocLimit`, that controls Lua memory allocation pool (in megabytes, default 1536 MB). Shaman has put this in control of a modoption in FW and claims it brings great performance benefits (which makes some sense, a lot of Lua perf cost is GC which just won't run if there's plenty free space left).

Some questions:
 * ~~change default? Shaman changed the default to 2560 MB in FW, presumably if this was troublesome then he would have heard about crashes from potatos etc.~~  0cf618ea6b4c1dae10c5397b5a2d8992af53f092
 * give people some control over it? Ideally this would just be a springsetting that everybody could tweak locally, a modrule sounds fairly silly (perhaps it's just a default?). Check the engine and talk them into making it a springsetting if it isn't already I guess. Making the modrule controllable by a modoption sounds bad (people could troll potato nubs or just OOM themselves, but also it's just an obscure technical thing that people would either not find or cargo cult) so I don't think it would be a good idea.

**Comment by GoogleFrog** [comment]
What does BAR do? The higher limit sounds fine.

**Comment by GoogleFrog** [comment]
FW has a lot more lua than ZK afaik. Will a larger size make GC take longer? I guess we can try the setting and check feedback.

**Comment by sprunk** [comment]
Seems to be no complaints, idk if there's much reason to go even higher. Perhaps the better route would be to tweak GC engine-side not to even run if there's still lots of memory left in absolute (non-%) terms.
