### ISSUE TITLE
Add UnitEnteredSubmerged and UnitLeftSubmerged callins

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4916]
I want a version  of UnitEnteredWater and UnitLeftWater that triggers when a units radius becomes completely submerged.

Cloak and shield gadgets both hack this together in an ugly way: https://github.com/ZeroK-RTS/Zero-K/commit/6bcbf2fa74bcb31ee1f6e0a067d52ebd70a29b95

A nicer method would involve splitting this out to an API widget. An even nicer method would be to put these callins in the engine directly.

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/pull/843

**Comment by sprunk** [comment]
Callin merged to engine. #4924 seems to be about incorporating it into gameside code.
