### ISSUE TITLE
Nobody understands the selection volume code

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4923]
Cloakbot factory has the following selection volume.
```
  selectionVolumeOffsets        = [[0 0 10]],
  selectionVolumeScales         = [[104 50 136]],
  selectionVolumeType           = [[box]],
```

Shieldbot factory has the following selection volume.
```
  selectionVolumeOffsets        = [[0 0 14]],
  selectionVolumeScales         = [[80 50 80]],
  selectionVolumeType           = [[box]],
```
I used VISUALIZE_SELECTION_VOLUME in `unitdefs_posts` to visualise the volumes, and verified them by mousing over them.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/a7c8cca3-9fba-48a3-9eab-a1a6f1fac3f6)

The shieldbot factory volume is wider than the cloaky volume. What is going on. It works for now, but I doubt anyone knows why, which means we don't know that it won't randomly stop working in the future. There is some processing happening somewhere apparently, but I didn't find it.

**Comment by sprunk** [comment]
Units without an explicit selection volume have it set to (colvol * multiplier). This multiplier is also applying to explicit selection volumes. The default multiplier for buildings is 1.35 (which is why shield grows to be larger than cloakyfac), but cloaky fac has it overridden to 1.
