### ISSUE TITLE
Constructors sit around failing to find a path

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4925]
North edge of this game. Starts after skip 551. http://zero-k.info/Battles/Detail/1647991?

Doesn't seem to happen with luarules disabled. It is as if they fail to receive their move goal from the raw move gadget. The engine seems to replicate a lot of the raw move gadget so perhaps it is becoming obsolete.

**Comment by GoogleFrog** [comment]
```
-- Debug
local oldSetMoveGoal = Spring.SetUnitMoveGoal
function Spring.SetUnitMoveGoal(unitID, x, y, z, radius, speed, raw)
	oldSetMoveGoal(unitID, x, y, z, radius, speed, raw)
	if unitID == 3744 then
		Spring.MarkerAddPoint(x, y, z, ((raw and "r") or "") .. (radius or 0))
		Spring.Echo("SetGoal", unitID, x, y, z, radius, speed, raw)
	end
end

local oldClearUnitGoal = Spring.ClearUnitGoal
function Spring.ClearUnitGoal(unitID)
	if Spring.GetGameFrame() < 550*30 or unitID ~= 3744 then
		oldClearUnitGoal(unitID)
	end
	if unitID == 3744 then
		Spring.Echo("ClearGoal", unitID)
	end
end
```

I ran the game locally with the above. The unitID is one of the units that fails and the frame is the frame a second or so before the issue.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/4ee46ba4-5249-4ebf-8984-cc13cf424e9a)

It looks like the move goal is issued correctly but the units don't move. It isn't raw.

**Comment by GoogleFrog** [comment]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/e48cef02-d382-4e0e-aa9a-0d4962e53da9)
After a few seconds the gadget issues an order nearby in an attempt to unstick the unit. This is expected behaviour for the gadget given its detected that the unit is stuck.

**Comment by GoogleFrog** [comment]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/7922eade-d431-4200-834d-afc516c15db2)
It tries to move to the location from a few different spots but never finds a path.

**Comment by GoogleFrog** [comment]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/0d78e9e2-aa26-48ce-bc33-6a32c968daa0)
I think it is caused by the random map. http://zero-k.info/Maps/Detail/61184

The bug is triggered by using non-raw move to an impassable location. To make the gadget give such an order there has to be a gap in the impassibility, otherwise the gadget would just send the unit to the closest edge of the impassible region. The unmodified terrain of the random map is a flat at something like -100 height. I believe the commander is able to path while the cloaky constructor can't because the commander is amphibious, so the -100 height was pathable for it.

Movement works fine for unmodified non-random maps with a similar test.

**Comment by marcushutchings** [comment]
> ![image](https://user-images.githubusercontent.com/1318249/244919098-0d78e9e2-aa26-48ce-bc33-6a32c968daa0.png) I think it is caused by the random map. http://zero-k.info/Maps/Detail/61184
> 
> The bug is triggered by using non-raw move to an impassable location. To make the gadget give such an order there has to be a gap in the impassibility, otherwise the gadget would just send the unit to the closest edge of the impassible region. The unmodified terrain of the random map is a flat at something like -100 height. I believe the commander is able to path while the cloaky constructor can't because the commander is amphibious, so the -100 height was pathable for it.
> 
> Movement works fine for unmodified non-random maps with a similar test.

Precisely where on the map and at what time in the replay does this example of the issue occur?

**Comment by GoogleFrog** [comment]
[20230611_213702_Random Plateaus v1_105.1.1-1774-g5e966db BAR105.sdfz.txt](https://github.com/ZeroK-RTS/Zero-K/files/11715782/20230611_213702_Random.Plateaus.v1_105.1.1-1774-g5e966db.BAR105.sdfz.txt)

Sure, it is very easy to reproduce.
- Find a cliff.
- Spawn a cloakcon somewhere around the bottom.
- Spawn a factorycloak_dead somewhere around the top.
- Tell the cloakcon to move to the debri.

As far as I can tell it reproduces with basically any unit and source of blocking. It can be reproduced by lining up two cliffs and telling the unit to walk into the second one.

**Comment by sprunk** [comment]
Apparently fixed by https://github.com/beyond-all-reason/spring/commit/6e72d021ec54726c9cb0333cbfb7165e9f43ef4f
