### ISSUE TITLE
eco panel has negative bars during wait for com-spawn (v1.3.1.3)

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#493]
![zk negative res bar](https://cloud.githubusercontent.com/assets/3044855/5676468/903eba0e-97d6-11e4-932e-c3a4f5edb650.png)

v1.3.1.3 and test-8781-26fd234 with spring 91.0

gui_chili_economy_panel2.lua

There is some another way how it can happen during more normal situation (changing to spec or something, not sure) but this is easiest to reproduce:

-Start game
-click "Close" on commander choice screen
-wait
-storage bars go negative during the wait for default commander to spawn

**Comment by GoogleFrog** [comment]
Cannot reproduce. Could you give your graphics details because it could be a bug in cutting the rectangle for the skin.

Could you also find out what the real resource values are when this happens?

**Comment by knorker** [comment]
No idea how to get my "graphics details" (engine, lua, drivers, whatever) in one easy way and do not have spring dev sdd bla setup to figure out more.

With /resbars:

![zk negative res bar 2](https://cloud.githubusercontent.com/assets/3044855/5676740/46fe7be0-97db-11e4-93ef-d8223fd8f820.png)

For me it reproduces in replay too: http://zero-k.info/Battles/Detail/321614
During the period where it says "Type !force to start blabla" bars are correct at zero.
After game starts it is negative until commander appears.
