### ISSUE TITLE
shield keep playing "being hit animation" even after they stop being hit

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K#4944]
shield keep playing "being hit animation" even after they stop being hit
![20230623100326_1](https://github.com/ZeroK-RTS/Zero-K/assets/14219158/e01e9e16-32fe-49df-bb64-a431a9c5d67f)

**Comment by sprunk** [comment]
I believe this was fixed by c0210077d48c560d8093c49ceb6b55244720cb61 but a replay link would be good.
