### ISSUE TITLE
Consider `wupget:Initialize(*allUnits*)`

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4955]
Many wupgets iterate over all existing units on `/lua reload`. Perhaps the wupget handler could do a single `Spring.GetAllUnits` call and pass this table to all initializing wupgets so they don't have to do this on their own?

**Comment by sprunk** [comment]
Here's some obvious benefits and downsides.
```diff
++ teaches newbie modders writing wupgets (via the presence of the arg hinting that it is there for a reason) that it may be a good idea to handle existing units
+ marginal (idk, measure!) speed-up for rare use cases such as loading a save game (LuaUI only), disabling LuaUI when catching up, and possibly reloading during development.
-- it requires talking to other games since otherwise ZK diverges.
- is a new standard that people will need to adhere to if it is going to be useful, which is cognitive clutter.
```
It would require easy but extensive changes, ideally in most spring games, and it's hard to tell how much of a benefit it would really be. I think it may be too mana-inefficient at this point to try and convince other games (and engine basecontent) to inflict a change like this to their wupget handlers, but idk.

**Comment by GoogleFrog** [comment]
The downsides only occur if you think widgets are portable between games. In practise they aren't due to the different includes and ways we handle settings.

**Comment by sprunk** [comment]
I don't think portability is binary and I think it's good not to move towards the world where it's closer to the "not portable at all" world as opposed to the "essentially portable but you need to change a handful of lines".

**Comment by sprunk** [comment]
Engine development is now in a state where this needn't be done by ZK.

**Comment by GoogleFrog** [comment]
Also another downside, what if a unit is created in Initialize?
