### ISSUE TITLE
GetPlayerRulesParam seems to be missing from luaUI.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4970]
See https://github.com/ZeroK-RTS/Zero-K/commit/f4e7392a4944993bf30845687d0225a37342b168

Check and make engine report.

**Comment by sprunk** [comment]
Why make a report if you can push to master? https://github.com/beyond-all-reason/spring/commit/436a0ef7a2b8da46ad9e347a5e4c1ff33bd3af9d
