### ISSUE TITLE
Game Isn't Functioning Or Working

### ISSUE THREAD

**Issue by Michal0899** [ZeroK-RTS/Zero-K#4974]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/114314122/a92c926f-3dbf-4351-ac98-ec06fc126e55)

game isn't working at all for me

This Screenshot is from Campign Singleplayer 

tried reinstalling the game and validating game files but didn't help to fix this problem

**Comment by GoogleFrog** [comment]
What fixed it?
