### ISSUE TITLE
Unit def modding: exit to chobby on parse failure

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#4984]
Unit def parsing crashes on failure. This is done on purpose for visibility. But, newbie modders use Chobby instead of direct spring.exe so a unit def parsing failure involves a lot of overhead in setting up a battle again. Make it so parse failures are handled gracefully and, for example, you just get a pop-up with some explanation text and "exit to chobby" button immediately on load instead.

**Comment by GoogleFrog** [comment]
This is possible?

**Comment by sprunk** [comment]
Which "this"? The commit exists so what I wanted is possible thus, but it's something of a hack.
