### ISSUE TITLE
Capture in campaign no longer lets the player build their own unlocks

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4994]
http://zero-k.info/Forum/Post/260130#260130

- Play the Dominatrix mission.
- Capture the Rover factory just to the north of the start.
- Attempt to build a Dominatrix.

Attempting to build the Domi after disabling luarules and luaui doesn't do anything, so it seems to be a new engine bug or change in behaviour. Building a Ravager at least queues it with luarules and luaui disabled.

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/commit/a2035c74fc93199d4daa5370523a27dda86082a3
