### ISSUE TITLE
Implement new Likho model

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5018]
Latest version: 
[likho2023-RC4.zip](https://github.com/ZeroK-RTS/Zero-K/files/12779075/likho2023-RC4.zip)

Feedback goes to `brunocb` in #modelling on Discord

**Comment by GoogleFrog** [comment]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/c6e05b93-ee74-46f8-b34d-b1824415de7f)

I tried putting some files in some likely places and made up a lua for the dae. It's invisible (see mouseoever highlight) and the script crashes. 

The fact that it's dae means I won't be able to fiddle with it to fix anything that goes wrong.

**Comment by sprunk** [comment]
Feedback happens in #5164 so this ticket seems redundant.
