### ISSUE TITLE
A combination of setting & widget can cause "Spring: Fatal Error: unable to allocate memory"

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#504]
Couldn't spend time to debug at the moment (maybe later),
but will just paste config:

http://pastebin.com/cyJwu8cZ zk_data.lua
http://pastebin.com/it8tZR94 zk_order.lua

I knew its the settings because the problem disappear when I delete the config.

**Comment by GoogleFrog** [comment]
Remove the non-default enabled widgets?

**Comment by xponen** [comment]
after some timely elimination process:

the cause is the font size setting. "9" or "10" (for Pro_console and old Chili Chat) is the magic number for Spring fatal crash.

But when I put it as decimal (eg: "9.25" or "10.25") it won't crash. I'll try make all Font slider to apply decimal number to fix this.
