### ISSUE TITLE
Consider keeping kestrel/eclipse for mods

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5056]
Consider putting the new bombers under new defs, mods (+ carrier mission?) may be using the old planes.

**Comment by GoogleFrog** [comment]
As a duplicate file or a replacement?
- Kestrel barely changed functionally. The model changes are backwards compatible.
- Eclipse was non-functional when I found it, so any mod will already have a new unitdef for it.

**Comment by sprunk** [comment]
Sounds good.
