### ISSUE TITLE
Lua error in unit_refuel_pad_handler

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K#5066]
[t=01:45:33.223310][f=0039684] [Game::ClientReadNet][LOGMSG] sender="Shaman" string="[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_refuel_pad_handler.lua"]:605: [string "LuaRules/Gadgets/unit_attributes.lua"]:317: attempt to perform arithmetic on field 'origMaxRudder' (a nil value)
stack traceback:
	[C]: in function 'assert'
	[string "LuaRules/Gadgets/unit_refuel_pad_handler.lua"]:605: in function 'UpdateCoroutines'
	[string "LuaRules/Gadgets/unit_refuel_pad_handler.lua"]:610: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:989: in function <[string "LuaRules/gadgets.lua"]:987>
	(tail call): ?"

**Comment by GoogleFrog** [comment]
A replay would be good, but I can blindfix probably.
