### ISSUE TITLE
Claymore's unit AI positions itself too far to shoot when attacking underwater targets

### ISSUE THREAD

**Issue by Lukas321321** [ZeroK-RTS/Zero-K#5068]
To reproduce, spawn a stationary enemy unit on the seafloor of a deep body of water. When issued an attack command to hit this structure, the Claymore will position itself so that the enemy structure is just outside of its range, making it unable to hit the target without being manually commanded to move in closer. I have not been able to reproduce the issue consistently - the unit will sometimes position itself correctly and sometimes too far out, though it appears to be less common in shallower water. Attached is a replay demonstrating the issue.
[claymoreAIproblem.zip](https://github.com/ZeroK-RTS/Zero-K/files/13411852/claymoreAIproblem.zip)

**Comment by GoogleFrog** [comment]
How deep, what map?

**Comment by Lukas321321** [comment]
> How deep, what map?

not sure. it's not consistent. i was able to recreate it by spawning an energy pylon in the southeastern corner of aurelian and having the claymore attack it, though sometimes it happens and sometimes it doesn't
