### ISSUE TITLE
All Cegs are black squares

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5081]
![image](https://github.com/ZeroK-RTS/Zero-K/assets/1318249/bb6783f3-6ca1-4a07-96f9-8446a3166571)

I have 

MaxTextureAtlasSizeX = 2048
MaxTextureAtlasSizeY = 2048

in springsettings

**Comment by Anarchid** [comment]
Likely user error? ZK-chobby sets [4096](https://github.com/search?q=repo%3AZeroK-RTS%2FChobby%20MaxTextureAtlasSizeX&type=code) for these settings as far as i can tell.

**Comment by Anarchid** [comment]
Huh, it seems to also be nil (=engine default) on my machine, where the animated sprite works. This could be OS differences.

But it also means the setting was deleted at some point.

**Comment by Anarchid** [comment]
Cause of deletion: 4096 is the [default](https://github.com/beyond-all-reason/spring/blob/7202e6ac31df0da708539dabfcc358d0f581cba7/rts/Rendering/Textures/TextureAtlas.cpp#L22) in Recoil for a while. 

Having it at 2k implies an older engine, if it's not an explicit setting.

**Comment by Anarchid** [comment]
https://github.com/ZeroK-RTS/Chobby/pull/874 should make this easier to not get 2k when switching to engines with worse defaults. 

That said, it seems like non-engine-hopping non-dev users would not be affected by this.
