### ISSUE TITLE
Jump range display ceases to function in unknown circumstances

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#509]
See title. A Lua error message is displayed on the debug console but I am currently unable to impart the content. My knowledge of recent changes is possibly insufficient so a recent patch may have made this report superfluous.

**Comment by GoogleFrog** [comment]
Post the content when you can

**Comment by sprunk** [comment]
The ticket contains zero useful information and some changes have been made to the jump UI meanwhile. Close?

**Comment by Skasi** [comment]
> My knowledge of recent changes is possibly insufficient so a recent patch may have made this report superfluous.

Probably fixed by https://github.com/ZeroK-RTS/Zero-K/commit/c488b8b8e8117f79311a78f49286ab34cab331f3 then? (patch 40 days prior)
