### ISSUE TITLE
ReplayCamera: Optionally disable the blue rectangle that tells you what it is doing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5094]

**Comment by moreginger** [comment]
You can. It's supposed to default to off. Something went wrong with merge?

https://github.com/ZeroK-RTS/Zero-K/blob/b18660feea8191065a5d55960b763d56d7c28c02/LuaUI/Widgets/camera_replaycam.lua#L88

**Comment by GoogleFrog** [comment]
I mean the blue transparent chili element (at least I hope it is chili) that says things like "Lets get an overview of the battle".

**Comment by sprunk** [comment]
f7bfe30795f2ae99444ade694392fb21294792e7
