### ISSUE TITLE
ReplayCamera: Optionally disable LOS

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5095]
It seems to force disable LOS at the moment. That is confusing since other bits of settings control LOS. Perhaps it could link in, or at least be a toggle so people are aware of it.

**Comment by moreginger** [comment]
I'll remove this, I think it's better to let it be controlled externally.

**Comment by sprunk** [comment]
18176078f3304d2236888392a77bf8528dc59c91
