### ISSUE TITLE
Check json upgrade for perf

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5101]
BAR recently upgraded the lua json library for perf reasons. Investigate (what version do we use, are there gains with the version BAR picked, are there problems with the even newer version they explicitly didn't use) and apply if it looks good.

beyond-all-reason/Beyond-All-Reason#2459

**Comment by GoogleFrog** [comment]
The big improvement would be in chobby since it jsons the lobby messages. I don't know what json we have in ZK itself, especially outside of loading.

**Comment by Beherith** [comment]
If its the same one that was used by chobby, then its an absolute garbage creation hog.

**Comment by GoogleFrog** [comment]
It's the same file and the chance is meant to be a noop externally, so isn't this easy?
