### ISSUE TITLE
Shutdown of Initial-Queue for spec in pre-game might be uninformed

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#511]
Just noticed it in News-post.

Initial-Queue also display for spectator. This is what we saw in Shadowfury's Youtube video. 

https://github.com/ZeroK-RTS/Zero-K/commit/641620ad6849306b85e95c3ac4937507641c1675 probably thought its Engine drawn (because it look soo good?)

Maybe found bug with mission?

**Comment by KingRaptor** [comment]
Hmm, I actually hadn't considered that scenario. It needs fixing to remain on for spectators but not accept queue orders.

**Comment by xponen** [comment]
I'll go investigate this problem tomorrow if nobody wish to... :)

**Comment by xponen** [comment]
KingRaptor... D:
hokomoko already fixed it here https://github.com/ZeroK-RTS/Zero-K/commit/7ff7ad0364270f2e694b87ac595657eb95a1797a
