### ISSUE TITLE
Buff Corsair

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5116]
So I don't forget next stable. Suggestions?

**Comment by Techhead0** [comment]
I remember a convo about this a few weeks ago, my thoughts were a slice more range would make it comfortably kite siren and help deal with siren's dominance, and there's a bit of room there to do so before it flips the mace unit matchup. (Vs amph it just dies to duck or scallop)

**Comment by Kingstad** [comment]
If range increase messes with too many interactions how about just HP buff plus some more pellets in wider cone. Hopefully extending the phase of the game before jack-of-all-trades siren comes out in numbers. I somewhat envision corsair as a sea scorcher wanting to get close to dish out its full damage.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/ZeroK-RTS/Zero-K/commit/3d135c4e4cc40f0322ccc4fd888ee2059db46720
