### ISSUE TITLE
Claims that terra 6 doesnt block veh (and 18 doesnt block bots)

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5124]
https://discord.com/channels/278805140708786177/278908415756206080/1187234359170830346

**Comment by IdkSomethingTemporary** [comment]
Tested with terraform raise/lower on titandual (and a previous game which I lost because +18 didn't block bots)
Testing points towards the current correct numbers to block veh is -10/+10 and to block bot is -30/+22
