### ISSUE TITLE
Consider making mexes snap to closest unqueued

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5156]
Mexes snap to the closest spot. So if you want to build a triplet you gotta click in their general areas:
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/e9c4d365-194d-4348-86ff-8ffffb2ccb22)

What if you could just click three times to queue all three? It would queue up a mex in the closest unqueued spot each time.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/4b4aa544-8f44-4706-9a21-0adea76615c8)

Low priority either way because area mex exists, but people coming from other RTS might prefer manual clicking.

**Comment by GoogleFrog** [comment]
Shift+click unqueues a queued mex, right? If not, then there is a bug. So how are you supposed to cancel a queued mex if the snap goes to the nearest unqueued?

People from other RTS would also manually click on the mex spots rather than on one spot.
