### ISSUE TITLE
COFC snaps back to orbit around centered raytrace on ctrl+mmb rotation

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#517]
When you Ctrl+MMB click a world location to orbit-rotate around it while using COFC, the camera first smoothly centers on that location.

Formerly, consequent mouse move without letting go of ctrl+mmb would then rotate around that new location.

Currently, it snaps right back to original rotation position (raytraced from center of screen, it seems?) and then rotates around it.

This happens on 91.0 as well as on dev engine.

**Comment by dvr333** [comment]
hmm, I thought this was only an issue with dev engine.
