### ISSUE TITLE
Current Likho missing exhaust flames?

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5175]
See https://github.com/ZeroK-RTS/Zero-K/pull/5164#issuecomment-1913033187

**Comment by GoogleFrog** [comment]
Likho does not have exhaust flames when the unit is renamed to bomberheavyold without changing the lups fx config.

**Comment by sprunk** [comment]
On that note perhaps lups configs could have arbitrary names and then units would have a customparam like `lups_config = "likho"` so that this doesn't happen when modders make new units based on existing ones.
