### ISSUE TITLE
LUPS Ribbons spawn in front of their position

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5178]
Empty piece is where the arrow points but the ribbon draws in front of the wing.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/1ddf6e6f-079b-4b17-9b27-1cd871623bee)

**Comment by GoogleFrog** [comment]
The proper fix would be to change the spawn point in the LUPS particle. I suspect it is something like spawning at the midpoint rather than the front.

**Comment by GoogleFrog** [comment]
Fixed. It was some broken assumption about what callouts mean.
https://github.com/ZeroK-RTS/Zero-K/commit/78a6e07f1f0aac353b91493438cb4f6da01a7e01
