### ISSUE TITLE
Stardust fire rate (aka slow doesn't handle continuous decay)

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5182]
Stardust has a 0.1 reloadtime, which means 3 frames. At 100% heat (50% slowdown) it should fire with 6 frames between each shot. But it fires every 3 frames at 100% heat, and there's a range between about 30% and 40% heat where it fires every 2 frames (!).

Here's what happens:
* continuous heat decay means it oscillates at around 98% heat and is always some tiny fraction smaller than on the previous frame.
* a 49%ish slowed Stardust shoots at frame N. The delay is set to 6 frames correctly, i.e. next shot is at frame N+6 (which is `N+(3 / 0.51)` with some leeway involved).
* attributes gadget at frame N recalculates the slow. One frame's worth of heat decay means it arrives at N+5.98 or such. **There is no half frame leeway for rounding and engine rounds down.** So engine rounds this to N+5.
* at frame N+1, slow is recalculated. Again the slow is one frame's worth of heat decay less, so the calculated frame doesn't quite reach N+5 and ends up at N+4.98ish, which the engine rounds to N+4.
* at frame N+2 a similar thing happens again and the frame ends up being N+3.
* at frame N+3 the Stardust is ready and fires again.

----

But this used to work. What changed? Here are a couple of engine facts.

1) everything is a burst weapon, possibly with 1 burst.
2) the engine defaults to 0.1 burstRate if undefined.
3) engine applies the burstRate delay after every shot, even the last one in the burst.

This almost never comes up in practice because no ZK weapon has a reload time faster than (burstRate * burst).

But it was possible for a modder to set reloadtime to 0.033 or 0.066 and end up with a weapon that has an effective reload time of 0.1 due to the default burstRate. The fix to this was to default burstRate to 0 feb523a6f29add36a9bd44297e14acf4baab42f3. This changed Stardust burstRate from 0.1 to 0.

The attributes gadget adjusts the burstRate at time of firing but doesn't continuously adjust the frame at which the current burst expires. So what used to happen was that the frame when reload was finished was behaving as incorrectly as it does now (i.e. it actually was 3 frames at full heat) but Stardust still fired every 6 frames because it was limited by burstRate, which wasn't adjusted continuously and fact nr 3) above applied.

----

There are two fixes possible:
* one is to just bring burstRate back to 0.1. This achieves the previous behaviour but just hides the issue, which may resurface if slow gets made to handle burst (or if engine stops applying burst rate after the last shot).
* a more elegant one would be to apply the half-frame rounding leeway to the reload frame when recalculating (it already gets added to the reload time which is why the correct value of 6 shows up initially, and not 5.99). But this gets a different shooting characteristic for Stardust specifically (it still reaches 6 frames eventually, but reaches the breakpoints earlier resulting in an effective nerf) and also I haven't done the math to see how it behaves in general.
* best would probably be to add slow to engine but that is a large design undertaking.

**Comment by GoogleFrog** [comment]
I recall being fine with the title of this ticket when implementing Stardust heat. It was just part of the territory. But if something has changed, then idk.
