### ISSUE TITLE
Check small selection volumes

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5183]
I added a debug view to engine that lets you display both collision and selection volume at the same time (collision is purple, selection is green). Almost all units have the selection volume larger than the collision volume, the major exceptions are Athena and Newton.
This isn't necessarily a problem but maybe it's an oversight.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/3773c7a0-0cec-4481-89d8-8d4da969e6b1)
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/180aab94-f4f3-4fbc-b785-a63df1ca7f38)
beyond-all-reason/spring#1286

**Comment by GoogleFrog** [comment]
The same thing can be done with a constant in unitdefs_post. It turns the colvol into the selection volume so it can be seen.

Athena and Newton seem like oversights.
