### ISSUE TITLE
Port LUPS patch that makes them run at >30 draw FPS

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5184]
See beyond-all-reason/Beyond-All-Reason#2596
* claims that it's free but actually there are extra `Spring.GetFrameTimeOffset()` calls. Perhaps LUPS has enough overhead already for this to be relatively cheap though
* being gameframe bound also lets us not worry about edge cases. Check what happens at differing gamespeeds (incl. x0 aka pause)

**Comment by Beherith** [comment]
"Claims"
