### ISSUE TITLE
Various campaign nitpicks

### ISSUE THREAD

**Issue by Kingstad** [ZeroK-RTS/Zero-K#5187]
after testing in skirmish, almost all pw structures do not leave a ghost after having been spotted in fog of war. This is mainly annoying with the ancient fabricator as there are missions where those have to be killed, most of all on the final mission Cipher where you try to snipe them with starlight and you have to re scout over and over.

Typos:
- CODEX:
asjulohi fabricators: "they spared on expense on Asjulohi"
IFF Codes: "may even respond to orders issed by commander it sees as friendly"
Skokukur Uprising: "equiped" instead of equipped
Rockbar Battleground: "the progenitors of the Anarchai were originally were a small techologist settlement."
Starsong: last paragraph has so many commas?
- MISSION BRIEFINGS:
Sapphire: "no one has ever succeeded at such task"
LALATA: "I could access to some research systems" does this one need "gain access"?
- In game mission briefing and unit descriptions:
BAVHAKYA: odin description is for the old D-gun version

There are other tiny phrasing nitpicks here and there I havent bothered writing down and I'll leave gameplay stuff alone

**Comment by sprunk** [comment]
+ ZeroK-RTS/Chobby@a91fd2e3425abd98e8d2a75322c26f4d29b59f3a
