### ISSUE TITLE
Option to only select non-retreating units with control groups

### ISSUE THREAD

**Issue by Buskemor** [ZeroK-RTS/Zero-K#5193]
When using control groups (ctrl1-9), have an option to not select retreating units (like the option of decreasing their selection rank on retreat)

**Comment by sprunk** [comment]
Doesn't the decrease selection rank option work?

**Comment by Buskemor** [comment]
@sprunk It works when selecting using click and drag, but for control groups it doesn't.
It makes sense for control groups to select everything in the control group regardless of selection rank, but this makes using retreat on your units very annoying if you're controlling your units with control groups.

![image](https://github.com/ZeroK-RTS/Zero-K/assets/130304167/d12c4e85-b6f3-4fb2-9e65-2369b3fbca6e)

**Comment by GoogleFrog** [comment]
The bool in the fix could be a setting that makes control groups ignore selection ranks of at least X. This would let the default treat ranks 1,2,3 as the same rank, which would be useful for setting retreat to rank 0, or even just setting rank 0 manually.
