### ISSUE TITLE
Hold mouse to terraform stopped working

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#5202]
When placing structure, holding mouse click to set structure height no longer works

**Comment by sprunk** [comment]
It now requires a checkbox because newbies who were slow and undecided at dragging windgen lines (etc) would hold the button too long and then get confused by the UI.

**Comment by sprunk** [comment]
Settings / Interface / Building Placement

https://github.com/ZeroK-RTS/Zero-K/blob/2fbb696b32312ae548ce4c8a5fd2fd384dfa05d7/LuaUI/Widgets/gui_lasso_terraform.lua#L94-L99

**Comment by Licho1** [comment]
Thanks for explanation of the reason!
