### ISSUE TITLE
Speccheat prevention fires in 1v1 games

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#521]
Speccing some 1v1 with default settings, i am unable to type in non-specchat mode. That is, text entered in "to all" mode will be greyed out and invisible to players.

It is still relayed by Springie to the battleroom, though, and vice versa.

**Comment by Anarchid** [comment]
It seems passed now, i'll list the games which were affected later.

**Comment by GoogleFrog** [comment]
Are maps able to create extra allyTeams? Automatic triggers on more than 3 allyTeams because gaia always exists but I am not aware of any way to add more without something like competitive chickens or FFA.

**Comment by Anarchid** [comment]
Sometimes extra startboxes exist due to unrelated bug. Could this be the reason in any way?
Are playerless teams possible?

**Comment by Anarchid** [comment]
Checked in 2v2 by adding a startbox for team 3, hypothesis confirmed.

Suggested fix is to discount teams without human players.

**Comment by Anarchid** [comment]
Additionally it seems that since this change, proconsole2 visibly hangs the game for some time after message is received. Dunno if worth a separate issue.
Chili chat, bubbles, and proconsole 1 are not affected, or are affected only imperceptibly.

**Comment by GoogleFrog** [comment]
You human player fix sounds good. I'm not supporting Proconsole 2.

**Comment by Anarchid** [comment]
My fix is broken because it operates on "teams" without retrieving them. Should have tested bleh

Also the lobby mute copypasta has the same issue and probably needs same therapy
