### ISSUE TITLE
Acess Violation Crash

### ISSUE THREAD

**Issue by Wizpher** [ZeroK-RTS/Zero-K#5212]
At about 40 minutes every game (On future wars custom games) I get a crash that says, "Spring as crashed: Access Violation." This happens if i'm hosting or not. It also says, "A stacktrace as been written to: <Insert file for infolog here>"

**Comment by Wizpher** [comment]
The map was violet rampart if that matters

**Comment by Arch-Shaman** [comment]
Zero-K needs to update to latest circuit to fix this. In the mean time you can use the AIs here:
https://github.com/Arch-Shaman/FutureWars-CircuitAIConfigs

**Comment by Arch-Shaman** [comment]
If you're still getting crashes with those ais post your infolog to me and I'll forward it to Lamer.

**Comment by sprunk** [comment]
Not a vanilla ZK gameside issue, for the mod distribution problem see ZeroK-RTS/Zero-K-Infrastructure#2977
