### ISSUE TITLE
use tags to mark releases

### ISSUE THREAD

**Issue by wuyoli** [ZeroK-RTS/Zero-K#5217]
we are trying to package this game for the Nix package manager, but we are not sure which commit corresponds with the current release.

Which commit is used for the current release?

Is there a currently a way to find this information?

If not: Could you start marking release commits? (For example with git tags?)

**Comment by sprunk** [comment]
It's always the most recent commit whose first line of the commit message is `VERSION{foo}`.

For example:
* current 117bf89867ee180a4e3a83cca34c4f44c3d8c661
* previous e8ee3b15ff2049fb3b7a9ef3bfd017330fc82867

**Comment by wuyoli** [comment]
Thank you for the fast reply. This seems kinda unclean, but we can work with this.

**Comment by sprunk** [comment]
Oh, there's also the engine at https://github.com/beyond-all-reason/spring/ . The current version of ZK runs on this release https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-2314-g9e0bf7d and the way to tell is probably some config file inside the Chobby repo.

**Comment by sprunk** [comment]
Reopen if you need more info
