### ISSUE TITLE
Bomber command crash

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5240]
https://zero-k.info/Battles/Detail/1870369

[t=01:12:38.363655][f=0009370] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=GameFrame trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_bomber_command.lua"]:237: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_bomber_command.lua"]:237: in function 'RefreshEmptyPad'
	[string "LuaRules/Gadgets/unit_bomber_command.lua"]:262: in function 'RefreshEmptyspot_minusBomberLanding'
	[string "LuaRules/Gadgets/unit_bomber_command.lua"]:624: in function 'GameFrame'
	[string "LuaRules/gadgets.lua"]:989: in function <[string "LuaRules/gadgets.lua"]:987>
	(tail call): ?

[2024-04-06_00-21-08-322_Prestige v1_105.1.1-2314-g9e0bf7d BAR105.zip](https://github.com/ZeroK-RTS/Zero-K/files/14891853/2024-04-06_00-21-08-322_Prestige.v1_105.1.1-2314-g9e0bf7d.BAR105.zip)

Replay on https://github.com/ZeroK-RTS/Zero-K/commit/8f4ff4a89aa0c09e6dc499b7d49f0a532bbe5c9c

I reverted the only change to bomber command and confirmed that the modified code does not crash bomber command.

**Comment by sprunk** [comment]
e1648b46ad6a4996760ad92100be14a9fd951b8b
