### ISSUE TITLE
In-game settings resets to default every time the game restarted

### ISSUE THREAD

**Issue by Blackrobe** [ZeroK-RTS/Zero-K#5263]
I encountered some bug where the audio level resets to default levels every time I launch Zero K. I'm playing on Windows, Steam.

Before restarting
![image](https://github.com/ZeroK-RTS/Zero-K/assets/14886923/994b96bb-3f1b-46ee-b5a6-7d555b8a9e86)

After restarting
![image](https://github.com/ZeroK-RTS/Zero-K/assets/14886923/0cf27410-68c3-43ae-9e44-8ffc6370464b)

What's weird is that some settings does not persist (got reset), but others do remember their state since the previous game run.

Here is the condition after restarting, and after clicking "Reset" on the bottom.
![image](https://github.com/ZeroK-RTS/Zero-K/assets/14886923/77cdc057-1653-48fe-b97d-eb3f14149d8f)

**Comment by GoogleFrog** [comment]
Master volume is in springsettings.cfg. Check that you have write permissions for it.

**Comment by Blackrobe** [comment]
@GoogleFrog I'm sorry but I cannot find the keyword in the springsettings.cfg, here is my entire file below. The only relevant config is `MaxSounds = 32` but is that not for the maximum amount of sounds that can be played at once, not the volume?

```
3DTrees = 1
AllowDeferredMapRendering = 1
AllowDeferredModelRendering = 1
AnimationMT = 0
BuildWarnings = 0
BumpWaterBlurReflection = 1
BumpWaterTexSizeReflection = 128
CamFreeScrollSpeed = 50
CamMode = 1
CamTimeExponent = 4.0
CamTimeFactor = 1.0
CmdAlpha = 0.60000002
CmdAlphaDark = 0.65000004
CmdIconAlpha = 0.44999999
DisplayDebugPrefixConsole = 0
DualScreenMiniMapOnLeft = 1
DynamicSky = 0
EdgeMoveDynamic = 0
EdgeMoveWidth = 0.003
FPSFOV = 90
FPSScrollSpeed = 50
FontSize = 18
Fullscreen = 0
GrassDetail = 0
GroundDecals = 2
GroundDetail = 90
HangTimeout = 30
HardwareCursor = 1
InitialNetworkTimeout = 0
InputTextGeo = 0.26 0.73 0.02 0.028
LODScale = 1.000
LODScaleReflection = 1.000
LODScaleRefraction = 1.000
LODScaleShadow = 1.000
Language = en
LinkBandwidth = 0
LinkIncomingMaxPacketRate = 512
LinkIncomingPeakBandwidth = 65536
LinkIncomingSustainedBandwidth = 65536
LinkOutgoingBandwidth = 131072
LogFlush = 0
LuaAutoModWidgets = 1
LuaGarbageCollectionMemLoadMult = 2.5
LuaGarbageCollectionRunTimeMult = 1.5
MSAALevel = 4
MaxParticles = 15000
MaxSounds = 32
MaximumTransmissionUnit = 0
MiddleClickScrollSpeed = -0.0015
MiniMapCanFlip = 1
MiniMapMarker = 0
MinimapOnLeft = 1
MouseDragCircleCommandThreshold = 25
MouseDragScrollThreshold = 0
MoveWarnings = 0
NetworkLossFactor = 1
NormalMapping = 1
OverheadMaxHeightFactor = 1.39999998
OverheadScrollSpeed = 50
ReconnectTimeout = 0
ReflectiveWater = 4
RotOverheadScrollSpeed = 50
RotateLogFiles = 1
Shadows = 1
ShowClock = 0
ShowPlayerInfo = 0
SmoothLines = 1
SmoothPoints = 1
SplashScreenDir = ./MenuLoadscreens
TeamHighlight = 0
TreeRadius = 1200
UnitIconDist = 151
UpdateBoundingVolumeMT = 0
UpdateWeaponVectorsMT = 0
UseDistToGroundForIcons = 1.10000002
UseLuaMemPools = 0
UseNetMessageSmoothingBuffer = 0
VFSCacheArchiveFiles = 0
VSync = 0
VerboseLevel = 10
Version = 2
Water = 4
WindowBorderless = 1
WindowPosY = 0
WorkerThreadSpinTime = 5
XResolutionWindowed = 1920
YResolutionWindowed = 1080
ZKUseNewChiliRTT = 0
interfaceScale = 100
snd_general = 100
```

**Comment by Blackrobe** [comment]
I tried to change `MaxParticles = 15000` from inside the game's lobby to the value 2000. It did change the value inside the configuration file, so I think write permission is not the problem here.

https://github.com/ZeroK-RTS/Zero-K/assets/14886923/09003916-e401-4ac0-a386-3c4540bc6a89

**Comment by GoogleFrog** [comment]
My springsettings contains `snd_volmaster`. If yours does not, then I suspect that the game can't write to it. Check whether the file changes at all between opening and closing the game over some session where you modify settings.

**Comment by Blackrobe** [comment]
> My springsettings contains `snd_volmaster`. If yours does not, then I suspect that the game can't write to it. Check whether the file changes at all between opening and closing the game over some session where you modify settings.

hmm... check this out, I added `snd_volmaster = 20` into springsettings while the game is running and it worked. However the line that I added completely disappear when I restarted the game.

Is it possibly caused by Steam cloud sync? Did we sync these settings into it?

**Comment by Blackrobe** [comment]
also if failure writing into springsettings exist, may I know where I can find it? 
infolog file does not seem to log any errors

**Comment by sprunk** [comment]
Looks like failure to write into springsettings is 100% silent. I made an engine bug report beyond-all-reason/spring#1474

**Comment by Blackrobe** [comment]
> Looks like failure to write into springsettings is 100% silent. I made an engine bug report [beyond-all-reason/spring#1474](https://github.com/beyond-all-reason/spring/issues/1474)

Thanks for the help @sprunk , but imo this issue should not be caused by failing to write? :/ please CMIIW

In this video below, the scenario goes like: 

- I opened springsettings in VSCode and Zero K
- I started a game and I modify the master volume, it gets written as shown in VSCode
- I closed the game and launch it again via Steam
- That master volume settings in springsettings is gone as shown in VSCode

https://github.com/ZeroK-RTS/Zero-K/assets/14886923/9782f19c-35e2-4a0a-8e32-ed05241f0985

**Comment by GoogleFrog** [comment]
Do you have some sort of steam cloud sync thing enabled? Does `configversions.json` exist, and when was it last modified?

@sprunk can you think of any answer that isn't going to end with us just rolling our own snd_ in lua configs?

**Comment by sprunk** [comment]
idk, what are we going to do if the next guy over has an opposite problem where lua configs get overwritten but springsettings are reliable? It looks like chobby is applying the default so first we should probably look why chobby does that.

Perhaps move `snd_general=100` from here (and equivalents)
https://github.com/ZeroK-RTS/Chobby/blob/ea7ac8c8ec6983a24b3c6ccdf7cf3ec3c004ae8c/LuaMenu/configs/springsettings/springsettings.lua#L89
into there?
https://github.com/ZeroK-RTS/Chobby/blob/ea7ac8c8ec6983a24b3c6ccdf7cf3ec3c004ae8c/LuaMenu/configs/springsettings/springsettingsChanges.lua#L20

**Comment by GoogleFrog** [comment]
@Licho1 I think the wrapper is failing to write `configversions.json`, and that makes a bunch of settings non-sticky.

**Comment by GoogleFrog** [comment]
See https://steamcommunity.com/app/334920/discussions/0/4364627785841721455/

**Comment by GoogleFrog** [comment]
@Blackrobe try downloading `configversions.json` from https://raw.githubusercontent.com/ZeroK-RTS/Chobby/master/LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json and putting it in steamapps\common\Zero-K.

**Comment by Blackrobe** [comment]
> @Blackrobe try downloading `configversions.json` from https://raw.githubusercontent.com/ZeroK-RTS/Chobby/master/LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json and putting it in steamapps\common\Zero-K.

Hi @GoogleFrog , I can confirm that this fixes it.

I did as you instructed here. I pasted the `configversions.json` into the directory without any modifications, and when I run the game, the Steam client said that game is downloading a few things.

The issue no longer repeat itself with the presence of `configversions.json`.

**Comment by Blackrobe** [comment]
Thanks @Licho1 and @GoogleFrog for deploying v1.12.5.0

https://github.com/ZeroK-RTS/Chobby/commit/736f981c6ab4ef046ef72af6ebd7f535d40060f9

I tried reinstalling the game clean through Steam -- complete with steamapps directory wipe, looks fine now as I can no longer reproduce the issue.
