### ISSUE TITLE
Github repo: add link and tags

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#5269]
IDK how helpful they are but can't hurt. The task would be to figure out what conventions for tags exist and suggest a decent set.

Here's a comparison of ZK and Spring repos:
![image](https://github.com/ZeroK-RTS/Zero-K/assets/2573076/eff69a37-d7b9-4f45-be56-8b320e711181)

**Comment by Licho1** [comment]
@sprunk you are now co-owner of the org, feel free to add them yourself :)

**Comment by sprunk** [comment]
Thanks!

Added some basic tags. Perhaps a better set could be curated but it would require somebody with "market" knowledge of how contributors/people use the tags.
