### ISSUE TITLE
Map scanline artifacts when zoomed out

### ISSUE THREAD

**Issue by Muon** [ZeroK-RTS/Zero-K#534]
This screenshot on Finn's Revenge exhibits a strange scanline-like artifact in the map texture:

![2015-01-23_00001](https://cloud.githubusercontent.com/assets/402745/5873427/61b123dc-a34a-11e4-9719-3f55899266ae.jpg)

The artifacts disappear when zoomed in. Maybe there's some problem with the geometry?

**Comment by Anarchid** [comment]
Some maps just have this. 

Others don't. It's not a game issue as far as known; a map issue.

One other map which exhibits this is icy run, more do.

**Comment by Muon** [comment]
What causes it, though?

**Comment by Anarchid** [comment]
Bad compression settings when compiling map.
