### ISSUE TITLE
Terrain shadow geometry artifacts

### ISSUE THREAD

**Issue by Muon** [ZeroK-RTS/Zero-K#535]
The following screenshot on Finn's Revenge exhibits some shadow (?) artifacts:

![2015-01-23_00002](https://cloud.githubusercontent.com/assets/402745/5873457/cb461fbe-a34a-11e4-830e-ac164f4ca92f.jpg)

**Comment by Anarchid** [comment]
This might be useful to submit to engine, if it already hasn't been fixed in future versions or reported there before.

**Comment by Orfelius** [comment]
I don't know if you still browse this repo @Muon but you didn't elaborate on which version of then engine you were operating on.

**Comment by sprunk** [comment]
Belongs to the engine and does not contain information such as version. Close?

**Comment by Muon** [comment]
Here's the replay: http://zero-k.info/Battles/Detail/326285

Engine 91.0

**Comment by Orfelius** [comment]
I say that this is related to shadow quality in the Spring. On lower quality it WILL look bad. I have just launched the game in 98+ and seen no problems so this issue looks outdated. Close?

**Comment by Anarchid** [comment]
Engine bug; not fixable ZK-side; reported on mantis; closing.
