### ISSUE TITLE
Defender Lacks a Reload Bar

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#539]
Hacksaw gets one but not defender. Makes it impossible to tell when your defenders will be ready to fire again.

**Comment by xponen** [comment]
I've checked just now, 
Defender's reload cycle actually is (uniquely) scripted. It is not using engine's salvo behaviour which Hacksaw uses.

To fix this it need the Defender script to communicate with the UI widget.

Maybe someone could try convert Defender's script to LUA for easy access.

**Comment by Anarchid** [comment]
Defender can reload without launching the full salvo and i think it's reload time resets after each fired missile. What i am saying is that this is not a "normal" reload anyway, the rules are different.

Hacksaw can't have this, it doesn't have individually visible missile pieces to show how many missiles it has stockpiled.

I guess the hypothetical Defender reload bar would need to show how much missiles it has left **and** how much time until they are refilled.

**Comment by GoogleFrog** [comment]
xponen I already LUSed Defender.

You can think of defender as having 3 independent weapons which are unable to fire within about a second of each other. Each weapon has its own reload time.This makes a reload bar quite difficult to implement in a useful way. Often Defenders will fire 3 shots then appear to take about 8 seconds to reload. Complications set in when you consider different cases such as firing 2 shots and then a 3rd a little bit later.

A decent solution may be to track the reload time of the first weapon as that will cover most cases. The little green lights over the missile tubes already communicate the reload times though.

The implementation does not actually use 3 weapons. Hacksaw intentionally does not fire like Defender.

**Comment by GoogleFrog** [comment]
This cannot work.
