### ISSUE TITLE
Gifting caretakers does not reset their action queue

### ISSUE THREAD

**Issue by matthasbeendestroyed** [ZeroK-RTS/Zero-K#5393]
1. Start a nanoframe (say a superweapon).
2. Make a caretaker.
3. Gift the caretaker to an ally.
4. The caretaker continues to spend metal on the nanoframe.

I understand the expected behavior is that the caretaker should at least pause. It currently continues to spend and the ally may not be aware they are funding another player's project.

**Comment by GoogleFrog** [comment]
By pause do you mean receive the Wait command? We want to avoid secretly funding another players project, and I thought it was fixed somehow. But I don't recall the solution being to Wait. The move state of the Caretaker should determine whether it assists allies. Perhaps it is a matter of clearing the queue on share if the move state says so.
