### ISSUE TITLE
Unit build icons (not radar icons) need to be regenerated

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#540]
Current build icons are out of date - the backgrounds for airplant and gunship factory still show green in topleft and blue in bottomright, which suggests that they are placed submerged like amphs or fusion would be.

![buildicon bug](https://cloud.githubusercontent.com/assets/132906/5899090/2b79db4c-a557-11e4-9c7a-4c84757c1ea7.png)

**Comment by sprunk** [comment]
Silencer buildpic still has Core logo on it (OTA IP).
