### ISSUE TITLE
Improve start position shuffle.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#544]
Start position shuffle should shuffle start positions before the game starts. People should be placing their command in the start box they will actually start in.

**Comment by sprunk** [comment]
won't happen, licho said it's perfection not worth the cost

**Comment by Licho1** [comment]
If you can do it without breaking other stuff, do it. But any additional cost is up to you (PW, QM, whatever this breaks, because I don't know).
Testing environment is your friend

**Comment by Licho1** [comment]
In other words, springie needs some control over boxes and it needs ability to disable shuffle and set them as before.

**Comment by sprunk** [comment]
The infra-side implementation was supposed to just change how startboxes are put into spring start-script (eventually: into modoption instead of the engine startbox fields -- the one i added didn't remove engine boxes because thats not yet ready game-side).

Springie would still have full control over how the boxes are set up and control how the shuffle behaves through another modoption, so nothing is affected.

**Comment by Licho1** [comment]
In that case you probably made erorr in format string did you test on local or test springie?
Deploying blind changes in key infra is really bad idea.

**Comment by sprunk** [comment]
It compiled so i assumed everything worked

**Comment by Licho1** [comment]
that equals to blind test...

2015-05-20 10:10 GMT+02:00 sprunk <notifications@github.com>:

**Comment by xponen** [comment]
@sprunk I discover this can be done without gadget changes. 

We shuffle the startbox during startscript creation, suddenly the startbox ingame is randomized and didn't match the ZKL screen.

**Comment by sprunk** [comment]
No, that wouldn't do anything. You would still know where everybody starts except you'd know that from Spring.GetAllyTeamStartBox instead of the lobby.

**Comment by xponen** [comment]
@sprunk we can attach some tag to the startscript that tell ZK to hide player position by overriding Spring.GetAllyTeamStartBox() like this: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Utilities/weapon_index_compat_91.lua

**Comment by sprunk** [comment]
Perhaps that would work. Want to implement that?

**Comment by xponen** [comment]
Turn out there was much help! the override for Unsynced was separate from Synced, like here:
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/main.lua

Is check first whether user can override this file to undo the override,

**Comment by xponen** [comment]
@sprunk yes, I want to try. will get back to you if it is a fail

**Comment by sprunk** [comment]
Game-side my implementation is used but infra-side xponen's version got merged.
Both implementations require the counterpart to also get merged to be useful.
Only one version of the shuffer is needed so one of them needs to be chosen and the other reverted.

**Comment by GoogleFrog** [comment]
Is this done?

**Comment by sprunk** [comment]
Done but needs Springie to be deployed.

**Comment by GoogleFrog** [comment]
What does that mean? Something in springie? In stable?

If something is implemented then the ticket for it should be closed because the change is going to make it in.

**Comment by sprunk** [comment]
It means it is fully implemented (ie. ticket closable) and awaits infra stable.
