### ISSUE TITLE
When zooming out with tab, minimap does not hide itself (nvidia gtx 970)

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#553]
http://i.imgur.com/OW8MlyT.jpg

**Comment by GoogleFrog** [comment]
Which camera?

**Comment by GoogleFrog** [comment]
Try resetting your settings to see if it persists.

**Comment by dvr333** [comment]
This should happen on any zoom-out. Kaen's solution is okay, but hacky, but the existing setup with COFC and transparency should be extended to apply to any camera (line 830 of gui_chili_minimap). That assumes that the maximum zoom distance of any camera is something Lua can know.

**Comment by dvr333** [comment]
Actually, on further review, my mode is basically a fix for COFC to be consistent with what kaen is doing. Kaen's idea can work alongside it.

**Comment by GoogleFrog** [comment]
Tab was removed.
