### ISSUE TITLE
Nvidia gtx 970 - gigantic selection "circle" around structure appears

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#555]
http://i.imgur.com/MA2QOfM.jpg

**Comment by GoogleFrog** [comment]
How about above water? It looks like an interaction with the water graphics to me.

**Comment by Anarchid** [comment]
This is water 3 i think, reflective/refractive, not the ZK default of bumpwater 4.

**Comment by ashdnazg** [comment]
Check if it happens in the latest develop version, may be the same issue as infotexture whitening

**Comment by Licho1** [comment]
Indeed it was water 3, i had to switch to it because with default water
units are nearly invisible due to reflection.

2015-02-01 11:17 GMT+01:00 Eshed <notifications@github.com>:

**Comment by GoogleFrog** [comment]
Stuff was fixed since then. Reopen if it continues to fail.
