### ISSUE TITLE
Players that have surrendered still receive metal from their team's mexes

### ISSUE THREAD

**Issue by blah1** [ZeroK-RTS/Zero-K#557]
e.g.: http://zero-k.info/Battles/Detail/328767

When SpaceAids surrenders after losing his base, THOL's metal income is cut in half until SpaceAid's metal storage of 500 is full. 
This effectively takes 500 metal from a team for each player that has dropped out on that team.

Possible fix: Set the maximum metal storage to 0 for dead players, thus stopping metal leech and giving back any of the 500 metal currently stored.

**Comment by GoogleFrog** [comment]
Sounds like a good fix.
