### ISSUE TITLE
fighterdrone crashes the game

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#566]
fighterdrone (a new reef model I think) that is hidden in the files crashes the game.
I suspect it is because of .dae format.
I suspect that it was not meant to be commited yet.
I suspect one certain person might be behind this.

And yes I was using the newest engine build to run it.
Please remove or fix :\ don't clutter already cluttered repo with completely broken units :L

**Comment by KingRaptor** [comment]
Fighterdrone has been in repo for months and is even used in an official mission. My tests with ZKL skirmisher on 91, 98 and 98.0.1-374-g147ee66 with Zero-K v1.3.2.1 on TitanDuel (/give fighterdrone, make it fly around, shoot ground, then self-destruct) all work.

Combining the factual errors with your attitude in this issue report makes me very annoyed. Stop it.

**Comment by Orfelius** [comment]
Sorry for that.
But problem persist but is not linked towards that particular unit itself. In offline enviroment fighterdrone spawns fine.
It seems that !hostsay command is broken.
Closing.
