### ISSUE TITLE
Fake napalm

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#569]
Phoenix is not a napalm bomber. In ZK napalm stays on the ground and damages units overtime.
I suggest either renaming Phoenix to fire bomber or giving it actual napalm which stays in the ground.

**Comment by GoogleFrog** [comment]
Dropping a firewalker bomb would make pheonix actually good and deal with the inaccuracy somewhat.

**Comment by Orfelius** [comment]
I have tried to make that happen and succeded somewhat in my test enviroment but I do not know how to scale Fx effect properly :\
Phoenix would require higher cost though too since its capacity to kill skirmishers and alike would sufficiently increase.

**Comment by sprunk** [comment]
Naming is not an issue and Firewalker bomb is no longer desired as "pheonix fire does not hang around for that long anymore". Can be closed.
