### ISSUE TITLE
bugged coms when people resign during pregame phase

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K#570]
http://zero-k.info/Battles/Detail/330353

player nassier resigned during the startup phase after selecting his com, without picking a starting position. as a result, a noname-owned commander dropped from the sky that couldnt be /taken nor was it given by the afk monitor, despite blinking. 

http://zero-k.info/Battles/Detail/329616

in this other game with the same bug, alcur resigned during the startup and later rejoined, but did not get his com back.

**Comment by xponen** [comment]
There's multiple way this can be fixed:
Do you want:
1) /take to be enabled in pre-game situation? or;
2) fix Lagmonitor to handle pre-game resign?

**Comment by GoogleFrog** [comment]
I would rather fix start unit setup to take pregame resign into account. This is not a lagmonitor thing.

**Comment by KlonZK** [comment]
take also needs to be enabled to get all the ressources from resigned/lagged etc teammates. especially in the early stage of the game the team that gets extra coms from resigners/laggers are at a significant disadvantage when half of a players storage is not given (which usualy is the case).

other than that, i dont think its a good idea to remove take.

**Comment by xponen** [comment]
the com problem sound like a really really complex bug!
but we didn't block resource take, we just block unit take (except in cheat mode).

Idk if com issue can be solved quickly, and I bet some people can't stand seeing unit blinking. I'll just do PR to disable the /take gadget for now.

**Comment by KlonZK** [comment]
but its a new bug as far as i can tell. maybe the recent lobby changes cause it?

**Comment by xponen** [comment]
what is weird is why Alcur and Nassier resign too early. They might have problem that they didn't report.

In mean time, we fix bugged com.

**Comment by xponen** [comment]
turn out Alcur accidentally in-game
