### ISSUE TITLE
Snake unable to shot at tidal generators

### ISSUE THREAD

**Issue by Magmanx** [ZeroK-RTS/Zero-K#575]
Snakes aim at tidals and fire, but the torpedo dive below the tidal and miss its target.
http://zero-k.info/Battles/Detail/333046 
In south my snakes tryed it at a tidal line.

**Comment by KlonZK** [comment]
happens with other torpedo weapons as well (duck, urchin, probably all others as well)

**Comment by GoogleFrog** [comment]
Fixed.
