### ISSUE TITLE
Game Details presets set BumpWaterRefraction to 2

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#577]
The higher game details presets (Ultra, and maybe High) set BumpWaterRefraction to 2. This mode causes issues with commander names and can sometimes cause issues with underwater unit visibility as well.

The setting should probably never go above 1 in presets.

**Comment by dvr333** [comment]
Wait, this should be in Infrastructure. Sorry

**Comment by Licho1** [comment]
Nah it belongs here because its a game bug (the rendering)

**Comment by dvr333** [comment]
I can remove the depth check on names (and icons) and that helps, it's probably not a bad idea either. However, the main issue is probably engine-side, as the water layer has a depth mask when  BumpWaterRefraction is set to 2 and doesn't when it is set to 1. This also affects facplop effects, and generally messes with everything that assumes water is considered transparent to depth, so that the depth value that matters is the ground below the water, not the water itself.
