### ISSUE TITLE
Dirtbag do not aggro chickens.

### ISSUE THREAD

**Issue by Princereaper** [ZeroK-RTS/Zero-K#578]

**Comment by Princereaper** [comment]
I found out dirtbags don't aggro chickens. I went around killing roosts with dirtbags.

http://zero-k.info/Battles/Detail/333831
http://zero-k.info/Battles/Detail/333837

**Comment by GoogleFrog** [comment]
Add a new cat for stupid targets for chickens. Duplicate stupid target except for dirtbag. Make the chicken cats use this new cat.

**Comment by sprunk** [comment]
I dislike the idea of doing the extra cat hack just for this edge case. It's probably fine if people learn to raid with Dirtbag.

**Comment by sprunk** [comment]
It sounds better for chickens to push against the base instead of chasing chaff. If porcers learn to raid this way then all the better. Eventually chicken Pigeons / Spikers / Tubes appear and sort any straggler Dirtbags out.
