### ISSUE TITLE
/take broken when player resigns pre-start

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#580]
com idles, flashing in colors, is not given to next highest elo player the whole game

alcur resigned, im the one who should get it.

http://zero-k.info/Battles/Detail/334039

**Comment by mojjj** [comment]
also, /take has no effect -.-

**Comment by xponen** [comment]
is duplicate of this: https://github.com/ZeroK-RTS/Zero-K/issues/570
I will check the lagmonitor.
@GoogleFrog idea is to not spawn com for non-player

**Comment by xponen** [comment]
okay, fixed in https://github.com/ZeroK-RTS/Zero-K/commit/2509b6319fe58da5d84ba4a30da4936a72d1a0dc (stop spawn for resigned player)
