### ISSUE TITLE
consider moving krow to strider

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#590]
Reasoning: costs 5k - there is a large gap between it and the next unit available in "normal" facs (golly at 2.2k) and it is also more expensive than multiple other striders (all of the sub-10k ones in fact).

Potential arguments against include being a balance change (nerf to both GS and Krow, delaying rushes).

**Comment by Licho1** [comment]
Im not against that though I would like athena re-added to strider too.

**Comment by Licho1** [comment]
And perhaps warlord and reef moved back to sea lab ...

**Comment by Anarchid** [comment]
Pretty sure neo-reef won't fit into shipyard.

**Comment by sprunk** [comment]
Moving reef/warrior back into sea would also be completely against moving krow to strider so doing both would be silly.

**Comment by Princereaper** [comment]
I believe it would help "elevate against the cheese known as krow rush by allowing it to take longer to rush.

**Comment by Licho1** [comment]
Meh there is no more consistency in this than in current setup dont see much value.
