### ISSUE TITLE
Leviathan only fires with Settarget

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#591]
Manual standard attack order on Leviathan does not work, while Settarget causes it to fire.

**Comment by Princereaper** [comment]
I believe it only fires if you got los on a target?

**Comment by Anarchid** [comment]
It fires without los with settarget. It should fire always.

**Comment by Anarchid** [comment]
It fires on the dev engine. Considering the issue obsolete like 91.0 is.
