### ISSUE TITLE
98+ bertha can fire at right angle

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#603]
All I did was to change it to hold fire and then back and then let it pick its own targets.

http://cloud-4.steamusercontent.com/ugc/526131613411006149/ACE233CFFE4DD52B11D04049F6590EF1E45B388A/

**Comment by GoogleFrog** [comment]
And you are unaware that units have always been able to do this?

**Comment by Licho1** [comment]
I know it was happening but it was norm in this case, every shot was like that after some point in game.

**Comment by sprunk** [comment]
Fixed: https://github.com/ZeroK-RTS/Zero-K/commit/f282ea002af339107a95fb3e2b04827cc327bde0#diff-8ecf516e7e606e8298909b591f0a8e3fR101
