### ISSUE TITLE
98.0 is too slow for me

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#604]
In battle 336402 (http://zero-k.info/Battles/Detail/336402), sometime after playing approximately 20 minutes, I experienced a severe slowdown. I was constantly catching up and the frame rate display showed 2 FPS. Eventually I decided it was best to resign.

Specs:
AMD Radeon HD 5670
Intel Core i3 CPU 540 @ 3.07 GHz
4 GB of RAM

**Comment by GoogleFrog** [comment]
Do this: https://github.com/ZeroK-RTS/Benchmarks/wiki/How-to-Benchmark-Jan-2015

**Comment by Sgathec** [comment]
In this battle I was incessantly catching up too after a certain amount of time had passed.

http://zero-k.info/Battles/Detail/348337

infolog.txt: https://gist.github.com/Sgathec/6553e99c107762448be6

I'll consider benchmarking.

**Comment by sprunk** [comment]
The infolog contains MASSIVE amounts of widget error spam and the ticket itself doesn't seem to have much value without the benchmark results. Close?
