### ISSUE TITLE
98.0-403 elevation view is all blue for me 

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#605]
all false color view is opaque blue for me at Archers_Valley_v6
I don't think it happen to me  before in other map
![98 403 archer valley v6](https://cloud.githubusercontent.com/assets/2525365/6516488/5743828e-c3cd-11e4-976f-0f8a04915146.jpg)

infolog: http://pastebin.com/0xjTwL9R

**Comment by xponen** [comment]
still occur in 98.0-667

**Comment by Orfelius** [comment]
Looking at infolog this looks as a clear engine issue and should be reported on Mantis not here.

**Comment by KingRaptor** [comment]
Reopen and modify if this still happens in 100.
