### ISSUE TITLE
ZeroKLobbyErrors.txt insanely huge

### ISSUE THREAD

**Issue by T-Lama** [ZeroK-RTS/Zero-K#612]
Just a week ago I found that Zeroklobbyerrors.txt is being many Megabytes in size, so I deleted it and it is now like 12MB just in 5 days.

All lines contains this message:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Threading.Tasks.Task<System.Runtime.CompilerServices.VoidTaskResult>' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at LobbyClient.TasClient.<OnLineReceived>d__a.MoveNext()

I am running 32-bit WinXP with exponen's compiled Lobby. Also, most of the games starting on 0.98 version crashes, dunno if it is tied to this case or not.

**Comment by xponen** [comment]
okay, will try to fix

**Comment by xponen** [comment]
hello @T-Lama  , can you redownload this http://zero-k.info/lobby/Zero-K_NET4.0.exe 

If the error disappear then I'll make post in forum telling others to download it too.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/537

**Comment by T-Lama** [comment]
I've been running it for quite a while and got no problem or crash whatsoever. It also detects game version correctly instead of forcing 0.91, so great improvement over the older one. Thanks!
