### ISSUE TITLE
New Widget: Constructor Seperator

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#622]
Problem: If you give your fac orders for combat units, it can cause problems with constructors that you want to treat differently. ie, if you give your fac fight orders for your combat units, your constructors by default will "fight" by helping the fac, which may not be what you want. You can get around this by using move orders instead, but this forces a compromise for combat units, which are better set on fight and which you might want to send somewhere further away than your constructors. This also causes problems for other widgets that can only give orders to constructors if they're idle.

Solution: A widget that 'catches' constructors as they complete and replaces their fac orders with a move order to a nearby rally (ie the default rally point). That way fac orders only apply to combat units (with the widget enabled) so you can give your fac whatever orders you want without worrying about what your constructors will do.

**Comment by xponen** [comment]
maybe you can try building this widget, or mention this idea in forum. There are people who love to make stuff. If they know all the technical stuff they will make it.

**Comment by GoogleFrog** [comment]
I don't think the complexity of this solution is worth the control benefit.

Complexity: Two types of rally point, one type is weaker than the other? It requires a new move button for the UI. How do you draw it? We already have Move and the Assist state toggle.
