### ISSUE TITLE
Reef is pushed by drones under construction in dev engine

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#623]
Possible fixes:
- make unpushable?
- make drones incapable of pushing while not finished?
- move drones further outside colvol so no pushing happens
- adjust reef colvol or sphere

**Comment by xponen** [comment]
IMO experiment with colvol offset
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Configs/drone_defs.lua#L16

hopefully it reset to default when drone is finish building.

**Comment by GoogleFrog** [comment]
The drones should be constructed outside of the hitvolume. This should always have been the case to make the AA interaction good.

**Comment by GoogleFrog** [comment]
Works in 98-451.
