### ISSUE TITLE
Team color nearly invisible in sea

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#637]
Team game battles are really hard to understand with default settings

http://i.imgur.com/gTCIEs5.jpg

**Comment by Anarchid** [comment]
Possible solution: teamplatters for submerged units? Or just teamplatters for everything?

**Comment by Licho1** [comment]
Also disabling seafloor shadow might help (or making it less visible, in the past it projected soft shadow on water surface instead).

And yes if we cannot fix rendering itself then teamplatters for submerged units might be best option..

**Comment by Pxtl** [comment]
Team-colored bubbles?

**Comment by dvr333** [comment]
Default-on x-ray shader? This is probably a good visibility idea in general, but doubly so for underwater from the looks of it.

**Comment by dvr333** [comment]
I've set up XRay Shader to be a lot brighter when it is underwater for Dynamic water and Bumpmapped water when BumpWaterReflections = 2 with #724. Not sure if that totally fixes things, but XRay Shader helps quite a lot anyway.
