### ISSUE TITLE
Visual part of bleeding edge ZK + 98.0.1-459 is broken on ATi (Windows)

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#646]
It looks like this:
http://snag.gy/MMDMh.jpg
http://snag.gy/PYx9R.jpg

Here http://zero-k.info/Battles/Detail/339609 and http://zero-k.info/Battles/Detail/339608

**Comment by Anarchid** [comment]
Do you get flicker?

**Comment by GoogleFrog** [comment]
Can you check earlier versions to find the commit that caused it? This looks like something to mantis.

**Comment by cleanrock** [comment]
From infolog:
[f=0000000] [Map Edge Extension] Error: Map Edge Extension widget: mirror shader error: Vertex shader failed to compile with the following errors:
ERROR: 0:17: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:18: error(#164) l-value required: assign "gl_Vertex" (can't modify an input)
ERROR: 0:31: error(#162) Wrong operand types: no operation "&&" exists that takes a left-hand operand of type "uniform highp float" and a right operand of type "uniform highp float" (or there is no acceptable conversion)
ERROR: error(#273) 3 compilation errors.  No code generated

Probably not the cause but i think you should make sure and look into it.

**Comment by lhog** [comment]
I've checked 98.0.1-459 with current ZK and experienced the same behavior. Engine is most likely one to blame. Surprisingly enough log doesn't hint of any OpenGL related errors.

**Comment by Anarchid** [comment]
Can you delete your cache(s) and/or run engine locally in isolation mode to see if this occurs?

If it does: Can you compile and check if https://github.com/spring/spring/commit/34f289c277d523c6eccbc74f185d2857bb56f948 is the first broken commit?

**Comment by GoogleFrog** [comment]
I made a ticket on mantis after a report form another player https://springrts.com/mantis/view.php?id=4715

Do what they want with DebugGL and respond.

**Comment by GoogleFrog** [comment]
Who is this? Respond! This is currently blocking the engine.

**Comment by lhog** [comment]
May I wonder why the ZK default version of the engine has gone past 451, although the issue is apparently not fixed: http://zero-k.info/Forum/Thread/14088

**Comment by Anarchid** [comment]
I'll revert back to 451 later today.

**Comment by sprunk** [comment]
Fixed: https://springrts.com/mantis/view.php?id=4715
