### ISSUE TITLE
disarmed sharpshooter doesn't get cloak back

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#652]
disarm sharpshooter with stiletto. After disarm is over, sharpshooter is uncloaked. You have to switch off / switch on cloak again to work.
Dunno if this applies to other cloaked units.
here an battle example. sharpshooters in the middle:
http://zero-k.info/Battles/Detail/340193 after 10 th min or so
edit:
min 22 disarmed sniper in mid

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/93878bc78aefca72358ca07fb8a993263b04e030
