### ISSUE TITLE
Some units don't shoot at things they should shoot

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K#653]
http://zero-k.info/Battles/Detail/340211

See group of scallops wandering around the geo and can't shoot it from the distance other than melee-like.

**Comment by GoogleFrog** [comment]
Cannot reproduce.

**Comment by lhog** [comment]
Can anyone else try? Cause I can do that 100% of time on that map.

**Comment by lhog** [comment]
Tested on ZK default 98+ and 91. The issue is engine version dependent:
http://zero-k.info/Battles/Detail/340653 (with LuaUI disabled)
http://zero-k.info/Battles/Detail/340655

I fail to understand how this could not be reproduced, since targeting & shooting must be synced.

**Comment by Anarchid** [comment]
Clearer instructions, maybe. A specific angle of attack.

My suspicion: Geothermal is an .obj; its aimpos could now reside very low on the ground; small terrain irregularities would be enough to obscure it from attackers with low firepoints.

This is, for example, why Gauss currently aims not from its gun, but from a special magical vantage point.

**Comment by lhog** [comment]
For me they shoot only when melee close and mostly to the corners of geothermal plant. It's easy to see in the replays attached previously.

**Comment by Anarchid** [comment]
I was able to reproduce it on Trefoil. Raising the geo midpos by 8 elmos fixed the issue.

The root cause is probably with the scallop and its low aimpoint, but it's an s3o.
