### ISSUE TITLE
Scythes won't get to range to attack fusions (98)

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#664]
Build scythe, order it to attack fusion, it closes in but stays just outside its weapon range.

**Comment by xponen** [comment]
Its pathfinding bug, I report here https://springrts.com/mantis/view.php?id=4721

**Comment by xponen** [comment]
closed because can't fix from here.

**Comment by xponen** [comment]
ops! un-close so that other dev can see!

**Comment by Anarchid** [comment]
The devs who need to be able to see this issue are engine devs, and all data is on mantis.
Closing.
