### ISSUE TITLE
Late-joiner's messages are not displayed in lobby

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#67]
When a spectator joins the game at a later time then their ingame chat messages are not displayed in the lobby by Springiee.

Example:
* Game starts
* 5 minutes later Skasi joins to watch
* Ingame Skasi presses Ctrl+Enter to write to all and says "Honk!"
* Tab out to lobby, Springiee did not forward the message

**Comment by GoogleFrog** [comment]
Infrastructure and quite unimportant.
