### ISSUE TITLE
Chicken Queen should fly directly into base without Fight-Command

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#688]
Queen just dies in front of every porc because it uses fight Command. It should fly in peoples main base and use fight command then. It would be much harder to kill it

**Comment by sprunk** [comment]
How would you define "main base"? What if someone has a lot of decentralized infrastructure?

One simple idea that would cover most practical cases for little cost is to have a list of priority targets that are a good idea to snipe (for example: Singularity and Moho-geo) and only do mindless Fight when there aren't any of those left.

**Comment by Anarchid** [comment]
Highest-value cluster of unarmed structures; xponen made optical cluster detection for CAI, so this can be reused.

**Comment by Jamanno** [comment]
Okay when its the easiest way. Then add pylons too for disabling ddm power shot and anni + behe. In general queen should focus on energy structures.
normally you haven't decentralised bases, most chicken games I played humans had one big base, so queen should fly behind power porc and do its job there and only blob his chicken kids there (you know queen spawns different chickens too at random).

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/44b7e61ce9abe3c5fe17a2a2ee296bd9e69a1751

**Comment by Jamanno** [comment]
that works niceley.
It is good to see how it ignores porc front line and just kills everything it finds in the back.
But:
- sometimes it just sits down near some solars and waits in back. it does not search explicitly for singus as it seems. (it should avoid digged singus though)
- it overflies geos or mohos e.g. on chicken nuggets

if you make a fix for that do not cancel the behaviour that it flies to the back, that is awesome. :)

**Comment by Jamanno** [comment]
maybe she could fly for geo spots after she is in base? Not sure how such search script would work

**Comment by sprunk** [comment]
Figure out some good target value assessment algorithm. Implementations especially welcome.
