### ISSUE TITLE
Remodel Battle and Strike comms

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#703]
These commanders are too OTA distinctive, even though their current model is original. They need remodeling before steam.

**Comment by Orfelius** [comment]
Armcom (strike chassie) is being remade by Anarchid already also it is worth to mention that armcom has only diffrent texture and it is still an OTA thing. Battlecom is a remake, altrough... it is not really that big of a deal that it is a bit alike to a core commander imho.

**Comment by Anarchid** [comment]
I intend to finish slimcom before this month is over.
