### ISSUE TITLE
Upsize cursors to power of 2

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#704]
All cursor images need their size increased to their next largest power of 2. This is because some graphics cards cannot deal with anything else.

The upscale should simply add a transparent border to the cursors, do not rescale. Also pay attention to the hotspot of each cursor.

**Comment by jk3064** [comment]
engine already handles that

**Comment by xponen** [comment]
@GoogleFrog how do we know its the power-of-2 problem? 
I found some script for Window's Powershell and ImageMagick program that could possibly automate padding all files into a square of power-of-2, but how sure its needed? 

useful script:
http://viziblr.com/news/2012/1/11/recursive-batch-image-conversion-with-powershell-and-imagema.html
http://www.fmwconcepts.com/imagemagick/tidbits/image.php#power2_pad

**Comment by sprunk** [comment]
assigning to self

**Comment by GoogleFrog** [comment]
jK has does the engine handle it in 98.0.1-451? We have reports of some cursors being invisible and the image sizes was a possible problem.

**Comment by jk3064** [comment]
hasn't changed, code is here:
https://github.com/spring/spring/blob/develop/rts/Game/UI/HwMouseCursor.cpp#L311

if at all you changed something, e.g. changed cursor images to something too large (some gpu drivers only support 48x48, some 96x96, and very rare do 128x128)

**Comment by xponen** [comment]
I checked all the cursor icon, all now have 32x32 or 64x64 as nearest power-of-2 size

Original size:
non-power-of-2 size for optional cursor set:
17x21
21x21
26x26
20x20
39x39
42x42

for zk set:
24x24
27x27
40x40
48x36
48x48

**Comment by xponen** [comment]
all cursor icon have been upsized to nearest pow-of-2
