### ISSUE TITLE
ingame camera broken

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#711]
mojjj at
http://zero-k.info/Battles/Detail/346138
using COFC camera.
on game start, camera is tilt to ground level and looking forward to the horizon. is this normal?
on click to factory icon/commander icon to select it, camera is adjusted in a silly way. whole image is somewhere not on the map, rotating is not bringing anything to view. tilt and zoom out to max brings back the map, and can continue normally from there.

Flipstip at
http://zero-k.info/Battles/Detail/346104
I had the same camera bug as DErankSoldiermojjj described in the icy run game, will post infolog tonight. Camera started out horizontally in the corner, pointing south. I thought it was a feature to show of the nice trees. At ctrl+C, the camera would move inside my com's head, and scrolling was extremely sensitive.

**Comment by dvr333** [comment]
The first one is fixed by #709, I'm not sure about the second one, though #709 will fix the camera start position bug, and probably fix the ctrl+c bug

**Comment by Flipstip** [comment]
My infolog:
http://pastebin.com/nZvDg2fj
At a certain point I pause the game and try to disable and re-enable camera widgets. I don't remember which widget it was, I think the COFC camera, it turned orange in the end iirc.

**Comment by dvr333** [comment]
Try using the beta/test server. Judging from the infolog stacktrace, you were playing on stable v1.3.4.2, and a lot has changed on the test build for COFC in the last couple days.

**Comment by Orfelius** [comment]
Looks like this one is fixed. Close please?
