### ISSUE TITLE
Jump commander teleports over map twice

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#720]
Upon landing after a jump order a jump commander teleported towards the other side of the map, getting stuck on a wind gen. After trying to move for a short moment it teleports again. **No Djinn was used** (because none were built).

Replay: http://zero-k.info/Battles/Detail/346786
Watch Coc_fr's commander slightly east of map center at 7:35 - 7:45 game time.

Attached is a screenshot I made shortly after it happened in a demo-replay. It includes a list of the commanders modules. I noticed that Coc_fr has been lagging almost the whole game (and games prior). Just pointing that out.

![teleporting commander bug](https://cloud.githubusercontent.com/assets/132906/7323552/a63aaf08-eaaf-11e4-9f7f-73f533347330.png)

**Comment by xponen** [comment]
Debugged that jumpy com. Found a triggers: morph.
I made a video because its really useful https://youtu.be/QdXHMfr3FfA

**Comment by Anarchid** [comment]
Reported fixed.
