### ISSUE TITLE
Permanent afterburner after error spam

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#721]
Screenshot showing error spam:
![screen00541](https://cloud.githubusercontent.com/assets/132906/7324796/ee2ca5d2-eab9-11e4-9913-679366b0a536.png)

Some seconds/minutes after making this screenshot I noticed that about half the Swifts in the game had a permanent afterburner speed bonus. Using afterburner again didn't remove the effect. Other players also mentioned perma slow-diving Ravens later, but I didn't really check for that.

Sadly the game didn't get recorded after people !resigned, they mentioned desyncs. I can provide a local replay file though if requested.

http://zero-k.info/Forum/Thread/14102 same game

**Comment by GoogleFrog** [comment]
I think this was fixed.
