### ISSUE TITLE
Add install instructions to README or INSTALL

### ISSUE THREAD

**Issue by krichter722** [ZeroK-RTS/Zero-K#731]
Please add/link instructions on how to process from source checkout to the usage of the game in the `spring` engine to `REAMDE.md` or `INSTALL`.

**Comment by GoogleFrog** [comment]
What do you want to build?

**Comment by krichter722** [comment]
Apparently there's no build process. Since there's no longer an installer/platform to play for systems which are not Windows which is the only platform supported by the version on steam (please don't do such severe disimprovements!), one needs to figure out a way to be able to play the game. The only hint is a link to https://springrts.com/wiki/Gamedev:Structure in README which suggests linking directories which which are no longer included in the repository.

**Comment by Anarchid** [comment]
> Apparently there's no build process. Since there's no longer an installer/platform to play for systems which are not Windows which is the only platform supported by the version on steam (please don't do such severe disimprovements!), one needs to figure out a way to be able to play the game. 

https://zero-k.info/Wiki/DownloadLinux

**Comment by sprunk** [comment]
He wants to build an `.sd7` or `.sdz` archive. This is not equivalent to just packing the repo because there are some extra steps involved (`$ sed -i -e 's/$VERSION/v1.2.3.4/g' modinfo.lua ; rm -r .git` etc)
