### ISSUE TITLE
Athenas sometimes don't call UnitIdle or UnitFinished when built

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#733]
This prevents autogroup from adding them properly, and the workers that were building the athena may continue to produce more athenas even though none were ordered. This doesn't seem to affect any of the units that athena itself can build, though.

**Comment by xponen** [comment]
this is probably a report about "Global Command" widget that you are working on. 

have you tried Spring.Echo("test") to confirm UnitFinished() wasn't called?  CBA seem to able to handle Athena properly.

**Comment by mtroyka** [comment]
Actually I think it's an issue caused by the unit mover widget, which I also have enabled. UnitFinished unfortunately doesn't give you any info about the builder, and since athenas can fly if they move out of the way then detecting what job a given athena represents becomes really difficult. I observed the same behavior with CBA. 6 Athenas queued produced 4 that remained on the queue after being finished, and after that there were two that remained on the queue after the first round of erroneous athenas were produced. Strangely enough CBA set all the builders to idle even though there were still 2 error athenas still shown as being on the queue.

Unfortunately fixing that would be rather difficult, and probably not worthwhile. :| I dunno about the weird CBA behavior though.
