### ISSUE TITLE
Autojump sometimes gets freakers stuck on buildings, and does not unstick them

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K#744]
I looked it over trying to see if I could find a way to fix it, however that only left me with more questions. I suspect the problem is with GetNearestObstacleEnterAndExitPoint, and I noticed that the variables x and z in that function are used without defining them locally, and I couldn't find anywhere where they were declared globally either. I'm also not sure why Spring.TestBuildOrder is used instead of Spring.TestMoveOrder, although there may be a good reason for that.

One thing I do notice though it that it seems to unstick recoms pretty consistently, but not freakers for some reason, maybe because they're smaller. Other units don't tend to get stuck in buildings regardless.

**Comment by GoogleFrog** [comment]
I don't care about autojump. Is jump itself broken?

**Comment by xponen** [comment]
@GoogleFrog ,this is just a non-default autojump widget jump too close to a build site,
Is harmless, no bug in Jump when it happen. 
Widget isn't smart enough to not jump to close into space where it queued to build stuff,.

**Comment by xponen** [comment]
@mtroyka , Spring.TestMoveOrder did not exist in Spring 91, so wasn't used. Maybe can use now

**Comment by GoogleFrog** [comment]
The gadget does not care which widget gives the jump command. If the widget can cause stuckness then the default UI probably has a bug too.

**Comment by GoogleFrog** [comment]
No response. I have heard no other report of jump causing units to stick.
