### ISSUE TITLE
Consider whether to make Solar force-close a part of the combat penalty

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#748]
Currently out-of-combat timers for repair bonuses differ:

* out of combat self-repair timers vary for each unit (typically 60s, but for some as low as 2s).
* out of combat constructor repair timer (for the x4 repair speed bonus) is constant at 10s.

Consider whether having one shared timer for both would be good.

+ + more intuitive
+ + makes one able to tell whether the con bonus is active based on the self-regen (no indication currently)
- - balance change: a nerf to constructor repair (especially against high-reload weapons where the x4 bonus could kick in between shots)

**Comment by GoogleFrog** [comment]
The bonuses are too diverse for this.

**Comment by sprunk** [comment]
Alright

**Comment by sprunk** [comment]
Consider whether to make force-closing of Solars a part of the combat penalty.
The practical effect would be close time 8->10.

**Comment by GoogleFrog** [comment]
No, it is just a thing that Solars do when they are hit. Similar to how Crabes curl up when they are static. Not everything has to take 10 seconds.

**Comment by Orfelius** [comment]
Thats what she said
