### ISSUE TITLE
Selection Shapes are drawn below all units.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#751]
Selections for air units are drawn below the selection for ground units.
![screen00201](https://cloud.githubusercontent.com/assets/1318249/7467003/13502304-f332-11e4-981c-39790f50839f.png)

Selections are occluded by parts of the unit that should be below the selection. This is most visible for mexes. Land mexes should not have a large base.
![screen00202](https://cloud.githubusercontent.com/assets/1318249/7467004/1fcd7186-f332-11e4-88eb-003a3d328619.png)

Allied selections do not merge with your own selection.

**Comment by GoogleFrog** [comment]
The second issue was fixed.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/94dd87fa69f1726daaa9058e54149915ada5b0e3
