### ISSUE TITLE
The ground texture disappeared after I pressed F1

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K#752]
See title. Sorry, I lost infolog.txt.

The simulation time in the battle was around 32:00 when it happened.

http://zero-k.info/Battles/Detail/348546

**Comment by GoogleFrog** [comment]
Try the latest engine.

**Comment by xponen** [comment]
same case as https://github.com/ZeroK-RTS/Zero-K/issues/605

**Comment by GoogleFrog** [comment]
Duplicate.
