### ISSUE TITLE
COFC jitter jumping

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#776]
Once in a while when I edge scrolling or zoom out the COFC goes highwire, starts to jitter showing outside of the map places and then it settles somewhere outside of the map. Then after input from mouse the camera goes into zoomed out position.

I have not been able to reproduce the bug as it happens randomly and I didn't manage to take a proof of it (yet) but as many of you know I have started recording games from my perspective recently so I hope to catch the bug on tape. I am just writing this ticket with hope that ShadowFury might know whats up.

**Comment by dvr333** [comment]
If you can find a way to reproduce, let me know. Also, what are your COFC settings?

**Comment by dvr333** [comment]
Check again with latest COFC. I'm pretty sure the tiltzoom rewrite fixed all the jitter issues.

**Comment by Orfelius** [comment]
I don't quite recall, what exactly was the issue. However I haven't been noticing any simmilar issues for some time. Closing.
