### ISSUE TITLE
lobby 1.3.2.65 aborts under mono when attempting to edit keybinds

### ISSUE THREAD

**Issue by jhoblitt** [ZeroK-RTS/Zero-K#792]
Attempting to access Settings -> Adv. Settings -> Edit keybinds causes mono to exit on a `sigabrt` with a colossal stacktrace.  I've dumped it into this gist: https://gist.github.com/jhoblitt/5b48243540dd1062dea2 instead of inlining it due to its size.

```
$ mono --version
Mono JIT compiler version 4.0.1 (tarball Wed Apr 29 08:44:01 BST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 21 (Twenty One)
Release:	21
Codename:	TwentyOne
```

**Comment by jhoblitt** [comment]
Would anyone like the core file?  It's ~111MiB.

**Comment by lhog** [comment]
LibreOffice's Writer has opened up for me. I have older mono version mono-3.12.1-1 though.

**Comment by jhoblitt** [comment]
@lhog The `xdg-open` command works and exits with status 0.  I've updated to the latest 4.0.1-4 build of mono and get the same abort.

This might be a mono/clr compatiblity bug, however, I know virtually nothing about the .net ecosystem.

**Comment by lhog** [comment]
@jhoblitt , what application did xdg-open open for you?

**Comment by sprunk** [comment]
This belongs in the infra section - continue any discussion in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/657
