### ISSUE TITLE
Widget/Gadget handlers use ipairs everywhere

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#816]
Apparently ipairs are expensive. Should that be changed to normal iteration or is keeping ipairs intended?

**Comment by xponen** [comment]
@GoogleFrog did a messy UnitPreDamaged() optimization, up to you if you want to impose that to all callins

**Comment by sprunk** [comment]
That optimisation is unrelated to the removal of ipairs (it exists to prevent calling the event for gadgets that declare they aren't interested) and is not even messy.

It could even be as tidy as it did before if the initialisation stuff actually happened on initialisation instead of checking for the first run every time.

**Comment by GoogleFrog** [comment]
I think you should run a test to determine the difference between ipairs and a manual iterator. I think tidyness is important for the gadget handler but I would also like to keep the difference between the basecontent handler and ours small. If there is no performance gain to be had with this change then I do not want it implemented.

**Comment by mtroyka** [comment]
About that, using normal iteration is faster, but only if the iterator is the most expensive part of a given loop. In other words, it only matters if the loop does 9001 iterations but has a cheap body. I experimented with it in my own code and never noticed a difference.

**Comment by xponen** [comment]
there won't be any way to prove it work because there's no gadgetHandler profiler.

**Comment by sprunk** [comment]
According to https://springrts.com/wiki/Lua_Performance normal iteration is twice as fast. The overhead is comparatively small in most cases however.

There are some call-ins that tend to have cheap bodies and get called a lot and so could benefit from the reduced overhead (for example Allow*BuildStep).

**Comment by sprunk** [comment]
Closing because any changes in the handlers are difficult to measure.
