### ISSUE TITLE
add repair award

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#818]
would be interesting to reward repairs. Like u can get Big Purple Hear but there isn't shown how many HP you repaired etc.

**Comment by sprunk** [comment]
Purple Heart tracks damage received so repairing your units already helps achieve that. Constructor repair is quite performance-heavy to track so while easy to implement it's something that needs to be carefully considered.

If the performance cost of tracking repair is not a problem then consider also extending the aircraft idle regeneration widget to also handle all idle regens and combat autoheal. This way all possible methods of health regeneration become known to Lua which has other uses than awards (eg.. it makes it possible to have a consisted method of conveying regeneration through the UI).

**Comment by Anarchid** [comment]
A repair award would be cool, but no cheap way of implementing such is known.
