### ISSUE TITLE
Consider constructor & caretaker morph

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#820]
At big and a prolonged game, ZK's constructor & caretaker could create an inefficient gameplay that's reminiscent of Balance Annihilation's metal-maker, where we spam caretakers or constructors to build stuff faster. Why do players need to do this? we should allow them to morph caretakers into a bigger & better caretaker with bigger buildpower instead.

This will optimize ZK to have less unit and less command during late-game gameplay.

**Comment by dvr333** [comment]
Wouldn't removing caretaker and constructor resource gain fix this problem in a much simpler way, while also fixing some resourcing transparency issues?

**Comment by sprunk** [comment]
As far as I can tell from #zkdev this is unrelated to the income problem; it is supposed to solve the problem of the AllowUnitBuildStep call-in being expensive by reducing amount of builders that can call it.

**Comment by xponen** [comment]
Yea, I'm referring to performance cost of having too much constructor/caretaker. I'm using Balance Annihilation's metal-maker as example of people wasting bandwidth by using widget to manage the economy by spamming off/on on their metal-maker farm.

**Comment by dvr333** [comment]
That just defers the problem, then. If you are trying to get performance by deferring performance issues (rather than trying to make the specific issue less of a performance burden) why not just limit game sizes and kill another bird with that stone?

**Comment by xponen** [comment]
I remember that Starcraft & Warcraft did something like: supply depot, or upkeep to limit unit. So we too should invent clever way to limit unit. 

Amazingly, ZK is already played using less unit than other Spring game (like Balance Annihilation, or NOTA), this is probably something to do with clever unit design than an artificial limit.

**Comment by sprunk** [comment]
Surely the best way to marginally improve performance is to fiddle with the balance of every constructor in the game. Kappa

**Comment by xponen** [comment]
Maybe if we double its HP, body volume, or special attributes, then it would be equivalent to an X amount of caretaker/constructor?

**Comment by dvr333** [comment]
ZK is played with fewer units partly because they are expensive (relative to resources) and partly because there are strong type counters, so it is really hard to keep an army alive when its counter comes in.=.

**Comment by GoogleFrog** [comment]
This isn't happening. You just confuse players with the morph interface and direct upgrade micro (similar to mex -> moho mex morph).
