### ISSUE TITLE
Report terraform issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#824]
Report issues instead of idly discussing them and hoping that they are read. Do not report the issues in this ticket, instead make a proper ticket.

**Comment by Orfelius** [comment]
Perhaps this should have been posted on the development subforum instead? or made a wiki page on github?

**Comment by GoogleFrog** [comment]
This way when/if they see the ticket they will be looking at the ticket system so making a ticket will be easy for them. A wiki page would take more effort and they are invisible.
