### ISSUE TITLE
Consider improved impulsejump as the default jump

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K#825]
It allow Jumper to interact with Newtons and other unit.

Definition of Impulse Jump:
Impulse jump is a jump where unit rely on Spring's skidding physic during jump. This add the ability for unit to register collision, bounces and other forces that come from gadgets or weapons. Enabling it will allow Jumper to interact with the world, such as with Newton push, without relying on extraneous LUA code.

Issues with Impulse Jump:
The issues is the fine balance between physic freedom (aka: free-skidding) or the on-rail nature of scripted motion (aka: MoveCtrl jump). Sometimes a decision has to be made to disallow push or allow bounce, to balance between unit controls and degrees-of-freedom. This balance is delicate & controversial but is adjustable.

Latest version (and rules): https://github.com/ZeroK-RTS/Zero-K/pull/812  
  - Push resist based on tank value: corsumo being largest and corfast being smallest
  - half bounce from feature collision

**Comment by GoogleFrog** [comment]
I said that your impluse jump caused units to bump each other off cliffs. You said that was intended.

**Comment by xponen** [comment]
Didn't happen for 10 jack...
![10corjackimpulsejumpcliff](https://cloud.githubusercontent.com/assets/2525365/8034817/00bdf20a-0e1e-11e5-9f88-e6509ebc34d2.jpg)

**Comment by GoogleFrog** [comment]
Edge.

**Comment by xponen** [comment]
Seems fine on the very edge with 2 corsumo... (see picture)
![2corsumocliffimpulsejump](https://cloud.githubusercontent.com/assets/2525365/8034967/6a3f6a82-0e1f-11e5-9f2d-8d0b97f755ae.jpg)

**Comment by KingRaptor** [comment]
1) Why did you change the test parameters?
2) Why are we issue open/close warring?

**Comment by xponen** [comment]
corsumo is bigger, also you know what happen to 10 jack on very edge, there's not enough space for unit to stand.
