### ISSUE TITLE
Music and all other in-game sounds aren't being turned off when window is minimized

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#835]
The subject. I'm playing && spectating in window mode, when spectating  I often need to minimize window and switch to other activity.
When I do so I have to manually turn off zk sounds, would it be possible to turn off them automatically when window is minimized?

**Comment by sprunk** [comment]
I think this belongs to engine.

**Comment by Anarchid** [comment]
This is both an engine issue and an OS-specific engine issue (sound abolition does happen on ubuntu for me).
