### ISSUE TITLE
Remove desync warning for specs

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#837]
It makes no sense to show desync warning of spectating player to players that are in-game
it leads to disturbance and sometimes causes people to !voteexit such games

**Comment by DeinFreund** [comment]
afaik games with desynced spectators currently count as desynced and will thus be ignored for elo and other stats.
as long as this is the case it makes sense to exit such games.

**Comment by Licho1** [comment]
Its not oossible to tell who is avtually desynced and who is correct there is no authority each client reports its view

**Comment by let4be** [comment]
@Licho1 it should be possible to hide messages that belong to spectators

**Comment by Licho1** [comment]
There is no way to tell who is desynced. Those messages are bogus. Single
desynced spec will report every other as desynced and we dont knowcwho is
reporting.
Dne 15.6.2015 11:22 napsal uživatel "let4be" <notifications@github.com>:

**Comment by let4be** [comment]
I perfectly understand this, I do not understand
why do I see a message "Noob12345 is desynced error in frame ######" while Noob12345 is a spectator and i'm playing a game
I suggest to hide desync messages that belong to Noob12345 because he is a spectator

**Comment by Licho1** [comment]
It can also mean that you are desynced and report him!! Really there is no
useful info in those except that someone in game ia desynced
Dne 15.6.2015 11:30 napsal uživatel "let4be" <notifications@github.com>:
