### ISSUE TITLE
Consider invalidate path cache for all players in-game and rebuild it if one of in-game players have staled path cache

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K#838]
Currently it leads to desync and causes people to wait, it would be nice simply to invalidate all caches and recalculate them.
Yes it would take time but it would auto-fix the problem for all players. Nobody knows how to manually remove staled path cache, it becomes especially important in light of future steam release.

**Comment by Orfelius** [comment]
As nobody has responded to this yet I might as well give my uninformed opinion on this.
This might belong into the mantis.

**Comment by sprunk** [comment]
Belongs to infra
