### ISSUE TITLE
Initial queue start position type interaction

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#851]
Initial queue references the engine start position type.
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_initial_queue.lua#L215

Does this reference need updating? Should it be removed? Will initial queue work under all three new start position options (it should because each has players know where they are going to start).

**Comment by sprunk** [comment]
Springie always sets startpos type to 2 (ie. pick ingame) so this check can be removed.
Initial queue will work normally under the new system because the shuffler only touches boxes and not startpositions themselves.
