### ISSUE TITLE
Mex explosion has drill attached to gib in 98-829

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#857]
When mexes are overkilled in 98-829 their top gib has the drill attached. It looks quite bad. The engine gained the ability to make gibs which bring their children with them and the mex is apparently doing that.

The fix is to rewrite the script in lua. That will probably fix the issue because then the explode flags will be set correctly.

**Comment by sprunk** [comment]
Assigning self
