### ISSUE TITLE
Regression: priorities don't respect constructed unit priority

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#860]
1) have singu
2) have cons assist it
3) set singu to low priority
4) have factory on normal with nanos assisting it as a "load"

Expected outcome: singu is built only if factory+assists work at full speed
Actual outcome: singu is built with cons spending about the same as lab/nanos

This is a regression, it used to work properly.

**Comment by GoogleFrog** [comment]
Cannot reproduce. Replay?

**Comment by Licho1** [comment]
http://zero-k.info/Battles/Detail/360021

**Comment by GoogleFrog** [comment]
At 15:49 you had 23.1 metal income. Drain:
 * 15? high priority BP comm morph.
 * 10 normal shipyard
 * 10 low nano turret
 * 7.5 normal Mariner on low Singu

14.2 drain from morph.
6.7 drain from factory.
1.3 drain from nano turrets.
1 drain from Mariner

The commander drain fluctuates around 14.2 to 15. There is a bug here but it is to do with high priority morph failing to grab enough metal from lower priority things. Priority inheritance works fine.

**Comment by GoogleFrog** [comment]
Morph gadget still thought that the economy updated every 32 frames instead of every 30 frames when telling priority how much the morph will drain. This caused priority to set aside more metal for morph than it allowed morph to use (because morph would ask for metal in properly sized chunks). This left some metal leftover for the lower priority constructions to use.

**Comment by Licho1** [comment]
I'm not so sure later I assisted singu top right and swapped fac nanos to normal and it didnt help both were draining same

**Comment by GoogleFrog** [comment]
This may have fixed that. I have added some debug information regardless. Say if it happens again with something later than v1.3.6.3

https://github.com/ZeroK-RTS/Zero-K/commit/58abcc2e113e5573863e5ead4259d95165bbec8b

**Comment by sprunk** [comment]
>6.7 drain from factory (normal)
1.3 drain from nano turrets (low)
1 drain from Mariner (inherited low)

Should Low receive any resources at all if Normal isn't working at full power?

**Comment by Licho1** [comment]
No, low priority is meant to get 0 if there are still not excessing normal
priority constructions..

2015-06-21 23:16 GMT+02:00 sprunk <notifications@github.com>:

**Comment by sprunk** [comment]
I think that was caused by the morph error which is already fixed though.

**Comment by Licho1** [comment]
I dont see how that can cause any drain for low though but ok..

2015-06-21 23:33 GMT+02:00 sprunk <notifications@github.com>:

**Comment by sprunk** [comment]
See earlier comment: https://github.com/ZeroK-RTS/Zero-K/issues/860#issuecomment-113730044
