### ISSUE TITLE
0HP leviathan! skuttle jump target not working on reef

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K#862]
http://zero-k.info/Battles/Detail/360169

#skuttle on reef and leviathan killed both but left the levathan at alive at 0 HP. (dunno if it was still able to move or take action as i had no vision after that and we lost -.-)

anyway, skuttle refused to jump sea, targeted shallow water edge at terraformed canal. isnt this supposed to be working, to jump enemy units? i mean ok leviathan is under water, but reef was also not able to be jumped on.

**Comment by sprunk** [comment]
Skuttle can't jump on enemy units if they are on unpathable terrain (like cliffs, or water) and never could.

Will look at the Leviathan.

**Comment by KlonZK** [comment]
would be a cool feature to have skuttle be able to do that tho (kinda makes sense now that it can jump into anything)

**Comment by sprunk** [comment]
Replay from site is broken for me. Got a working local replay?

**Comment by mojjj** [comment]
https://www.dropbox.com/s/3zd38bm5leavdut/20150620_230654_Verdant%20v4_98.0.1-451-g0804ae1%20develop.sdf?dl=0

**Comment by sprunk** [comment]
Fixed in https://github.com/ZeroK-RTS/Zero-K/commit/37925d1fc6358b5133e8ae0e442a435418e69c68

**Comment by mojjj** [comment]
nice wok!

**Comment by CarabusX** [comment]
Should be marked as fixed if it really was.

**Comment by Anarchid** [comment]
^
