### ISSUE TITLE
Win counter suddenly stopped working reliably

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#866]
The win counter seems to always give player 1 the win, since 1.3.6.0.

Testing out the code, it looks like Spring.GetTeamInfo is returning "true" all the time as its "isDead" return value, but that only happens in 1.3.6.0 or later. Testing with 1.3.5.1 shows no issue, and players are correctly marked as winning. Not sure if this is an engine bug, but both game versions were tested with 98.0.1-451 and exhibited different behaviour.

Note that testing involved modifying the win counter code slightly to check the isDead status from all players/teams.

**Comment by GoogleFrog** [comment]
Try 1.3.6.5 or later.

**Comment by GoogleFrog** [comment]
I played some 1v1 with 1.3.6.5 and lost as player 0 and it seemed to work.
