### ISSUE TITLE
widget:GameOver and gadget:GameOver doesn't seem to process input from game_over.lua

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#867]
Related to #866.

Despite game_over.lua having an explicit call to Spring.GameOver with the winning allyteams as the parameter, neither the widget nor gadget GameOver callin seems to have that. Possibly an engine bug, Not sure what to test for that.

**Comment by GoogleFrog** [comment]
There could be some sort of order effect in the engine which causes isDead to not be set fast enough. Regardless, it is easily replaced by teamRulesParams and has already been done. https://github.com/ZeroK-RTS/Zero-K/commit/450523d6bef216c9eb6b830191d4df5edb1cff05
