### ISSUE TITLE
insane pathfinder lag when trying to reach positively inacessible terrain

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K#874]
that is, terrain that the selected unit(s) just cannot go, such as very steep hills for bots etc, or when moving at the edges of such areas (for example, when trying to move a shieldball through the hills on spiders web). the more, the merrier. did not happen with older game version,but happens in all versions since first tests with new engine versions a few month ago. 

probably has been reported in some way or another and not sure this even is the right place, but came to my mind and i wonder if this is a well known issue / if this happens to everyone?

**Comment by GoogleFrog** [comment]
There is little useful information here. At least provide a replay link. The best thing would be to make a small replay where you reproduce this problem.

**Comment by abma** [comment]
fixed in 98.0.1-692-gd9f51e3
https://springrts.com/mantis/view.php?id=4765

**Comment by KlonZK** [comment]
in case its still needed:

http://zero-k.info/Battles/Detail/360808

steps to reproduce:
- built a lot of units with limited move type
- give move order somewhere they cannot go at all

**Comment by Anarchid** [comment]
The linked game was on engine 98.0.1-451, so would indeed be fixed  in 98.0.1-692-gd9f51e3.

Reopen if possible to replicate in versions newer than that.
