### ISSUE TITLE
MonoDevelop fails to load ZK infra

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K#875]
It gives an error along the lines of "Unknown ToolsVersion '12.0'". Opening the .csproj files and changing ToolsVersion to 4.0 works around the issue.

Related link: [Unknown ToolsVersion '12.0'](http://forums.xamarin.com/discussion/12066/unknown-toolsversion-12-0)

**Comment by maackey** [comment]
Is this really a bug with the infrastructure project though? 

"FWIW XS 4.2.3 will support reading ToolsVersion 12 files"

It looks like the new version of XS will support the new files. The same error occurs in older versions of VS too.

**Comment by KingRaptor** [comment]
The project working with new versions of Xamarin would be more relevant if we were developing using Xamarin (AFAICT it's only for developing mobile apps, and it isn't free anyway).

**Comment by abma** [comment]
isn't this issue-tracker for the game only? 
should go to https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues imo

**Comment by KingRaptor** [comment]
Oops. (thanks abma!)
