### ISSUE TITLE
Unit_CMD_RETREAT - Desync

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#877]
Had a game where I desynced because Unit_CMD_RETREAT errored out. Said it "called too many times without a second augment. Check your script, this may lead to memory leak!"

Game: http://zero-k.info/Battles/Detail/360880

Details: Occured after swift fight. Top right corner.
Time: [f=0024187] Sync error for Shamanpluk in frame 24170 (got a79b3290, correct is 727b2944)
is when it occured.

**Comment by GoogleFrog** [comment]
That would not cause desync and was not even an error. Post your infolog for the retreat warning.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/e66b57fbaa043684b703ec514207f94f87c1f533

**Comment by ArchShaman** [comment]
Well that was fast. I just finished the replay to get the infolog.
