### ISSUE TITLE
Terraform Hijinx

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K#878]
Apparently terraforming a pillar (1x1 or 2x2, just enough for a firewalker to get put on) high enough will make it get stuck in the ground if it attempts to fire at a wrong location.
 or something. Not even sure how to replicate this... but it becomes practically untargetable I think...
See: http://zero-k.info/Battles/Detail/360792

A picture of the epic fail:
![screen00216](https://cloud.githubusercontent.com/assets/7841201/8373407/49fe97fe-1ba1-11e5-8342-b88ba32eeffc.png)

(Skip most of it until Dr0ppy starts building the terra tower)

**Comment by GoogleFrog** [comment]
I don't mind that some units have trouble firing if they get stuck in really impassible terrain.
