### ISSUE TITLE
manually set targets removed frequently

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K#888]
*edit: there doesnt seem to be a bug here, read below comments first*

the requirement for this seems to be that a target unit is in radar range, but not vision. also possible that the transition between radar and vision causes it to happen. 

1: use set target on a unit
2: be in radar range, but dont have visuals on the unit (possibly walk at the edges of vision such that the unit may briefly enter it)
3: be in firing range or not, does not seem to matter
--> target will be lost after short time

http://zero-k.info/Battles/Detail/361961

happens a couple of times in this game in my area (northwest corner). i set my shieldball to target various stingers and other defenses in order to disarm them via racketeers, but the target was frequently removed and they started shooting random other stuff, much to my dismay. radar visible all the time and in firing range most of the time as well.

**Comment by lhog** [comment]
Apparently @KlonZK used STOP several times and STOP cancels target. Actually I tried few commands and most of them cancel "set target": state change (fire state, repeat state, overkill state, move state), also fight command. My conclusion might be wrong, but seems like "set target"  only survives CMD.MOVE commands.

**Comment by KlonZK** [comment]
stop breaking target seems to be a rather recent addition and i think its a terrible idea.

- it is vital that people can use stop to stop unit movement while maintaining the target, if target breaks even for a short time it can have dire consequences (wasted shots, turrets turning for that extra second, etc). 

- people may not even notice that their units shoot at other targets instead the one that they explicitly ordered them to shoot (like me, for the last two weeks. that explains a couple of odd situations where units failed to do their job for seemingly no reason)

- there already exists an explicit "remove target" command, anyone who actually uses set target knowns about this.

- people who dont know about this but used an attack order earlier (that also seems to set target?) may be annoyed that units start shooting at random other targets of preference when they order their units to just stop (their movement)

**Comment by GoogleFrog** [comment]
People would be annoyed that their units are shooting something which they set as a target in a previous battle. I think the default behaviour is fine. You want an option beyond turning off the widget.

**Comment by KlonZK** [comment]
people dont necessarily order STOP at any point after a previous battle. in fact, they probably dont, if they are just moving around their units from point A to point B. there is a good chance however that people use stop during micro. 

unless people know about this, and explicitly use/ avoid using stop (which is bad, because stop does things in micro that you cannot do otherwise), outcomes will be effectivly random. 

since people have to know about this behaviour to utilize it, have to explicitly use stop to remove targets, and there is a seperate command for which both of these things also apply, but that does not trigger unwantedly and also does not break micro, why not use that instead?

also, what widget?

**Comment by GoogleFrog** [comment]
Changes to make:
* Make firestate, movestate etc.. commands no longer clear target.
* Add two options to Game/Target AI submenu. Botj are enabled:
  * Keep removed attack command as a target
  * Stop commands cancel target.

**Comment by KlonZK** [comment]
nice.

**Comment by GoogleFrog** [comment]
That makes no sense, what is 'nice' at?

**Comment by GoogleFrog** [comment]
The default settings aim to implement the following behaviour: Units "remember" that you wanted them to attack a particular target even after given a move command.

**Comment by KlonZK** [comment]
nice is at  "Add two options to Game/Target AI submenu....", which is to say, i appreciate that. 

imo the default should be the way it used to be, that is, stop doesnt clear target.

**Comment by GoogleFrog** [comment]
Stop option exists.
