### ISSUE TITLE
Friendly fire!

### ISSUE THREAD

**Issue by pyrothraxus** [ZeroK-RTS/Zero-K#894]
Felons have been doing friendly fire! shooting stationary and moving allies with their fast attacker!
Killing things like fusions and other felons.

Test with maken a group of felons, 

Send into battle, watch them suicide each other...

**Comment by GoogleFrog** [comment]
I mostly fixed the problem by moving the aim point of Felon to between its shooters. Previously the aim point was a the top of the shield (for legacy reasons) and the location of an aim point should be irrelevant for the unit.

There are still some edge cases https://springrts.com/mantis/view.php?id=4883

**Comment by Orfelius** [comment]
More documented case #1091

**Comment by GoogleFrog** [comment]
I cannot make Felon kill an ally with sustained fire. I can only manage to make one fire a single shot at the ally. After the single shot the Felon is blocked from firing. Therefore we are not going to get a case where the Felon bursts down an allied Fusion. I'm calling this fixed.
