### ISSUE TITLE
Hovers (and probably ships still too) movement on shores weird in "new engine"

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#897]
For some months (ie not just the latest engine change) ships and hovers have some weird acceration-bug when moving very close to shores. Their movement seems very artificial and doesn't really respect their facing.

This is extra frustrating on hovercraft because many supported and featured maps have shores where hovers have an awful time pathing. When ordered to turn around and retreat while doing this they instead go even further and suicide because of the acceleration before they are able to fully turn around and move back.

**Comment by GoogleFrog** [comment]
This is fine. The alternative is probably that they would get stuck in terrain.
