### ISSUE TITLE
Units move without visible orders

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K#900]
See Hammers on the southern side at 9:50 of http://zero-k.info/Battles/Detail/362225
After killing a bit of porc they keep moving forward even though they are set to hold position and don't show any active orders.

**Comment by GoogleFrog** [comment]
They lost sight of their target so moved such that it would come back into range. Their target was an unreachable radar dot which then disappears because a radar tower was destroyed. This looks intentional to me.

**Comment by Skasi** [comment]
Is there a way to disable this behavior?
