### ISSUE TITLE
Builder refuses to reclaim

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#901]
http://zero-k.info/Battles/Detail/362231
Commander is unable to reclaim a mex wreck (at the bottom, has multiple markers).

**Comment by ArchShaman** [comment]
Had issues like this myself, only cons forget to build stuff, they'll finish it to 1-2% (without q command) then move on to the next thing they had planned. Seems rather random.

**Comment by GoogleFrog** [comment]
Follow mantis and then possibly make a report.

**Comment by GoogleFrog** [comment]
ArcchShaman make a proper for your issue.
