### ISSUE TITLE
Map extension on Titan Duel shows green dots

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#911]
http://i.imgur.com/0O2My0e.png

Seemingly with newest engine and some 98 dev versions TitanDuel's map extension shows up these dots that I suspect might be a reflection of stock engine metalmap (the one used by BA for example).

**Comment by GoogleFrog** [comment]
Look up, I am fairly sure that these are stars reflected from the skybox.

**Comment by Orfelius** [comment]
Apperently you are right. However west, north and north-west boxes have no reflection for some reason.
