### ISSUE TITLE
Chat widgets drop inputs

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K#915]
The chat widgets, or at least everything but the old Console, have a nasty tendency to unpredictably drop inputs when typing. I'm not sure if this is engine-level or widget-level, but I don't recall it happening with Console, but it happens often with Proconsole.

If it also happens with Console and with no widgets at all, then close this and I'll mantis.

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=4690

**Comment by GoogleFrog** [comment]
https://springrts.com/mantis/view.php?id=4690

**Comment by kaen** [comment]
https://springrts.com/mantis/view.php?id=4690#c15104

**Comment by dvr333** [comment]
This still happens.

**Comment by sprunk** [comment]
Duplicate of #1367

**Comment by GoogleFrog** [comment]
No, #1367 is a particular proposed solution. There are other ways to resolve the issue.

**Comment by GoogleFrog** [comment]
Fixed in engine around September 2016.
