### ISSUE TITLE
0 damage hit

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K#919]
http://zero-k.info/Battles/Detail/363079 about 5:15, Moderator hits a Warrior doing 0 damage.

Picture with hitboxes: http://i.imgur.com/VXqNPWO.jpg

Note how the beam doesn't reach the gray hitsphere. I think this is engine-related but:
1) ZK fiddles with impactOnly beamlasers to make them have microscopic AoE -- perhaps the AoE could not reach the hitsphere in this case?
2) perhaps ZK could also workaround the problem by messing with the gray hitbox sizes?

**Comment by GoogleFrog** [comment]
Make sure that the beam hit, if it does then post on mantis. If a projectile hits a hitvolume then it should deal damage, regardless of what the grey sphere is doing.
