### ISSUE TITLE
MASSIVE fail in economy

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#926]
Suddenly all people in team started to be getting very small ammount of metal, not even base mex income (which was 70) ..

http://i.imgur.com/E3fPo7H.jpg

Basically broken game. 

http://zero-k.info/Battles/Detail/363429

Game self fixed just seconds before our resign vote passed.

**Comment by CarabusX** [comment]
Happened again in http://zero-k.info/Battles/Detail/363588 for south team.
Income of every player in the team fluctuated, one second it was normal, then the next one it was only +4M or +5M, then normal again, etc.
