### ISSUE TITLE
Outlaw pulse is outlined by a solid thick line

### ISSUE THREAD

**Issue by beamer159** [ZeroK-RTS/Zero-K#927]
The problem can be seen in this screenshot:

http://i.imgur.com/71BciTl.jpg

The problem is caused by a setting in lups,cfg. One of my lines was the following:

//DistortionCopyDepthBuffer = true   // do depthtest? (can increase performance if turned off)

I changed this line to the following:

DistortionCopyDepthBuffer = false   // do depthtest? (can increase performance if turned off)

This change fixed my issue, seen here:

http://i.imgur.com/vqXwdTR.jpg

This line is automatically set "correctly" only for the Low graphics preset. All other presets write the line which gives me the graphical issue.

**Comment by ArchShaman** [comment]
This belongs in Infra.

**Comment by KingRaptor** [comment]
What graphics hardware are you using?

Try updating drivers, etc. etc.

**Comment by ArchShaman** [comment]
http://pastebin.com/s8xJ815n this should help.

**Comment by GoogleFrog** [comment]
Fixed by changing lups.cfg

DistortionUpdateSkip      = 1      // must be larger zero (larger := better performance)
DistortionCopyDepthBuffer = false   // do depthtest? (can increase performance if turned off)

Old: http://pastebin.com/v0D7v4mV
New: http://pastebin.com/JTksKtUh
