### ISSUE TITLE
Playerlist doesn't display metal and energy income properly

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K#952]
The values displayed are untrue. This is a problem both for spectators and team players since there is not a good way to tell the eco numbers of your teammates.

**Comment by GoogleFrog** [comment]
Attach a replay with a time. An explanation would be good too.

**Comment by Anarchid** [comment]
This seems to come from the overridden balance-bar widget, which is implicitly not supported. Afaict, latest iteration of default eco widget does not experience the issue.
