### ISSUE TITLE
units of resigned player are given to another already resigned player

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K#959]
1) highest elo player resigns
2) another player resigns also
3) third player doesnt get 2nd players units, instead they are transfered to the resigned player 1 (his teamcolor, but "noname")

http://zero-k.info/Battles/Detail/369029

/take didnt seem to work (because removed entirely?)

**Comment by sprunk** [comment]
Lagmonitor was recently rewritten. Reopen if still happens.
