### ISSUE TITLE
Attrition counter problems

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#967]
Attrition counter crashes in CAI 2v2 CCR. I looked at its team detection code and could not figure out what it was trying to do. Also "Your Team" and "Enemy Team" is bad for spectators.

Additionally, it sometimes voluntarily disables itself when playing 1v1 due to failing to detect an enemy team.

Look at the spectator panels widget to do better team naming and detection.

**Comment by GoogleFrog** [comment]
[CAI 2v2 CCR.txt](https://github.com/ZeroK-RTS/Zero-K/files/1318/CAI.2v2.CCR.txt)

**Comment by Anarchid** [comment]
Ostensibly fixed in #1049

**Comment by Anarchid** [comment]
Clansmen detection breaks it.
```
[f=0014901] [cawidgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_attrition_counter.lua"]:234: attempt to index field 'clanNameLengthCutoff' (a nil value)
[f=0014901] [cawidgets.lua] Error: Removed widget: Attrition Counter
```

**Comment by CarabusX** [comment]
It crashes in local game vs nullAIs.

[f=0000000] [cawidgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/gui_attrition_counter.lua"]:170: attempt to index field 'aiNames' (a nil value)
[f=0000000] [cawidgets.lua] Error: Removed widget: Attrition Counter

(my local ZK repo is about week old so could have been fixed already)

**Comment by KlonZK** [comment]
the data table that is used in line 170 doesnt exist, it is only declared in the other block of the if-clause (the not-ai case).

**Comment by sprunk** [comment]
Should be fixed by the recent team name changes.
