### ISSUE TITLE
Rezzed units with initial states set to Inherit, start with unwanted states

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#979]
Imagine the following situation:
Raven has initial states of Fire State and Fly/Land set to Inherit (from factory).
Airplane factory has these initial states set to Hold Fire and Fly.

This means that without touching the states all your Ravens will be Hold Fire and Fly.
But if you rezz yours or enemy Raven from wreck its states will be Fire At Will and Land, which are the engine defaults. These are kinda unwanted.

**Comment by CarabusX** [comment]
For units that got rezzed and not produced by factory I would suggest iterating the buildorder tree upwards and finding the first unit whose state is not set to Inherit and grabbing that.

**Comment by KingRaptor** [comment]
Fixed in https://github.com/ZeroK-RTS/Zero-K/commit/94a497712fab0cd2da2b6bcfd5b3a740963944f8

Thanks for the proposal on how to fix, was helpful!
