### ISSUE TITLE
"Player X resigned" message does not show in chat or log

### ISSUE THREAD

**Issue by CarabusX** [ZeroK-RTS/Zero-K#983]
Unlike #772 it seems to be engine issue in Spring 100.0.
"Player X resigned" message doesn't show up in Chili Chat, in engine console, or in infolog.txt even with /luaui disable and /luarules disable, which suggests the engine doesn't output the message at all.

Would be nice to have the message again as it is useful to know when the player you fight resigns, especially in FFAs.
Likely needs to be Lua'ed using PlayerChanged callin.

**Comment by sprunk** [comment]
/luarules disable will disable the message because it is done through Lua.

**Comment by CarabusX** [comment]
They don't appear without '/luarules disable' either.

**Comment by CarabusX** [comment]
I saw "Player X resigned, giving all units to player Y." or similar message in teamgame today.
It is possible that "Player X resigned" message is only missing when the player is last in his team (for example in FFA).
