### ISSUE TITLE
WARNING NUKE LAUNCH, moves chat window or whatever on top of screen is

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#989]
yeah. the warning bar interacts with well arranged gui.

**Comment by GoogleFrog** [comment]
Then move the nuke launch window somewhere else? It does not do this with the defaults.

**Comment by Jamanno** [comment]
just thought about why it cannot be overlaying? It is no deal for me to move it, but some may wonder why gui arrangement changed. :)

**Comment by ArchShaman** [comment]
It's hard to move it honestly. The box to move it only shows up when it does.
