### ISSUE TITLE
pause game after game ended and take screenshot

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K#991]
1) it lags always when everything self destructs.
2) Why not take a final screenshot from final game?
Could be used on website

**Comment by Anarchid** [comment]
I'm confused whether this is a feature request or a bug report. 

Even so, self-destructing a few hundred units at the same time will probably be taxing on performance unconditionally and irreparably, and not blowing up the losing side loses a very perceivable feedback on who won.

If you have multiple issues, create multiple tickets.
