### ISSUE TITLE
(v1.3.8.10) startboxes did not disappear at start of match

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K#994]
in the last few matches as player the startboxes + playermarkers did not disappear at start of game.
see picture, there is units plus boxes+markers.

![bla](https://cloud.githubusercontent.com/assets/3044855/9323043/585d89ea-457c-11e5-9bad-104accc73380.jpg)

**Comment by GoogleFrog** [comment]
Got a replay or infolog?

**Comment by GoogleFrog** [comment]
No replay or infolog still? The startbox API and drawing system has changed since then and I have not heard of this bug from others. See if it still occurs.
