### ISSUE TITLE
Chili rejoiining bar fails to appear

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K#997]
Was FFA game, widget was running (restarting it didnt help). 
I dropped due to crash and was rejoiining

**Comment by sprunk** [comment]
No infolog or replay.

The rejoin bar used to do weird unreliable things (like [ask other players for their OS clock time...](https://github.com/ZeroK-RTS/Zero-K/blob/775b09891fd5df79b7ff65810b1d2534c57abf1a/LuaUI/Widgets/gui_chili_rejoin_progress.lua#L365)) and I rewrote it recently (https://github.com/ZeroK-RTS/Zero-K/commit/ffae760e0a36c432bef22328ee60ff8fd2f65d1a) which hopefully this fixes the issue.
